### ISSUE TITLE
IoT connection issues on packet loss.

### ISSUE THREAD

**Issue by steelzeh** [aws/aws-sdk-ios#1002]
* **What service are you using?**
IoT

* **In what version of SDK are you facing the problem?**
2.6.25

* **Is the issue limited to Simulators / Actual Devices?**
Only tested on actual device

* **Can your problem be resolved if you bump to a higher version of SDK?**
No

* **Is this problem related to specific iOS version?**
No

* **How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?**
Carthage

* **Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.**

After the connection to a socket has been established, if there is a packet loss for an extended period of time the MQTT session is closed without notifying the user, this results in a disconnected socket where the status of the socket is still connected.

1. Start the IoTSampleSwift app and connect to socket on both devices
2. Enable packet loss via Network Link Conditioner under iOS Settings -> Developer
3. Wait for around 2-3 minutes with packet loss.
4. Suddenly this is being logged to console:

<img width="860" alt="screen shot 2018-07-23 at 13 01 00" src="https://user-images.githubusercontent.com/7465835/43073046-7e9c77cc-8e78-11e8-8aa2-5c2875617f78.png">

MQTTSessionEventConnectionClosed: MQTT session closed.

If you try and fetch .getConnectionStatus now it will return 2 = connected.
Nothing is notifying the user, the connection just gets terminated.

In another case the SDK never realises that the connection is lost, and when you disable the Network Link Conditioner no data comes through the socket.

So sometimes the sdk continues to say ClockTickXXX for an unknown time and the stream is never closed, other times after an extended period of time the stream is closed and the reconnectTimer is never initialised because in initiateReconnectTimer it checks if the mqttStatus != connected, but mqttStatus is never set to anything other than connected in MQTTSessionEventConnectionClosed siwtch case unless userDidIssueDisconnect is true.

@cbommas

**Comment by cbommas** [comment]
@steelzeh 

Thank you for reporting this issue. I will investigate and get back to you.
Couple of questions
1) In the first case, where the connection error is being reported, are you seeing the connection being retried and established again?
2) Can you share what you have setup in the MQTT Configuration for  retry and keep alive.

**Comment by aat2703** [comment]
@cbommas any news

**Comment by cbommas** [comment]
@steelzeh @aat2703 

I am looking into this and if all works out, will target this to be included in the next rev of the SDK.
Will keep you guys posted.

**Comment by steelzeh** [comment]
Alright thank you @cbommas

**Comment by cbommas** [comment]
@steelzeh, @aat2703 

The latest rev of the SDK (2.6.26) contains this fix. Please try it out and let us know how it goes.

**Comment by steelzeh** [comment]
@cbommas we were running our own forked version as we didn't want to wait 10 days for the update to be rolled out.

But it seems to have fixed our issues.

**Comment by cbommas** [comment]
@steelzeh

Thank you for confirming. I will go ahead and close this issue. Please reopen if you encounter further issues.
