### ISSUE TITLE
AWSUserPoolsSignUp should be able to disable/remove optional fields

### ISSUE THREAD

**Issue by kklobe** [aws/aws-sdk-ios#1005]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito User Pools built-in UI

* In what version of SDK are you facing the problem?
2.6.25

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Configure a Cognito User Pool (General settings / Attributes) to make phone number optional. The Sign Up UI then gives no indication to the user that it's optional, nor is there a way to remove the field from the UI. There should be a way to indicate that a field is optional, or remove it entirely using the AWSAuthUIConfiguration object.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
@kklobe Sorry for the delayed response. I will take this as a feature request to the team. For complete control and customization of the SignIn, you can build your UI on top of the AWS Cognito UserPools SignIn SDK. https://docs.aws.amazon.com/cognito/latest/developerguide/walkthrough-using-the-ios-sdk.html
