### ISSUE TITLE
Set request timeout

### ISSUE THREAD

**Issue by yefan813** [aws/aws-sdk-ios#101]
My question is ,when I use  "AWSDynamoDBObjectMapper" to delete a item in table, how can I set the timeout.  if the network is too slowly,I need wait for too long before enter the Block.

    peopleUp.puuid = @"dsdsdssads";
     peopleUp.pdate = @"11-11-2014";
    AWSDynamoDBObjectMapper *dynamoDBObjectMapper = [AWSDynamoDBObjectMapper defaultDynamoDBObjectMapper];
    
    [[dynamoDBObjectMapper remove:peopleUp];
     continueWithExecutor:[BFExecutor mainThreadExecutor] withBlock:^id(BFTask *task) {
         
         if (!task.error) {
 
         }else{
             
             NSDictionary *userInfoDic = task.error.userInfo;
                   
         }
         return nil;
     }];

**Comment by ataranlen** [comment]
I'd also like to request that this be implemented.

**Comment by confucious** [comment]
I also would like to request for this.

**Comment by inlinestyle** [comment]
This would be very helpful for us, especially so we could bail out from a stalled request in a timely manner.

**Comment by yosuke-matsuda** [comment]
`AWSNetworkingConfiguration` (a parent of `AWSServiceConfiguration`) has two properties, `timeoutIntervalForRequest` and `timeoutIntervalForResource`. You can set these properties to update the timeout settings. Thanks.

**Comment by inlinestyle** [comment]
Thanks for the info! Now I can see that those will just default to the `NSURLSessionConfiguration` defaults, which is what we wanted.

**Comment by swl367** [comment]
@yosuke-matsuda  sorry, another question. Even if I set the two timeoutIntervals on the AWSServiceConfiguration, this code seems to be overriding the invoke request on iOS currently:
```
@implementation AWSAPIGatewayClient

- (instancetype)init {
    if (self = [super init]) {
        static NSURLSession *session = nil;

        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
            //I don't seem to get the correct time out unless i set the timeout interval here
            //sessionConfiguration.timeoutIntervalForResource = 10;
            session = [NSURLSession sessionWithConfiguration:sessionConfiguration];
        });

        _session = session;
    }
    return self;
}
```

**Comment by yosuke-matsuda** [comment]
`AWSAPIGatewayClient` has an independent runtime, and it does not use `AWSServiceConfiguration` for the configuration. We'll see how we can address it.

**Comment by swl367** [comment]
I ended up subclassing the GatewayClient for now and overriding the init.

**Comment by FrantzdyRomain** [comment]
Any updates on this?
