### ISSUE TITLE
Not able to register device for Push sync 

### ISSUE THREAD

**Issue by rtiwarihr** [aws/aws-sdk-ios#1011]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Congnito User pool

* In what version of SDK are you facing the problem?
    pod 'AWSSNS'
    pod 'AWSCognito'
    pod 'AWSCore'

* Is the issue limited to Simulators / Actual Devices?
Actual Device

* Can your problem be resolved if you bump to a higher version of SDK?
Not sure

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? Cocopods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Steps : Login into the App
Sign-in with username and password

**_Code in AWSManager.m class_**

**====== Initial set-up for AWSCognitoIdentityUserPoolConfiguration==========**
**//Called at time of launch**
```
-(void)initialSetup
{
    // AWS Log configuration
    [AWSDDLog addLogger:[AWSDDTTYLogger sharedInstance]];

    [AWSDDLog sharedInstance].logLevel = AWSDDLogFlagDebug;
    
   
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:nil];
    
    AWSCognitoIdentityUserPoolConfiguration *userPoolConfiguration = [[AWSCognitoIdentityUserPoolConfiguration alloc]  initWithClientId:@"xxxxxxxxxxxxxxxxxxxx"  clientSecret:nil poolId:@"xxxxxxxxxxxx"];
    
   [AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:configuration userPoolConfiguration:userPoolConfiguration forKey:USER_POOL_KEY];
    
    
   _aWSCognitoIdentityUserPoolObj = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:USER_POOL_KEY];
    
    self.aWSCognitoIdentityUserPoolObj.delegate = self;
    
} 
```

**======Code to sign in ==========**
- (void)signInCognitoWithUsername:(NSString *)userName andPassword:(NSString*)password completionHandler:(void (^)(AWSTask<AWSCognitoIdentityUserSession*> * session,bool isSignedIn))completionHandler

{

    AWSCognitoIdentityUser * user = [Application.pushSyncHandler.aWSCognitoIdentityUserPoolObj currentUser];
    if (Application.pushSyncHandler.aWSCognitoIdentityUserPoolObj.currentUser.isSignedIn) {
        AWSTask<AWSCognitoIdentityUserSession*> * session = [user getSession];
        if (session) {
            DDLogInfo(@"Token to be used %@ accessToken %@ refreshToken %@",session.result.idToken.tokenString,session.result.accessToken.tokenString,session.result.refreshToken.tokenString);
          [self registerDeviceForPushSync];
            DDLogInfo(@"User has already logged in");
            //[self getProfileWithAuthToken:session.result.idToken.tokenString];
             completionHandler(session,true);
        } else {
            DDLogInfo(@"AWS session does not exist");
        }
       
        
    } else {
        [[user getSession:userName password:password validationData:nil] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull t) {

[self registerDeviceForPushSync];
            completionHandler(t,false);
            return nil;
        }];
        
        
    }
}

**======Code to register for push sync ==========**
```
-(void)registerDeviceForPushSync {
   // AWSCognitoIdentityUserPool * _pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:USER_POOL_KEY];
    
    credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"xxxxxxx" identityProviderManager:_aWSCognitoIdentityUserPoolObj];
    
    DDLogInfo(@"Identity Id %@",credentialsProvider.identityId);
    _identityId = credentialsProvider.identityId;
    AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];
    
    [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = serviceConfiguration;
    
    
    
     DDLogInfo(@"Device token from APNS %@",Application.deviceTokenData);

    AWSCognito *syncManager = [AWSCognito defaultCognito];
    
    
    // Retrieve your Amazon Cognito ID
    [[credentialsProvider getIdentityId] continueWithBlock:^id(AWSTask *task) {
        if (task.error) {
            NSLog(@"Error: %@", task.error);
        }
        else {
            // the task result will contain the identity id
            NSString *cognitoId = task.result;
        }
        return nil;
    }];
    
    [[syncManager registerDevice:Application.deviceTokenData] continueWithBlock:^id(AWSTask *task) {
        if(task.error){
            DDLogError(@"Unable to registerDevice: %@", task.error);
        } else {
            [self subscribeToDatasets];
            DDLogInfo(@"Successfully registered device with id: %@", task.result);
        }
        return nil;
    }
     ];
    
    

   
    
}

```

**_//Code from AWSCognitoService class_**

```
-(AWSTask *)registerDeviceInternal:(NSString *) deviceToken {
**NSString *currentDeviceId = [AWSCognito cognitoDeviceId];
        NSString *currentDeviceIdentity = [AWSCognito cognitoDeviceIdentity];
        if(currentDeviceId && currentDeviceIdentity && [self.cognitoCredentialsProvider.identityId isEqualToString:currentDeviceIdentity]){
            return [AWSTask taskWithResult:currentDeviceId];
        }**

}
```

For every login, **currentDeviceIdentity** and **self.cognitoCredentialsProvider.identityId**  are same due to which register device api is never called.

I suspect something wrong with the configuration.

Need help as I am not able to receive push. Also, please suggest few sample which can help to understand Cognito user pool  and push sync mechanis

Any inputs will be appreciated

**Comment by rohandubal** [comment]
Hello @rtiwarihr 

I see that you are calling `registerDevice` immediately after `getIdentityId`. I think it should be called in the completion handler of `getIdentityId`. 

Also, if you are just starting to write your app, I would suggest you to use AppSync instead for data synchronization. About AppSync: 

> AppSync is a new service for synchronizing application data across devices. Like Cognito Sync, AppSync enables synchronization of a user's own data, such as game state or app preferences. AppSync extends these capabilities by allowing multiple users to synchronize and collaborate in real-time on shared data, such as a virtual meeting space or chatroom. Start building with [AWS AppSync now](https://aws.amazon.com/appsync/resources/).

Hope this helps,
Rohan

**Comment by rtiwarihr** [comment]
```
[[self.credentialsProvider getIdentityId] continueWithBlock:^id(AWSTask *task) {
        if (task.error) {
            NSLog(@"Error: %@", task.error);
        }
        else {
            // the task result will contain the identity id
            NSString *cognitoId = task.result;
            
            [[syncManager registerDevice:Application.deviceTokenData] continueWithBlock:^id(AWSTask *task) {
                if(task.error){
                    DDLogError(@"Unable to registerDevice: %@", task.error);
                } else {
                    [self subscribeToDatasets];
                    DDLogInfo(@"Successfully registered device with id: %@", task.result);
                }
                return nil;
            }
             ];
        }
        return nil;
    }];

```
This fails when I logout and then login again. It says could not connect to hostname for **registerdevice** event

On logout I do the following,

```
-(void)signOut{
   
     AWSCognitoIdentityUser * user = [[AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:USER_POOL_KEY] currentUser];
    if(user){
         [user signOutAndClearLastKnownUser];
    }
    
    // AWSCognito unsubscribe to datasets
    
    [[[[AWSCognito defaultCognito] openOrCreateDataset:STATUS_DATASET] unsubscribe] continueWithBlock:^id(AWSTask *task) {
        if(task.error){
            DDLogError(@"Unable to unsubscribe to dataset: %@ %@", task.error,STATUS_DATASET);
        } else {
            DDLogInfo(@"Successfully unsubscribed to dataset: %@ %@", task.result,STATUS_DATASET);
        }
        return nil;
    }
     ];
    [[[[AWSCognito defaultCognito] openOrCreateDataset:FETCH_HOME_DATASET] unsubscribe] continueWithBlock:^id(AWSTask *task) {
        if(task.error){
            DDLogError(@"Unable to unsubscribe to dataset: %@ %@", task.error,FETCH_HOME_DATASET);
        } else {
            DDLogInfo(@"Successfully unsubscribed to dataset: %@ %@", task.result,FETCH_HOME_DATASET);
        }
        return nil;
    }
     ];
    
     // AWSCognito wipe
    
     AWSCognito *syncManager = [AWSCognito defaultCognito];
     [syncManager wipe];
    
}

```

The main issue which I suspect is with the Keychain. Its picks the older users credentials and hence fails to register device and subscribe to events. What is the better approach to handle logins of different users

**Comment by rohandubal** [comment]
I think to handle logins of different users, you should ensure you clear the keychain and credentials before logging any user in. Doing that will make sure you have empty keychain.

An important part to note is that you will have to clear multiple keychains. One is of user pools which you are doing. Other is of Cognito Identity (Cognito Credentials Provider.)

Clearing both should give you a good behavior.

Thanks,
Rohan

**Comment by rohandubal** [comment]
No, you should not have to perform userPoolConfiguration on every login. The only good practice to follow would be to clear all keychains before every login, even if using the same client/ configuration.
