### ISSUE TITLE
Resuming multiple times finishes the upload before it has been completed.

### ISSUE THREAD

**Issue by pablogeek** [aws/aws-sdk-ios#1015]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS S3
* In what version of SDK are you facing the problem?
2.6.26
* Is the issue limited to Simulators / Actual Devices?
All devices
* Can your problem be resolved if you bump to a higher version of SDK?
No, this is the latest one
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

We are checking first if we have any pending uploads to resume, if not we run a new multi part upload.
The problem is after restart the app multiple times, it enters to `completionBlockUpload` before it has been uploaded completely.

Steps 
- Start uploading a 100mb file
- Restart the app when it reaches 8mb aprox
- It resumes from 5mb
- Restart the app when it reaches 30mb
- it will resume again
- Restart the app when it reaches 50mb
- It will resume but after upload a few mb (I guess the next chunk of data) it will call to `completionBlockUpload`

```

let expression = AWSS3TransferUtilityMultiPartUploadExpression()
        expression.progressBlock = { _, progress in
            NSLog("AWSS3TransferUtilityMultiPartUploadExpression progress")
            DispatchQueue.main.async(execute: {
                video.updateUploadProgress(progress.completedUnitCount, totalBytesExpectedToWrite: progress.totalUnitCount, speed: 0.0)
            })
        }
         
        let completionBlockUpload: AWSS3TransferUtilityMultiPartUploadCompletionHandlerBlock = {
            [weak self] _, error in
            DispatchQueue.main.async {
                // perform some action on completed upload operation
                if let e = error as NSError? {
                    print("Error: \(e.localizedDescription)")
                    self?.errorVideo(e, video: video)
                    return
                }
                self?.completeUpload(video: video)
            }
        }


AWSTransfer(video: video) { [weak self] transferUtility in
            
            transferUtility?.getMultiPartUploadTasks().continueOnSuccessWith(block: { (tasks) -> Any? in
                
                if let task = tasks.result?.firstObject as? AWSS3TransferUtilityMultiPartUploadTask {
                    task.resume()
                    task.setProgressBlock(expression.progressBlock!)
                    task.setCompletionHandler(completionBlockUpload)
          
                }else {
                    let fileURL = URL(fileURLWithPath: video.localFilePath)
                    
                    let task = transferUtility?.uploadUsingMultiPart(fileURL: fileURL,
                                                                     bucket: video.amazonBucket,
                                                                     key: video.uploadKey,
                                                                     contentType: "video/mov",
                                                                     expression: expression, completionHandler: completionBlockUpload)
                    
                    task?.continueWith(executor: AWSExecutor.mainThread()) {
                        (uploadTasks) -> AnyObject! in
                        
                        
                        if let error = task?.error as NSError? {
                            print("Error: \(error.localizedDescription)")
                            self?.errorVideo(error, video: video)
                        }
                        NSLog("continueWith!!")
                        
                        if let res = task?.result {
                            // Do something with uploadTask.
                            self?.transferTasks[video.uploadKey] = res
                        }
                        return nil
                    }
                }
                return nil
            })
        }


```

**Comment by cbommas** [comment]
@pablogeek 
I will look into this and get back to you

**Comment by ShadyBoukhary** [comment]
I've had the same issue with the transfer ulitilty. I solved it by manually handling it.

**Comment by pablogeek** [comment]
@ShadyBoukhary Manually handling it, you mean? AWSManager?

**Comment by ShadyBoukhary** [comment]
@pablogeek I kept a list of unuploaded files in UserDefaults. Then at app launch, I check for them and I reupload the ones that had not finished uploading. Resuming multiple times was unreliable for me so if upload failed, I don't rely on the transfer utility to resume, I just reupload. It's just a workaround. But like a huge portion of the AWS SDK, it's the only solution I found.

**Comment by cbommas** [comment]
@pablogeek 
I am targeting the fix for this issue in the next rev of the SDK. Will loop back on this thread once the release is out.

**Comment by pablogeek** [comment]
@cbommas Sounds great thanks!!!!

**Comment by kvasukib** [comment]
The issue has been fixed in 2.6.28. Can you upgrade to the latest version and check if it fixes the issue? Thanks

**Comment by simeondrage** [comment]
tested it. seemed fixed to me. we are going to release our app with the new SDK :)

**Comment by undefobj** [comment]
@simeondrage @pablogeek @ShadyBoukhary I work on both the AppSync and SDK library team and am interested in the use cases/apps that you might be building with this functionality. If you're open to sharing I would like to chat with you further if you're open to emailing or a phone call. If so could you email me richthr_at_amazon.com (replace the at with @).

**Comment by simeondrage** [comment]
@undefobj sure, i'll email you

**Comment by cbommas** [comment]
@simeondrage 

Thanks for confirming. I will go ahead and close this issue. Please feel to reopen if you run into issues.
