### ISSUE TITLE
Memory Leak inside AWSURLSessionManager URLSession delegate

### ISSUE THREAD

**Issue by pedromcunha** [aws/aws-sdk-ios#1021]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSCore, AWSS3, AWSKinesis

* In what version of SDK are you facing the problem?
2.6.26

* Is the issue limited to Simulators / Actual Devices?
Actual Devices

* Can your problem be resolved if you bump to a higher version of SDK?
No, as far as I know.

* Is this problem related to specific iOS version?
Not sure.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Run the demo, use the SDK to make a request (kinesis in this case). Also make sure to enable Malloc Scribble and Malloc Stack (live allocations only)

After running some tests for leaks using the memory debugger I ran into some memory issues with the AWS sdk. This line in particular:
`    
[[[AWSTask taskWithResult:nil] continueWithSuccessBlock:^id(AWSTask *task) {
`

I think the proposed fix would be to add [weak self] to the success block. Here's a screenshot of a portion of the leaks detected:

![screen shot 2018-08-16 at 4 12 22 pm](https://user-images.githubusercontent.com/6723339/44232490-39534380-a16f-11e8-8e93-abee79e48898.png)

**Comment by bukira** [comment]
I think this is still happening in 2021

Crashed: com.apple.NSURLSession-delegate
0  libswiftCore.dylib             0x18a4f51a0 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrement<(swift::PerformDeinit)1>(unsigned int) + 20
1  app name                 0x10139e004 lazy protocol witness table accessor for type Int and conformance Int + 4382367748
2  libswiftCore.dylib             0x18a4f43d8 _swift_release_dealloc + 40
3  libsystem_blocks.dylib         0x1d1cf6764 _Block_release + 200
4  libsystem_blocks.dylib         0x1d1cf6764 _Block_release + 200
5  AWSCore                        0x102ba469c __destroy_helper_block_e8_32s40s48s56s + 32
6  libsystem_blocks.dylib         0x1d1cf6764 _Block_release + 200
7  AWSCore                        0x102b93620 __destroy_helper_block_e8_32s40s + 24
8  libsystem_blocks.dylib         0x1d1cf6764 _Block_release + 200
9  CoreFoundation                 0x186470f44 -[__NSArrayM removeAllObjects] + 220
10 AWSCore                        0x102ba4068 -[AWSTask runContinuations] + 440
11 AWSCore                        0x102ba3b78 -[AWSTask trySetResult:] + 144
12 AWSCore                        0x102baa21c -[AWSTaskCompletionSource setResult:] + 80
13 AWSCore                        0x102bb6e80 __61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke + 4112
14 AWSCore                        0x102ba4a18 __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 92
15 AWSCore                        0x102ba4410 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 88
16 AWSCore                        0x102baeb20 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 128
17 AWSCore                        0x102baf034 -[AWSExecutor execute:] + 76
18 AWSCore                        0x102ba4278 -[AWSTask continueWithExecutor:block:cancellationToken:] + 304
19 AWSCore                        0x102ba4978 -[AWSTask continueWithExecutor:successBlock:cancellationToken:] + 204
20 AWSCore                        0x102ba4aa0 -[AWSTask continueWithSuccessBlock:] + 100
21 AWSCore                        0x102bb5dc4 -[AWSURLSessionManager URLSession:task:didCompleteWithError:] + 380
22 app name                     0x1017c11d4 __InstrumentURLSessionTaskDidCompleteWithError_block_invoke + 4386705876
23 CFNetwork                      0x186d6a8cc _CFNetworkHTTPConnectionCacheSetLimit + 154244
24 libdispatch.dylib              0x18618424c _dispatch_call_block_and_release + 32
25 libdispatch.dylib              0x186185db0 _dispatch_client_callout + 20
26 libdispatch.dylib              0x18618d10c _dispatch_lane_serial_drain + 580
27 libdispatch.dylib              0x18618dc90 _dispatch_lane_invoke + 460
28 libdispatch.dylib              0x186197d78 _dispatch_workloop_worker_thread + 708
29 libsystem_pthread.dylib        0x1d1d63804 _pthread_wqthread + 276
30 libsystem_pthread.dylib        0x1d1d6a75c start_wqthread + 8
