### ISSUE TITLE
Can push sync be ignored for the device from where it is triggered ?

### ISSUE THREAD

**Issue by rtiwarihr** [aws/aws-sdk-ios#1022]
What service are you using?
AWS Congnito User pool

In what version of SDK are you facing the problem?
pod 'AWSSNS'
pod 'AWSCognito'
pod 'AWSCore'

Is the issue limited to Simulators / Actual Devices?
Actual Device

Can your problem be resolved if you bump to a higher version of SDK?
Not sure

Is this problem related to specific iOS version?
No

How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? Cocopods

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Steps : Login into the App
Receive a push sync

I'm receiving a push sync on the same device from where I trigger it. Need a mechanism to bypass it so that I can avoid unnecessary refresh on my device despite of updating the local cache.

ideally, it should be received only when an external source triggers it.

Please advice

**Comment by kvasukib** [comment]
@rtiwarihr Thank you for reporting to us. Sorry for the inconvenience caused. Can you elaborate on what you mean by "push sync"?
