### ISSUE TITLE
AWSS3TranferUtility not calling completionHandler in background on large multipart uploads when not connected to debugger

### ISSUE THREAD

**Issue by jeffjvick** [aws/aws-sdk-ios#1023]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSS3TransferUtility iOS
* In what version of SDK are you facing the problem?
2.6.26
* Is the issue limited to Simulators / Actual Devices?
Actual device
* Can your problem be resolved if you bump to a higher version of SDK?
N/A
* Is this problem related to specific iOS version?
don't know, I'm on 11.4.1
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Note: I'm only testing on a real device.

I have a completionHandler that prints to NSLog when it is called.  If I start a multipart upload while connected to the xCode debugger and then background the app the completionHandler will correctly fire and write to NSLog when the file is finished uploading in the background.

If however I disconnect the debugger and try the same sequence it will not call the completionHandler in the background.  I believe the difference in having / not having the debugger attached with regards to background operation is outlined in this post: https://forums.developer.apple.com/message/42353#42353

I have noticed that if I don't include `handleEventsForBackgroundURLSession` in the `AppDelegate` the background uploads don't work at all but I have stopped calling `interceptApplication` because supposedly the SDK now handles this.  I think the issue is related to this.

```
    func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
        NSLog("handler events for background URLSession") 
        /*
         Store the completion handler.
         */
        // I'm told this is no longer needed to be called by us and is instead taken care of by the SDK
        //AWSS3TransferUtility.interceptApplication(application, handleEventsForBackgroundURLSession: identifier, completionHandler: completionHandler)
    }
```

The `handleEventsForBackgroundURLSession` is called in the background since I see the log output but my completionHandler is not getting called and I also do see that the file actually made it into the bucket.

Also, the problem only happens if the app is uploading in the background for a significant amount of time.  It seems to need to be in the background for greater than ~30seconds for it not to work.

**Comment by pablogeek** [comment]
@jeffjvick I haven't had this, in my case it wasn't resuming at all if I'm running the app from xcode (debugging). So it is weird what they are doing here. First time I see different behaviour when debugging.

**Comment by jeffjvick** [comment]
@pablogeek After talking with some @cbommas I learned that what I’m see is actually expected behavior.  Basically if you background your app while in the middle of a multipart upload it will only complete the current parts and not start any new parts while in the background.  They had concluded that waking the app up periodically to start additional parts would be undesirable.  I was expecting it to do exactly that.

Since I know you guys do very large multipart uploads, how are you handling this?  Or are you not letting the user upload in the background?

**Comment by simeondrage** [comment]
@jeffjvick from my testing its working fine for us. I background the app at 200mb uploaded. Wait a minute and its got to 300mb. @pablogeek can explain what hes done in the code.

**Comment by cbommas** [comment]
@simeondrage 
I posted an update in https://github.com/aws/aws-sdk-ios/issues/769 on this topic. Lets consolidate our communication and track it in one place on https://github.com/aws/aws-sdk-ios/issues/769
