### ISSUE TITLE
No error message with Transfer Utility when no network connection- iOS Swift

### ISSUE THREAD

**Issue by Hardy143** [aws/aws-sdk-ios#1029]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3 Transfer Utility
* In what version of SDK are you facing the problem?
2.6.13
* Is the issue limited to Simulators / Actual Devices?
I'm running on an iPhone 6s
* Can your problem be resolved if you bump to a higher version of SDK?
Don't know
* Is this problem related to specific iOS version?
No i'm running latest version
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

When I put my phone on airplane mode and try to upload my files to the S3 bucket using Transfer Utility I'm not getting any error message. The upload just keeps trying to upload continuously and doesn't stop. Other errors do work, for example, if the bucket name is incorrect I get the expected error.

My code is as follows. Sorry if I'm doing something wrong that's very basic, I'm new to AWS.

```swift
func uploadData(fileUrl: URL, key: String, content: String, completion: @escaping(Int) -> ()) {
        
        var successCount = 0
        
        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, progress) in
            DispatchQueue.main.async(execute: {
                // Do something e.g. Update a progress bar.

            })
        }
        
        let transferUtility = AWSS3TransferUtility.default()
        
            transferUtility.uploadFile(fileUrl, bucket: "liopa-datacapture-ios", key: key, contentType: content, expression: expression) { (task, error) in
                if let error = error {
                    print("Error: \(error.localizedDescription)")
                    successCount = 0
                    completion(successCount)
                    return
                }
                
                print("Successfully uploaded")
                successCount = 1
                completion(successCount)
            }

    }
```

**Comment by desokroshan** [comment]
@Hardy143 Thanks for reaching out. uploadFile task can potentially run into two types of errors depending on when the error occurs. There can be error in upload task creation itself (which seems to be the case with you since the phone was already on airplane mode when upload starts). Secondly, there can error after the upload task has been created and is in progress. The completion handler in your snippet reports only the latter. The following snippet has .continueWith handler which reports errors in task creation itself. 
```
transferUtility.uploadFile(fileUrl, bucket: "liopa-datacapture-ios", key: key, contentType: content, expression: expression, completionHandler: { (task, error) in
                if let error = error {
                    print("Error: \(error.localizedDescription)")
                    successCount = 0
                    completion(successCount)
                    return
                }
                
                print("Successfully uploaded")
                successCount = 1
                completion(successCount)
            }).continueWith(block: { (task) -> Any? in
                        if (task.error != nil) {
                            print("error in creating task \(error)") // check here for errors in task creation
                         }
                        return nil
                    })
```
Can you please try the above?

**Comment by Hardy143** [comment]
@desokroshan thanks for your help. I understand what you mean about the errors being two different kinds but unfortunately the code isn't working for me. I've copied your code into mine and it's not printing an error.

**Comment by cbommas** [comment]
@Hardy143 

Just following up on this thread. I had a couple of questions.
- You mentioned that you get an error when the bucket name is incorrect. Can you post the error message/stack trace?
- what happens when you take the phone off airplane mode? Does the transfer start?

**Comment by cbommas** [comment]
@Hardy143 
Just checking back to see if you were still encountering issues. Please let me know.

**Comment by Hardy143** [comment]
@cbommas thanks for getting back to me. I was using S3 as part of my end of year uni project. It’s been handed in now and I’ve started straight into a new job and haven’t had a chance to look at my project since. I’ll try and have a look this weekend and answer your above questions.

**Comment by cbommas** [comment]
@Hardy143 

Thank you, let me know how it goes. 

Also, please look at this thread https://github.com/aws/aws-sdk-ios/issues/1047. It has information regarding how the TransferUtility works when the device goes offline.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
