### ISSUE TITLE
Port is dropped when custom endpoint

### ISSUE THREAD

**Issue by jabarkarim** [aws/aws-sdk-ios#1039]
In my app I have to use AWSS3 to generate presigned URL and when setting a custom endpoint with port (ex: http://localhost:8080) the generated URL does not contain the port.

I have this entry in my Podfile
`
pod 'AWSS3'
`
So I am not sure about the version of AWSS3 that is loaded.

Here is my code:

`
let credential = AWSStaticCredentialsProvider.init(accessKey: "somekey", secretKey: "somesecret")
                    
                    let endpoint : AWSEndpoint = AWSEndpoint(urlString: "http://localhost:8080/s3")
                    
                    let configuration = AWSServiceConfiguration.init(region:.USEast1, endpoint: endpoint, credentialsProvider: credential)
                    AWSServiceManager.default().defaultServiceConfiguration = configuration
                    
                    let urlBuilder = AWSS3PreSignedURLBuilder.default()
                    let request = AWSS3GetPreSignedURLRequest()
                    request.bucket = "thumbnails"
                    request.key = "pydio-thumbstore/\(node.id)-\(thumbSize).\(format)"
                    request.httpMethod = AWSHTTPMethod.GET
                    request.expires = NSDate().addingTimeInterval(5*60) as Date
                    
                    var presignedURL: URL? = nil
                    let preSignedURLRequest = urlBuilder.getPreSignedURL(request)
                    preSignedURLRequest.continueWith { (task:AWSTask<NSURL>) -> Any? in
                        if let error = task.error as NSError? {
                            print("Error: \(error)")
                            return nil
                        }
                        presignedURL = task.result as URL?
                        return nil
                    }
                    preSignedURLRequest.waitUntilFinished()
                    return presignedURL
`

Am I doing something wrong?

**Comment by cbommas** [comment]
@jabarkarim 

Sorry to hear you are running into issues. Can you give me some more information about your use cases - typically, the presigned URL is a mechanism used to provide access to specific S3 files to unauthorized users who are not part of your account or group.

**Comment by cbommas** [comment]
@jabarkarim 

I am going to go ahead and close this thread as I haven't heard back. Please feel free to reach back to us if you are still facing issues.
