### ISSUE TITLE
AWS Pinpoint special characters(JSON Format not accepting) issue with deep linking for iOS(2.6.27 Version) and Android(2.6+)

### ISSUE THREAD

**Issue by chuchuTv** [aws/aws-sdk-ios#1046]
We are facing some technical issue in AWS Pinpoint. Actually the deep link url worked fine some couple of days back. But now it is not working, it throws invalid URL error in campaigns.

I have used the below URL,
 urlscheme://deeplink/{"newtestdetails": [{"VideoId": "test1","DisplayName": "Test1","ThumbnailName": "test1.jpg"}]}

Note: This works fine in direct messages with device token. The above dummy deep link works fine previously but now it is not working. Is there anything updated with the recent SDK's, If yes please let us know about it. We noted that special characters are not accepted now in deep link, is that we need to change it as URL Encode format. Kindly help us regarding this.

**Comment by kvasukib** [comment]
@chuchuTv Sorry for the delayed response. Can you answer the following questions?
1) Version of AWS SDK for iOS?
2) Version of iOS?
3) A code snippet
4) a description of your use-case
