### ISSUE TITLE
How to Update an Item on DynamoDB

### ISSUE THREAD

**Issue by GreyEcologist** [aws/aws-sdk-ios#105]
Hey, I posted the question earlier, but I see the behavior of the SDK hasn't changed, the API doc however seems to hint at the correct behavior:
http://docs.aws.amazon.com/AWSiOSSDK/latest/Constants/AWSDynamoDBObjectMapperSaveBehavior.html

> AWSDynamoDBObjectMapperSaveBehaviorUpdate
AWSDynamoDBObjectMapperSaveBehaviorUpdate will not affect unmodeled attributes on a save operation and a nil value for the modeled attribute will remove it from that item in DynamoDB.

QUESTION: 
I want to update the firstName attribute of my item with has many other attributes, however the call below removes the other item's attributes. It other words it creates a new item instead of updating the existing item. How can I do so without retrieving and saving all the item's attributes?

```
TestObject *item = [TestObject new]; //@interface TestObject : AWSDynamoDBModel <AWSDynamoDBModeling>
item.personID = @"person1"; //personID is my dynamoDB table HasKey
item.firstName = @"Gary"; //the only attribute I want to update

AWSDynamoDBObjectMapper *dynamoDBObjectMapper = [AWSDynamoDBObjectMapper defaultDynamoDBObjectMapper];
AWSDynamoDBObjectMapperConfiguration *config = [[AWSDynamoDBObjectMapperConfiguration alloc] init];
[config setSaveBehavior:AWSDynamoDBObjectMapperSaveBehaviorUpdate];

[[dynamoDBObjectMapper save:item]
 continueWithExecutor:[BFExecutor mainThreadExecutor] withBlock:^id(BFTask *task) {
     if (!task.error) {

         UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Succeeded"
                                                         message:@"Successfully updated the data in the table."
                                                        delegate:nil
                                               cancelButtonTitle:@"OK"
                                               otherButtonTitles:nil];
         [alert show];
     } else {
         NSLog(@"Error: [%@]", task.error);

         UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Error"
                                                         message:@"Failed to update the data in the table."
                                                        delegate:nil
                                               cancelButtonTitle:@"OK"
                                               otherButtonTitles:nil];
         [alert show];
     }
```

**Comment by Crphang** [comment]
I believe I had the same problem before. If I'm not wrong, I made the mistake of assigning the table as Hash-And-Range Key, where both hash and range are unique attributes. Mutating Range Key will hence create a new table.

What you could do is create another table that is hashKey only. 

Anyway, I believe that UIAlertView is deprecated from iOS8 onwards.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to let us know if the problem persists. Thanks.
