### ISSUE TITLE
AWS S3 image URL issue

### ISSUE THREAD

**Issue by ishaanapptree** [aws/aws-sdk-ios#106]
I have created an image URL using preSigned URL request and then using the same key name.
I have made uploadRequest.
After the call is successful when I get the image from the URL using SDWebImage library it gives me an error
Request timed out
If I use depricated methods it gives me an error
Unacceptable content type

**Comment by yosuke-matsuda** [comment]
We've released the new S3 Background Transfer Sample in our [sample app repo](https://github.com/awslabs/aws-sdk-ios-samples). It demonstrates how to use `S3PreSignedURLBuilder` and upload/download files in the background. Hope it helps.
