### ISSUE TITLE
Upload when app is in background.

### ISSUE THREAD

**Issue by johnqh** [aws/aws-sdk-ios#107]
As stated in https://github.com/aws/aws-sdk-ios/issues/6:

"The background transfer on iOS 7 and above only supports files. Currently, we don't support background transfer, but we are planning to support it in the future."

Does that mean (app)background uploading is not supported? Please clarify. If there is a way to do it, can you provide some sample code?

**Comment by yosuke-matsuda** [comment]
We've released the new S3 Background Transfer Sample in our [sample app repo](https://github.com/awslabs/aws-sdk-ios-samples). It demonstrates how to use `S3PreSignedURLBuilder` and upload/download files in background. Hope it helps.
