### ISSUE TITLE
IoTDataManger Subscribe and 3G network condition

### ISSUE THREAD

**Issue by RyanCodes** [aws/aws-sdk-ios#1070]
**State your question**

For some reason when I am not utilizing the network conditioner on my standard Wifi connection. My subscribe event calls back with no problem... it subscribes gives a call back with data and I can move on... but if I have the network conditioner on my device set to 3G for example and try to subscribe the callback is never called? Is there a setting in iotdatamanager that only allows wifi? This is making me bang my head :) 

**Which AWS Services are you utilizing?**

IoT

**Provide code snippets (if applicable)**

`self.iotDataManager.subscribe(toTopic: subscribeTopic, qoS: .messageDeliveryAttemptedAtLeastOnce) { data  in 
 <do something with data>
}`

**Environment(please complete the following information):**
 - SDK Version:  2.6.32
 - Dependency Manager: Cocoapods
 - Swift Version : Swift 4.2

**Device Information (please complete the following information):**
 - Device: iPhone X Real Device
 - iOS Version: [e.g. iOS 11.4] IOS 12.0

**Comment by RyanCodes** [comment]
figured it out

**Comment by fasngo** [comment]
Hi @RyanCodes did you figure out why the subscribe call was not working with the network link conditioner on?  Do you mind sharing 😄

**Comment by RyanCodes** [comment]
@fasngo sure thing... in my case we actually were setting the subscribe callback after we called `iotDataManager.publishString` so when we were getting results back the subscribe callback wasn't initialized yet.. it was a strange scenario
