### ISSUE TITLE
Here's how to uses PromiseKit with iOS SDK

### ISSUE THREAD

**Issue by bennnjamin** [aws/aws-sdk-ios#1076]
I've done some work on using Promises with this SDK, and it makes working with AWSTask/Swift much more readable for those interested. I got it working on an issue in their repository here: https://github.com/mxcl/PromiseKit/issues/951 and am including the code here. Maybe this could be useful to others

```swift
import PromiseKit
import AWSCore

extension Promise {
    /**
     The provided closure is executed when this promise is resolved.
     */
    public func then<U: AnyObject>(on q: DispatchQueue? = conf.Q.map, body: @escaping (T) -> AWSTask<U>) -> Promise<U?> {
        return then(on: q) { tee -> Promise<U?> in
            let task = body(tee)
            return Promise<U?> { seal in
                task.continueWith(block: { task in
                    if task.isCompleted {
                        seal.fulfill(task.result)
                    } else if let error = task.error {
                        seal.reject(error)
                    } else {
                        seal.reject(PMKError.invalidCallingConvention)
                    }
                    return nil
                })
            }
        }
    }
    
}
```

In order to use, you need to start a promise chain with a void promise like so:

```swift
    Promise().then {
      return AWSTask()
    }.then { (result) in
      return anotherAWSTask(result)
    }.done { (nextResult)
      print(nextResult)
    }.catch { (error) in
       print(error)
    }
```

**Comment by palpatim** [comment]
Thanks for this contribution @bennnjamin. I'm adding the "closing soon if no response" label just so this issue doesn't stay open past a week from now, but it will remain in the archive and searchable. It also looks like you're adding it to the PromiseKit snippets repo for others to find, so it should be discoverable that way as well.

**Comment by rainypixels** [comment]
Thanks for this. I did find a bug here, though, and figured I should share the fix:

```swift
extension Promise {
  /**
   The provided closure is executed when this promise is resolved.
   */
  public func then<U: AnyObject>(on q: DispatchQueue? = conf.Q.map, body: @escaping (T) -> AWSTask<U>) -> Promise<U?> {
    return then(on: q) { tee -> Promise<U?> in
      let task = body(tee)
      return Promise<U?> { seal in
        task.continueWith(block: { task in
          if let result = task.result {
            seal.fulfill(result)
          } else if let error = task.error {
            seal.reject(error)
          } else {
            seal.reject(PMKError.invalidCallingConvention)
          }
          return nil
        })
      }
    }
  }
}
```

`task.isCompleted` is an unreliable if condition since all tasks (even tasks that return errors) complete. Your original extension was swallowing my errors because the if clause was returning the `nil` `task.result` instead of the `task.error`.
