### ISSUE TITLE
S3TransferManager to resume some of the requests

### ISSUE THREAD

**Issue by evenluo** [aws/aws-sdk-ios#11]
I really appreciate the great work you guys did. But there was some minor issues when I used AWS SDK for iOS 1.x: I have to resume all uploading even if I just want to resume some of them; and now I have to implement the separate uploading by myself.

It would be great if we could have the new feature: group one (or more) tasks with tag and then we could control, for instance uploading, the tasks by using that tag.

**Comment by MohamedThabib** [comment]
I have used the older AWSS3 frame work and AWSRuntime frame work in my iOS App to upload a file in my amazon bucket and get the url of it now I need to do the same with the latest AWSiOSSDKV2.0 frame work lot of thing has change in this latest SDK could some point me to the correct resource where I can upgrade the frame work. I have searched But I am unable to find the correct resource 

I have followed the S3 TransferManager sample I am able to upload the file but I am not able to get the URL of that uploaded file.

Any kind of help would be greatly appreciated!

**Comment by yosuke-matsuda** [comment]
[AWS Mobile SDK Developer Guides](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/) should help you get started with the new SDK. Especially, [Use Pre-Signed URLs to Transfer Objects in the Background](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transfermanager.html#use-pre-signed-urls-to-transfer-objects-in-the-background) may answer your Amazon S3 question.

**Comment by yosuke-matsuda** [comment]
We released `AWSS3TransferUtility`, and you can resume upload/download request individually. See our [blog post](https://mobile.awsblog.com/post/Tx283AGGIL76PKP/Amazon-S3-Transfer-Utility-for-iOS) for more details. Thanks.
