### ISSUE TITLE
Verifying file MD5 checksum after download from S3

### ISSUE THREAD

**Issue by autresphere** [aws/aws-sdk-ios#112]
Is there any way of verifying the integrity of a file downloaded with AWSS3TransferManager? Checking the MD5 file checksum would be a good way, but can we get this value from S3?

**Comment by JesseCrocker** [comment]
If anyone else runs into this and need to verify eTags for multi-part downloads, i've released a method for doing this at https://github.com/trailbehind/FileMD5Hash . It will properly calculate an eTag for single or multi part, and can guess the chunk size based on the server sent eTag as long as the chunk size is multiple of 1024*1024.
