### ISSUE TITLE
How to use IAM in AWS?

### ISSUE THREAD

**Issue by harshcs** [aws/aws-sdk-ios#120]
I want to use IAM in place of Cognito Credentials as you have mentioned in your sample code? How can I use that and which function I will have to call?
```
let credentialsProvider = AWSCognitoCredentialsProvider.credentialsWithRegionType(
    AWSRegionType.USEast1,
    accountId: cognitoAccountId,
    identityPoolId: cognitoIdentityPoolId,
    unauthRoleArn: cognitoUnauthRoleArn,
    authRoleArn: cognitoAuthRoleArn)
```

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to let us know if the problem persists. Thanks.
