### ISSUE TITLE
Upload Image / Video from assets library to S3

### ISSUE THREAD

**Issue by ndbroadbent** [aws/aws-sdk-ios#121]
It seems that `AWSS3TransferManager` does not support uploading files directly from the assets library. I'm seeing this error in my logs:

```
Error Domain=NSCocoaErrorDomain Code=260 "The operation couldn’t be completed. (Cocoa error 260.)" UserInfo=0x7ff40850a7a0 {NSFilePath=/asset.mov, NSUnderlyingError=0x7ff40850ae30 "The operation couldn’t be completed. No such file or directory"}
```

My `AWSS3TransferManagerUploadRequest` looks like this:

```
<AWSS3TransferManagerUploadRequest: 0x7ff4023e2d30> {
    ACL = 0;
    body = "assets-library://asset/asset.mov?id=BCDF906D-AAAA-AAAA-AAAA-3AEA235DFF35&ext=mov";
    bucket = "****-uploads";
    currentUploadingPartNumber = 0;
    key = "**********.mov";
    serverSideEncryption = 0;
    state = 0;
    storageClass = 0;
    totalSuccessfullySentPartsDataLength = 0;
}
```

I think it's having trouble with the `assets-library://` protocol. It would be awesome if the AWS iOS SDK could handle this properly, maybe by using the [getBytes function on ALAssetRepresentation](https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAssetRepresentation_Class/#//apple_ref/occ/instm/ALAssetRepresentation/getBytes:fromOffset:length:error:).

Otherwise, how should I approach this? Should I just copy the asset data to a temporary file before each upload? 

Thanks!

**Comment by ndbroadbent** [comment]
Thanks for your help, I'll do that for now.

**Comment by drmarkpowell** [comment]
AWS SDK developers you should totally implement support for this, it would really help performance of apps that upload photos to the cloud!

**Comment by chadnewbry** [comment]
+1 would be useful.

**Comment by CVBECO** [comment]
+1 also think this would make photo uploads more efficient

**Comment by SebastianBO** [comment]
+1

**Comment by barth1337** [comment]
+1

**Comment by roymckenzie** [comment]
+1

**Comment by ZaidPathan** [comment]
+1, After Parse shutdown - AWS has good chance to pick grip on MBAAS.

**Comment by dustin6464** [comment]
+1

**Comment by urmi1** [comment]
Hello, I can't upload "assets-library://" Video and image directly from this URL. Can you please help me out how can i implement this functionality?
Thank you.
