### ISSUE TITLE
Please explain AWSURLRequestRetryHandler timeIntervalForRetry:

### ISSUE THREAD

**Issue by humblehacker** [aws/aws-sdk-ios#124]
It's pretty clear that this is used to determine the time interval between successive request retries, but the calculation of this interval is (to me) perplexing.  

A pretty common retry interval is Binary Exponential Backoff:

    pow(2, currentRetryCount)

This increases the time between successive retries, usually capped by a maximum number of retries.  For example, four retries would yield the following time intervals:

retries | time (secs)
---------|------------
0         |     1
1         |     2
2         |     4
3         |     8
4         |   16

The AWS SDKs implementation uses this calculation:

    pow(0.2 * 10, currentRetryCount) / pow(10, currentRetryCount)

Four retries would yield the following time intervals:

retries | time (secs)
---------|------------
0         |     1.0
1         |     0.2
2         |     0.04
3         |     0.008
4         |     0.0016

As you can see, this calculation radically _decreases_ the time between successive retries.

I'm admittedly not an expert in this area.  Can someone explain why this is desirable?

**Comment by yosuke-matsuda** [comment]
It is a known issue with the SDK. It should be an exponential back off. We have a fix, and it will be pushed when we released the next version. Thanks.

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.0.14. It should address the issue you encountered.

Thanks,
