### ISSUE TITLE
Mantle/Mantle.h file not found

### ISSUE THREAD

**Issue by ericcheungidea** [aws/aws-sdk-ios#125]
I follow the instruction in the amazon mobile analytic webpage (instruction link: https://console.aws.amazon.com/mobileanalytics/home/?region=us-west-2#/overview?consoleState=management&appTitle=VisualEffect&platform=allplatforms). Add all required frameworks but can't compile the project. Xcode says "Mantle/Mantle.h file not found". What should I do?

My Mac had both Xcode 6.1.1 and Xcode 6.2 beta. I uninstalled both and reinstall the Xcode 6.1.1 but the project doesn't work also. 

![screen shot 2015-01-05 at 2 47 24 pm](https://cloud.githubusercontent.com/assets/493442/5610038/cab0b344-94e9-11e4-95b4-abce259f7fa9.png)

**Comment by yosuke-matsuda** [comment]
Have you made sure your **Framework Search Paths** is correctly pointing to all of the necessary frameworks? Even when  you do not manually manipulate this value, Xcode automatically updates it when you make certain actions on the project.

It may help to clean up *Framework Search Paths* and re-add the frameworks, too.

**Comment by luyishisan** [comment]
i hv the same question with it.
when i built the project. the x-code tell me mantle/mantle.h file not found

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to reopen if you continue to see the issue.
