### ISSUE TITLE
AWSDynamoDBObjectMapper save result is incomplete

### ISSUE THREAD

**Issue by RealNerd** [aws/aws-sdk-ios#126]
I'd like to suggest that the current implementation of [AWSDynamoDBObjectMapper save:configuration:] needs a minor update. The core of the save implementation is this:

            return [[self.dynamoDB putItem:putItemInput] continueWithBlock:^id(BFTask *task) {
                if ([task.error.domain isEqualToString:AWSDynamoDBErrorDomain]
                    && task.error.code == AWSDynamoDBErrorConditionalCheckFailed) {
                    AWSDynamoDBUpdateItemInput *updateItemInput = [AWSDynamoDBUpdateItemInput new];
                    updateItemInput.tableName = [[model class] performSelector:@selector(dynamoDBTableName)];
                    updateItemInput.attributeUpdates = [model itemForUpdateItemInput];
                    updateItemInput.key = [model key];

                    return [self.dynamoDB updateItem:updateItemInput];
                }

                return nil;
            }];

This code returns a *nil* BFTask if there is a general error putting the item (for example, bad or missing key). It also returns *nil* if the save succeeds initially. The only path that returns a non-nil result is if the save fails and the update call happens.

I would like to suggest this code change:

            return [[self.dynamoDB putItem:putItemInput] continueWithBlock:^id(BFTask *task) {
                if ([task.error.domain isEqualToString:AWSDynamoDBErrorDomain]
                    && task.error.code == AWSDynamoDBErrorConditionalCheckFailed) {
                    AWSDynamoDBUpdateItemInput *updateItemInput = [AWSDynamoDBUpdateItemInput new];
                    updateItemInput.tableName = [[model class] performSelector:@selector(dynamoDBTableName)];
                    updateItemInput.attributeUpdates = [model itemForUpdateItemInput];
                    updateItemInput.key = [model key];

                    return [self.dynamoDB updateItem:updateItemInput];
                }

                if (task.error) {
                    return [BFTask taskWithError:task.error];
                }
                
                return task;
            }];

I'm happy to clone the repo, make the change and do a pull request, but I want some feedback on this first to make sure my suggestion is peer reviewed. I could be missing something obvious.

**Comment by yosuke-matsuda** [comment]
We are aware of the [issue](https://forums.aws.amazon.com/thread.jspa?messageID=590158), and the fix is on the way. Thank you.

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.0.14. It should address the issue you encountered.

Thanks,
