### ISSUE TITLE
AWSS3DownloadRequest

### ISSUE THREAD

**Issue by gkaur1** [aws/aws-sdk-ios#127]
Hi I am download files from Amazon S3 storage by setting my amazon service as below

    AWSServiceConfiguration *serviceConfiguration = [AWSServiceConfiguration configurationWithRegion:AWSRegionUSEast1
                                                                                 credentialsProvider:credentialsProvider];
    [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = serviceConfiguration;
    
    self.downloadRequest = [AWSS3TransferManagerDownloadRequest new];
    self.downloadRequest.bucket = bucketName;
    self.downloadRequest.key = bucketKey;
    
    NSString *tempDwnloadingFilePath = [NSTemporaryDirectory() stringByAppendingPathComponent:bucketKey];
    NSFileManager *fileManager = [NSFileManager defaultManager];
    NSError *error = nil;
    if ([fileManager fileExistsAtPath:tempDwnloadingFilePath]) {
        if (![fileManager removeItemAtPath:tempDwnloadingFilePath
                                     error:&error]) {
            NSLog(@"Error: %@", error);
        }
    }

    
    
    NSURL *downloadingFileURL = [NSURL fileURLWithPath:tempDwnloadingFilePath];
    self.downloadRequest.downloadingFileURL = downloadingFileURL;

after the download completes as it doesn't error out. I am trying to read the content from file path like below 

    NSData *data = [[NSFileManager defaultManager] contentsAtPath:[NSTemporaryDirectory() stringByAppendingPathComponent:self.bucketKey]];

but i see that my data is nil, do you know if i am doing something wrong. Thank you.

**Comment by yosuke-matsuda** [comment]
Have you tried **S3 Transfer Manager Sample** in our [GitHub repo](https://github.com/awslabs/aws-sdk-ios-samples)? It demonstrates how to use `AWSS3TransferManager` to upload and download files.

**Comment by gkaur1** [comment]
I see that the example is about UIImage. I didn't try the example, but is there anything different about downloading videos. I thought task.result.body contained the NSData 

Sent from my iPhone

On Jan 13, 2015, at 7:09 PM, Yosuke Matsuda <notifications@github.com> wrote:




Have you tried S3 Transfer Manager Sample in our 
GitHub repo? It demonstrates how to use AWSS3TransferManager to upload and download files.
—
Reply to this email directly or 
view it on GitHub.

**Comment by yosuke-matsuda** [comment]
From the SDK point of view, there is no difference between images and videos since they are stored as a binary in Amazon S3. You just need to be careful with your MIME type. You should take a look at the sample.
