### ISSUE TITLE
how can i set connection timeout in s3 sdk 2 upload ios 

### ISSUE THREAD

**Issue by abeeriqbal** [aws/aws-sdk-ios#129]
whenever my network is slow or my file taking  more than 30 second to upload i want to cancel this upload. i know i can use NSTimer but if there is any property in awstrasferManger or in putobjectRequest that can help.So please tell me how can i set timeout

      
     AWSS3TransferManager *transferManager = [AWSS3TransferManager    defaultS3TransferManager];
    AWSS3TransferManagerUploadRequest *uploadRequest =       [AWSS3TransferManagerUploadRequest new];
    uploadRequest.bucket = [Constants pictureBucket];
    uploadRequest.key = imageName;
    uploadRequest.body = fileUrl;
    uploadRequest.contentType = isPNG ? @"image/png" : @"image/jpeg";
    
        uploadRequest.contentLength = [NSNumber numberWithUnsignedLongLong:imageData.length];
    [[transferManager upload:uploadRequest] continueWithBlock:^id(BFTask *task) {
        BOOL isError = (task.error == nil) ? NO : YES;
        NSLog(@"response and error is %@",task.error);
     
      
        if (!isError && task.isCompleted)
        {
            
        }
        else
        {
          
        }
        return nil;
    }];

**Comment by yosuke-matsuda** [comment]
The timeout configuration is [in our back log](https://github.com/aws/aws-sdk-ios/issues/101). Thanks.

**Comment by abeeriqbal** [comment]
ok Thanks yosuke-matsuda

**Comment by dipkasyap** [comment]
@yosuke-matsuda  is it still in backlog ?
