### ISSUE TITLE
Failure to compile LlamaKit in latest version

### ISSUE THREAD

**Issue by stefanbund** [aws/aws-sdk-ios#130]
LlamaKit appears to be a new library required to build 2.0.13. I find that it is stalling the build, after I updated my pod (`pod update`). I am running into this libtool error when updating my SDK:
    
    Libtool /Users/stefanbund/Downloads/aws-sdk-ios-samples-master/CognitoSyncDemo/Build/Products/Debug-iphoneos/libPods-LlamaKit.a normal arm64
    cd /Users/stefanbund/Downloads/aws-sdk-ios-samples-master/CognitoSyncDemo/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only arm64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -L/Users/stefanbund/Downloads/aws-sdk-ios-samples-master/CognitoSyncDemo/Build/Products/Debug-iphoneos -filelist /Users/stefanbund/Downloads/aws-sdk-ios-samples-master/CognitoSyncDemo/Build/Intermediates/Pods.build/Debug-iphoneos/Pods-LlamaKit.build/Objects-normal/arm64/Pods-LlamaKit.LinkFileList -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/stefanbund/Downloads/aws-sdk-ios-samples-master/CognitoSyncDemo/Build/Intermediates/Pods.build/Debug-iphoneos/Pods-LlamaKit.build/Objects-normal/arm64/Pods_LlamaKit.swiftmodule -framework Foundation -o /Users/stefanbund/Downloads/aws-sdk-ios-samples-master/CognitoSyncDemo/Build/Products/Debug-iphoneos/libPods-LlamaKit.a

    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]    

After spending several hours researching how to overcome this libtool error, I am stumped. How are we to get past this kind of error, when updating to .13?

**Comment by yosuke-matsuda** [comment]
The AWS Mobile SDK for iOS does not use LlamaKit. It seems like you are trying to run CognitoSyncDemo. Have you modified the sample in any way? I've just confirmed I was able to run `pod install` to CognitoSyncDemo.

**Comment by stefanbund** [comment]
yes, you're exactly right. I have used the cognito sample to experiment with FB authentication.

**Comment by stefanbund** [comment]
It's been a helpful sample in integrating the latest SDK. I am about two weeks away from a published app. However, I ran into an issue getting the transfer manager to run, getting an error from [AWSXMLRequestSerializer serializeRequest:headers:parameters:] (AWSURLRequestSerialization.m:181). 

After running a breakpoint on that line I found that the parameters had been populated correctly. I believe this was flagged as a bug earlier. I then updated the SDK by running     pod update     on the sample. 

(I am hooking up the IOS Photos API to AWS/S3 via transfer manager. I was able to connect to the service, but couldn't complete my request, as detailed in https://github.com/aws/aws-sdk-ios/issues/59. )

I am able to authenticate to Cognito using an unauthenticated access, with permissions granted on S3.  

I guess I was hoping to overcome this issue with the request serializer by upgrading, but I have this new libtool error.

**Comment by yosuke-matsuda** [comment]
As I mentioned earlier, the AWS Mobile SDK for iOS does not use LlamaKit. I assume you added LlamaKit as a pod, and the newer version of LlamaKit is causing the issue in your project. The developer of LlamaKit should be able to assist you better.

**Comment by stefanbund** [comment]
Can I send you the project? It is really shutting down with this error. Thanks for your consideration,

Stefan

**Comment by stefanbund** [comment]
Thanks for this bit of help. There was an additional framework added that required building a static lib from swift, which was failing under libtool. This has been removed, and the error overcome. Thanks, SB
