### ISSUE TITLE
ifModifiedSince issues after 2.0.14

### ISSUE THREAD

**Issue by Michels10** [aws/aws-sdk-ios#138]
Hi,

I've been waiting for the ifModifiedSince fix in 2.0.14 for a while so I was glad to see the change added in the release notes, but I haven't been able to actually get it to work...

1)
I set the date like this (with an example of the NSLog below)
```
NSDictionary *attributes = [[NSFileManager defaultManager] attributesOfItemAtPath:tmp error:nil];
self.downloadRequest1.ifModifiedSince = [attributes fileModificationDate];
NSLog(@"\nLOCAL MODIFICATION: %@ FOR FILE: %@", [attributes fileModificationDate], tmp);
```
```
//Example of NSLog output:
//2015-01-20 23:39:35 +0000 FOR FILE: /var/mobile/Applications/...-993FB56000E8/Documents/MyBucket/location_99/location_99_profile_image.jpg
```
2)
Then when the file downloads (it does not return the 304 error, as the docs state it should) the `AWSS3TransferManagerDownloadOutput` says the following:

```
download output location_99_profile_image.jpg:
 <AWSS3TransferManagerDownloadOutput: 0x170576d40> {
    ETag = "\"18fb0ab78e3ed5db877e89..\"";
    acceptRanges = bytes;
    body = "file:///var/mobile/Applications/...-0536C5D21FA3/Documents/MyBucket/location_99/location_99_profile_image.jpg";
    contentEncoding = "";
    contentLength = 60994;
    contentType = "binary/octet-stream";
    lastModified = "2015-01-13 21:07:59 +0000";
    serverSideEncryption = 0;
}
```

I can post more code if needed, but this should be a fairly straight forward diagnosis. 

Thanks,

**Comment by yosuke-matsuda** [comment]
Have you made sure you are using 2.0.14? You should [enable](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html#logging) the verbose logging, and you can confirm the SDK version by looking at the `user-agent` header. The logs should help you debug the issue.

**Comment by Michels10** [comment]
I've confirmed I am using 2.0.14: 

What format should I be specifying the date in for ifModifiedSince?  Should it be the HTTP standard format? 

```If-Modified-Since: Sat, 29 Oct 1994 19:43:31 GMT```
as per: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25


Currently I am passing in a date in this format: ```2015-01-21 02:41:42 +0000```


```
AWSiOSSDKv2 [Debug] AWSSignature.m line:241 | -[AWSSignatureV4Signer signS3RequestV4:] | Canonical request: [GET
/MyBucket/location_99/location_99_header.jpg

content-type:binary/octet-stream
host:s3.amazonaws.com
if-modified-since:Wed, 21 Jan 2015 02:41:42 GMT
user-agent:aws-sdk-iOS/2.0.14 iPhone-OS/8.1 en_US
x-amz-content-sha256: ...55
x-amz-date:20150121T024929Z

content-type;host;if-modified-since;user-agent;x-amz-content-sha256;x-amz-date..55]
```

```

AWSiOSSDKv2 [Debug] AWSURLResponseSerialization.m line:258 | -[AWSXMLResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response header: [{
    Date = "Wed, 21 Jan 2015 02:56:56 GMT";
    Etag = "\"...49a2\"";
    "Last-Modified" = "Tue, 13 Jan 2015 21:08:08 GMT";
    Server = AmazonS3;
    "x-amz-id-2" = "...";
    "x-amz-request-id" = ...102;
}]

download output location_99_header.jpg:
 <AWSS3TransferManagerDownloadOutput: 0x7fface206f10> {
    ETag = "\"...49a2\"";
    lastModified = "2015-01-13 21:08:08 +0000";
    serverSideEncryption = 0;
}

```

Thanks

**Comment by yosuke-matsuda** [comment]
The data type of `ifModifiedSince` is an `NSDate` (it does not have a formatting information). According to the log above, you are sending `Wed, 21 Jan 2015 02:41:42 GMT` for `if-modified-since` and received no data with the last modified date of `Tue, 13 Jan 2015 21:08:08 GMT`. It seems like an expected behavior. What issue are you having?

**Comment by Michels10** [comment]
You're right, for some reason I thought it would raise an error.  One last last thing, if I use a pre-signed url to create an ```NSURLSessionDownloadTask``` or ```NSURLRequest```, will the functionality be identical?

After this feel free to close the issue.

Thanks for your help.

**Comment by yosuke-matsuda** [comment]
The additional headers need to be signed as well, and currently `AWSS3PreSignedURLBuilder` does not support the `ifModifiedSince` attribute. However, we are planning to add more customization options to `AWSS3PreSignedURLBuilder` in the coming releases. Thanks.
