### ISSUE TITLE
Amazon Latest SDK integration with iOS gives error

### ISSUE THREAD

**Issue by Bhat123** [aws/aws-sdk-ios#139]
I am developing an app for iPhone and have integrated Amazon SDK v 2.0.10 for performing file transfer.

When i try to integrate the latest SDK v i.e, 2.0.13 i get the following error. Please help me out.
Errors:
```
duplicate symbol _OBJC_IVAR_$_BFWebViewAppLinkResolverWebViewDelegate._didFailLoadWithError in:
    Cryptall/Classes/Third Party Libraries/Amazon S3/frameworks/AWSiOSSDKv2.framework/AWSiOSSDKv2(BFWebViewAppLinkResolver.o)
    Cryptall/Classes/Third Party Libraries/Amazon S3/third-party/Bolts.framework/Bolts(BFWebViewAppLinkResolver.o)
duplicate symbol _OBJC_IVAR_$_BFWebViewAppLinkResolverWebViewDelegate._hasLoaded in:
    Cryptall/Classes/Third Party Libraries/Amazon S3/frameworks/AWSiOSSDKv2.framework/AWSiOSSDKv2(BFWebViewAppLinkResolver.o)
    Cryptall/Classes/Third Party Libraries/Amazon S3/third-party/Bolts.framework/Bolts(BFWebViewAppLinkResolver.o)
duplicate symbol _OBJC_METACLASS_$_BFWebViewAppLinkResolverWebViewDelegate in:
    Cryptall/Classes/Third Party Libraries/Amazon S3/frameworks/AWSiOSSDKv2.framework/AWSiOSSDKv2(BFWebViewAppLinkResolver.o)
    Cryptall/Classes/Third Party Libraries/Amazon S3/third-party/Bolts.framework/Bolts(BFWebViewAppLinkResolver.o)
duplicate symbol _OBJC_CLASS_$_BFWebViewAppLinkResolverWebViewDelegate in:
    Cryptall/Classes/Third Party Libraries/Amazon S3/frameworks/AWSiOSSDKv2.framework/AWSiOSSDKv2(BFWebViewAppLinkResolver.o)
    Cryptall/Classes/Third Party Libraries/Amazon S3/third-party/Bolts.framework/Bolts(BFWebViewAppLinkResolver.o)
duplicate symbol _OBJC_METACLASS_$_BFWebViewAppLinkResolver in:
    Cryptall/Classes/Third Party Libraries/Amazon S3/frameworks/AWSiOSSDKv2.framework/AWSiOSSDKv2(BFWebViewAppLinkResolver.o)
```

Already raised a concern in the below link.
http://stackoverflow.com/questions/28112400/amazon-latest-sdk-integration-with-ios-gives-error/28112610#28112610

Regards,
Bhat

**Comment by yosuke-matsuda** [comment]
Thank you for bringing the issue to our attention. The AWS Mobile SDK for iOS 2.0.12 and 2.0.13 unintentionally embed the third party libraries  in `AWSiOSSDKv2.framework`. We updated the version of CocoaPods, and the new version adds each pod to **Other Linker Flags**, which resulted in the inclusion of the third party libraries in the main framework.

We've released 2.0.15 to address the issue.

Thanks,

**Comment by Bhat123** [comment]
Started receiving below one after replacing...
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_FMDatabaseQueue", referenced from:
      objc-class-ref in AWSiOSSDKv2(AWSKinesisRecorder.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yosuke-matsuda** [comment]
It seems like you are not including `FMDB.framework` (it's under the third-party directory).

**Comment by Bhat123** [comment]
Yosuke, I did not see FMDB.framework was not there when i downloaded aws-ios-sdk-2.0.15 version.

**Comment by yosuke-matsuda** [comment]
Could you clear the browser cache and download the SDK again? If you still do not see `FMDB.framework`, please let us know. Thanks.

**Comment by Bhat123** [comment]
I downloaded the fmdb version and integrated. Now it is working.
