### ISSUE TITLE
AWSAbstractIdentityProvider and Swift

### ISSUE THREAD

**Issue by pgherveou** [aws/aws-sdk-ios#140]
When you want to subclass AWSAbstractIdentityProvider in swift you need to override  the readonly token property, to set it later in the refresh method 

I did something like this
```swift
  var _token: String!
  override var token: String! {
    get {
      return _token
    }
  }
```

Does this property really need to be read only? It would be cleaner not to have to override this property in subclasses dont you think?

**Comment by yosuke-matsuda** [comment]
`token` should not be modified outside of the identity provider, so making it a read-only property semantically makes sense. Also, overriding a property in a subclass seems appropriate.

Swift is new, and the community is still trying to form conventions and best practices. Hopefully, Apple provides more and more of the best practices we all can follow. If you know any guidelines from Apple regarding this topic, we try to align our SDK to the community.
