### ISSUE TITLE
[AWSS3TransferManagerUploadRequest encodeWithCoder:]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by jhyu** [aws/aws-sdk-ios#141]
I'm having issues uploading an image using the mobile iOS SDK. I'm using CocoaPods. 
```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e455f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010e0bfbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010e45d04d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010e3b527c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010e3b4e18 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x000000010b858e85 _encodeObject + 1120
	6   Foundation                          0x000000010b895085 +[NSKeyedArchiver archiveRootObject:toFile:] + 241
	7   TheSnappning                        0x000000010b1f9460 __38-[TMDiskCache setObject:forKey:block:]_block_invoke_2 + 368
	8   libdispatch.dylib                   0x000000010e92fba6 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000010e94d7f4 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010e935b22 _dispatch_queue_drain + 1417
	11  libdispatch.dylib                   0x000000010e935432 _dispatch_queue_invoke + 235
	12  libdispatch.dylib                   0x000000010e937fc1 _dispatch_root_queue_drain + 685
	13  libdispatch.dylib                   0x000000010e9395d9 _dispatch_worker_thread3 + 111
	14  libsystem_pthread.dylib             0x000000010ecd16cb _pthread_wqthread + 729
	15  libsystem_pthread.dylib             0x000000010eccf4a1 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```
Here's the code:

    NSString *fileName = [[[NSProcessInfo processInfo] globallyUniqueString] stringByAppendingString:@".png"];
    
    NSData * imageData = UIImagePNGRepresentation([UIImage imageNamed:@"Icon-60@2x-1.png"]);
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    NSString *appFile = [documentsDirectory stringByAppendingPathComponent:fileName];
    [imageData writeToFile:appFile atomically:YES];
    
    AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];
    AWSS3TransferManagerUploadRequest *uploadRequest = [AWSS3TransferManagerUploadRequest new];
    uploadRequest.body = [NSURL fileURLWithPath:appFile];
    uploadRequest.key = fileName;
    uploadRequest.bucket = @"test";
    
    
    [[transferManager upload:uploadRequest] continueWithExecutor:[BFExecutor mainThreadExecutor]
                                                       withBlock:^id(BFTask *task) {
                                                           if (task.error) {
                                                               if ([task.error.domain isEqualToString:AWSS3TransferManagerErrorDomain]) {
                                                                   switch (task.error.code) {
                                                                       case AWSS3TransferManagerErrorCancelled:
                                                                       case AWSS3TransferManagerErrorPaused:
                                                                           break;
                                                                           
                                                                       default:
                                                                           NSLog(@"Error: %@", task.error);
                                                                           break;
                                                                   }
                                                               } else {
                                                                   // Unknown error.
                                                                   NSLog(@"Error: %@", task.error);
                                                               }
                                                           }
                                                           
                                                           if (task.result) {
                                                               AWSS3TransferManagerUploadOutput *uploadOutput = task.result;
                                                               // The file uploaded successfully.
                                                           }
                                                           return nil;
                                                       }];

**Comment by yosuke-matsuda** [comment]
We have an `AWSS3TranferManager` sample app in our GitHub [repo](https://github.com/awslabs/aws-sdk-ios-samples). Have you tried running it? Do you see the same issue?

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to update the thread if you continue to see the issue.
