### ISSUE TITLE
SSECustomerKey 

### ISSUE THREAD

**Issue by mcsio** [aws/aws-sdk-ios#142]
I'm having trouble using the customer provided encryption key.  I provide all three headers:

    "x-amz-server-side-encryption" = AES256;
    "x-amz-server-side-encryption-customer-algorithm" = AES256;
    "x-amz-server-side-encryption-customer-key" = "=1\U00cd)b^DQ\U00de^U^R$^L\U00ce\U00a8\U00b1DY\U00e1\U00d4^Lv\U00abh\U00ae?o&6^Y<86>8";

My key is really =1Í)b^DQÞ^U^R$^LÎ¨±DYáÔ^Lv«h®?o&6^Y<86>8
But it looks like AWS escapes it?

The error I get is:
The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by mcsio** [comment]
I also have the md5 in the header but it doesn't change the error 
    "x-amz-server-side-encryption-customer-key-MD5" = b4e05563e057efb55e34cc525ea0f347;

**Comment by yosuke-matsuda** [comment]
You are not base64 encoding the `x-amz-server-side-encryption-aws-kms-key-id`. Take a look at [Server-Side Encryption Specific Request Headers](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#put-object-sse-specific-request-headers) for further details.

**Comment by mcsio** [comment]
I had tried that also.  But I get "Server Side Encryption with Customer provided key is incompatible with the encryption method specified"  It would really help if I had some real examples not fake strings used in Server-Side Encryption Specific Request Headers.  Thanks.


Key = 1Í)b^DQÞ^U^R$^LÎ¨±DYáÔ^Lv«h®?o&6^Y<86>8
Headers:
    "x-amz-server-side-encryption" = AES256;
    "x-amz-server-side-encryption-customer-algorithm" = AES256;
    "x-amz-server-side-encryption-customer-key" = "PTHDjSliXkRRw55eVV5SJF5Mw47CqMKxRFnDocOUXkx2wqtowq4/byY2Xlk8ODY+OA==";
    "x-amz-server-side-encryption-customer-key-MD5" = b4e05563e057efb55e34cc525ea0f347;

**Comment by mcsio** [comment]
Also why do you keep closing the issue so fast.  I can't see how to open it again?

**Comment by mcsio** [comment]
Can you give an example of a key, "x-amz-server-side-encryption-customer-key", and "x-amz-server-side-encryption-customer-key-MD5" that work?

**Comment by mcsio** [comment]
Why do you close the issues so fast - I just posted more questions on this.  Is there a way for me to open it again?

Scott

**Comment by yosuke-matsuda** [comment]
[Amazon S3 Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) is the best place to connect with other developers regarding how to use the service. A quick search returned a few threads including [this thread](https://forums.aws.amazon.com/thread.jspa?messageID=597690), which should address your question.
