### ISSUE TITLE
issue with cocoapods 0.36.0.beta.2

### ISSUE THREAD

**Issue by szehnder** [aws/aws-sdk-ios#146]
I am seeing the following error in XCode when I try to add the lib via pod install.

**Podfile**
    
    ...
    pod 'AWSiOSSDKv2'

Pods/Headers/Private/AWSiOSSDKv2/AWSMobileAnalyticsContext.h:17:9: 'configuration/AWSMobileAnalyticsConfiguring.h' file not found

I've gone through and tried making the modifications to the pod to get it to work as a dynamic framework (as that's what the cocoapods beta is using now), to no avail.  

I'm using XCode Version 6.2 (6C107a)

When do you think you will be able to add cocoapods beta2 support?

**Comment by yosuke-matsuda** [comment]
Please see #145
