### ISSUE TITLE
unable to access aws sdk in custom class

### ISSUE THREAD

**Issue by RyanPliske** [aws/aws-sdk-ios#147]
I'm able to to successfully implement the AWS methods within any of my viewcontrollers, but when I attempt to do so in a custom class such as "AmazonHandlerMode.swift" that I've created, then XCode doesn't recognize the aws module. 

I've looked at the example code and see that all of them do their aws uploading in a viewcontroller. What happens if the user leaves the view while the request is still occurring? My viewcontroller doesn't complete the request.

How can I "import" the Amazon module into a custom class? My installation method is using CoCoa Pods. Much help appreciated. Thank you.
@yosuke-matsuda @brsunter

**Comment by RealNerd** [comment]
Did you create the bridging header file (https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-XID_77)? Once you have that file, you should #import the AWS headers in the bridging header and they will then be available to your Swift code.

**Comment by RyanPliske** [comment]
Yes. I did that. It's pretty weird. Like I said i'm able to access them from viewcontrollers within my project, but not from any other .swift files. Interestingly, I'm able to access them if I include the .frameworks, but not by Cocoa Pods.

**Comment by RyanPliske** [comment]
Yes. I did that. It's pretty weird. Like I said i'm able to access them from viewcontrollers within my project, but not from any other .swift files. Interestingly, I'm able to access them if I include the .frameworks, but not by Cocoa Pods.

**Comment by yosuke-matsuda** [comment]
I am able to use AWS classes from non-view controller classes with the latest version of Xcode and the AWS SDK in Swift. Can you share the content of your Objective-C Bridging Header and your custom class implementation where you get the compiler error?

**Comment by RyanPliske** [comment]
by latest version of XCode do you mean the 6.3 Beta that came out last night? Because I tried using that and it broke the .m and .h source files for Alamofire in a few places.
I am running 0.35.0 CocoaPods. My bridging header is quite simply #import "Alamofire.h".

Podfile has: pod 'Alamofire', '~> 1.1' within it.

My custom class isn't much to share either.

    class CameraModel {
        var numberOfPhotosPurchased : Int
        var numberOfPhotosUsed : Int
        var cameraID : Int!
        var arrayOfPhotos_ThatFailedToUpload : [Int]!
  
      init(photosPurchased : Int){
        self.numberOfPhotosUsed = 0
        self.numberOfPhotosPurchased = photosPurchased
      }
    }

I've had success including the source files into my project allowing me access in the class. But all of the pods I use just aren't recognized in my non view controller classes.

**Comment by RealNerd** [comment]
Did you have two questions? Originally you mentioned trouble using AWS, but your last comment is about Alamofire. If you're using both frameworks, then your bridging header should include an import for the AWS features you're using, in addition to the import for Alamofire.

**Comment by RyanPliske** [comment]
whoops my fault. you're correct. I guess my question is for Cocoapods in general. all of my cocoapods behave this way. I just realized that. I'd love to figure this out but I understand if you all haven't seen this behavior from cocoapods before. I've spent a few days on this and at this point, I'm just going to not use cocoapods ever again.

**Comment by RealNerd** [comment]
No problem. I actually haven't seen this problem myself. I include all of the required #import lines in my bridging header and it works throughout my Swift code, view controller or not. I don't have a lot of experience with Swift yet, but so far, for me, importing Objective-C libraries using CocoaPods just works.

**Comment by RyanPliske** [comment]
lucky dawg you.

**Comment by yosuke-matsuda** [comment]
I should have said "the latest production version of Xcode," which is currently 6.1.1. We do not support beta versions of products unless otherwise specified. We try to support Xcode 6.3 when it reaches GA. Closing the issue for now, but if you are encountering the issue with Xcode 6.1, please let us know. Thanks.
