### ISSUE TITLE
#import "../core/AWSMobileAnalyticsContext.h" not found

### ISSUE THREAD

**Issue by need2edit** [aws/aws-sdk-ios#148]
Build Fails with error:  #import "../core/AWSMobileAnalyticsContext.h" not found
— Using CocoaPods 0.35.0 with Swift iOS SDK 8.1, Xcode 6.1.1.  
— Trying to build project with Amazon SDK v2
— Target set to 8.1
![core-not-found](https://cloud.githubusercontent.com/assets/6213423/6123942/9298450e-b0d6-11e4-8eef-ffae8adb28aa.png)

**Comment by yosuke-matsuda** [comment]
Can you share the content of your Objective-C Bridging Header?

**Comment by need2edit** [comment]
```
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//
#import "S3.h"
```


##Additional Note:
If more AWS files are imported, like AWSCore, DynamoDB, etc, more of these not found preprocessor errors fire.  We only need the S3 API currently, but this may be helpful as well.

**Comment by yosuke-matsuda** [comment]
I cannot reproduce the issue with your environments (CocoaPods 0.35.0, Swift, iOS SDK 8.1, and Xcode 6.1.1). Have you cleaned up Xcode temporary directory, removed `Pods` and `Podfile.lock`, and rerun `pod install` while Xcode is not running?

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to let us know if you keep encountering the problem. Thanks.
