### ISSUE TITLE
AWS Mobile SDK v2.0.15 | Download Link not working

### ISSUE THREAD

**Issue by faizankhan1909** [aws/aws-sdk-ios#153]
Hi,
   I want to download SDK v2.0.15 framework by clicking "Download the AWS SDK for iOS 2.0.15" link on the following URL:

https://aws.amazon.com/releasenotes/iOS/2185076487836985

It just redirects me to the link: http://aws.amazon.com/mobile/sdk/ and is not allowing me to download specific version of the framework. I can download the latest SDK but unable to download specific version.

**Comment by yosuke-matsuda** [comment]
You can use [this link](http://sdk-for-ios.amazonwebservices.com/aws-ios-sdk-2.0.15.zip) to download the AWS Mobile SDK for iOS 2.0.15.
