### ISSUE TITLE
AWSDynamoDBObjectMapper NSNumberFormatter don't take into account different type of Locale

### ISSUE THREAD

**Issue by andreineacsu** [aws/aws-sdk-ios#155]
Hello,

I would like to let you know that AWSDynamoDBObjectMapper `aws_getAttributeValueWithVersion` method is not taking into account that NSNumberFormatter is taking into account the user's Locale settings. For example, I'm in Romania and the NSNumberFormatter failed to parse a number formatted like 12345.677 because in Romania we're not using period but comma (the number would be formatted like this: 12345,677). NSNumberFormatter failed to parse the NSString and caused an internal exception to be raised. 

I suggest forcing the NSNumberFormatter decimalSeparator to `@"."`:

    NSNumberFormatter *numberFormatter = [NSNumberFormatter new];
    numberFormatter.numberStyle = NSNumberFormatterDecimalStyle;
    numberFormatter.decimalSeparator = @".";
    id val = [numberFormatter numberFromString:self.N];
    return val;

Best Regards,
Andrei

**Comment by yosuke-matsuda** [comment]
Thank you for bringing the issue to our attention. We will address it in the upcoming release. Thank you.

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.0.17, which addresses the issue. Thanks.
