### ISSUE TITLE
ETag and If-Modified-Since

### ISSUE THREAD

**Issue by donileo** [aws/aws-sdk-ios#156]
I am attempting to get S3 to reply back with a 304 Not modified error but for the life of me cannot. Prior to requesting a file to be downloaded I specified the AWSS3TransferManagerDownloadRequest properties to be

      downloadRequest.ifNoneMatch = fileEtag;
      downloadRequest.ifModifiedSince = ifModifiedForFile

every single time i ask for the file from S3 it is delivered to me without checks.. yet if I do a IfNoneMatch then yes an error is returned as it should be. Whats going on? I checked my code and even debugged the SDK itself to make sure S3 was being sent the information but nope.

**Comment by yosuke-matsuda** [comment]
Can you enable the [verbose logging](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html#logging) and look at the logs? It is a great first step in debugging any issues. [This thread](https://github.com/aws/aws-sdk-ios/issues/138) may help as well.

**Comment by donileo** [comment]
Hi Yosuke yes the link to that thread is the same issue I'm having. The confusion and problem in my opinion is that the documentation states that a 304 error should be returned but the console never shows no such error. The verbose logging shows no such error either. This is further complicated by the fact that the SDK seems to do its own internal caching so with no error warning or any sign its very hard to know if its working. What is funny is that using the IfMatch field does return an error and its clearly visible but IfNoneMatch and IfModifiedSince do not and I think thats where the problem lays.

**Comment by yosuke-matsuda** [comment]
Can you share the logs so that we can assist you debug the issue?

**Comment by donileo** [comment]
Yes I can shared the logs.. 

2015-03-04 15:04:23.341 Myapp[19884:2342993] AWSiOSSDKv2 [Verbose] AWSURLRequestSerialization.m line:195 | -[AWSXMLRequestSerializer serializeRequest:headers:parameters:] | Request body: []
2015-03-04 15:04:23.343 Myapp[19884:2342993] AWSiOSSDKv2 [Debug] AWSSignature.m line:241 | -[AWSSignatureV4Signer signS3RequestV4:] | Canonical request: [GET
/<redacted>/users/person49_photo1.jpg

content-type:binary/octet-stream
host:s3.amazonaws.com
if-none-match:"8e7fdb41d916ba4326180957121c87b6"
user-agent:aws-sdk-iOS/2.0.16 iPhone-OS/8.1 en_US
x-amz-content-sha256:<redacted>
x-amz-date:20150304T200423Z
x-amz-security-token:<redacted>

content-type;host;if-none-match;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token
<redacted>]
2015-03-04 15:04:23.344 Myapp[19884:2342993] AWSiOSSDKv2 [Debug] AWSSignature.m line:248 | -[AWSSignatureV4Signer signS3RequestV4:] | AWS4 String to Sign: [AWS4-HMAC-SHA256
20150304T200423Z
20150304/us-east-1/s3/aws4_request
<redacted>]
2015-03-04 15:04:23.616 Myapp[19884:2342993] AWSiOSSDKv2 [Debug] AWSURLResponseSerialization.m line:258 | -[AWSXMLResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response header: [{
    Date = "Wed, 04 Mar 2015 20:04:20 GMT";
    Etag = "\"8e7fdb41d916ba4326180957121c87b6\"";
    "Last-Modified" = "Wed, 04 Mar 2015 16:24:03 GMT";
    Server = AmazonS3;
    "x-amz-id-2" = <redacted>;
    "x-amz-request-id" = <redacted>;
}]
2015-03-04 15:04:23.634 Myapp[19884:2342993] Item users/person49_photo1.jpg downloaded successfully <AWSS3TransferManagerDownloadOutput: 0x7f993d05cf60> {
    ETag = "\"8e7fdb41d916ba4326180957121c87b6\"";
    lastModified = "2015-03-04 16:24:03 +0000";
    serverSideEncryption = 0;
}

As you can see here the request is properly made with a if-none-match matching the Etag of the file being requested yet no error is returned. I obviously redacted my bucket name and anything i deemed a security issue to reveal.

**Comment by yosuke-matsuda** [comment]
Based on the log, `ifNoneMatch` seems to be working as expected. HTTP status code 3xx indicates redirection and not error. The AWS SDK returns `NSError` only for 4xx (client errors) and 5xx (server errors). The log shows the `body` property is `nil`, and the file was not downloaded, which is what you are expecting.

Could you double check if the SDK actually downloaded the file when it should not have? Thanks.

**Comment by donileo** [comment]
I understand, after testing I did confirm it was working correctly but again maybe it would great to add to the documentation/header files that the 302 errors returned don't show as actual errors in the console as implied. Its because of that confusion that I believed the SDK wasn't working as it should.
