### ISSUE TITLE
Uploading using accessKey and signature, instead of accessKey and secret

### ISSUE THREAD

**Issue by colinta** [aws/aws-sdk-ios#158]
I've searched high and low looking for a definitive "supported / not supported / won't support", but I can't find anything, so here goes.

Our API is returning AWS credentials in the form of `accessKey / bucket (prefix) / signature / policy` values, and I'm uploading images to these temporary buckets.

I'd much rather be using AWS's SDK, so that I could reap the benefits of large uploads, resumable uploads, etc.  Is there any planned support for using `signature` instead of `secret`?

**Comment by yosuke-matsuda** [comment]
I assume you are talking about [Authenticating Requests in Browser-Based Uploads Using POST](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html). We currently do not have any plan to support this. You can use `AccessKey` and `SecretKey` already present on your server with Amazon STS to generate the AWS temporary credentials for the SDK.

**Comment by colinta** [comment]
Gotcha - thanks for the info!  Makes sense.  We're "porting" the web-app features into the iOS app, so for now we'll continue with the browser-based-POST solution, and upgrade to AWS SDK in the future when we need those features.
