### ISSUE TITLE
Please document logins in AWSAbstractIdentityProvider

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#160]
```objective-c
/**
 * Each entry in logins represents a single login with an identity provider.
 * The key is the domain of the login provider (e.g. 'graph.facebook.com') and the value is the
 * OAuth/OpenId Connect token that results from an authentication with that login provider.
 */
@property (nonatomic, strong) NSDictionary *logins;
```

I read this five times and for the life of me still don't understand how i'm supposed to subclass this.  Does "OAuth/OpenId" mean the the token i got from my server using `get_open_id_token_for_developer_identity` or is this *my* token.  

There are examples floating everywhere now that are essentially people shoving random values into this dictionary.  :(   eg http://stackoverflow.com/questions/26290256/aws-cognito-ios-developer-authenticated-identities/26741208#26741208

**Comment by turacma** [comment]
Sorry for the confusion, we'll definitely work on updating the docs to better reflect a recommended solution.

Please look at my update which includes a link to [an end-to-end sample](http://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en).

**Comment by rromanchuk** [comment]
@turacma It only starts getting tricky when the developer supports authenticated and unauthenticated identity pools... it starts getting complex fast.  Side note, is twitter/digits anywhere on the roadmap?

**Comment by turacma** [comment]
@rromanchuk Correct, supporting unauthenticated, public providers and developer authenticated identities can get tricky. I again apologize for the state of the documentation. This is something we are actively working on to try and and improve.

Twitter/digits support is a request we have heard from a lot of customers so it is definitely something that is on our roadmap, but I can't commit to a timeline of if/when it would be available.

**Comment by helloniklas** [comment]
This has all stopped working no with 2.4.0 it seems as AWSAbstractCognitoIdentityProvider is no longer available. Any ideas how to rewrite all this?

**Comment by googoodalls** [comment]
same as helloiklas.
AWSAbstractCognitoIdentityProvider class is disappeared  in v2.4.0
Down vote for this update.

**Comment by yosuke-matsuda** [comment]
The `logins` dictionary has been deprecated. We are preparing the sample app updates, and it should be available soon. When we update our samples, we'll update [this thread](https://github.com/aws/aws-sdk-ios/issues/357). Thanks.

**Comment by apatrida** [comment]
@turacma @yosuke-matsuda ... the other thread isn't updated either.
