### ISSUE TITLE
Is AWS Lambda support on the road map? 

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#161]

**Comment by yosuke-matsuda** [comment]
We are actively working on adding Lambda support to the AWS Mobile SDK. When we release it, I'll update this thread. Thanks.

**Comment by rromanchuk** [comment]
Sweet! :+1:

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.1.1 with the AWS Lambda support. Thanks.

**Comment by rromanchuk** [comment]
:beers:
