### ISSUE TITLE
Local file removed when S3 does not return HTTP body

### ISSUE THREAD

**Issue by donileo** [aws/aws-sdk-ios#166]
So i have AWSS3TransferManager set to download some images to my app doc directory and I set the if-none-match and if-modified-since fields of the AWSS3TransferManagerDownloadRequest. When I call the AWSS3TransferManager download method to download the files the AWSS3TransferManager will always delete the file already have stored on disk. How is this caching? What'll happen is that upon further requests to download the same file i again set the if-none-match, if-modified-since tags on the DownloadRequest but because the tags do match they aren't downloaded which is correct. If the file I'm requesting is a file I supposedly have stored with a matching Etag it shouldn't download..  However in that download request my disk files are deleted :( ! Here are the lines of code which i am baffled as to  how it allows caching with the if-modified-since and if-none-match.

lines 465-469 of AWSS3TransferManager.m state

>else {
>            //if file already existed, remove it to avoid received data has been appended to exist file.
>            [[NSFileManager defaultManager] removeItemAtURL:downloadRequest.downloadingFileURL >error:nil];
>        }

Yet, again..if the requested file is always removed from disk prior to downloading what was the point of
specifying the if-none-match and if-modified-since?

Some more thought into the lines above leads me to believe that it is wrong to assume that the S3TransferManager will actually return a file. In the case of using a if-none-match or if-modified-since no files would be returned so its wrong to assume as the above lines do that a file will actually be returned and the file will be appended to. The file should only be removed when we know for sure new data is coming back.

**Comment by yosuke-matsuda** [comment]
`AWSS3TransferManager` does not support caching, and the developers have to handle the objects based on their use cases.

However, removing the local file when the service returns `nil` for body seems like a bug. We will address it and update the thread when it is done.

**Comment by Michels10** [comment]
I ran into this issue as well and figured I would suggest a fix. I can make a pull request if needed.

As of AWSS3 v2.1.2:

in AWSS3TransferManager.m I would suggest changing line 576 from 
`if (tempFileURL && originalFileURL) {` 
to 
`if (([[NSFileManager defaultManager] fileExistsAtPath:tempFileURL.path]) && originalFileURL) {`

This will prevent the file from being overwritten if nothing is downloaded.  e.g. in the event that ifModifiedSince is set and nothing is in the body of the reqest after completion.

Please let me know what your thoughts are.  This has solved the problem for myself and my team.

**Comment by yyzhu** [comment]
We've just release AWs Mobile SDK for iOS v2.2.2 which should solve this issue. Could you have a try and let us know if everything is good?
