### ISSUE TITLE
Undefined symbols for architecture armv7:  "_aws_loadGZIP", "_aws_loadMTLPredefinedTransformerAdditions", "_aws_loadMTLNSCoding"

### ISSUE THREAD

**Issue by mikebevz** [aws/aws-sdk-ios#168]
Hi,
I've got XCode 6.2, Swift project, added SDK (v2) manually

When I try to compile my project for my iPhone 5 I see the following

```
"Undefined symbols for architecture armv7:
  "_aws_loadGZIP", referenced from:
      ___29+[AWSCategory loadCategories]_block_invoke in AWSiOSSDKv2(AWSCategory.o)
  "_aws_loadMTLPredefinedTransformerAdditions", referenced from:
      ___29+[AWSCategory loadCategories]_block_invoke in AWSiOSSDKv2(AWSCategory.o)
  "_aws_loadMTLNSCoding", referenced from:
      ___29+[AWSCategory loadCategories]_block_invoke in AWSiOSSDKv2(AWSCategory.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"
```

Any idea what can be wrong?

**Comment by yosuke-matsuda** [comment]
Can you describe the steps you took to import the framework into your project? Please list all of the steps as detailed as possible so that we can assist you better. Thanks.

**Comment by prestonwpope** [comment]
@mikebevz any update on this? I've having the same problem and cannot seem to solve it.

**Comment by yosuke-matsuda** [comment]
Closing the thread. If you continue to see the issue, please feel free to update the thread with additional information. Thanks.

**Comment by ajay2c9** [comment]
hai i Install the framework using the pods and i got this error all pods are installed and i got above errors
