### ISSUE TITLE
DynamoDB silent failure inserting objects via mapper

### ISSUE THREAD

**Issue by drmarkpowell** [aws/aws-sdk-ios#170]
If you configure an object mapper for DynamoDB that has empty strings for any of the fields, trying to write its information to the database will silently fail with no error or exception thrown. It is far too easy to miss a write failure because a field is accidentally empty. This requirement of DynamoDB should be explicitly validated and exceptions and/or errors generated for invalid objects.

In the following snippet, if any of the field of myObject are empty or NULL, the write will silently fail.

    [[dynamoDBObjectMapper save:myObject]
         continueWithExecutor:[BFExecutor mainThreadExecutor]
         withBlock:^id(BFTask *task) {
             if (task.error) NSLog(@"Dynamo error %@", task.error);
             if (task.exception) {
                 NSLog(@"The request failed. Exception: [%@]", task.exception);
             }
             //This block will be executed after the table row is saved.
             NSLog(@"recorded object status in Dynamo for id %@", myObject.myobj_id);
             return nil;
         }];

**Comment by yosuke-matsuda** [comment]
What version of the SDK are you using? Does it silently fail when you use the AWS Mobile SDK for iOS 2.1.0? Thanks,

**Comment by drmarkpowell** [comment]
I'm still on 2.0.12 because I'm waiting for resolution on my pull request for Govcloud support:
https://github.com/aws/aws-sdk-ios/pull/110

I'll try to reintegrate this mod into 2.1.0 and see if it resolves the silent failure.

**Comment by yosuke-matsuda** [comment]
We fixed a silent failure issue with the `- save:` method with [2.0.14](https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#2014). Hopefully, using the latest version resolves the issue.

**Comment by drmarkpowell** [comment]
Yes, in version 2.1.0 the sdk now throws an error. This is an example of what I saw:
Dynamo error Error Domain=com.amazonaws.AWSDynamoDBErrorDomain Code=0 "The operation couldn’t be completed. (com.amazonaws.AWSDynamoDBErrorDomain error 0.)" UserInfo=0x176467140 {__type=com.amazon.coral.validate#ValidationException, message=One or more parameter values were invalid: An AttributeValue may not contain an empty string}
