### ISSUE TITLE
Can i get url of file in S3?

### ISSUE THREAD

**Issue by Anhnh** [aws/aws-sdk-ios#172]
I found solution to get url of file in S3 at reference 
https://aws.amazon.com/articles/SDKs/iOS/3002109349624271
But in new SDK version (2.1.0), i can't do that.  So, how can i get url of the file in S3 with SDK version 2.1.0?
Thanks!

**Comment by yosuke-matsuda** [comment]
You can use `AWSS3PreSignedURLBuilder` to generate a presigned URL for Amazon S3 objects. You can take a look at [S3BackgroundTransfer-Sample](https://github.com/awslabs/aws-sdk-ios-samples) for some sample code.

**Comment by Anhnh** [comment]
Thank you so much!!!
