### ISSUE TITLE
AWSiOSSDKv2 is missing

### ISSUE THREAD

**Issue by Bhat123** [aws/aws-sdk-ios#173]
I just downloaded the amazon SDK form the link: http://aws.amazon.com/mobile/sdk/.

 But it does not contain the AWSiOSSDKv2.framework in it. When i used the version 2.0.15 and the above mentioned framework was present . But in the version 2.1.0 AWSiOSSDKv2 framework is not there.

Regards, 
Chandrika

**Comment by yosuke-matsuda** [comment]
We have split `AWSiOSSDKv2.framework` into the core and a framework per-service in version 2.1.0. See this blog [post](http://mobile.awsblog.com/post/Tx3OJX4PLAUJEH0/The-AWS-Mobile-SDK-for-iOS-2-1-0-Split-Frameworks) for more details.
