### ISSUE TITLE
Random request signature failures

### ISSUE THREAD

**Issue by azinman** [aws/aws-sdk-ios#174]
I'm having an issue where randomly where since having moved from the 1.9.x SDK to 2.1.0, maybe 5-10% of the time I'm seeing upload failures on a key signing issue. The key is the same every time -- that never changes (and yes I know that I'm to go a more secure route soon, but for now this is guaranteed a constant). What's odd is the same file, uploading to the same location, will work again so it's not like the path itself is the problem.

The region is AWSRegionUSWest2

Here is the error:

In trying to upload to a path like 1745e208-aa8e-3880-a8b9-948c0193855a/hRvru7ZT8gQ.jpg

I get:

```
Error Domain=com.amazonaws.AWSGeneralErrorDomain Code=3 "The operation couldn’t be completed. (com.amazonaws.AWSGeneralErrorDomain error 3.)" 
UserInfo=0x1743bb660 
{SignatureProvided=51d8cea5d752faf3890ca5cf9bc588f8f5aca4b0291a8d33df5fd5d3151c9ddb, 
RequestId=0AC31B47736FBFB9, 
StringToSign=AWS4-HMAC-SHA256-PAYLOAD\n20150329T232305Z\n20150329/us-west-2/s3/aws4_request\<access request>, 
Code=SignatureDoesNotMatch, 
HostId=<host id>, 
StringToSignBytes=<bytes>, 
AWSAccessKeyId=<ACCESS KEY>, 
Message=The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Again... I'll be able to try again to the EXACT SAME PATH with the EXACT SAME DATA and it'll work in a future request.

**Comment by yosuke-matsuda** [comment]
Amazon S3 occasionally returns a `SignatureDoesNotMatch` exception with temporary credentials probably due to its massively distributed nature. In this situation, the SDK just retries the request. Does the latest version of the SDK automatically retry the request? If it does not, please let us know. Thanks.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. If you continue to experience the problem, please feel free to update the thread.
