### ISSUE TITLE
Bugs with UICKeyChainStore

### ISSUE THREAD

**Issue by jeremiahbunton** [aws/aws-sdk-ios#175]
It seems that there are some semantic issues in the code:  missing semicolons and "use of undeclared identifiers" in the UICKeyChainStore pod.  Any help would be greatly appreciated.

Thank you.

**Comment by yosuke-matsuda** [comment]
Please post your `Podfile` and the version of Xcode so that we can see if we can reproduce the issue.

However, UICKeyChainStore's GitHub [repo](https://github.com/kishikawakatsumi/UICKeyChainStore/issues) is probably more appropriate to discuss semantic issues in UICKeyChainStore.

**Comment by jeremiahbunton** [comment]
Here is a screenshot of the Podfile.
It seems to run fine, just once I open the project in Xcode it seems to have issues.

Thank you for the help!

![screen shot 2015-04-13 at 6 42 56 pm](https://cloud.githubusercontent.com/assets/7061420/7128841/f3e85d96-e20c-11e4-9bd4-9960d6e8df74.png)

**Comment by jeremiahbunton** [comment]
I am sorry to waste your time but I found the solution on the UISKeyChainStore git account.  Here is a link incase anyone else if having the same problem and thank you for looking into it.

https://github.com/kishikawakatsumi/UICKeyChainStore/issues/84
