### ISSUE TITLE
#import AWSCore.h error

### ISSUE THREAD

**Issue by berilcetin** [aws/aws-sdk-ios#176]
I am using Facebook SDK with AWS, with Cocoapods. In my AppDelegate I import AWSCore.h and it gives me 3 errors. AWSCore.h, could not build module 'Bolts' and two other errors on module-includes. I cannot build my project and I cannot find any solutions, I've been looking for days. Any help would appreciated. Thanks.
![screen shot 2015-04-13 at 11 42 11](https://cloud.githubusercontent.com/assets/2082160/7112469/855c0aec-e1d2-11e4-86ca-2505048d41c4.png)

**Comment by yosuke-matsuda** [comment]
Please post your `Podfile` so that we can try to reproduce the issue.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. If you continue to experience the problem, please feel free to update the thread.

**Comment by berilcetin** [comment]
I've been also using Parse SDK and I was adding it as a framework. So I removed it from frameworks and added into my pod file. This solved the problem, I think Parse was causing the issue. Thanks anyway.
