### ISSUE TITLE
AWSS3GetPreSignedURLRequest handling custom metadata

### ISSUE THREAD

**Issue by jpike88** [aws/aws-sdk-ios#177]
This needs to be able to handle custom headers for custom object metadata, otherwise it's pretty useless for many of use cases.

**Comment by yosuke-matsuda** [comment]
This is in our backlog. When it is released, I'll update the thread. Thanks.

**Comment by jpike88** [comment]
Wow I just did a workaround that took me about 10 minutes. This is an easy one to implement, maybe your backlog need some reprioritising.

**Comment by bcherry** [comment]
This is also an issue for me - I'd like to upload files with a Cache-Control header set for Cloudfront, but it currently takes two requests if done using the `AWSS3GetPreSignedURLRequest`

**Comment by memreas** [comment]
Hi,
   I'm having this issue as well.  Is this scheduled to be included?

Thanks,
John

**Comment by yyzhu** [comment]
Hi @jpike88  @bcherry @memreas  
We've released AWS Mobile SDK for iOS 2.2.3 that can accept additional request parameters to be included in pre-signed URLs. 

For more details, please refer to release notes: https://aws.amazon.com/releasenotes/iOS/4731210461260864

**Comment by bcherry** [comment]
Yay! Thanks @yyzhu!

**Comment by jpike88** [comment]
Great, now it's broken my implementation.

Please show me sample code of presigning and successfully uploading a file with additional headers using the new version, as I've just spent 3 hours trying to make the damn thing accept the HTTP PUT headers. Why is v4 suddenly not working?

**Comment by jpike88** [comment]
I recommend you guys actually test your code. I had to do the SAME workaround as last time to make the thing work again.

```

    /*
     X-Amz-SignedHeaders Lists the headers that you used to calculate the signature. The HTTP host header is required. 
     Any x-amz-* headers that you plan to add to the request are also required for signature calculation.
     In general, for added security, you should sign all the request headers that you plan to include in your request.
     */
    
    NSMutableDictionary *headers = [NSMutableDictionary new];
    [headers setObject:host forKey:@"host"];
    
    if ([contentType length] > 0) {
        [headers setObject:contentType forKey:@"Content-Type"];
    }
    if ([contentMD5 length] > 0) {
        [headers setObject:contentMD5 forKey:@"Content-MD5"];
    }
    
    
    //add additionalParameters to queryString
    for (NSString *key in requestParameters) {
        id value = requestParameters[key];
        if ([value isKindOfClass:[NSNull class]]) {
            [headers setObject:@"" forKey:key];
        } else {
            [headers setObject:[requestParameters objectForKey:key] forKey:key];
        }
        
    }


    [queryString appendFormat:@"%@=%@&",@"X-Amz-SignedHeaders",[[AWSSignatureV4Signer getSignedHeadersString:headers] aws_stringWithURLEncoding]];
    
    //add security-token if necessary
    if ([credentialsProvider respondsToSelector:@selector(sessionKey)] && [credentialsProvider.sessionKey length] > 0) {
        [queryString appendFormat:@"%@=%@&", @"x-amz-security-token", [credentialsProvider.sessionKey aws_stringWithURLEncoding]];
    }
```

**Comment by yyzhu** [comment]
Hi, @jpike88 

There are some test cases in [our repos](https://github.com/aws/aws-sdk-ios/blob/master/AWSS3Tests/AWSS3PreSignedURLBuilderTests.m#L618) which shows how to use pre-signed URL with `requestParameters`.

Basically, the code snippets in above test cases is similar to this:
```
AWSS3GetPreSignedURLRequest *getPreSignedURLRequest = [AWSS3GetPreSignedURLRequest new];
getPreSignedURLRequest.bucket = @"your-bucket-name";
getPreSignedURLRequest.key = @"your-key-name";
getPreSignedURLRequest.HTTPMethod = AWSHTTPMethodPUT;
getPreSignedURLRequest.expires = [NSDate dateWithTimeIntervalSinceNow:3600]; //presigned-URL expiration date

//Add other parameters or your custom metadata 
[getPreSignedURLRequest setValue:@"userdefined-value" forRequestParameter:@"x-amz-meta-userdefined-key"];

//Build pre-signedURL
AWSS3PreSignedURLBuilder *preSignedURLBuilder = [AWSS3PreSignedURLBuilder defaultS3PreSignedURLBuilder];
[[preSignedURLBuilder getPreSignedURL:getPreSignedURLRequest] continueWithBlock:^id(AWSTask *task) {
    
    //retrieve presigned-URL
    NSURL *presignedURL = task.result;

    //create a url request
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:presignedURL];
    [request setHTTPMethod:@"PUT"];
    [request setHTTPBody:testObjectData];
    
    //send HTTP PUT Request
    NSError *returnError = nil;
    NSHTTPURLResponse *returnResponse = nil;
    [NSURLConnection sendSynchronousRequest:request returningResponse:&returnResponse error:&returnError];
    
    if (returnResponse.statusCode < 200 || returnResponse.statusCode >=300) {
        NSLog(@"server returns error.");
    }
    return nil;
}];
```

You may go to AWS Management Console -> S3 Console -> Select "your-bucket-name" -> Select "your-key-name" -> Select "Property" on the right panel. You should see the the `x-amz-meta-userdefined-key` under `MetaData` tab.

If you still have trouble using presignedURL with additional parameters, could you please upload your code snippets with the error log message so we can take a look.

Thanks.
