### ISSUE TITLE
Typo of "AWSS3Transfermanager"

### ISSUE THREAD

**Issue by matrixstone** [aws/aws-sdk-ios#178]
In README.md file, in the section "Getting Started with Objective-C", in the 4th step "Make a call to the AWS services.", there is a typo in the first line of code: 
"AWSS3TransferManager *transferManager = [AWSS3Transfermanager defaultS3TransferManager];".

The second "AWSS3Transfermanager" should be "AWSS3TransferManager".

**Comment by yosuke-matsuda** [comment]
We'll fix it in the next release. Thanks.

**Comment by yosuke-matsuda** [comment]
We've updated README.md. Thanks.
