### ISSUE TITLE
Frequent AWS Errors

### ISSUE THREAD

**Issue by minimalistcode** [aws/aws-sdk-ios#179]
I'm not sure at what point I started seeing this. I send off about 25-50 request to AWS, and I get back several different errors about 5%-10%.  The code for the requests looks like this:

```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^(void) {
    for (Report *report in reports) {
        [self getCommentsForReport:report nextToken:nil completionHandler:^(NSMutableArray *comments, Report *report, NSString *nextToken, BOOL addToComments, NSError *error) {
        NSLog(@"error: %@", error.localizedDescription);
    }];
}

-(void) getCommentsForReport:(Report *)report nextToken:(NSString *)nextToken completionHandler:(void (^)(NSMutableArray *comments, Report *report, NSString *nextToken, BOOL addToComments, NSError *error))completionHandler
{
    AWSSimpleDBSelectRequest *awsSimpleDBSelectRequest = [AWSSimpleDBSelectRequest new];
    awsSimpleDBSelectRequest.selectExpression = [NSString stringWithFormat:@"select * from %@ where ReportIdentifier = \'%@\' intersection Date is not null order by Date asc", domainComment, report.identifier];
    awsSimpleDBSelectRequest.nextToken = nextToken;
    AWSSimpleDB *awsSimpleDB = [AWSSimpleDB defaultSimpleDB];
    [[awsSimpleDB select:awsSimpleDBSelectRequest] continueWithBlock:^id(BFTask *task)
    {
        dispatch_async(dispatch_get_main_queue(), ^{
             if (task.error)
             {
                 completionHandler(nil,nil,nil,NO,task.error);
             }
             else
             {
                 NSMutableArray *comments = [self parseComments:(AWSSimpleDBSelectResult *)task.result];
                 completionHandler(comments,report,((AWSSimpleDBSelectResult *)task.result).nextToken,(nextToken == nil ? NO : YES),task.error);
             }
         });
         return nil;
     }];
}

```

Some of the errors I get back intermittently include:

(com.amazonaws.AWSGeneralErrorDomain error 3.): The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details

(com.amazonaws.AWSSimpleDBErrorDomain error 0.): The AWS Access Key Id you provided does not exist in our records

And I see intermittently this with identical code getting photos from S3:
(com.amazonaws.AWSS3ErrorDomain error 1.): The operation couldn’t be completed.

Can you tell me why I am getting these errors now or how to get rid of them? 
Thanks.

**Comment by yyzhu** [comment]
Hi minimalistcode,

May we know what kind of credentials did you use in above example? Does the credentials comes from CognitoIdentityBroker? If yes, could you try to use  AWSStaticCredentialsProvider (with a valid IAM AccessKey/SecretKey) to see if such errors still happened?

An example to create a staticCredentialsProver:

```
AWSStaticCredentialsProvider *credentialsProvider = [[AWSStaticCredentialsProvider alloc] initWithAccessKey:@"accessKey" secretKey:@"secretKey"];
AWSServiceConfiguration *configuration = [AWSServiceConfiguration  configurationWithRegion:AWSRegionUSEast1
                                                                               credentialsProvider:credentialsProvider];
[AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;
```

**Comment by minimalistcode** [comment]
I am using Cognito with this code:

    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"];
    AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];
    [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = serviceConfiguration;

Since I posted this question 2 weeks ago, I rewrote my code to get better performance and instead of getting lots of these errors, I only see a few of them, but I still see them.

I went ahead and tried using AWSStaticCredentialsProvider like you suggested and now I don't see any of these errors at all. Does this mean you might know what is causing this?

**Comment by yosuke-matsuda** [comment]
Right after the temporary credentials are generated, we sometimes see `InvalidAccessKeyId` exceptions. It is due to a massively distributed nature of the services. When you encounter the exception, you can simply retry the request.
