### ISSUE TITLE
Amazon Login Framework issus

### ISSUE THREAD

**Issue by babusoftsuave** [aws/aws-sdk-ios#18]
Hi.. I am integrating  the Amazon Login in my IOS App. I used both Google plus share and Amazon login in my application. when i try to build project it show "Duplicate symbol in GooglePlus and Amazon Framework" error

"duplicate symbol _kClientId in: /Users/test/Amazon/Apps-SDK/iOS/LoginWithAmazon/LoginWithAmazon.framework/LoginWithAmazon(AIConstants.o) 

/Users/test/GooglePlus/google-plus-ios-sdk-1.5.1/GooglePlus.framework/GooglePlus(GPPOzLogger.o) ld: 1 duplicate symbol for architecture i386 clang: error: linker command failed with exit code 1 (use -v to see invocation)
"

How to solve this issus?

![screen shot 2014-07-14 at 8 12 14 pm](https://cloud.githubusercontent.com/assets/7513337/3572408/9273c626-0b67-11e4-95d4-2701f0c9d997.png)

**Comment by jkoepcke** [comment]
Hey, I am seeing the same thing here - any update on when this will be fixed?

Don't want to say this, but when it comes down to logging in with Google+ OR Amazon... somebody has to decide which one is more important ;-)

As a temporary solution (believe it or not) you can use a text editor and replace all occurrences of "_kClientId" in the LoginWithAmazon binary with something else (like "_kClientIe").

Thanks in advance & best regards.

**Comment by scottbyrns** [comment]
Google+ with LoginiWithAmazon causes this conflict. If this helps amazon care, our team has chosen to remove all amazon oauth support in our website and our mobile applications until this has been resolved.

**Comment by yosuke-matsuda** [comment]
The Login with Amazon team released the new version of SDK that addresses the name collision issue. You can grab the latest version SDK from [their website](http://login.amazon.com/ios)). Thank you.
