### ISSUE TITLE
How can it select ReducedRedundancy?

### ISSUE THREAD

**Issue by nagaho** [aws/aws-sdk-ios#183]

**Comment by yyzhu** [comment]
could you give us more details about that?

**Comment by nagaho** [comment]
I want to use this option but don't know how to use it.
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRRS.html

**Comment by yosuke-matsuda** [comment]
`AWSS3PutObjectRequest` has a property called [storageClass](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3PutObjectRequest.html#//api/name/storageClass). You can set it to `AWSS3StorageClassReducedRedundancy`.

Hope it helps,
