### ISSUE TITLE
[Feature Request]: Support carthage

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#184]
https://github.com/Carthage/Carthage

**Comment by yyzhu** [comment]
Thank you for the feature request. Although we don't have a plan to support it immediately, but we will keep an eye on it.

**Comment by schickling** [comment]
+1

**Comment by baek-jinoo** [comment]
+1

**Comment by schickling** [comment]
@yyzhu it should be pretty easy: just make the build scheme public and push it.

**Comment by NicholasTD07** [comment]
+1 It should be super easy. Make a scheme for the framework and make it public. That's all. :)

**Comment by baek-jinoo** [comment]
This could also include having a prebuilt binary in the release section on Github.

**Comment by wakinchan** [comment]
:+1:

**Comment by dannydallen** [comment]
+1

**Comment by lumos-pairstation** [comment]
+1

**Comment by thbaja** [comment]
+1

**Comment by solidcell** [comment]
+1

**Comment by uneco** [comment]
+1

**Comment by nurseymybush** [comment]
+1

**Comment by solidcell** [comment]
Is there any update from the maintainers as to whether this will happen or not?  It seems like a big win for a small change.  There's obviously interest, as the "+1"s show. Don't you want this feature for your library?

**Comment by yoller** [comment]
+1

**Comment by plenilune** [comment]
+1

**Comment by rkawajiri** [comment]
+1

**Comment by nayutaya** [comment]
+1

**Comment by spencerkohan** [comment]
+1

**Comment by yosuke-matsuda** [comment]
Although internally we still need to sort a few things out (including the migration from the static framework to dynamic framework, and dropping iOS 7 support), we are actively looking into supporting Carthage. Thanks.

**Comment by tc** [comment]
+1

**Comment by yutakaA** [comment]
+1

**Comment by hsienchiaolee** [comment]
+1

The latest Carthage supports building multiple frameworks. To support multiple frameworks, create a new dynamic framework target for each project with shared scheme for each target.

**Comment by dcosson** [comment]
+1

**Comment by hatebyte** [comment]
+1

**Comment by AndreiVidrasco** [comment]
+1

**Comment by thebugcode** [comment]
This is needed asap. Chartage is a used by thousands now +1

**Comment by schlingding** [comment]
+1

**Comment by FranDepascuali** [comment]
+1

**Comment by rainypixels** [comment]
+1

**Comment by algal** [comment]
+1

**Comment by solidcell** [comment]
Hey guys, check it out: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

You can use the new reactions feature instead of a bunch of "+1" comments.

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.4.0, which adds official support for Carthage. Thanks.
