### ISSUE TITLE
Clarification about offline Dynamo DB 

### ISSUE THREAD

**Issue by andreaf** [aws/aws-sdk-ios#188]
Dear all, sorry for the question, but any way to have Dynamo DB sync offline ? 
I found a version with this feature in 1.X  SDK (based on coredata) but I'm not able to find something similar on 2.X

thanks a lot
Andrea Fanfani

**Comment by yosuke-matsuda** [comment]
Neither versions of the iOS SDK supports offline sync for Amazon DynamoDB. The Core Data component is designed to be used while the device is online.

You may want to take a look at [Amazon Cognito Sync](http://aws.amazon.com/cognito/) to sync data online and offline among multiple devices.

**Comment by Sun3** [comment]
Isn't Cognito Sync used for app preferences or game state? How would you use Cognito with DynamoDB?

Thanks.

**Comment by behrooziAWS** [comment]
Cognito Sync and DynamoDB are two different datastores.  You cannot use Cognito Sync to synchronize data stored in DynamoDB.

**Comment by Sun3** [comment]
Thanks for the clarification. Just to make sure I understand, as of now DynamoDB does not support offline sync.

**Comment by behrooziAWS** [comment]
That is correct, DynamoDB does not support offline sync.

**Comment by aletheia** [comment]
Here at Neosperience we're developing a library to add persistent store support to dynamodb through CoreData. We plan to release it open source, but we are looking for contributors.




If anyone is interested, please contact me in private.






—
Luca Bianchi PhD
bianchi.luca@gmail.com
