### ISSUE TITLE
resume upload using NSURLSession

### ISSUE THREAD

**Issue by nasirmehmood** [aws/aws-sdk-ios#191]
While using S3TransferManager if a file upload was interrupted then on next try of same file, it would resume upload from where it was interrupted (nearest 5MB chunk).
Right now I am using NSURLSession for background upload, if upload get interrupted (network failure e.g.) and I try to upload same file again then it begins uploading from very start. 

How can I achieve same behavior of S3TransferManager using NSURLSession ? so it resumes uploading same file from the point where it was interrupted.

Please provide response on it.

**Comment by yosuke-matsuda** [comment]
You cannot resume background uploads. You need to manually break down your file into smaller chunks if you want to accomplish the same behavior.

**Comment by nasirmehmood** [comment]
I have broken in down into chunks of 5MB and stored them into separate files. Then signing each chunk request and uploading chunk file. But whenever I try to upload from file, it gets stuck after 163840 or 196608 bytes and never continues resulting in request failure. However if I am setting chunk bytes as request body and then sending request, it works fine. It only gets stuck while uploading chunk from file. 
I am not sure what's wrong here, any thoughts ?

**Comment by yosuke-matsuda** [comment]
Sounds like you are having issues using Apple's `NSURLSession`. Their [Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html) may help.
