### ISSUE TITLE
S3 ListObjects Prefix - Same for CopyObjects or DeleteObjects?

### ISSUE THREAD

**Issue by mcsio** [aws/aws-sdk-ios#192]
You can use the prefix attribute on ListObjects to limit the records retrieved.  This works great to create a tree structure and only fetch as you need the records.

But when we go to copy or delete a folder on the client side there isn't a prefix attribute to send to the server. Seems you have to fetch all the objects before the copy or delete.

I've seen other libraries (PHP) talking about using Perl-Compatible Regular Expression (PCRE) to filter the names for deleting.
http://stackoverflow.com/questions/9054287/delete-from-s3-using-api-php-using-wildcard

Can you do this somehow I'm the IOS SDK?

**Comment by yosuke-matsuda** [comment]
You cannot delete/copy multiple objets using regular expression with the AWS Mobile SDK for iOS.
