### ISSUE TITLE
Deprecated method error

### ISSUE THREAD

**Issue by cacmartinez** [aws/aws-sdk-ios#194]
Hi in the file AWSCredentialsProvider.m the following method that has been deprecated, and it says to use a method that doesn't exist in the file instead: (So is the method missing?, or is the hint of which one to use wrong?)
```
+ (instancetype)credentialsWithRegionType:(AWSRegionType)regionType
                                accountId:(NSString *)accountId
                           identityPoolId:(NSString *)identityPoolId
                            unauthRoleArn:(NSString *)unauthRoleArn
                              authRoleArn:(NSString *)authRoleArn __attribute__ ((deprecated("Use '- initWithRegionType:accountId:identityPoolId:unauthRoleArn:authRoleArn:' instead.")));
```

**Comment by yosuke-matsuda** [comment]
You can use `- initWithRegionType:identityId:accountId:identityPoolId:unauthRoleArn:authRoleArn:logins:` instead. Looks like the message is outdated. Also, you may want to consider using [Enhanced Flow](https://mobile.awsblog.com/post/Tx2323YHCM0I7OO/Understanding-Amazon-Cognito-Authentication-Part-4-Enhanced-Flow).

**Comment by yosuke-matsuda** [comment]
We've updated the deprecation message. Thanks.
