### ISSUE TITLE
Update podspec dependency to Bolts/Tasks subspec

### ISSUE THREAD

**Issue by chadpod** [aws/aws-sdk-ios#195]
In pods applicable, update the the dependency on Bolts to just be the Bolts/Tasks subspec, assuming Bolts/AppLinks isn't being used.  I ended up having to do this because I was using AWS services in a keyboard extension and the Bolts/AppLinks stuff make use of [UIApplication sharedApplication], which isn't available in an iOS extension.

**Comment by yosuke-matsuda** [comment]
We are aware of the issue. We have a plan to remove the third party library dependency. With the coming release, you will not need to make the change. Thanks.

**Comment by yosuke-matsuda** [comment]
2.2.0 removed all of the third-party library dependencies. Closing this thread.
