### ISSUE TITLE
Mobile Analytics Timestamps

### ISSUE THREAD

**Issue by cthomaschase** [aws/aws-sdk-ios#197]
Been using AWSMA in production for a few weeks and started seeing odd timestamps in our Redshift data store. I've been able to trace a few (not all) of these back to S3, so I suspect this is not happening on the export to Redshift.

Here is a sample set from Redshift:

![cthomaschase_ _psql_ _247x70](https://cloud.githubusercontent.com/assets/455635/8025228/9c93b15a-0d02-11e5-9849-80b21728369c.png)

These are the default 'built-in' session events generated by the SDK.

You can see that the *session_start_timestamp* is `1970-01-01 01:30:27.383`, yet the *session_stop_timestamp* is `2015-05-23 11:44:18.517`.

Based on the support team's answer here https://forums.aws.amazon.com/thread.jspa?threadID=182012&tstart=0, it's possible that the client device can have incorrect date/time settings. If this was the case, how would we have a mix of *good* and *bad* data?

Anyone else seeing this?

**Comment by yyzhu** [comment]
AWS Mobile SDK for iOS has a clockskew feature which can automatically using server's time if the device's time is incorrect. But this feature has limitations and not able to  handle every situations, (i.e. when session_start upon app's launch, or device's is offline while Mobile-Analytics is recording Events, clockskew doesn't have the chance to get correct time from server), which result inconsistent timestamps among start_timestamp  stop_timestamp and event_timestamp. 

In our latest release v2.1.2, we fixed this issues by only using device's original time (even it is incorrect) for all Mobile-Analytics events to make sure all timestamps is consistent.

you can download the latest version via http://aws.amazon.com/mobile/sdk/

**Comment by cthomaschase** [comment]
That makes sense, thank you.
