### ISSUE TITLE
Allow gzip content encoding on DynamoDB rest API responses

### ISSUE THREAD

**Issue by mrtj** [aws/aws-sdk-ios#201]
I work with big DynamoDB and I download and cache the data client-side. Downloading all data from my table with a scan operation takes quite a while, up to 10 seconds. As the data can be measured in several megabytes I wanted to check if the responses of the DynamoDB web service uses gzip content-encoding and I found that it does not, furthermore the Accept-Encoding header is hard coded to empty string in `-[AWSDynamoDBService initWithConfiguration:]` method ([lines 219-221 of AWSDynamoDBService.m](https://github.com/aws/aws-sdk-ios/blob/eaa3860ad84959b527f7506a4c3fffe28026aea9/AWSDynamoDB/AWSDynamoDBService.m#L219-L221)):

    _configuration.headers = @{@"Host" : _configuration.endpoint.hostName,
                               @"Content-Type" : @"application/x-amz-json-1.0",
                               @"Accept-Encoding" : @""};

What is the rationale behind this decision? If I change the empty string to "gzip, deflate" the request speeds up up to 5 times (2 seconds for the same scan operation).

**Comment by yosuke-matsuda** [comment]
We currently disable GZip in the Amazon DynamoDB client for the following reason. Amazon DynamoDB returns CRC32 with a response, and even though we currently do not verify it, we are planning to do so.

When the service returns small data, it does not GZip the content, and the CRC32 calculation on the device succeeds. However, when the service returns GZiped larger data, the iOS automatically unzip the content, and the SDK does not have an opportunity to calculate the valid response CRC32 to verify the integrity.

At this moment, the SDK does not perform CRC32 verification, so you can modify the source and allow Gzipping if it suits your usecase. However, please keep the above in mind when doing so. We are currently looking for a way to provide both speed and data integrity. Thanks.
