### ISSUE TITLE
Issue on AWSS3GetPreSignedURLRequest with "?prefix=" request

### ISSUE THREAD

**Issue by weahoo** [aws/aws-sdk-ios#202]
Once the bucket is set to getPreSignedURLRequest.key = @"?prefix=", and others follow the background transfer example, the following exception was returned:
"ttps://example.s3.amazonaws.com/%3Fprefix%3D?x-amz-security-token=A..." 
and then the following info displayed:
S3 DownloadTask: <__NSCFBackgroundDownloadTask: 0x15561c230>{ taskIdentifier: 1 } completed with error: The requested URL was not found on this server.
As we know we would like to query the list of the objects in the given bucket, and after check the source, it seems the implementation forces to use the URLEncoding to encode the key, but in this case the conversion caused the incorrect issue. If the Pre-Signed request didn't support this feature, would you please point out is there any option to realize such a function?

**Comment by yosuke-matsuda** [comment]
You cannot set `?prefix=` to the `key` property because it is an invalid key. You should use [`- listObjects:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/listObjects:) to list objects with a given prefix.

**Comment by weahoo** [comment]
Since AWSS3ListObjectsRequest didn't belong to AWSS3PreSignedURL, so does it mean this listObjects action cannot be executed in background mode? I intend to execute such list action in background mode even the application is not in foreground.

**Comment by yosuke-matsuda** [comment]
I'm not sure what your use case is, but if you want to get a list of objects and initiate downloads, then your app needs to wake up.

**Comment by weahoo** [comment]
Is it possible to enable object list action even in background mode as a new feature of the SDK like using Pre-signed URL to download/upload content? I intend to enable the app to get the object list and fetch the corresponding objects even in background mode, e.g. if the location was changed and then fetching object list is triggered. I knew the "listObjects" worked very well when the app in foreground and wake up mode.

**Comment by yosuke-matsuda** [comment]
We do not have the plan to support the feature.

If you start significant location change monitoring and your app is subsequently terminated, the system automatically relaunches the app into the background if a new event arrives. So, you do not need to run `- listObjects:` in the background mode.

Background transferring of `NSURLSession` allows your app to download/upload data even when it is not running at all. It does not make much sense to get a list of objects in this manner.
