### ISSUE TITLE
Build AWSCore using Cocoapods and use_frameworks!

### ISSUE THREAD

**Issue by fabioknoedt** [aws/aws-sdk-ios#203]
Building the new version (**2.2.0**) using **Frameworks** in the beta version of *Cocoapods* (**0.37.2**) fails to compile.

```
platform :ios, "8.0"
use_frameworks!

target "MyApp" do
  
pod 'AWSCore'
pod 'AWSS3'

end
```

Thanks for removing the dependencies! Very nice!

**Comment by kousun12** [comment]
++

**Comment by yosuke-matsuda** [comment]
Thank you for the report. We try to support CocoaPods 0.37 by the time it drops the beta tag. In the meanwhile, please use the latest non-beta version of CocoaPods.

**Comment by fabioknoedt** [comment]
Hi, thanks for the answer!
Yeah, I was reporting that for the fact that the version before (2.1.2) was working just fine with CocoaPods 0.37.2 beta. After I updated to 2.2.0 it doesn't anymore.

**Comment by connectdotz** [comment]
I am also seeing this problem, the problem seems to be from the new files in 2.2.0, such as AESCoreFMDatabase:
<code>
..../Pods/AWSCore/AWSCore/FMDB/AWSFMDatabase.h:2:9: Include of non-modular header inside framework module 'AWSCore.AWSFMDatabase'
</code>

specifically on the line that imports "sqlite3.h"

don't think it is a cocoapod problem, please look into it at your earliest convenience. Thanks.

**Comment by kousun12** [comment]
also getting the `Include of non-modular header inside framework module 'AWSCore.AWSFMDatabase'` bit in the same place in my build

**Comment by yosuke-matsuda** [comment]
Indeed, this is not specific to the beta version of the CocoaPods. We need to update how `sqlites3.h` is included in the header files. We will address it in the next release. Meanwhile, please remove `use_frameworks!` from `Podfile` or use 2.1.2. Thanks.

**Comment by levous** [comment]
Well, this crushed two days of troubleshooting.  Thanks for addressing it.  When might we expect the next release?  AWSMobileAnalytics is not available < 2.2.0

thanks

**Comment by yosuke-matsuda** [comment]
`AWSMobileAnalytics` is in `AWSCore` <2.2.0.

**Comment by levous** [comment]
Sorry, my mistake.  I saw that the AWSMobileAnalytics folder and Xcode pro disappears on the 2.1.2 tag and assumed it wasn't included.

thanks

**Comment by CVBECO** [comment]
Thank you!! Switching to 2.1.2 saved me two days of troubleshooting as well.

**Comment by swennemans** [comment]
I'm having the same problem. When using the `use_frameworks` tag a lot of error occur.

**Comment by swennemans** [comment]
Even with version 2.1.2 I get the following error in my bridging header file. 

`AWCore/AWSCore.h' file not found. This is with using Cacaopods.

**Comment by yosuke-matsuda** [comment]
We've released 2.2.1, which should address this issue. Could you try 2.2.1 and see if it resolves the compiler error? Thanks.

**Comment by durre** [comment]
2.2.1 resolved the Include of non-modular header errors for me. However, I'm seeing a bunch of "Duplicate interface definition for class AWSMTLValueTransformer", AWSModel, AWSNetworkingRetryType and so on.

Not sure if it's my setup that's weird or a new problem.

**Comment by fabioknoedt** [comment]
For me, it works. Thanks for the update!
