### ISSUE TITLE
Support BatchGetItem in AWSDynamoDBObjectMapper

### ISSUE THREAD

**Issue by colkilgore** [aws/aws-sdk-ios#204]
I'm having problems with trying to map to my database a response from `batchGetItem`. The response is not a typical dictionary that I could easily map to database, but a structure that has also the datatypes included. When I use the methods from `AWSDynamoDBObjectMapper` like `Load` or `Query` I immediately get the properly mapped `AWSDynamoDBObjectModel` subclass that I created which is what I'm looking for.

Example of what I'm getting
`"Item": {
   "Year": {"S": "1985"},
   "Fans": {"SS": ["Fox","Lloyd"]},
        "Name": {"S": "Back To The Future"},
"Rating": {"S": "****"}
}`

What I would like to get:
`"Item": {
        "Year": "1985",
        "Fans":  ["Fox","Lloyd"],
        "Name": "Back To The Future",
        "Rating": "****"
    }`

Are there plans to support `batchGetItem` in `AWSDynamoDBObjectMapper` to receive the mapped objects?

Or is there an easy way to parse the differently structured dictionary? I see that there is a private method called `- (NSDictionary *)removeAttributes:(NSDictionary *)item mapperVersion:(AWSDynamoDBObjectMapperVersion)mapperVersion` that could be useful for this kind of thing, but there is no way to access it. 

Maybe there is something I'm missing.

**Comment by yosuke-matsuda** [comment]
We do not have an immediate plan to support `batchGetItem` in `AWSDynamoDBObjectMapper`. I share your request with my team for future considerations.

**Comment by helloniklas** [comment]
Seems this would be essential to have a useful API. How is one otherwise meant to use this SDK.
