### ISSUE TITLE
2.2.0 needs to list dependencies now that they have been removed from podspec

### ISSUE THREAD

**Issue by dougboberg** [aws/aws-sdk-ios#205]
My local Podfile did not specify the AWS version, preferring to always pull the latest:

`pod 'AWSCore'`

With the 2.2.0 release the podspec changed meaning that none of the AWS dependencies are installed.  To fix I reverted to a specific AWS version:

`pod 'AWSCore', '2.1.2'`

For those using the cocoapods dependency manager either the AWS software is aware of and can retrieve its required dependencies, or the documentation needs to specify all required dependencies so that we can manually configure them for retrieval.

**Comment by yosuke-matsuda** [comment]
`AWSCore` 2.2.0 does not depend on any pods, so that is an expected behavior. You need to rename `BFTask` to `AWSTask` as mentioned in the [release note](https://aws.amazon.com/releasenotes/iOS/0764834686220312).

**Comment by dougboberg** [comment]
O... K.  I guess you can close this question.  We want need to use BFTask for other things so now I guess we will have both BFTask and AWSTask in the code.
