### ISSUE TITLE
AWSS3PreSignedURLBuilder support for v4 signatures (Frankfurt)

### ISSUE THREAD

**Issue by meeee** [aws/aws-sdk-ios#209]
As @yosuke-matsuda [stated](https://github.com/aws/aws-sdk-ios/issues/25#issuecomment-78613732), `AWSS3PreSignedURLBuilder` currently only supports v2 signatures.

I'd like v4 signature support so I can use buckets in Frankfurt.

**Comment by yyzhu** [comment]
Hi @meeee 
We've released AWS Mobile SDK for iOS 2.2.3 which use AWS Signature Version 4 for generating the pre-signed URLs. For more details, please refer to release notes: https://aws.amazon.com/releasenotes/iOS/4731210461260864

**Comment by meeee** [comment]
Thanks!
