### ISSUE TITLE
Need help to resolve crash issue

### ISSUE THREAD

**Issue by care2achieve** [aws/aws-sdk-ios#210]
Please check this https://github.com/AFNetworking/AFNetworking/issues/2743

**Comment by yyzhu** [comment]
Hi @care2achieve ,

I've just looked at the link you provided, and I can confirm that our AWS Mobile SDK for iOS doesn't use any swizzle method (expect testing classes). My suggestion would be isolating the error: removing any codes related to our SDK and to see if the error still happened.
