### ISSUE TITLE
Support ignoreAttributes method in AWSDynamoDBObjectModel

### ISSUE THREAD

**Issue by hmuronaka** [aws/aws-sdk-ios#211]
I have to upload  an instance of AWSDynamoDBObjectModel subclass except it’s some attributes.
I tried to use AWSDynamoDBModeling.ignoreAttributes, but it doesn’t work.

Please support AWSDynamoDBModeling.ignoreAttributes.

**Comment by yosuke-matsuda** [comment]
We have released the AWS Mobile SDK for iOS 2.2.4 with the `ignoreAttributes` support. Thanks.
