### ISSUE TITLE
No info of uploadrequest in response

### ISSUE THREAD

**Issue by sumitjain7** [aws/aws-sdk-ios#216]
I am using AWSS3TransferManagerUploadRequest object and 
transferManager.upload(uploadRequest).continueWithBlock{(task) -> AnyObject! in}
for upload process.
If I upload multiple images using this method, I do not get any info about my request in 'task' so that I can match whether the response is for which request.

Can you help?

**Comment by yosuke-matsuda** [comment]
I am not sure if I understand your question. Can you share the code snippet and detail steps to reproduce the issue?
