### ISSUE TITLE
Get warning message in XCode 6.3 - synthesis will not synthesize property 'outputClass';

### ISSUE THREAD

**Issue by mihir-mehta** [aws/aws-sdk-ios#219]
Got following warning in XCode 6.3 
1> Auto property synthesis will not synthesize property 'outputClass'; it will be implemented by its superclass, use @dynamic to acknowledge intention (In AWSCognitoIdentityResponseSerializer and AWSMobileAnalyticsERSResponseSerializer) 

Got same warning for NSURL *body in AWSS3TransferManagerUploadRequest class. 

We should either use dynamic if we have specific purpose for using same property name in subclass Or we should rename/remove the property from subclass
![screen shot 2015-07-20 at 2 18 53 pm 2](https://cloud.githubusercontent.com/assets/6812906/8772502/4d684fdc-2eea-11e5-8b60-6e5214c82157.png)

**Comment by yosuke-matsuda** [comment]
It doesn't seem like you have the latest version of the AWS Mobile SDK. Please try again with the latest version and let us know if it resolved the issue.

**Comment by mihirpmehta** [comment]
Hi, 

This pod comes along with the Facebook SDK pod i guess. So i haven't specify any version .

This what my podfile looks like 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking'
pod 'PubNub'
pod 'MBProgressHUD'
pod 'PureLayout'
pod 'IQKeyboardManager'
pod 'INTULocationManager'
pod 'EasyMapping'
pod 'CardIO'
pod 'Mixpanel'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'

How can i make sure that latest SDK is being used. And is there any chances that any functionality of the facebooksdk will break if i i explicitly update this SDK to latest version ?

**Comment by yosuke-matsuda** [comment]
The `AWSS3` spec does not contain the Facebook SDK. Also, I do not see any AWS specs in your `Podfile`. Probably, I am missing something. Can you explain your setup in more detail?

**Comment by mihirpmehta** [comment]
It's otherway around, FacebookSDK i think installing aws SDK just run this pod file on any project see. it will automatically install aws iOS

**Comment by mihirpmehta** [comment]
One of the pod mentioned above has dependancy of awsiOSSDKv2 , which is installing old SDK

**Comment by yosuke-matsuda** [comment]
No, none of the above pods depends on `AWSiOSSDKv2`. In any case, you need to get the latest version of the SDK to remove the compiler warning.
