### ISSUE TITLE
Amazon iOS Mobile SDK v2 Create empty folder

### ISSUE THREAD

**Issue by daumantasversockas** [aws/aws-sdk-ios#220]
I have a issue related with **Amazon iOS Mobile SDK v2**. I have a task to create an empty folder inside provided bucket. To create an empty folder I am using method:

    - (void)createDirectory:(AWSS3Object *)directory inBucket:(AWSS3Bucket *)bucket success:(void (^)())success failure:(void (^)(NSError *error))failure
    {
        NSString *configurationKey = [NSString string];
    
        if (self.configurationType == AmazonServiceConfigurationTypeDefault)
        {
            configurationKey = S3ConfigurationKey;
        }
    
        else if (self.configurationType == AmazonServiceConfigurationTypeHUB)
        {
            configurationKey = S3HUBConfigurationKey;
        }
    
        else if (self.configurationType == AmazonServiceConfigurationTypeTemporary)
        {
            configurationKey = S3TemporaryConfigurationKey;
        }
    
        AWSS3 *s3 = [AWSS3 S3ForKey:configurationKey];
    
        AWSS3PutObjectRequest *putObjectRequest = [AWSS3PutObjectRequest new];
    
        putObjectRequest.key = directory.key;
        putObjectRequest.bucket = bucket.name;
        putObjectRequest.body = [NSString string];
    
        [[s3 putObject:putObjectRequest] continueWithBlock:^id(AWSTask *task)
        {
            if (task.error)
            {
                NSError *error = task.error;
            
                failure(error);
            }
        
            else
            {
                success();
            }
        
            return nil;
        }];
    }

With this method I am always getting the error: `The request signature we calculated does not match the signature you provided`.

My access and secure keys are correct.

From the previous experience, I was used to get this error because of incorrect parameters.

**My key:** `AWS iOS SDK v2 Test/test/`

**My bucket:** `abc-test`

Previously, when I was using AWS iOS Mobile SDK v1, practically the same code has been working like a charm.

**Comment by yosuke-matsuda** [comment]
We confirmed there is an issue with the SDK. We will address it in the upcoming release. Thank you for bringing this to our attention.

**Comment by yyzhu** [comment]
Hi @daumantasversockas , 

We've release AWS Mobile SDK for iOS 2.2.3 which solve the issue where an empty directory cannot be created, for more details, please refer to the release notes: https://aws.amazon.com/releasenotes/iOS/4731210461260864   

Thanks.
