### ISSUE TITLE
Support for two credential provider regions

### ISSUE THREAD

**Issue by larryaasen** [aws/aws-sdk-ios#221]
Since defaultServiceConfiguration in AWSServiceManager can only be set once, I am not able to change my credentialsProvider while running my iOS app. For S3 I am using AWSStaticCredentialsProvider in region Oregon, and for SNS I am using AWSCognitoCredentialsProvider in region USEast1. These credential providers cannot be used at the same time, and across two regions. Is there a way to handle this?

**Comment by yosuke-matsuda** [comment]
Each service client has `+ register[SERVICENAME]WithConfiguration:forKey:`  and `+ [SERVICENAME]ForKey:` methods (e.g. [`+ registerS3WithConfiguration:forKey:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/registerS3WithConfiguration:forKey:) and [`+ S3ForKey:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/S3ForKey:)). You can use these method to pass different service configurations to different instances of service clients. The API doc has more details with code snippets. Hope this helps.

**Comment by larryaasen** [comment]
@yosuke-matsuda Thanks for the tip. That worked.
