### ISSUE TITLE
Cannot import AWSCore as instructed in "Getting Started with Swift section"

### ISSUE THREAD

**Issue by tohsaki** [aws/aws-sdk-ios#223]
Step 4 of Getting Started with Swift section is:
#import <AWSCore/AWSCore.h>
However, AppDelegate.swift does not accept this syntax since it is a Swift file.

Note: 
First I imported AWSCore only in my Bridging-Header file:
#import <AWSCore/AWSCore.h>

At this point, the following code compiled in AppDelegate.swift:
        let credentialsProvider: AWSCognitoCredentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.USEast1, identityPoolId: <my arn>)
        let configuration: AWSServiceConfiguration = AWSServiceConfiguration(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)
        
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration

After adding AWSS3 to the Bridging-Header file, I got compiler errors and xCode no longer recognize:
Use of unresolved type 'AWSCognitoCredentialsProvider'
Use of unresolved type 'AWSServiceConfiguration'
Use of unresolved type 'AWSServiceManager'

Step 4 seems to be related to the issue above. However, I am having difficulty importing AWSCore since #import <AWSCore/AWSCore.h> is a Objective-C syntax

Thanks for your reply in advance

**Comment by yosuke-matsuda** [comment]
It's a documentation issue. You can totally ignore Step 4 for Swift. You can take a look at Swift sample apps [here](https://github.com/awslabs/aws-sdk-ios-samples).

**Comment by tohsaki** [comment]
Thanks, Matsuda-san!
I will take a look at samples.

Tsuni Ohsaki

**Comment by yosuke-matsuda** [comment]
We've updated `README.md`. Thanks.
