### ISSUE TITLE
AWSCognitoCredentialsProvider via singleton? 

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#225]
In all of the ios example documentation `AWSServiceManager` is set up in `didFinishLaunchingWithOptions`, but when using 3rd party authentications it's required to set the logins property as shown http://docs.aws.amazon.com/cognito/devguide/identity/external-providers/twitter/

In this documentation `credentialsProvider` magically appears inside the example scope, and quite obvious, not being set inside application launch.  I have not RTFM yet, but is there any way to access this instance from `AWSServiceManager`?  Can I use `AWSServiceManager.defaultServiceManager().defaultServiceConfiguration.credentialsProvider.logins =`?  I really don't want to be responsible for passing this instance around, and I especially don't want to reach back inside the app delegate to access this instance. 

Would be nice if this example was updated without the assumption the reader even knows what class this variable is an instance of.

**Comment by jbailey2010** [comment]
Sorry for the confusion. The credentialsProvider object is the Cognito client for vending credentials. An example of how to create an instance and how it can be used is available in our developer guide: http://docs.aws.amazon.com/cognito/devguide/identity/getting-credentials/.

Using a singleton to access it is perfectly acceptable/a good usage of the client.

Does that answer your question?

**Comment by rromanchuk** [comment]
I guess i'm asking if it's possible to use `AWSServiceManager` to grab the credential provider I set on app launch?  I don't really want to manage it myself, but I can't find where it's exposed. I get that i could subclass and add my own singleton convenience, but was hoping i could just ask the defaultManager for it, especially since authentication almost always happens after initialization.

**Comment by yosuke-matsuda** [comment]
It is possible to use `AWSServiceManager` because `defaultServiceManager` retains a reference to `defaultServiceConfiguration` which has the credentials provider you set. If that is the instance of credentials provider you are looking for, you can grab it from there.

Please note that the data type of `credentialsProvider` in `AWSServiceConfiguration` is `id<AWSCredentialsProvider>`. You need to check if it is an instance of `AWSCognitoCredentialsProvider` and cast it appropriately.
