### ISSUE TITLE
[DynamoDB] Crash on querying a table with "corrupt" data types 

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#226]
This may be intended operation, but just want to point out a crasher that is little bit difficult to diagnose at first. Let's say you have a key that's defined as a string in your iOS modeling, but due to developer error, somewhere else like lambda or a rails backend, a boolean gets saved instead of a string.  

Here is a real word scan of some records in was console for a table. 
`MyKey String: my cool string` <--- normal
`MyKey String: my other cool string` <--- normal
`MyKey Null:	true` <--- opps, developer error

Now when you use the SDK to run a query, this record will throw a `task.exception` because it's trying to set `nil` with `setObject` 
![screen shot 2015-08-06 at 1 35 00 pm](https://cloud.githubusercontent.com/assets/102188/9123056/eabaaf32-3c41-11e5-8855-87070374e565.png)

Now this is clearly user error, but it's a little bit scary thinking you could release a client, and because of a polluted record, your client could become unusable. 

Please feel free to close this if this is intentional.

**Comment by yosuke-matsuda** [comment]
As you indicated, it's a user error. However, the SDK should fail more gracefully. We will take a look. Thank you for bringing the issue to our attention.

**Comment by yyzhu** [comment]
We've fixed this issue in our latest AWS Mobile SDK for iOS.
