### ISSUE TITLE
Conflicts with Documents on AWSKinesisRecorder#saveRecord

### ISSUE THREAD

**Issue by rkawajiri** [aws/aws-sdk-ios#228]
The document said that

> Return Value
AWSTask- task.result contains an instance of AWSKinesisPutRecordInput persisted.

But it does not return correctly, based on my code reading and simple test.

![screen shot 2015-08-11 at 23 19 17](https://cloud.githubusercontent.com/assets/661102/9199787/71804bb2-407f-11e5-83a5-a766b0944ada.png)

* [Documents](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSKinesisRecorder.html#//api/name/saveRecord:streamName:)
  * [The source of documents](https://github.com/aws/aws-sdk-ios/blob/8cdca780bd13a5d2b47ace9cd004420a12b66602/AWSKinesis/AWSKinesisRecorder.h#L224)
* [Implementation](https://github.com/aws/aws-sdk-ios/blob/8cdca780bd13a5d2b47ace9cd004420a12b66602/AWSKinesis/AWSKinesisRecorder.m#L149-L250)
* [Commit of Test Code](https://github.com/rkawajiri/aws-sdk-ios/commit/f2b958d7220f9db768e579b037eda7f626ec1061)

**Comment by yosuke-matsuda** [comment]
Yes, you are right. `task.result` is always `nil`. We'll update the documentation in the next release. Thanks.

**Comment by yosuke-matsuda** [comment]
We have released the AWS Mobile SDK for iOS 2.2.4. It should address your issue. Thanks.

**Comment by rkawajiri** [comment]
:+1: Thank you.
