### ISSUE TITLE
iOS SDK support for Amazon RDS coming?

### ISSUE THREAD

**Issue by seanrice** [aws/aws-sdk-ios#229]
Are there any plans to add iOS SDK "database client" support for Amazon RDS? 

AWS Cognito is awesome for sync'ing data between one users devices, but we also need to sync team athlete data when available with coaches devices. open to suggestions.  

Sean (seanrice@mac.com)

**Comment by yosuke-matsuda** [comment]
We currently do not have plans to support Amazon RDS. Please note that the [Amazon RDS API](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/Welcome.html) is for managing the RDS instances, and you cannot retrieve data through it. For the security concerns, we do not recommend directly connecting to the RDS instances from mobile devices. You should have a server that connects to the database, and your mobile devices should talk to the server instead.

**Comment by seanrice** [comment]
thank you YM, i'll do more homework.

**Comment by seanrice** [comment]
I humbly respect all security concerns, but doesn't every well-written Amazon framework address such things? If it can be done, imagine the benefits having Amazon RDS client support built into the iOS framework. This gentleman did back in 2012 ...

![screen shot 2015-08-20 at 11 58 17 pm](https://cloud.githubusercontent.com/assets/1357349/9403151/405ddfb0-47b2-11e5-975a-b3a1216b55b3.png)

**Comment by turacma** [comment]
@seanrice I will point out again what @yosuke-matsuda already has: the RDS API is for supporting **management** of database instances, and as such is not a good fit for a SDK focused on mobile development.

What you seem to be asking for (based on the forum post you screen capped) is a database access library. As RDS supports a number of different *kinds* of databases (MySQL, PostgreSQL, SQL Server), each with their own protocol, this would multiply the effort necessary to support such an endeavor. 

I will note that none of the AWS SDKs (even those with *support* for RDS) do this. They instead defer this effort to libraries that are built to speak the protocols of those databases, for instance the entire JDBC stack for Java.

If you feel like you still want to go the route of connecting directly to a database from your application (a setup we would not recommend for stability of your platform), I encourage you to seek out libraries that were designed with this in mind. For instance, [this library](https://github.com/djthorpe/postgresql-kit) would allow you to connect directly to a PostgreSQL database.

**Comment by seanrice** [comment]
Thanks Bob,

> On Aug 21, 2015, at 3:33 AM, Bob Kinney <notifications@github.com> wrote:
> 
> As RDS supports a number of different kinds of databases (MySQL, PostgreSQL, SQL Server), each with their own protocol, this would multiply the effort necessary to support such an endeavor

Yes sir it would, and if it were my call all protocols would be supported. In our case, we’d be happy with MySQL.

**Comment by seanrice** [comment]
Yes sir it would, and if it were my call all protocols would be supported. Perhaps a clarification will help. As Amazon RDS supports a number of different kinds of databases (MySQL, PostgreSQL, SQL Server) each with their own protocol, it seems logical to me we should support them all.

Moreover, client access to a database securely from a mobile app doesn't have to be rocket science, and if the methods exist to secure network communication ... why not extend them? I'm told rapid database access directly from mobile is a "common" feature request.

Every Amazon framework is built to be secure as possible. Quite logically, the Amazon RDS client database frameworks must be secure. How is for wiser minds to figure out, however, consider the potential for mobile development. Isn't solving big problems sort-of the Hallmark of Amazon? As a coach of distance runners, it's my job to encourage hard work... to strive for the impossible!

Forgive my ignorance, perhaps that's what prevents me from seeing the status-quo as acceptable.

**Comment by vishaldroisys** [comment]
AWS Amplify Support Postgres DB now?
