### ISSUE TITLE
SQLite Vacuum Error overwrite Kinesis service Error on AWSKinesisRecorder#submitAllRecords

### ISSUE THREAD

**Issue by rkawajiri** [aws/aws-sdk-ios#230]
On AWSKinesisRecorder#submitAllRecords method, when sqlite vacuum occurs error, it overwrites errors from AWSKinesis#putRecords. The caller of the `submitAllRecords` cannot get the error. It is difficult to debug errors related the API requests.

The code is 
https://github.com/aws/aws-sdk-ios/blob/8cdca780bd13a5d2b47ace9cd004420a12b66602/AWSKinesis/AWSKinesisRecorder.m#L360-L375.

However, I don't know the solution.

Thanks,

**Comment by yosuke-matsuda** [comment]
What causes you to get errors for both `putRecords` and `VACUUM`? Especially, why is your `VACUUM` failing?

In many situations, the error from `putRecords` is more important, so we can update the SDK to return the Kinesis error over the SQLite error.

**Comment by rkawajiri** [comment]
The errors for `putRecords` was `InvalidIdentityPoolConfigurationException`. Our IAM configuration was just incorrect. This was what I wanted to know. 

The errors for `VACUUM` is

  - code = 1
  - domain = "AWSFMDatabase"
  - userInfo[0] = "cannot VACUUM - SQL statements in progress".

Actually, the error is not resolved. Currently, this is not becoming a big issue. However, I think this error may affect app disk usage with empty space on long-term. Right? So, I would like to know how to fix it.

[break point on debug](https://github.com/aws/aws-sdk-ios/blob/8cdca780bd13a5d2b47ace9cd004420a12b66602/AWSKinesis/AWSKinesisRecorder.m#L368)
![screen shot 2015-08-15 at 08 15 39](https://cloud.githubusercontent.com/assets/661102/9285921/dbfeda5a-4325-11e5-81f4-e681af75d582.png)

**Comment by yosuke-matsuda** [comment]
We addressed the issue with `VACUUM` with the AWS Mobile SDK for iOS 2.3.2. Thanks.
