### ISSUE TITLE
Version 2.2 AWS Cognito 

### ISSUE THREAD

**Issue by DaveKerr** [aws/aws-sdk-ios#231]
I've updated cocoapods to the latest version. I've deleted derived data directories and cleaned product. I've deleted Podfile.lock and Pods directory. I've executed 'pod install' which now downloads version 2.2.3 and 4 in some cases. I'm getting a linker error which I'm unable to find a solution:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AWSCognitoCredentialsProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_AWSServiceConfiguration", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_AWSServiceManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am opening the .xcworkspace file.  In Build Settings have changed Build Active Architecture Only to No.  Changed Architectures and Valid Architectures to `armv7` and `armv7s`.  I can't figure out where the `x86_64` architecture is referenced or built in any library or pod.

**Comment by yosuke-matsuda** [comment]
I cannot reproduce the issue with our sample Amazon Cognito Sync app. Can you post the content of your `Podfile` and your import statements in your application delegate? Also, what's the version of CocoaPods you are using? The latest version is currently 0.38.2. Please make sure to use the latest version. Thanks.

**Comment by DaveKerr** [comment]
----CocoaPod Info----
more podfile
source 'https://github.com/CocoaPods/Specs.git'
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'

pod --version
0.38.2

pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using AWSAutoScaling (2.2.4)
Using AWSCloudWatch (2.2.4)
Using AWSCognito (2.2.4)
Using AWSCore (2.2.4)
Using AWSDynamoDB (2.2.4)
Using AWSEC2 (2.2.4)
Using AWSElasticLoadBalancing (2.2.4)
Using AWSKinesis (2.2.4)
Using AWSLambda (2.2.4)
Using AWSMachineLearning (2.2.4)
Using AWSMobileAnalytics (2.2.4)
Using AWSS3 (2.2.4)
Using AWSSES (2.2.4)
Using AWSSNS (2.2.4)
Using AWSSQS (2.2.4)
Using AWSSimpleDB (2.2.4)
Generating Pods project
Integrating client project
Sending stats

----Import Statements----
#import "AppDelegate.h"
#import <AudioToolbox/AudioToolbox.h>

#import <GoogleOpenSource/GoogleOpenSource.h>
#define kGTLAuthScopePlusLogin "https://www.googleapis.com/auth/plus.login"
#import <GooglePlus/GooglePlus.h>

#import <AWSCognito/AWSCognito.h>
#import <AWSCore/AWSCore.h>

**Comment by yosuke-matsuda** [comment]
I created a new project with your `Podfile` and I was able to access `AWSCognito` without any issues. It seems like you have manually manipulated the project file. Are you building the correct *Target*? Do you have the same issue with our [sample project](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoSync-Sample/Objective-C)?

**Comment by DaveKerr** [comment]
I am going to start over - create a new project, copy all my code and storyboard into the new project and re-install the pods.  This approach will not provide a way for us to understand what is going on with the linker, but I can move on from this point if successful.  Give me a couple of days to do this - my code base is huge as is my storyboard.  I will report back if successful or not.

**Comment by DaveKerr** [comment]
By the way - I have installed the latest pods and there is a warning in AWSS3TransferUtility.m
<img width="1280" alt="screen shot 2015-08-21 at 7 25 37 am" src="https://cloud.githubusercontent.com/assets/9383681/9408212/2b0458c8-47d6-11e5-9656-b59033956079.png">

**Comment by yosuke-matsuda** [comment]
We'll suppress the warning on iOS 8 in the future version of the SDK. On iOS 8 and above, the highlighted code is not executed. It is there for the iOS 7 compatibility. Thanks.

**Comment by DaveKerr** [comment]
I have been told by Apple Developer Technical Support that the AWS pods will only support physical devices, not simulators.  Is this true?  I get 9 errors when compiling for a simulator target device, 1 error when compiling for a physical device.

There is a warning when compiling:
Pods was rejected as an implicit dependency for 'libPods.a' because its architectures 'armv7' didn't contain all required architectures 'armv7 arm64'

The remaining error is:  
Ld /Users/Dave/Library/Developer/Xcode/DerivedData/QuizOnTap-bnigxgdhvqenjcgjlwjqmbxllqtq/Build/Intermediates/QuizOnTap.build/Debug-iphoneos/QuizOnTap.build/Objects-normal/arm64/QuizOnTap normal arm64
    cd /Users/Dave/Documents/Development/Brillada/QuizOnTap
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -L/Users/Dave/Library/Developer/Xcode/DerivedData/QuizOnTap-bnigxgdhvqenjcgjlwjqmbxllqtq/Build/Products/Debug-iphoneos -F/Users/Dave/Library/Developer/Xcode/DerivedData/QuizOnTap-bnigxgdhvqenjcgjlwjqmbxllqtq/Build/Products/Debug-iphoneos -F/Users/Dave/Documents/Development/Brillada/QuizOnTap/QuizOnTap -F/Users/Dave/Downloads/google-plus-ios-sdk-1.7.1 -filelist /Users/Dave/Library/Developer/Xcode/DerivedData/QuizOnTap-bnigxgdhvqenjcgjlwjqmbxllqtq/Build/Intermediates/QuizOnTap.build/Debug-iphoneos/QuizOnTap.build/Objects-normal/arm64/QuizOnTap.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=7.0 -framework Foundation -framework CoreMotion -framework CoreLocation -framework UIKit -framework Security -framework CoreGraphics -framework MediaPlayer -framework CoreText -lPods -framework SystemConfiguration -framework AssetsLibrary -Xlinker -dependency_info -Xlinker /Users/Dave/Library/Developer/Xcode/DerivedData/QuizOnTap-bnigxgdhvqenjcgjlwjqmbxllqtq/Build/Intermediates/QuizOnTap.build/Debug-iphoneos/QuizOnTap.build/Objects-normal/arm64/QuizOnTap_dependency_info.dat -o /Users/Dave/Library/Developer/Xcode/DerivedData/QuizOnTap-bnigxgdhvqenjcgjlwjqmbxllqtq/Build/Intermediates/QuizOnTap.build/Debug-iphoneos/QuizOnTap.build/Objects-normal/arm64/QuizOnTap

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have removed intermediate directories, removed Podfile.lock and pods and pod installed the pods in my Podfile.  I have reinstalled cocoapods as will and get the same error.

**Comment by yosuke-matsuda** [comment]
You should be able to use the SDK on both simulators and iOS devices. You seem to be having a CocoaPods issue. [This](https://github.com/CocoaPods/CocoaPods/issues/2053) may help.

**Comment by DaveKerr** [comment]
I have seen that thread - changed yes to no for both debug and release and it still doesn't work. Any other thoughts?

Thanks,
Dave

**Comment by yosuke-matsuda** [comment]
You seem to be having issue with CocoaPods, so you may get more info on the CocoaPods thread. Alternatively, you can [use frameworks](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html) to import the AWS Mobile SDK for iOS.

**Comment by DaveKerr** [comment]
Thanks Yosuke,

I came to that same framework conclusion this morning after spending the weekend uninstalling and reinstalling XCode, Cocoapods, intermediate files, changing build and release architecture flags, and many more steps. 

Are there any items to watch out for when removing Cocoapods and re-implementing frameworks?  Are there reliable steps documented anywhere you can point me to?

Thanks,
Dave

**Comment by yosuke-matsuda** [comment]
I don't think removing CocoaPods integration is automated through `pod`. You should use a version control system such as Git and revert the changes.

**Comment by vGubriienko** [comment]
I have same issue using  `pod 'AWSS3'` with version 2.2.2 and podfile instruction `use_frameworks!`. does the pod compatible with `use_frameworks!`?

**Comment by kulkarnij** [comment]
Including AWS as frameworks is not a satisfactory solution. Framework inclusion involves a path setting and it can be different for each team member which means a manual edit of project file is required after a git pull. It also means that people have to manually update all the frameworks instead of simple command like pod update. The aws team needs to work on supporting cocoapods.

**Comment by kulkarnij** [comment]
I had to include X86_64 and i386 as valid architectures for each of the many AWS framesworks in the pods project and turn off build for active architectures only to no. I am wondering if there is a way to specify this in the configuration of the pod  itself so that it installs with these options.
