### ISSUE TITLE
Using the XCode 7 Beta 5, I am getting a compiler error

### ISSUE THREAD

**Issue by yoasha** [aws/aws-sdk-ios#232]
ld: '...AWSCore.framework/AWSCore(AWSModel.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this a known issue?

**Comment by yyzhu** [comment]
Hi @yoasha,

This is a known issue , for now you can disable the bitcode  to build it under Xcode 7 Beta 5. [How to disable bitcode](http://stackoverflow.com/questions/30848208/new-warnings-in-ios9)

We will include the BitCode in our SDK in future releases. 

Thanks

**Comment by yoasha** [comment]
Thank you for the quick response!

**Comment by Norod** [comment]
Hello,

When I set ENABLE_BITCODE to YES, AWS fails to link (as expected). However, when I set ENABLE_BITCODE to NO, I can no longer add a watchOS 2 App. (ERROR: "Target 'watchOS2 Extension' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform")

Does it mean that Apps which would like to have support for the upcoming watchOS 2 are not able to use the AWS framework until this issue is resolved?

Thank you!

**Comment by yosuke-matsuda** [comment]
If you compile the SDK for yourself (e.g. using CocoaPods), you can circumvent the issue. You cannot use the pre-compiled frameworks until we fix this. Thanks.

**Comment by petegrif** [comment]
Not working for me, with bitcode disabled.

**Comment by yyzhu** [comment]
@petegrif 
all examples codes should compile under Xcode 7 with Bitcode Disabled. Could you give us the name of examples that doesn't compile?

**Comment by petegrif** [comment]
Thanks for getting back to me.

The sample file is S3TransferManagerSampleSwift

I had to change to code a little to conform to Swift 2.0. I   Got error message "ld: library not found for -lAWSCore" Disabled bitcode but same message.

I did this successfully for another example - S3BackgroundTransfer-Sample - and managed to compile it (though no yet got it all working). And in this case I didn't disable bitcode but it compiled.

thanks again.

**Comment by petegrif** [comment]
s3transfermanagersamplesiwft

thanks

I got the one that executes in the background to compile but not this one

(btw there is a fair amount of deprecated swift code in the examples as I'm
sure you know)

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.3.0 with bitcode. Thanks.

**Comment by Norod** [comment]
Thank you for updating us 👍 By the way, so far I'm very happy with the build I have made from your source (works well on production).

**Comment by mattijsf** [comment]
It seems that the pre-built binary available from https://aws.amazon.com/mobile/sdk/ doesn't include bitcode (or is not >2.3.0?)

Pre-built binaries:

```
wget http://sdk-for-ios.amazonwebservices.com/latest/aws-ios-sdk.zip
unzip -d aws-ios-sdk-latest aws-ios-sdk.zip
otool -l aws-ios-sdk-latest/frameworks/AWSCore.framework/AWSCore | grep bitcode
```
Result: Bitcode **not** included

Building from source:

```
wget https://github.com/aws/aws-sdk-ios/archive/2.3.2.zip
unzip 2.3.2.zip
cd aws-sdk-ios-2.3.2
Scripts/SdkPackage.sh AWSCore
otool builtFramework/framework/AWSCore.framework/AWSCore -l | grep bitcode
```

Result: Bitcode **not** included


But when I modify and add the following `xcodebuild` argument to `Scripts/SdkPackage.sh`:
`OTHER_CFLAGS="-fembed-bitcode -Qunused-arguments" \`

Result: Bitcode **included**

Is this expected?

**Comment by yosuke-matsuda** [comment]
The distributed frameworks contain bitcode. You need to specify the CPU architecture to see the result such as `otool -arch armv7s -l`.
