### ISSUE TITLE
[Documentation] Public provider discrepancy 

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#233]
http://docs.aws.amazon.com/cognito/devguide/identity/external-providers/twitter/

Says `api.twitter.com`

but the ruby documentation says http://docs.aws.amazon.com/sdkforruby/api/Aws/CognitoIdentity/Client.html#get_id-instance_method
`www.twitter.com`

**Comment by yosuke-matsuda** [comment]
`api.twitter.com` is the correct one. We'll update the doc in the future release. Thanks.

**Comment by yosuke-matsuda** [comment]
We've updated the documentation. Thank you.
