### ISSUE TITLE
Access S3 bucket without specifying region?

### ISSUE THREAD

**Issue by Paul-van-Klaveren** [aws/aws-sdk-ios#235]
Hi,
We want our iOS app to retrieve files from a given S3 bucket, without having to specify from which region — any load balancing would be handled on the backend.
Is this possible with the current SDK?

I've tried calling `AWSServiceConfiguration` with `AWSRegionType.Unknown`, but that resolved to
https://s3.(null).amazonaws.com/--bucketName--/--fileName-- followed by an error.

(We sort of expected this to be possible out-of-the-box, considering Cross-Region Replication etc. https://aws.amazon.com/about-aws/whats-new/2015/03/amazon-s3-introduces-cross-region-replication/)
Moreover, it seems to work via a browser:
https://s3-eu-west-1.amazonaws.com/--bucketName--/--fileName--  ‹––– incl. region…
https://--bucketName--.s3.amazonaws.com/--fileName--     ‹––– no region given here!

Note: we are not using Cognito.

**Comment by yosuke-matsuda** [comment]
When using the AWS Mobile SDK for iOS, you always need to specify the region. You should manage a dictionary of buckets and regions to figure out to which region you need to send the request. Please note that the US Standard Region redirects requests to certain other regions, but it is not efficient.

**Comment by yoasha** [comment]
My app is also using AWS-S3, and obviously it's used across the world. I remember that I struggled with this issue a lot, until finally hard coded to the US region as I didn't find any simple solution... As an SDK provider, I think you should strongly consider adding something like AWSRegionType.AutoDetect as I can't see too many developers adding to their code the complexity of managing region dictionaries. Adding an auto detect option to your SDK sounds like a natural requirement to me.

**Comment by yosuke-matsuda** [comment]
Alternatively, you can use [`getBucketLocation:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/getBucketLocation:) to get the location of the bucket and create a client for the region.
