### ISSUE TITLE
How to get MD5 checksum in iOS

### ISSUE THREAD

**Issue by samma89** [aws/aws-sdk-ios#238]
I have used amazon v2 iOS latest api to upload videos to s3 BUCKET , i use there latest class called 
AWSS3TransferUtility

https://mobile.awsblog.com/post/Tx283AGGIL76PKP/Amazon-S3-Transfer-Utility-for-iOS

i managed upload videos successfully , but now i cant get the checksum of the uploaded file

                 AWSS3 *s3 = [AWSS3 S3ForKey:@"uploadingS3"];

                AWSS3HeadObjectRequest *headObjectRequest = [AWSS3HeadObjectRequest new];
                headObjectRequest.bucket = [Utill getBucketName];
                headObjectRequest.key =footage.videoFileName;

                AWSTask *awsTask = [s3 headObject:headObjectRequest];
                AWSS3HeadObjectOutput *headObjectOutput = awsTask.result;

                NSLog(@"headObjectOutput.ETag %@",headObjectOutput.ETag);
in here etag returns as null

any particular reason that this doesnt work

**Comment by yosuke-matsuda** [comment]
It seems to be not related to the transfer utility. Note `- headObject:` is an asynchronous request and returns immediately. When you are accessing `task.result`, the result may not be available yet. See [Working with AWSTask](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html) for more details.

**Comment by samma89** [comment]
understood , but this result should be validated for already uploaded file  , isnt it  ??

**Comment by yosuke-matsuda** [comment]
I'm not sure what you mean, but you can validate `Etag` using `- headObject:`.
