### ISSUE TITLE
performance issues with aws_stringValue

### ISSUE THREAD

**Issue by itchingpixels** [aws/aws-sdk-ios#239]
Hello,

We're building an app that uses S3 to upload data and we're experiencing some performance issues:

![image](https://cloud.githubusercontent.com/assets/5416288/9690128/6c716622-5332-11e5-8cfe-640204a71f44.png)

Would it be possible to optimise this method: aws_stringValue?

There are a few alternatives around that could perform better:
http://nshipster.com/nsformatter/

Please have a look, this is causing some serious issues for us.

Thank you!

**Comment by yosuke-matsuda** [comment]
The SDK is creating a new instance of `NSDateFormatter` for each call. It should reuse the same instance of `NSDateFormatter` instead of creating a new one. We'll update it in the future release. Thanks.

**Comment by itchingpixels** [comment]
Sure. I'm not 100% sure if this is actually the problem - it may be.
But according to my measurements, the heavy lifting actually happens when the method stringFromDate is called on NSDateFormatter, and not when the NSDateFormatter instance is created. Can you confirm?

**Comment by yosuke-matsuda** [comment]
We've improved the `aws_stringValue` performance with the AWS Mobile SDK for iOS 2.3.0, so please try again. Thanks.
