### ISSUE TITLE
AWS EC2 Container Service Support

### ISSUE THREAD

**Issue by MaksymBilenko** [aws/aws-sdk-ios#240]
Hello,
I'm curious is there a EC2CS docker container support at this SDK (unable to figure it out for now).

**Comment by yosuke-matsuda** [comment]
Please note that the AWS Mobile SDK provides a management APIs, and you cannot connect to the container from iOS devices using the SDK. `AWSEC2` is a direct map of [Amazon EC2 API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/Welcome.html). So, the answer depends on what you want to accomplish.
