### ISSUE TITLE
Error in was-sdk-ios

### ISSUE THREAD

**Issue by wnmtest0** [aws/aws-sdk-ios#242]
![screen shot 2015-09-08 at 3 52 53 pm](https://cloud.githubusercontent.com/assets/4254549/9733689/064cb1d2-564b-11e5-8f3b-d28cd5268ea5.png)

plz solve this issues

**Comment by yosuke-matsuda** [comment]
You seem to be using an old version of Xcode. Please update your Xcode and try again.
