### ISSUE TITLE
AWSS3TransferUtility completes upload partially, hangs, and then times out

### ISSUE THREAD

**Issue by kevinwo** [aws/aws-sdk-ios#243]
In attempting to upload small files to S3, each file stops uploading at a consistent number of bytes per file, hangs, and then ultimately times out. For example, one file is 1960955 bytes, yet only uploads 196608 bytes each time before halting.

I am on a stable Internet connection using the default transfer utility, Cognito credentials, and have tried uploading using both uploadData: and uploadFile: methods. Any idea what might be happening here?

**Comment by yosuke-matsuda** [comment]
When an upload hangs like you described, usually it's a permission issue. Have you verified you have set up permissions correctly? Also, if your bucket is in a different region than you specified in the SDK, the authentication fails as well.

**Comment by kevinwo** [comment]
Yes, I can confirm permissions are set up correctly and I've initialized my Cognito credential using AWSRegionUSEast1. In fact, I'm currently able to upload without issue when *not* using the AWS SDK, using a previously hand-rolled NSURLSession interface, although I'd like to move towards using the SDK.  If permissions or bucket are incorrect, should I not receive an immediate error response to my PUT request?

**Comment by yosuke-matsuda** [comment]
Can you share your code snippet and detailed steps to reproduce the issue so that I can try it?
