### ISSUE TITLE
Only include subset of AWS pods?

### ISSUE THREAD

**Issue by rpitting** [aws/aws-sdk-ios#245]
In the getting-started-section, you specify the following list for the Podfile:

```
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'
```

Is it _really_ necessary to include all pods? For using the SNS service, can I just use that pod?

**Comment by yosuke-matsuda** [comment]
If you want to use Amazon SNS, you can add

    pod 'AWSSNS'

to your `Podfile` and not others.

**Comment by rpitting** [comment]
Thanks!
