### ISSUE TITLE
AWSCognitoDataset's lastModifiedDate and creationDate always returns '1970-01-01 00:00:00 +0000'

### ISSUE THREAD

**Issue by svyatoslav-zubrin** [aws/aws-sdk-ios#246]
I want to use AWS Cognito Sync to store user data from the iOS app. I have created the dataset with that code:
```
AWSCognito *cognito = [AWSCognito CognitoForKey:cognitoKey];
AWSCognitoDataset *userInfoDataset = [cognito openOrCreateDataset:@"UserInfoDataset"];
[userInfoDataset setString:@"my name" forKey:@"NameKey"];
[userInfoDataset synchronize];
```
And I can see the dataset in the identity browser. After that the name was updated couple of times with the same code. But the "lastModifiedDate" or the "creationDate" properties of the received dataset are always set to '1970-01-01 00:00:00 +0000'. The code:
```
AWSCognitoDataset *userInfoDataset = [cognito openOrCreateDataset:VUAmazonSyncCognitoDatasetNameUserInfo];
[[userInfoDataset synchronize] continueWithBlock:^id(AWSTask *task) {
    // do some stuff
    if (!task.isCancelled && !task.error) {
        NSLog(@"%@ was last modified at %@, created at %@", userInfoDataset.name, userInfoDataset.lastModifiedDate, userInfoDataset.creationDate);
    }
    return nil;
}];
```
gives me:
```
UserInfoDataset was last modified at 1970-01-01 00:00:00 +0000, created at 1970-01-01 00:00:00 +0000
```
At the same time in the identity browser I can see the correct values for that fields:
![screen shot 2015-09-16 at 3 58 17 pm](https://cloud.githubusercontent.com/assets/1381440/9905899/4b35d1fc-5c90-11e5-99a1-e886aff41c3c.png)
I'm using AWS iOS SDK 2.2.5.
Can you help me find what I'm doing wrong here?

**Comment by svyatoslav-zubrin** [comment]
I've found that to get correct dates "refreshDatasetMetadata" method of the AWSCognito class can be used. But never the less I'd like to know if it is OK that the entity of AWSCognitoSyncDataset has incorrect metadata or is it something wrong with my code?

**Comment by behrooziAWS** [comment]
Thanks for the report, looks like we are only correctly setting those fields upon calling refreshDatasetMetadata.  We will look into fixing this in a future release.

**Comment by vsochinsky** [comment]
Are there any updates on this issue?

**Comment by belix** [comment]
it is still not working yet. are there any news on fixing this issue?

**Comment by karthiksaligrama** [comment]
We just release iOS SDK version 2.4.2 which has a fix for this issue.
