### ISSUE TITLE
Supporting devices with wrong time

### ISSUE THREAD

**Issue by tspecht** [aws/aws-sdk-ios#248]
Hi,

some of my users seem to have devices on which they have set the wrong device time. This causes the system to fail the validation of the AWS SSL certificate and thus all requests are failing. Is there a possibility to configure the SDK to skip SSL validation in this case? I tried implementing it myself and found that it should be possible by implementing the following NSURLSessionDelegate method:

```
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential *))completionHandler
{
	NSURLProtectionSpace * protectionSpace = challenge.protectionSpace;
	if ([protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
		SecTrustRef serverTrust = protectionSpace.serverTrust;
		completionHandler(NSURLSessionAuthChallengeUseCredential, [NSURLCredential credentialForTrust: serverTrust]);
	}
	else {
		completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
	}
}
```

Would it be possible to switch this on and off through the SDK?

**Comment by yosuke-matsuda** [comment]
When the device clock is overly skewed, and SSL fails, we recommend letting the end user know of the issue, providing guidance on how to fix the clock and failing gracefully. We do not recommend overwriting the OS's default authentication behavior for security concerns.

If you must overwrite it, the SDK is open sourced, and you can modify it to suit your use case.
