### ISSUE TITLE
AWSS3TransferManagerUploadRequest unavailable ("unresolved identifier")

### ISSUE THREAD

**Issue by schnabler** [aws/aws-sdk-ios#249]
Project was upgraded from Xcode 6 to Xcode 7 (iOS 8.0 as deployment target)

    let uploadRequest = AWSS3TransferManagerUploadRequest()

now gives an

    (Use of unresolved identifier 'AWSS3TransferManagerUploadRequest')

error. No code was changed. No "AWSS3"-classes show up in autocomplete either.

I installed AWS SDK via Cocoapods. Uploading images to S3 worked just fine in Xcode 6.  I can also set up AWSCognitoCredentialsProvider/AWSServiceConfiguration in my App Delegate without any problems.
Can anyone help me out? Thanks.

**Comment by yyzhu** [comment]
It looks like AWSCore.framework has been imported but AWSS3.framework did not. Could you give more details?

1. Which version of the Cocoapods do you have?
2. Content of your  Podfile?
3. Content of the your bridging header used in your swift project?

Also, have you tried to removed the "Podfile.lock" and "Pods/" folder in your project and reinstall the SDK by running "pod install"?

Thanks!
