### ISSUE TITLE
[Documentation][DynamoDB] Examples for modeling collection data

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#250]
Is there anyway you could add more examples of complex data types? All the examples i see use scalar types, and it's a bit confusing how to bridge these from ios. 

```
Amazon DynamoDB supports the following data types:

Scalar types – Number, String, Binary, Boolean, and Null.
Multi-valued types – String Set, Number Set, and Binary Set.
Document types – List and Map.
```

For example, can you add a string set, number set, and binary set using both objective-c and swift? 
```
#import <Foundation/Foundation.h>
#import <AWSDynamoDB/AWSDynamoDB.h>

@interface Book : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

@property (nonatomic, strong) NSString *Title;
@property (nonatomic, strong) NSString *Author;
@property (nonatomic, strong) NSNumber *Price;
@property (nonatomic, strong) NSString *ISBN;

@end
```

There is a little blip on the getting started guide, but it's all over the place. It would be much more clear to just add non scalar types to your example.

> As of SDK version 2.0.16, the AWSDynamoDBModel mapping class is deprecated and replaced by AWSDynamoDBObjectModel. The deprecated AWSDynamoDBModel used NSArray to represent multi-valued types (String Set, Number Set, and Binary Set); it did not support Boolean, Map, or List types. The new AWSDynamoDBObjectModel uses NSSet for multi-valued types and supports Boolean, Map, and List. For the Boolean type, you have to create an NSNumber using [NSNumber numberWithBool:YES] or using the shortcuts @YES and @NO. For the Map type, create using NSDictionary. For the List type, create using NSArray.

**Comment by rromanchuk** [comment]
This test suite is actually pretty helpful for anyone hunting 

https://github.com/aws/aws-sdk-ios/blob/master/AWSDynamoDBTests/AWSDynamoDBObjectMapperSwiftTests.swift

**Comment by yyzhu** [comment]
Hi @rromanchuk 

The current sample project doesn't demonstrate how to model map and list type by using DynamoDB Object Mapper, we will improve our sample code in future release.

For now, you can use the test suite as a reference for those complex types; For swift version, you've already found it: https://github.com/aws/aws-sdk-ios/blob/master/AWSDynamoDBTests/AWSDynamoDBObjectMapperSwiftTests.swift

For Objective-C, here is the link: https://github.com/aws/aws-sdk-ios/blob/master/AWSDynamoDBTests/AWSDynamoDBObjectMapperTests.m

Thank you for the suggestions!

**Comment by rromanchuk** [comment]
Thanks @yyzhu the test suite is actually very helpful!
