### ISSUE TITLE
ld: library not found for -lAWSAutoScaling

### ISSUE THREAD

**Issue by vickyrappier** [aws/aws-sdk-ios#252]
Hi Team,

I am getting this error 'ld: library not found for -lAWSAutoScaling'

Although I did following still the issue is not allowing me to get away with the compile error.

1) Pod reinstalled 
2) Pod update / install both done.
3) Checkout of code freshly 
4) Framework Paths removed 
5) Header Search Paths removed 
6) Library Search paths removed
7) Clean Build directory.

What can be the cause. I know this is not AWSScaling error because if i comment that I get another AWS library error.

After pods installs this is all I have downloaded in library.

<img width="228" alt="screen shot 2015-09-28 at 1 36 08 pm" src="https://cloud.githubusercontent.com/assets/11133355/10128482/f9c787e8-65e5-11e5-94d8-1451056a98f6.png">

**Comment by rohandubal** [comment]
Hi,

To answer this, could you please tell if you are opening the workspace (*.xcworkspace) or the project(*.xcodeproj) in xcode? Its required that you open the workspace and not the project from the Finder. Please let me know if that is the case.

-Rohan

**Comment by vickyrappier** [comment]
I fixed this problem by fresh checkout and deleting the pods and podlock then reinstall again. This I tried earlier with existing copy but didn't work. 
Thanks 

Sent from Outlook




On Mon, Sep 28, 2015 at 10:50 AM -0700, "rohandubal" <notifications@github.com> wrote:












Hi,



To answer this, could you please tell if you are opening the workspace (.xcworkspace) or the project(.xcodeproj) in xcode? Its required that you open the workspace and not the project from the Finder. Please let me know if that is the case.



-Rohan
