### ISSUE TITLE
CDN Integration with IOS

### ISSUE THREAD

**Issue by vickyrappier** [aws/aws-sdk-ios#253]
Hello Team,

I am developing an IOS And Android Chat application currently uploading and downloading media that is shared across chat users using S3 , We have used S3 store with Cognito credential system.

Can you guide us how can we integrate CDN Systems which is upcoming feature of AWS for better delivery and latency management.

Any help and guidance is much appreciated.

Thanks,
Vicky

**Comment by yosuke-matsuda** [comment]
You can learn more about [Amazon CloudFront](https://aws.amazon.com/cloudfront/) here. Also, we have a dedicated Amazon CloudFront [Discussion Forum](https://forums.aws.amazon.com/forum.jspa?forumID=46) to connect with other developers if you have any questions about CloudFront.
