### ISSUE TITLE
STANDARD_IA

### ISSUE THREAD

**Issue by trondkr** [aws/aws-sdk-ios#255]
Hi. I was looking into version 2.2.6 for AWS S3 methods and I was wondering if it supports the new Standard Infrequent Access storage class. If so, do you have an example how I would set the storage class correct? According to the AWS SDK FAQ you "The default setting is STANDARD. You can use an optional header on a PUT request to specify the setting STANDARD_IA". But how do I do that using the AWS SDK for iOS? Thanks. T

**Comment by yosuke-matsuda** [comment]
Currently, the AWS Mobile SDK does not support `STANDARD_IA`. When we add the support, we'll update the thread. Thanks.

**Comment by trondkr** [comment]
Thanks for your quick reply.

**Comment by yosuke-matsuda** [comment]
We released the AWS Mobile SDK for iOS 2.3.3 with `STANDARD_IA`. Thanks.
