### ISSUE TITLE
get access to AWSS3TransferManagerUploadRequest object after close and run the app again

### ISSUE THREAD

**Issue by pablogeek** [aws/aws-sdk-ios#256]
I'm trying to resume videos after close and run the app again. 

I'm using this method 

```
AWSS3TransferManager *manag = [AWSS3TransferManager S3TransferManagerForKey:video.uploadKey];

                    [manag resumeAll:^(AWSRequest *request) {

                    }];

```

How can I get the AWSS3TransferManagerUploadRequest object once I started the app? I need that object for set the uploadprogress block to update the progressbar

**Comment by yosuke-matsuda** [comment]
`AWSS3TransferManagerUploadRequest` is a subclass of `AWSRequest`. You can use `AWSRequest` for setting progress feedback blocks. Going forward, we focus our development effort on `AWSS3TransferUtility` and plan to phase out `AWSS3TransferManager` support. We recommend starting looking into `AWSS3TransferUtility` and see if it covers your needs.

**Comment by pablogeek** [comment]
Is not entering to that block inside of resumeAll block.
Steps to reproduce:

- Start to upload a file
- Force quit the app when the upload raise 6mb. 
- Run the app again and run resumeAll

@yosuke-matsuda
