### ISSUE TITLE
Using presigned urls in AWSS3TransferUtility

### ISSUE THREAD

**Issue by vphamdev** [aws/aws-sdk-ios#257]
How can I use a presigned url that was generated server side to upload a file from the client?
It doesn't appear possible as the transfer utility is building it's own presigned urls. What am I missing?

**Comment by yosuke-matsuda** [comment]
The pre-signed URL that `AWSS3PreSignedURLBuilder` generates is just an instance of `NSURL`, so you can use it just like a regular `NSURL`. You should read [URL Session Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/URLLoadingSystem.html#//apple_ref/doc/uid/10000165i) for details.

If you use `AWSS3TransferManager`, you don't need to generate a pre-signed URL for yourself.

**Comment by vphamdev** [comment]
Thanks @yosuke-matsuda , our architecture is that the server is generating a presigned url for the iOS client and I would love to utilize the AWSS3TransferUtility for the backgrounding capabilities and to leverage your efforts on the TransferUtility going forward.

The interface exposed by the TransferUtility does not appear to support using an already existing presigned url to upload a file. Is there any way for me to use the server's presigned url and also leverage AWSS3TransferUtility?

**Comment by yosuke-matsuda** [comment]
If you generate a pre-signed URL for yourself, you need to manage the upload/download for yourself as well. You can implement for yourself following Apple's programming guide.

**Comment by Parag2385** [comment]
> Thanks @yosuke-matsuda , our architecture is that the server is generating a presigned url for the iOS client and I would love to utilize the AWSS3TransferUtility for the backgrounding capabilities and to leverage your efforts on the TransferUtility going forward.
> 
> The interface exposed by the TransferUtility does not appear to support using an already existing presigned url to upload a file. Is there any way for me to use the server's presigned url and also leverage AWSS3TransferUtility?

Hey @vphamdev, were you able to upload files with TransferUtility with your server-generated pre-signed URLs? I'm having the same problem.

**Comment by vphamdev** [comment]
Hi @Parag2385, yes, I forked the repo in order to add a few convenience wrapper methods that accepted the presigned url as a parameter then calling through to the standard paths

**Comment by Parag2385** [comment]
@vphamdev Cool, nice. I'll try that. Is there any way you still have that forked repo, you can share?

**Comment by derwaldgeist** [comment]
IMHO, this should be a feature in AWSS3TransferUtility, so we can avoid storing any credentials client-side. Correct me if I am wrong, but to me this seems to be a security risk. Thus, I re-opened this as #4711.
