### ISSUE TITLE
Is there a max limit for S3 API parallel requests?

### ISSUE THREAD

**Issue by abc2mit** [aws/aws-sdk-ios#258]
There's one point in testing my app that I'm uploading 67 pieces of data to S3 simultaneously. What ends up happening is that about half of them go through and the other half returns a timeout error. Is that expected behavior? Is there some sort of queuing when multiple requests are executed?

**Comment by yosuke-matsuda** [comment]
It depends on how they are sent. You should share the code snippet for the upload. Also, how big are the files you tried to upload?

**Comment by abc2mit** [comment]
```Objective-C
- (AWSTask *)uploadToS3:(NSURL *)photoURL metadata:(NSDictionary *)photoMetadata {
    NSLog(@"Uploading photo to S3.");
    AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];
    AWSS3TransferManagerUploadRequest *uploadRequest = [[AWSS3TransferManagerUploadRequest alloc] init];
    // TODO change this to be configurable
    uploadRequest.bucket = S3_BUCKET;
    uploadRequest.key = photoMetadata[@"remoteUri"];
    uploadRequest.body = photoURL;
    return [transferManager upload:uploadRequest];
}
```

I basically call that method 60 times in a loop for a mass upload of photos that are 600KB in size. Since they are ```AWSTask```s, they all run in parallel. It looks like after 20, the rest of them will return with a timeout. Right now, I'm building a delay mechanism, but I haven't tested it yet. It looks something like this:

```Objective-C
- (AWSTask *)uploadToS3:(NSURL *)photoURL metadata:(NSDictionary *)photoMetadata {
    NSLog(@"Uploading photo to S3.");
    AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];
    AWSS3TransferManagerUploadRequest *uploadRequest = [[AWSS3TransferManagerUploadRequest alloc] init];
    // TODO change this to be configurable
    uploadRequest.bucket = S3_BUCKET;
    uploadRequest.key = photoMetadata[@"remoteUri"];
    uploadRequest.body = photoURL;
    return [[[[AWSTask taskWithDelay:_taskDelay] continueWithBlock:^id(AWSTask *task) {
        [self increaseTaskDelay];
        return task;
    }] continueWithBlock:^id(AWSTask *task) {
        return [transferManager upload:uploadRequest];
    }] continueWithBlock:^id(AWSTask *task) {
        [self decreaseTaskDelay];
        return task;
    }];
}
```

**Comment by yosuke-matsuda** [comment]
Instead of adding a delay and make all of them run in parallel, I recommend running them serially. In many situations, the mobile devices have limited bandwidth, and uploading files one by one usually generates a better result. See [this section](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html#in-sequence) of our guide for details. Also, by modifying this approach, you can create two or three lines of serial uploads if you want to upload two or three files in parallel depending on your network speed and file sizes.

**Comment by abc2mit** [comment]
... sigh. Running in serial is simplistic from a coding perspective by chaining ```AWSTasks```, but from a design perspective, it has a whole slew of problems when it comes to mobile design. Firstly, bandwidth may be an issue when running in parallel, but unless you have a spotty connection, asynchronous requests do not have to provide an immediate result, so the user doesn't really care how fast or slow it is. Secondly, bandwidth is determined by the network and the underlying phone antenna and firmware/software.

The biggest issue with mobile development is minimizing the battery usage. Keeping the radios powered for a long time (which is what is going to happen with a serial request), drains the battery significantly. (My expertise in this area comes from working on battery management issues with the *Fire Phone* where the 3D cameras, the screen, the GPS and the radio were all competing for battery resources.)

I ended up building my own dynamic queuing system that handles serializing and parallelizing requests based on the load (number of requests) triggered.
