### ISSUE TITLE
Retry with AWS ios

### ISSUE THREAD

**Issue by jplazcano87** [aws/aws-sdk-ios#259]
i'm using the aws sdk to upload some big pictures, i read all the documentation but there is no documented way to retry a failure upload when the app is killed or the internet connection is lost

```
- (void)upload:(AWSS3TransferManagerUploadRequest *)uploadRequest {
  
  AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];
  [[transferManager upload:uploadRequest] continueWithBlock:^id(AWSTask *task) {
    if (task.error) {
      if ([task.error.domain isEqualToString:AWSS3TransferManagerErrorDomain]) {
        switch (task.error.code) {
          case AWSS3TransferManagerErrorCancelled:
          case AWSS3TransferManagerErrorPaused:
          {
            
          }
            break;
            
          default:
            NSLog(@"Upload failed: [%@]", task.error);
            break;
        }
      } else {
        NSLog(@"Upload failed: [%@]", task.error);
      }
      
      if (self.delegate && [self.delegate respondsToSelector:@selector(s3TransferFailure)]) {
        [self.delegate s3TransferFailure];
      }
    }
    if (task.result) {
      NSLog(@"task result %@", task.result);
      NSLog(@"upload correct %@", task.error);
      [self updateStatus];
      if (self.delegate && [self.delegate respondsToSelector:@selector(s3TransferSuccess)]) {
        [self.delegate s3TransferSuccess];
      }
      
    }
    
    return nil;
  }];
}
```
there's any way to do this? the documentation is nos very clear and is a must for any developer using the SDK

The iOS AWS docs it doesn't mention anything about retrying on failed or faulted task. Yes, there is the AWSServiceConfiguration.maxRetryCount but that doesn't solve the issue with retrying faulted or failed tasks after that count as been exceeded. Also the iOS AWS Examples don't show anything in regards to this either.

**Comment by yosuke-matsuda** [comment]
The transfer manager tries to retry, but when it fails, you need to reinitiate the upload. So, you just need to create a new upload request object and call `- upload:`.

Going forward, we focus our development effort on `AWSS3TransferUtility` and plan to phase out `AWSS3TransferManager` support. We recommend starting looking into `AWSS3TransferUtility` and see if it covers your needs.
