### ISSUE TITLE
Symbol not found for arch x86_64

### ISSUE THREAD

**Issue by mhussain** [aws/aws-sdk-ios#260]
Hi, 

I am trying to use the Obj-C frameworks for AWSSQS in my project. And when I build, I get the following error messages. 
```Objective-C
"_OBJC_CLASS_$_AWSSQS", referenced from:
objc-class-ref in something.o
"_OBJC_CLASS_$_AWSSQSSendMessageRequest", referenced from:
objc-class-ref in something.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am using Xcode Version 7.0.1 (7A1001) on OS X 10.11 (15A284) 

I added the frameworks as mentioned in your README.md and then linked libsqlite, libz and Systemconfigiuration.framework in Build Phases. 

My settings for Architectures is 
```
Standard Architectures (armv7, arm64) - $(ARCHS_STANDARD)
```

My settings for Valid Architectures is
```
armv7 armv7s arm64
```

In the linking section of Build Settings, I have also ensured that I have the flag ```$(inherited)``` set for "Other Linker Flags". This was based off [this ](http://sohu.io/questions/33700/undefined-symbols-for-architecture-arm64)

Any help would be appreciated as I am lost. :(

**Comment by mhussain** [comment]
Just to clarify, I have included the following AWS frameworks into my project.

```
AWSCore.framework
extras/AWSCognito.framework
AWSSQS.framework
```

**Comment by yosuke-matsuda** [comment]
Can you share your import statement and code snippet? Also, what's the version of the AWS Mobile SDK for iOS you are using? The latest version of `AWSSQS.framework` supports five architectures including `x86_64`:
```
$ file AWSSQS 
AWSSQS: Mach-O universal binary with 5 architectures
AWSSQS (for architecture armv7):	current ar archive random library
AWSSQS (for architecture armv7s):	current ar archive random library
AWSSQS (for architecture i386):	current ar archive random library
AWSSQS (for architecture x86_64):	current ar archive random library
AWSSQS (for architecture arm64):	current ar archive random library
```

**Comment by mhussain** [comment]
I am importing AWSCore in AppDelegate.h like :
```
#import <UIKit/UIKit.h>
#import <CoreData/CoreData.h>
#import <AWSCore/AWSCore.h>
```

I am using the AWSCognito to get auth details in AppDelegate.m like:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
...
...
    
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1
                                                                                                    identityPoolId:kCognitoIdentityPoolId];
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1
                                                                         credentialsProvider:credentialsProvider];
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

And then I am using AWSSQS in Something.m like this
```

#import <AWSSQS/AWSSQS.h>
...
...

    AWSSQS *sqs = [[AWSSQS alloc] init];
    AWSSQSSendMessageRequest *messageRequest = [[AWSSQSSendMessageRequest alloc] init];
    [messageRequest setQueueUrl:kQueueURL"];
    [messageRequest setMessageBody:@"Testing postage"];
    [sqs sendMessage:messageRequest];
}
```

I downloaded the AWSSDK for iOS from [here](http://sdk-for-ios.amazonwebservices.com/latest/aws-ios-sdk.zip) and its version 2.2.7

I set up my project in this manner based on [these docs](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html)

**Comment by yosuke-matsuda** [comment]
Your import statements look just fine. Can you make sure you see `AWSCore.framework` and `AWSSQS.framework` listed under **Link Binary With Libraries** section?

This is not directly related to the compiler issue, but you should update 

    AWSSQS *sqs = [[AWSSQS alloc] init];

to

    AWSSQS *sqs = [AWSSQS defaultSQS];

Otherwise, it will cause a crash in the runtime.

**Comment by mhussain** [comment]
I do see it. Along with the other frameworks, and dylib's mentioned in the docs.

<img width="977" alt="screen shot 2015-10-21 at 8 27 33 am" src="https://cloud.githubusercontent.com/assets/300578/10621629/acc5be0c-77cd-11e5-9a23-671fb7bc6a1d.png">


W.r.t. %/alloc and init/defaultSQS/ .. will do. Thanks

**Comment by yosuke-matsuda** [comment]
**Framework Search Path** is correctly pointing to the frameworks, right? What do you see if you `cd` into `AWSSQS.framework` and run the following?

    $ ls -al
    $ file AWSSQS

**Comment by mhussain** [comment]
```bash
total 16
drwxr-xr-x@  5 mujtabahussain  staff   170 15 Oct 14:10 .
drwxr-xr-x  62 mujtabahussain  staff  2108 15 Oct 14:40 ..
lrwxr-xr-x   1 mujtabahussain  staff    23 15 Oct 14:10 AWSSQS -> Versions/Current/AWSSQS
lrwxr-xr-x   1 mujtabahussain  staff    24 15 Oct 14:10 Headers -> Versions/Current/Headers
drwxr-xr-x@  4 mujtabahussain  staff   136 15 Oct 14:10 Versions
 $  file AWSSQS
AWSSQS: Mach-O universal binary with 5 architectures
AWSSQS (for architecture armv7):	current ar archive random library
AWSSQS (for architecture armv7s):	current ar archive random library
AWSSQS (for architecture i386):	current ar archive random library
AWSSQS (for architecture x86_64):	current ar archive random library
AWSSQS (for architecture arm64):	current ar archive random library
  $ 
```

Definitely seems to be right

**Comment by yosuke-matsuda** [comment]
And **Framework Search Path**?

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. If you continue to encounter the issue, please feel free to update the thread with the information. Thanks.
