### ISSUE TITLE
All AWS SDK are complaining about "Duplicate interface definition for class xxx"

### ISSUE THREAD

**Issue by smartleoyu** [aws/aws-sdk-ios#263]
I just did an **pod update** on AWS SDK, then when I built the Xcode project, I got so many **"Duplicate interface definition for class xxx"**, and **"Property has a previous declaration"** from all AWS SDK pods, but other pods such as AFNetworking is not.

I am using Swift 2 (El Capitan + Xcode 7) and so I have this in my Objective-C Bridge Header file:
#import "AWSCognito.h"
#import "AWSCore.h"
#import "AWSDynamoDB.h"
#import "AWSS3.h"
#import "AWSSNS.h"
#import "AWSMobileAnalytics.h"

It used to be working perfectly before my **pod update**. I am not sure if this is cause by AWS SDK or Cocoapods, or others.

I have also created a question: http://stackoverflow.com/questions/33180650/pod-update-results-in-duplicate-interface-definition-for-class-xxx-for-all-aws

**Comment by minimalistcode** [comment]
I have the same problem.  I could not figure out how to fix it, so I restored my whole project from a backup the night before.

**Comment by yosuke-matsuda** [comment]
Can you share your `Podfile` and version of CocoaPods? Also, do you see the same issue with these [sample apps](https://github.com/awslabs/aws-sdk-ios-samples)?

**Comment by minimalistcode** [comment]
Thanks.  Running all 3 commands to clear the cache worked for me.

**Comment by srinathp90** [comment]
Simple solution here..it worked for me

Go to edit scheme -> Select Build -> Build option untick the Parallelize Build

Now run your App
