### ISSUE TITLE
iOS 8 and 9 use deprecated APIs

### ISSUE THREAD

**Issue by adamkuipers** [aws/aws-sdk-ios#264]
AWSCore and AWSS3 (I'm sure there are others but these are what I'm using) are using deprecated APIs.

In AWSCategory.m and AWSTMDiskCache.m:
> 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

In AWSMTLManagedObjectAdapter.m:
> 'NSConfinementConcurrencyType' is deprecated: first deprecated in iOS 9.0 - Use another NSManagedObjectContextConcurrencyType

In AWSTMDiskCache.m:
> 'CFURLCreateStringByReplacingPercentEscapesUsingEncoding' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByRemovingPercentEncoding] or CFURLCreateStringByReplacingPercentEscapes() instead, which always uses the recommended UTF-8 encoding.

In AWSUICKeyChainStore.m:
> 'kSecUseNoAuthenticationUI' is deprecated: first deprecated in iOS 9.0 - Use a kSecAuthenticationUI instead.

AWSS3TransferUtility.m:
> 'backgroundSessionConfiguration:' is deprecated: first deprecated in iOS 8.0 - Please use backgroundSessionConfigurationWithIdentifier: instead

**Comment by yosuke-matsuda** [comment]
We are aware of the warnings and will address them in the future release. Thanks.

**Comment by yosuke-matsuda** [comment]
We addressed the deprecation warnings with the new release of the SDK. Thanks.
