### ISSUE TITLE
Can not create a custom AWSEndpoint

### ISSUE THREAD

**Issue by dpakatheman** [aws/aws-sdk-ios#265]
I am trying to use the aws-sdk-ios to interface with Ivona Speech cloud, a TTS solution acquired by Amazon that uses AWS Signature Version 4.

http://developer.ivona.com/en/speechcloud/request-signing.html

Since Ivona is not supported by the aws-sdk-ios currently, I have tried to create a custom AWSEndpoint, but the AWSEndpoint properties are readonly, and the init methods only let me connect to preconfigured services.  

I'd prefer not to have to compile the aws-sdk-ios myself, but I believe it would be possible to do what I want with a class extension or by modifying the source code.

Is it possible to leverage the  aws-sdk-ios to connect to services not explicitly supported?  If not, is there a reason that it is designed to prevent this?

**Comment by yosuke-matsuda** [comment]
If you are trying to use the SDK for non-supported services, you need to update the SDK for yourself. A class extension is one way to do it.
