### ISSUE TITLE
XCode 7.1 : No longer builds against a development pod

### ISSUE THREAD

**Issue by solomon23** [aws/aws-sdk-ios#266]
If you create a development pod and reference AWSKinesis and AWSCore, the project will no longer build as of XCode 7.1.  It previously built clean in 7.0.1.  Here's a sample project:

https://www.dropbox.com/s/98h743arecqtwrs/BadPod%202.zip?dl=0

The discussion over on cocoapods:

https://github.com/CocoaPods/CocoaPods/issues/4420

**Comment by mikecole20** [comment]
+1

I'm having the same issue with AWSCore and AWSS3. My SDK (my private cocoapod) depends on AWSCore and AWSS3 and compiles fine. My app depends on my SDK (which includes AWSCore and AWSS3 in the podspec). AWSS3 gives the ```include of non-modular header inside framework module``` error when trying to compile the app. Everything worked well in Xcode 7.0.1.

**Comment by yosuke-matsuda** [comment]
We will look into this. Thanks.

**Comment by earulraj** [comment]
Any update to this issue.. Facing the same :(

**Comment by abeeriqbal** [comment]
Try to clean and rebuild your project

**Comment by rkawajiri** [comment]
Is this problem solved?

According to this PR https://github.com/aws/aws-sdk-ios/issues/272, this seems to be solved. However, I'm having the same issue on my private pod with 2.3.2.

**Comment by mikecole20** [comment]
It's still a problem for me as well.

**Comment by mikecole20** [comment]
I wanted to follow up on this. We just updated our SDK to use AWSCore 2.3.2 and AWSS3 2.3.2. Still getting the same issue when importing our SDK into our App.

From ```AWSBolts.h```:

```Include of non-modular header inside framework module 'AWSCore.AWEBolts'```

Which causes another build error in our swift file where we try to use ```import AWSCore```

```Could not build Objective-C module 'AWSCore'```

**Comment by yosuke-matsuda** [comment]
This issue has not been addressed. https://github.com/aws/aws-sdk-ios/issues/272 is a separate issue.

**Comment by Kumuluzz** [comment]
@yosuke-matsuda, are there any updates or progress made on this issue?

**Comment by moa7ed** [comment]
Any updates??

**Comment by yosuke-matsuda** [comment]
With CocoaPods 1.0.0, this issue should have been resolved. Please let us know if you keep encountering the issue. Thanks.
