### ISSUE TITLE
AWSTask blocks, swift 2.0 and nil return values

### ISSUE THREAD

**Issue by foscomputerservices** [aws/aws-sdk-ios#268]
Yesterday I attempted to integrate the SNS tools into my swift 2.0 (Xcode 7, iOS 9) project.  I was able to get it all integrated following the example project that was kindly generated for me from the AWS SNS website.

However when I started testing the code, I continually encountered optional unwrap runtime errors.  When returning nil from the various AWSTask blocks as indicated should be done in the example code.

As I investigated, the problem appeared to be with the non-attributed Objective-C header files that swift was consuming.  Swift decided that the APIs should return implicitly unwrapped optionals for the return values.

So, I forked the code and updated AWSTask.h adding in what seemed to be the correct _Nonnull/_Nullable flags and, as expected, the crashes went away.

Does this seem to be the correct way to solve this issue?  I'm quite surprised that no one else had already encountered this problem before.  Possibly I'm missing something?

If this is the correct approach, I'd be happy to generate a pull request.

**Comment by yosuke-matsuda** [comment]
I'm not sure what you mean by the SNS tools and the generated example project. Could you list the URLs you downloaded these from and the official names for them? Thanks.

**Comment by foscomputerservices** [comment]
Thank you for your followup!

As for the SNS tools, I was referring to the AWSSNS sdks (https://github.com/aws/aws-sdk-ios/tree/master/AWSSNS), which I am integrating into my Swift project via cocoa pods (pod 'AWSCore', '~> 2.2.7' and pod 'AWSSNS', '~> 2.2.7')

As for the generated code, I was referring to the project that was generated by the (beta) AWS Mobile Hub (https://console.aws.amazon.com/mobilehub/home?region=us-east-1#/).  Of course this is Objctive-C code, so I was using it as a template to write my swift version.

Additionally I referred to the README.md (https://github.com/aws/aws-sdk-ios/blob/master/README.md) in this repository, which has the following Swift example code:

```swift
dynamoDB.listTables(listTableInput).continueWithBlock{ (task: AWSTask!) -> AnyObject! in
    let listTablesOutput = task.result as AWSDynamoDBListTablesOutput

    for tableName : AnyObject in listTablesOutput.tableNames {
        println("\(tableName)")
    }

    return nil
}
```

In both the generated code from the AWS Mobile Hub and the this example, the blocks (of type AWSContinuationBlock) provided to AWSTask are expressed to return nil even though the function is declared implicitly unwrapped.  Running this example in my application causes 'EXC_BAD_INSTRUCTION' as one would expect.

Here's an example playground attempting to do the same thing:

```swift
func test() -> AnyObject! { return nil }
print(test()) // <- crashes
```

Since the Objective-C headers in AWSTask.h (in the aws-sdk-ios code) are not marked as to nullability (e.g. _Nullable/_Nonnull), swift improvises and we get the following (Xcode generated swift api from AWSTask.h):

```swift
/*!
 A block that can act as a continuation for a task.
 */
public typealias AWSContinuationBlock = (AWSTask!) -> AnyObject!
```

So, I forked the code and modified AWSTask.h as follows:

```objective-c
/*!
 A block that can act as a continuation for a task.
 */
typedef _Nullable id(^AWSContinuationBlock)(AWSTask * _Nonnull task);
```

Which give us the following swift type:

```swift
/*!
 A block that can act as a continuation for a task.
 */
public typealias AWSContinuationBlock = (AWSTask) -> AnyObject?
```

Then modified my usages as follows:

```swift
aTask.continueWithBlock{ (task: AWSTask) -> AnyObject? in
  // do a thing
  return nil
}
```

All now works beautifully.

**Comment by yosuke-matsuda** [comment]
Probably, the following line is causing the crash for you:

    let listTablesOutput = task.result as AWSDynamoDBListTablesOutput

The sample code assumes a successful execution of the call, but you need to check for errors in real life situations. `task.result` does not always have values. You should check if `task.error` has a value, and if it does, you should handle the error. Then you should check if `task.result` has a value and process the result. We'll update the sample code to reflect it.

**Comment by foscomputerservices** [comment]
What I'm really referring to is the fact that the return result is marked as implicitly unwrapped (AnyObject!). Thus when nil is returned from these functions, anyone that uses that result will crash (as demonstrated in the playground code that I provided above).

It seems to me that if the function is expected to return nil, then the return type should reflect that and be AnyObject? instead of AnyObject!

**Comment by yosuke-matsuda** [comment]
[BFTask](https://github.com/BoltsFramework/Bolts-iOS) is already updated with the nullability updates, so we will pick up the changes in the future. However, the crash you are seeing is most likely not caused by this. You need to update the error handling logic.

**Comment by foscomputerservices** [comment]
Great to hear about the nullability updates!

(BTW, the crashes that I'm seeing cannot possibly be due to what you're mentioning, because I'm not using that code; that is, I never copied that code into my project, and yes, I'm performing the checks that the API suggests).  I only showed the code above to demonstrate the return type of the function that was in the readme file.  But nonetheless, if the nullability changes are coming, that will solve the issue.  Thank you!)
