### ISSUE TITLE
resumeAll does not work after the app has been closed.

### ISSUE THREAD

**Issue by Tarang** [aws/aws-sdk-ios#271]
Reproduction

upload a file
close the app after more than 5mb has been uploaded
use `resumeAll`

The AWSS3 tests do not take into the account when the app has been closed.

The issue has already been raised before: https://github.com/aws/aws-sdk-ios/issues/154

**Comment by yosuke-matsuda** [comment]
We focus our development effort on `AWSS3TransferUtility` and plan to phase out `AWSS3TransferManager` support. We recommend starting looking into `AWSS3TransferUtility` and see if it covers your needs.
