### ISSUE TITLE
Xcode complain "Include of non-modular header inside framework"

### ISSUE THREAD

**Issue by saemitang** [aws/aws-sdk-ios#272]
I'm trying to include #import "&lt;AWSS3/AWSS3.h&gt;" into my umbrella header so that I can use AWSS3 framework inside my Swift codes. And Xcode keep complaining this error, "Include of non-modular header inside framework". I'm using AWSS3.framework and AWSCore.framework inside my own framework project. Any idea?

**Comment by yosuke-matsuda** [comment]
We currently do not ship our frameworks with module maps. We will update the thread when it is released. Thanks.

**Comment by yosuke-matsuda** [comment]
We addressed the issue with the AWS Mobile SDK for iOS 2.3.2. Thanks.

**Comment by saemitang** [comment]
Thank you v much.
