### ISSUE TITLE
IN condition in scan

### ISSUE THREAD

**Issue by batical** [aws/aws-sdk-ios#273]
Hello, 

Discovering dynamoDB with an IOS app.

Got some issue trying to find potential regitered user from a list of item

Let' imagine I got a User table with mail as a key.
I got an array of 50 mails, and I would like to know which mail is already in the database.

I got it working using a lambda invoke function.

```
 TableName : 'Users',
        AttributesToGet : ['mail'],
        ScanFilter: {
            'mail': {
            ComparisonOperator: 'IN',
            AttributeValueList: mails
            }
        }
```

But I cannot manage to do it directly from my ios using scanfilter ou filterExpression

```
let scanExpression : AWSDynamoDBScanExpression = AWSDynamoDBScanExpression()
		let usermailCondition = AWSDynamoDBCondition()
		let v1    = AWSDynamoDBAttributeValue();
		v1.SS = mails
		usermailCondition.comparisonOperator = AWSDynamoDBComparisonOperator.IN
		usermailCondition.attributeValueList = [ v1 ]
		scanExpression.scanFilter = ["mail" : 	usermailCondition]
```

```ComparisonOperator IN is not valid for SS AttributeValue type}```
Is it on purpose ? is there another way of doing it ?

thanks

**Comment by yosuke-matsuda** [comment]
As the error message suggests, your request has invalid structure. `scanFilter` is a legacy parameter for backward compatibility. You should use [`filterExpression`](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#FilteringResults).

Please note that `scan` potentially consumes a lot of read capacity units. `query` is usually more efficient. You should carefully pick your table structure and querying strategy based on your use case.

**Comment by batical** [comment]
I tried using filterExpression or scanFilter (spend a lot of time on it). The result is I cannot use IN condition with a filterExpression. (or a scanFilter ) from IOS part. It is working from a lambda function....


With a little more of reading since my first message, will give batchRequest a try (or query through lambda with IN condition) AS I was not able to use IN condition in ios sdk. 

Basically trying to find a way to do "indexKey in [IndexKeyArray]" with the less read capacity units consumed. As you said, scan would consume too much

Thanks for your answer
