### ISSUE TITLE
Chunked Upload (Background / Foreground)

### ISSUE THREAD

**Issue by darcwader** [aws/aws-sdk-ios#274]
I've seen the samples and documentation. is there any way to create a chunked upload to aws in the background? 

I know this can be done in foreground. but there also having a lot of trouble getting a sample to work. can you please point out to a sample to do chunked upload.

**Comment by yosuke-matsuda** [comment]
Currently, you need to divide the file into multiple parts for yourself.

**Comment by darcwader** [comment]
i have tried to create the parts, but it returns 403 error as the headers do not match. wanted to know if there is any sample for doing this?

also the background transfer in iOS is outright not supported i guess. can this be confirmed please.

**Comment by yosuke-matsuda** [comment]
You can split a file into multiple pieces using Apple's native APIs. You should refer to Apple's documentation.

`AWSTransferUtility` support background transfer while `AWSS3TransferManager` does not.
