### ISSUE TITLE
Multiple load operations overall progress with AWSS3TransferUtility

### ISSUE THREAD

**Issue by krasnodar95** [aws/aws-sdk-ios#275]
Tell me, how can I combine multiple load operations, and to monitor their overall progress with the help of AWSS3TransferUtility? I could not find such a possibility in the SDK. I need to combine the load groups. And I would even unite these groups. I need to get the overall progress of such associations.

**Comment by yosuke-matsuda** [comment]
`AWSS3TransferUtility` provides progress feedback per transfer. You can aggregate them as you need.

**Comment by krasnodar95** [comment]
Yes, I have no choice) I would like to hear from you how to do it. It is better if you show a concrete example of the code. Thank you.

**Comment by yosuke-matsuda** [comment]
You can share what you have done so far so that we can point you to the right direction. If you prefer one-on-one support, you can sign up for [AWS Support](https://aws.amazon.com/premiumsupport/). The technical support engineers can help you with the technical questions.

**Comment by krasnodar95** [comment]
Let's discuss here. Maybe someone also solves a similar problem. My task is to show that the indicator of downloading/uploading the package within which is located a multiple files. That decision that I'm trying to use has turned bad.
I created special classes and MyUploadTask MyDownloadTask. Since I still need at any time (even after the completion of the transaction) to show the files that belong to a specific task (MyUploadTask / MyDownloadTask), I made these classes heirs Object from RealmSwift. What would progress to aggregate data from multiple AWSS3TransferUtilityUploadTask / AWSS3TransferUtilityDownloadTask (next S3UpTask / S3DownTask), I made a wrapper classes over S3UpTask / S3DownTask, and called them MyUploadTaskItem, MyDownloadTaskItem. Here's an example

```
class MyDownloadTask: Object {
  dynamic var objectID = NSUUID().UUIDString
  let items = List<MyDownloadTaskItem>()

  var totalRecievedBytes: Int64 {
    return items.map{$0.totalRecievedBytes}.reduce(0){$0 + $1}
  }
  
  var totalBytesExpectedToRecieve: Int64 {
    return items.map{$0.totalBytesExpectedToRecieve}.reduce(0){$0 + $1}
  }
  
  var progress: Float {
    if totalBytesExpectedToRecieve == 0 {
      return 0
    }
    
    return Float(totalRecievedBytes) / Float(totalBytesExpectedToRecieve)
  }
  
  var downloadingCompleted: Bool {
    return items.map{$0.downloadingCompleted}.reduce(true){$0 && $1}
  }

  override static func primaryKey() -> String? {
    return "objectID"
  }
}


class MyDownloadTaskItem: Object {
  dynamic var objectID = NSUUID().UUIDString
  dynamic var downloadingCompleted = false
  dynamic var awsTaskID: Int64 = 0

  var totalRecievedBytes: Int64
  var totalBytesExpectedToRecieve: Int64

  dynamic var downloadedObject: AnyObject?

  override static func primaryKey() -> String? {
    return "objectID"
  }

  override static func ignoredProperties() -> [String] {
    return ["totalRecievedBytes", "totalBytesExpectedToRecieve"]
  }
}
```

I do not keep progress in Realm (you can see it at ignoredProperties). When I get to the screen where I need to show the download progress bar, I make a request of the Realm all objects of type MyDownloadTask. And my ViewController begins to catch NSNotifications, I send during AWSS3TransferUtilityDownloadProgressBlock. Similarly, I than passes notifications during AWSS3TransferUtilityDownloadCompletionHandlerBlock that would assign the task a status of "complete." I really hate my decision, but as I tried, I did not come up with the best. Even my looks awful load indicator, which can run it back and forth, depending on the order of notifications.

**Comment by yosuke-matsuda** [comment]
It sounds like the main issue is that you lose the current progress when you leave the screen. When the view controller is reconstructed, you start getting the partial results. You can separate the progress tracking logic, a model (M) in MVC, from the view controller, and make sure it is not released until all transfers complete.

**Comment by krasnodar95** [comment]
You propose to create a class Progress Tracker? And somehow linked to an instance AWSS3DT? Can you sketch out an example?

**Comment by yosuke-matsuda** [comment]
[AWS Support](https://aws.amazon.com/premiumsupport/) provides Architecture support. They should be able to help you with that.

**Comment by krasnodar95** [comment]
Thanks

**Comment by riazhazan** [comment]
@yosuke-matsuda Did you get a solution for this?
