### ISSUE TITLE
Is AWSS3TransferUtility viable for production code

### ISSUE THREAD

**Issue by android1989** [aws/aws-sdk-ios#276]
I have seen a couple of issues with a response that "development is currently focused on AWSS3TransferUtility and developers should start looking into it to see if it can solve their needs." I think for my needs it would fit perfectly, but currently it is in beta and I am worried about building out a solution for production while it is still in such a state. 

Any idea of when AWSS3TransferUtility will exit beta and be useable in production applications?

**Comment by yosuke-matsuda** [comment]
While we cannot discuss our future plans, `AWSS3TransferUtility` has a few limitations as described in this [blog post](https://mobile.awsblog.com/post/Tx283AGGIL76PKP/Amazon-S3-Transfer-Utility-for-iOS). If it suits your use case, it is more stable and reliable than `AWSS3TransferManager.
