### ISSUE TITLE
AWSS3TransferUtility - adding metadata to an upload request

### ISSUE THREAD

**Issue by android1989** [aws/aws-sdk-ios#277]
I have scanned through the AWSS3TransferUtility code and cannot find a way to add metadata to the request. We currently add some post-processing instructions in AWSS3TransferManagerUploadRequest's metadata and our server will take care of the rest. 

I am wondering if I am missing something or if another technique is favored over this approach.

**Comment by yosuke-matsuda** [comment]
The transfer utility upload takes an expression object. You can add metadata to the expression by calling [– setValue:forRequestParameter:](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtilityExpression.html#//api/name/setValue:forRequestParameter:).
