### ISSUE TITLE
Autogenerated AWSAPIGatewayClient now throwing fatal with latest update

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#278]
https://github.com/aws/aws-sdk-ios/commit/740ba6ecf34500cbc2e914a42b0593106e785caf#diff-ac0048d415614e973a15af0558562828R326

**Comment by yosuke-matsuda** [comment]
Have you modified the `Podfile` shipped with the API Gateway SDK? Or, are you using `AWSCore.framework`?

**Comment by rromanchuk** [comment]
```
PODS:
  - AWSAPIGateway (2.3.0):
    - AWSCore (= 2.3.0)
  - AWSCognito (2.3.0):
    - AWSCore (= 2.3.0)
  - AWSCore (2.3.0)
  - AWSDynamoDB (2.3.0):
    - AWSCore (= 2.3.0)
  - AWSMobileAnalytics (2.3.0):
    - AWSCore (= 2.3.0)
  - AWSSNS (2.3.0):
    - AWSCore (= 2.3.0)
  - AWSSQS (2.3.0):
    - AWSCore (= 2.3.0)
```

**Comment by rromanchuk** [comment]
The callee is autogenerated SDK client code form the API Gateway console

**Comment by yosuke-matsuda** [comment]
Thank you for confirming the modifications to the `Podfile`. Can you call the following to clear the CocoaPods's cache, remove `/Pods` and `Podfile.lock`, then install the pods again?

    pod cache clean --all

Please let us know if this fixes the issue. Thanks.

**Comment by rromanchuk** [comment]
ahh, looks good now. Thanks!
