### ISSUE TITLE
AWSS3TransferUtility - Ability to add priority to a Task

### ISSUE THREAD

**Issue by renjithn** [aws/aws-sdk-ios#279]
The default NSURLSessionTask has a priority property which can be useful in several situations.

Shouldn't the AWSS3TransferUtilityTask class expose the underlying NSURLSessionTask so that its priority can be set?

**Comment by yosuke-matsuda** [comment]
We will evaluate how we can best provide the feature. Thanks.

**Comment by yosuke-matsuda** [comment]
Starting with 2.4.1, `AWSS3TransferUtilityTask` exposes the underlying `NSURLSessionTask`. Thanks.
