### ISSUE TITLE
Support for tvOS

### ISSUE THREAD

**Issue by lackernabouticare** [aws/aws-sdk-ios#280]
Is there any intention to provide SDK support for tvOS?

**Comment by skyebook** [comment]
+1

**Comment by yosuke-matsuda** [comment]
I will share this as a feature request with my team. Thanks.

**Comment by ravindhiran** [comment]
AWS SDK for tvos ?

**Comment by pierreg256** [comment]
+1

**Comment by helloniklas** [comment]
+1

**Comment by m-etka** [comment]
**+1**

**Comment by elgordino** [comment]
Any news on this?

**Comment by johnspurlock** [comment]
+1

**Comment by helloniklas** [comment]
+1

**Comment by tfonfara** [comment]
+1

**Comment by deepp** [comment]
Any news on this or update? I would need it for already existing iOS app , which i would be porting for tvOS. Any alternative?

**Comment by cptobvious** [comment]
+1

**Comment by kjsujesh** [comment]
+1

**Comment by chayakornS** [comment]
+1

**Comment by Abeansits** [comment]
Any news @yosuke-matsuda ?

**Comment by Abeansits** [comment]
There's an open PR for it: https://github.com/aws/aws-sdk-ios/pull/608

**Comment by ameter** [comment]
For anyone that comes across this ticket looking for tvOS support, the new [aws-sdk-swift](https://github.com/awslabs/aws-sdk-swift) will support tvOS as well as all other platforms that are supported by Swift.  At the time of this writing, [aws-sdk-swift](https://github.com/awslabs/aws-sdk-swift) is available as an alpha release.

For more information, see this [blog post](https://aws.amazon.com/blogs/developer/announcing-new-aws-sdk-for-swift-alpha-release/)

Support for non-iOS platforms is being tracked under this [ticket](https://github.com/awslabs/aws-sdk-swift/issues/376). If this capability is important to you, please 'thumb-up' the ticket to help us with prioritization.
