### ISSUE TITLE
AWSS3TransferUtilityTask has no response information

### ISSUE THREAD

**Issue by bryansum** [aws/aws-sdk-ios#281]
This came from me debugging a non-working S3 upload... Using the `uploadFile:` syntax, `AWSS3TransferUtilityUploadCompletionHandlerBlock` returns a completion handler with the associated `AWSS3TransferUtilityTask` and an error. The issue is that the error returned only incorporates `NSURLSessionTask` client-side errors; so if S3 returns an error response we have no way of verifying this.

**Comment by yosuke-matsuda** [comment]
We will address it in the future release of the SDK. Thanks.

**Comment by Skorch** [comment]
The same goes for the `AWSS3TransferUtilityDownloadCompletionHandlerBlock`.  If the file doesn't exist, or the permissions are incorrect, you receive no indication of a 403 error, exception you do receive the error XML document.  There's no way to know that the data is invalid.

**Comment by desmondmcnamee** [comment]
+1

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.4.1, which addresses this issue. Thanks.
