### ISSUE TITLE
Support for Extension

### ISSUE THREAD

**Issue by virengujariya** [aws/aws-sdk-ios#283]
I'm using services on iOS Share Extension. Any idea when/why this error? However AWSS3TransferUtility is executed and has result. 

```
AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityUploadTask *task, NSError *error) {
            dispatch_async(dispatch_get_main_queue(), ^{
                // Do something e.g. Alert a user for transfer completion.
                // On failed uploads, `error` contains the error object.
                if (error) {
                    NSLog(@"Error: %@", error.localizedDescription);
                } else {
                    NSLog(@"Done %@", @"Success");
                }
            });
        };
```

**Comment by yosuke-matsuda** [comment]
Currently, the iOS extension is not officially supported. I'll share this as a feature request to the team. If you use CocoaPods, you can try setting `sharedContainerIdentifier` to the underlying `NSURLSession` and see if it resolves the issue.

**Comment by virengujariya** [comment]
@yosuke-matsuda Awesome! Added '''configuration.sharedContainerIdentifier = @"here goes extension group package name";''' in AWSS3TransferUtility.m and it worked.

**Comment by karthiksaligrama** [comment]
Added support for setting `sharedContainerIdentifier` in the `ServiceConfiguration` with 2.4.6

**Comment by imackinn** [comment]
@karthiksaligrama appreciated

**Comment by swaroopgs** [comment]
@karthiksaligrama can i set sharedContainerIdentifier in my class where i am initializing the transfer utility.

**Comment by swaroopgs** [comment]
@karthiksaligrama can i set sharedContainerIdentifier in my class where i am initializing the transfer utility?

**Comment by VigneshPT** [comment]
@karthiksaligrama We have added the sdk through Pods, and it would not be a good idea to go and modify the AWSS3TransferUtility.m file. Would I be able to set the sharedContainerIdentifier through Info.plist or is there any other way I could do this?

**Comment by VigneshPT** [comment]
@karthiksaligrama Possible to set the sharedContainerIdentifier through the Info.plist file?
