### ISSUE TITLE
CognitoSyncDemo AWS Cognito.default() = nil

### ISSUE THREAD

**Issue by ducmaxime** [aws/aws-sdk-ios#284]
I try connect with developper account. But AWSCognito.defaultCognito() function return always nil value

My code

      let identityProvider = DeveloperAuthenticatedIdentityProvider(
            regionType: Constants.awsRegionType,
            identityId: identityId,
            identityPoolId: Constants.AWS_POOLID,
            logins: logins,
            providerName: Constants.AWS_DEVELOPER_PROVIDER,
            token:token,
            authClient: nil)
            
            
       let cognitoProvider = AWSCognitoCredentialsProvider(regionType: Constants.awsRegionType, identityProvider: identityProvider, unauthRoleArn: nil, authRoleArn: nil)
        let configuration = AWSServiceConfiguration(region: Constants.awsRegionType, credentialsProvider: cognitoProvider)
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration
   
        let syncClient  = AWSCognito.defaultCognito()

**Comment by nishkrishnan** [comment]
Hey, I am unable to reproduce this with my Identity Pool configuration.  Can you step into defaultCognito() and see where exactly it is returning nil? Also, can you provide additional code to help me diagnose this issue?  Thanks, Nish

**Comment by yosuke-matsuda** [comment]
We assume the issue has been resolved. If you continue to encountering the issue, please feel free to update the thread with the requested information. Thanks.

**Comment by ducmaxime** [comment]
I have resolve issue.
I instantiate AWSCognito with my own configuration :
