### ISSUE TITLE
Compile error when AWSCore imported

### ISSUE THREAD

**Issue by daupawar** [aws/aws-sdk-ios#288]
When i import '#import <AWSCore/AWSCore.h>' I get the below mentioned errors . Thanks for your help .

AWS Frameworks/AWSCore.framework/Headers/AWSSTSModel.h:63:51: Expected ';' at end of declaration list
AWS Frameworks/AWSCore.framework/Headers/AWSSTSModel.h:68:42: Property has a previous declaration

**Comment by yosuke-matsuda** [comment]
Can you post the detailed steps to reproduce the issue? What version of Xcode and the AWS Mobile SDK are you using? Have you made sure you are not importing multiple copies of the same framework?

**Comment by daupawar** [comment]
I am using Xcode version 6.4
 I have a couple of other pods that I am including in my podfile.
Heres how the podfile looks like,platform :ios, '7.0'
pod 'ObjectiveDDP'
pod 'Mantle', '~> 1.5.1'
pod 'RequestUtils', '~> 1.1'
pod 'M13OrderedDictionary', '~> 1.0.6'
pod 'ArcGIS-Runtime-SDK-iOS' 

pod 'MBProgressHUD', '~> 0.9.1'

source 'https://github.com/CocoaPods/Specs.git'

pod 'AWSS3'

**Comment by yosuke-matsuda** [comment]
The latest version of the AWS Mobile SDK for iOS supports Xcode 7 and later as mentioned in README. You can specify the version to `2.2.7` if you cannot upgrade it to Xcode 7 yet.

**Comment by daupawar** [comment]
Thank you yosuke-matsuda,
I'll try to update xcode version and check.
