### ISSUE TITLE
AWSTask blog post is really out of date

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aws/aws-sdk-ios#291]
This link referenced in readme http://mobile.awsblog.com/post/Tx2B17V9NSVLP3I/The-AWS-Mobile-SDK-for-iOS-How-to-use-BFTask is really hard to read as class names don't match (apparently it was BTTask) and awsblog has very bad syntax highlighting.

After spending 10 minutes, I still could not understand a bit at all. I suggest having it as a topic in this repository.

**Comment by fosterzhang** [comment]
Thanks for the suggestion. We'll definitely take it into consideration.

**Comment by yosuke-matsuda** [comment]
Our [Developer Guide](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html) is the maintained and up-to-date source of information regarding how to use our SDK. Please refer to this guide instead. Thanks.

**Comment by ahmetalpbalkan** [comment]
@yosuke-matsuda  Thanks.
