### ISSUE TITLE
Multiple Semantic issues in AWSCognitoIdentityModel.h

### ISSUE THREAD

**Issue by praveenaj** [aws/aws-sdk-ios#292]
I was using AWS SDK 2.1.0 (not installed using cocoapods) and just installed latest version using cocoapods. I followed this guide to migrate https://mobile.awsblog.com/post/Tx31LFFH2WPO706/AWS-Mobile-SDK-for-iOS-2-2-0

But getting the following errors when compiling:
 ![image](https://cloud.githubusercontent.com/assets/538142/11760693/94f8bd94-a0ca-11e5-9427-6c080d204f40.png)

Environment:
Xcode: Version 6.4 (6E35b)
OSX: El Capitan 10.11.2 (15C50)

**Comment by rohandubal** [comment]
Hi, 
Which is the AWS SDK version you are trying to update to? The latest one is 2.3.2 and only supports Xcode 7 and above. Thanks.

-Rohan
