### ISSUE TITLE
AWSKinesisRecorder#saveRecord is not Asynchronous method?

### ISSUE THREAD

**Issue by rkawajiri** [aws/aws-sdk-ios#294]
In my understand, `AWSKinesisRecorder#saveRecord` method is Asynchronous method.
  - http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html

However, the method deadlocked on main thread when we started to use SDK 2.3.2 (the previous SDK was 2.2.3).

![screen shot 2015-12-14 at 11 26 06](https://cloud.githubusercontent.com/assets/661102/11771578/a007ca04-a255-11e5-8ae2-b8025b173461.png)

Do you have any ideas?

**Comment by yosuke-matsuda** [comment]
Can you share a code snippet to reproduce the issue? Thanks.

**Comment by rkawajiri** [comment]
I cannot reproduce the same bug even when I back to the same source code.
So please close this issue. This problem may be resolved by clearing caches or something.

But, I describe below more details for someone who see similar issues again.

`saveRecord` method was indirectly called in `application didFinishLaunchingWithOptions` after Cognito and Kinesis Configurations in main thread. But the application was stacked. So I paused the app from XCode. Then the above screenshot shows.

By following the debugger, the below line is processed.
https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Bolts/AWSExecutor.m#L62
It does not seems to executed asynchronously (right?).

So I resolved this issues by wrapping `saveRecord` method itself with `dispatch_async` for this time.
