### ISSUE TITLE
Lambda invocation works in aws-sdk-iOS 2.3.0, breaks in aws-sdk-iOS 2.3.2

### ISSUE THREAD

**Issue by sumitlni** [aws/aws-sdk-ios#297]
When calling
```objc
 [[AWSCloudLogic sharedInstance] invokeFunction: withParameters: withCompletionBlock:^(id result, NSError *error)
```
I kept getting `ResourceNotFound` exception. Fortunately I had an older binary (to be precise, a MySampleApp demo generated via Mobile Hub) available that I was able to compare against. In aws-sdk-iOS/2.3.0, the invocation headers are:
```
content-type:application/x-amz-json-1.0
host:lambda.us-east-1.amazonaws.com
user-agent:aws-sdk-iOS/2.3.0 iPhone-OS/9.2 en_US MobileHub 6552f27b-9ab2-45c3-afd2-012bbeb85c4f aws-my-sample-app-ios-objc-v0.4 invoker
```
Notice the **host** line. In aws-sdk-iOS/2.3.2, the invocation headers change to:

```
content-type:application/x-amz-json-1.0
host:data.iot.us-east-1.amazonaws.com
user-agent:aws-sdk-iOS/2.3.2 iPhone-OS/9.2 en_US MobileHub 6552f27b-9ab2-45c3-afd2-012bbeb85c4f aws-my-sample-app-ios-objc-v0.4 invoker
```
I did no configuration changes, either in the app or through the AWS console, but for some reason the host changes from `lambda.*` to `data.iot.*` which causes Lambda invocation to fail. Downgrading to aws-sdk-iOS/2.3.0 made the problem go away, so the issue definitely points to a bug in aws-sdk-iOS/2.3.2.

**Comment by yosuke-matsuda** [comment]
It sounds like you updated `AWSCore.framework` to 2.3.2, but did not update `AWSLambda.framework`. You cannot mix different versions of frameworks. Please use the same version of the AWS frameworks in your app.

**Comment by sumitlni** [comment]
You are absolutely correct - brilliant piece of deduction by the way! I was linking with a static version of AWSLambda, removed it, added to Podfile, updated and it works beautifully! Eating humble pie and closing the issue, thanks for your help!
