### ISSUE TITLE
IdentityId changing across app restarts

### ISSUE THREAD

**Issue by sumitlni** [aws/aws-sdk-ios#298]
The issue has been posted as a question at http://stackoverflow.com/questions/34620614/aws-cognito-identityid-changing-for-anonymous-guest-users . Basically the identityId is changing for the guest login, causing app malfunction as it relies on identityId as hash key for DynamoDB lookup. Please advise.

**Comment by yosuke-matsuda** [comment]
The Stackoverflow question is being answered by the AWS engineer. Closing this one in favor of the SO thread.
