### ISSUE TITLE
"Certificate is invalid" error when using cognito identity pool

### ISSUE THREAD

**Issue by erawhctim** [aws/aws-sdk-ios#299]
First off I apologize if this is the wrong place to post this.

I'm using the AWS SDK to authenticate via a cognito identity pool and fetch items from S3. I ran into this issue on an iOS 8.3 device, and previously had zero errors using an iOS 9 device (I'm not sure if that is relevant or not):

```
AWSiOSSDKv2 [Error] AWSURLSessionManager.m line:260 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error
Domain=NSURLErrorDomain 
Code=-1202 
"The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cognito-identity.us-east-1.amazonaws.com” which could put your confidential information at risk."
UserInfo=0x1741b8020 {NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1700d1950>,
NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?,
_kCFStreamErrorCodeKey=-9807, 
NSUnderlyingError=0x17404b070 "The operation couldn’t be completed. 
(kCFErrorDomainCFNetwork error -1202.)", 
NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cognito-identity.us-east-1.amazonaws.com” which could put your confidential information at risk., 
NSErrorFailingURLKey=https://cognito-identity.us-east-1.amazonaws.com/,
NSErrorFailingURLStringKey=https://cognito-identity.us-east-1.amazonaws.com/,
_kCFStreamErrorDomainKey=3}
```

The error repeats a few times at `AWSURLSessionManager.m line:260` and `AWSIdentityProvider.m line:188`, and the entire chain of errors seems to stem from a call to `AWSS3.defaultS3().listObjects(...)`

After searching online I found these two links on SO:
http://stackoverflow.com/a/18366596
http://stackoverflow.com/a/30720929

The second one seemed like a possible solution, though I'm really lost at this point... Any help would be greatly appreciated.

**Comment by yosuke-matsuda** [comment]
Do you have any proxy between your device and the AWS service? It seems like an environmental issue. Do you know under what circumstances you can reproduce the error?

**Comment by erawhctim** [comment]
So it turns out this was unrelated to the AWS SDK (apologies!) but in fact caused by the date/time not being set properly on the device (since it didn't have a sim card and was set to the default 1/1/1970 epoch date). 

Visiting other https links in the browser on the device resulted in similar "Certificate cannot be trusted" errors, and resetting the device's date/time alleviated the issue.
