### ISSUE TITLE
AWSURLSessionMAnager.m error caused by pausing.. Also unable to resume download task.

### ISSUE THREAD

**Issue by Jreyno40** [aws/aws-sdk-ios#302]
Here are the error messages I am getting (in the if(task.error != nil) block of a transfer manager download):

I get this message when attempting to pause a task:

```
AWSiOSSDKv2 [Error] AWSURLSessionManager.m line:260 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://s3.amazonaws.com/..., NSErrorFailingURLStringKey=https://s3.amazonaws.com/..., NSLocalizedDescription=cancelled}
```
I am not exactly sure what is causing this error:
```
AWSiOSSDKv2 [Error] AWSS3TransferManager.m line:530 | -[AWSS3TransferManager download:cacheKey:] | Unable to resume download task: Failed to retrival tempFileURL. [Error Domain=NSCocoaErrorDomain Code=260 "The file “...” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/AE52CBF4-650E-4B42-B69D-4AA604081024/tmp/..., NSUnderlyingError=0x168412b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}]
```

Any help would be greatly appreciated! What causes these messages? Specifically the first one. When I go to read AWSURLSessionManager.m line:260, I cannot figure out what is causing this because I have no idea what calls the function.

**Comment by yosuke-matsuda** [comment]
`- pause` cancels the currently running task, so the first error is expected.

Going forward, we focus our development effort on `AWSS3TransferUtility` and plan to phase out `AWSS3TransferManager` support. We recommend starting looking into `AWSS3TransferUtility` and see if it covers your needs.
