### ISSUE TITLE
Add support for custom AWS service endpoint

### ISSUE THREAD

**Issue by anozaki** [aws/aws-sdk-ios#303]
IoT framework provides account specific URL to connect to, but the api doesn't give you a way to specify a host.

**Comment by gkwicker** [comment]
Thanks for pointing this out.  There should be a way to specify your account-specific URL when connecting to the service, so we'll look into adding this in an upcoming release.

**Comment by DsrMedia** [comment]
Is there any update on this feature? We've tried to implement the iOS SDK with the same setup as the Android SDK with no luck.

**Comment by karthiksaligrama** [comment]
Added in v2.4.9. Please refer https://github.com/aws/aws-sdk-ios/blob/master/AWSS3Tests/AWSS3Tests.m#L311 for sample
