### ISSUE TITLE
can't change endpoint in sdk ios V2

### ISSUE THREAD

**Issue by WildanGarviandi** [aws/aws-sdk-ios#304]
my backend team said i need to upload to an custom endpoint
eg.https://s3-ap-southeast1.amazonaws.com/my-team/ but all i got is https://s3.amazonaws.com/my-team/ how can i change the endpoint?

**Comment by yosuke-matsuda** [comment]
You need to change the region in `AWSServiceConfiguration`. See [this sample](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3BackgroundTransfer-Sample/Objective-C/S3BackgroundTransferSampleObjC/AppDelegate.m#L25) app as an example.

**Comment by WildanGarviandi** [comment]
@yosuke-matsuda yes it works now, i was set the wrong region it sould be point to singapore but i set to other region, thanks btw
