### ISSUE TITLE
ResumeAll removes from Cache

### ISSUE THREAD

**Issue by nthState** [aws/aws-sdk-ios#306]
Hi,
If I pauseAll, then resumeAll, the upload is removed from the cache, so I cannot pauseAll again.

I think the issue is below the line
//remove Resumed Object

**Comment by rohandubal** [comment]
Hi nthState, we focus our development efforts on AWSS3TransferUtility and plan to phase out AWSS3TransferManager support. We recommend you take a look into AWSS3TransferUtility and see if it covers your needs.

**Comment by nthState** [comment]
Hi, Thanks, unfortunately, the 50 minute limit is a deal breaker for me, I'm having to work with a 3G connection and require features like multi-part upload.
