### ISSUE TITLE
Authentication Provider in swift 

### ISSUE THREAD

**Issue by LamourBt** [aws/aws-sdk-ios#307]
Ok guys, I am just tired and frustrated because I cannot be that crazy to create a simple login using AWS, So I created my identity pool where I created [ **Identity Pool Id, Identity Pool Name, Identity Pool ARN , and Developer provider name , Unauthenticated Role, Authenticated Role** ]  then I created the stack using the CloudFormationManager and t**he status CREATE_COMPLETE and I have the URLApplication which is in form of http://21.564.545.87. **

Now in the class below I am confused because its not clear on how to get the **token**, so here is my code 
```

 class IdentityProvider: AWSAbstractCognitoIdentityProvider
{
 override func refresh() -> AWSTask! {

          let task = AWSTaskCompletionSource().task
         if !self.isAuthenticated()  {
          return super.getIdentityId()
       }
      
        let tmp = NSMutableDictionary()
        tmp.setObject("temp", forKey: "IdentityPoolARN")
        self.logins = tmp as [NSObject : AnyObject]
        
        self.identityId = "IdentityPoolID"
        self._token = ""         //<-------------------------- how should I be able to retrieve this ?
        
        return AWSTask(result: self.identityId)
    }
}
```
The code on stackoverflow is no help.. 
The document http://docs.aws.amazon.com/cognito/devguide/identity/developer-authenticated-identities/  here  throw me of the track because when you get to part on how to get the token for swift the code provided is an java like really. Can Anyone really help please ?

**Comment by rachitdhall** [comment]
Hi,

When using developer authenticated identities, the way to get the identityId and token is through the [GetOpenIdTokenForDeveloperIdentity](http://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetOpenIdTokenForDeveloperIdentity.html) API. You would need a backend or authentication server of your own which takes in the username and password from the application, then call the above mentioned API. This would return an identityId and a token which you can pass it back to you application. You can always post your questions on our [forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)

Thanks,
Rachit

**Comment by rachitdhall** [comment]
Closing this in favor of the [same issue](https://github.com/awslabs/aws-sdk-ios-samples/issues/46) in the samples repository
