### ISSUE TITLE
AWSS3TransferUtility - configure to disable Cellular network access 

### ISSUE THREAD

**Issue by bradgmueller** [aws/aws-sdk-ios#310]
Currently the `AWSS3TransferUtility` doesn't expose the `NSURLSessionConfiguration` used in initialization. This doesn't allow modifying the configuration to set `allowsCellularAccess = NO`. 

Since the Transfer Utility serves to facilitate uploading/downloading large files in the background, I think having the ability to limit these requests to Wi-Fi only would be a good addition. 

Thanks!

**Comment by yosuke-matsuda** [comment]
We are considering adding this feature in the future release. Thanks.

**Comment by corbt** [comment]
@yosuke-matsuda would you accept a pull request implementing this functionality? We upload large video files in the background and it's critical that we give our users the ability to only upload when connected to wifi.

**Comment by yosuke-matsuda** [comment]
There is actually already [one](https://github.com/aws/aws-sdk-ios/pull/323), and we pulled it. With the next release, we'll update the podspecs and frameworks. We always appreciate user contributions :)

**Comment by corbt** [comment]
@yosuke-matsuda oh, awesome! That moved faster than I expected. Do you have a release schedule planned for the next version?

**Comment by yosuke-matsuda** [comment]
The feature went live with the release of the AWS Mobile SDK for iOS 2.3.6. Thanks.
