### ISSUE TITLE
Definition of 'Fabric' must be imported from module 'AWSCore.Fabric' before it is required

### ISSUE THREAD

**Issue by anbarasu0504** [aws/aws-sdk-ios#311]
Before adding 'AWSDynamoDB' to pod, the below code

`[Fabric with:@[CrashlyticsKit]];`

 in our project's AppDelegate was not creating any problem but after adding, the build fails with error

> Definition of 'Fabric' must be imported from module 'AWSCore.Fabric' before it is required

**Comment by yosuke-matsuda** [comment]
How are you importing Fabric in the file? Are you explicitly calling `@import Fabric;`?

**Comment by anbarasu0504** [comment]
`#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>`

**Comment by yosuke-matsuda** [comment]
The duplicated protocol definition headers may be colliding. What happens if you remove the AWS SDKs from the pod and import the frameworks from our [website](https://aws.amazon.com/mobile/sdk/)?

**Comment by anbarasu0504** [comment]
We tried removing DynamoDB from pods and adding it manually to the project. Still we are getting the same error, unable to run the project.

**Comment by m-conklin** [comment]
I am experiencing the same error, and have also tried importing the framework, which has not rectified the problem.

**Comment by pconno** [comment]
I am also experiencing this. Any work around?

**Comment by pconno** [comment]
I was able to fix this by importing #import <Fabric/Fabric.h> after importing AWSCore

**Comment by m-conklin** [comment]
YES!!

Thanks, that is perfect.

#import "AWSCore/AWSCore.h"
#import <Fabric/Fabric.h>

Problem soved.

**Comment by anbarasu0504** [comment]
Yes. This worked :+1:

**Comment by yosuke-matsuda** [comment]
Could you try the AWS SDK 2.3.5 and see if it resolves the issue? Thanks.

**Comment by pconno** [comment]
Hmm, this actually seems to have broken something with FMDB. Likely a separate but similar issue. I'll have to dig more

**Comment by m-conklin** [comment]
The hack in my above comment was working well, until I went to archive the app.

Now there is an error with the Duplicate definition of Fabric.h in both AWSCore and in the Fabric pod.

**Comment by m-conklin** [comment]
Hats off to @yosuke-matsuda.

Ran a pod update, AWSCore 2.3.5, and I can now archive.

Well played AWS team!

**Comment by wkoszek** [comment]
@yosuke-matsuda I was not running into this problem at all in `2.3.6` at all, but I have upgraded my AWS Pods recently to `2.4.0`:

https://github.com/wkoszek/sensorama-ios/commit/0f6e314d784821c826a19f43dcbf3f57327593c6

I'm hitting this problem. Symptom is the same as guys explained above. However there is a weird behaviour for unit tests in my case. I build them with CMD+SHIFT+u:

![image](https://cloud.githubusercontent.com/assets/483344/14736285/06d588ee-082b-11e6-8ebc-d5731deb0d37.png)

Sometimes it fails, and if it fails, it's always with:

![image](https://cloud.githubusercontent.com/assets/483344/14736303/2765b246-082b-11e6-9487-8f07df2d1513.png)

But when I rebuild it several times by hitting the same keystrokes, it can actually build fine. This helped:

https://github.com/wkoszek/sensorama-ios/commit/195042c613e09a4c17aa6beb044f6030537f5229

Would be nice to understand why it's happening.
