### ISSUE TITLE
Using local DynamoDB

### ISSUE THREAD

**Issue by hsienchiaolee** [aws/aws-sdk-ios#314]
I am trying to connect to my local DynamoDB instance, but it seems to me that there is currently no way to set a custom endPoint URL for dynamo DB. AWSServiceConfiguration.endpoint is a readonly property, and it does not have an initializer method that allows a custom URL. What else can I do to achieve my goal?

**Comment by yosuke-matsuda** [comment]
Currently, the AWS Mobile SDK for iOS does not support Local DynamoDB library. We'll consider adding the capability to override the endpoint URL in the future.
