### ISSUE TITLE
Exception thrown for the result set with NULL data type

### ISSUE THREAD

**Issue by sreejithsn** [aws/aws-sdk-ios#318]
We have table with map attribute. Some items are inserted with NULL data type as shown below. When queried with AWS iOS SDK mapper( "dynamoDBObjectMapper.query"), exception is thrown. Any workaround for it?

      "currentStatus": {
        "M": {
          "driverId": {
            "S": "0"
          },
          "driverLogin": {
            "NULL": true
          },

Android SDK is not throwing any exception

**Comment by yosuke-matsuda** [comment]
The DynamoDB Object Mapper for iOS currently does not support the `NULL` data type. However, it should handle it more gracefully. Have you specified the attribute in [`+ ignoreAttributes`](https://github.com/aws/aws-sdk-ios/blob/master/AWSDynamoDB/AWSDynamoDBObjectMapper.h#L103)?

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to add more details if you continue seeing the issue. Thanks.
