### ISSUE TITLE
TransferUtility wifi only

### ISSUE THREAD

**Issue by corbt** [aws/aws-sdk-ios#319]
I'm using TransferUtility to upload fairly large video files, and it seems to be working well. However, I'd like for users of my app to be able to disable uploads when connected to cellular data, because it would be easy to blow through their entire data allowance with just a few uploads.

I can check before starting a transfer whether wifi is connected or not, and only initialize the transfer if it is. However, this doesn't help if a user starts an upload while connected to wifi and then moves away from the access point.

iOS has the ability with NSURLSession to limit transfers to not use cellular access. It would be great if this library could either (1) give an option to disable transfers on cellular data or (2) allow the user to pass in a custom `NSURLSessionConfiguration`, that could customize this and other properties.

**Comment by yosuke-matsuda** [comment]
Consolidating to [this thread](https://github.com/aws/aws-sdk-ios/issues/310).
