### ISSUE TITLE
why there is no way to initiate endpoint in AWSServiceConfiguration?

### ISSUE THREAD

**Issue by zhihuitang** [aws/aws-sdk-ios#321]
in AWSServiceConfiguration, there is a init function, we can initiate regionType and credentialsProvider. 
> (instancetype)initWithRegion:(AWSRegionType)regionType credentialsProvider:(id<AWSCredentialsProvider>)credentialsProvider;

But if I want to set endpoint, how should I do? or is it impossible?

> @interface AWSServiceConfiguration : AWSNetworkingConfiguration
> 
> @property (nonatomic, assign, readonly) AWSRegionType regionType;
> @property (nonatomic, strong, readonly) id<AWSCredentialsProvider> credentialsProvider;
> @property (nonatomic, strong, readonly) AWSEndpoint *endpoint;
> @property (nonatomic, readonly) NSString *userAgent;
> 
> + (NSString *)baseUserAgent;
> 
> + (void)addGlobalUserAgentProductToken:(NSString *)productToken;
> 
> - (instancetype)initWithRegion:(AWSRegionType)regionType
>            credentialsProvider:(id<AWSCredentialsProvider>)credentialsProvider;
> 
> - (void)addUserAgentProductToken:(NSString *)productToken;
> 
> + (instancetype)configurationWithRegion:(AWSRegionType)regionType
>                     credentialsProvider:(id<AWSCredentialsProvider>)credentialsProvider __attribute__ ((deprecated("Use '- initWithRegion:credentialsProvider:' instead.")));
> 
> @end

**Comment by zhihuitang** [comment]
finally I managed customized the endpoint like this:
configuration.baseURL = NSURL(string: "xxxx.xxx.xxx")

**Comment by yosuke-matsuda** [comment]
Currently, there is no official support for custom AWS service endpoint. We are working on providing the API for this. Consolidating to [this thread](https://github.com/aws/aws-sdk-ios/issues/303).

**Comment by zhihuitang** [comment]
In Android SDK there is way to customise the endpoint like this:
> authFactory = new ApiClientFactory()
>                 .**endpoint**(AUTH_ENDPOINT)
>                 .credentialsProvider(credentialsProvider)
>                 .region(REGION.getName())
>                 .apiKey(APIKEY);

It seems you guys don't talk each other with Android team ?

**Comment by sabdalla80** [comment]
This can be done easily by changing the AWSConfigurationService.endpoint in the SDK code.

**Comment by zhihuitang** [comment]
@sabdalla80. Yes you are right. But I don't want to touch the SDK code, since the SDK might be upgraded.
