### ISSUE TITLE
Xcode "AWSSESErrorDomain error 4" on email send attempt

### ISSUE THREAD

**Issue by nehloo** [aws/aws-sdk-ios#322]
I'm getting this error message when I attempt to send an email message with AWSSES with Xcode for an iOS app:

`awsSES.sendEmail error: The operation couldn’t be completed. (com.amazonaws.AWSSESErrorDomain error 4.)`

I'm creating the service with AWSCognitoCredentialsProvider, AWSServiceConfiguration and AWSServiceManager. Then I use AWSSESSendEmailRequest, AWSSESMessage, AWSSESContent, AWSSESBody, and finally AWSSES sendEmail in the process. sendEmail's completion block function is returning this AWSTask error mentioned above.

**Comment by yosuke-matsuda** [comment]
The error code 4 is `AWSSESErrorMessageRejected`. You should [enable verbose logging](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html) and see what's causing the error.

**Comment by nehloo** [comment]
That worked and I was able to identify the issue which was a SES configuration. Thanks yosuke-matsuda.
