### ISSUE TITLE
MQTT LWT support for IoT SDK

### ISSUE THREAD

**Issue by anozaki** [aws/aws-sdk-ios#326]
It would be nice if the IoT SDK provided a way to specify LWT.

This would be a really nice feature to have to detect IoT disconnect.

**Comment by bhadrip** [comment]
Hello @anozaki ,

Thanks for bringing the missing feature to our attention. We will add LWT to the SDK as part of our upcoming releases. 

Bhadri

**Comment by minbi** [comment]
Please re-open the issue if this still applies
