### ISSUE TITLE
AWSDynamoDBObjectMapper on iOS set Bool values to 1 instead of true?

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#332]
On iOS9.3 the AWSDynamoDBObjectMapper sets a Bool correctly to true or false in the DynamoDB table. However, running the same code on iOS9.2.1 it sets the same values to an Int of 0 or 1 instead. This breaks the whole db when I try and search for items in there based on these values in a filterExpression.

I'm using Swift and the latest AWS SDK for iOS.

**Comment by yosuke-matsuda** [comment]
Could you share a sample code snippet that we can use to reproduce the issue? Thanks.

**Comment by helloniklas** [comment]
I have this Swift class with a dynamoDBObjectMapper.save method. Everything has been working fine on my phone running iOS9.3 I then started to test with another device running iOS 9.2.1, and the data seemed to save fine But when I then tried to do a query on it didn't come back. I then looked in the dynamoDB table, ad the device running on iOS9.2.1 has saved Bool with a 0 rather than false, and the type has been set to Number rather than Bool on those entries.

I now resorted to just Int of 0 and 1 instead of a Bool, but it's doesn't make for very nice code.

`class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
     var userID: String!
    var updatedAt: String! 
    var createdAt: String!
    var identityID: String!
    var username: String!
    var email: String?
    var emailVerified: Bool = false

    static func dynamoDBTableName() -> String! {
        return "User"
    }

    static func hashKeyAttribute() -> String! {
        return "userID"
    }

    func save(completion: (result: Bool, error: NSError?) -> Void) {
        UIApplication.sharedApplication().networkActivityIndicatorVisible = true
        let dynamoDBObjectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        dynamoDBObjectMapper.save(self).continueWithBlock { (task) -> AnyObject? in
            dispatch_async(dispatch_get_main_queue(), {
                UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                if let _ = task.result {
                    completion(result: true, error: nil)
                }
                else if let error = task.error {
                    print(error.localizedDescription)
                    completion(result: false, error: error)
                }
                else {
                    completion(result: false, error: nil)
                }
            })
            return nil
        }
    }

}`

**Comment by helloniklas** [comment]
I also get problem with a filterExpression on an Int on iOS9.2.1, but works fine on iOS9.3. I wonder if this has to do with Xcode 7.3 not working with your SDK for Swift. A bit worrying though since it will be out next week most likely.

Seems the only way to get this to work across devices is to do a complete scan then deal with filtering afterwards in Swift.

**Comment by yosuke-matsuda** [comment]
For boolean values, you need to use `NSNumber` when you are defining the model class. You can pass `true` and `false` as follows: `NSNumber(bool: true)` and `NSNumber(bool: false)`. This is an inherent limitation of the object mapping library the DynamoDB Object Mapper uses. With the future versions, we'll see how we can improve the experience in Swift. Thanks.

**Comment by helloniklas** [comment]
Ok thanks, odd that it worked fine on iOS9.3, saving Bool as true and false...

**Comment by helloniklas** [comment]
Can I use the swift Int or do I need to use NSNumber as well in the model class?
Also, I have problem with an array of [String]. Does this need to be NSArray ?

**Comment by yosuke-matsuda** [comment]
We recommend `NSNumber` over `Int`. `Array` and `Dictionary` should work just fine.

**Comment by helloniklas** [comment]
So I'm saving an array of strings from nodejs lambda, it appears in the console view as:

{ "asdasdasda", "us-east-1:0c7b8a7e-23e3-436e-9767-df56d923f355" }

Which seems to be a StringSet?

Is that way it won't map to my class with a property:

`var connects: [String]?`

It says:
-[__NSSingleObjectSetI objectAtIndex:]: unrecognized selector sent to instance 0x15592dc80
 *** Caught exception setting key "connects" : -[__NSSingleObjectSetI objectAtIndex:]: unrecognized selector sent to instance 0x15592dc80
 +[NSError awsmtl_modelErrorWithException:]: unrecognized selector sent to class 0x1a1224540

I'm saving from nodes like this,

```
connects: {
          Action: 'PUT',
          Value: {
            SS: connects
          }
```

**Comment by yosuke-matsuda** [comment]
For `SS` (String Set), you need to use `Set<String>`. `Array<String>` is for `L` (List) data type.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to add more details if you continue seeing the issue. Thanks.

**Comment by helloniklas** [comment]
When can we expect full native swift support for AWS sdk? Competition has had it for years.
