### ISSUE TITLE
AWSDynamoDBObjectMapper does not support Global Secondary Indexes?

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#333]
Is it not possible to use the AWSDynamoDBObjectMapper with the iOS SDK to query a secondary global index? I get the error com.amazonaws.AWSDynamoDBErrorDomain error 1 when attempting this.

**Comment by yosuke-matsuda** [comment]
The DynamoDB Object Mapper supports Global Secondary Indexes. You should take a look at this [sample app](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/DynamoDBObjectMapper-Sample).

**Comment by helloniklas** [comment]
Ok, odd then. I can't get it to give me back data, although running it in the web console on that index gives me back data correctly. Could it be because I have a hashKey for this index that is an Int? But then, it does work fine in the web console.

```
        let queryExpression = AWSDynamoDBQueryExpression()
        queryExpression.indexName = "gender-createdAt-index"
        queryExpression.hashKeyAttribute = "gender"
        queryExpression.hashKeyValues = 1
        queryExpression.rangeKeyConditionExpression = "createdAt >= :val"
        queryExpression.expressionAttributeValues = [":val": "0"]
        queryExpression.scanIndexForward = true
        dynamoDBObjectMapper.query(User.self, expression: queryExpression).continueWithBlock { (task) -> AnyObject? in
```

**Comment by yosuke-matsuda** [comment]
Can you share your model class, table schema, and the complete code snippet to reproduce the issue? What's the data type of `createdAt`? Based on the posted code snippet, it is defined as `S` (String).

Also, it seems like you are using some deprecated properties. The latest version of the SDK is 2.3.6. We recommend using the latest version of the SDK.

**Comment by helloniklas** [comment]
createdAt is a String as AWS can't handle native NSDate objects. I'm using the latest SDK 2.3.6, but it's not giving me any warnings about something being deprecated? Which properties would be deprecated? 

I'm trying to get all the objects but sorted by a date. this seems very tricky to do with AWS.

**Comment by yosuke-matsuda** [comment]
Oh, my bad. I thought `rangeKeyConditionExpression` is deprecated in 2.3.6.

If you continue to encountering the issue, please provide the requested information. Thanks.

**Comment by helloniklas** [comment]
Ok, a bit confusing that it's not listed as depreciated in the 2.3.6 docs, sample code, or Xcode, http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSDynamoDBQueryExpression.html

Will get the information over after I tested this a bit more.

Thanks for your help.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to add more details if you continue seeing the issue. Thanks.
