### ISSUE TITLE
Using multiple services in different regions

### ISSUE THREAD

**Issue by iurichiba** [aws/aws-sdk-ios#336]
Hi,

I've encountered a problem using multiple services in my app, each in a different region.

We're using 2 services, ATM: SNS and S3.
The problem is that SNS is hosted at **US-East-1**, and S3 is hosted at **SA-East-1**.

When the app initializes, I configure it with to use USEast1, so that I can register my device on SNS, subscribe and unsubscribe to channels without any problems. But now I'm implementing a feature that requires S3 uploads, and I can't do it because the app's configured to use USEast1. 

I get this error:
```
Message=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., Code=PermanentRedirect
```
If I change the region to SAEast1, it works, but SNS doesn't.

Is there any way I can configure the app to access both regions, one for each service?

Hope you guys can help me!
Thanks!

**Comment by yosuke-matsuda** [comment]
You should use [`+ registerS3WithConfiguration:forKey:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/registerS3WithConfiguration:forKey:) to pass a new `AWSServiceConfiguration` with the new region, then use [`+ S3ForKey:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/S3ForKey:) to retrieve the service client. In this way, you can mix services from multiple regions.

**Comment by iurichiba** [comment]
Oh, I'll try that! Thanks for the answer :smile:

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to add more details if you continue seeing the issue. Thanks.

**Comment by iurichiba** [comment]
It worked! I'm sorry I didn't reply sooner, but thanks!
