### ISSUE TITLE
AWSNetworkingUploadProgressBlock: totalBytesSent > totalBytesExpectedToSend

### ISSUE THREAD

**Issue by zhenyakoval** [aws/aws-sdk-ios#337]
I'm using following code for progress logging of upload request:
```      
  if let uploadRequest = AWSS3TransferManagerUploadRequest() {
            uploadRequest.bucket = ...
            uploadRequest.key = ...
            uploadRequest.body = NSURL(fileURLWithPath: ...)
            uploadRequest.uploadProgress = { [weak self] (bytesSent, totalBytesSent, totalBytesExpectedToSend) in
                  print("bytesSent: \(bytesSent), totalBytesSent: \(totalBytesSent), totalBytesExpectedToSend: \(totalBytesExpectedToSend)")
                 let progress = Float(totalBytesSent) / Float(totalBytesExpectedToSend)
                 ....
            }
        }
    }
```

In some cases (e.g. locking screen) I get next error:
```
AWSiOSSDKv2 [Error] AWSURLSessionManager.m line:260 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost."
```

Uploading continues anyway after unlocking screen, but we have strange byte values in logs:
`bytesSent: 23031, totalBytesSent: 54039172, totalBytesExpectedToSend: 48319969`

`totalBytesSent` is bigger than `totalBytesExpectedToSend`. 
Is it correct behavior?
How can we calculate uploading progress in this case?

**Comment by yosuke-matsuda** [comment]
`AWSS3TransferManager` does not handle transfers when the app is not in the foreground (e.g. When the screen is locked). You can cancel the requests when the app goes foreground and restart the transfers when the app comes back.

Going forward, we focus our development effort on `AWSS3TransferUtility` and plan to phase out `AWSS3TransferManager` support. We recommend starting looking into `AWSS3TransferUtility` and see if it covers your needs. It should handle the transfer better when the app is interrupted.

**Comment by zhenyakoval** [comment]
@yosuke-matsuda, thank you for response
`AWSS3TransferUtility` looks great, is it still in beta?

**Comment by yosuke-matsuda** [comment]
It is still in beta and is possible that we make minor breaking API changes to the transfer utility. However, it is more stable for transferring date to/from the Amazon S3.
