### ISSUE TITLE
Missing AWSS3BucketLocationConstraintAPNortheast2 enum

### ISSUE THREAD

**Issue by dennykim** [aws/aws-sdk-ios#338]
As of SDK Version 2.3.4, `AWSS3BucketLocationConstraint` enum is missing a bucket location constraint for the **Asia Pacific (Seoul)** (`AWSRegionAPNortheast2`) region.

It should be named `AWSS3BucketLocationConstraintAPNortheast2` to maintain the standard naming convention.

**Comment by yosuke-matsuda** [comment]
We will add **Asia Pacific (Seoul)** to `AWSS3BucketLocationConstraint` in the future release. Thanks.

**Comment by karthiksaligrama** [comment]
Fixed with aws sdk for ios version 2.4.2
