### ISSUE TITLE
I'm integrating the Transfer manager into my app and am getting this kind of error when I try to upload a file

### ISSUE THREAD

**Issue by PengsreangSrun** [aws/aws-sdk-ios#342]
AWSiOSSDKv2 [Error] AWSURLResponseSerialization.m line:174 | +[AWSXMLResponseSerializer serializerWithResource:actionName:] | can not find s3-2006-03-01.json file in the project
2014-12-30 17:00:53.047 Station[20733:8184049] AWSiOSSDKv2 [Error] AWSURLRequestSerialization.m line:145 | +[AWSXMLRequestSerializer serializerWithResource:actionName:] | can not find s3-2006-03-01.json file in the project.

All above is from log and I add this framwork by manually not by cocoapod.
Therefore,Can you help me to solve these issues?

**Comment by yosuke-matsuda** [comment]
What version of the SDK are you using? You should try the latest version of the SDK (2.3.6 at this point) because `s3-2006-03-01.json` has been removed from the SDK since version 2.2.0.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to add more details if you continue seeing the issue. Thanks.
