### ISSUE TITLE
AWS SDK without cocoapods?

### ISSUE THREAD

**Issue by shaunbruno** [aws/aws-sdk-ios#345]
Our team is having difficulties getting the app to compile without using cocoapods to install the SDK. 

Is this possible? Or should it be easy? Are we just doing something wrong?

Best Regards

**Comment by yosuke-matsuda** [comment]
[Set Up the SDK for iOS](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html) section of the iOS Developer Guide may help.
