### ISSUE TITLE
How to order a scan results by createdAt

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#346]
So I'm struggling to do what I would have hoped would be a very simple thing. I need to get all items of an object so I'm using a scanExpression. However, I also needs this ordered by a date. Since it's my understanding that a scan might not return all 1000s of items in one go, i.e. I will have to ask for another page, I will need these ordered by a date before I get them. As if I order these myself once I have the items, I might not have all the items available and won't be able to sort them all on the date.

I've tried to set up a secondary index for this with a sort key of my createdAt field. However, it seem doing a scan on that index still doesn't order them by createdAt and that this can only be achieved by a query. But since I need all available items I need to use a scan.

Surely there must be a way to get items in a certain order as otherwise DynamoDB becomes unusable with a large data set.

Any advice on this would be appreciated.

**Comment by fosterzhang** [comment]
@helloniklas your understanding of Scan and Query is correct. DynamoDB doesn't support sorting in a scan operation, which makes senses, as ordering in a full table scan is usually unnecessary. However the query operation supports sorting. A work around (not recommended) is to create a GSI with a constant value hash key and createdAt as range key. Then you can do a query on this GSI with the ordering you want. Beware that this adds cost and limits your table size to 10GB (maximum size of one hash key). How this would help.

**Comment by helloniklas** [comment]
I tried to do that, i.e. I added a value called disabled, I can the use that as the hash key for the secondary index table, and set the hash to 0 (to get all items that has not been disabled). I then add a sort key with the createdAt. I'm then able to view this in the AWS web console, however, running this from the iOS SDK with swift just returns an error 0 or 1 without any further hints. I assume this doesn't work in Swift, or maybe the dynamo object mapper is not supported with this kind of use. I spent a lot time trying to get error go away, but nothing seems to work.

**Comment by helloniklas** [comment]
I do something like this 

```
                queryExpression.indexName = "disabled-createdAt-index"
                queryExpression.hashKeyAttribute = "disabled"
                queryExpression.hashKeyValues = NSNumber(int: 0)
                queryExpression.rangeKeyConditionExpression = "createdAt >= :val" 
                queryExpression.expressionAttributeValues = [":val": "0"]
                queryExpression.scanIndexForward = true
```

**Comment by yosuke-matsuda** [comment]
First, you should enable the  [verbose logging](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html) so that you can see more detailed logs.

Also, can you share the index schema and the table schema? Is `createdAt` a string attribute? In this case, you should not need to set anything for `rangeKeyConditionExpression` and `expressionAttributeValues`.

**Comment by helloniklas** [comment]
@fosterzhang Ok that verbose logging was very helpful. Turns out the IAM role didn't allow access to the secondary index, I assumed giving access to the table would also allow access to the secondary index. So I've updated that IAM role. But it now seems to work... Great!

Is there a way to give IAM access to all secondary indices of a table, or do I have to add these manually for each one?

Also, how concerned should I be about the 10gb limit and cost, I guess if is this is the only way to do this ordering I have no option.

Many thanks for your help.

**Comment by yosuke-matsuda** [comment]
[Allow Access to a Specific Table and All of Its Indexes](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/access-control-identity-based.html#access-policy-examples-for-sdk-cli.example4) has an example policy to allow access of all of its indexes.

[Guidelines for Working with Tables](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForTables.html) should help on how to design your DynamoDB table.

**Comment by vishnu-ts** [comment]
condition = new Condition().withComparisonOperator(
				ComparisonOperator.EQ).withAttributeValueList(
				new AttributeValue().withS(patient_Id));
