### ISSUE TITLE
Is the use of Cognito mandatory with the new version of the SDK

### ISSUE THREAD

**Issue by hatimk** [aws/aws-sdk-ios#348]
Hi,

I am currently encountering a limitation with Cognito which is discussed here: https://github.com/aws/amazon-cognito-ios/issues/12. Even though Cognito is now recognized as a best practice, I still need to directly use Web Identity Federation for my use case.

Nevertheless, the documentation on the subject (like http://aws.amazon.com/articles/4617974389850313) seems outdated and I am not sure that it is still valid given the new SDK version. So my question is: is it possible to use Web Identity Federation without Cognito with the new version of the SDK? And if it is the case, is there any up-to-date documentation I can check?

Thanks a lot,
Hatim

**Comment by behrooziAWS** [comment]
It is still possible to use Web Identity Federation.  There is no documentation specifically for V2, but this is what you use:
https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Authentication/AWSCredentialsProvider.h#L103

**Comment by hatimk** [comment]
Clear enough and it works. Thanks.
