### ISSUE TITLE
How to set Custom endPoint in AWSS3

### ISSUE THREAD

**Issue by sabdalla80** [aws/aws-sdk-ios#349]
In Version 1 AmazonS3Client, it had a way to set a custom endpoint.
I noticed endpoint was a readonly member in AWSS3. 

In JavaScript for intance, we have the following which works:
var ep = new AWS.Endpoint('http://hello.company.com:1310/');
var s3 = new AWS.S3({endpoint: ep});

Can I do the same in AWSS3 iOS?

**Comment by yosuke-matsuda** [comment]
Currently, `AWSS3` does not support it. Merging it to [this thread](https://github.com/aws/aws-sdk-ios/issues/303).

**Comment by vishnuag05** [comment]
hey any progress on this ? I also need to specify custom end point , Please help

**Comment by sabdalla80** [comment]
I changed the code in the sdk. Very minimal trivial change will do the trick.

Get Outlook for iOS




On Tue, May 31, 2016 at 11:42 AM -0700, "vishnuag05" <notifications@github.com> wrote:





hey any progress on this ? I also need to specify custom end point , Please help

---

**Comment by vishnuag05** [comment]
How can I get that @sabdalla80

**Comment by sabdalla80** [comment]
In awsservice src file, look at initwithconfiguration method, it defaults to amazon urls, you need to pass in yours.

Get Outlook for iOS




On Tue, May 31, 2016 at 11:46 AM -0700, "vishnuag05" <notifications@github.com> wrote:





How can I get that @sabdalla80

---

**Comment by vishnuag05** [comment]
hey @sabdalla80  I mean to say where can I get modified code, changes you made?

**Comment by vishnuag05** [comment]
var presignedUrl: AWSTask = AWSTask()
        let expiration = NSDate().dateByAddingTimeInterval(5*60)
        
        
        let credential = AWSStaticCredentialsProvider.init(accessKey: AWS_ACCESS_KEY_ID, secretKey: AWS_SECRET_KEY_ID)
        let configuration = AWSServiceConfiguration.init(region:.Unknown, credentialsProvider: credential)
       // print("%@",configuration.endpoint)
        //let regionTp = AWSRegionType(s)
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration
        let urlBuilder = AWSS3PreSignedURLBuilder.defaultS3PreSignedURLBuilder()
        
        
        let preSignedURLRequest = AWSS3GetPreSignedURLRequest.init()

        preSignedURLRequest.key = "someobject
        preSignedURLRequest.bucket = "sonebucketname"
        preSignedURLRequest.expires = expiration
        preSignedURLRequest.HTTPMethod = .GET
        presignedUrl = urlBuilder.getPreSignedURL(preSignedURLRequest)

**Comment by vishnuag05** [comment]
This is what I am using right now

**Comment by vishnuag05** [comment]
// android example
public static String getPreSignedURL(String url) {
java.util.Date expiration = new java.util.Date();
long msec = expiration.getTime();
msec += 1000 60 5; // 5 minutes
expiration.setTime(msec);

    AWSCredentials myCredentials = new BasicAWSCredentials(
            AppConstants.AWS_ACCESS_KEY_ID, AppConstants.AWS_SECRET_KEY_ID);
    AmazonS3 s3client = new AmazonS3Client(myCredentials);
    s3client.setEndpoint(AppConstants.ENDPOINT_S3);
    GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(
            AppConstants.BUCKET_NAME, url.replace(AppConstants.OBJECT_NAME_FILTER, ""));
    request.setExpiration(expiration);
    URL objectURL = s3client.generatePresignedUrl(request);
    return objectURL.toString();
}

**Comment by vishnuag05** [comment]
in android this works

**Comment by vishnuag05** [comment]
@sabdalla80 Please help me
