### ISSUE TITLE
How to get AWS Temporary Credentials from Cognito

### ISSUE THREAD

**Issue by SunnyGurnani** [aws/aws-sdk-ios#350]
I used Cognito Enhanced Authentication Flow because that's what is properly documented and I am able to get CognitoId from credentialsProvider.identityId.

But credentialsProvider.accessKey, secret and sessionToken is all set to Nil. 

This guide titled **[Retrieving an Amazon Cognito ID and AWS Credentials](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-auth.html)** dosen't actually have any information about retrieving Temporary credentials.

Can you please provide information about how to get AWS Credentials using Cognito?

Following is the screenshot showing credentials provider, you can crearly see that identityId is set but AWS AccessKey, Secret and session is set to null.

<img width="535" alt="screen shot 2016-04-07 at 3 19 37 pm" src="https://cloud.githubusercontent.com/assets/943576/14368731/877dd382-fcd4-11e5-881b-9275946571b4.png">

**Comment by SunnyGurnani** [comment]
It worked fine, it seems like I just had to call refresh after setting the credentials.

**Comment by fosterzhang** [comment]
@SunnyGurnani Correct, credentials won't be retrieved until refresh is called, either manually or automatically.

**Comment by SunnyGurnani** [comment]
@fosterzhang  can you update your documentation because it says no one has to call refresh manually. A simple line like following would be great for the community.

> After calling refresh() you will find the AWS credentials set in the credentialsprovider

This could had saved 20 hours of my time and frustration with AWS.
