### ISSUE TITLE
AWSDynamoDBObjectMapper load:(Class)resultClass by hash does not return nil if object does not exists 

### ISSUE THREAD

**Issue by hryckiel** [aws/aws-sdk-ios#352]
Hi,

Seems there is a bug in the method:

- (AWSTask *)load:(Class)resultClass
         hashKey:(id)hashKey
        rangeKey:(id)rangeKey

According to the documentation AWSTask .result  should return null if the object does not exists in the DynamoDB but seems it do return an object instead of null but with default property values set in the mapping class and for strings it returned "<null>"

**Comment by yosuke-matsuda** [comment]
We will address it in the next release. Thanks.

**Comment by helloniklas** [comment]
I got caught out of this as well, had to check properties to see if it was a valid object or not.

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.4.0, which addresses the issue. Thanks.
