### ISSUE TITLE
Using AWSLambdaInvoker to get mapped model objects back from nodejs

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#354]
So, If I have a lambda function written in nodes that does some queries on dynmodb. How can I return these objects mapped to a Swift object through the AWSLambdaInvoker, similar to how when I do a jury from the iOS SDK I get mapped objects back.

Or do I have to manually parse the json and create those objects?

**Comment by yosuke-matsuda** [comment]
`AWSLambdaInvoker` does not map JSON to an object. You need to map it for yourself or use any third party libraries to do so.

**Comment by helloniklas** [comment]
Ok, so if I map these manually to a model object that is dynamo object subclass, I can then save them back as normal to dynamodb though the model mapper? And they will save to the correct object based on the hash key I guess?

Is this automatic mapping of native object something that will be added? Most other systems I worked with like Parse did this for you, when using server side cloud code and sending data back.

**Comment by yosuke-matsuda** [comment]
It totally depends on how you map the object, but you should be able to map it to a subclass of `AWSDynamoDBObjectModel`.
