### ISSUE TITLE
Generated iOS SDK Client uses the deprecated class method 'signerWithCredentialsProvider:endpoint:'

### ISSUE THREAD

**Issue by rainypixels** [aws/aws-sdk-ios#360]
We installed all the relevant frameworks (Core, Cognito, APIGateway) successfully through Carthage in a fresh iOS9 project. Build>Run worked great. Then we generated an SDK from API Gateway and imported it into the project, and that caused the following error: 

```
/ProjectPath/DIGClient.m:120:62: No known class method for selector 'signerWithCredentialsProvider:endpoint:'
```

The code that gives the error:
```
AWSSignatureV4Signer *signer = [AWSSignatureV4Signer signerWithCredentialsProvider:_configuration.credentialsProvider endpoint:_configuration.endpoint];
```

The fix that I made (based on a warning and deprecation hint that I had from a prototype I'd built a few months ago using a similar setup):
```
AWSSignatureV4Signer *signer = [[AWSSignatureV4Signer alloc] initWithCredentialsProvider:_configuration.credentialsProvider endpoint:_configuration.endpoint];
```

I suspect the auto-generated SDK has some deprecated code (hopefully this is the only stale code :-D), and you may want to fix that. Happy to provide more info if you need it.

**Comment by yosuke-matsuda** [comment]
We will see how we can address the issue with the API Gateway code generation. Thanks.

**Comment by GreyEcologist** [comment]
Hey, any update on that, I'm running into the same issue.

**Comment by sridharrajagopal** [comment]
Appreciate any updates. I ran into this issue too. Thanks rainypixels for the workaround!

**Comment by karthiksaligrama** [comment]
This issue is fixed. Please download the api gateway sdk again from the api gateway console to get the updated sdk
