### ISSUE TITLE
Using Cognito Identity User Pools instead of custom identity provider, beta?

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#361]
Following the change to the custom user identity APIs. I'm thinking I might be better of to just start using the new Cognito Identity User Pools that provides this out of the box. The APIs are there in SDK 2.4.0. Things like  pool.signUp:password:userAttributes:validationData.

However, this is listed as being in Beta in your docs? Although 2.4.0 is not listed as being Beta?

What does this Beta really mean? Can I start using this in app that is meant to ship in a months time? Or will this not work at all in Production?

**Comment by patvyas** [comment]
The public beta of Cognito User Pools is intended to allow developers to start building their apps as we gather feedback and enhance the service. We will strive to maintain compatibility, but we may make changes during the beta period based on customer feedback. We are interested in your requirements and would like to discuss your specific plans. You could reach us by developer support or through sending us private message on forums https://forums.aws.amazon.com/forum.jspa?forumID=173

**Comment by behrooziAWS** [comment]
Closing, let us know if you need further clarification.
