### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by FranDepascuali** [aws/aws-sdk-ios#363]
We had the release 2.4.0 as dependency, and we were using
```objective-c
typedef void (^AWSS3TransferUtilityDownloadProgressBlock) (AWSS3TransferUtilityDownloadTask *task,
int64_t bytesWritten,
int64_t totalBytesWritten,
int64_t totalBytesExpectedToWrite); 
```
When updating to 2.4.1, it seems to be changed to 
```objective-c
typedef void (^AWSS3TransferUtilityProgressBlock) (AWSS3TransferUtilityTask *task, NSProgress *progress);
```
We were relying on the `AWSS3TransferUtilityProgressBlock`, so our code didn't compile with `2.4.1`. Please use [Semantic Versioning](http://semver.org/); This should have been a mayor change because you made incompatible API changes.

**Comment by yosuke-matsuda** [comment]
`AWSS3TransferUtility` was a beta labeled component. If you need to depend on a beta component, you should fix the version number for the dependency. More on our current versioning conventions can be found [here](https://github.com/aws/aws-sdk-ios/issues/357#issuecomment-215284491). Merging to the original thread.
