### ISSUE TITLE
IoT MQTTClient as a Dependency

### ISSUE THREAD

**Issue by gaston23** [aws/aws-sdk-ios#365]
Can we depend on https://github.com/ckrey/MQTT-Client-Framework ? instead of the internal hardcoded lib,

**Comment by rongaws** [comment]
For the MQTT part, it's possible. Much of the MQTT implementation are wrapped in https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/Internal/AWSIoTMQTTClient.h, so replacing the existing MQTT implementation with a different one is basically to rewrite this interface layer.

Other AWS service specific APIs in the same SDK, such as those defined in https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/AWSIoTService.h can't be replaced as they are not MQTT specific. 

May I ask what the main reasons are for replacing the existing MQTT implementation? Thanks.

-Rong
