### ISSUE TITLE
Subscribe topic

### ISSUE THREAD

**Issue by brunoudi** [aws/aws-sdk-ios#366]
I'm subscribing to a topic with the code below:

    iotDataManager.subscribeToTopic("device1/status/#", qos: 0, messageCallback: {
        (payload) ->Void in

        let stringValue = NSString(data: payload, encoding: NSUTF8StringEncoding)!

        print("received: \(stringValue)")
        dispatch_async(dispatch_get_main_queue()) {
            //some code here
        }
    } )
the problem is that when i get a message, i don't know the exactly topic which came from... example "device1/status/on" or "device1/status/value". In the example i'm getting only the payload.

Is there a way to get the full topic and the payload?

**Comment by rongaws** [comment]
Thanks for bringing this use case to our attention. Unfortunately, in the current version SDK, the actual topic is not passed back to the callback function. This is where the callback is invoked upon new message arrival - https://github.com/aws/aws-sdk-ios/blob/1ec2fc8ceca0e3314b86979e6efb636e7501e081/AWSIoT/Internal/AWSIoTMQTTClient.m#L640

We are aware of this limitation and are looking into ways to improve it. In the meantime, a quick workaround would be adding a message identifier in the payload, or if you are comfortable with modifying the code, you could try adding the topic parameter into the callback function, and you will also need to modify the callback function signature AWSIoTMQTTNewMessageBlock defined in AWSIoTDataManager.h and probably few other places.

Please let me know if there's anything else we could help. Thanks. 

-Rong

**Comment by gkwicker** [comment]
Hi @brunoudi, here's a patch you could try until an updated version of the SDK is available.  Note that the changes in the upcoming version of the SDK may be a little different than these.  Let us know if there's anything else we can do, and thanks for using AWS IoT.

```
diff --git a/AWSIoT/AWSIoTDataManager.h b/AWSIoT/AWSIoTDataManager.h
index 1e05859..6a936d9 100644
--- a/AWSIoT/AWSIoTDataManager.h
+++ b/AWSIoT/AWSIoTDataManager.h
@@ -31,7 +31,7 @@ typedef NS_ENUM(NSInteger, AWSIoTMQTTQoS) {
     AWSIoTMQTTQoSMessageDeliveryAttemptedAtLeastOnce = 1
 };
 
-typedef void(^AWSIoTMQTTNewMessageBlock)(NSData *data);
+typedef void(^AWSIoTMQTTNewMessageBlock)(NSString *topic, NSData *data);
 
 #pragma mark - AWSIoTMQTTLastWillAndTestament
 
diff --git a/AWSIoT/Internal/AWSIoTMQTTClient.m b/AWSIoT/Internal/AWSIoTMQTTClient.m
index 5d45be6..74dbb3e 100644
--- a/AWSIoT/Internal/AWSIoTMQTTClient.m
+++ b/AWSIoT/Internal/AWSIoTMQTTClient.m
@@ -637,7 +637,7 @@ static AWSIoTMQTTClient *_defaultMQTTClient = nil;
         if (topicMatch) {
             AWSIoTMQTTTopicModel *topicModel = [self.topicListeners objectForKey:topicKey];
             if (topicModel) {
-                topicModel.callback(data);
+                topicModel.callback(topic, data);
             }
         }
     }
```

**Comment by brunoudi** [comment]
thanks @rongaws and @gkwicker for the answers... i made the workaround as suggested and it is working as expected for now.
