### ISSUE TITLE
currentUser method in AWSCognitoIdentityUserPool still returns username after signOut is called on user?

### ISSUE THREAD

**Issue by wz366** [aws/aws-sdk-ios#369]
Should `currentUser` method return the current user who is **logged in**? I called `signOut` on an AWSCognitoIdentityUser object and still got the username when I called `currentUser` on AWSCognitoIdentityUserPool.

**Comment by jbailey2010** [comment]
Not exactly. It'll give the last logged in user. On signOut, the tokens for that user are cleared, so it's not an actionable entity.
