### ISSUE TITLE
Can AWSCognitoIdentityUserPool tell me if user has logged in?

### ISSUE THREAD

**Issue by wz366** [aws/aws-sdk-ios#370]
I am using Cognito Identity User Pool as one of my login providers in my app. Is there a `isLoggedIn` equivalent method in AWSCognitoIdentityUserPool to tell me if user is logged in with User Pool? So I can present a view to the user to ask for username and password if user is not logged in.

**Comment by jbailey2010** [comment]
If you call getSession, one of two things happens depending on if the user is logged in. If they are, it will give tokens back (either from the key chain or a call to refreshTokens). If not, it will invoke interactive authentication. That could be used as a gate to that view. Does that flow work for what you're trying to do? If not, could you provide a bit more detail on why/what you're aiming for?

you just call getSession and if they aren’t logged in, it will invoke interactive auth
otherwise it will return valid tokens, either from the keychain or via a call to refreshTokens

**Comment by wz366** [comment]
I want to have control when to present a login view. My user can be logged in through Facebook or Google and I don't want to be forced to present a login view if user is not logged in through User Pool.

**Comment by jbailey2010** [comment]
Understood. That's a totally valid use case, we'll prioritize exposing a way to take care of that and will update here once we have.

**Comment by wz366** [comment]
Thanks, I'll wait for the good news.

**Comment by cclogg** [comment]
> If you call getSession, one of two things happens depending on if the user is logged in. If they are, it will give tokens back (either from the key chain or a call to refreshTokens). If not, it will invoke interactive authentication. That could be used as a gate to that view.

Hey thanks for responding, this is good info! So would one typically use [pool getUser], and then do [[user getSession] continueWithBlock...] ? If the task succeeds, then the user is 'signed in', but if it errors, is this when the pool's delegate is necessary? ie:
`-(void) getPasswordAuthenticationDetails:(AWSCognitoIdentityPasswordAuthenticationInput *) authenticationInput passwordAuthenticationDetails:  (AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails*>*) passwordAuthenticationDetails`
Or what is typically done if the 'getSession' method errors?

**Comment by behrooziAWS** [comment]
I've added a readonly property on CognitoIdentityUser called signedIn to help with this in 2.4.2.  If you call[ [userPool getCurrentUser] ](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityUserPool.html#//api/name/currentUser )you should be able to check that [property](https://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityUser.html#//api/name/signedIn).

**Comment by reaganwood1** [comment]
Hey all, I just wanted to let you know that the isSignedIn attribute is slow to set for the current logged in user. @behrooziAWS 

Preface: I log in, dismiss the view ondidcompletestepwitherror, then the following set of code runs in my vc presented:

`func isCustomerLoggedIn () -> Bool {
        let isCustomerLoggedIn = AppDelegate.defaultUserPool().currentUser()?.isSignedIn
        
        if let isCustomerLoggedIn = isCustomerLoggedIn, isCustomerLoggedIn == true {
            return true
        } else {
            return false
        }
    }`

This will return false even after a successful login. However, if I add a 1 second sleep, the method works successfully under the same conditions. Hope this helps you.

**Comment by ali-mehmood-10p** [comment]
@jbailey2010,  any update on this or we still need implement other workaround?

**Comment by afanaian** [comment]
> Hey all, I just wanted to let you know that the isSignedIn attribute is slow to set for the current logged in user. @behrooziAWS
> 
> Preface: I log in, dismiss the view ondidcompletestepwitherror, then the following set of code runs in my vc presented:
> 
> ```
> func isCustomerLoggedIn () -> Bool {
>         let isCustomerLoggedIn = AppDelegate.defaultUserPool().currentUser()?.isSignedIn
>         
>         if let isCustomerLoggedIn = isCustomerLoggedIn, isCustomerLoggedIn == true {
>             return true
>         } else {
>             return false
>         }
>  }
> ```
> This will return false even after a successful login. However, if I add a 1 second sleep, the method works successfully under the same conditions. Hope this helps you. This isn't an ideal way for me to do things (adding the sleep), but there doesn't seem to be a way around it.

Thanks for this. Working on this SDK has not been pleasant.
