### ISSUE TITLE
How to supply a AWSS3TransferUtilityProgressBlock in Swift

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#372]
The docs seem to be missing the definition of the AWSS3TransferUtilityProgressBlock, and the iOS Objcetive-c guide examples contain what seems to be old API, ie. expression.uploadProgress does not exist any more, but expression.progressBlock exists. But, it's not clear how I can construct this in order to track progress.

**Comment by helloniklas** [comment]
Actually, wasn't that hard

```
            let expression = AWSS3TransferUtilityUploadExpression()
            expression.progressBlock = { (task: AWSS3TransferUtilityTask, progress: NSProgress) in
                print(progress.fractionCompleted)
            }
```

**Comment by Bhat123** [comment]
let expression = AWSS3TransferUtilityUploadExpression()
        let progressBlock: AWSS3TransferUtilityProgressBlock?

        progressBlock = {(task, progress) in
            dispatch_async(dispatch_get_main_queue(), {
                print("Progress: \(Float(progress.fractionCompleted))")
            })
        }
        expression.progressBlock = progressBlock
