### ISSUE TITLE
'AWSCore/AWSCore.h' file not found with Xcode Version 7.3.1 (7D1014)

### ISSUE THREAD

**Issue by jimmyshiau** [aws/aws-sdk-ios#375]
After I upgrade to  Xcode Version 7.3.1 (7D1014)
I did `pod update`
```
Downloading dependencies
Using AWSCore (2.4.1)
Using AWSS3 (2.4.1)
```
![screen shot 2016-05-11 at 5 09 32 pm](https://cloud.githubusercontent.com/assets/1056469/15175925/34a3face-179b-11e6-9914-6687c0b2754f.png)

Build will fail

**Comment by tfonfara** [comment]
I have the same problem after upgrading to cocoapods 1.0.0 final version.
To me it looks like this line is missing in the podspec file:
`s.public_header_files = 'AWSCore/*.h', 'AWSCore/**/*.h'`
This may also relate to all the other podspecs.

**Comment by k06a** [comment]
@tfonfara works for me with version `2.3.5`

**Comment by tfonfara** [comment]
@k06a even the downgrade doesn't solve the problem for me... maybe my project contains wrong configurations. Two questions: do you have any header files inside the Pods/Headers directory? What directories are included in your Build Settings > Header Search Paths config? My config only includes subdirectories of Pods/Headers (which is actually empty)

**Comment by k06a** [comment]
@tfonfara I am only using AWSMobileAnalytics:
```
pod 'AWSMobileAnalytics', '2.3.5'
```

```
$ ls Pods/Headers/Public/AWSCore/
AWSBolts.h							AWSGZIP.h							AWSSignature.h
AWSBoltsVersion.h						AWSIdentityProvider.h						AWSSynchronizedMutableDictionary.h
AWSCancellationToken.h						AWSLogging.h							AWSTMCache.h
AWSCancellationTokenRegistration.h				AWSMTLJSONAdapter.h						AWSTMCacheBackgroundTaskManager.h
AWSCancellationTokenSource.h					AWSMTLManagedObjectAdapter.h					AWSTMDiskCache.h
AWSCategory.h							AWSMTLModel+NSCoding.h						AWSTMMemoryCache.h
AWSClientContext.h						AWSMTLModel.h							AWSTask.h
AWSCognitoIdentity.h						AWSMTLReflection.h						AWSTaskCompletionSource.h
AWSCognitoIdentityModel.h					AWSMTLValueTransformer.h					AWSUICKeyChainStore.h
AWSCognitoIdentityResources.h					AWSMantle.h							AWSURLRequestRetryHandler.h
AWSCognitoIdentityService.h					AWSModel.h							AWSURLRequestSerialization.h
AWSCore.h							AWSNetworking.h							AWSURLResponseSerialization.h
AWSCredentialsProvider.h					AWSReachability.h						AWSURLSessionManager.h
AWSExecutor.h							AWSSTS.h							AWSValidation.h
AWSFMDB.h							AWSSTSModel.h							NSArray+AWSMTLManipulationAdditions.h
AWSFMDatabase.h							AWSSTSResources.h						NSDictionary+AWSMTLManipulationAdditions.h
AWSFMDatabaseAdditions.h					AWSSTSService.h							NSError+AWSMTLModelException.h
AWSFMDatabasePool.h						AWSSerialization.h						NSObject+AWSMTLComparisonAdditions.h
AWSFMDatabaseQueue.h						AWSService.h							NSValueTransformer+AWSMTLInversionAdditions.h
AWSFMResultSet.h						AWSServiceEnum.h						NSValueTransformer+AWSMTLPredefinedTransformerAdditions.h
```

Header search paths contains a lot:
<img width="606" alt="2016-05-11 15 49 22" src="https://cloud.githubusercontent.com/assets/702124/15181484/a69cc4b0-1798-11e6-8eac-5eb55c48b9a1.png">

**Comment by tfonfara** [comment]
@k06a I'm also using AWSMobileAnalytics, but my Pods/Headers directory is empty. Can you confirm that `pod --version` returns 1.0.0? In my git diff I can see, that all the headers were removed with the 1.0 update.

**Comment by k06a** [comment]
@tfonfara sure:
```
$ pod --version
1.0.0
```

**Comment by yosuke-matsuda** [comment]
When having an issue with CocoaPods 1.0.0, there are a few things you can try.

1. Remove `Podfile.lock` and `Pods/` and reinstall pods using `pod install`.
1. Starting with 1.0.0, `target` is required. Make sure you have `target` defined in your `Podfile`.
1. Check your `Podfile` and see if you have `use_frameworks!` in it. Here is how you should import `AWSCore` depending on the language and the flag:

Swift - `use_frameworks!` is required

    import AWSCore

Objective-C - with `use_frameworks!`

    @import AWSCore;

or

    #import <AWSCore/AWSCore.h>

Objective-C - without `use_frameworks!`

    #import <AWSCore/AWSCore.h>

**Comment by tfonfara** [comment]
I tried all those things, unfortunately without success. I also tried to `pod deintegrate` and install again. I get the same error as shown in the first post, first in my bridging header ('AWSDynamoDB/AWSDynamoDB.h' file not found), and if I comment that out I get a similar error in the AWSMobileAnalytics.h header ('AWSCore/AWSCore.h' file not found). If I use same podfile with 0.39.0 everything works fine. Installed AWS version numbers are 2.4.1.

![aws](https://cloud.githubusercontent.com/assets/728683/15207524/0a5a1c76-1827-11e6-8e09-dd121fdc653f.png)

**Comment by k06a** [comment]
@tfonfara updated to version 2.4.1 - all works fine.

**Comment by yosuke-matsuda** [comment]
[Our sample apps](https://github.com/awslabs/aws-sdk-ios-samples) are updated to use CocoaPods 1.0.0. You should take a look at them. If you continue encountering the issue, please share the detailed steps to reproduce it. Thanks.

**Comment by tfonfara** [comment]
Update: seems that the problem was in DerivedData/Build/Intermediates... I just removed the products folder so far (clean didn't work out), after deleting the intermediates folder as well the problem seems to be solved.

**Comment by k06a** [comment]
@tfonfara you can also avoid this problem by commenting `use_frameworks!` line in `Podfile`

**Comment by barrettj** [comment]
@tfonfara the trick of manually deleting the folder was what worked for me as well, doing a clean did nothing

**Comment by k06a** [comment]
@tfonfara look at my comment in this thread: https://github.com/CocoaPods/CocoaPods/issues/4605

**Comment by zfisher323** [comment]
It looks like AWSCore 2.4.8 broke this again? Everything was working fine with Cocoapods 1.0.1 and AWS 2.4.7 but then I updated to 2.4.8 and I'm now getting "'AWSURLRequestRetryHandler.h" file not found" followed by "Could not build Objective-C module 'AWSS3" - I even downloaded the S3TransferUtilitySampleSwift directly from github and receive the same error messages. Anyone else seeing this issue crop up in 2.4.8?
![screen shot 2016-09-16 at 1 03 50 pm](https://cloud.githubusercontent.com/assets/1075492/18594496/686d0f76-7c0e-11e6-85ae-111b476771e2.png)

**Comment by agusguerra10** [comment]
Same thing happening here

**Comment by matthijsotterloo** [comment]
Yes, please solve this a.s.a.p. Having the same issue.

**Comment by pratap511** [comment]
hi 
   it's working to me 

https://github.com/aws/aws-sdk-ios/pull/462

-#import "AWSURLRequestRetryHandler.h"
+#import "AWSCore/AWSURLRequestRetryHandler.h"

**Comment by vsouza** [comment]
Removing folder `~/Library/Developer/Xcode/DerivedData` works for me 😄

**Comment by iwllyu** [comment]
I was having this problem. You can do Product -> (hold option key) -> Clean Build Folder

or shortcut Option + Shift + Command + K to clean the build folder (not just clean)

**Comment by tywoodpav** [comment]
I cannot get the project to build following the steps in the guide. 

It says `#import <AWSCore/AWSCore.h>` is not found. 

If I expand Libraries > Core.xcodeproj > Frameworks, AWSCore.framework is there. Expanding it shows nothing (not sure if that is normal). 

I set the Framework Search Paths to `$(SRCROOT)/../node_modules/aws-sdk-react-native-core/ios/Frameworks` in the project build settings. Opening that folder shows AWSCore.framework with Modules and Versions inside it. 

Ive also got an AWSCore.framework file (it has the framework icon) directly under Project in XCode. Expanding it shows nothing (again not sure if that is normal).

https://i.imgur.com/6D5Awwh.png

**Comment by guptatarun84** [comment]
Use the `$(inherited)` flag for FRAMEWORK_SEARCH_PATHS and OTHER_LDFLAGS in both Debug and Release. Somehow pods can't able to add the dependency by itself.
