### ISSUE TITLE
Cancellation support in API Gateway

### ISSUE THREAD

**Issue by freak4pc** [aws/aws-sdk-ios#376]
I've digged through the docs and Headers etc ... Can't find any feasible way of disposing a AWSTask after I start executing. 

Is there any best-practice / method for doing this ?

**Comment by yosuke-matsuda** [comment]
`AWSRequest`, a parent of most of the request objects, has [`- cancel`](https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Networking/AWSNetworking.h#L194). You can use it to cancel the request.

**Comment by freak4pc** [comment]
Hey @yosuke-matsuda , thanks for your comment.

AWSTask specifically [has no such method](https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Bolts/AWSTask.h). 

There are some methods containing a `cancellationToken` parameter, but couldn't really understand the context of those.

**Comment by yosuke-matsuda** [comment]
You need to call `- cancel` on the request, not the task object.

**Comment by freak4pc** [comment]
Some methods in the AWS SDK return a AWSTask. And there's no way to access it's request directly that I can see, meaning no way to cancel it directly ... unless I'm missing something?

**Comment by yosuke-matsuda** [comment]
Which method do you want to cancel?

**Comment by freak4pc** [comment]
For example, APIGateway has a invokeHTTPRequest method that returns a AWSTask. I would like to cancel this after firing and don't have access to the NSURLRequest, as it's created within the method.

**Comment by yosuke-matsuda** [comment]
Currently, the SDK generated by Amazon API Gateway does not support cancellation. We will share this as a feature request to the API Gateway team. Thanks.

**Comment by jondwillis** [comment]
Any updates on this?
