### ISSUE TITLE
AWSCognitoIdentityUser getSession fails when device/simulator language differ than english 

### ISSUE THREAD

**Issue by nuinisk** [aws/aws-sdk-ios#377]
[Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"__type":"NotAuthorizedException","message":"Incorrect username or password."}

see also:
https://forums.aws.amazon.com/thread.jspa?threadID=230694

**Comment by chetanme** [comment]
Hello, we found the bug and will be releasing the fix with our next SDK release. Thank you for reporting.

**Comment by behrooziAWS** [comment]
This was resolved in 2.4.2.
