### ISSUE TITLE
Infinite loop after submitAllRecords on AccessDeniedException

### ISSUE THREAD

**Issue by FrankSalad** [aws/aws-sdk-ios#379]
I've been testing Kinesis using the iOS client library. I haven't enabled access to my Kinesis streams for my Cognito users, and I was just testing whether the forbidden error gets handled and propagated properly to my client code. Using the basic example in the tutorial, I run this code:

```
  NSString *serialized = @"my test data";
  
  NSData *yourData = [serialized dataUsingEncoding:NSUTF8StringEncoding];
  AWSKinesisRecorder *kinesisRecorder = [AWSKinesisRecorder defaultKinesisRecorder];
  AWSTask* localSave = [kinesisRecorder saveRecord:yourData streamName:streamName];
  
  [[localSave continueWithSuccessBlock:^id _Nullable(AWSTask * _Nonnull task) {
    return [kinesisRecorder submitAllRecords];
  }] continueWithBlock:^id _Nullable(AWSTask * _Nonnull task) {
    if (task.error) {
      NSLog(@"Error: [%@]", task.error);
    }
    return nil;
  }];
```

I expect my client to eventually hit that task.error block, but instead my console is continuously spammed with:
```
... AWSiOSSDKv2 [Error] AWSKinesisRecorder.m line:147 | __109-[AWSKinesisRecorderHelper submitRecordsForStream:records:partitionKeys:putPartitionKeys:retryPartitionKeys:]_block_invoke | Error: [Error Domain=com.amazonaws.AWSKinesisErrorDomain Code=0 "(null)" UserInfo={__type=AccessDeniedException, Message=User: arn:aws:sts::... is not authorized to perform: kinesis:PutRecords on resource: arn:aws:kinesis:...}]
```

I've updated to the latest version of the library on cocoapods (2.4.1)

**Comment by yosuke-matsuda** [comment]
The error log did not come from the 2.4.1. You see the same behavior with 2.4.1, right? Also, can you confirm it infinitely retries, or each request is retried 3 times (by default) and stops?

**Comment by FrankSalad** [comment]
@yosuke-matsuda you're right, I did a clean rebuild and [now I'm having a different issue](https://github.com/aws/aws-sdk-ios/issues/385) that's preventing me from even getting to that point.

**Comment by yosuke-matsuda** [comment]
Please feel free to update the thread if this continues to be an issue. Thanks.

**Comment by joseandro** [comment]
I am getting a similar problem, my console gets continuously hammered with a similar error message when the user goes offline in the middle of a streaming. Can stop the whole batch execution when no internet connection is available?
