### ISSUE TITLE
Only phone_number attribute is currently supported as a MFA option.

### ISSUE THREAD

**Issue by evankyle** [aws/aws-sdk-ios#382]
I have a MFA via email requirement and need to know if this is something I have missconfigured or when the feature will be available.
```objc
AWSCognitoIdentityUserSettings *settings = [AWSCognitoIdentityUserSettings new];
AWSCognitoIdentityUserMFAOption *mfaOptions = [AWSCognitoIdentityUserMFAOption new];
mfaOptions.attributeName = @"email";
mfaOptions.deliveryMedium = AWSCognitoIdentityProviderDeliveryMediumTypeEmail;
settings.mfaOptions = @[mfaOptions];
return [cognitoUser setUserSettings:settings]; 
```
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=10 "(null)" UserInfo={__type=InvalidParameterException, message=Only phone_number attribute is currently supported as a MFA option.}

**Comment by chetanme** [comment]
We currently only support SMS MFA. We will take this as a feature request and add it to our list. Thanks for bringing this up.

**Comment by jbailey2010** [comment]
Hi,

Thanks for the suggestion, we've made a note of it for prioritization in future releases. Once the service has been updated, the client side support will be updated to stay in sync.

**Comment by carlhunterroach** [comment]
As of January 2018, MFA is still only SMS MFA.

**Comment by MehdizadeMilad** [comment]
As of September 2023, MFA is still only SMS MFA.
