### ISSUE TITLE
Disabled User + forgotPassword creates unexpected "Username/client id combination not found." 

### ISSUE THREAD

**Issue by evankyle** [aws/aws-sdk-ios#384]
Disable a user in the User Pool web console and...
```objc
[[cognitoUser forgotPassword] 
  continueWithBlock:^id _Nullable(AWSTask * _Nonnull task) 
  { AWSLogDebug(@"%@",task.error);
    return nil;  
  }
]; 
```
Returns
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=13 "(null)" UserInfo={__type=ResourceNotFoundException, message=Username/client id combination not found.}

I would expect something more like a user disabled message in this case.

**Comment by chetanme** [comment]
This is intentionally thrown as a a generic error instead of a specif type. Returning an error that user exists and is disabled essentially means that without any valid credentials we are telling the caller that user exists and is in some state. Some attacker who get holds of a user pool id and client id/secret can call forget password, or any other unauthenticated, API to enumerate users which exists in the system. This was the security concern which made us return a generic error.

**Comment by evankyle** [comment]
One can already "enumerate" via.
```objc
[self.pool signUp:user password:pw userAttributes:@[emailAtt] validationData:nil]; 
if([task.error.userInfo[@"__type"] isEqualToString:@"UsernameExistsException"])
```
Trying a reset hack to a "disabled account" would be pointless other then finding out who is using a system which the signup call already provides.

This is just forcing devs to make two calls first to signup then to forgot password to see if an account has been disabled. Users that are disabled often need to know. It would be nice to allow setting a reason at the time of disabling the user that gets returned to them.

**Use case:**
- User **bob101** is a bad boy.
- Admin disables account **bob1001** (the wrong user)
- User **bob1001** trys to login and miss types his password.
- **bob1001** thinks he forgot his password and trys a reset.
- User not found error is displayed.
- **bob1001** is in panic & quickly calling support.

**Comment by chetanme** [comment]
We have heard similar complaint from other customers and we are considering to change the service behavior. Check the discussion on [this post](https://github.com/aws/aws-sdk-ios/issues/380#issuecomment-219664265), the requirement here is very similar to what you are asking for except for the flow.

Making two calls to get the state is not an ideal situation and we would definitely work on a solution for this. We will keep this thread updated. Thank you.

**Comment by jbailey2010** [comment]
Hi,

We appreciate mentioning it, and have prioritized it accordingly. Once we have made the service change, we'll update the client side support appropriately.
