### ISSUE TITLE
Memory leak in AWSS3ChunkedEncodingInputStream

### ISSUE THREAD

**Issue by rgurzhiy** [aws/aws-sdk-ios#387]
I've designed a simple application that uploads file by button click

**AppDelegate.m**
```
#import "AppDelegate.h"
#import <AWSS3/AWSS3.h>

@interface AppDelegate ()
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    id<AWSCredentialsProvider> credentialsProvider = [[AWSStaticCredentialsProvider alloc] initWithAccessKey:@"<ACCESS-KEY>"
                                                                                                   secretKey:@"SECRET_KEY"];
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionEUCentral1 credentialsProvider:credentialsProvider];
    [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;
    return YES;
}

@end
```

**ViewController.m**
```
#import "ViewController.h"
#import <AWSS3/AWSS3.h>

@interface ViewController ()
@end

@implementation ViewController

- (IBAction)test:(id)sender {
    AWSS3TransferManagerUploadRequest *request = [AWSS3TransferManagerUploadRequest new];
    request.bucket = @"<BUCKET>";
    request.key = @"test.txt";
    request.body = [[NSBundle mainBundle] URLForResource:@"test" withExtension:@"txt"];
    
    [[[AWSS3TransferManager defaultS3TransferManager] upload:request] waitUntilFinished];
}

@end
```

When I profile it in Instruments for memory usage I get the following:
![screen shot 2016-05-17 at 8 41 19 pm](https://cloud.githubusercontent.com/assets/16662707/15322601/632f7006-1c70-11e6-9c98-4e946b89330c.png)
![screen shot 2016-05-17 at 8 45 23 pm](https://cloud.githubusercontent.com/assets/16662707/15322602/65955568-1c70-11e6-800c-675fdb08fc29.png)
![screen shot 2016-05-17 at 8 45 40 pm](https://cloud.githubusercontent.com/assets/16662707/15322607/6904835e-1c70-11e6-9f3f-d6e70d3e7c1c.png)

The leak is being detected every time I run `- (IBAction)test:(id)sender` method.

**Comment by yosuke-matsuda** [comment]
Do you see the same leak when you remove `- waitUntilFinished`? Looks like `retain` and `release` are matching within `AWSCore`.

In any case, we recommend using `AWSS3TransferUtility` over `AWSS3TransferManager`. Since `AWSS3TransferUtility` does not use `AWSS3ChunkedEncodingInputStream`, you should not see this issue.

**Comment by rgurzhiy** [comment]
Same with `- waitUntilFinished` removed.
Yes `retain` and `release` are matching within `AWSCore`. As far as I understand from debugging and profiling, `AWSS3ChunkedEncodingInputStream` is a wrapper for default `NSInputStream` retrieved from `NSMutableURLRequest `. Leaked `CFStreamDelegate` is being created in `CFReadStreamSetClient` and retained in `HTTPNetConnection`. Then it is being passed to `AWSS3ChunkedEncodingInputStream`'s `- setDelegate:` method. Without wrapper default `NSInputStream` from `NSMutableURLRequest` releases it somehow. So, the problem might be in implementation. 
Anyway, the issue itself looks quite awkward. I've spent some time and haven't found any solution or example of proper `NSInputStream` subclassing.

`AWSS3TransferUtility` works without leak detection. I'll check progress and cancelling features and try using it. Thanks.

**Comment by yosuke-matsuda** [comment]
We will see if this is caused by `AWSCore` or `CFNetwork`. Please feel free to update the thread if `AWSS3TransferUtility`'s progress and cancellation did not work for you. Thanks.
