### ISSUE TITLE
Can't authenticate with alias

### ISSUE THREAD

**Issue by marcelodeaguiar** [aws/aws-sdk-ios#394]
I am trying to configure UserPool to allow authentication using user email. I have already created the pool and marked **emai**l as an alias.
I then downloaded the sample from here https://github.com/awslabs/aws-sdk-ios-samples/tree/developer-authenticated-identities-2-4/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample updated my ids on Constants.m and run the app and follow up the sign up process to create a user and validate it. Now when I try to download using the user email I get the message "Username or password is invalid". When I try to login with the username everything works fine. How do I make the login work with user's email?

**Comment by mreddyg** [comment]
Hi,

Can you check if the user's email is verified? To use email as an alias (i.e. authenticate with email), the email has to be verified. You can check this under user details in the Cognito console. 

In general, users can have email and/or phone number as alias. If a user-pool has email and/or phone number alias enabled, the users in that user-pool will be able to use them as alias only after they have verified the email/phone number. 

The iOS SDK provides api's to verify users email and phone numbers. To verify a user's email, request for a verification code for email. A verification code will be delivered to the users's registered email address. Use this code with the verification api to verify the email.

Thanks,
Mahesh

**Comment by behrooziAWS** [comment]
Also confirm you are using 2.4.2 of the ios sdk, there was a bug with earlier versions causing aliases to not work.

**Comment by marcelodeaguiar** [comment]
@mreddyg I double checked and confirmed that both the user and email are verified.
@behrooziAWS Yes I'am using 2.4.2.

**Comment by mreddyg** [comment]
Can you give us the "Request Id" from this error and the timestamp?  The "Request Id" should be part of the error message.

**Comment by marcelodeaguiar** [comment]
The request id is **3cf62a99-22a6-11e6-b0e1-ab7df24c55af**
Timestamp: **1464200805**

I have attached the full log if you want it.
[AWS Login Error.docx](https://github.com/aws/aws-sdk-ios/files/282658/AWS.Login.Error.docx)

**Comment by mreddyg** [comment]
From this request id, it looks like your app is using the iOS SDK version 2.4.1. Can you retry with iOS SDK 2.4.2.

**Comment by marcelodeaguiar** [comment]
You are right! The sample uses version 2.4.1. This version is fixed in the Pod file mabe it should be changed. Thank you anyway its working now.

**Comment by behrooziAWS** [comment]
it was using ~> 2.4.1 in the Podfile which should pull in 2.4.2 on a pod update.  Regardless I've updated it to 2.4.2 now.
