### ISSUE TITLE
Still seeing some devices setting a NSNumber Boolean to true and some to 1

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#395]
So, I noticed a while back that Swift boolean was not supported but treated differently on different device. I did move over to use 
`var emailVerified:NSNumber = NSNumber(bool: true)`
But, I still see some devices setting this to true rather than 1, this only happens occasionally, but is disastrous as it then corrupts the data for that user.

Would be good to simply support Swift Bool instead.

**Comment by rohandubal** [comment]
Hi, could you please provide some more details on this? Does this happen with a specific set of devices with specific OS version? Are there any steps by which we can reproduce this? Thanks.

**Comment by helloniklas** [comment]
I originally had this problem when using swift Bool which was the treated differently on an 4s running 9.3 versus 6s running 9.3.2. It seemed to go away when using NSNumber(:bool) instead. But now that the app is out in the wild and there are 1000s of users variations I still see this sometimes showing up as 0 and sometimes as bool. 

Seems your swift implementaton is a bit flakey.

**Comment by karthiksaligrama** [comment]
@helloniklas apologize for responding so late, what we are trying to understand here is what part of SDK are you facing this problem?

**Comment by helloniklas** [comment]
This is happening while using the dynamodb model mapper and saving an object directly to dynamodb from Swift. Despite having these properties as NsNumber as swift Bool doesn't work.

**Comment by minbi** [comment]
@helloniklas Are you still having this problem with newest SDKs?
