### ISSUE TITLE
2.4.0 logins dictionary is deprecated

### ISSUE THREAD

**Issue by Ashish145** [aws/aws-sdk-ios#396]
I have done with "Amazon Cognito Identity : User Pools (Beta)" but when trying with "External Identity Providers" there is some probem because latest version. so i need latest demo for the External Identity Providers Amazon Cognito Identity : User Pools (Beta) Please help me out..

Getting following error in External Identity Providers :

The logins dictionary is deprecated. If you implement `AWSIdentityProviderManager`, do not call `- setLogins:`. The `AWSIdentityProviderManager` should return the valid logins.

**Comment by karthiksaligrama** [comment]
Consolidating to #357
