### ISSUE TITLE
How do I mention custom end point without the use of regiontype ? (I am putting android code thats what I want)

### ISSUE THREAD

**Issue by vishnuag05** [aws/aws-sdk-ios#398]
As far as I searched there isn't any way to get this done. If there is a way please let me know.

    public static String getPreSignedURL(String url) {
    java.util.Date expiration = new java.util.Date();
    long msec = expiration.getTime();
    msec += 1000 * 60 * 5; // 5 minutes
    expiration.setTime(msec);
    
    AWSCredentials myCredentials = new BasicAWSCredentials(
    AppConstants.AWS_ACCESS_KEY_ID, AppConstants.AWS_SECRET_KEY_ID);
    AmazonS3 s3client = new AmazonS3Client(myCredentials);
    s3client.setEndpoint(AppConstants.ENDPOINT_S3);
    GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(
    AppConstants.BUCKET_NAME, url.replace(AppConstants.OBJECT_NAME_FILTER, ""));
    request.setExpiration(expiration);
    URL objectURL = s3client.generatePresignedUrl(request);
    return objectURL.toString();
    }

**Comment by karthiksaligrama** [comment]
At this time we do not support custom endpoints for iOS. We are working on providing the API for this. Consolidating to this #303 .

**Comment by vishnuag05** [comment]
@karthiksaligrama I would really appreciate if you provide me a way to do so, I mean maybe some tweaks in the code . I tried to change URL to my custom points but seems like RegionType is messing it up.
Apart from this when you guys planning to provide sdk for this , I am really concerned abpout this because my whole app is music streaming app without this It will become use less.
