### ISSUE TITLE
Singing up with email to AWSCognitoIdentityUserPool is case sensitive

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#399]
If signUp with AWSCognitoIdentityUserPool using email Test@test.com, I then can not log in a the same user with test@test.com (all lower case). Now I can of course enforce all lower case from the app itself, but seems that email signUp shouldn't be case sensitive when signing up with a user pool.

**Comment by MarkMerc123** [comment]
Hello,

Thank you for your feedback. We will consider it in future development. Your solution of either forcing the user to enter all lowercase, or converting to all lowercase after input solves the problem.

Thanks,
Mark

**Comment by jbailey2010** [comment]
Hi, 

We appreciate the request. When the service has added support for this feature, we will update the client support appropriately.
