### ISSUE TITLE
Remove unused frameworks?

### ISSUE THREAD

**Issue by Morrowless** [aws/aws-sdk-ios#400]
I am only using S3 for my app but apparently all of the AWS frameworks are being included, even with the strip-frameworks.sh run script phase. I thought I would only need AWSCore and AWSS3 or am I misunderstanding this? 

Contents of my app's .ipa:
![screen shot 2016-06-06 at 6 16 50 pm](https://cloud.githubusercontent.com/assets/16893090/15817488/2a80bc80-2c13-11e6-8518-b279550372bd.png)

**Comment by karthiksaligrama** [comment]
how are you including the frameworks?

**Comment by Morrowless** [comment]
I added them like instructed. 
![screen shot 2016-06-07 at 3 04 17 pm](https://cloud.githubusercontent.com/assets/16893090/15847471/1c7706f4-2cc1-11e6-8fef-83f2dd22a87a.png)

**Comment by karthiksaligrama** [comment]
if you are using carthage. You should be able just include the frameworks that you need in the embed frameworks phase.

**Comment by karthiksaligrama** [comment]
Assuming resolved. closing this issue. Please reopen/ open a new issue if you have any other concerns.
