### ISSUE TITLE
AWSS3TransferUtility causes app crash if type check fails

### ISSUE THREAD

**Issue by shankera** [aws/aws-sdk-ios#401]
The transfer utility type checks with an assert, which causes the app to crash unrecoverably if it fails. 

https://github.com/aws/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L670

**Comment by shankera** [comment]
This is an actual use-case resulting in a crash, and not just a question. There are many valid use cases for the NSURLSessionTaskDelegate to return a task that has an empty response, or a general response that is not a NSHTTPURLResponse. Can a generalized error be returned from the function when these situations occur, instead of crashing the app?

**Comment by karthiksaligrama** [comment]
can you give me some example use cases w.r.t to S3 transfer utility? What is the return type in your use case?

**Comment by shankera** [comment]
<img width="446" alt="screen shot 2016-06-06 at 6 33 11 pm" src="https://cloud.githubusercontent.com/assets/5796193/15877364/52b81378-2ce1-11e6-9a01-1fb59d63da4a.png">

This is what the task object looks like when it crashes. If there is an issue with the service request there is the possibility of the NSURLSessionTask to be nil, empty, or a type other than NSHTTPURLResponseTask - even if the original request was an HTTP request. This is behavior defined in the NSURLSessionTaskDelegate, which is not necessarily specific to the S3 transfer utility.

**Comment by karthiksaligrama** [comment]
If there is an issue with request are you not getting a valid error object?

**Comment by shankera** [comment]
That is correct, we are not getting a valid error object.

**Comment by shankera** [comment]
Will you be fixing this issue?

**Comment by karthiksaligrama** [comment]
I'm not sure if we are targeting a valid scenario here. If you are getting no response or an error object there is something very likely gone wrong at the network level and it should result in a fault which is the current implementation.

**Comment by karthiksaligrama** [comment]
Closing this issue as its not really a bug. Please open a new issue if you have other questions.

**Comment by shankera** [comment]
The screenshot that I added to this chat has an exception breakpoint occurring on the line in question, as a result of an empty task object. How is it not a bug that this code was able to execute and fail? Why can't it be fixed regardless of how much of an edge case it is? Code-wise it's plain as day, there is an _assert_ that will crash the app if the type check fails.
