### ISSUE TITLE
AWSWebIdentityCredentialsProvider should allow nullable providerId from Swift code

### ISSUE THREAD

**Issue by traylewin** [aws/aws-sdk-ios#402]
The providerId field is required to be nil when using OpenID endpoints. However it's impossible to send a nil from Swift because the field isn't marked as nullable in the ObjectiveC signature. Note: You can't send an empty string or you'll get a validation error stating that there must be 4 characters. 

Please change this: 
- (instancetype)initWithRegionType:(AWSRegionType)regionType
                        providerId:(NSString *)providerId
                           roleArn:(NSString *)roleArn
                   roleSessionName:(NSString *)roleSessionName
                  webIdentityToken:(NSString *)webIdentityToken;

to this

- (instancetype)initWithRegionType:(AWSRegionType)regionType
                        providerId:(**nullable** NSString *)providerId
                           roleArn:(NSString *)roleArn
                   roleSessionName:(NSString *)roleSessionName
                  webIdentityToken:(NSString *)webIdentityToken;

**Comment by karthiksaligrama** [comment]
Fixed with 2.4.6
