### ISSUE TITLE
Deleting identity from Identity browser causes sdk to stay locked in with invalid identity id

### ISSUE THREAD

**Issue by simoami** [aws/aws-sdk-ios#403]
This happens when the condition `shouldResetIdentityId` always returns false as show below:

https://github.com/aws/aws-sdk-ios/blob/8f5aa0d6d85d971f80c3491ff0297b62af5fa947/AWSCore/Authentication/AWSCredentialsProvider.m#L433

```
+ (BOOL)shouldResetIdentityId:(NSError *)error
                authenticated:(BOOL)isAuthenticated {
    BOOL shouldResetIdentityId = NO;
    if ([error.domain isEqualToString:AWSCognitoIdentityErrorDomain]) {
        if (error.code == AWSCognitoIdentityErrorResourceNotFound) {
            shouldResetIdentityId = isAuthenticated; <-- PARAM GETS NO FROM isAuthenticated
        }
        ...
    }
    return shouldResetIdentityId;
}
```

Even after logging in, the identity id doesn't get renewed and isAuthenticated continues to be false.

Any ideas?

**Comment by behrooziAWS** [comment]
Looking this over, I think it should always reset the identity id when the server returns ResourceNotFound regardless of whether the identity is authenticated or not.  Will test this and follow up.

**Comment by simoami** [comment]
Hello, what this resolved? 
@rohandubal  I don't understand the reason for closing this issue?

**Comment by rohandubal** [comment]
Hello @simoami , apologies. The issue was closed in error. Reopened.

Thanks,
Rohan

**Comment by simoami** [comment]
no problem, thanks!
