### ISSUE TITLE
AWSDynamoDB Impossible to authenticate

### ISSUE THREAD

**Issue by davideme** [aws/aws-sdk-ios#405]
AWS Stack:
Cognito
Federated Identities - with a Facebook App
DynamoDB tables - that require Cognito authenticated access

Scenario:
1. Calling AWSDynamoDBObjectMapper.load()
2. Received NotAuthorizedException, Unauthenticated access is not supported for this identity pool
3. Calling AWSIdentityManager.defaultIdentityManager().loginWithSignInProvider or AWSIdentityManager.defaultIdentityManager().resumeSessionWithCompletionHandler
4. Received a Succefull authentication
5. Calling again AWSDynamoDBObjectMapper.load()
6. Received again NotAuthorizedException, Unauthenticated access is not supported for this identity pool

Expected:
Call to AWSDynamoDBObjectMapper after authentication should return the correct result and not an authentication error.

Pods and Library:
  - AWSMobileHubHelper v0.2 for swift
  - AWSCognitoIdentityProvider (2.4.3)
  - AWSCore (2.4.3)
  - AWSDynamoDB (2.4.3)
  - AWSLambda (2.4.3)
  - AWSMobileAnalytics (2.4.3)
  - AWSS3 (2.4.3)
  - AWSSNS (2.4.3)

**Comment by karthiksaligrama** [comment]
can you tell me how you are initializing `AWSDynamoDBObjectMapper ` ?

**Comment by davideme** [comment]
It was initialized with Fabric, 
`      Fabric.with([AWSCognito.self])`

**Comment by rohandubal** [comment]
Hi,
Could you please specify what credential provider you are using and how you are using it? can you share the code snippet without your credentials?
Thanks!

**Comment by davideme** [comment]
I was using the example generated by AWS Mobile Hub + Fabric 
All the credentials wher in info.plist

Using cognito authentication with Facebook Provider

**Comment by rohandubal** [comment]
Hi,
Currently is not possible to use Fabric with Mobile Hub Helper Framework as the AWS SDKs are Dynamic Frameworks while Fabric is static. You could try using the older SDKs (2.3.6) but they do not have support for info.plist and need to initialize the clients from code.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
closing this issue. Please reopen/open a new issue if you have any other question.
