### ISSUE TITLE
Access identity pool datasets across multiple user ids

### ISSUE THREAD

**Issue by simoami** [aws/aws-sdk-ios#406]
I need to be able to display a list of users whose data is stored in datasets via Cognito Sync, like in this [screenshot](https://www.invisionapp.com/subsystems/main_landing/assets/img/screens/social-5.png). It seems that I cannot access datasets across multiple uses to fetch their names, so what is the recommended approach?
1. Access each user's "Profile" dataset to pull their first, last name, or 
2. Have a separate dynamodb table for "Users" to query multiple users. If so what is private datasets still relevant for?

**Comment by karthiksaligrama** [comment]
You are right you cannot access datasets across multiple users. You need to use Dynamodb or some other form of storage if you want to query multiple users. Private datasets can be used for storing user specific information and making it available across multiple devices to give users consistent user experience.

**Comment by simoami** [comment]
ok, thanks for confirming. It's worth noting that there are specific applications for this storage model and not suitable for many more. It works for apps like Password managers, where data is really not meant to be queried or processed across multiple accounts. It doesn't work for social apps where you want to query users based on their geo location, age, gender...or to display user profiles you want to "friend". 

Closing ticket.
