### ISSUE TITLE
AWSCognitoCredentialsProvider and AWSServiceConfiguration regions and stuck UI

### ISSUE THREAD

**Issue by DsrMedia** [aws/aws-sdk-ios#407]
The goal is to download a few hundred small files from our S3 Bucket.
Our AWS Cognito is set up in the EUWest1 region and our S3 Bucket in the EUCentral1 region.

`[AWSLogger defaultLogger].logLevel = AWSLogLevelVerbose;
        self.credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionEUWest1 identityPoolId:@"eu-west-1:xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"];
        self.configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionEUCentral1 credentialsProvider:self.credentialsProvider];
        AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = self.configuration;`

With this configuration I get the following error:

> Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=1 "(null)"
> which is a AWSS3TransferUtilityErrorRedirection error. status code is 301

When I change the regions in the configuration to central, I'm getting the following error

> Error: Error Domain=com.amazonaws.AWSCognitoCredentialsProviderErrorDomain Code=4 "(null)"
> AWSiOSSDK v2.4.3 [Debug] AWSURLSessionManager.m line:525 | -[AWSURLSessionManager printHTTPHeadersAndBodyForRequest:] | Request headers:
> {
>     "Content-Type" = "application/x-amz-json-1.1";
>     Host = "cognito-identity.eu-central-1.amazonaws.com";
>     "User-Agent" = "aws-sdk-iOS/2.4.3 iPhone-OS/9.3.2 en_AT";
>     "X-Amz-Date" = 20160617T090206Z;
>     "X-Amz-Target" = "AWSCognitoIdentityService.GetCredentialsForIdentity";
> }
> AWSiOSSDK v2.4.3 [Debug] AWSURLSessionManager.m line:542 | -[AWSURLSessionManager printHTTPHeadersAndBodyForRequest:] | Request body:
> {"IdentityId":"eu-west-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx"}

The identityId printed here is not the same as the identityPoolId I use in the configuration, but I'm assuming that's ok.

In the Android version of our app everything works fine, however there we can set an endpoint. Basically my question is how can I convert the following Android configuration to iOS?

```
 // Initialize the Amazon Cognito credentials provider
                CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                                                                            activity.getApplicationContext(),
                                                                            S3_IDENTITY_POOL_ID,
                                                                            Regions.EU_WEST_1
                );

                // Create an S3 client
                AmazonS3 s3 = new AmazonS3Client(credentialsProvider);
                // Set the region of the S3 bucket
                s3.setRegion(Region.getRegion(Regions.DEFAULT_REGION));
                s3.setEndpoint(S3_END_POINT);
```

My next issue is that when using the AWSS3TransferUtility to download files in a loop in sequence, my UI gets stuck when creating the tasks. With the AWSS3TransferManager this does not happen. I have yet to try the parallel mechanism described in the documentation, however for our purposes a sequential download would be beneficial. Any suggestions?

http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html

**Comment by rohandubal** [comment]
Hi,
Sorry that you are having issues using Transfer Utility. Could you please specify how are you initializing and calling the Transfer Utility client?

-Rohan

**Comment by karthiksaligrama** [comment]
Assuming resolved. Please open a new issue if otherwise
