### ISSUE TITLE
Missing newline in AWSSignature

### ISSUE THREAD

**Issue by ScottRobbins** [aws/aws-sdk-ios#408]
You're missing a newline at the end of `AWSSignature.h`

Not a big deal, but Xcode gives me a warning for it and it hurts my OCD

**Comment by karthiksaligrama** [comment]
What version of xcode are you using?

**Comment by harrisnb** [comment]
same for me: XCode Version 7.3.1 (7D1014)

**Comment by karthiksaligrama** [comment]
Fixed with 2.4.6
