### ISSUE TITLE
iOS AppVersion and AppBuild are filled in wrong field?

### ISSUE THREAD

**Issue by hubertwang** [aws/aws-sdk-ios#409]
Hi everyone,

The tracking key named "app_version_code" and "app_version_name" arouse my interest since the naming logic is different from iOS naming logic. I checked the key names and then realized that they may come from android PackageInfo. 

[Android Studio - Version Your App](https://developer.android.com/studio/publish/versioning.html)

> **android:versionCode** — An integer value that represents the version of the application code, relative to other versions.

> **android:versionName** — A string value that represents the release version of the application code, as it should be shown to users. The value is a string so that you can describe the application version as a <major>.<minor>.<point> string, or as any other type of absolute or relative version identifier.

According to the explanation above, the corresponding field on iOS should be CFBundleVersion(app build) and CFBundleShortVersionString(app version).

But in AWSClientContext.m, they are save to:

`
@"app_version_name": self.appBuild,
@"app_version_code": self.appVersion,
`
[AWSClientContext.m line: 88-89](https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Service/AWSClientContext.m)

![2016-06-23 2 13 52](https://cloud.githubusercontent.com/assets/1281311/16294086/4ca1cbf6-3951-11e6-8320-ea518c3ca30c.png)

As you can see, in the attachment above, the test value for "app_version_name" is "v1.2", which matches the format of iOS app version.

Therefore, I think the correct mapping should be:
app_version_name-> android:versionName, iOS:CFBundleShortVersionString(app version)
app_version_code-> android:versionCode, iOS:CFBundleVersion(app build)

#410

**Comment by karthiksaligrama** [comment]
we are aware of this bug, we will let you know when we fix this in the sdk

**Comment by karthiksaligrama** [comment]
Fixed with 2.4.6
