### ISSUE TITLE
AWSCognito: make the file path of the sqlite3 file configurable

### ISSUE THREAD

**Issue by MathieuLescure** [aws/aws-sdk-ios#411]
It seems that the path is hardcoded to be in ".DocumentDirectory". As a consequence a user can easily edit the file (by downloading, modifying and uploading it back with iTune). This is not alway desired and it would be nice to be able to configure any path (or at least one in ".ApplicationSupportDirectory")

**Comment by karthiksaligrama** [comment]
The file can only be downloaded when you set `UIFileSharingEnabled` in your plist.

**Comment by MathieuLescure** [comment]
Setting UIFileSharingEnabled to false may work for some use cases, but unfortunately not for mine. UIFileSharingEnabled apply to all files in the documents folder, and in my case I need to let the users download all the files in this folder except the Cognito db.

**Comment by karthiksaligrama** [comment]
Thanks we will consider making this configurable.
