### ISSUE TITLE
AWSDynamoDBObjectModel description

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-ios#412]
I have a swift class like the attached but it seems "description" is not a valid variable. Is there a workaround for this as the database attribute name is description and it cannot be changed at this stage.

<img width="1000" alt="description" src="https://cloud.githubusercontent.com/assets/10569142/16336053/f7f613a4-3a3c-11e6-88d1-b02e7315ae18.png">

**Comment by karthiksaligrama** [comment]
you can use another name for description and then override the `JSONKeyPathsByPropertyKey` class function 

```
override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
              ......
               "_description" : "description",
              ......
        ]
    }
```

**Comment by hashitha** [comment]
Thanks

**Comment by keegho** [comment]
Error:
Method doesnt override any method from its superclass >>>???

**Comment by danieldelouya** [comment]
Struggling with the same issue. Same "Method doesnt override any method from its superclass"

**Comment by pantuspavel** [comment]
@keegho @danieldelouya try this if you're using swift 3:
```
override class func jsonKeyPathsByPropertyKey() -> [AnyHashable : Any]
```
