### ISSUE TITLE
Issue 180 still not resolved

### ISSUE THREAD

**Issue by pradipvaghasiya** [aws/aws-sdk-ios#415]
When user on a wifi network without internet or poor internet like edge and even if Transfer manager is asked to download the image once, images are still being corrupted.

**Comment by pradipvaghasiya** [comment]
Steps:
Started 3 downloads on Edge network no data or very less is coming with very poor connection
Do some dirty stuff like below
Go to airport mode and come back
Take app in background and come back again. 
Results corrupted images. Not every time but sometimes when below line gets printed on Log
                        AWSLogWarn(@"Warning: target file already exists, will be overwritten at the file path: %@",delegate.downloadingFileURL);

**Comment by karthiksaligrama** [comment]
thanks for reporting this. Will update when resolved.

**Comment by karthiksaligrama** [comment]
Thanks for reporting this. We will update the thread when issue resolved.

**Comment by pradipvaghasiya** [comment]
Thanks for your quick update! 
Can you please suggest any workaround for this if any?

**Comment by rishabhthakrar** [comment]
Hi Team, 

We are encountering the same issue of Corrupt images for AWS S3 and the Workaround suggested in #180 doesnt work either. 

Look forward to your urgent support with a resolution / workaround for this at the earliest.

**Comment by rishabhthakrar** [comment]
Hi Team, 

We are facing the same issue with AWS S3. Corrupt images are being retrieved with weak (below 3G) connectivity. Going through the threads, I see various people facing this issue and have reported the same. 

This is of great concern to us as Corrupted images are being sent to our end Users, affecting the overall user experience. 

Would like to urge you for your support in having this resolved at the earliest. Look forward to hearing from you.

**Comment by rohandubal** [comment]
Hi,

I tried multiple network configurations to try and reproduce this issue but without success. I tried multiple network profiles with 5kbps without packet loss, 15kbps with 90% packet loss, etc. and still could not reproduce the issue. Can any one provide a code snippet by which we can reproduce the issue?

Also, 
Does the code explicitly set the `downloadingFilePath` on the download request? Can you try to reproduce without using `downloadingFilePath` property?

Thanks,
Rohan

**Comment by pradipvaghasiya** [comment]
Please find code snippet. 
`       let downloadRequest = AWSS3TransferManagerDownloadRequest()
        downloadRequest.bucket = AWSManager.s3BucketName()
        downloadRequest.key = key
        let transferManager = AWSS3TransferManager.defaultS3TransferManager()
        return transferManager.download(downloadRequest)
`

I have tried with both setting downloadingFilePath and without it. Issue remains. 

Currently the work around that we are following is to set maxRetryCount to 0 for AWSServiceConfiguration.

**Comment by tuchangwei** [comment]
I met the same issue. My network connection was bad, I started downloading photos and waited them to complete.
The logs as following:
```
2016-12-21 21:38:14.669 xxx[17316:569501] AWSiOSSDK v2.4.11 [Debug] AWSURLSessionManager.m line:425 | -[AWSURLSessionManager URLSession:dataTask:didReceiveResponse:completionHandler:] | target file already exists, will be appended at the file path: file:///Users/vale/Library/Developer/CoreSimulator/Devices/4445A553-6720-48A2-AABF-198B83C11A64/data/Containers/Data/Application/52B6422A-2293-4B0A-987C-7FD81D8C8C8A/tmp/130591.jpg97130FC0-CD1F-4B03-9801-639E4899093A-17316-00002291B2275E12
2016-12-21 21:38:34.048 xxx[17316:569861] AWSiOSSDK v2.4.11 [Debug] AWSURLSessionManager.m line:553 | -[AWSURLSessionManager printHTTPHeadersForResponse:] | Response headers:
{
    "Accept-Ranges" = bytes;
    "Content-Length" = 119887;
    "Content-Type" = "image/jpeg";
    Date = "Wed, 21 Dec 2016 13:38:07 GMT";
    Etag = "\"0ac527312aa40733ebde1936fa2946bd\"";
    "Last-Modified" = "Tue, 20 Dec 2016 17:10:28 GMT";
    Server = AmazonS3;
    "x-amz-id-2" = "oJXGJ/qw5kPajBRuKHnDuzVi6UVRVfdzedgRVGaBFVK1Zah/4dqBLcnUFZIY1xpWXTWHNIbhpCo=";
    "x-amz-request-id" = 620078565851AD73;
}
----------------------------------------
2016-12-21 21:38:34:053 AWSAPI.swift=>downloadFileAsync(serverFileName:destinationPath:completionHandler:)[98]=>task.isFaulted false
----------------------------------------
2016-12-21 21:38:34:053 AWSAPI.swift=>downloadFileAsync(serverFileName:destinationPath:completionHandler:)[99]=>task.isCompleted true
----------------------------------------
2016-12-21 21:38:34:054 AWSAPI.swift=>downloadFileAsync(serverFileName:destinationPath:completionHandler:)[100]=>task.isCancelled false
----------------------------------------
2016-12-21 21:38:34:054 AWSAPI.swift=>downloadFileAsync(serverFileName:destinationPath:completionHandler:)[101]=>task.error nil
----------------------------------------
2016-12-21 21:38:34:055 AWSAPI.swift=>downloadFileAsync(serverFileName:destinationPath:completionHandler:)[102]=>task.exection nil
```
I had planted to see if the error is existing, then I can delete the broken photo, but you see the logs:
`task.isCompleted true`, `task.isFaulted false`. These information can't help me delete the broken photo.

Here are the photos I downloaded.
![qq20161221-0](https://cloud.githubusercontent.com/assets/2604045/21391814/2b013602-c7c8-11e6-9c81-61ff06198edd.png)

**Comment by bruce-lumo** [comment]
Any resolution on this? I am having some realm files get corrupted when I upload them to S3 over a poor network.

**Comment by tuchangwei** [comment]
@bruce-lumo Set `AWSServiceConfiguration.maxRetryCount = 0`

**Comment by cmavromoustakos** [comment]
So not sure this is related to your issues but I just spent the last 2 hours banging my head with this issue. I realized that I changed the time on my device to a future time to test something related to local notifications.

Apparently that was causing the same behavior as the issue reported here. Again the 2 issues might be completely unrelated. But for anyone stumbling across this issue it might save you some time.

**Comment by twobitlabs** [comment]
Setting the maxRetryCount = 0 in our testing does indeed fix the download corruption issue. However, it also prevents the SDK from detecting clock skew errors and retrying the request a 2nd time in that case. So users that have manually set their clocks on their phones will get errors.

**Comment by minbi** [comment]
Please use TransferUtility from now on. Samples can be found [here](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample)
