### ISSUE TITLE
Why kinesis retry only 3times

### ISSUE THREAD

**Issue by JMASystems** [aws/aws-sdk-ios#416]
In AWSAbstractKinesisRecorder.m,
submitAllRecords method retry only 3times,and failure records is deleted.
This specification will cause a problem at the time of the off-line uses.

My application used in the off-line for long-term,then many records were deleted.
Will this specification can not be abolished,or is there any solution for it?

Thank you.

**Comment by fosterzhang** [comment]
@JMASystems This is to prevent bogus records from being retried over and over again. It's better to check your network before calling `submitAllRecords`. Meanwhile, we'll see how to improve error handling in the SDK. Stay tuned.

**Comment by karthiksaligrama** [comment]
@JMASystems can you just not call `submitAllRecords` when you don't have network reachability?

**Comment by JMASystems** [comment]
Thank you for reply.

The communication is very unstable in our environment.
So even if we check reachability in advance,api call might be failed sometime.

Can we set a custom retry count property?

**Comment by nexus49** [comment]
+1 for @JMASystems comment

Also it would be very beneficial to be able to know when a message was dropped, so that the client could re enter that record depending on the error. We are also trying to build an app that supports a lot of on/offline and bad connectivity scenarios. Its very hard to debug if kinesis drops messages or if there could be other errors in play.

**Comment by nexus49** [comment]
@JMASystems where you able to find a solution to this issue? I hacked the retry of the sdk but still seem to be missing messages in certain offline scenario's.

**Comment by JMASystems** [comment]
At ver 2.4.8.
It seems to be implemented the KinesisRetryHandler.
https://github.com/aws/aws-sdk-ios/blob/d0154d3f1e1cc20fad8c7339208ee208f1d8c516/AWSKinesis/AWSKinesisRequestRetryHandler.m
So,it might be realized if we modify KinesisConfigration so that we can pass your own handler.
@nexus49 How about that.
