### ISSUE TITLE
Improving Objective C interoperability with Swift ?

### ISSUE THREAD

**Issue by mackoj** [aws/aws-sdk-ios#418]
Hi,

Please can you consider providing interoperability for Swift project by improving support Objective C interoperability feature like:
- [lightweight generics](http://www.miqu.me/blog/2015/06/09/adopting-objectivec-generics/)
- [nullability annotation](http://www.miqu.me/blog/2015/04/17/adopting-nullability-annotations/)
- [kindof](http://www.miqu.me/blog/2015/06/09/adopting-objectivec-generics/)

Something even greater would be to have a full Swift value type support for all of the generated code from AWS platform.

Thanks,

**Comment by karthiksaligrama** [comment]
What version of sdk are you using?

We added generics support to all low leve clients and some high level api's like TransferUtility from version [2.3.4](https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#234)

The nullability support was added similarly in version [2.3.1](https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#231)

What value types in swift are you missing out on?

**Comment by mackoj** [comment]
Hi, 

I use the 2.4.5 version of AWSCore. I use AWS API Gateway to generate my AWSModel and the issue is in that part of the process I think. Can I improve my model on AWS API Gateway in order to have better type information in the generated SDK ? 

Cheers,

**Comment by karthiksaligrama** [comment]
Thanks, we will update you when the fix is out

**Comment by karthiksaligrama** [comment]
@mackoj this issue is fixed. Please download the sdk again from the api gateway console.

**Comment by plougy** [comment]
Can you please remove the space character added in the methods between
the first parenthesis and the class name for the parameters into `*ApiClient.h`?

```swift
- (AWSTask *)usersUserIdPut:( NSString *)userId body:( UserModel *)body;
``` 

Thank you 😉
