### ISSUE TITLE
Support for both 2.3.x and 2.4.x in a library that depends on AWS SDK

### ISSUE THREAD

**Issue by eugeneshih** [aws/aws-sdk-ios#419]
Our company provides a binary library that depends on the AWS iOS SDK. We want to be able to allow users of our library to specify the version they want to use since they also might use the AWS SDK. Some apps need to support iOS 7 so those must use AWS SDK 2.3.x. However, other app developers don't want to be pinned to 2.3.x because they want to use new features provided in 2.4.x.

One solution is to copy all the AWS 2.3.x code into my source and rename everything. This will work, but is undesirable since I'm no longer benefitting from improvements provided by updates in 2.4.x and above. Is there another way?

**Comment by karthiksaligrama** [comment]
1. You cannot use both the sdk' you will have to let the customer choose which version of sdk they want to use.
2. You will have to use reflection and/or custom preprocessor directives in your code to check which version of sdk the customer is using and handle your logic accordingly.

**Comment by karthiksaligrama** [comment]
Closing this issue. Please reopen or log another issue if you have any other question
