### ISSUE TITLE
AWSS3TransferUtilityErrorDomain Code=2

### ISSUE THREAD

**Issue by plougy** [aws/aws-sdk-ios#420]
I get an error from `AWSS3TransferUtilityDownloadCompletionHandlerBlock`when I try to download a file but the error is not documented, and in `task.response` I get a status code **403**.

```
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)"
```

However, I don't understand why the bucket name is prefixed ahead `s3.amazonaws.com` in the url.

Do you have a solution to reverse that?

**Comment by plougy** [comment]
The problem comes from the file permissions.

How added automatically the rights reading for **Any Authenticated AWS User** on each files uploaded from the iOS SDK?

**Comment by Dinalli** [comment]
I get the same error from uploading too. Did you managed to solve this at all ? Im not having much luck

**Comment by plougy** [comment]
Sorry, I resolved the problem by adding a **bucket policy** directly in bucket for the downloading.

@Dinalli: you can add the permissions manually in permission or add a bucked policy.

**Comment by fabriciovergal** [comment]
@Dinalli  Did you solve this issue ?

**Comment by Dinalli** [comment]
Yes thanks. I was missing a permission

**Comment by fabriciovergal** [comment]
Was missing permission directly in the Bucket policy or in the AIM ? 
Could you share your policy file ?

**Comment by damathryx** [comment]
I am having this problem right now for uploading

**Comment by msencenb** [comment]
@damathryx I had this issue today with uploads. I resolved this by specifying a /* on my resources in my IAM policy, like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mmemories-local/*"
            ]
        }
   ]
}
```

In the [setup documentation](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3-setup-for-ios.html) the 'Resource' in the policy document has no trailing *

**Comment by nafetswirth** [comment]
Seeing the same thing out of nowhere. Started a couple days ago without any change to the policy or bucket...

**Comment by anushkmittal** [comment]
same issue. started out of nowhere... It looks really random

**Comment by sachinB94** [comment]
@nafetswirth @anushkmittal Hey, how did you fix this? I'm facing this in production. Happens really randomly.

**Comment by Armenm** [comment]
Hey @sachinB94 I had the same issue on only one of our test device.
After hours of debugging, testing and googling, I found out that the date/time was not set to 'automatic' on the device. It was set to a future date. Setting to the current time fixed the issue for me.
Here as a reference that helped me :)
https://github.com/amazon-archives/aws-sdk-react-native/issues/22#issuecomment-419855230

**Comment by ilkayaktas** [comment]
I know this is an old question, however it's better to write my situation and solution. 
In my iOS (Swift) project, I was trying to upload a picture after login (using Cognito) and I got this error:

    Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" 

Everything seemed well on code below:
```

    transferUtility.uploadData(
                data,
                key: "my-picture.png",
                contentType: "image/png",
                expression: expression,
                completionHandler: completionHandler).continueWith { (task) -> AnyObject? in
                    if let error = task.error {
                        print("Error: \(error.localizedDescription)")
                        DispatchQueue.main.async {
                            print("Error on upload: \(error.localizedDescription)")
                        }
                    }
                    
                    if let _ = task.result {
                        DispatchQueue.main.async {
                            print("Upload Starting!")
                        }
                    }
                    
                    return nil;
            }

```
The solution is on [AWS Amplify Storage documentation][1]. As stated there, I should have written  the key value like 
   ` key: "private/{user_identity_id}/my-picture.png"`

Maybe, it will help anybody in the future.



  [1]: https://aws-amplify.github.io/docs/ios/storage#storage-access

**Comment by tirthpatelflynn** [comment]
@sauravexodus I am trying to upload video using same method like this can you provide me with an idea where do i put setting for disabled accelerated mode

```
transferUtility.uploadData(
                 data,
                 key: "my-picture.mp4",
                 contentType: "video/mp4",
                 expression: expression,
                 completionHandler: completionHandler).continueWith { (task) -> AnyObject? in
                     if let error = task.error {
                         print("Error: \(error.localizedDescription)")
                         DispatchQueue.main.async {
                             print("Error on upload: \(error.localizedDescription)")
                          }
                     }
```
                     
                     if let _ = task.result {
                         DispatchQueue.main.async {
                             print("Upload Starting!")
                         }
                     }
                     
                 ```
    return nil;
             }
```

**Comment by tapiwakundi** [comment]
Thank you so much @msencenb . You literally saved my. I was pulling my hair struggling with the aws sdk
