### ISSUE TITLE
resumeAll not resuming upload after switching to/from airplane mode

### ISSUE THREAD

**Issue by GavinsGit** [aws/aws-sdk-ios#421]
Hi,

I'm testing a wifi failure condition here while uploading a multi-part file.

Here is the scenario:

1) start upload of file using AWSTransferManager
2) Bring up bottom tray and switch to airplane mode. 
3) Upload task fails with the following error:

Upload failed: [Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSErrorFailingURLStringKey=https://s3-eu-west-1.amazonaws.com/kindeo.com-staging/8be4a044-42cc-4896-9615-5c66c2b2558a/video.mp4?partNumber=1&uploadId=7bs1CBYUfhiqQmgqNH2sudg4mBt6TphwAPj3i5xwpdSu4aHelkZQatDRRHZs.J6joVCq04lAxsb2O1jU28icZ.1b_oDC3soYkikEtEtFRjgqZoFl5UeDQ3gQE, _kCFStreamErrorCodeKey=57, NSErrorFailingURLKey=https://s3-eu-west-1.amazonaws.com/XXXXX.com-staging/8be4a044-42cc-4896-9615-5c66c2b2558a/video.mp4?partNumber=1&uploadId=7bs1CBYUfhiqQmgqNH2sudg4opVbynSmBt6TphwAPj3i5xwpdSu4aHelkZQatDRRHZs.J6joVCq04lAxsb2O1jU28icZ.1b_oDC3soYkikEtEtFRjgqZoFl5UeDQ3gQE, NSLocalizedDescription=The Internet connection appears to be offline., _kCFStreamErrorDomainKey=1, NSUnderlyingError=0x1458ae40 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57}}}]

4) I switch off airplane mode and make a call to resumeAll, however the upload does not restart.

What is the correct process for handling a network failure when using AWSTransferManager?

**Comment by rohandubal** [comment]
Hi,

Are you pausing all the ongoing requests when you receive the network changed event? If the transfer is already failed, you cant resume it directly by calling resume all. It should be in a paused state before you can resume it. On a failed download, you can add a custom retry logic in the completion handler.

Thanks,
Rohan
