### ISSUE TITLE
Cache control for S3 uploads

### ISSUE THREAD

**Issue by whiskey** [aws/aws-sdk-ios#423]
Hey guys,

I'm struggling to set proper cache headers (like `max-age=3600`) for my uploaded files via the iOS SDK 2.4.x. Any hint here or [on StackOverflow](http://stackoverflow.com/questions/38096610/how-to-define-cache-control-for-awss3transferutility) is highly appreciated.

Thanks

**Comment by karthiksaligrama** [comment]
commented on your stackoverflow post. Closing this issue to keep the thread in a single place.

**Comment by whiskey** [comment]
Sorry @karthiksaligrama but as I stated out in SO, the expected solution still does not work. So it's either a user error (this is what I always assume first) or a bug. It would be nice if somebody else would check the current state.
