### ISSUE TITLE
AWSS3TransferUtility not always using assumed role; getting 403 error

### ISSUE THREAD

**Issue by cmeil** [aws/aws-sdk-ios#427]
We have ten devices, all using v2.4.3 of the SDK, all running the exact same version of an app, all accessing the same S3 object. 9 devices work. AWS logs show they are using the arn:aws:sts assumed-role. One device consistently gets 403 AccessDenied 368 when accessing the same object. AWS logs show no assumed-role is used for that device. 

We are using temporary credentials only. This scenario should not be possible with the transfer utility.

**Comment by rohandubal** [comment]
Hi,
thanks for reporting this. Could you please mention what kind of device was it? and which OS version it was running? Was it similar to all other devices which you had? 

Thanks,
Rohan

**Comment by cmeil** [comment]
The failing device was an iPhone 5S running iOS 8.2. There was one other device (an iPhone 6 Plus) also running iOS 8.2 that did not exhibit the issue. 

I could not simulate the failure using XCode's Simulator with the 5S and iOS 8.2, though, so I am unclear what it is about that particular device.

**Comment by cmeil** [comment]
Note: While I don't have direct logs from the failing device itself, it also appears that the transfer utility did NOT report the 403 error back to the calling code. We have download retry logic in place in the event of an error, and it was not triggered. So it appears the downloadToURL() method never invoked the completion block with an error code when it failed.

**Comment by rohandubal** [comment]
I am not able to reproduce this on my side. Does it always consistently fail? Do you have any steps by which I can reproduce?

**Comment by cmeil** [comment]
The problem occurred during a public beta event, and it occurred consistently for that one device. I'll contact the device's owner and see if I can install a debug build with with the AWSS3 iOS logs enabled and attempt to reproduce the issue again. Please let me know if you have any specific instructions for what I can capture.

**Comment by cmeil** [comment]
Hi. I didn't get access to the device, but the owner informed me that the phone was no longer correctly maintaining the time of day (damaged cellular radio). This certainly sounds likely to interfere with temporary credentials, which would depend on a functional clock.

However, the AWS SDK also did not provide an indication of the error back to the calling code so that the scenario could be handled, so I still consider there to be an issue here. (i.e., I would expect the completion block to be called with a non-nil error parameter).

**Comment by cmeil** [comment]
I am able to reproduce 1/2 of the problem by manually setting an iPhone's clock forward or backward by a day. This results in the assumed role not being used and a 403 error being logged by AWS. However, in this scenario, the error IS reported by the SDK to the calling code.

Because the issue of the 403 error NOT being reported by the SDK has only thus far been observed on one device, and that device has since been revealed to contain a malfunctioning cellular radio, which could have unknown consequences, I think this issue may be closed.
