### ISSUE TITLE
Xcode 8: Found an unexpected Mach-O header code: 0x72613c21

### ISSUE THREAD

**Issue by peter99330** [aws/aws-sdk-ios#429]
I just tried building an app I was previously developing under Xcode 7 with the new Xcode 8 beta and get the following error with the newest SKD (2.4.5): `Found an unexpected Mach-O header code: 0x72613c21`

Deleting all Frameworks from Embedded Frameworks gets rid of the error, but produces a new one: bash: `/Users/*****/Library/Developer/Xcode/DerivedData/MyApp-gmsydrrvmebbiuarunefhhwwkuty/Build/Products/Debug-iphoneos/MyApp.app/Frameworks/AWSCore.framework/strip-frameworks.sh: No such file or directory`

The project was originally created by Mobile Hub and updated to 2.4.5 using Frameworks.

**Comment by rohandubal** [comment]
Currently, we don't have the compatibility with Xcode  8. I will update this thread once we make it compatible. Thanks!

**Comment by karthiksaligrama** [comment]
related to #413 . Closing this and tracking this in a single thread.
