### ISSUE TITLE
pool.delegate

### ISSUE THREAD

**Issue by onesmalldog** [aws/aws-sdk-ios#430]
I find AWSCognitoIdentityInteractiveAuthenticationDelegate will implement end of confirm user in aws-mobile-blog, but i can't find where the delegate used, can you help me?

**Comment by wdane** [comment]
The blog post you are referring to is https://mobile.awsblog.com/post/TxGNH1AUKDRZDH/Announcing-Your-User-Pools-in-Amazon-Cognito correct? The AWSCognitoIdentityInteractiveAuthenticationDelegate is set on  pool.delegate = self; where self is implementing AWSCognitoIdentityInteractiveAuthenticationDelegate.  And "This protocol is meant to manage your custom login UI and accept username and password information from your end user.  The protocol's methods are only invoked if the user has never authenticated, if the user has signed out, or if the user's refresh token (which is valid for 30 days) has expired:" 

Does this answer your question?
Thanks

**Comment by behrooziAWS** [comment]
Please reopen if you need more clarification.
