### ISSUE TITLE
How do you rename an AWS3 folder(Object)?

### ISSUE THREAD

**Issue by daisoreanu** [aws/aws-sdk-ios#431]
Hi, 

I have looked over the documentation for the iOS (Objective C) and could't fine a way to rename a folder, also if this is not possible, I will appreciate an example regarding moving a file to a different Folder inside same bucket?

Thank you in advance

**Comment by karthiksaligrama** [comment]
You can use [replicate object](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html#//api/name/replicateObject:) api to replicate objects in bucket and then delete api to delete the old objects.

**Comment by karthiksaligrama** [comment]
Assuming answered. Closing issue. Please reopen or raise another issue.
