### ISSUE TITLE
Error in AWSS3TransferUtility Upload Since Version 2.4.6

### ISSUE THREAD

**Issue by serg2007** [aws/aws-sdk-ios#434]
Its not working again since vercion 2.4.6

{ status code: 403, headers {
    Connection = close;
    "Content-Type" = "application/xml";
    Date = "Mon, 25 Jul 2016 14:34:16 GMT";
    Server = AmazonS3;
    "Transfer-Encoding" = Identity;
    "x-amz-id-2" = "3lYncChov3jve9vNwGdbaPZMmmiVnkozmGt/PmK6ZhxA3hrt+VLM5EOUbHTvz1OYBYnxWl8uAYI=";
    "x-amz-request-id" = 509F81000B0645C6;
}

**Comment by fosterzhang** [comment]
403 usually implies permission issue. Would you please double check whether the Cognito credentials have permission to access S3?

**Comment by karthiksaligrama** [comment]
Assuming resolved, Closing this issue. Please let me know if this persists.
