### ISSUE TITLE
iOS 7.x support

### ISSUE THREAD

**Issue by hayohayo** [aws/aws-sdk-ios#437]
As far as I understand it 2.3.x is the latest version that still supports iOS 7.x. And 2.4.x is 8+.

Is decision to switch to 8+ explained anywhere? I'd like to read more about it.

Will 2.3.x still get updates?

**Comment by karthiksaligrama** [comment]
You are right. We not have published switch to 8+ anywhere, but it can be summarized as follows 

* Versions below iOS * have 3% market share [See](https://developer.apple.com/support/app-store/)
* With 2.4.x we added support for dynamic frameworks which was only supported with iOS 8+

Version 2.3.x will not be getting any more updates, You should plan to switch to 2.4.x incase you want continuous bug fixes and improvements.

**Comment by hayohayo** [comment]
Thank you for your answer, Karthik! I assume it is mainly about dynamic frameworks, and the switch is justified by market share... It still causes problems for the 3%, which some people care about :(

Anyway, thanks!
