### ISSUE TITLE
Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by EricRen20** [aws/aws-sdk-ios#438]
I am a new on using the AWS SDK. I got the error when I access AWS resource by signing up using Cognito Identity user pool.

Here is my code about how I create conitocredentialprovider.

> AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:nil];
> AWSCognitoIdentityUserPoolConfiguration *userPoolConfiguration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:@"YOUR_CLIENT_ID"  clientSecret:@"YOUR_CLIENT_SECRET" poolId:@"YOUR_USER_POOL_ID"];
> [AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration userPoolConfiguration:userPoolConfiguration forKey:@"UserPool"];
> AWSCognitoIdentityUserPool *pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];
> AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"YOUR_IDENTITY_POOL_ID" identityProviderManager:pool];
> 

when I access DynamoDB, I got error saying Invalid login token. Issuer doesn't match providerName.

Also, I noticed the logins dict where the key starts with NULL, which is so wired.
 

> [AWSURLSessionManager printHTTPHeadersAndBodyForRequest:] | Request body:
> {"Logins":{"(null)\/us-east-1........":"....."

anyone knows what the problem is?
Thanks,

**Comment by EricRen20** [comment]
rolling back to 2.4.5 and everything works fine.

**Comment by karthiksaligrama** [comment]
we re aware of this issue and working on a fix.

**Comment by karthiksaligrama** [comment]
fixed in 2.4.7
