### ISSUE TITLE
AWSMobileHubHelper SDK closure (AnyObject, NSError) -> Void, Which should be (AnyObject?, NSError?) -> Void .

### ISSUE THREAD

**Issue by beeth0ven** [aws/aws-sdk-ios#440]
In AWSMobileHubHelper's protocol `AWSSignInProvider ` , There is a function:

` public func login(completionHandler: (AnyObject, NSError) -> Void)`

I think the parameters it should be optional type like this:

` public func login(completionHandler: (AnyObject?, NSError?) -> Void)`

![2016-08-07 11 40 03](https://cloud.githubusercontent.com/assets/5554127/17460334/c095f950-5c93-11e6-93b2-236546b2077b.png)

I think this is the same kind of issue with this one:

[NSError is imported as non-optional in swift in didCompletePasswordAuthenticationStepWithError](https://github.com/aws/aws-sdk-ios/issues/433)

**Comment by karthiksaligrama** [comment]
fixed. You can find the mobile hub code in this repo [aws/aws-mobilehub-helper-ios](https://github.com/aws/aws-mobilehub-helper-ios)
