### ISSUE TITLE
Why are pre signed urls capped at 7 days?

### ISSUE THREAD

**Issue by msencenb** [aws/aws-sdk-ios#445]
I'm upgrading from a very old iOS SDK, in which pre-signed urls did not have a max expiration date. My app prints photos, so I hand off pre-signed urls to my printing partner who sometimes has to issue re-prints etc, which inevitably take longer than 7 days (previously, I've had it set to 6 months). 

I like the fact that I hand out urls, but my printing partner doesn't have access to them forever, which keeps my users photos private. Pre signed urls seem to match this use case nicely minus the short expiration date. Is it possible to create pre signed urls without that seven day cap? If not, do you have suggested workarounds?

**Comment by karthiksaligrama** [comment]
The Pre-signed url is signed with a cognito credentials which expire after an hour. one option is you could generate pre-signed urls on the server side which can have potentially greater expiration duration. another option is to ask you printing partner to cache the image locally so that its available to him when ever he needs.

**Comment by msencenb** [comment]
Thanks for the answer. Unfortunately the Ruby SDK also throws an exception for any duration over seven days. At this point I'm probably just going to send my printing partner a cloudfront url instead of the raw s3 url. Security by obscurity is not ideal, but it's the use case that matches my current business needs best. 

Anyways, I do enjoy that amazon takes security seriously as evidenced by the cognito work, and ephemeral access keys. Unfortunately it's just a little too secure to be useful for me at the moment.
