### ISSUE TITLE
AWSMobileAnalyticsService hard-coded to East1 Region / causes issues with user pools in other regions

### ISSUE THREAD

**Issue by mnolanjr98** [aws/aws-sdk-ios#448]
I have a managed user pool and federated identity pool in the West2 region.  When attempting to integrate both Cognito Identity Management and Mobile Analytics in the same application - I am only able to get one or the other.  The code listed below appropriately authenticates / registers users tied to pools in West 2.  However, when the analytics attempt to send, the AWSMobileAnalyticsService seems to try to configure the AWSCognitoIdentityManager to the East1 region.  If I rearrange the code below such that the credentialsProvider is not set to nil during instantiation of AWSServiceConfiguration, then analytics work but all actions regarding authentication and user creation stop working.  The Constants.* references are static constants for the actual configuration values.

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        AWSLogger.defaultLogger().logLevel = AWSLogLevel.Verbose
        
        let DefaultServiceRegionType = AWSRegionType.USWest2
        
        let serviceConfiguration = AWSServiceConfiguration(
            region: DefaultServiceRegionType,
            credentialsProvider: nil)
        
        // Needed to support account registration
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = serviceConfiguration
        
        let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: Constants.ClientIdAuth, clientSecret: Constants.ClientSecretAuth, poolId: Constants.PoolId)
        
        let poolKey = Constants.UserPoolName
        
        AWSCognitoIdentityUserPool.registerCognitoIdentityUserPoolWithConfiguration(serviceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: poolKey)
        
        let pool = AWSCognitoIdentityUserPool(forKey: poolKey)
        pool.delegate = self
        
        let analytics = AWSMobileAnalytics(forAppId: Constants.AnalyticsAppId, identityPoolId: Constants.CognitoIdentityPoolId)
        
        return true
    }

**Comment by rohandubal** [comment]
Hi, instead of using 

`AWSMobileAnalytics(forAppId: Constants.AnalyticsAppId, identityPoolId: Constants.CognitoIdentityPoolId)`

I would recommend using 

`AWSMobileAnalytics(forAppId: Constants.AnalyticsAppId, configuration: serviceConfiguration)`

which uses the SDK service configuration which contains credential provider.

**Comment by mnolanjr98** [comment]
This path doesn't work for me.  The way my service configuration is setup, the credentialsProvider is nil.  If I change things to have it not nil, then authentication & user registration through Cognito fails.

Everything works as I have it coded if I am in the East1 region.  The code really shouldn't be hardcoding a region, or if it's going to, there should at least be an alternative to change it.

**Comment by rohandubal** [comment]
We will update the thread once we have a fix for this. Thanks.

**Comment by rohandubal** [comment]
Hi mnolanjr98,

Is there a reason why you are setting the credential provider as nil? You could set the credential provider as the user pools credential provider and it should work fine.

Thanks,
Rohan

**Comment by mnolanjr98** [comment]
The sample code in GitHub shows this as being set to nil, so I followed that.

I did try models where I set the credential provider, but all authentication in the application stopped working.  What is the actual class name of the User Pool Credentials Provider?  Maybe I was using the class - I'm pretty sure it was the default credentials provider.

**Comment by karthiksaligrama** [comment]
we have deprecated this api in the latest release. Specifying the identity pool id is not the right way of initializing any service. You should always use a credentials provider instead. 

For setting up user pools you can use

```
AWSCognitoIdentityUserPoolConfiguration *configuration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:@"CLIENT_ID"
                                                                                                              clientSecret:@"CLIENT_SECRET"
                                                                                                                    poolId:@"USER_POOL_ID"];
[AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration userPoolConfiguration:configuration forKey:@"UserPool"];
AWSCognitoIdentityUserPool *pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];
```


For more details visit https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-ios-sdk.html

**Comment by mnolanjr98** [comment]
I'm sorry, but your answer is totally confusing, and doesn't even get to my original complaint in this defect.  Is this the deprecated part you refer to -
    let DefaultServiceRegionType = AWSRegionType.USWest2

    let serviceConfiguration = AWSServiceConfiguration(
        region: DefaultServiceRegionType,
        credentialsProvider: nil)

Because this was my original point - your code has the region hard-coded inside the AWSServiceConfiguration (unless this was changed in 2.4.9).  I haven't checked it out yet, but your answer gave no indication that this is what you were addressing (and was my original problem).

Next, the code snippet you pasted is the objective-c equivalent of what I posted originally so I don't get why you are commenting on how I need to do something differently, when it is the same as what I posted.

When you say I shouldn't use the identity pool id to initialize a service, are you referencing the AWSMobileAnalytics service initialization?  This is the only one where I am passing an identity pool id, and I'm pretty sure I tried the other initializers and none of them worked properly.  I guess I'll try again, but please clarify.

**Comment by mnolanjr98** [comment]
And if you are referencing my initialization of the AWSMobileAnalytics, please provide a reference.

**Comment by karthiksaligrama** [comment]
yes, i was talking about the usage of identity pool id directly in the constructor.

I'm updating the code you posted with changes for user pool for your reference

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
   // Override point for customization after application launch.
   AWSLogger.defaultLogger().logLevel = AWSLogLevel.Verbose

    let DefaultServiceRegionType = AWSRegionType.USWest2

   let userPoolServiceConfiguration = AWSServiceConfiguration(
        region: DefaultServiceRegionType,
        credentialsProvider: cognitoIdentity)

    let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: Constants.ClientIdAuth, clientSecret: Constants.ClientSecretAuth, poolId: Constants.PoolId)

    let poolKey = Constants.UserPoolName
    AWSCognitoIdentityUserPool.registerCognitoIdentityUserPoolWithConfiguration(userPoolServiceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: poolKey)

    let pool = AWSCognitoIdentityUserPool(forKey: poolKey)

    pool.delegate = self

   let cognitoIdentity = AWSCognitoCredentialsProvider(regionType: DefaultServiceRegionType, identityPoolId: "######", identityProviderManager:pool)

   let serviceConfiguration = AWSServiceConfiguration(
        region: DefaultServiceRegionType,
        credentialsProvider: cognitoIdentity)

   AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = serviceConfiguration

   let analyticsConfiguration = AWSMobileAnalyticsConfiguration();

   let analytics = AWSMobileAnalytics(forAppId: Constants.AnalyticsAppId, configuration:analyticsConfiguration)

   return true
}
```

**Comment by mnolanjr98** [comment]
This code won't compile, and get's into a chicken or the egg scenario (which comes first?).

The way you are initializing the instance of cognitoIdentity is well after you pass it into the constructor when creating the object assigned to userPoolServiceConfiguration.  So the first inclination is to move this to a point prior to initialization of the userPoolServiceConfiguration instance - but then you need to create the instance of AWSCongnitoIdentityUserPool assigned to the pool variable.  And this begins a total cascade of things to be shifted around.  And everything I've tried doesn't end up with both authentication and analytics working cohesively (when using User Pools - I haven't tried any other authentication provider).

Does AWS have a working sample with User Pools and Mobile Analytics working together?  Seeing they are part of the the cohesive Mobile Hub, I am assuming so.  It would be nice to see what that looks like.

**Comment by karthiksaligrama** [comment]
you can set `AWSAnonymousCredentialsProvider` for your `userPoolServiceConfiguration`
