### ISSUE TITLE
CodeDeliveryDetails is null for ForgotPassword/ConfirmForgotPassword

### ISSUE THREAD

**Issue by akamud** [aws/aws-sdk-ios#452]
Similar to awslabs/aws-sdk-ios-samples#95, I am getting `null` from `response.codeDeliveryDetails` after the task continuation for ForgotPassword and ConfirmForgotPassword. I can see from the logs that the response is coming in correctly, but the object is never populated.

I managed to fix this by doing what was instructed in the issue mentioned above, since the problem is just in the parsing/filling of the object. I noticed many of the methods are missing the required code to work correctly.

From my understanding this code is missing in those methods:

```
[response aws_copyPropertiesFromObject:task.result];
```

Examples:
https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L91
https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#77

I suggest going through the methods again and adding all the missing calls.

**Comment by yishafang** [comment]
Thanks for pointing out, we will try to fix it for the next release of the SDK.

**Comment by behrooziAWS** [comment]
Apologies for not following up here.  This was fixed in 2.4.8 released 9/12/2016.
