### ISSUE TITLE
AWSS3TransferUtility uploads not working, but AWSS3TransferManager working

### ISSUE THREAD

**Issue by emjoseph** [aws/aws-sdk-ios#454]
I'm using AWSCore (2.4.7) and AWSS3 (2.4.7) via Cocoapods. Running on an iPhone 6 (9.3.4)

I've set up the AWSS3TransferUtility code exactly as you've shown in your examples and the upload never starts. The progress block and completion handler are never called, and no errors or exceptions are found in the **AWSS3TransferUtility.defaultS3TransferUtility().uploadFile** method

I should add that AWSS3TransferManager is working perfectly though.

Is there something missing from your examples/documentation on how to get the AWSS3TransferUtility working?

**Comment by emjoseph** [comment]
Figured it out by delving through trial and error and some inspiration from the AWS forums. Apparently AWSS3TransferUtilityManager doesn't work with buckets that have special characters in their names (in my case a dash). Frustrating because this wasn't a problem with the AWSS3TransferManager.

**Comment by sshilko** [comment]
Same issue, cant use bucket with dashes

**Comment by muellerfr** [comment]
Hi @sshilko,

sorry your running into a problem. Please create a new [bug report ](https://github.com/aws-amplify/aws-sdk-ios/issues/new?template=bug_report.md) with details such as SDK version, OS version. etc.
