### ISSUE TITLE
CognitoIdentityUser - confirm user at later date?

### ISSUE THREAD

**Issue by iussef** [aws/aws-sdk-ios#455]
Right after a sign up, calling user.confirmSignUp works perfectly. However, sometimes a user may sign up to my app, then instead of entering their confirmation code close the app and come back at a later date. In these cases, I try to confirm the user by using pool.currentUser().confirmSignUp, but the app crashes and doesn't let me confirm the user - it seems as though its only possible to confirm a user received directly as a result of sign up. 

Is there any solution to this/am i getting the user incorrectly by calling pool.currentUser? Thanks :)

**Comment by behrooziAWS** [comment]
currentUser won't have a username set unless you have successfully signed in once.  Have you tried using the getUser api with the signed up user name and calling confirmUser on that?  You should be able to call confirm user at any time as long as you have a valid username with your AWSCognitoIdentityUser object.

**Comment by iussef** [comment]
Thanks for the quick help - I've just implented that, but my users don't have a username, just an email address (which is an alias). When i print pool.getUser("emailaddress") it always returns a user, even if I enter an email that isn't a user at all. What's happening?

**Comment by behrooziAWS** [comment]
One of the parameters to signUp is username so you should always have a username.  getUser:username doesn't actually make a call to the service, it just returns a user object with the username set to whatever you provided.  If you call confirmSignUp on a user object with a valid username, it will succeed, otherwise it will return an error.

**Comment by iussef** [comment]
Perfect - I was assuming setting email as alias automatically made it equivalent to username, and was then setting the username as a random string. I changed it to set the username as the email too, and pool.getUser works for confirming the sign up.

Greatly appreciate the help from you both.
