### ISSUE TITLE
Resume functionality for iOS 

### ISSUE THREAD

**Issue by bhartiios** [aws/aws-sdk-ios#456]
I'm uploading a file of size 20MB on AWS server. Due to some reason, uploading failure after 50% uploading or user terminates the app. So after failure, I want to restart the uploading from 10MB(as 50% already done). How to do this.

Using same object of AWSS3TransferManagerUploadRequest, it starts uploading from the same point where it lefts last time but in case my app gets terminated then how would it starts from same point because I don't have any reference of AWSS3TransferManagerUploadRequest object.
I'll create new object of AWSS3TransferManagerUploadRequest & starts uploading, it will starts from 0MB.

Please suggest.

**Comment by bhartiios** [comment]
Any solution to start the uploading from the same point where it stopped in last session due to some failure. 
Please respond asap.

**Comment by rohandubal** [comment]
Hello @bhartiios 

Apologies for the delayed response. You could use `AWSS3TransferUtility` available in the iOS SDK to achieve your use case. It will resume your upload when the application is launched, in case the app is killed manually / by iOS. For documentation please refer to the following link: http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html 

Thanks,
Rohan
