### ISSUE TITLE
enumerateToAssignBlocksForUploadTask not returning all task

### ISSUE THREAD

**Issue by vipulpurohit** [aws/aws-sdk-ios#457]
Hello,
I'm trying to upload some file over s3. What I need is to get all `pending/in-progress/completed` task list when I start my iOS application.

As per the AWS S3 documentation I'm using `enumerateToAssignBlocksForUploadTask` to get the task list but I'm getting only single item in the list and If I relaunch the application other details of that single item like uploaded kb etc also become empty.

This was the link which I refereed from AWS documentation 
[ASW LINK](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html) 

Am  I doing something wrong or its an issue with the amazon s3 iOS sdk.
Please help me in this issue.

Thanks

**Comment by rohandubal** [comment]
Hello,

If the app is killed, all the upload progress / information is lost and won't be available after restart. It should be used when the app has moved to background and then returning from background to foreground. You show have a list of tasks with unique identifiers which you get when you create an upload / download task.

Thanks,
Rohan
