### ISSUE TITLE
May Be Session expiration issue.

### ISSUE THREAD

**Issue by anilappvolution** [aws/aws-sdk-ios#458]
I used aws in my iOS application. But issue is app installed in device and open stay one hour. then call any services no data retrieved. But when device connected with Xcode this issue never coming, means not able to debug this issue. because in debugging mode working perfect!!.

could you please help me on this.

Thanks in advance.

**Comment by karthiksaligrama** [comment]
Can you give more context as to what service you are using and your xcode version etc?

**Comment by anilappvolution** [comment]
Used Services :

'AWSCognito'
'AWSCognitoIdentityProvider'
'AWSDynamoDB'
'AWSEC2'
'AWSLambda'
'AWSS3'
'AWSSES'
'AWSSNS'

Xcode version : 7.3

**Comment by karthiksaligrama** [comment]
is there a way i can reproduce the problem?
