### ISSUE TITLE
Carthage: Compiling AWS SDK iOS is slow: Allow selective compilation

### ISSUE THREAD

**Issue by thebugcode** [aws/aws-sdk-ios#459]
Currently, we have to wait around 5 minutes for compiling aws-sdk for iOS. We only need 1 of the many frameworks aws-sdk for iOS contains. Something should be done to speed up compilation times and allow users of the sdk to pick and choose what frameworks they need.

**Comment by karthiksaligrama** [comment]
@thebugcode are you talking about carthage build?

**Comment by thebugcode** [comment]
Exactly :)

**Comment by karthiksaligrama** [comment]
I think we can include prebuilt frameworks as part of release so carthage doesn't have to build the sdk.

**Comment by esetnik** [comment]
Hitting the same issue. Takes me around 15 min locally to compile the aws sdk components with carthage and ~40 min on circle ci. I think the best solution is some sort of sub-repository specification support in carthage. It could work like subspecs in Cocoapods but use various workspaces to define which modules are built. This is by no means an issue exclusive to `aws-sdk-ios` but this project has an especially high component count.

For example:
`github "aws/aws-sdk-ios" ~> 2.4` could become `github "aws/aws-sdk-ios/AWSS3" ~> 2.4`

**Comment by victusfate** [comment]
also if you guys could package the binaries that'd be awesome. thanks to @marcvanolmen for mentioning this.
https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by lightsprint09** [comment]
Is there some progress in providing prebuild  frameworks for carthage?

**Comment by lauracalinoiu** [comment]
How are you all dealing with such an incredible time for building `aws sdk` on CI, on production code - with Carthage?
@thebugcode, you opened the issue on September, 2016. 
Have you found any solution to this?

**Comment by thebugcode** [comment]
Hi Laura,
 I update dependencies individually and avoid updating all of them because of aws sdk. 
Here is how to update specific dependencies instead of all of them :
http://thebugcode.github.io/how-to-update-a-single-dependency-using-carthage/

**Comment by lightsprint09** [comment]
@lauracalinoiu We use carthage feature `--cache-builds` and cache Carthage/build

**Comment by lauracalinoiu** [comment]
@thebugcode, thank you for your extreme quick response. 
I need the builds to run fast on Buddy Build. 
The Carthage command line that is used on BuddyBuild is:
` carthage bootstrap --platform ios --no-use-binaries --verbose`, I do not know how to use it just on some of the libraries. 


@lightsprint09, I do not know yet how to use `--cache-builds` Carthage option in BuddyBuild. Is it possible?

**Comment by vccabral** [comment]
I know this is an old thread but I am searching for compilation instructions. Does anyone have those?

**Comment by AndreyPoznyak** [comment]
are there any updates on the this issue guys?
it takes 20 mins for my Mac Pro to compile whole aws-sdk-ios (2.6.30) when I need only 1 library :)
if there are some improvements - what version can be used please?

**Comment by ObjColumnist** [comment]
@AndreyPoznyak I am using 2.6.1 with Carthage and it just downloads the prebuilt libraries for that, changed a few months ago.

You might not be/want to use Carthage so might not help, but is a possible solution.

**Comment by palpatim** [comment]
As @ObjColumnist pointed out in their answer above, we do pre-build binaries, which should greatly reduce local compilation times. Unfortunately, without restructuring the package into git submodules (each of which would require its own Github repo), we can't support individual SDK compilation.
