### ISSUE TITLE
2.4.8 Not compiling with Xcode8GM

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#460]
/redacted/Pods/AWSS3/AWSS3/AWSS3RequestRetryHandler.h:16:9: 'AWSURLRequestRetryHandler.h' file not found

Using the following 
```
 pod 'AWSCore'
    pod 'AWSS3'
    pod 'AWSCognito'
    pod 'AWSMobileAnalytics'
```

**Comment by esetnik** [comment]
+1 same issue as above. I reverted to 2.4.7 and it's working correctly.

**Comment by rromanchuk** [comment]
revert to `2.4.7` working fine for me as well. Didn't have time to do any investigating unfortunately.

**Comment by karthiksaligrama** [comment]
Related to #462

**Comment by lfarah** [comment]
I reverted and still had problems....

**Comment by puttputt** [comment]
Updating cocoapods to the latest version and including the pods under target 'xxx' do - resolved for me.

**Comment by lfarah** [comment]
@puttputt what is target 'xxx'? Can you post your Podfile here?

**Comment by gsabran** [comment]
I'm using
```
pod 'AWSS3', '2.4.7'
```

And it works fine in xcode 8

**Comment by aksswami** [comment]
Encountered the same issue. Reverting back to `2.4.7`.

**Comment by zfisher323** [comment]
I encountered the same issue even in xcode 7.3.1 - perhaps 2.4.8 isn't ready for primetime? - downgrading to 2.4.7 has resolved the issue for now

**Comment by LamourBt** [comment]
I have use cocoapods for the installation, I update the pod after the installation to 2.4.8 on IOS 10 swift 3.0. I create the bridge folder and import  `#import <AWSCore/AWSCore.h>`
`#import <AWSCognito/AWSCognito.h>`. It refused to work

![screen shot 2016-09-18 at 7 44 40 pm](https://cloud.githubusercontent.com/assets/14245117/18620037/7bd5af84-7dd8-11e6-861c-66ce2972cbc4.png)

**Comment by mitchellporter** [comment]
I was able to fix this issue by updating `cocoapods` to version `1.0.1`. If you're still having trouble after updating, try uninstalling `cocoapods` and then doing a fresh install.

AWS pods are now working for me just fine using `Xcode 8` with `Swift 2.3`

**Comment by LamourBt** [comment]
@gsabran are you still have the problem ?

**Comment by esetnik** [comment]
i'm experiencing the same issue using swift 3 / cocoapods 1.1.0.rc.2

**Comment by gsabran** [comment]
@LamourBt as I said, I reverted to `2.4.7` and things are fine `2.4.8` was not working.

**Comment by patgoley** [comment]
This is fixed if you replace the import in AWSS3RequestRetryHandler.h with the following:

replace: 
`#import "AWSURLRequestRetryHandler.h"`

with:
`#import <AWSCore/AWSURLRequestRetryHandler.h>`

This worked for me at least. Happy to submit a PR if this fixes works for other setups too (Carthage).

**Comment by esetnik** [comment]
@patgoley https://github.com/aws/aws-sdk-ios/pull/462

**Comment by LamourBt** [comment]
@karthiksaligrama Thank you for the new update 2.4.9 is working fine so far
