### ISSUE TITLE
UserPools sign in does not work in Xcode 8 simulator

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#463]
Running on the device it works fine, but in the simulator it never signs the user in?

**Comment by BruceBuckland** [comment]
A workaround.

@helloniklas i also found that my userpools signin was not working in Xcode 8, when I look in the logs and search for security I find some security errors (OSStatus error: [-34018] Security error has occurred.).  I think those are related to the use of Keychains by the AWS libraries, and I resolved the errors and fixed the login by enabling keychain sharing (Your App-> select Target -> Capabilities -> Keychain Sharing.

I don't think there is any keychain sharing, but that's what I did.  I think this may be related to IOS10

**Comment by behrooziAWS** [comment]
We've been watching these threads: https://forums.developer.apple.com/thread/4743?start=90&tstart=0 https://forums.developer.apple.com/message/179846#179846 so far it appears to be an Apple issue and we've had success enabling Keychain Sharing.
