### ISSUE TITLE
UserPool and Cognito sign out not working

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#464]
If I sign in with a user, then sign out and attempt to sign in with a different user without quitting the app in between, it does still think it's the previous user.

What else do I need to do to properly clear everything in the keychain etc.

I'm doing.
```

        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .usEast1, identityPoolId: Constants.identityPoolId, identityProviderManager:pool)
        credentialsProvider.clearCredentials()
        credentialsProvider.clearKeychain()

        let pool = AWSCognitoIdentityUserPool(forKey: "UserPool")
        let user = pool?.currentUser()
       user?.signOut()
```

**Comment by behrooziAWS** [comment]
> does still think it's the previous user

After you've signed out, you will no longer have an active session and will need to sign in again.  If you are still seeing the user as signed in, then you are signing back in somewhere in your code.  If instead you are referring to the SDK remembering the last known user,  you can call pool?.clearLastKnownUser() to forget them.

**Comment by behrooziAWS** [comment]
Also, you should use a singleton for your credentialsProvider just like you are doing with your user pool with register and forKey, if you are instantiating it whenever you want to use it, the behavior is not guaranteed.

**Comment by helloniklas** [comment]
Ok thanks, this works now.
