### ISSUE TITLE
While pod update AWS SDK 2.4.0

### ISSUE THREAD

**Issue by YDobariya** [aws/aws-sdk-ios#465]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `Info.plist` or set `defaultServiceConfiguration` before using this method.'

**Comment by karthiksaligrama** [comment]
this is not an error. You need to configure the defaultServiceConfiguration in your ServiceManager or set the info.plist on your app with the service configuration.
