### ISSUE TITLE
Not able to use AWSS3 in swift project

### ISSUE THREAD

**Issue by sajeeshes** [aws/aws-sdk-ios#467]
I was trying to integrate AWSS3 framework in my swift project
Integrated AWS library using cocoa pods.
Application is building fine after the cocoa pod integration 
When i was trying to import AWSS3 in my swift class I am getting following errors
1. Could not build Objective-C module 'AWSS3'
2. 'AWSURLRequestRetryHandler.h' file not found
I have used  use_frameworks! in my pod file for making bridging
Can anyone suggest a solution for this?

**Comment by mrdavidrees** [comment]
I'm not sure why, but to achieve temporary fix you can change the line to
```
#import <AWSCore/AWSURLRequestRetryHandler.h>
```

**Comment by karthiksaligrama** [comment]
Fixed with 2.4.9

**Comment by sajeeshes** [comment]
Its working fine with 2.4.9
Thank you all
