### ISSUE TITLE
Tasks running in AWSS3TransferUtility do not call completion with error when no bucket name is supplied

### ISSUE THREAD

**Issue by mrdavidrees** [aws/aws-sdk-ios#469]
Whilst fixing an issue where I didn't set a bucket name, I found that tasks would never complete, both not calling the completionHandler or setting to finished, the task will be continuously in the executing state and will stay alive in any queues that it is running in. 

I believe the issue exists deeper in 
```
[[self.preSignedURLBuilder getPreSignedURL:getPreSignedURLRequest]
```

but the only way I could see this issue was by breaking on

```
- (AWSTask *)continueWithExecutor:(AWSExecutor *)executor
                    successBlock:(AWSContinuationBlock)block
               cancellationToken:(AWSCancellationToken *)cancellationToken {
    if (cancellationToken.cancellationRequested) {
        return [AWSTask cancelledTask];
    }

    return [self continueWithExecutor:executor block:^id(AWSTask *task) {
        if (task.faulted || task.cancelled) {
            return task; //Breakpoint
        } else {
            return block(task);
        }
    } cancellationToken:cancellationToken];
}

```

where there task would fault but no errors were ever logged or provided.

I am using 2.4.5

**Comment by karthiksaligrama** [comment]
fixed with 2.4.10
