### ISSUE TITLE
How to use Cognito and User Pool auth in Notification Service Extension

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#471]
So I need to be in auth mode and be able to call Lambda functions from my Notification Service extension in iOS10.

How is this easiest achieved? Do I need to do the whole login etc from the extension. Or could I just share the auth tokens in a shared keychain group then somehow use this and sign the request in the extension with these, without having to login the user from the extension again?

**Comment by kredden** [comment]
Cleaning up old issues.  Did you ever get this working?
