### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by adiki** [aws/aws-sdk-ios#477]
I'm using AWSS3TransferManager to upload data to S3. I encounter following crash:

Fatal Exception: NSInvalidArgumentException
*** -[NSConcreteData initWithBytes:length:copy:deallocator:]: absurd length: 18446744073709551615, maximum size: 9223372036854775808 bytes

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1846301c0 __exceptionPreprocess
1  libobjc.A.dylib                0x18306855c objc_exception_throw
2  CoreFoundation                 0x184630108 -[NSException initWithCoder:]
3  Foundation                     0x18502b29c -[NSConcreteData initWithBytes:length:copy:deallocator:]
4  Foundation                     0x1850233ec -[_NSPlaceholderData initWithBytes:length:copy:deallocator:]
5  Foundation                     0x18502b1e8 +[NSData(NSData) dataWithBytesNoCopy:length:]
6  AWSCore                        0x10048f018 -[AWSS3ChunkedEncodingInputStream nextChunk] (AWSSignature.m:657)
7  AWSCore                        0x10048f7f8 -[AWSS3ChunkedEncodingInputStream read:maxLength:] (AWSSignature.m:706)
8  CFNetwork                      0x184e3299c HTTPTransaction::RequestBodyStream::_bufferRequestBodyFromStream_offqueue()
9  libdispatch.dylib              0x1834b91c0 _dispatch_client_callout
10 libdispatch.dylib              0x1834c4b24 _dispatch_block_invoke_direct
11 CFNetwork                      0x184e4ae98 RunloopBlockContext::_invoke_block(void const*, void*)
12 CoreFoundation                 0x1845099a8 CFArrayApplyFunction
13 CFNetwork                      0x184e4ad7c RunloopBlockContext::perform()
14 CFNetwork                      0x184e4c0a4 MultiplexerSource::perform()
15 CFNetwork                      0x184e4be10 MultiplexerSource::_perform(void*)
16 CoreFoundation                 0x1845de278 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
17 CoreFoundation                 0x1845ddbc0 __CFRunLoopDoSources0
18 CoreFoundation                 0x1845db7c0 __CFRunLoopRun
19 CoreFoundation                 0x18450a048 CFRunLoopRunSpecific
20 CFNetwork                      0x184cf7cec +[NSURLConnection(Loader) _resourceLoadLoop:]
21 Foundation                     0x18511650c __NSThread__start__
22 libsystem_pthread.dylib        0x1836c3860 _pthread_body
23 libsystem_pthread.dylib        0x1836c3770 _pthread_body
24 libsystem_pthread.dylib        0x1836c0dbc thread_start

**Comment by rohandubal** [comment]
Hi,
Could you please answer the following questions?
-What is the SDK version you are using?
-What is the file size of the file you are trying to upload?
-Are there any steps to reproduce this error?

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
assuming this is fixed. Closing the issue. Please open a new one if the problem persists
