### ISSUE TITLE
Subscribe to IoT Lifecycle events

### ISSUE THREAD

**Issue by mmadjer** [aws/aws-sdk-ios#478]
How can I subscribe to lifecycle events?

I tried it this way but no luck by #using the IoTSimpleSwift project.

```
let iotDataManager = AWSIoTDataManager.defaultIoTDataManager()
iotDataManager.subscribeToTopic("$aws/events/#", qoS: .MessageDeliveryAttemptedAtMostOnce) { (payload) in
            
        }
```

My policy is defined as follow:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:region:account:client/${iot:ClientId}"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topic/201657"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topicfilter/201657"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topicfilter/$aws/events/*"
      ]
    }
  ]
}
```

The MQTT Client on the AWS IoT site is receiving lifecycle events when subscribed to `$aws/events/#` but not within the app.

Thanks in advance.

**Comment by fengsongAWS** [comment]
Hi @mmadjer ,

Thanks for interest in AWS IoT Device SDK.

Are you using cognito or pkcs12 ? If you use cognito, please make sure you linked the cognito with IAM policies which allow FullIoTAccess for unauthenticated devices. If using pkcs12, I would suggest to try allowing access to 'iot:*' first and see if it works. 

Did you attach this policy to your Application, which supposed to be filled in Constaints.swift? 
Pleases double check you have the correct region associated with the Policy and region in file Constants.swift.
Also, just to make sure that the region and account in your Policy document such as, `"arn:aws:iot:region:account:topicfilter/$aws/events/*",` should be filled corresponding to your AWS IoT account information.  

Please feel free let us know if you still have problems.

Thanks,
Fengyi

**Comment by mmadjer** [comment]
Hi @fengsongAWS ,
Thanks for the quick response.

I did all that and I initially used pkcs12 and tried cognito afterwards, also no success.

However, I just now found the issue which is in the policy document.
I applied the Lifecycle events policy as described here [(http://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html)].

```
{
    "Version":"2012-10-17",
    "Statement":[{
        "Effect":"Allow",
        "Action":[
            "iot:Subscribe",
            "iot:Receive"
        ],
        "Resource":[
            "arn:aws:iot:region:account:topicfilter/$aws/events/*"
        ]
    }]
}
```

Here the resource is _topic filter ARN_ which applies to _iot:Subscribe_ whereas _iot:Receive_ needs _topic ARN_.
So by changing from the above to the foloowing policy I get the lifecycle events now.

```
{
    "Version":"2012-10-17",
    "Statement":[{
        "Effect":"Allow",
        "Action":[
            "iot:Subscribe"
        ],
        "Resource":[
            "arn:aws:iot:region:account:topicfilter/$aws/events/*"
        ]
    },
{
        "Effect":"Allow",
        "Action":[
            "iot:Receive"
        ],
        "Resource":[
            "arn:aws:iot:region:account:topic/$aws/events/*"
        ]
    }]
}
```

**Comment by fengsongAWS** [comment]
It's great to hear that your problem has been resolved. Maybe this would be a good example for people who have similar confusion. Feel free to post any questions you have in the future and thanks for your interest again in the AWS IoT SDK.

Thanks,
Fengyi
