### ISSUE TITLE
Configuring Credentials in Amazon s3 iOS SDK 2.4.9

### ISSUE THREAD

**Issue by Ajmal-M-A** [aws/aws-sdk-ios#479]
I try to test the upload functionality in Amazon S3 sdk 2.4.9 Using [The Amazon S3 TransferManager Sample .](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferManager-Sample/Objective-C)

In the project where I need to configure the S3 Credentials like RoleARN and AccountID?

What type of data I need to fill in Constants.m and S3TransferManagerSample-Info.plist with variable names?

I got the following the Error after setting the Buketname,Poold and Region.

`AWSCognitoCredentialsProvider credentials]_block_invoke352 | Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=5 "(null)" UserInfo={__type=InvalidIdentityPoolConfigurationException, message=Invalid identity pool configuration. Check assigned IAM roles for this pool.}]
`
Please help me run the sample.

**Comment by mlshon** [comment]
Did you follow the directions in the README? It tells you the data that needs to be filled.
Also, can you confirm:
1) You enabled Unauthenticated identities
2) The identity pool id listed in your trust relationships matches the identity pool you are using

You can also use AWS Mobile Hub to generate and download a working sample app.

**Comment by karthiksaligrama** [comment]
assuming resolved. Closing
