### ISSUE TITLE
Cannot create empty folder with AWS S3 SDK 2.4.9

### ISSUE THREAD

**Issue by windyit08** [aws/aws-sdk-ios#480]
AWSS3 *s3 = [AWSS3 defaultS3];
    
    AWSS3PutObjectRequest *putObjectRequest = [AWSS3PutObjectRequest new];
    
    putObjectRequest.key = @"test/";
    putObjectRequest.bucket = testBucketNameGeneral;
    putObjectRequest.body = nil;
    
    [[[s3 putObject:putObjectRequest] continueWithBlock:^id(AWSTask *task)
     {
         XCTAssertNil(task.error, @"The request failed. error: [%@]", task.error);
         return nil;
     }] waitUntilFinished];

>>> I make sure that the / character is added at the end of the key but a empty folder [test] was not created, it's a file with content type "binary/octet-stream"
>>> Some keys I tried:   "a/b/"   "a/b/"  => Not OK
>>> After that, I downgraded AWS S3 SDK to 2.3.6 and it's OK, my code woking!

Please check and fix it.
Thanks and Regards,
Phong

**Comment by karthiksaligrama** [comment]
thanks for reporting, looking into this now.

**Comment by karthiksaligrama** [comment]
Fixed with 2.4.10
