### ISSUE TITLE
Custom Credential Provider Issue - Swift2.2 , AWS 2.4.9, AWSCredentials AWSCredentialsProvider 

### ISSUE THREAD

**Issue by Bhat123** [aws/aws-sdk-ios#481]
Hi All,

 I am creating the custom credential provider so that i can set accesskey , secretkey , token and expiration however i am receiving the below error while uploading the file 
**[__NSCFString expiration]: unrecognized selector sent to instance**

Below is the Custom class i have created using Swift 2.2 .. Kindly help me here in resolving the above issue 

### 
_```
import AWSS3
import AWSCore.AWSCredentialsProvider
class MYAWSCredentialProvider:AWSCredentials, AWSCredentialsProvider{
    var bucketName:String!
    var token:String!
    var awsAccessKey: String!
    var awsSecretKey: String!
    var awsExpiration: NSDate?
    var awsRegion:String!
    
    static let sharedInstance = MYAWSCredentialProvider(accessKey: "", secretKey: "", sessionKey: "")
    
    @objc func logins() -> AWSTask {
        return AWSTask(result: token)
    }

     init(accessKey: String, secretKey: String, sessionKey: String?) {
        super.init()
        self.token = sessionKey
        self.awsAccessKey = accessKey
        self.awsSecretKey = secretKey
    }
    private static func sharedInstanceWith(accessKey: String, secretKey: String, sessionKey: String) -> MYAWSCredentialProvider {
        let instance = MYAWSCredentialProvider.sharedInstance
        instance.token = sessionKey
        instance.awsAccessKey = accessKey
        instance.awsSecretKey = secretKey
        return instance
    }
     func updateAWSInfo (jsonString: JSON) {
         awsAccessKey               = jsonString["accessKey"].stringValue
         awsSecretKey               = jsonString["secretKey"].stringValue
         bucketName                 = jsonString["bucketName"].stringValue
         awsRegion                     = jsonString["region"].stringValue
         token                      = jsonString["token"].stringValue
        let expirationTime         = jsonString["expirationTime"].stringValue
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "E MMM d HH:mm:ss 'UTC' YYYY"////Fri Sep 30 14:42:53 UTC 2016
        let date = dateFormatter.dateFromString(expirationTime)
        awsExpiration      =  date
        let credentialsProvider = MYAWSCredentialProvider.sharedInstanceWith(awsSecretKey, secretKey: awsSecretKey, sessionKey: token)
        let configuration = AWSServiceConfiguration(region:AWSRegionType.APSoutheast1, credentialsProvider:credentialsProvider)
        configuration.maxRetryCount = 3;
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration
    }
    @objc func credentials() -> AWSTask {
        return AWSTask(result: token)
    }
     func invalidateCachedTemporaryCredentials(){
        
    }
}
```_

**Comment by karthiksaligrama** [comment]
i'm not sure whats your use case for going with custom credential provider and setting access keys and secret. Can you elaborate on that? The best practice on mobile is always to use Cognito Identity and set IAM policy on AWS resource access.

**Comment by Bhat123** [comment]
We get credential information from our local host server through Web service call. It is keep on expiring in 30 min of time. Hence i created custom credential provider.  Suggest if this does not make sense

**Comment by karthiksaligrama** [comment]
couple of things i notice.
* You are not setting expiration token anywhere 
* Your AWSTask result for `credentials()` function is returning a token value, and not the entire credentials.
* You seem to be implementing `AWSIdentityProviderManager ` interface (though you have not declared it

here is what i would change your code to 

```
import AWSS3
import AWSCore.AWSCredentialsProvider
class MYAWSCredentialProvider: AWSCredentialsProvider{
    @objc func credentials() -> AWSTask {
       //make api call to your web service to get credentials .
       //return AWSTask(result:credentials);
    }
}

```

Let me know how it goes.

**Comment by Bhat123** [comment]
Hey , Sorry for uploading the wrong code, below is the latest one `//
//  MYAWSCredentialProvider.swift
//  MYtronic
//
//  Created by Sajeesh ES on 20/09/16.
//  Copyright © 2016 MYtronic. All rights reserved.
//

import UIKit
import SwiftyJSON
import AWSS3
import AWSCore.AWSCredentialsProvider
class MYAWSCredentialProvider:AWSCredentials, AWSCredentialsProvider{
    var bucketName:String!
    var token:String!
    var awsAccessKey: String!
    var awsSecretKey: String!
    var awsExpiration: NSDate?
    var awsRegion:String!
    
    static let sharedInstance = MYAWSCredentialProvider(accessKey: "", secretKey: "", sessionKey: "", expiration: nil)
    override init(accessKey: String, secretKey: String, sessionKey: String?, expiration: NSDate?) {
        super.init()
        self.token = sessionKey
        self.awsAccessKey = accessKey
        self.awsSecretKey = secretKey
        self.awsExpiration = expiration
    }
    private static func sharedInstanceWith(accessKey: String, secretKey: String, sessionKey: String, expiration: NSDate) -> MYAWSCredentialProvider {
        let instance = MYAWSCredentialProvider.sharedInstance
        instance.token = sessionKey
        instance.awsAccessKey = accessKey
        instance.awsSecretKey = secretKey
        instance.awsExpiration = expiration
        return instance
    }
     func updateAWSInfo (jsonString: JSON) {
         awsAccessKey               = jsonString["accessKey"].stringValue
         awsSecretKey               = jsonString["secretKey"].stringValue
         bucketName                 = "MYtronic-acs-tool"//jsonString["bucketName"].stringValue
         awsRegion                     = jsonString["region"].stringValue
         token                      = jsonString["token"].stringValue
         let expirationTime         = jsonString["expirationTime"].stringValue
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat =  "dd-MMM-yyyy HH:mm:ss"////03-Oct-2016 16:54:47
        awsExpiration = dateFormatter.dateFromString(expirationTime)
        let credentialsProvider = MYAWSCredentialProvider.sharedInstanceWith(awsAccessKey, secretKey: awsSecretKey, sessionKey: token, expiration: awsExpiration!)
        let configuration = AWSServiceConfiguration(region:AWSRegionType.APSoutheast1, credentialsProvider:credentialsProvider)
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration

    }
    @objc func credentials() -> AWSTask {
        //make api call to your web service to get credentials .
        let credentialsProvider = MYAWSCredentialProvider.sharedInstanceWith(awsAccessKey, secretKey: awsSecretKey, sessionKey: token, expiration: awsExpiration!)
        let configuration = AWSServiceConfiguration(region:AWSRegionType.APSoutheast1, credentialsProvider:credentialsProvider)
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration
        return AWSTask(result:credentialsProvider);
    }
     func invalidateCachedTemporaryCredentials(){
    }
}
`

**Comment by Bhat123** [comment]
An i want to create custom credential class where in i can update the accesskey etc.,  hence  i used AWSCredentials

**Comment by karthiksaligrama** [comment]
you are still returning the wrong type in the credentials method. It should return a AWS task with the type credentials. if you are setting the access keys then you should have something like this

```
class MYAWSCredentialProvider:AWSCredentialsProvider{
var bucketName:String!
var token:String!
var awsAccessKey: String!
var awsSecretKey: String!
var awsExpiration: NSDate?
var awsRegion:String!

override init(accessKey: String, secretKey: String, sessionKey: String?, expiration: NSDate?) {
    super.init()
    self.token = sessionKey
    self.awsAccessKey = accessKey
    self.awsSecretKey = secretKey
    self.awsExpiration = expiration
}

@objc func credentials() -> AWSTask {
   let credentials = AWSCredentials(accessKey:self.awsAccessKey, secretKey:self.awsSecretKey, sessionKey :self.token, expiration:self.awsExpiration);
    return AWSTask(result:credentials);
}

```

**Comment by Bhat123** [comment]
@Karthik Saligrama Thanks a lot this worked for me 👍

**Comment by bryanrahn** [comment]
@karthiksaligrama Your comment here: https://github.com/aws/aws-sdk-ios/issues/481#issuecomment-251219848, whats the proper way to actually do an async web service call to get auth tokens, and then return a AWSTask w/ said credentials?

**Comment by vqchau** [comment]
If anyone is looking for a basic credential provider then check out AWSStaticCredentialsProvider
