### ISSUE TITLE
AWS 2.4.9, Swift 2.2  Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2

### ISSUE THREAD

**Issue by Bhat123** [aws/aws-sdk-ios#482]
I am trying to upload the image to s3 bucket however getting the below issue, Can anybody help me here ?

[2016-10-04 10:08:11.114 MYProj[11781:106074] AWSiOSSDK v2.4.9 [Debug] AWSS3TransferUtility.m line:331 | __86-[AWSS3TransferUtility uploadFile:bucket:key:contentType:expression:completionHander:]_block_invoke | Request headers:
{
    "Content-Type" = "image/jpeg";
    "User-Agent" = "aws-sdk-iOS/2.4.9 iPhone-OS/9.3 en_US transfer-utility";
}
Upload Starting!
Failed with error
Error: Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Tue, 04 Oct 2016 09:08:19 GMT, x-amz-request-id=2F6A53E4E356E1E5, x-amz-id-2=hWjUUT4F/Oc2kUaO6JtmnURKMnGP24kyOvZZcxNlsWA90nUyNF9LyrXqQkdB83DDbvcFeVbMVAU=}
](url)

**Comment by karthiksaligrama** [comment]
can you give me more information on what exactly you trying to do? And steps to reproduce this problem?

**Comment by Bhat123** [comment]
This is fixed by having the proper AWSCredential which you mentioned earlier. Thanks @karthiksaligrama
