### ISSUE TITLE
How to use AWSMobileAnalytics and AWSMobileAnalyticsConfiguration in 2.4.9

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#483]
So, since the earlier methods has been deprecated, 

`AWSMobileAnalytics(forAppId: Constants.AmazonAnalyticsAppId, identityPoolId: Constants.CognitoIdentityPoolId)`

One would assume the docs should have been updated, but both in the Integration Steps for Mobile Analytics and in the Guide http://docs.aws.amazon.com/mobile/sdkforios/developerguide/analytics.html it still uses the deprecated method.

Since this new method AWSMobileAnalytics(forAppId: <#T##String!#>, configuration: <#T##AWSMobileAnalyticsConfiguration!#>) seems to use yet a different way of sending in a configuration, a sample would be good. I.e. how do I set up the config and send it in, so I first need to auth with user pools?

**Comment by karthiksaligrama** [comment]
Here is a way you can use User Pools and Mobile Analytics post 2.4.9. I'll get the doc updated.

```
let serviceConfiguration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: nil)

let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: "YOUR_CLIENT_ID", clientSecret: "YOUR_CLIENT_SECRET", poolId: "YOUR_USER_POOL_ID")

AWSCognitoIdentityUserPool.registerCognitoIdentityUserPoolWithConfiguration(serviceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: "UserPool")

let pool = AWSCognitoIdentityUserPool(forKey: "UserPool")

let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "YOUR_IDENTITY_POOL_ID", identityProviderManager:pool)

let serviceConfiguration = AWSServiceConfiguration(region: DefaultServiceRegionType, credentialsProvider: credentialsProvider)

let analyticsConfiguration = AWSMobileAnalyticsConfiguration()
analyticsConfiguration.serviceConfiguration = serviceConfiguration;

let analytics = AWSMobileAnalytics(forAppId: Constants.AnalyticsAppId, configuration:analyticsConfiguration)

```

**Comment by helloniklas** [comment]
@karthiksaligrama ok, so if I want to set this up in the app delegate to be able to track the sign up process as well, I can just send in let serviceConfiguration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: nil) to the analyticsConfiguration.serviceConfiguration = serviceConfiguration; 

And it will still work?

**Comment by karthiksaligrama** [comment]
i believe so cause, your deliveries will fail until you set the credential providerand you will have to reinitialize `MobileAnalytics` since the service configuration is a copy or the default Configuration.

**Comment by helloniklas** [comment]
@karthiksaligrama so you're saying after user pool sign in, I have to set this again on the analytics config?

**Comment by helloniklas** [comment]
@karthiksaligrama seems these APIs are getting flakier with every release....

**Comment by karthiksaligrama** [comment]
yes thats the case. I don't understand what you mean by "flakier", We removed the Identity Pool id from the constructor because this was not the right approach for setting a dependency on cognito. esp Now that Cognito is available on multiple regions.

We are always open to feedback if you have any.

**Comment by helloniklas** [comment]
Thanks, will try and set it again then once I have an auth user...

It seems to me this service config is set in different ways for different uses, sometimes with a singleton, sometimes with a defaultService, sometimes with register service config, on an instance class, sometime as a static, depending on how this is then is set it sometimes doesn't work properly with an auth or unauth user. For instance LambdaInvoker. Since the docs are rarely updated and different in different places, i.e. the iOS guide, the mobile hub, the dash board, this makes it hard and confusing to actually get things to work. Would be good to have a consistent way the APIs are and methods are meant to be used.

**Comment by karthiksaligrama** [comment]
`defaultConfiguration` should serve most of the sue cases and you need to use register for configurations that are specific to your a particular service.
Regarding Auth and UnAuth the SDK doesn't really take into account if the user is Auth or UnAuth  since the service doesn't care for it and as long as we have a way to get the credentials it should be good.

However i do believe there needs to be some consistency in serviceConfiguration. I'll make a note in our backlog to that effect.

**Comment by karthiksaligrama** [comment]
updated documentation - See https://github.com/awsdocs/aws-ios-developer-guide/blob/master/doc_source/analytics.rst. Would be pushed to the actual docs shortly.

**Comment by helloniklas** [comment]
Great thanks. Isn't it about time you move this to Swift now. Can't think of any other SDK that doesn't document in Swift by now.

**Comment by helloniklas** [comment]
@karthiksaligrama this new analytics does not work. I suspect it's because I have to initialise it twice, once before user is logged in and then again after, but no tracking is showing up. Will just use the old deprecated APIs as they seem to work. The docs on the dashboard are still using the old APIs.
