### ISSUE TITLE
FABKitprotocol file not found error which is a duplicate of MopubSDK

### ISSUE THREAD

**Issue by satishreddy17** [aws/aws-sdk-ios#486]
We are using AWSCore and mopubSDK frameworks in our project. The Fabric files(4 files) from the AWSCore framework are duplicate files with MopubSDK framework, which is getting an error "FABKitprotocol.h file not found error" when building. To my observation this is happening from AWSCore 2.4.0 before that we are using AWSCore 2.2.7 which is working fine. So we cross checked it and came know that the fabric files are in the new updates of AWSCore. Please help me to fix this issue.

**Comment by iwllyu** [comment]
maybe similar? https://github.com/aws/aws-sdk-ios/issues/351

**Comment by karthiksaligrama** [comment]
can you please update to latest sdk and let me know if it fixes the problem?
