### ISSUE TITLE
AWSS3TransferUtility - Uploading progress becomes zero when turn off and then on the wifi

### ISSUE THREAD

**Issue by pratibha-bhandari** [aws/aws-sdk-ios#487]
I am uploading some large files like 400 MB. When file is in progress and I turn off the wifi and then turn on, the file starts uploading from zero. It removes all previous uploading progress. I want to resume the file not restart. 

How can i do this with AWSS3TransferUtility?

**Comment by karthiksaligrama** [comment]
related to #489

**Comment by Nikolus005** [comment]
any update on this?

**Comment by kvasukib** [comment]
Hi @Nikolus005, Have you considered using enumerateToAssignBlocksForUploadTask as described in #489?
