### ISSUE TITLE
Accessing Dualstack Endpoint (IPv6 Support)

### ISSUE THREAD

**Issue by cdunkel** [aws/aws-sdk-ios#492]
My service uses an AWS S3 bucket to store read-only JSON that is then ingested by my iOS apps.  Recently I have been getting rejections from Apple based on the app not working on an IPv6-only network, in spite of the fact that I'm now running the AWS iOS SDK v2.4.8 which is past the version that [supposedly introduced IPv6 support (2.4.2)](https://aws.amazon.com/releasenotes/iOS/6543428673454214).

After some investigation I discovered that in order to use IPv6 I need to [enable dualstack - or somehow specify a dualstack bucket](https://aws.amazon.com/blogs/aws/now-available-ipv6-support-for-amazon-s3/).

However, I can't actually figure out how to do that through the iOS SDK!  There is documentation for [Java and .NET](http://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html#dual-stack-endpoints-sdks), but nothing on iOS.  Even checking out the [release notes](https://aws.amazon.com/releasenotes/iOS/6543428673454214) just links to this [blog post](https://forums.aws.amazon.com/thread.jspa?threadID=216686&tstart=0), which is about the most unhelpful thing ever.  There is also nothing mentioned about dualstack in the [iOS SDK documentation](http://docs.aws.amazon.com/AWSiOSSDK/latest/).

I feel like I'm overlooking some key piece of information, but I'm at a loss to figure out what it is at this point.

**Can someone point me in the right direction or help me figure out what I'm missing so that I can point my iOS apps to a dualstack S3 endpoint?**

If there are any questions about my implementation or AWS version please let me know and I will respond ASAP.

Thanks!

**Comment by karthiksaligrama** [comment]
we do not have support for dual stack endpoint yet. You can get around it by using custom endpoint . Here is an example

https://github.com/aws/aws-sdk-ios/blob/master/AWSS3Tests/AWSS3Tests.m#L311

**Comment by cdunkel** [comment]
@karthiksaligrama - thank you for the quick response.  I'll give this a try and see if it works in our implementation.

Is this called out somewhere in the documentation and I missed it?  If it's not documented I'd like to submit a request for that to be added somewhere, perhaps in the same place [where the Java and .NET implementations are covered](http://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html#dual-stack-endpoints-sdks), but pointing developers to the examples you referenced.

Is there some official way that I could request an update to the documentation?

Thanks!
