### ISSUE TITLE
AWSS3TransferUtility is not supporting multipart. Why?

### ISSUE THREAD

**Issue by pratibha-bhandari** [aws/aws-sdk-ios#493]
I am using aws ios sdk 2.4.9. AWSS3TransferUtility support background uploads but is not supporting multipart uploads. I want to upload multiple large files with background support and automatic pause/Resume with network reachability. Uploads are getting restart when network comes. This means that AWSS3TransferUtility is not using multipart uploads as AWSS3TransferManager uses.
Can you please suggest what I have to use to get these two functionality to work. @karthiksaligrama

**Comment by karthiksaligrama** [comment]
you could use transfer manager for multi part uploads but you will loose background uploads capability.

**Comment by jamesfzhang** [comment]
@karthiksaligrama Can you provide an example of using `AWSS3TransferManager` and multi-part uploads? The closest form of documentation I can find is [here](https://aws.amazon.com/articles/0006282245644577), but is very out of date. Thank you.

**Comment by gsabran** [comment]
This might be relevant, even if the code is not totally shown... https://medium.com/@otusweb/how-to-tame-the-aws-framework-to-upload-a-large-file-to-s3-19430d245510#.fellvgd6b

@karthiksaligrama when you say "background upload capability", do you mean that multipart upload cannot run when the app is in the background? While `AWSS3TransferUtility` can? I guess that the `AWSS3TransferManager` is different correct? Does `AWSS3TransferManager` don't handle app going getting backgrounded?

**Comment by minbi** [comment]
`AWSS3TransferManager` [documentation](http://docs.aws.amazon.com/ja_jp/mobile/sdkforios/developerguide/s3transfermanager.html).

**Comment by pratibha-bhandari** [comment]
@minbi there is no information about the multipart upload with background on this documentation. Can you please share any sample or documentation that support multipart upload with background. I need it urgently. 

It will be a great help for me.

**Comment by minbi** [comment]
Multipart part upload in the background is not currently supported. We will take your request into consideration and update this thread with any changes.

**Comment by pratibha-bhandari** [comment]
@minbi Thanks for your quick reply. I have posted this on Oct 10. Didn't get any update on this yet. Can you please tell me some approx. time of this feature implementation from your side as I have urgent requirement of this.

**Comment by pablogeek** [comment]
@minbi How is the status of this? I'm wondering if this will be available soon. Thanks

**Comment by chrisscholly** [comment]
Any update?
