### ISSUE TITLE
Logins Dictionary is Deprecated

### ISSUE THREAD

**Issue by kdbertel** [aws/aws-sdk-ios#494]
In the [Amazon Cognito Developer Guide section on external identity providers](http://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html), it indicates that you can set the `logins` property for external provider credentials.

However, on `AWSCognitoCredentialsProvider`, the `logins` dictionary is deprecated. It seems to indicate that we should use the `AWSIdentityProviderManager` protocol, but I cannot find any examples on how to do this, especially when I want to have external identity providers alongside Cognito User Pools.

The current sample for external identity providers edits the `logins` property directly, but is also running a version of the SDK that is six months old, which appears to pre-date User Pools.

Where can I find documentation/examples on how to run User Pools alongside external identity providers using the modern SDK? Or has the `logins` property been deprecated in error?

**Comment by karthiksaligrama** [comment]
related to #357 , closing and consolidating

**Comment by kdbertel** [comment]
It appears that #357 was closed without actually resolving this issue. Can it be reopened?
