### ISSUE TITLE
How to change a User Pool username and disable old username?

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#495]
So I have a User Pool set up that uses email as username, and the preferred alias enabled as well, meaning I'm able to change the email used at sign up to something else and the user is then able to sign in with the new email. However, is there a way to after this change disable the original username they sign dup with?

Suppose the users email was hacked. As it stands now the username they first signed up with can still be used to sign in with as well as they new username they changed to. This means someone could request a password reset with the old username?

**Comment by behrooziAWS** [comment]
If they request a password reset, the reset code will be sent to the current email or phone_number, not the original username.  The original username can request a password reset but it will be sent to the new location.

Normally, if you want the email address to be mutable, you set the username to something other than email and turn on email address alias.

**Comment by rohandubal** [comment]
Hello @helloniklas 

I am marking this issue closed. Please feel free to re-open if any further questions / issues exist.

Thanks,
Rohan
