### ISSUE TITLE
IAM API

### ISSUE THREAD

**Issue by sbender9** [aws/aws-sdk-ios#496]
I need access to the IAM API's from my iOS application. Is there any way to get an SDK created for IAM?

**Comment by karthiksaligrama** [comment]
can you tell me more about your use case?

**Comment by viterete8** [comment]
+1

**Comment by sbender9** [comment]
I totally missed your question @karthiksaligrama. I wanted to create users and place them in groups. I've since written lambda functions to handle it.

**Comment by viterete8** [comment]
In my case, i can't find any documentation/tutorial teaching how to make calls from Swift to API Gateway methods that require IAM Authorization.
