### ISSUE TITLE
Unable to verify a UserPool user if app shuts down in between

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#497]
So, I'm able to verify a user with the code after signing up if it's done in the same run of the app. But, if a user sign ups, then the app shuts down and restarts (for instance battery drains or for whatever reason the user doesn't verify user right away) I then retrieve that user by user name and do the verify in the same way

`user.confirmSignUp(code, forceAliasCreation: true).continue({ (task) -> Any? in`

But I then just get back the error AWSCognitoIdentityProviderErrorDomain.codeMismatch despite the code being the correct one?

**Comment by behrooziAWS** [comment]
The confirmation code is valid for 24 hours.  I just tested quitting the app and confirming the user and it worked without issue.  If more than 24 hours has elapsed, you need to use `user.resendConfirmationCode()` http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityUser.html#//api/name/resendConfirmationCode

**Comment by helloniklas** [comment]
@behrooziAWS ok thanks for confirming. Not sure why I can't get this to work properly. After shutdown, do I then need to call signUP again on that user? Or do I need to log them in first, before calling confirmSignUp? 

At the moment I retrieve the user from the user pool by username, then call confirmSignUp. But I suspect maybe I have to first sign them in to get their session again?

**Comment by behrooziAWS** [comment]
No, you do not need to call signup or obtain a session.

[[pool getUser:@"userName] confirmSignUp:@"code"];  Is what I was doing.  If you still can't get it to work, send some request ids and we can look at the the calls server side.

**Comment by helloniklas** [comment]
It works if I sign in the user first otherwise it gives back an error.

**Comment by behrooziAWS** [comment]
You can't sign in a user that is not confirmed, I'm not sure I follow.  By sign in, what exactly are you doing?

**Comment by helloniklas** [comment]
I store username and password in secure keychain. Then use that to do getSession on the user of the app shut down in between. It comes back saying user is unconfirmed. But, if I don't do this. The code won't work.

**Comment by chetanme** [comment]
Do you still have questions about the flow here? If yes, feel free to re-open with the steps to reproduce the issue.
