### ISSUE TITLE
Mac OS X Support?

### ISSUE THREAD

**Issue by mildm8nnered** [aws/aws-sdk-ios#498]
We'd like to be able to use the SDK on iOS and Mac OS X

Are there any plans to support the desktop as well as mobile?

From a very brief review of the source, it looks like almost all of the UIKit dependencies are actually in the unit tests.

**Comment by karthiksaligrama** [comment]
Not planned yet, But we will consider it.

**Comment by orj** [comment]
I too would like this SDK to support the Mac.  I've did a spike out today on what it would take to port over to the Mac and the base work in the code seems fairly trivial. Essentially just remove some unnecessary UIKit imports and provide a UIDevice stand-in for the Mac.

I even started doing some of this work (I can provide a pull request with some of it if necessary).

The main issues I see are in MobileAnalytics.  There are some baked in assumptions about the lifecycle of iOS apps there which don't hold for Mac apps.  And there are some things in AWSCognitoIdentityUserPool that I don't quite understand the significance of.

As a macOS app developer I'd really love to use Mobile Analytics.  I've used it briefly with an iOS project I worked on and found it useful and want to start using it for Mac projects.

**Comment by pkirchner** [comment]
+1

**Comment by triplef** [comment]
+1

**Comment by Vimy** [comment]
+1

**Comment by jseibert** [comment]
+1

**Comment by RichAppz** [comment]
+1

**Comment by RichAppz** [comment]
I found articles about developers requesting the back in 2010, it's crazy that we are still having to request such a fundamental feature of the SDK. Is there a timeline for this to be implemented or is there a work around that we can use?

**Comment by pcolton** [comment]
++1

**Comment by ruizrica** [comment]
+1

**Comment by maysamsh** [comment]
+1

**Comment by EricWasTakenMJD** [comment]
@orj - did you ever continue the analysis to port for macOS? I'd be willing to collaborate on a fork.

**Comment by s16h** [comment]
Are there any plans to take this on?

**Comment by pkirchner** [comment]
Here is an initial start to have at least S3 working on MacOS. will update it to match latest AWS SDK in the next days... (Most work done by others)

https://github.com/pkirchner/aws-sdk-objc

**Comment by nikilster** [comment]
@karthiksaligrama any updates on this - would love to use it!

@pkirchner - does your fork work for S3 uploads?

**Comment by nikilster** [comment]
@pkirchner how do you build and get the framework files for your fork? 

Asking here as I wasn't seeing how to create a new issue in that repo.

**Comment by pkirchner** [comment]
i'm just using it as a source for cocoapods right now.

**Comment by foscomputerservices** [comment]
+1 -- especially now that swift in on the server (e.g. Vapor, Perfect, etc...)

**Comment by ricktbaker** [comment]
+1 I can't believe there is not an SDK for macOS already.

**Comment by spentak** [comment]
+1 We have a Mac and iOS app

**Comment by syvex** [comment]
+1

**Comment by mohacs** [comment]
It is crazy, why AWS keep ignoring macOS platform. IOS apps mostly comes with counterpart on macOS. 
+1

**Comment by loganallenc** [comment]
+1 Why has this not happened yet?

**Comment by darthdurden** [comment]
How is this not a thing already? I really need this (and assumed it was already a done deal)

**Comment by waynemock** [comment]
I’ve got a port of the kit to macOS working well for my needs. It’s the latest version 2.6.12. Has all the frameworks except AWSLex and AWSPinpoint. 

https://github.com/waynemock/aws-sdk-ios

**Comment by mirkokiefer** [comment]
+1

**Comment by mirkokiefer** [comment]
Still very much interested in this...

**Comment by waynemock** [comment]
I've been actively working on my port. I'm using AWSCore and S3 in a project that uses AWS Transcribe. I've also added a framework for Transcribe in a separate branch. The port has taking a bit of a back seat to my project that uses it. It still needs to get the unit tests up and running.

**Comment by loganallenc** [comment]
I want Mac OS X support.

**Comment by rynosoft** [comment]
+1

**Comment by christwsy** [comment]
+1

**Comment by danilke** [comment]
+1

**Comment by gray-goose** [comment]
+1

**Comment by kicsipixel** [comment]
+1

**Comment by sv9988** [comment]
+1

**Comment by armadsen** [comment]
Add me to the list asking for macOS support.

**Comment by seanbehan** [comment]
+1

**Comment by Jonathanrwebb** [comment]
+1

**Comment by ddegner** [comment]
+1

**Comment by sethkor** [comment]
+1

**Comment by ddegner** [comment]
In the end I had to use python, which was much easier to program, but looks all non-native

**Comment by muellerfr** [comment]
Hello @mildm8nnered,

I have added this as a feature request in our backlog and have submitted it to the team for prioritization. At this point the team has no plan to support Mac OS X. We will let you know, either on this thread, or through a forum announcement if we add support for Mac OS X.

**Comment by pablogeek** [comment]
+1

**Comment by Jacob101mcd** [comment]
+1 Insane this hasn't happened yet.

**Comment by LYM-collab** [comment]
Jinx this is crazy it was requested 4 years ago, almost every other SDK has updated to support Mac OS X and yet here we are requesting this for 4 years and still not a peep from AWS with any encouraging news. Please fix this soon as otherwise I'm considering switching from using AWS for all our business needs as if you can't keep an SDK updated with basic features our trust in AWS will continue to wane.

**Comment by vgorloff** [comment]
Seems we have to switch to ARM silicon :)

**Comment by imf** [comment]
So... Is this coming any time soon or ever? Given that you can use basically the same UI for both MacOS and iOS now, and _we're talking about fairly generic model level stuff..._
