### ISSUE TITLE
Using AWSMobileAnalytics(forAppId: Constants.AmazonAnalyticsAppId, configuration:analyticsConfiguration) does not work

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#499]
So the new API simply does not show up in analytics.

If I put the old one in:
`AppDelegate.analytics = AWSMobileAnalytics(forAppId: Constants.AmazonAnalyticsAppId, identityPoolId: Constants.identityPoolId)`

it works fine, but the new API

```
        let analyticsConfiguration = AWSMobileAnalyticsConfiguration()
        analyticsConfiguration.serviceConfiguration = serviceConfiguration;
        AppDelegate.analytics = AWSMobileAnalytics(forAppId: Constants.AmazonAnalyticsAppId, configuration:analyticsConfiguration)
```

nothing shows up...

**Comment by karthiksaligrama** [comment]
can you enable log and see what exception message you get?

**Comment by karthiksaligrama** [comment]
i'm assuming this is resolved, if it persists, please create a new issue or reopen this one and let us know the exact set of steps
