### ISSUE TITLE
How to increase AWSKeyMaxStorageSize?

### ISSUE THREAD

**Issue by digitwolf** [aws/aws-sdk-ios#500]
I've reached the 5mb limit of AWSKeyMaxStorageSize in AWSMobileAnalytics.
After that AWS Mobile Analytics stops adding events.

https://github.com/aws/aws-sdk-ios/blob/master/AWSMobileAnalytics/Internal/AWSMobileAnalyticsFileEventStore.m#L99

I haven't figured a way to set this value and there is no documentation.
Please help me increase the limit.

**Comment by rohandubal** [comment]
Hi @digitwolf ,

Thanks for reporting this. We currently do not have a way to increase the limit. We have take this as a feature request and update this thread once we provide a way to do so.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
added in 2.4.12

**Comment by digitwolf** [comment]
Thanks @karthiksaligrama,
Can you share an example?

**Comment by chrisvire** [comment]
2.3.8 is the currently available SDK.  @karthiksaligrama, how would I get 2.4.12? Any idea on release timeline?

**Comment by behrooziAWS** [comment]
@chrisvire Please open an issue in the Android repo: https://github.com/aws/aws-sdk-android/issues  The iOS release versions don't align with Android.
