### ISSUE TITLE
ApiGateway generated Obj-C code does not process ISO8601 Date as expected

### ISSUE THREAD

**Issue by peterfennema** [aws/aws-sdk-ios#501]
I am using the iOS SDK 2.4.9.
My remote service returns a Date like this: 2016-10-18T10:50:25.884Z

This matches (AWSCategory.m) with AWSDateISO8601DateFormat3

`NSString *const AWSDateISO8601DateFormat3 = @"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
`

However, the generated code (see below) assumes that the date format is AWSDateISO8601DateFormat1

`NSString *const AWSDateISO8601DateFormat1 = @"yyyy-MM-dd'T'HH:mm:ss'Z'";
`

The result is that after receiving a User object from my service, the createdAt date is always nil.
I would expect that the generated code would work for all Date formats that satisfy the ISO8601 date.

To verify I edited the generated code replacing AWSDateISO8601DateFormat1 with AWSDateISO8601DateFormat3. This works like a charm :) , but is a inconvenient workaround (don't want to edit generated code)

A fragment of my schema:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "User Schema",
    "type": "object",
    "properties": {
        "userId": {
            "description" : "Unique id for the user",
            "type": "string"
        },
        "createdAt": {
            "description": "Date in ISO8601 format",
            "type": "string",
            "format": "date-time"
        }
    }
}

```

Generated code

```

@interface AMZTESTUser : AWSModel
/**
 Unique id for the user [optional]
 */
@property (nonatomic, strong, nullable) NSString *userId;

/**
 Date in ISO8601 format [optional]
 */
@property (nonatomic, strong, nullable) NSDate *createdAt;

@end


@implementation AMZTESTUser

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"userId": @"userId",
             @"createdAt": @"createdAt"
             };
}

+ (NSValueTransformer *)createdAtJSONTransformer {
    return [AWSMTLValueTransformer reversibleTransformerWithForwardBlock:^id(NSString *dateString) {
        return [NSDate aws_dateFromString:dateString format:AWSDateISO8601DateFormat1];
    } reverseBlock:^id(NSDate *date) {
        return [date aws_stringValue:AWSDateISO8601DateFormat1];
    }];
}

@end
```

**Comment by karthiksaligrama** [comment]
related to #488
