### ISSUE TITLE
UserPool confirmation email goes into users spam folder

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#503]
Is there any way to avoid this happening? I guess it's based on the message being short and coming from unknown user.

**Comment by behrooziAWS** [comment]
Is your sender using a custom domain in SES? http://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-domains.html Or the default?

**Comment by helloniklas** [comment]
I'm using a custom domain. Email goes out fine. But I've got reports that for a lot of users they end up in their spam folders. Just wounded if there is anyway to avoid this.

**Comment by behrooziAWS** [comment]
We do use DKIM to improve the deliverability of the default verificationemail.com emails.  But with custom domains, I'm not sure there is much that can be done besides tweaking the message content.  We can't influence the ranking algorithm the email provider uses.  You may be able to use some of the suggestions here: https://fulcrumtech.net/resources/avoiding-gmail-spam-filter/.  Another option would be to confirm via SMS, but there are costs associated with that.  You should be able to view some metrics about email deliveries in your SES console.

**Comment by behrooziAWS** [comment]
Another option is to turn on DKIM on your custom domain.  http://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim.html
