### ISSUE TITLE
API Gateway issue - SDK version 2.4.11

### ISSUE THREAD

**Issue by tomhoffen** [aws/aws-sdk-ios#505]
Hi, 
I am using API Gateway SDK version 2.4.9 and everything is working well. 

Now after updating the SDK to version 2.4.11 the SDK is trying to hit 
/v1/photos%3Fexpand%3D1%26per_page%3D20
instead
/v1/photos/expand=1&per_page=20

From the latest commit it seems that now you are encoding the entire url (including the query string parameters) - 
https://github.com/aws/aws-sdk-ios/compare/1034a77a77cc7ea5866389275a5105bff074f24f...7035addb92b3b8294acb21a5c6a57c13e076a143#diff-3738b43dd1185103c95081ed5a684772R377

**Comment by rohandubal** [comment]
Hi,
Could you provide some more details about the errors which you are getting? Do the invocations keep failing?

Thanks,
Rohan

**Comment by tomhoffen** [comment]
Hi, 
I'm getting the following error:

Error Domain=com.amazonaws.AWSAPIGatewayErrorDomain Code=1 "(null)" UserInfo={HTTPBody={
    Message = "User: arn:aws:sts::**************:assumed-role/Cognito..../CognitoIdentityCredentials is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:eu-west-1:************:**********/***/GET/v1/photos%3Fexpand%3D1%26per_page%3D20%26filter%3Din_feed%2Ceq%2C1";
}


Thanks,
Tom

**Comment by helloniklas** [comment]
I'm being a related problem when creating a AWSAPIGatewayRequest and adding queryParameters it encodes them as %3f and doesn't find the end point?

{ URL: https://xxxxxxxx-1.amazonaws.com/dev/listen/posts/%3Ftags%3DI22e68a91c9cf49d9988f7a42563256ee }
{
    message = "No method found matching route listen/posts/%3Ftags%3DI22e68a91c9cf49d9988f7a42563256ee for http method GET.";
}

**Comment by batkuip** [comment]
Same problem here - looks like 2.4.10 & 2.4.11 have a broken APIGatewayClient

**Comment by batkuip** [comment]
https://github.com/aws/aws-sdk-ios/blob/7035addb92b3b8294acb21a5c6a57c13e076a143/AWSAPIGateway/AWSAPIGatewayClient.m#L377

is encoding again - processParameters already has encoded the individual elements.

**Comment by helloniklas** [comment]
For me it does work in 2.4.10 but it's broken in 2.4.11

**Comment by DerkBusser** [comment]
+1, same issue with api gateway

**Comment by karthiksaligrama** [comment]
fixed with 2.4.12

**Comment by vinaygoel79** [comment]
When I tried to hit the request through postman. I am facing the some problem. I set this in the aws authentication in postman:-

"Access key:- xxxxxxxxxx

Secrete key:-xxxxxxxxxx

Aws region:- ap-south-1

Service name:- execute-api".

while POST i got this error

{ "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/dms/api/v1/filestore/file\n\ncontent-length:29940\ncontent-type:multipart/form-data\nhost:e7ffona9b4.execute-api.ap-south-1.amazonaws.com\nx-amz-date:20170714T111258Z\n\ncontent-length;content-type;host;x-amz-date\n15c77e9022d5c4e9de523e7279515d245695c76115ebabe7517119701f9ae963'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170714T111258Z\n20170714/ap-south-1/execute-api/aws4_request\nb0e6151f24eb3a4aa5520da442bdafe7625a44ed7c15f3109eeb78eef038a6cd'\n" }
while GET i got this

{ "message": "No method found matching route api/v1/filestore/file for http method GET." }
In the code I did something like this

@RestController
@requestmapping(value = "/v1/filestore")
public class FileUploadController {

@Autowired
private IFileStoreService fileStoreService;

@CrossOrigin
@ResponseBody
@RequestMapping(value = "/file/{id}", method = RequestMethod.GET)
and in application.properties i set

server.contextPath=/api
If I was wrong then please lead me the correct argument and help me to fix this issue.

Thanks

**Comment by kvasukib** [comment]
Hi @vinaygoel79,

Which SDK version are you using?

**Comment by vinaygoel79** [comment]
i didn't generate any SDK in API Gateway but i am using  java 8 platform for creating a lambda function
