### ISSUE TITLE
Xcode8,Xcode7 AWSCore.framework/strip-frameworks.sh: No such file or directory

### ISSUE THREAD

**Issue by VishIphTech** [aws/aws-sdk-ios#508]
I just used cocoaPod and its working well on device and simulator. But when i trying to archive for create ipa its showing error:

bash: /Users/*****/Library/Developer/Xcode/DerivedData/BodyRub-elmsjazmbtnyffesgirscgmvdaho/Build/Intermediates/ArchiveIntermediates/BodyRub/BuildProductsPath/Release-iphoneos/BodyRub.app/Frameworks/AWSCore.framework/strip-frameworks.sh: No such file or directory

**Comment by rohandubal** [comment]
Can you re-install all the dependencies? Also, could you clean the contents of `/Users/your_user_name/Library/Developer/Xcode` and try compiling again? Whats the version of  SDK you are using?

Thanks,
Rohan

**Comment by VishIphTech** [comment]
Version 2.4.5

I have try to find luck using diffrent way's

1. Update pod
2. Re- install
3. Using framework
etc

But i could't get any luck.

Thanks

**Comment by VishIphTech** [comment]
I have found the solution.

Once i have deleted "Run script" from project "Build Phases" its working.

Thanks
Vish

**Comment by karthiksaligrama** [comment]
@VishIphTech deleting the run scripts is not the way to go, your app might be rejected from the app store. I would rather root cause this as to why you are not getting the script. Can you confirm if you are using cocoapods or carthage or prebuilt frameworks?

**Comment by SongXiXiang** [comment]
@karthiksaligrama :
excuse me, if I don't include the scripts when using cocoapods, can my app submit to app store?

**Comment by codeslubber** [comment]
Jesus headless horseman? what is going on here? I am using carthage and it also failed saying no such file.

**Comment by kiroskirin** [comment]
@codeslubber Make sure you run `Carthage` script first like this

<img width="605" alt="screen shot 2018-10-13 at 1 50 17 am" src="https://user-images.githubusercontent.com/311686/46888331-63349800-ce8a-11e8-9347-47bb0f11be95.png">
