### ISSUE TITLE
Unable to change configuration of mobile analytics

### ISSUE THREAD

**Issue by Eckelf** [aws/aws-sdk-ios#509]
I want to provide the ability to opt-out of the app's event tracking while it is running.

`AWSMobileAnalyticsConfiguration` does provide `enableEvents` as a way to disable that, however `AWSMobileAnalytics` caches instances based on their app id which means that I can't update the configuration dynamically.

Is there a way around that or am I missing something?

While looking at the source files I noticed a function `removeCachedInstances` which is private unfortunately.

**Comment by rcha** [comment]
There is no other way currently.

Please feel free to submit a pull request and we will review it and add it to the next release. 

You should also consider switching to use Amazon Pinpoint instead: 
https://aws.amazon.com/pinpoint/
