### ISSUE TITLE
APIGateway Swift generated API does not work with Xcode 8

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#510]
So, even after going through and updating everything in the generated code to Swift 3, I still get various complaints, such as self.configuration.endpoint = AWSEndpoint(region: configuration.regionType, service: .APIGateway, URL: NSURL(string: URLString)!) is read only and can not be set.

Also, the dispatch_once is no longer available in Swift.

Any plans on updating this? Or how can I work around this for now?

**Comment by helloniklas** [comment]
After doing some more refactoring I now get it to compile and run, but it's not working, it doesn't seem to pick up the baseURL, I get

<NSMutableURLRequest: 0x17001aa90> { URL: (null)/listen/rules }
unsupported URL

When can we expect this to be updated to work with Xcode8, as it's pretty useless as it is now.

**Comment by carlhunterroach** [comment]
I was also getting "unsupported URL"

The issue was in the APIG generated iOS SDK file "XXXXxxxxClient.swift"
It defined a new static variables (among other things).
Rolling back this single file to an earlier version removed the "unsupported URL" error messages.

**Comment by rohandubal** [comment]
Hello @helloniklas 

We currently do not have code generation for Swift 3. If your app code base is in Swift 3, you could use the Objective C generated SDK using a bridging header. I am marking it as feature request and update the thread when we have Swift 3 Code Generation for API Gateway SDK.

Thanks,
Rohn

**Comment by miktap** [comment]
I'm experiencing same issues. Objective C generated SDK works but it's really painful to use compared to the Swift generated. It's rather simple to convert Swift generated SDK to Swift 3 compatible but there's still that one error that @helloniklas mentioned. Generated SDK tries to set a readonly property. Why is the `configuration` property of `AWSAPIGatewayClient` class made as readonly?

**Comment by azizj1** [comment]
This is still happening ... unbelievably annoying

**Comment by KaushalElsewhere** [comment]
I upgraded my project from swift 2.3 to 3.0 today and facing same issue as mentioned above.
Any Idea when its going to be fixed?

**Comment by rohandubal** [comment]
Hello, We have released Swift 3 generated SDK support. You can download it from API Gateway console and use it with AWS iOS SDK 2.5.3.

Thanks,
Rohan

**Comment by ForeandAft** [comment]
This appears to have reappeared.  I just downloaded an SDK from API Gateway and this bad line is still in the source code.

**Comment by muellerfr** [comment]
@ForeandAft, we're tracking the issue here: https://github.com/aws/aws-sdk-ios/issues/916
