### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by richlowenberg** [aws/aws-sdk-ios#511]
There used to be release notes, and those have stopped being created. Would be helpful to have those back, especially for identifying swift compatibility etc.

**Comment by rohandubal** [comment]
Hi,

It is tracked in changelog here: https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md

Also the AWS Release notes are here: 

https://aws.amazon.com/releasenotes/iOS

Thanks,
Rohan

**Comment by richlowenberg** [comment]
Awesome, thanks!
