### ISSUE TITLE
Use the v4 signature function directly

### ISSUE THREAD

**Issue by simoami** [aws/aws-sdk-ios#513]
Hi I have to use a different lib to make http calls to secure endpoints from the API gateway. For this to work I need to generate the v4 signature separately. Is it possible to use the one bundled in iOS sdk?

**Comment by karthiksaligrama** [comment]
Thanks for your feedback. I'll add this to the backlog

**Comment by simoami** [comment]
Thanks!

**Comment by kmcgill88** [comment]
This post is pretty old but @simoami, did you ever get this to work? I have the same use case and am fumbling around looking at options.
