### ISSUE TITLE
Bug: CognitoUserPools Update Attributes allows duplicate emails

### ISSUE THREAD

**Issue by BruceBuckland** [aws/aws-sdk-ios#515]
Update Attributes allows User Pools to duplicate emails to be verified even when email is set up as an alias. This seems wrong.

Login with the email address used as a username works, however only for one of the ID's, I haven't figured out which one yet.

I think this is a bug.

Reported against aws-ios-sdk-samples already, but it is not their bailywick, nor yours for that matter.  Server side API problem?

**Comment by behrooziAWS** [comment]
I think this is just a misunderstanding of expected behavior.  An email can be associated with one username at a time and is only setup as an alias when the email is verified.  If you verify the same email on another username, the alias will migrate to that username.  Until the email is verified, the email cannot be used as an alias.

The alias is only setup when the email is verified to prevent someone from blocking the rightful owner from signing up.

**Comment by BruceBuckland** [comment]
@behrooziAWS 
Thanks, and I do understand what you are saying.  However this expected behavior is causing problems that I think have not been considered.  They become obvious when you implement and test a full implementation of user pools.

I think this "alias of an email address" feature has not been fully considered.  

The rightful owner **IS** prevented from signing up once the email has been updated into the user pool.  (this is because he tries to sign up, he gets a confirmation code and enters it and it tells him that the email is duplicate.  From then on the username he used on that attempt is stranded (without a CLI admin-delete-user intervention).  

I brought a related issue up on the sdk-samples board, and @kushwahavinay suggested that I do an initiateAuth to find out if the user email exists.  I think getSession could do that for me (it does ti with username!).


I hear that that this is by design, but that doesn't make sense when once considers that the API already does that for me with usernames (it won't let me create a duplicate username - which is of course obviously the right thing to do and is needed).

In any case, I have two workarounds.  1) take email and make it NOT and alias. or 2) fetch the session beforehand and if I get a username does not exist error, then go ahead and register it.  But as I said, user.getSession should do that for me.

**Comment by BruceBuckland** [comment]
Thanks for your help.

Just to let you know, i implemented  @kushwahavinay suggestion, which in the IOS SDK works like this:

- Do a get session with a big long string for a password that nobody will ever type, and use the email address as the username for signup.  Do a user.getSession using that username and password.

- Switch based upon the error you get and return an appropriate task
  - If you get NotAuthorized - construct an AWSTask in error state, for the case where the mail is already in use.
  - If you get UserNotFound - return an AWSTask that does the expected getSession with the real username password and attributes
```
            if task.error == nil  {
                NSLog("How did you guess that password, and why?")
                return nil
            } else {  // we should either get wrong password or user not exist
                if let rejectType = task.error?.code  {
                    
                    switch rejectType {
                    case AWSCognitoIdentityProviderErrorType.NotAuthorized.rawValue:
                        
                        // If it is not authorized, then the email exists as an alias to another user
                        return AWSTask(error: NSError(domain: AWSCognitoIdentityProviderErrorDomain, code: AWSCognitoIdentityProviderErrorType.UsernameExists.rawValue, userInfo: ["message":"Email already in use by a user"]))
                        
                    case AWSCognitoIdentityProviderErrorType.UserNotFound.rawValue:

                        // If it is not found, then the email is not an alias to another user and can be used
                        return self.pool!.signUp(self.usernameField.text!, password: self.passwordField.text!, userAttributes: userAttributes, validationData: nil)
                        
                    default:
                        
                        // Other errors - we will have to see
                        NSLog("When checking if email was unique encountered unexpected error type: \(rejectType) expected NotAuthorized or UserNotFound - debug - continuing")
                        return self.pool!.signUp(self.usernameField.text!, password: self.passwordField.text!, userAttributes: userAttributes, validationData: nil)
                    }
                }
            }
```

(Thank you for your help, and I hope you will modify the SDK to manage this. I think you will agree this is more than the SDK design anticipated would need to be done).

**Comment by behrooziAWS** [comment]
> (this is because he tries to sign up, he gets a confirmation code and enters it and it tells him that the email is duplicate. From then on the username he used on that attempt is stranded (without a CLI admin-delete-user intervention). 

I don't think this is true are you aware of [this method](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityUser.html#//api/name/confirmSignUp:forceAliasCreation:) for confirming?

**Comment by BruceBuckland** [comment]
@behrooziAWS 
Right... Thank you.  I did not know about the confirmSignUp:forceAliasCreation: method, and you are correct, that would avoid the "unusable identity" problem.  

Can we assume that if the confirmSignUp:forceAliasCreation: process occurs (by a third party), and is never confirmed, that the original user gets to keep his email/phone?

**Comment by behrooziAWS** [comment]
Correct, the alias does not get reassigned until it is confirmed on the other account.

**Comment by BruceBuckland** [comment]
Excellent. I will use that in combination with @kushwahavinay 's suggestion.

Can you tell me if we will see the new aws-mobilehub-helper-ios code soon?  The mobile-hub downloads now use a version that has user pools and AWSSignInProviderFactory but we don't have that on the mobile-hub-helper github.

**Comment by BruceBuckland** [comment]
@behrooziAWS 
Excellent. I will use that in combination with @kushwahavinay 's suggestion.

Can you tell me if we will see the new aws-mobilehub-helper-ios code soon? The mobile-hub downloads now use a version that has user pools and AWSSignInProviderFactory but we don't have that on the mobile-hub-helper github.

**Comment by behrooziAWS** [comment]
I spoke with the mobile hub team and it is on their todo list, no date was provided.

**Comment by BruceBuckland** [comment]
Thanks

**Comment by minbi** [comment]
Please re-open the issue if this still applies
