### ISSUE TITLE
Library not loaded errors when running on an actual device

### ISSUE THREAD

**Issue by bomalley** [aws/aws-sdk-ios#517]
Xcode 8.0 (8A218a)
AWS SDK 2.4.11

I've tried the CocoaPods approach and the Frameworks approach. Both produce the same errors when I archive and install on an iPhone.  The app crashes and the crash log says:

> Termination Description: DYLD, Library not loaded: @rpath/AWSSNS.framework/AWSSNS

There must be something wrong with the Xcode configuration.  Any ideas?

**Comment by karthiksaligrama** [comment]
if you are using dynamic framework , make sure you are following steps listed here

https://github.com/aws/aws-sdk-ios#frameworks

**Comment by bomalley** [comment]
Thanks for the reply @karthiksaligrama – I have.

I just committed my code, moved over to a machine running Xcode 7.2 (7C68) and it works. Granted that's a test case of 1, but it seems to imply that there's a conflict with something in AWS and Xcode 8.

In the case of my example, I haven't even written a single line of code to interface with AWS. This test was simply to be able to compile with those frameworks included, so I don't think this is related to the Swift/Xcode 8 issue already reported.

**Comment by bomalley** [comment]
The plot thickens after more testing.

An app built with Xcode 7.3 and running on iOS 9.3.5 will work as expected.

An app built with Xcode 7.3 and running on iOS 10 will not work without an entitlements file. It will give an error – "no valid 'aps-environment' entitlement string found for application".  

If you compile with the entitlements.plist file, the app crashes and shows the DYLD, Library not loaded error like in my first post.

This leads me to believe that perhaps the conflict is more related to iOS 10 than any version of Xcode.

**Comment by karthiksaligrama** [comment]
You need to have app entitlements for keychain access on IOS10

**Comment by bomalley** [comment]
Keychain Sharing?  For which Keychain Groups?

**Comment by karthiksaligrama** [comment]
you can define your own keychain groups, but as long as the keychain access in enabled in capabilities we are good.

**Comment by rohandubal** [comment]
Hello @bomalley ,

I am closing this issue, please feel free to open if the any issue still persists.

Thanks,
Rohan
