### ISSUE TITLE
Settings public-read ACL on AWSS3TransferUtilityUploadExpression does not work

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#518]
So, I'm uploading ok with the AWSS3TransferUtility.default(), however, I need to set the ACL to public read. I'm trying:

            let expression = AWSS3TransferUtilityUploadExpression()
            expression.setValue("public-read", forRequestHeader: "x-amz-acl")

Then passing this to the AWSS3TransferUtility.default().uploadData(

However, it does not seem to work.

**Comment by helloniklas** [comment]
Ok turns out I need to add an IAM policy to my cognate auth role, putObjectACL allow.

**Comment by borisdering** [comment]
@helloniklas, sorry I'm pretty new to the AWS world. Can you explain how you achieved this?
