### ISSUE TITLE
cocoapods not pulling 2.4.11, highest available seems to be 2.4.10 

### ISSUE THREAD

**Issue by codepowder** [aws/aws-sdk-ios#519]
Here is the pod file excerpt, and I am trying to force it to go higher than 2.4.10:

>     pod 'AWSAutoScaling', '~> 2.4.10'
>     pod 'AWSCloudWatch', '~> 2.4.10'
>     pod 'AWSCognito', '~> 2.4.10'
>     pod 'AWSCognitoIdentityProvider', '~> 2.4.10'
>     pod 'AWSDynamoDB', '~> 2.4.10'
>     pod 'AWSEC2', '~> 2.4.10'
>     pod 'AWSElasticLoadBalancing', '~> 2.4.10'
>     pod 'AWSIoT', '~> 2.4.10'
>     pod 'AWSKinesis', '~> 2.4.10'
>     pod 'AWSLambda', '~> 2.4.10'
>     pod 'AWSMachineLearning', '~> 2.4.10'
>     pod 'AWSMobileAnalytics', '~> 2.4.10'
>     pod 'AWSS3', '~> 2.4.10'
>     pod 'AWSSES', '~> 2.4.10'
>     pod 'AWSSimpleDB', '~> 2.4.10'
>     pod 'AWSSNS', '~> 2.4.10'
>     pod 'AWSSQS', '~> 2.4.10'
>   
>     pod 'FBSDKCoreKit'
>     pod 'FBSDKLoginKit'
>     pod 'FBSDKShareKit'
> 

Here is the log from pod installation: 

> MB:ShowCoach bojans$ pod install --verbose
>   Preparing
> 
> Analyzing dependencies
> 
> Inspecting targets to integrate
>   Using `ARCHS` setting to build architectures of target `Pods-ShowCoach`: (``)
> 
> Finding Podfile changes
>   - AEConsole
>   - AELog
>   - AWSAutoScaling
>   - AWSCloudWatch
>   - AWSCognito
>   - AWSCognitoIdentityProvider
>   - AWSDynamoDB
>   - AWSEC2
>   - AWSElasticLoadBalancing
>   - AWSIoT
>   - AWSKinesis
>   - AWSLambda
>   - AWSMachineLearning
>   - AWSMobileAnalytics
>   - AWSS3
>   - AWSSES
>   - AWSSNS
>   - AWSSQS
>   - AWSSimpleDB
>   - FBSDKCoreKit
>   - FBSDKLoginKit
>   - FBSDKShareKit
> 
> Resolving dependencies of `Podfile`
> 
> Comparing resolved specification to the sandbox manifest
>   - AEConsole
>   - AELog
>   - AWSAutoScaling
>   - AWSCloudWatch
>   - AWSCognito
>   - AWSCognitoIdentityProvider
>   - AWSCore
>   - AWSDynamoDB
>   - AWSEC2
>   - AWSElasticLoadBalancing
>   - AWSIoT
>   - AWSKinesis
>   - AWSLambda
>   - AWSMachineLearning
>   - AWSMobileAnalytics
>   - AWSS3
>   - AWSSES
>   - AWSSNS
>   - AWSSQS
>   - AWSSimpleDB
>   - Bolts
>   - FBSDKCoreKit
>   - FBSDKLoginKit
>   - FBSDKShareKit
> 
> Downloading dependencies
> 
> -> Using AEConsole (0.3.0)
> 
> -> Using AELog (0.3.0)
> 
> -> Using AWSAutoScaling (2.4.10)
> 
> -> Using AWSCloudWatch (2.4.10)
> 
> -> Using AWSCognito (2.4.10)
> 
> -> Using AWSCognitoIdentityProvider (2.4.10)
> 
> -> Using AWSCore (2.4.10)
> 
> -> Using AWSDynamoDB (2.4.10)
> 
> -> Using AWSEC2 (2.4.10)
> 
> -> Using AWSElasticLoadBalancing (2.4.10)
> 
> -> Using AWSIoT (2.4.10)
> 
> -> Using AWSKinesis (2.4.10)
> 
> -> Using AWSLambda (2.4.10)
> 
> -> Using AWSMachineLearning (2.4.10)
> 
> -> Using AWSMobileAnalytics (2.4.10)
> 
> -> Using AWSS3 (2.4.10)
> 
> -> Using AWSSES (2.4.10)
> 
> -> Using AWSSNS (2.4.10)
> 
> -> Using AWSSQS (2.4.10)
> 
> -> Using AWSSimpleDB (2.4.10)
> 
> -> Using Bolts (1.8.4)
> 
> -> Using FBSDKCoreKit (4.17.0)
> 
> -> Using FBSDKLoginKit (4.17.0)
> 
> -> Using FBSDKShareKit (4.17.0)
>   - Running pre install hooks
> 
> Generating Pods project
>   - Creating Pods project
>   - Adding source files to Pods project
>   - Adding frameworks to Pods project
>   - Adding libraries to Pods project
>   - Adding resources to Pods project
>   - Linking headers
>   - Installing targets
>     - Installing target `AEConsole` iOS 9.0
>       - Generating Info.plist file at `Pods/Target Support Files/AEConsole/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AEConsole/AEConsole.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AEConsole/AEConsole-umbrella.h`
>     - Installing target `AELog` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AELog/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AELog/AELog.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AELog/AELog-umbrella.h`
>     - Installing target `AWSAutoScaling` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSAutoScaling/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSAutoScaling/AWSAutoScaling.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSAutoScaling/AWSAutoScaling-umbrella.h`
>     - Installing target `AWSCloudWatch` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSCloudWatch/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSCloudWatch/AWSCloudWatch.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSCloudWatch/AWSCloudWatch-umbrella.h`
>     - Installing target `AWSCognito` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSCognito/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSCognito/AWSCognito.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSCognito/AWSCognito-umbrella.h`
>     - Installing target `AWSCognitoIdentityProvider` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSCognitoIdentityProvider/Info.plist`
>       - Generating module map file at `Pods/Target Support
>       Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider.modulemap`
>       - Generating umbrella header at `Pods/Target Support
>       Files/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider-umbrella.h`
>     - Installing target `AWSCore` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSCore/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSCore/AWSCore.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSCore/AWSCore-umbrella.h`
>     - Installing target `AWSDynamoDB` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSDynamoDB/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSDynamoDB/AWSDynamoDB.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSDynamoDB/AWSDynamoDB-umbrella.h`
>     - Installing target `AWSEC2` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSEC2/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSEC2/AWSEC2.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSEC2/AWSEC2-umbrella.h`
>     - Installing target `AWSElasticLoadBalancing` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSElasticLoadBalancing/Info.plist`
>       - Generating module map file at `Pods/Target Support
>       Files/AWSElasticLoadBalancing/AWSElasticLoadBalancing.modulemap`
>       - Generating umbrella header at `Pods/Target Support
>       Files/AWSElasticLoadBalancing/AWSElasticLoadBalancing-umbrella.h`
>     - Installing target `AWSIoT` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSIoT/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSIoT/AWSIoT.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSIoT/AWSIoT-umbrella.h`
>     - Installing target `AWSKinesis` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSKinesis/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSKinesis/AWSKinesis.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSKinesis/AWSKinesis-umbrella.h`
>     - Installing target `AWSLambda` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSLambda/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSLambda/AWSLambda.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSLambda/AWSLambda-umbrella.h`
>     - Installing target `AWSMachineLearning` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSMachineLearning/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSMachineLearning/AWSMachineLearning.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSMachineLearning/AWSMachineLearning-umbrella.h`
>     - Installing target `AWSMobileAnalytics` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSMobileAnalytics/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSMobileAnalytics/AWSMobileAnalytics.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSMobileAnalytics/AWSMobileAnalytics-umbrella.h`
>     - Installing target `AWSS3` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSS3/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSS3/AWSS3.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSS3/AWSS3-umbrella.h`
>     - Installing target `AWSSES` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSSES/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSSES/AWSSES.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSSES/AWSSES-umbrella.h`
>     - Installing target `AWSSNS` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSSNS/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSSNS/AWSSNS.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSSNS/AWSSNS-umbrella.h`
>     - Installing target `AWSSQS` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSSQS/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSSQS/AWSSQS.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSSQS/AWSSQS-umbrella.h`
>     - Installing target `AWSSimpleDB` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/AWSSimpleDB/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/AWSSimpleDB/AWSSimpleDB.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/AWSSimpleDB/AWSSimpleDB-umbrella.h`
>     - Installing target `Bolts` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/Bolts/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/Bolts/Bolts.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/Bolts/Bolts-umbrella.h`
>     - Installing target `FBSDKCoreKit` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/FBSDKCoreKit/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-umbrella.h`
>     - Installing target `FBSDKLoginKit` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/FBSDKLoginKit/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/FBSDKLoginKit/FBSDKLoginKit.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/FBSDKLoginKit/FBSDKLoginKit-umbrella.h`
>     - Installing target `FBSDKShareKit` iOS 8.0
>       - Generating Info.plist file at `Pods/Target Support Files/FBSDKShareKit/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/FBSDKShareKit/FBSDKShareKit.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/FBSDKShareKit/FBSDKShareKit-umbrella.h`
>     - Installing target `Pods-ShowCoach` iOS 10.0
>       - Generating Info.plist file at `Pods/Target Support Files/Pods-ShowCoach/Info.plist`
>       - Generating module map file at `Pods/Target Support Files/Pods-ShowCoach/Pods-ShowCoach.modulemap`
>       - Generating umbrella header at `Pods/Target Support Files/Pods-ShowCoach/Pods-ShowCoach-umbrella.h`
>   - Running post install hooks
>   - Writing Xcode project file to `Pods/Pods.xcodeproj`
>     - Generating deterministic UUIDs
>   - Writing Lockfile in `Podfile.lock`
>   - Writing Manifest in `Pods/Manifest.lock`
> 
> Integrating client project
> 
> Integrating target `Pods-ShowCoach` (`ShowCoach.xcodeproj` project)
>   - Running post install hooks
>     - cocoapods-stats from `/Users/bojans/.gem/ruby/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`
> 
> Sending stats
>       - AEConsole, 0.3.0
>       - AELog, 0.3.0
>       - AWSAutoScaling, 2.4.10
>       - AWSCloudWatch, 2.4.10
>       - AWSCognito, 2.4.10
>       - AWSCognitoIdentityProvider, 2.4.10
>       - AWSCore, 2.4.10
>       - AWSDynamoDB, 2.4.10
>       - AWSEC2, 2.4.10
>       - AWSElasticLoadBalancing, 2.4.10
>       - AWSIoT, 2.4.10
>       - AWSKinesis, 2.4.10
>       - AWSLambda, 2.4.10
>       - AWSMachineLearning, 2.4.10
>       - AWSMobileAnalytics, 2.4.10
>       - AWSS3, 2.4.10
>       - AWSSES, 2.4.10
>       - AWSSNS, 2.4.10
>       - AWSSQS, 2.4.10
>       - AWSSimpleDB, 2.4.10
>       - Bolts, 1.8.4
>       - FBSDKCoreKit, 4.17.0
>       - FBSDKLoginKit, 4.17.0
>       - FBSDKShareKit, 4.17.0
>   Pod installation complete! There are 22 dependencies from the Podfile and 24 total pods installed.
>

**Comment by rohandubal** [comment]
Thanks for reporting this, we will investigate this.

**Comment by rohandubal** [comment]
Hi, could you please retry now? It should be able to fetch 2.4.11. There was an error in publishing  AWSIoT podspec.

Thanks,
Rohan

**Comment by codepowder** [comment]
Yes, that works. Thank you!
