### ISSUE TITLE
Unable to authenticate IOS app using SAML & Amazon Cognito

### ISSUE THREAD

**Issue by MahekPavagadhi** [aws/aws-sdk-ios#520]
I am having some issue while trying to authenticate users using SAML & Amazon Cognito in my iOS mobile app.  I am getting the error pasted below about the need to use an Enhanced flow. Also,the version of aws-sdk-ios is 2.4.10.

_**# "x-amzn-ErrorMessage" = "Basic (classic) flow is not supported with SAML, please use enhanced flow.";
"x-amzn-ErrorType" = "InvalidParameterException:";
"x-amzn-RequestId" = "7633cc65-9cad-11e6-9b65-3397fdc7ad04";**_

**Comment by behrooziAWS** [comment]
Can you show how you are initializing your credentials provider?

**Comment by MahekPavagadhi** [comment]
class CustomIdentityProvider: NSObject, AWSIdentityProviderManager {
    var tokens : [NSString : NSString]?
    @objc var customRoleArn:String
    init(tokens: [NSString : NSString]) {
        self.tokens = tokens
        self.customRoleArn = "xxxx"
    }
    @objc func logins() -> AWSTask {
        return AWSTask(result: tokens)
    }
}
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    var customProviderManager:CustomIdentityProvider!
    var credentialsProvider:AWSCognitoCredentialsProvider!
    
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        // Enable IQKeyboardManager to manage keyboard and textfield
        IQKeyboardManager.sharedManager().enable = true
        // check
        var tok:[NSString:NSString] = [
        "arn:aws:iam::xxxx": "xxxx"]
        self.customProviderManager = CustomIdentityProvider(tokens:tok)
        self.customProviderManager!.customRoleArn
            = "xxxx"
        self.credentialsProvider = AWSCognitoCredentialsProvider(
            regionType: AWSRegionType.xxx,
            identityPoolId: "xxxx",
            unauthRoleArn: nil,
            authRoleArn: "xxxx",
            identityProviderManager: customProviderManager)
        let configuration = AWSServiceConfiguration(region:xxxx, credentialsProvider:credentialsProvider)
        
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration
        return true
    }

**Comment by behrooziAWS** [comment]
Use this constructor instead, otherwise it will use the classic flow which is not supported by SAML.
 self.credentialsProvider = AWSCognitoCredentialsProvider(
        regionType: AWSRegionType.xxx,
        identityPoolId: "xxxx",
        identityProviderManager: customProviderManager)

**Comment by MahekPavagadhi** [comment]
I tried using the constructor you mentioned and I got the following error:

```
    "x-amzn-ErrorMessage" = "Invalid identity pool configuration. Check assigned IAM roles for this pool.";
    "x-amzn-ErrorType" = "InvalidIdentityPoolConfigurationException:";
```

**Comment by kushwahavinay** [comment]
Seems like it is past the previous error, can you please check the role trust policy and see if it is setup correctly as per the documentation.
