### ISSUE TITLE
AWSCognitoIdentityUserPool delete user

### ISSUE THREAD

**Issue by hakobyan1** [aws/aws-sdk-ios#521]
Hi.

Currently i am trying to create functional for deleting user and write unit test for this functional.
So the problem is that AWSCognitoIdentityUserPool does not have deleteUser functional.

AWSCognitoIdentityUser has deleteUser functional but in this case it calls [user getSession] function which tries to access token from keychain, and cause of known issue on ios we have "OSStatus error: [-34018] Security error has occurred."

So my suggestion is to create deleteUser with username and password for (like signup,signin, ...) AWSCognitoIdentityUserPool which will use [user getSession:username password:password validationData:nil], in this case we do not need to access to keychain anymore (at least i hope it :))

**Comment by behrooziAWS** [comment]
Is it possible to run your tests on iOS 9.3 at least for this test?  That's what we do internally for tests that require the keychain until Apple resolves this:  https://forums.developer.apple.com/message/179846#179846

**Comment by hakobyan1** [comment]
One problem here is that my app does not support iOS 9 (it supports 10 and higher versions).

Plus currently for deleting user u should call  [user getSession:username password:password validationData:nil] to put token in keychain then [user deleteUser] which itself calls [user getSession].

So instead of having 
1. [user getSession:username password:password validationData:nil]
2. [user getSession].

We can have only.
 [user getSession:username password:password validationData:nil]

Thank you.

**Comment by behrooziAWS** [comment]
I think this is a workaround rather than a fix, can you implement  AWSCognitoIdentityInteractiveAuthenticationDelegate and set it on the pool instead that just returns the username and password?
