### ISSUE TITLE
DownloadProgress closure with negative values.

### ISSUE THREAD

**Issue by dydus0x14** [aws/aws-sdk-ios#524]
Sometimes 'downloadProgress' closure is called with 'toBeWritten' which is less 0.0. It seems to happen after calling cancel() of AWSRequest.

```
request.downloadProgress = { _, written, toBeWritten in
      let result = (toBeWritten <= 0) ? 0.0 : Double(written)/Double(toBeWritten)
 }
```

I can handle it outside but probably internal fix is better.

**Comment by rohandubal** [comment]
Hi, thanks for reporting this. Could you please mention the SDK version with which you are facing this issue? Also, is it limited to any specific iOS versions? I will try reproducing this issue by calling cancel() in the meanwhile.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hi @dydus0x14 

I tried reproducing this issue, but could not reproduce it. Can you provide with a code snippet using which we can reproduce this issue?

Thanks,
Rohan

**Comment by dydus0x14** [comment]
Hi @rohandubal
It's complicated to reproduce, but I caught this issue when my app loaded 4 images from AWS at the same time.

Thanks

**Comment by kvasukib** [comment]
Hi @dydus0x14, Thanks for reporting to us. If you can reproduce the issue, please share us more logs to diagnose the issue and re-open the issue.
