### ISSUE TITLE
AWS IoT: Error message is not always parsed in AWSIoTService

### ISSUE THREAD

**Issue by sergei-nntu** [aws/aws-sdk-ios#525]
AWSIoTService expect error description message to be stored in "message" key (all lower-case) of AWS IoT REST API response. While sometimes AWS IoT REST API returns error message in key "Message". This leads to inability of iOS application to show the appropriate text description of message to end-user.

**Comment by kvasukib** [comment]
Hi @sergei-nntu, Thanks for reporting to us and sorry for the delayed response. Are you referring to this one [AWSIoTService.m](https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/AWSIoTService.m#L85)
