### ISSUE TITLE
IOS client 2.4.12 Multiple download AWSS3TransferManager get "RequestTimeTooSkewed"  exception 

### ISSUE THREAD

**Issue by uc3po** [aws/aws-sdk-ios#527]
I'm using AWS 2.4.12 version and my app support IOS 9+. 
I'm trying to download multiple files. First file download successfully but rest of my files does not.
i got this  exceptions: 
[3]	(null)	@"MaxAllowedSkewMilliseconds" : @“900000"
[2]	(null)	@"Code" : @“RequestTimeTooSkewed"
Is there any solution for this issue or advice/code block?

my sample  code block: 
                        
                        AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];                             
                        NSMutableArray *tasks = [NSMutableArray new];
        
                        for (FileModel * file in files) { //file count changes, range [0,15]                                
                            NSString *filePath =[[[FolderPathUtilManager sharedFolderPathUtilManager] projectFolderPath]stringByAppendingPathComponent:file.name];
                            if ([[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
                                NSLog(@"File exists");
                            }else{
                                NSURL *downloadingFileURL = [NSURL fileURLWithPath:filePath];
                                AWSS3TransferManagerDownloadRequest *downloadRequest = [AWSS3TransferManagerDownloadRequest new];
                                downloadRequest.bucket = S3BucketName;//my bucket name
                                downloadRequest.key = file.amazonKey; // aws s3 key
                                downloadRequest.downloadingFileURL = downloadingFileURL;
                                
                                
                                AWSTask * taskForDownload = [transferManager download:downloadRequest];
                                [tasks addObject:taskForDownload];
                            }
                        }
                                
                           
                        [[AWSTask taskForCompletionOfAllTasks:tasks] continueWithExecutor:[AWSExecutor mainThreadExecutor] withBlock:^id(AWSTask *task) {
                            if (task.error != nil) {
                                NSLog(@"Error: [%@]", task.error);
                            } else {
                                NSLog(@"files uploaded!");
                            }
                            
                            dispatch_async(dispatch_get_main_queue(), ^{
                                [self.collectionView reloadData];
                            });
                            
                            return nil;
                        }];

**Comment by rohandubal** [comment]
Hi, thanks for reporting this. We will try reproducing this and update once we have a fix.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hi @uc3po I see that you are using the `mainThreadExecutor`. Could you please switch to `defaultExecutor` and see if the error still exists? Since you are calling `reloadData` on main queue, it would be fine to use the `defaultExecutor`. Also how long does it take for the error to surface when there are about 10 files in the task list? 

Thanks,
Rohan

**Comment by minbi** [comment]
Please re-open the issue if this still applies
