### ISSUE TITLE
AWSRegionType doesn't return correct region

### ISSUE THREAD

**Issue by moletteg** [aws/aws-sdk-ios#528]
Hello Everyone

I'm using this code to set up my AWS Connection : 

`AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]  initWithRegionType:AWSRegionAPNortheast1 identityPoolId:awsCredentials.CognitoPoolID identityProviderManager:nil];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionAPNortheast1 credentialsProvider:credentialsProvider];
[AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;`

Unfortunatively, the region isn't set well and the value is AWSRegionAPNortheast2 instead of AWSRegionAPNortheast1 in AWSServiceConfiguration init method class.

Do you know what is wrong ? thanks

**Comment by karthiksaligrama** [comment]
seems ok to me https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Service/AWSService.m#L228

**Comment by karthiksaligrama** [comment]
assuming resolved, closing this issue
