### ISSUE TITLE
Using AWS for App Extensions

### ISSUE THREAD

**Issue by aminiz2** [aws/aws-sdk-ios#529]
Is this possible? The app extensions target does not have an embedded binaries section.

**Comment by helloniklas** [comment]
I just trying to do this as well for a Share extension. And how can I use the same credentials provider to authenticate the an already signed in user from the Extension.

**Comment by k06a** [comment]
Having trouble with this:

> ./Pods/AWSMobileAnalytics/AWSMobileAnalytics/Internal/AWSMobileAnalyticsIOSLifeCycleManager.m:133:41: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Comment by alombard** [comment]
This would be really useful - thanks for your consideration.

**Comment by itsmeichigo** [comment]
Hi, is there any update for this soon?
