### ISSUE TITLE
getPrivateKeyRef error -25300

### ISSUE THREAD

**Issue by pccole** [aws/aws-sdk-ios#532]
When calling `connectWithClientId:cleanSession:certificateId:callback`, the app fails to connect because `Could not find SecIdentityRef aws connection failed` getIdentityRef error: -25000.

I looked at the MQTTClient implementation and noticed 
`SecIdentityRef identityRef = [AWSIoTKeychain getIdentityRef:[NSString stringWithFormat:@"%@%@",[AWSIoTKeychain privateKeyTag], certificateId ]];`. 

When I was calling `(BOOL)addPrivateKeyRef:(SecKeyRef)privkeyRef tag:(NSString*)tag` I was only providing `[AWSIoTKeychain privateKeyTag]`. I changed my implementation to add the certificateId to the end of the tag. It still fails to connect because it could not find SecIdentityRef.

Any help?

Edit:

I've changed my implementation slightly to 
`AWSIoTKeychain.generateKeyPairWithPublicTag(publicTag, privateTag:privateTag)`
`AWSIoTKeychain.addPrivateKey(privateKeyData, tag:privateTag)`

still failing to connect, "Could not find SecIdentityRef"

Edit 2:
I've done some testing and I'm still stumped on this issue. 
In `AWSIoTManager` there is a function called `createKeysAndCertificateFromCsr`. Now this isn't the function I want to use but it does work. Inside the function implementation, it goes through and adds  the privateKeyRef, publicKeyRef, and the certificatePem to the keychain. At the end it calls `[AWSIoTKeychain getIdentityRef:newPrivateTag]`, this always returns a SecIdentity. 

Now, the method I'm calling is `createKeysAndCertificate` in `AWSIoTService`. Once I get my response back I follow the same steps in `createKeysAndCertificateFromCsr` but when I call `[AWSIoTKeychain getIdentityRef:newPrivateTag]` at the end, it returns nil. I believe I'm missing a step in getting this path working but I'm not sure what I'm doing wrong.

**Comment by marcmatta** [comment]
Hi 

I have the same issue @pccole have you been able to fix this since you created this ticket?

Thanks!

**Comment by pccole** [comment]
@marcmatta No, I have not. The team decided to use `createKeysAndCertificateFromCsr` inside of `AWSIoTManager` instead of using `createKeysAndCertificate` inside of `AWSIoTService` and creating `privateKeyRef` and storing it in keychain.

**Comment by marcmatta** [comment]
Thank you!

**Comment by chaurah** [comment]
Hi @marcmatta/@pccole,
   Can you both please let us know which version of XCode and the AWS SDK you are using? This issue could be related to another issue we noticed in the latest version of XCode. You can find further information [here](https://github.com/awslabs/aws-sdk-ios-samples/issues/133). Either way, the versions will be helpful in debugging.

Please let us know if that link helps. Thank you for using AWS IoT and the AWS iOS SDK.

Rahul

**Comment by marcmatta** [comment]
Hi @chaurah,

I am using the following versions:

- Xcode 7.3
- AWS IoT SDK 2.4.12 using Pods
- AWS Core 2.4.12 using Pods

I have opened a separate ticket #552 with code details as @pccole  mentions -25000 and not -23000 error in his description. So if you can link my ticket as well to the ticket to #133 it would be useful to track it too.

I have also enabled Keychain Sharing but to no good. This is really frustrating and i would really appreciate your help!

Thank you for your support!

Marc

**Comment by pccole** [comment]
@chaurah very sorry for not following up sooner! 

- Xcode 8.2 
- AWS IoT SDK 2.4.10 using Pods
- AWS Core SDK 2.4.10 using Pods
- AWS Cognito SDK 2.4.10 using Pods

**Comment by pccole** [comment]
As an additional follow up, I noticed updates to the pods: 2.4.16. I'm currently converting my project to Swift 3 and will retest with Keychain sharing enabled.

**Comment by marcmatta** [comment]
@chaurah do you have any updates on this issue? Thanks!

**Comment by minbi** [comment]
Please re-open the issue if this still applies
