### ISSUE TITLE
Cannot archive application with AWS SDK framework included

### ISSUE THREAD

**Issue by RotemShor** [aws/aws-sdk-ios#534]
Hello,
While trying to archive I get this error:
Failed to verify bitcode in AWSAPIGateway.framework/AWSAPIGateway:
error: Cannot extract bundle from /var/folders.....

Do you have any solution without disabling bitcode in application?

Thank you

**Comment by rohandubal** [comment]
Hi @RotemShor 

Could you please provide some steps to reproduce?

Thanks,
Rohan

**Comment by RotemShor** [comment]
Hi @rohandubal,
The issue was solved. I forgot to add strip_framework.sh script.
Thank you
