### ISSUE TITLE
getDetails does not execute it's callback with facebook as signin provider

### ISSUE THREAD

**Issue by hhartz** [aws/aws-sdk-ios#535]
disclaimer, I'm using `AWSMobileHubHelper`, and sign in + fetch attributes using

    let signInProvider = AWSFacebookSignInProvider.sharedInstance()
    signInProvider.setPermissions(["email", "public_profile"])
    let identityManager = AWSIdentityManager.defaultIdentityManager()
    identityManager.loginWithSign(signInProvider, completionHandler: { (result, error) in
        self.user = self.pool.currentUser()
        self.user.getDetails().continue({ task in
            ...
        })
    })

In the completion handler, using a traditional username/password I do get details (and attributes) back - while using AWSFacebookSignInProvider the handler is not executed.

**Comment by rohandubal** [comment]
Please post issues related to `AWSMobileHubHelper` on https://github.com/aws/aws-mobilehub-helper-ios/issues/ for better responses and tracking. I am marking this closed.

Thanks,
Rohan

**Comment by hhartz** [comment]
@rohandubal ah, sorry for the oversight :)
