### ISSUE TITLE
Unable to find a specification for `AWSPolly`

### ISSUE THREAD

**Issue by fl0549** [aws/aws-sdk-ios#536]
Impossible to install Polly from Cocoapods

**Comment by karthiksaligrama** [comment]
Whats the error you are getting?
 Can you run `pod spec update`

**Comment by fl0549** [comment]
When I run `pod install` with `pod 'AWSPolly'` in my Podfile I get this error message : [!] Unable to find a specification for `AWSPolly`

**Comment by karthiksaligrama** [comment]
did u update your local podspec?

**Comment by karthiksaligrama** [comment]
assuming resolved closing this issue
