### ISSUE TITLE
AWS 2.4.14 and deploying iOS generated SDK from API Gateway console

### ISSUE THREAD

**Issue by pbonneville** [aws/aws-sdk-ios#537]
The AWSAPIGateway.framework in the 2.4.14 SDK and the generated iOS SDK code coming out of our AWS Gateway API are not compatible. It looks like a Swift 3 vs Swift 2 issue. 

I followed the instructions README in the generated SDK zip folder that I downloaded which only covers adding the AWS frameworks and a run script:

> ## With Frameworks
> 1. Download the SDK from [http://aws.amazon.com/mobile/sdk](http://aws.amazon.com/mobile/sdk). Amazon API Gateway is supported with the version 2.4.0 and later.
> 1. With your project open in Xcode, select your **Target**. Under **General** tab, find **Embedded Binaries** and then click the **+** button.
> 1. Click the **Add Other...** button, navigate to the 'AWSCore.framework' & 'AWSAPIGateway.framework' files and select them. Check the **Destination: Copy items if needed** checkbox when prompted.
> 1. Under the **Buid Phases** tab in your **Target**, click the **+** button on the top left and then select **New Run Script Phase**. Then setup the build phase as follows. Make sure this phase is below the 'Embed Frameworks' phase...
> 

I've also tried following instructions on this page: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-ios-swift.html

No luck.

Those instructions mentioned pointing to the Bridging_Header.h file, which I did, but it did not resolve the issues the app was spitting out related to not finding classes that were defined as being overridden and other Swift 3 v. Swift 2 method signature issues.

**Comment by idamaster** [comment]
@pbonneville Do you have specific examples of what issues you're running into? I used Mobile Hub and ran into a bunch of problems that Xcode didn't automatically fix for me. In Swift 3 I've found that example code from the SDK and samples in AWS had significant changes in the method signatures that weren't picked up by Xcode in the transition. A lot of trial and error to get the whole AWS SDK and associated examples to Swift 3...but it worked.

**Comment by rohandubal** [comment]
Hello @pbonneville 

The Swift generated SDK from API Gateway is Swift 2 and not Swift 3. If your application is in Swift 3 and you want an easy integration, you can use the Objective C generated SDK. You need to import the `*Client.h` file into your bridging header and you should be able to use the SDK in your Swift app.

Thanks,
Rohan
