### ISSUE TITLE
AWS SDK IOS Import issue for AWSSES and AWSSNS

### ISSUE THREAD

**Issue by omargda** [aws/aws-sdk-ios#538]
I'm unable to manually import AWSSES and AWSSNS into my Swift 3 project. I'm attempting to add it through the Embedded Libraries and adding the run script (as per the install guide), but I receive a "Could not build Objective-C module 'AWSSES'" and "Could not build Objective-C module 'AWSSNS'". I've tried aws-ios-sdk-2.4.15, aws-ios-sdk-2.4.14, and aws-ios-sdk-2.4.11, but no difference. Please help, as I've tried for days and tried many different ways, but I'd like to have the aws sdk installed manually, and not with cocoapods or Carthage. Thanks!

**Comment by rohandubal** [comment]
Hi @omargda , thanks for reporting this. I will try to reproduce this issue and get back to you.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hi @omargda ,

I am unable to reproduce this issue. Could you please provided detailed steps to re-produce this? Did you also add AWSCore along with AWSSNS and AWSSES framework files? Please let me know.

Thanks,
Rohan

**Comment by omargda** [comment]
Yeah, I have AWSCore and AWSS3 also added in the project. I was encountering this issue in a project which I'm unable to share, but was able to replicate in another existing project. I can share that project if you could look at it.

**Comment by omargda** [comment]
Here's the link to the project --which is having the exact same errors as the project I'd first encountered the problem in but cannot share. Thanks again for helping! https://github.com/omargda/900test

**Comment by rohandubal** [comment]
Hi @omargda 

I believe this is happening due to they way that `libNine00SecondsSDK.a` uses the AWSS3 SDK internally. Could you please elaborate on what the `libNine00SecondsSDK.a` library does and how does it have a dependency on Core / S3? It is causing some conflicts due to the way its consumed.

Thanks,
Rohan

**Comment by omargda** [comment]
Hello @rohandubal 

I've checked through the project, but the only instance of any AWSS3 by the libNine00SecondsSDK.a library is with it's requirement for me to import both AWSCore and AWSS3 into my project. It uses Core/S3 to store streams.

**Comment by rohandubal** [comment]
Could you try compiling the project without that library? I am not sure how that library is consuming the AWS Frameworks and that might be causing the issue.

Thanks,
Rohan

**Comment by omargda** [comment]
I removed it, and there was no difference. Still the same errors.
