### ISSUE TITLE
AWSS3TransferUtility.uploadFile fails when client time is inaccurate

### ISSUE THREAD

**Issue by gsabran** [aws/aws-sdk-ios#541]
If I advance my iPhone time by one day, and then call `AWSS3TransferUtility.uploadFile`, the request is rejected with status 403 and it seems that the request signing is inaccurate. Is it possible to reliably sign the request, independently of the client time?

Steps to reproduce:
- create a demo that successfully uploads a file through `AWSS3TransferUtility.uploadFile`
- change your iPhone time by adding one day
- check that [didCompleteWithError](https://github.com/aws/aws-sdk-ios/blob/2bd3a512c8b9046f060d5fef39f61c3005114a54/AWSS3/AWSS3TransferUtility.m#L684) is called with status 403

It seems that the expiration relies on the client time to be accurate: https://github.com/aws/aws-sdk-ios/blob/2bd3a512c8b9046f060d5fef39f61c3005114a54/AWSS3/AWSS3TransferUtility.m#L324

**Comment by gsabran** [comment]
If it's impossible to get something more reliable from the client, would it be possible to configure the AWSS3TransferUtilityUploadExpression to have optional date that one could fetch from its server? I'm not good at objective C so I can't really do a PR :(

**Comment by minbi** [comment]
Hi gsabran,

Does this occur if you retry the request?

You may find this resource helpful for your clock skew problem [Documentation](https://aws.amazon.com/blogs/mobile/clock-skew-fix/).

**Comment by gsabran** [comment]
Not sure exactly how do that. My upload looks like:

```swift
let task = transferUtility.uploadFile(
  file,
  bucket: Constants.awsS3BucketName,
  key: key,
  contentType: contentType,
  expression: expression,
  completionHander: { task, error -> Void in
    guard let e = error else {
      fulfill()
      return
    }
    print("(e as NSError).userInfo \((e as NSError).userInfo["AWSClockSkewError"])") // this is nil
    reject(e)
})
```

and when it fails I cannot retry it directly. If you mean that I should restart the upload from the beginning and create a new task, it still fails for me

**Comment by gsabran** [comment]
And looking up `aws_getRuntimeClockSkew` in the repo, I see is used nowhere but in tests

**Comment by gsabran** [comment]
Plus I don't see the skew being used or set in the transfer utilities:
- the expiration is set [here](https://github.com/aws/aws-sdk-ios/blob/2bd3a512c8b9046f060d5fef39f61c3005114a54/AWSS3/AWSS3TransferUtility.m#L324) as `[NSDate dateWithTimeIntervalSinceNow:AWSS3TransferUtilityTimeoutIntervalForResource]`
- there's a check on the expiration being in the future that is also not looking at any skew [here](https://github.com/aws/aws-sdk-ios/blob/2bd3a512c8b9046f060d5fef39f61c3005114a54/AWSS3/AWSS3PreSignedURL.m#L323): `if ([expires timeIntervalSinceNow] < 0.0) {`

Can you confirm that you're able to upload a file with a device whose clock in one day ahead? I tried to manually change the expiration but the request got rejected as well.

**Comment by lux2911** [comment]
We have same issue ! Everything gsabran said it's true....
@minbi you gave us this link https://aws.amazon.com/blogs/mobile/clock-skew-fix/ , but please explain us that code. 
Where are these delegates declared: -(void)request:(AmazonServiceRequest *)request didFailWithError:(NSError *)theError
and
-(void)request:(AmazonServiceRequest *)request didFailWithServiceException:(AmazonServiceException *)theException

,also types AmazonServiceRequest and AmazonServiceException are not found in whole iOS AWS SDK.

**Comment by gsabran** [comment]
@minbi do have an idea of what's not going right?

**Comment by kvasukib** [comment]
Hello @nick3389 

The latest version of the SDK, 2.6.20 released on 6/1/2018, contains this feature. 

        let serviceConfiguration = AWSServiceManager.default().defaultServiceConfiguration
        let transferUtilityConfiguration = AWSS3TransferUtilityConfiguration()
        //Set the timeoutIntervalForResource parameter (in seconds)
        transferUtilityConfigurationWithRetry.timeoutIntervalForResource = 15*60 //15 minutes
        
        AWSS3TransferUtility.register(
            with: serviceConfiguration!,
            transferUtilityConfiguration: transferUtilityConfiguration,
            forKey: "custom-timeout"
        )

        //Instantiate the transfer utility
        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "custom-timeout")
