### ISSUE TITLE
AWSRegionType does not reflect the new regions

### ISSUE THREAD

**Issue by Eightyplus** [aws/aws-sdk-ios#542]
Missing Canada and London!

**Comment by Eightyplus** [comment]
I can see the file is updated in the source repository, but not the CocoaPod.

**Comment by karthiksaligrama** [comment]
its updated @ https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Service/AWSServiceEnum.h#L53, For cocapods try running `pod spec update` and update your local cache

**Comment by Eightyplus** [comment]
Not sure what exactly fixed the problem, probably just cleared the cache 👍
