### ISSUE TITLE
Possible bug in AWSService.m

### ISSUE THREAD

**Issue by trondkr** [aws/aws-sdk-ios#543]
In AWSService.m  in the method listed below I believe there are two options for choice of regions missing?

    - (NSURL *)URLWithRegion:(AWSRegionType)regionType
              regionName:(NSString *)regionName
                 service:(AWSServiceType)serviceType
             serviceName:(NSString *)serviceName
            useUnsafeURL:(BOOL)useUnsafeURL {
    NSURL *URL = nil;

    NSString *separator = @".";
    if (serviceType == AWSServiceS3
        && (regionType == AWSRegionUSEast1
            || regionType == AWSRegionUSWest1
            || regionType == AWSRegionUSWest2
            || regionType == AWSRegionEUWest1
            || regionType == AWSRegionAPSoutheast1
            || regionType == AWSRegionAPNortheast1
            || regionType == AWSRegionAPNortheast2
            || regionType == AWSRegionAPSoutheast2
            || regionType == AWSRegionAPSouth1
            || regionType == AWSRegionSAEast1
            || regionType == AWSRegionUSGovWest1) {
            separator = @"-";
        }

Should be:

        - (NSURL *)URLWithRegion:(AWSRegionType)regionType
              regionName:(NSString *)regionName
                 service:(AWSServiceType)serviceType
             serviceName:(NSString *)serviceName
            useUnsafeURL:(BOOL)useUnsafeURL {
    NSURL *URL = nil;

    NSString *separator = @".";
    if (serviceType == AWSServiceS3
        && (regionType == AWSRegionUSEast1
            || regionType == AWSRegionUSWest1
            || regionType == AWSRegionUSWest2
            || regionType == AWSRegionEUWest1
            || regionType == AWSRegionEUWest2
            || regionType == AWSRegionAPSoutheast1
            || regionType == AWSRegionAPNortheast1
            || regionType == AWSRegionAPNortheast2
            || regionType == AWSRegionAPSoutheast2
            || regionType == AWSRegionAPSouth1
            || regionType == AWSRegionSAEast1
            || regionType == AWSRegionUSGovWest1
            || regionType == AWSRegionCACentral1)) {
            separator = @"-";
        }

Or are there special considerations for the two regions? Cheers, Trond

**Comment by karthiksaligrama** [comment]
if you look @ https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region both "." & "-" notation are supported by S3 in the new regions. So the code should work.
