### ISSUE TITLE
Library not found for lPods

### ISSUE THREAD

**Issue by gleutar** [aws/aws-sdk-ios#544]
Hi, I have inherited an old project which uses objective-c and swift 2.3. 

I wanted to add a new pod and got into trouble. This is my podfile:
`source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target :'fake_project_name' do
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'

end
`

Whatever I do, I get the error Library not found for -lPods. I tried deleting the Podfile.lock and Pods folder and running "pod install" several times. Same goes for "pod update". I created another project (only objective-c), added the same things and it builds. But I need this project and I cannot see where the problem could be. I tried deleting the build folder, the derived data folder, cleaning the workspace, closing, reopening it... you name it.
Ah, and yes, I always open the workspace, not the project in Xcode.
Any suggestion is more than appreciated! 
Thanks!

**Comment by karthiksaligrama** [comment]
Is there a way i can reproduce this? This seems to be more of a project specific issue to me since you say that in a new project same configuration works fine.

**Comment by gleutar** [comment]
@karthiksaligrama I'm afraid that I don't know how to reproduce it. The project works fine with older versions of AWS. The old Podfile looked like this:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target :'scan' do
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'

It used obviously an old version of cocoapods. Not sure how to recreate this. I thought I might have something to do with the swift version? Or the way the AWS sdk updates? Maybe there was a big change that now is not compatible?

**Comment by rohandubal** [comment]
Hi, Are you using Xcode 8 or Xcode 7.3.1? If Xcode 8, have you set your project to use legacy swift version? What is the version of SDK that your project is pulling when you do a pod update? Did you try specifying specific SDK version so that it pulls up frameworks of specific version?

Thanks,
Rohan

**Comment by gleutar** [comment]
HI @rohandubal I'm using Xcode 8. Yes, I've setup the swift legacy code usage for the targets. The swift version is 2.3. I tried several versions of the SDK including the last one. I think it is 2.4.16 or something. In any case, the last one available.
I also tried specific version like 2.0.15 and others but with no success.

**Comment by rohandubal** [comment]
Hi @gleutar 

I tried some things and could not reproduce the issue. I am afraid that without some steps, we wont be able to debug the issue and it really seems that it is project specific. Did you try comparing the configuration of a working project with that of yours?

Thanks,
Rohan

**Comment by gleutar** [comment]
Hi @rohandubal. I'm afraid that I don't know enough about the project to see the difference to a working project. I've already stated all the things I've noticed. I'm afraid that this bug cannot be successfully reproduced without sharing the whole project which I'm not allowed to...

**Comment by rohandubal** [comment]
Hello @gleutar , Sorry, but without further information or reproduction steps, I won't be able to guide you with the issue. I am marking this issue closed now, feel free to open if there are any further concerns.

Thanks,
Rohan
