### ISSUE TITLE
ld: framework not found AWSCore for architecture x86_64 on Xcode UnitTest

### ISSUE THREAD

**Issue by jplongo** [aws/aws-sdk-ios#546]
Everything is working fine when building my project using AWS Frameworks.

But I issue linker error when building my UnitTest. Don't know if it's a bug in your framework but I can't found answer about my problem. So if anybody can help.

Thanks 

Use Xcode 8.2, IOS10 and pod update to 2.4.16

![2016-12-15 at 1 16 pm](https://cloud.githubusercontent.com/assets/22789876/21225013/403d6926-c2cf-11e6-9527-cb748a768034.png)

**Comment by grstavares** [comment]
Hi,

How this issue was solved? I'm having the same trouble..

**Comment by jplongo** [comment]
Hi,
I've solved thins problem by adding AWS SDK manually. Using `Framework` method in official AWS repo 

https://github.com/aws/aws-sdk-ios
