### ISSUE TITLE
Fatal Exception in AWS library 

### ISSUE THREAD

**Issue by eugeneshih** [aws/aws-sdk-ios#547]
I am experiencing a crash that points to a problem in the AWSSignature class. I am using AWS 2.4.11

```
AWSSignature.m line 658
-[AWSS3ChunkedEncodingInputStream nextChunk]
```

I think similar problems have been reported before. See here: https://github.com/aws/aws-sdk-ios/issues/296. The suggested workaround in that issue is to switch to AWSS3TransferUtility but using that class requires us to switch to using AWS Cognito. I think that is a project in itself at the moment, so I think you should fix AWSSignature to prevent the crash.

Here's the source of crash:

```objective-c
    NSInteger read = [self.stream read:chunkBuffer maxLength:defaultChunkSize];

    // mark end of stream if no data is read
    self.endOfStream = (read <= 0);

    NSData *data = [NSData dataWithBytesNoCopy:chunkBuffer length:read];
```

`-[NSInputStream read:maxLength]` can return -1 when an error occurs. Passing -1 as the length parameter to `[NSData dataWithBytesNCopy:length]` will cause it to crash. Thus, you should handle the error condition and return NO from nextChunk, e.g.:

```objective-c
- (BOOL)nextChunk {
    if (self.endOfStream) {
        return NO;
    }

    // clear current chunkData for next chunk
    [self.chunkData setLength:0];

    uint8_t *chunkBuffer = calloc(defaultChunkSize, sizeof(uint8_t));
    NSInteger read = [self.stream read:chunkBuffer maxLength:defaultChunkSize];

    // mark end of stream if no data is read
    self.endOfStream = (read <= 0);

   **if(self.endOfStream) {
       return NO;
   }**

    NSData *data = [NSData dataWithBytesNoCopy:chunkBuffer length:read];
    [self.chunkData appendData:[self getSignedChunk:data]];

    AWSLogVerbose(@"stream read: %ld, chunk size: %lu", (long)read, (unsigned long)[self.chunkData length]);

    return YES;
}
```

**Comment by rohandubal** [comment]
Hi, could you please provide a code snippet for me to re-produce this issue? Does this happen specifically on simulators / devices? Also, is it limited to any iOS version? Please let me know.

Thanks,
Rohan

**Comment by uditarora360** [comment]
Hi,

I also faced the same issue when size of the image is increasing.


Thanks
Udit Arora

**Comment by wdane** [comment]
Resolving as no one has provided a code snippet reproducing or other data @rohandubal asked for.
