### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by batkuip** [aws/aws-sdk-ios#548]
Any chance of getting release notes?  Previously you could get an idea what was updated based on the commits.  However recently it's just massive 99+ file commits with no comments.

**Comment by rohandubal** [comment]
Hi,

All the changes are described in the Change Log file here:
https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md 

Also, all the release notes for iOS SDK are listed here:
https://aws.amazon.com/releasenotes/iOS

Latest:
https://aws.amazon.com/releasenotes/iOS/2445137242229345

Thanks,
Rohan
