### ISSUE TITLE
AWSS3ObjectCannedACLPublicRead not working

### ISSUE THREAD

**Issue by muzammil-triffort** [aws/aws-sdk-ios#550]
When I am setting ACL property in upload request, it stop working and not uploading image. Without adding ACL property, it is uploading photo inside bucket. 

uploadRequest.ACL = AWSS3ObjectCannedACLPublicRead; 

Please suggest, how to fix this.

**Comment by minbi** [comment]
Hi muzammil-triffort,

Do you have the logs for when this occurs?
Have you set your permissions correctly to upload with ACL?
http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

**Comment by muzammil-triffort** [comment]
I have tried with this permission for my bucket:

`   "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
            ],
            "Resource": "*"
        }`

**Comment by minbi** [comment]
Do you mind sharing a code snippet to reproduce?
What version of the SDK are you using?

**Comment by muzammil-triffort** [comment]
Hi @minbi 

Thank you for your support. Actually the issue is fixed now. It was not related to giving ACL property of object but first I have to integrate bucket policy on my bucket. After adding this property. Now I am able to upload images with ACL read property.

Meanwhile, I am using the iOS SDK.

Thank you again for the support.

Best, Muzammil
