### ISSUE TITLE
Dynamo DB Request: The operation couldn’t be completed. Connection reset by peer

### ISSUE THREAD

**Issue by pantuspavel** [aws/aws-sdk-ios#551]
# What's the problem #
Requests to dynamo db fail with the following logs:

```
AWSiOSSDK v2.4.16 [Debug] AWSURLSessionManager.m line:555 | -[AWSURLSessionManager printHTTPHeadersAndBodyForRequest:] | Request body:
{"TableName":"water-mobilehub-2105160602-Locations","IndexName":"Categories","FilterExpression":"#latitude < :latitudeR AND #latitude > :latitudeL","ExpressionAttributeValues":{":longitudeB":{"N":"-74074153"},":latitudeL":{"N":"40707198"},":category":{"S":"Image"},":latitudeR":{"N":"40737176"},":longitudeT":{"N":"-74051914"}},"ExpressionAttributeNames":{"#longitude":"longitude","#category":"category","#latitude":"latitude"},"KeyConditionExpression":"#category = :category AND #longitude BETWEEN :longitudeB AND :longitudeT"}
AWSiOSSDK v2.4.16 [Error] AWSURLSessionManager.m line:212 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error Domain=NSPOSIXErrorDomain Code=54 "Connection reset by peer" UserInfo={_kCFStreamErrorCodeKey=54, _kCFStreamErrorDomainKey=1}
Error: Failed to retrieve items. The operation couldn’t be completed. Connection reset by peer
```

Or sometimes with this logs:
```
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)
AWSiOSSDK v2.4.12 [Error] AWSURLSessionManager.m line:212 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9824, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1728401b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9824, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9824}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://dynamodb.us-east-1.amazonaws.com/, NSErrorFailingURLStringKey=https://dynamodb.us-east-1.amazonaws.com/, _kCFStreamErrorDomainKey=3}
Error: Failed to retrieve items. An SSL error has occurred and a secure connection to the server cannot be made.
```
And I'm pretty sure that adding `NSExceptionAllowsInsecureHTTPLoads` is not the correct answer.

# How to reproduce: #
- Switch from Wi-Fi to LTE or back;
- Pull application from background after being there for 5-10 mins.

**How to fix:**
If, after failed request, allow app to seat for about 3 sec, subsequent requests would run successfully.

# Request / Question: #
- Is my assumption correct that SDK didn't finish reconnecting when request was launched and it potentially was the cause of this problem?
- If so, is there a possible way to get a callback on reconnect finished event?

# Setup: #
Swift iOS project generated with:
```
Source code generated from template: aws-my-sample-app-ios-swift v0.6
```

Any suggestions on how to fix the problem would be appreciated.

**Comment by pantuspavel** [comment]
Any suggestion how to fix the issue? Kind of a deal breaker for me.

**Comment by pantuspavel** [comment]
I can see the following in my logs:
```
[] nw_coretls_read_one_record tls_handshake_process: [-9824]
```
and it might be related to [this](http://stackoverflow.com/questions/38962923/nw-coretls-read-one-record-tls-handshake-process-9801)

**Comment by rohandubal** [comment]
Hello @pantuspavel 

Sorry to hear that you are facing the issue, Please let us know the findings after you  try the ATS settings. You can refer them here as well: http://docs.aws.amazon.com/mobile/sdkforios/developerguide/ats.html 

Could you also provide some additional details:

-Since you mention LTE, I assume its an actual device. Does it happen on simulator as well?
-What is the iOS version?
-What is the Xcode version?
-Can you download the latest sample from Mobile Hub and confirm if issue is persistent? 

Thanks,
Rohan

**Comment by pantuspavel** [comment]
Hey @rohandubal

Yeah, [ATS settings](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/ats.html) did the trick for me.
The problem can be considered solved and I'm closing the issue.
I can confirm that sample project from Mobile Hub contains required ATS settings.

Since it was a complete surprise for me, I would suggest making this guide an integration step in Mobile Hub. Something like - "Hey, make sure you take a look at the ATS settings article or go to sample app info.plist and check out ATS section".

It slipped through my fingers because I used sample app as a reference and was building app in separate project.

Details:
- iPhone 6S
- iOS 10.1
- xCode 8.1 (8B62)
- Confirmed - ✅
