### ISSUE TITLE
Network calls do not show/hide network activity indicator

### ISSUE THREAD

**Issue by hhartz** [aws/aws-sdk-ios#555]
See e.g. https://github.com/Alamofire/AlamofireNetworkActivityIndicator which manages the activity indicator for the user. I assume `AWSNetworkingHTTPResponseInterceptor` could be used for this, but there is no documentation or examples that demonstrate how this should be used.

**Comment by zhihuitang** [comment]
same question, how to use AWSNetworkingHTTPResponseInterceptor properly?
