### ISSUE TITLE
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Thu, 22 Dec 2016 09:18:57 GMT, x-amz-request-id=78B8E6E4E4A1EBDC, x-amz-id-2=xml8ZvBcC0xDPY8uJGadzfQy4C4iFZsaBEYvMuAsD/81zCc3gVSsscX6IbXWHWxhgnvlVH6TGGU=

### ISSUE THREAD

**Issue by wangxiaokui** [aws/aws-sdk-ios#556]
printHTTPHeadersAndBodyForRequest:] | Request headers:
{
	User-Agent = aws-sdk-iOS/2.4.16 iOS/10.0.2 zh_CN,
	X-Amz-Target = AWSCognitoIdentityService.GetCredentialsForIdentity,
	X-Amz-Date = 20161222T091846Z,
	Content-Type = application/x-amz-json-1.1,
	Host = cognito-identity.us-east-1.amazonaws.com
}

**Comment by damathryx** [comment]
how did you solve this?

**Comment by ramki982** [comment]
@damathryx whenever u get this - convert the nsdata received in the callback to a string and log it.
That will give u vital clues. I see the same code returned by SDK in various scenarios but the nsdata has the XML response from the server which is vital
