### ISSUE TITLE
Plans for pure Swift port?

### ISSUE THREAD

**Issue by pawlowskialex** [aws/aws-sdk-ios#558]
Server-side Swift is getting big, with multiple web libraries, database connectors, parsers, template engines, etc, available now or being developed.

AWS is a major platform, and probably is the default choice for many of us, but the lack of pure Swift AWS SDK really puts the brakes on our attempts at server-side Swift.

I think I'm not the only one who would like to give it a go for at least some minor parts of production stack.

What do you think?
Thanks

**Comment by karthiksaligrama** [comment]
Thanks for your feedback. At this point we have no plans for supporting a pure swift sdk, but i'll pass this request along to the team.

**Comment by kcfancher** [comment]
I'd love this as well. It would be great to have a single library for Swift that could be used for macOS, iOS, or the server that isn't dependent on any platform specific libraries. 

Something like the aws-sdk-go library which is language, not platform, specific.
