### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by brunomacabeusbr** [aws/aws-sdk-ios#560]
Sometimes, **the same code** work in moment, and fail in others moments. I'm using S3.

I receive the error message `Session task failed with error: Error Domain=NSPOSIXErrorDomain Code=54 "Connection reset by peer"`. Why? I didn't change my network, the file, or anything.

**Comment by mlshon** [comment]
Can you please provide more information?
Code snippet?
What SDK version are you using?

**Comment by brunomacabeusbr** [comment]
This problem happen some times in my pod: https://github.com/brunomacabeusbr/RuAWSS3
This pod using AWSS3 version 2.4.16

**Comment by mlshon** [comment]
Can you point me to the specific section of code? 
And is there a stacktrace available?

**Comment by brunomacabeusbr** [comment]
The problem happned when made a request to Amazon. For example, happened in lines like:
```swift
public func upload(bucket: String, key: String, filePath: URL) -> Promise<Void> {
    let uploadRequest = AWSS3TransferManagerUploadRequest()!
    uploadRequest.body = filePath
    uploadRequest.key = key
    uploadRequest.bucket = bucket
        
    let transferManager = AWSS3TransferManager.default()!
        
    return Promise { fulfill, reject in
        transferManager.upload(uploadRequest).continue({ // ** this line!! **
            ...
```

another example

```swift
public func download(bucket: String, key: String) -> Promise<String> {
    ....
    let downloadRequest = AWSS3TransferManagerDownloadRequest()!
    downloadRequest.bucket = bucket
    downloadRequest.key = key
                    
    let transferManager = AWSS3TransferManager.default()!
    transferManager.download(downloadRequest).continue({ // ** this line **
        ...
```

My sincere apologies, but my macbook is in repair... I'm using a borrowed computer with Windows... Then, now, I can't create a "satisfactory answer", but, I will try to reproduce the error these days with another (borrowed) macbook.

In my old tests, when I uploaded/downloaded image, some times works, and some times fails. I do not remember if I need to restart the application when works to reproduce the error.
I not need change the code or network to reproduce the error.

**Comment by r-plus** [comment]
I also found this problem in my application with version 2.4.5 aws-ios-sdk.

In my case, I'm using `headObject` and `listObjects` methods with `AWSS3` individual service client and `download` method with `AWSS3TransferManager` service client.
My application task chaining flow is `listObjects` then `headObject` then `download`.

- First `Connection reset by peer` error is occurred `download` method, `headObject` and `listObjects` task are successfully each retry.
- Seconds, after first  `Connection reset by peer` error with download `headObject` task also occurred.
- Finally, `listObjects` task occurred too.

So I'm thinking this problem related service client instance.
I'll try recreate service client when get this error.

**Comment by wdane** [comment]
This is likely due to generic networking issues, such as the connection being dropped while switching from wi-fi to cell, cell reception falling in and out, ect... This is not an issue with the SDK itself, but app developers due need to make sure their app gracefully handles networking problems.

**Comment by svsharsha** [comment]
I still face this issue occasionally.
Code=-1005 "The network connection was lost." 

NSLocalizedDescription=The network connection was lost., _kCFStreamErrorDomainKey=4, NSUnderlyingError=0x16ec4e60 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4}}}--1005

**Comment by nastasiupta** [comment]
This also happens to me when I move the app to the background and lock the phone... any solution on this?
