### ISSUE TITLE
AWSCredentialsProvider fails to properly refresh aws token from developer identity on subsequent expired token calls

### ISSUE THREAD

**Issue by donileo** [aws/aws-sdk-ios#562]
Major bug! On encountering an expired or unathorized token the AWSCredentialsProvider class will fail to refresh the AWS token correctly on subsequent expired or unauthorized tokens. This is due because on the first expired/unauth'ed token received the self.hasClearedIdentityId is set but never cleared. Now whenever an expired token happens again (and it will) the custom developer identity provider is never asked to refresh the aws token hereby placing us in an error loop that can only be fixed by clearing the aws keychain completely and starting the login process again. 

So heres the problem flow:

Make a call to S3 with expired token -> AWSCredentialsProvider makes the call but AWS API returns that the token used is expired/unauthorized -> AWSCredentialsProvider clears the identityId and sets self.hasClearedIdentityId to YES, then it "refreshes" the token by calling [providerRef logins] -> AWSCredentialsProvider then retries the call with the refreshed token and everything is fine and dandy.

Sometime later (anytime later) make another call to S3 with expired token ->AWSCredentialsProvider makes the call and AWS API returns again that the token used is expired/unauthorized -> AWSCredentialsProvider DOES NOT ask the developer provider identity provider to refresh the token and it also does not retry the call because on the first call above the self.hasClearedIdentityId was set AND NOT cleared. So now AWSCredentialsProvider simply returns that there was an error clearing the identityId when there truly wasn't. It hasn't even cleared the identityId for this call. All future calls now will fail because we have a chicken egg problem. The aws token is expired but the aws sdk fails to ask the identity provider to refresh it.

Here are the lines of code that are responsible in  getCredentialsWithCognito:authenticated: customRoleArn (starts in line 416 of file AWSCredentialsProvider.m)

```
return [[[self.cognitoIdentity getCredentialsForIdentity:getCredentialsInput] continueWithBlock:^id(AWSTask *task) {
        // When an invalid identityId is cached in the keychain for auth,
        // we will refresh the identityId and try to get credentials token again.
        if (task.error) {
            AWSLogError(@"GetCredentialsForIdentity failed. Error is [%@]", task.error);

            // If we should reset IdentityId, clears it and retries.
            // Otherwise, simply returns the error to the caller.
            if (![AWSCognitoCredentialsProvider shouldResetIdentityId:task.error
                                                        authenticated:isAuthenticated]) {
                return task;
            }

            if (self.hasClearedIdentityId) {
                return [AWSTask taskWithError:[NSError errorWithDomain:AWSCognitoCredentialsProviderErrorDomain
                                                                  code:AWSCognitoCredentialsProviderInvalidConfiguration
                                                              userInfo:@{NSLocalizedDescriptionKey : @"GetCredentialsForIdentity keeps failing. Clearing identityId did not help. Please check your Amazon Cognito Identity configuration."}]];
            }

            AWSLogDebug(@"Resetting identity Id and calling getIdentityId");
            // if it's auth, reset id and refetch
            self.identityId = nil;
            providerRef.identityId = nil;
            self.hasClearedIdentityId = YES;

            return [[providerRef logins] continueWithSuccessBlock:^id _Nullable(AWSTask<NSDictionary<NSString *,NSString *> *> * _Nonnull task) {
                NSDictionary<NSString *,NSString *> *logins = task.result;

                // This should never happen, but just in case
                if (!providerRef.identityId) {
                    AWSLogError(@"In refresh, but identitId is nil.");
                    AWSLogError(@"Result from getIdentityId is %@", task.result);
                    return [AWSTask taskWithError:[NSError errorWithDomain:AWSCognitoCredentialsProviderHelperErrorDomain
                                                                      code:AWSCognitoCredentialsProviderHelperErrorIdentityIsNil
                                                                  userInfo:@{NSLocalizedDescriptionKey: @"identityId shouldn't be nil"}]];
                }
                self.identityId = providerRef.identityId;

                AWSLogDebug(@"Retrying GetCredentialsForIdentity");

                // retry get credentials
                AWSCognitoIdentityGetCredentialsForIdentityInput *getCredentialsRetry = [AWSCognitoIdentityGetCredentialsForIdentityInput new];
                getCredentialsRetry.identityId = self.identityId;
                getCredentialsRetry.logins = logins;
                getCredentialsRetry.customRoleArn = customRoleArn;

                return [self.cognitoIdentity getCredentialsForIdentity:getCredentialsRetry];
            }];
        }
```

I have submitted pull request #563. Let me know your thoughts.

**Comment by karthiksaligrama** [comment]
are you using the code that you have suggested in #357 ?

**Comment by donileo** [comment]
Yes I am. Still believe this is a bug. See that self.hasClearedIdentityId = YES; ? Wheres that being cleared on subsequent requests?

**Comment by donileo** [comment]
So given what you guys have told me on issue #357, that the manager is not used in developer federated identities, now I have to ask why is it the identityId is cleared? Clearing the identityId with no manager would have no effect in this code as the nested call to providerRef logins is going to call the tokens method and that is going to return right away stating there is a valid token. In the provide a identity provider manager flow this is fine, but in the developer federated identies flow with no manager this is not fine, its the token that should be cleared.

**Comment by johnmorrell** [comment]
I am also experiencing the same issue and ongoing frustrations with Cognito Developer auth on iOS.

**Comment by markuswinkler** [comment]
Has anyone solved this yet? Running into the same problem.

**Comment by npalethorpe** [comment]
This sounds like an issue I am currently experiencing - any solutions?

**Comment by markuswinkler** [comment]
@donileo Did you come up with a solve/workaround?

**Comment by donileo** [comment]
@markuswinkler I believe my pull request referenced up top solves this issue. I submitted it awhile ago so the source has changed sinced then so I believe it shoult still work. Regardless I'll take a look at the latest source and see if my PR is still good.

**Comment by markuswinkler** [comment]
@donileo Great! Thank you, I really appreciate it!
