### ISSUE TITLE
Using AWSCognitoCredentialsProvider with multiple services

### ISSUE THREAD

**Issue by kdbertel** [aws/aws-sdk-ios#564]
Previously, our code highly coupled an `AWSCognitoCredentialsProvider` with `AWSCognitoIdentityUserPool` to provide basic user sign-up. However, now we need to include third-party verification as peers to the Cognito User Pools authentication, all under the Cognito Identity Pool umbrella (side note: that these two things are both called "Cognito" has confused me and my peers on multiple occasions).

The [documentation](http://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html) still refers to the `logins` dictionary, and is so horrifically out of date to be useless.

Currently, we are calling `-setIdentityProviderManagerOnce:` on our instance of `AWSCognitoCredentialsProvider` to set the identity manager to the instance of `AWSCognitoIdentityUserPool` we have. However, when we add Facebook, Twitter, et cetera, we presumably are going to have Identity Providers for them, so how do we accomplish this with only setting the Identity Provider Manager Once?

Is there any up-to-date documentation (or better, sample code) that demonstrates how to perform user authentication on Cognito Identity Pools with 3rd-party services and Cognito User Pools as peers in the authentication process?

**Comment by karthiksaligrama** [comment]
did you take a look @ https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

**Comment by kdbertel** [comment]
Yes, but it's not relevant to me because we aren't using developer-authenticated identities. We are only using Cognito User Pools and other 3rd party methods.

**Comment by behrooziAWS** [comment]
The approach is the same as how to use multiple providers described in that doc, you need to create a IdentityProviderManager that is capable of determining how the user is authenticated and returns a logins map containing the appropriate token:

- (AWSTask<NSDictionary<NSString *, NSString *> *> *)logins {
    if (/*logic to determine if user is Facebook*/){
        return [AWSTask taskWithResult: @{ AWSIdentityProviderFacebook : [FBSDKAccessToken currentAccessToken] }];
    } else if (/*logic to determine if user is authenticated with user pools*/ {
        //this assumes you have passed in a userPool object and have access to it
        return [userPool logins];
    } else //user is unauth
    {
        return [AWSTask taskWithResult:nil];
    } 
}

Using AWSMobileHubHelper may be your simplest path to success here as it supports the Identity Providers you need.  https://github.com/aws/aws-mobilehub-helper-ios/tree/master/AWSMobileHubHelper  Try generating a mobile hub project as a starting point using the AWS Console that supports the Identity Providers you want to use to see the code.
