### ISSUE TITLE
AWSLogger should allow plugging in logging frameworks like CocoaLumberjack

### ISSUE THREAD

**Issue by ramki982** [aws/aws-sdk-ios#566]
Hi all,

The AWS Logger in the iOS SDK just writes the log messages to console using NSLog. I'm referring to the method. 
- (void)log:(AWSLogLevel)logLevel format:(NSString *)fmt, ... NS_FORMAT_FUNCTION(2, 3).

This makes it difficult to redirect logs to a file as NSLog messages are not visible when running on phone from ios 10 as apple moved to unified logging from ASL. 

Instead if there is a mechanism to plugin some thirdparty framework like CocoaLumberJack, it will help.

thanks
Ram

**Comment by karthiksaligrama** [comment]
Thanks i added this to the feature requests, I'll update when we have it available.

**Comment by ramki982** [comment]
Thanks a lot Karthik

**Comment by karthiksaligrama** [comment]
fixed with 2.5.4
