### ISSUE TITLE
Does passing nil to completion handler prevent app from resuming?

### ISSUE THREAD

**Issue by andrewkouri** [aws/aws-sdk-ios#569]
I am uploading a bunch of large files at once, however I am concerned that my app is running into the resume-rate-limiter.  This is not well documented, but I found this thread on the apple developer forums.  https://forums.developer.apple.com/thread/14854

I am using the Transfer Utility to upload to S3 in background. When the app moves to background, I dispatch ~30 upload sessions.  I do not want the completion handler for every single upload that finishes to get called.  How can I make it so that the app resumes only when ALL 30 uploads are finished?

**Comment by andrewkouri** [comment]
https://forums.developer.apple.com/thread/10239?q=background%20upload#10239 See this post -- I'm wondering if the library has any way to specify whether all urlsessiontasks go on the same session. https://forums.developer.apple.com/thread/10239?q=background%20upload#10239

**Comment by minbi** [comment]
You can try creating an aggregate of the tasks `AWSTask(forCompletionOfAllTasks: tasks).continueOnSuccessWith{...}`

**Comment by andrewkouri** [comment]
Right, but I believe the original `AWSS3TransferUtilityUploadTask` has it's own `completionHandler` that gets fired each time that individual file finishes uploading.

**Comment by andrewkouri** [comment]
Also, the `forCompletionOfAllTasks` just handles the case where TransferUtility initiates the upload. It doesn't wait for all the individual AWSS3TransferUtilityUploadTasks to run their completion handler.

**Comment by andrewkouri** [comment]
http://stackoverflow.com/questions/38057067/parallell-download-of-objects-from-a-aws-s3-bucket-on-ios-swift

**Comment by karthiksaligrama** [comment]
The solution mentioned in the stackoverflow is correct. Closing this issue. Please reopen if you continue to face this problem
