### ISSUE TITLE
AWSAPIGatewayClient still needs bridging header for use with Swift 3

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#573]
So I was hooping the new 2.5.0 would work better with Swift 3. But attempting to use the AWSAPIGatewayClient I still need to import a bridging header to be able to use it and set the configuration.

Would be nice to not have to do this as I believe it slows things down.

**Comment by wdane** [comment]
We have this in our backlog from https://github.com/aws/aws-sdk-ios/issues/510 . I'm going to close this issue as a duplicate to help reduce noise. If you think there is value in keeping this open to the public then feel free to re-open.
