### ISSUE TITLE
MobileAnalytics in Swift

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#575]
So, if I follow the instructions and convert it to Swift using

        let analyticsConfiguration = AWSMobileAnalyticsConfiguration()
        let analytics = AWSMobileAnalytics(forAppId: Constants.analyticsAppId, configuration: analyticsConfiguration)!

My app keeps loosing it session and I have to log in again every time. Seems it messes with the AWSServiceConfiguration and AWSCognitoCredentialsProvider

If I instead use the deprecated method AWSMobileAnalytics(forAppId: Constants.analyticsAppId, identityPoolId: Constants.identityPoolId)

it works fine.

Are there any full instructions how to set this up to work with AWSCognitoCredentialsProvider and AWSServiceConfiguration?

**Comment by minbi** [comment]
MobileAnalytics is being deprecated. Please use `AWSPinpoint`.

**Comment by helloniklas** [comment]
@minbi oh ok, good to know. Turns out the region our Cognito and APIGateway is in, is not supported anyway so have no choice but use Google Analytics instead.

**Comment by rcha** [comment]
You should be still able to setup Pinpoint or Mobile Analytics in us-east-1 and setup Cognito in a different region. 

Can you elaborate more on your use case and your setup with more code samples.

**Comment by helloniklas** [comment]
@rcha The docs and samples for mobile analytics explicitly states that cognitio needs to be in us east region as well. I will give it a go with pinpoint to see if it works.

**Comment by rcha** [comment]
@helloniklas 

In order to initialize pinpoint with a Cognito Credentials Provider in a different Region you will just need to change the region you defined for Cognito inside you plist file. 

```javascript
<key>AWS</key>
<dict>		
<key>CredentialsProvider</key>
<dict>
	<key>CognitoIdentity</key>
	<dict>
		<key>Default</key>
		<dict>
			<key>PoolId</key>
			<string>YOUR_COGNITO_POOL_ID_GOES_HERE</string>
			<key>Region</key>
			<string>YOUR_COGNITO_REGION</string>
		</dict>
	</dict>
</dict>
<key>PinpointAnalytics</key>
<dict>
	<key>Default</key>
	<dict>
		<key>AppId</key>
		<string>YOUR_APP_ID_GOES_HERE</string>
		<key>Region</key>
		<string>us-east-1</string>
	</dict>
</dict>
<key>PinpointTargeting</key>
<dict>
	<key>Default</key>
	<dict>
		<key>Region</key>
		<string>us-east-1</string>
	</dict>
</dict>
```
And then you will need to initialize the SDK with the default initializer which takes the credentials from your plist file:
```swift
let config: AWSPinpointConfiguration = AWSPinpointConfiguration.defaultPinpointConfigurationWithLaunchOptions(launchOptions);
pinpoint = AWSPinpoint.init(configuration:config)
```

If you do not want to use the default initializers with the plist configuration you can initialize the SDK with the following:
```swift
let cognitoCredentialsProvider: AWSCognitoCredentialsProvider = AWSCognitoCredentialsProvider.init(regionType: AWSRegionType.USEast1, identityPoolId:"YOUR_COGNITO_POOL_ID"); //Override Your Region Here
        
let serviceConfig: AWSServiceConfiguration = AWSServiceConfiguration.init(region: AWSRegionType.USEast1, credentialsProvider: cognitoCredentialsProvider)

let config: AWSPinpointConfiguration = AWSPinpointConfiguration.init(appId: "YOUR_APP_ID", launchOptions: launchOptions);

config.serviceConfiguration = serviceConfig;
config.targetingServiceConfiguration = serviceConfig;

pinpoint = AWSPinpoint.init(configuration:config)
```

I do not recommend keeping your Cognito Pool in a different region than the service you are using even tho it is possible. 

My recommendation is for you to have multiple Cognito Pool Ids, each in the respective region of the service you are using. To do that you will need to initialize multiple instances of AWSCognitoCredentialsProvider.

Hope that helps.

**Comment by helloniklas** [comment]
@rcha thanks for this very helpful. I'm however a bit confused about the region stuff. We have APIGateway calling Lambdas, S3, Elasticsearch and what not all in EU West region, so I assumed I have to auth against Cognito also in EU West in order to be able to call APIGateway, S3 etc. But you're saying I could set up Cognito for US EAST1 and still call APIGateway in EU WEST?

Any chance PIN Point will be added to more regions soon?

**Comment by behrooziAWS** [comment]
Cognito vended credentials are usable against services in any region.  There are two exceptions to this.  

1. If you are using Cognito sync, it must be in the same region as your Cognito Identity Pool.
2. If you are using API Gateway with Cognito Authorizers (not Sig-V4) it must be in the same region as your Cognito User Pool.

**Comment by helloniklas** [comment]
@rcha So I've implemented this per your suggestion, modifying the plist file to point Cognito in a different region. The debug log spits out that it successfully sent event. However, nothing shows up in the pinpoint console... I've waited some hours now. How soon is it mean to appear?

**Comment by helloniklas** [comment]
@rcha So I think changing the region inside the plist might not be enough. MobileHub has to be set up in us east region and will not see the Cognito in another region. Not sure why PinPoint has to rely on MobileHub. I have an existing setup that wasn't using MobileHub. Setting everything up, no events shows up in Pinpoint. Might have to go with Google Analytics anyway, since that just works with a couple of lines of code.

**Comment by helloniklas** [comment]
right, got this working now, but only if I use the cognito pool that MobileHub sets up... it's a bit confusing this. Since I already have Cognito set up with auth0 I thought I should use the same Cognito for this, but seems that not possible. So my app will have several Cognito pools which seems a bit odd.

**Comment by rcha** [comment]
@helloniklas Have you been able to get your events to show up in the Pinpoint console? 

What is the error you get when using your existing cognito pool you have setup with auth0.

**Comment by helloniklas** [comment]
@rcha yes as my comment per above, this now works. I was before trying to connect this to my existing Cognito Pool, that didn't work. If I had mobile hub set up a new Cognito Resource in eu west it works, while still using my other eu west Cognito Pool for auth0.

**Comment by rcha** [comment]
Glad to hear it works with a different Cognito Pool Id, however it should also work with your existing Cognito Pool for auth0, one possibility of why it might not be working would be if you have not enabled Unauth authentication for that Cognito Pool Id. 

Amazon Cognito can support unauthenticated identities by providing a unique identifier and AWS credentials for users who do not authenticate with an identity provider. If your application allows users who do not log in, you can enable access for unauthenticated identities. To learn more, see Identity Pools.

From the Console home page:

Click the name of the identity pool for which you want to enable or disable unauthenticated identities. The Dashboard page for your identity pool appears.
In the top-right corner of the Dashboard page, click Edit identity pool. The Edit identity pool page appears.
Scroll down and click Unauthenticated identities to expand it.
Select the checkbox to enable or disable access to unauthenticated identities.
Click Save Changes.

For for information you can checkout these docs: http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-console.html
