### ISSUE TITLE
App Store Review: API Gateway IPv6 support

### ISSUE THREAD

**Issue by aymericio** [aws/aws-sdk-ios#576]
We encounter a problem of validation with our application. Apple have rejected it about the compatibility with IPv6. All our APIs are based on API Gateway.

Our team have tried to add a CloudFront IPv6 ahead API Gateway but without success with IAM. Do you have any solution that can help us?

Our app: Swift, iOS: 10.0, SDK: 2.4.16

Many thanks

**Comment by minbi** [comment]
Have you tested using Apple's [documentation](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1)

**Comment by gokhanakkurt** [comment]
Hey @aymericio, I have the same problem. Have you found a solution for this issues?

**Comment by aymericio** [comment]
I wrote to Apple to explain than we don't this problem of our side with the conditions of the test provided in the [documentation](https://developer.apple.com/support/ipv6/).

Then Apple have validated the build. The problem never came back on.

Good luck 😊
