### ISSUE TITLE
SDK response upload success, but file does not exists

### ISSUE THREAD

**Issue by jhondge** [aws/aws-sdk-ios#579]
Use the AWSS3TransferUtility(reference this [guide)](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html) to upload file to my bucket and set the completionHandler block. In sometimes completionHandler block the response error is nil(it's means upload successfully), but it's not exists on amazon console.

**Comment by minbi** [comment]
Hi @jhondge,

Are you able to reproduce this consistently under certain conditions?
For reference, which version SDK are you using?

**Comment by jhondge** [comment]
Hi @minbi ,
Thanks for your response, but I can't reproduce this case, It was presented in our custom log file. It's have 3 times occur of 600 times upload. and We're using the SDK version is 2.3.6.

**Comment by minbi** [comment]
There seems to have been some issue fixes released in 2.4.1 that may address your issue. But I would advise upgrading to 2.5.0 (latest) if it is possible.

**Comment by jhondge** [comment]
Ok We will upgrade to the latest version,Thanks a lot.

**Comment by minbi** [comment]
You could request head information for the object immediately after uploading for definitive confirmation. But this will cost an extra call.

**Comment by karthiksaligrama** [comment]
if you are using cocoapods, you can continue using static frameworks. But as @minbi suggested you should move to latest sdk
