### ISSUE TITLE
Crash - AWSPinpoint: -[AWSPinpointSessionClient saveSession]

### ISSUE THREAD

**Issue by EntreGulss** [aws/aws-sdk-ios#580]
I've got crashes at `AWSPinpoint: -[AWSPinpointSessionClient saveSession]`.
Not a small number of crashes, but a certain level of bug. Screenshot below.

<img width="1187" alt="2017-02-06 22 09 23" src="https://cloud.githubusercontent.com/assets/5502175/22648247/132114ce-ecb9-11e6-8dcd-ebaf2390dec6.png">

I cannot figure out what's going on. please fix it.

**Comment by EntreGulss** [comment]
It happens when `AWSPinpoint` instance is initialized. But not always but sometimes.

**Comment by mlshon** [comment]
Hi,
Can you please provide some more details?
What is the SDK version? Stacktrace?

**Comment by EntreGulss** [comment]
I use CocoaPods to install `AWSPinpoint` SDK. The version is `2.4.16`.
```
pod "AWSPinpoint", "~> 2.4.16"
```

And the below is the Crashlytics log.
<img width="974" alt="2017-02-07 9 10 05" src="https://cloud.githubusercontent.com/assets/5502175/22672309/5925e014-ed16-11e6-8616-60fe5241d370.png">

```
Crashed: fmdb.<AWSFMDatabaseQueue: 0x17024bf70>
0  KMPlaceholderTextView          0x18ff82f70 (Missing)
1  KMPlaceholderTextView          0x191fac0c0 (Missing)
2  KMPlaceholderTextView          0x191fb331c (Missing)
3  AWSPinpoint                    0x10093f068 -[AWSPinpointSessionClient saveSession] (AWSPinpointSessionClient.m:115)
4  AWSPinpoint                    0x10093fc84 -[AWSPinpointSessionClient startNewSession] (AWSPinpointSessionClient.m:221)
5  AWSPinpoint                    0x10093f298 -[AWSPinpointSessionClient session] (AWSPinpointSessionClient.m:143)
6  AWSPinpoint                    0x1009372c8 __69-[AWSPinpointEventRecorder updateSessionStartWithCampaignAttributes:]_block_invoke_2 (AWSPinpointEventRecorder.m:277)
7  AWSCore                        0x100799f80 __49-[AWSFMDatabaseQueue beginTransaction:withBlock:]_block_invoke (AWSFMDatabaseQueue.m:187)
8  KMPlaceholderTextView          0x1903c21bc (Missing)
9  KMPlaceholderTextView          0x1903cf7f0 (Missing)
10 AWSCore                        0x100799ec0 -[AWSFMDatabaseQueue beginTransaction:withBlock:] (AWSFMDatabaseQueue.m:198)
11 AWSPinpoint                    0x100937150 __69-[AWSPinpointEventRecorder updateSessionStartWithCampaignAttributes:]_block_invoke (AWSPinpointEventRecorder.m:286)
12 AWSCore                        0x1007c7890 __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke (AWSTask.m:410)
13 AWSCore                        0x1007c7134 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 (AWSTask.m:336)
14 KMPlaceholderTextView          0x1903c21fc (Missing)
15 KMPlaceholderTextView          0x1903c21bc (Missing)
16 KMPlaceholderTextView          0x1903d03dc (Missing)
17 KMPlaceholderTextView          0x1903c59a4 (Missing)
18 KMPlaceholderTextView          0x1903d08d8 (Missing)
19 KMPlaceholderTextView          0x1903d234c (Missing)
20 KMPlaceholderTextView          0x1903d20ac (Missing)
21 KMPlaceholderTextView          0x1905cb2a0 (Missing)
22 KMPlaceholderTextView          0x1905cad8c (Missing)
```

**Comment by noboomu** [comment]
Experiencing same issue...

**Comment by CooperCodeComposer** [comment]
Still experiencing this issue. Looks like it's happening when we send out a push notification using Pinpoint. Approximately 15% of users who click on the push experience this crash. 

Any help much appreciated! 

AWS pinpoint 2.5.6 via cocoapods

![aws pinpoint crash](https://cloud.githubusercontent.com/assets/16313589/26078787/7cf62ce6-3975-11e7-9b27-53260ae23cdf.png)

**Comment by noboomu** [comment]
Any news on this @karthiksaligrama?

**Comment by kvasukib** [comment]
We have fixed it in 2.5.9

**Comment by itsmeichigo** [comment]
I just got the same issue with the exact same stack trace using version 2.6.11. Please take a look again?

**Comment by adjustnox** [comment]
Yes, please reopen this, we had the same issue again as well as of Mar 14.

**Comment by kubbing** [comment]
Bump, same issue here in production :/.
