### ISSUE TITLE
Unity game not connecting to AWS on iOS

### ISSUE THREAD

**Issue by Serinoxxx** [aws/aws-sdk-ios#581]
Hello,

I have setup AWS in my Unity game and it works fine in the editor and on Android but when I test it on iOS it doesn't seem to access AWS properly.

I have added the NSAppTransportSecurity elements to my info.plist file but that doesn't seem to help.

If it helps, the services I'm using are Cognito and SimpleDB.

This is the error I get from the Xcode debugger when trying to access AWS:

    NullReferenceException: A null value was found where an object instance was required. at Amazon.AWSConfigs.get_LoggingConfig () [0x00000] in :0 at Amazon.Runtime.ClientConfig..ctor () [0x00000] in :0 at Amazon.CognitoIdentity.AmazonCognitoIdentityConfig..ctor () [0x00000] in :0 at Amazon.CognitoIdentity.AmazonCognitoIdentityClient..ctor (Amazon.Runtime.AWSCredentials credentials, Amazon.RegionEndpoint region) [0x00000] in :0 at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor (System.String accountId, System.String identityPoolId, System.String unAuthRoleArn, System.String authRoleArn, Amazon.RegionEndpoint region) [0x00000] in :0 at GameControl.get_Credentials

This is how credentials is defined:

```
private CognitoAWSCredentials _credentials;

public CognitoAWSCredentials Credentials
{
    get
    {
        if (_credentials == null)
            _credentials = new CognitoAWSCredentials("IDENTITY_POOL_HERE", RegionEndpoint.APSoutheast2);
        return _credentials;
    }
}
```

Thanks for any help

**Comment by minbi** [comment]
Hi @Serinoxxx,

Please see if you have setup `awsconfig.xml` [instructions](https://github.com/aws/aws-sdk-net/blob/master/Unity.README.md#unity-sdk-fundamentals).

**Comment by Serinoxxx** [comment]
Hi @minbi,

Thanks for the reply.

I have added awsconfig.xml in my Assets/Resources folder and link.xml in my Assets root folder but still getting the same error.

I saw in some tutorials that UnityInitializer.AttachToGameObject(this.gameObject); is used but this is not available to me for some reason. Do you think this could be the issue? Have you successfully used AWS with iOS?

Thanks,
Lance

**Comment by Serinoxxx** [comment]
I don't know why but my link.xml isn't showing up. Here it is:

`<linker>

<assembly fullname="UnityEngine">
    <type fullname="UnityEngine.Experimental.Networking.UnityWebRequest" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.UploadHandlerRaw" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.UploadHandler" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.DownloadHandler" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.DownloadHandlerBuffer" preserve="all" />
</assembly>
<assembly fullname="mscorlib">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
</assembly>
<assembly fullname="System">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
</assembly>
<assembly fullname="AWSSDK.Core" preserve="all"/>
<assembly fullname="AWSSDK.CognitoIdentity" preserve="all"/>
<assembly fullname="AWSSDK.SecurityToken" preserve="all"/>
<assembly fullname="AWSSDK.SimpleDB" preserve="all"/>
  <assembly fullname="AWSSDK.DynamoDBv2" preserve="all"/>
</linker>`

**Comment by Serinoxxx** [comment]
<?xml version="1.0" encoding="utf-8"?>
<linker>

<assembly fullname="UnityEngine">
    <type fullname="UnityEngine.Experimental.Networking.UnityWebRequest" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.UploadHandlerRaw" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.UploadHandler" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.DownloadHandler" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.DownloadHandlerBuffer" preserve="all" />
</assembly>
<assembly fullname="mscorlib">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
</assembly>
<assembly fullname="System">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
</assembly>
<assembly fullname="AWSSDK.Core" preserve="all"/>
<assembly fullname="AWSSDK.CognitoIdentity" preserve="all"/>
<assembly fullname="AWSSDK.SecurityToken" preserve="all"/>
<assembly fullname="AWSSDK.SimpleDB" preserve="all"/>
  <assembly fullname="AWSSDK.DynamoDBv2" preserve="all"/>
</linker>

**Comment by Serinoxxx** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<linker>

<assembly fullname="UnityEngine">
    <type fullname="UnityEngine.Experimental.Networking.UnityWebRequest" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.UploadHandlerRaw" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.UploadHandler" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.DownloadHandler" preserve="all" />
    <type fullname="UnityEngine.Experimental.Networking.DownloadHandlerBuffer" preserve="all" />
</assembly>
<assembly fullname="mscorlib">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
</assembly>
<assembly fullname="System">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
</assembly>
<assembly fullname="AWSSDK.Core" preserve="all"/>
<assembly fullname="AWSSDK.CognitoIdentity" preserve="all"/>
<assembly fullname="AWSSDK.SecurityToken" preserve="all"/>
<assembly fullname="AWSSDK.SimpleDB" preserve="all"/>
  <assembly fullname="AWSSDK.DynamoDBv2" preserve="all"/>
</linker>`

**Comment by Serinoxxx** [comment]
For some reason it's not displaying my link.xml so I've attached it

[link.txt](https://github.com/aws/aws-sdk-ios/files/759946/link.txt)

**Comment by mlshon** [comment]
Can you try to follow the README to make sure you have link.xml in your assembly root with the entries in the example as is with your additional services?

**Comment by karthiksaligrama** [comment]
since this is related to AWS SDK for Unity, i suggest you open a issue in our https://github.com/aws/aws-sdk-net page.

**Comment by EunjeYu** [comment]
Hello, I have same problem.. I want to access to my S3 bucket, but i can't..
How can i handle this problem..?

**Comment by minbi** [comment]
Please open an issue with more details here https://github.com/aws/aws-sdk-net
Closed issues are not actively monitored.
