### ISSUE TITLE
Termination App in XCode 8.2 Swift 3.0 

### ISSUE THREAD

**Issue by SuhasDPatil** [aws/aws-sdk-ios#584]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'AWSCore and AWSS3 versions need to match. Check your SDK installation. AWSCore: 2.4.9 AWSS3: 2.4.10'

**Comment by minbi** [comment]
You have mismatch SDKs. Are you using the frameworks directly? If you are using Cocoapods change the versions in `Podfile` to match

**Comment by SuhasDPatil** [comment]
@minbi  Thank you for reply :)
Actually I have tried with both ways (I mean added frameworks directly and also used the Cocoapods) and also tried with same version but still occurs this issue.

**Comment by minbi** [comment]
Podfile
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'YourProjectTarget' do
    pod 'AWSS3'
end
```

cmd: pod update
