### ISSUE TITLE
Crash on -[AWSS3ChunkedEncodingInputStream nextChunk]

### ISSUE THREAD

**Issue by genadyo** [aws/aws-sdk-ios#586]
Hey,

Any idea what is going here?

http://crashes.to/s/f8644122968

**Comment by minbi** [comment]
Related to https://github.com/aws/aws-sdk-ios/pull/582

**Comment by freak4pc** [comment]
Fixed in 2.5.1 @genadyo

**Comment by genadyo** [comment]
https://github.com/aws/aws-sdk-ios/issues/592

**Comment by freak4pc** [comment]
Oh that's a bummer
