### ISSUE TITLE
Is AWSS3UploadPartRequest.body really anything?

### ISSUE THREAD

**Issue by ppamorim** [aws/aws-sdk-ios#587]
I was trying to send some bytes using the low level API, using this component to build the `AWSS3UploadPart`. By some reason this parameter `@property (nonatomic, strong) id _Nullable body;` inside the file [Here](https://github.com/aws/aws-sdk-ios/blob/b79dbbc9b1547684092028792c0a17448265705a/AWSS3/AWSS3Model.h),  means any type, but it only works with `NSData`. I tried to send bytes and it doesn't work.
This is something that would be advised on the documentation or inside this file. I am missing the low level API documentation (Java one has it) for iOS too.

- AWS: 2.4.9
- Swift: 3.0.1

Thank you!

**Comment by mlshon** [comment]
How are you using this or sending the bytes? Could you provide some code for us to look at?

**Comment by kvasukib** [comment]
Thank you, Pedro, for reporting to us. We are looking into it.
