### ISSUE TITLE
Discouraging SignUp flow

### ISSUE THREAD

**Issue by v-silin** [aws/aws-sdk-ios#591]
Hi.

Scenario is following:
1) Sign Up with “email1”
2) Confirm Sign Up
3) See success (important)
4) Sign Out
5) Sign Up with “email1” (same email, but sign up success)
6) Try confirm account
7) Account with such email already exist

By my mind, it's a little bit strange, that user can sign up with same email twice.

I see next expected behavior:
1) Sign Up with “email1”
2) Confirm Sign Up
3) See success (important)
4) Sign Out
5) Sign Up with “email1” (same email)
6) Sign Up failed: user with such email already exist.

Could you help me with this issue?

Also, I had a questions about user confirmation state:
Is it possible to get user confirmation state without signing in?
Plain getUser method doesn't work for me.

Can I use email instead of username as a primary alias for sign up?

Can I use email and username aliases together, and username is equal to email (username == email == some.email@emailhost.com) ?

**Comment by jukka-palomaki** [comment]
Are you using email as username or separate email field? Email field is not unique but username is.

**Comment by jukka-palomaki** [comment]
username can be equal to email

**Comment by v-silin** [comment]
@jukka-palomaki 

Hi, Jukka.

I am trying to use email as a primary alias, instead of username.

Scenario is following:
1) Sign up user with data:
email : some@email.com (user attribute. email is alias)
username : some@email.com
preferred username: MyUsername (user attribute . preferred username is alias)
password: anyPassword823
2) See error:
Username can not be email, if email alias enabled. (I don't remember exactly error description, but it's similar to this)

Issue is that I can't use email address as username, if email alias enabled.

**Comment by itrestian** [comment]
Please see issue below for an explanation of current alias functioning.

https://github.com/aws/amazon-cognito-identity-js/issues/148
