### ISSUE TITLE
AWSS3TransferUtility randomly not invoking progress and handler blocks for its AWSS3TransferUtilityDownloadTask when minimising and switching between the apps

### ISSUE THREAD

**Issue by SanCHEESE** [aws/aws-sdk-ios#595]
When `UIApplicationDidBecomeActiveNotification` recieved, I call `AWSS3TransferUtility`'s `enumerateToAssignBlocksForUploadTask:downloadTask:`, blocks are constructed using provided `downloadTask.taskIdentifier`. While switching between apps or minimising, locking, then maximising the app (approx 3 times) progress block stopped calling and sometimes handler block is not called too

**Comment by minbi** [comment]
Hi @SanCHEESE ,

Does this occur only when you perform these high volume switches?
Can you provide the SDK version you are using for reference?

**Comment by SanCHEESE** [comment]
Hi @minbi
Yes. I use latest 2.5.1 SDK on ios 10.2.
 I've found a workaround, just suspend and resume all download task after calling `numerateToAssignBlocksForUploadTask:downloadTask:`

**Comment by rohandubal** [comment]
Hello @SanCHEESE 

That is the expected behavior and usage. Your solution is correct.

Thanks,
Rohan

**Comment by SanCHEESE** [comment]
@rohandubal so please, mention this in documentation

**Comment by jeffjvick** [comment]
@rohandubal, wait, what?  I don't see anything about suspending / resuming the tasks in the enumerateToAssignBlocks example at https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html 

Can you please elaborate on what we are supposed to do regarding suspending and resuming tasks after calling enumerateToAssignBlocks?  I'm currently having troubling getting this to work with multipart uploads and I'm not sure if @SanCHEESE issue is part of my problem.

**Comment by cbommas** [comment]
closing this thread as we are tracking this in #769
