### ISSUE TITLE
AWSS3TransferUtility.uploadData() hangs

### ISSUE THREAD

**Issue by emojiface-ops** [aws/aws-sdk-ios#598]
I just updated to version 2.5.0 and upload() now hangs. It never reaches the continueWith() block.

Code:

        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1,
                                                                identityPoolId:"us-east-[REDACTED]")
        
        let configuration = AWSServiceConfiguration(region:.USEast1, credentialsProvider:credentialsProvider)
        
        AWSServiceManager.default().defaultServiceConfiguration = configuration

        let transferUtility = AWSS3TransferUtility.default()
        let uploadExpression = AWSS3TransferUtilityUploadExpression()

        let uploadCompletionHandler = { (task: AWSS3TransferUtilityUploadTask, error: Error?) -> Void in
            // Never reaches here
            if let HTTPResponse = task.response {
              ...              
            }
        }

            transferUtility.uploadData(
                data,
                bucket: "mybucketname",
                key: key,
                contentType: "image/png",
                expression: uploadExpression,
                completionHandler: uploadCompletionHandler
                ).continueWith (block: { (task) -> AnyObject? in
                    // Never reaches here
                    if let error = task.error {                        
                        print(error)
                    }
                    return nil
                })

I suspect an authentication issue. I've confirmed my cognito identity pool ID is correct, I've added an Inline S3 policy to my Cognito Unauth Role:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "StmtXXX",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mybucketname/*"
            ]
        }
    ]
}
```

And on to my S3 bucket:
```
{
	"Version": "2012-10-17",
	"Id": "PolicyXXX",
	"Statement": [
		{
			"Sid": "StmtXXX",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::[REDACTED]:role/Cognito_XXXUnauth_Role"
			},
			"Action": "s3:*",
			"Resource": "arn:aws:s3:::mybucketname/*"
		}
	]
}
```

Any idea what the problem might be?

**Comment by rohandubal** [comment]
Hi,

Did the code work for SDK versions 2.4.x? Even if there is an authentication issue, the code should reach this part:
```
               // Never reaches here
                if let error = task.error {                        
                    print(error)
                }
```

Control reaches this part as soon as the upload task is created. Does this specifically happen on a device / simulator?

Thanks,
Rohan

**Comment by emojiface-ops** [comment]
Hi Rohan, the code works correctly on version 2.4.16, iPhone device. I breakpointed "if let error..." and it never reaches there, just completely hangs. I *think* after 30 seconds or a minute it times out and hits that line, but I'm not 100% on that.

**Comment by rohandubal** [comment]
Hi, I am unable to reproduce this on my side. Could you try resetting the contents of simulator and retry again? Also we updated the SDKs to version 2.5.2, can you update the SDK to the latest version as well?

Thanks,
Rohan

**Comment by emojiface-ops** [comment]
I will retry with the new SDK

**Comment by minbi** [comment]
Please re-open this issue if the new SDK did not solve the problem.

**Comment by muellerfr** [comment]
Hi @commando24,

Please open a new issue if you are still experiencing problems. This particular issue was closed a long time ago. Be sure to state which version of the SDK are you on.

**Comment by tamoyal** [comment]
I'm having this exact issue. Might be something auth related but no error reported -`AWSCore (2.12.3)`

**Comment by tamoyal** [comment]
In my case the issue was that I used the version of the `uploadData` function that did not have a bucket parameter and I thought I specified that correctly by setting the bucket name as part of the key ...like this `"\(bucket_name)/rest/of/key"` however that did not work and I had to use the version of the method that has the bucket param. Anyway the real issue here is no error is reported which = bang head on wall for a bit
