### ISSUE TITLE
AWSEC2Image platform incorrectly returns AWSEC2PlatformValuesUnknown

### ISSUE THREAD

**Issue by vpatt** [aws/aws-sdk-ios#60]
I have several Windows images in my account, but the response object always has 0 as the return value.  Also, shouldn't there also be an enumeration for LINUX?

	typedef NS_ENUM(NSInteger, AWSEC2PlatformValues) {
		AWSEC2PlatformValuesUnknown,
		AWSEC2PlatformValuesWindows,
	};

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.0.14. It should address the issue you encountered.

Thanks,

**Comment by vpatt** [comment]
Thanks for your help.
--Vic
Vic Patterson
vic@tibco.com
