### ISSUE TITLE
Docs - When using Cognito and running unit tests on the iOS Simulator Security error abound.

### ISSUE THREAD

**Issue by aventurella** [aws/aws-sdk-ios#600]
This is a known issue with KeyChain access: 

https://forums.developer.apple.com/message/179846#179846

It would be nice if the docs called this out for the case where the Cognito related frameworks are included in another Framework. 

In order to unit test that code,  you must mount the tests in an App Host.  Which just means adding a new Single View App Target into the Framework Project Targets and choosing the `App Host` for the unit test target to be that new app.

I actually missed the security warnings in the console because as I was calling `getSession(username:password:validationData:)` and the logs were moving it out the immediate view.

Then I spent hours scratching my head why when I would `getDetails` etc it would try to authenticate me again and fail with a `missing delegate` error.

It all came down to that KeyChain access known issue with xctest + entitlements. So while it's not an issue with the libs herein, I think it should just be called out until Apple fixes it.

**Comment by karthiksaligrama** [comment]
Thanks we will add the docs,

Alternatively you can send us a PR for the places you are referring to
