### ISSUE TITLE
Using AWS IOT datamanager with register with key mechaism

### ISSUE THREAD

**Issue by ramki982** [aws/aws-sdk-ios#603]
Typically in AWS SDK, whenever we have different service configuration, we use the 

```
let configuration1 = AWSServiceConfiguration(region: .USWest2, credentialsProvider: credentialProvider1)
AWSIoTDataManager.registerIoTDataManagerWithConfiguration(configuration1, forKey: "USWest2IoTDataManager")
```

subsequently - we can retrieve the manager using 
`let IoTDataManager = AWSIoTDataManager(forKey: "USWest2IoTDataManager")`

If the user switches to a different region, we typically switch the configuration and hence the older datamanager is removed using the key and a new one is registered.
```
let configuration2 = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider2)
AWSIoTDataManager.registerIoTDataManagerWithConfiguration(configuration2, forKey: "USEast1IoTDataManager")
```

But this is NOT working in case of AWS IOT Datamanager due to the underlying MQTT client. The MQTTClient is somehow getting stuck with the older IOT data manager (probably due to the dispatch once).
```
- (AWSIoTMQTTClient *)mqttClient {
    static AWSIoTMQTTClient *_mqttClient = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _mqttClient = [AWSIoTMQTTClient sharedInstance];
        _mqttClient.associatedObject = self;
    });
    return _mqttClient;
}
```

As a result - shadow callbacks are failing with error unknown shadow as registration is done on new IOT datamanager and callback is done on old manager.

Could you help fix this

thanks
Ram

**Comment by fengsongAWS** [comment]
Hi @ramki982 ,
Thanks again for your interest in AWS IoT IOS SDK. You are right, this is a bug in SDK and I will include this in our roadmap and fix it in the future. At the same time, please feel free to let us know if you have any thoughts on this and we will definitely include it in our testing pipelines and give credit to your efforts if it released.
Thanks

**Comment by ramki982** [comment]
thanks @fengsongAWS for confirming. Outside the dispatch_once, I added the following locally to temporarily fix it. 

if (_mqttClient.associatedObject != self) _mqttClient.associatedObject = self;

thanks
Ram

**Comment by amiralidolat** [comment]
Has Anyone been able to address this? I've tried the AWSIoTDataManager.Default() which never worked, now I want to use thethe register method, it doesn't recognize, Here' how I have it in Swift:

iotDataManager = AWSIoTDataManager.register(with: configuration1!, forKey: "USEast1IoTDataManager")

**Comment by ramki982** [comment]
I have been using it all along. I had to manually patch the following function in SDK to get it working as suggested in comments above

```
- (AWSIoTMQTTClient *)mqttClient {
    static AWSIoTMQTTClient *_mqttClient = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _mqttClient = [AWSIoTMQTTClient sharedInstance];
        _mqttClient.associatedObject = self;
    });
    if (_mqttClient.associatedObject != self) _mqttClient.associatedObject = self;
    return _mqttClient;
}
```
