### ISSUE TITLE
AWSS3TransferUtilityErrorDomain error 2

### ISSUE THREAD

**Issue by damathryx** [aws/aws-sdk-ios#604]
Hi, I'm new to aws and I am using react-native and react-native-s3 package.
I am having a problem uploading only in iOS. Android is working fine.

v2.5.0

using `transferUtility.setupWithBasic(accessKey, secretKey, sessionKey)`
getting this error (only in iOS, android is working fine) on `transferUtility.subscribe(id, (err, task)`

> The operation couldn’t be completed. (com.amazonaws.AWSS3TransferUtilityErrorDomain error 2.

after it fails when upload reaches 100%. 
![screen shot 2017-02-24 at 10 40 06 pm](https://cloud.githubusercontent.com/assets/14576761/23307484/b09ffb3e-fae2-11e6-86dd-6c2c56b715be.png)

According to other issues with error like this I am missing bucket policy but why is it working in Android?

StackOverflow:
http://stackoverflow.com/questions/42456903/awss3transferutilityerrordomain-code-2-on-ios/42456952#42456952

**Comment by ramki982** [comment]
In my case also - i was misled to believing that i needed a policy. But in my case, I was trying to use a kms encryption but there was missing permission in IAM.

So I strongly suggest that you dump the task.result as a string and share the response from server. Above error code is what is given by SDK in client side

**Comment by damathryx** [comment]
@ramki982  turns out the region I am using is wrong but I am wondering why it's working in android?

**Comment by ramki982** [comment]
@damathryx thanks for the update. i'm not familiar with android sdk - so i cannot comment on that.

**Comment by kribby** [comment]
Ensure the time and date on the device is set correctly
