### ISSUE TITLE
Create AWSLexVoiceButton Programmatically

### ISSUE THREAD

**Issue by kisskumam** [aws/aws-sdk-ios#605]
Hi,
I'm currently working with AWSCognito and Lex. Just cannot find out the way that to create AWSLexVoiceButton programmatically then I can add the button as anywhere as I want.
Please give a help. 
Huge thanks!

**Comment by karthiksaligrama** [comment]
AWSLexVoiceButton is a simple UIView. You would make an object and add it programmatically similar to how you would interact with any other UIView
