### ISSUE TITLE
Cannot upload to S3 (Swift 3 & Cocoapods) “The request body terminated unexpectedly”

### ISSUE THREAD

**Issue by sebamisc** [aws/aws-sdk-ios#607]
When trying to upload to S3 (jpg) i get the following error:

    Error uploading: Optional("user-data/eu-west-1:xxxx-xxxx-xxxx-xxxx xxxxxxxxxx_primary_profile_picture.jpg") 
    Error: Error Domain=com.amazonaws.AWSS3ErrorDomain Code=0 "(null)" 
    UserInfo={HostId=XXX, 
    Message=The request body terminated unexpectedly, 
    Code=IncompleteBody, 
    RequestId=1485A0FFBD7819D7}`

Reported on stackoverflow here: http://stackoverflow.com/questions/42366893/upload-jpg-to-s3-the-request-body-terminated-unexpectedly (with code), seems to be an 2.5.1 issue.

**Comment by minbi** [comment]
This has been fixed in the released v2.5.2
