### ISSUE TITLE
UserPool how to getDetails after an explicit signIn (Objective-C)

### ISSUE THREAD

**Issue by moreaup** [aws/aws-sdk-ios#609]
Hi,

I'm trying to make a Cordova plugin for this sdk du to the performance issues known on the awk-sdk-js with ios.

So basically I don't have access to the UI or to the app delegate. I managed to make everything work with the plugin except one thing the getDetails which allow you to get user attributes.

Every time I call it, it says : "Authentication delegate not set" but in the documentation it says we need to link the pool delegate to the app delegate so I don't know what to do.
I need to find a way to get user details without this delegate set.

here is my code : https://github.com/moreaup/cordova-plugin-aws-user-pool, you need to go to src/AwsUserPoolPlugin.m.

Thank you for your time.

**Comment by moreaup** [comment]
So basically for those who have the same problem, I did it on my github repository if someone is interested. I'm gonna copy past a mail from aws : 

The reason you are seeing this error is due to the implementation of the CognitoUser getDetails method. This method will make a call to the non-explicit CognitoUser getSession method to ensure that a valid access token is used. This getSession method expects an authentication delegate. You can see this implementation, here:

    https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L127

Internally, the CognitoUser getDetails method is calling the AWSCognitoIdentityProvider getUser method with the access token returned by the call to CognitoUser getSession. Unfortunately the current implementation of the higher-level CognitoUser object may not adhere to your use case. You should be able to get the same results by using the AWSCognitoIdentityProvider object to make API calls directly to the User Pools API to get user details. Documentation provided below:

    [getUser:completionHandler:]
    http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityProvider.html#//api/name/getUser:completionHandler:
    [User Pools API Reference: GetUser]
    http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html

**Comment by F1LT3R** [comment]
@moreaup I am interested to see how you got Cordova communicating with native to do Cognito.  I see you have two aws repos (cordova-plugin-aws-user-pool & aws-sdk-ios), which one should I be looking at?

Also... do you happen to know for if it is still working?

**Comment by moreaup** [comment]
@F1LT3R, you can check on cordova-plugin-aws-user-pool
