### ISSUE TITLE
Can't initialize [AWSS3 defaultS3]

### ISSUE THREAD

**Issue by xikimay** [aws/aws-sdk-ios#612]
Hi everybody,

I'm trying to use the AWSS3 object in order to put an object to aws.
The problem i'm facing is that i can't initialize the AWSS3 object correctly.

The AWSS3 SDK version is 2.4.16

Here what's i'm doing : 
`- (id) init:(NSDictionary *)params {
    AWSCredentials              *credentials;
    AWSServiceConfiguration     *conf;
    NSDate                      *expiration;
    NSDateFormatter             *dateFormat;
    
    self._bucket = params[@"Bucket"];
    dateFormat = [[NSDateFormatter alloc] init];
    [dateFormat setDateFormat:@"yyyy-MM-dd'T'HH:mm:ssZ"];
    
    expiration = [dateFormat dateFromString:[params valueForKey:@"expiration"]];
    
    credentials = [[AWSCredentials alloc]
                   initWithAccessKey:[params valueForKey:@"AccessKeyId"]
                   secretKey:[params valueForKey:@"SecretAccessKey"]
                   sessionKey:[params valueForKey:@"SessionToken"]
                   expiration:expiration];
    
    conf = [[AWSServiceConfiguration alloc]
            initWithRegion:AWSRegionEUWest1
            endpoint:[params valueForKey:@"EndpointURL"]
            credentialsProvider:credentials];
    
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = conf;
    self._s3 = [AWSS3 defaultS3];
    self._bucket = params[@"Bucket"];
    
    return (self);
}` 

It crashes when calling [AWSS3 defaultS3] 

> 2017-03-09 11:49:36.465 xctest[95125:27780209] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setRegion:service:]: unrecognized selector sent to instance 0x7fa46253e0d0'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x0000000103c1ed4b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x000000010368021e objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000103c8ef04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x0000000103ba4005 ___forwarding___ + 1013
> 	4   CoreFoundation                      0x0000000103ba3b88 _CF_forwarding_prep_0 + 120
> 	5   Tests                               0x000000010fa78a42 -[AWSS3 initWithConfiguration:] + 498
> 	6   Tests                               0x000000010fa782cc __18+[AWSS3 defaultS3]_block_invoke + 508
> 	7   libdispatch.dylib                   0x000000010694812e _dispatch_client_callout + 8
> 	8   libdispatch.dylib                   0x0000000106932e0e dispatch_once_f + 68
> 	9   Tests                               0x000000010fa780a4 +[AWSS3 defaultS3] + 84

Does anyone know how to solve this ?

**Comment by rohandubal** [comment]
Hi, to help you better, could you answer a few more questions?
-I see that static credentials are being used here, what is the use case for it? We recommend using Cognito as its free and designed for Mobile use cases. Static credentials may cause the app to be rejected
-Do you have a custom endpoint you are trying to connect to?

Thanks,
Rohan

**Comment by xikimay** [comment]
Hi, thanks for answering
On Server-side, STS is implemented and it's the main reason why Cognito is not.
The static credentials are implemented in an SDK for iOS devices.
We use the Amazon server to store object and get them.
We are not using a custom endpoint

**Comment by rohandubal** [comment]
Hi,

Could you use the following constructor for setting the AWSServiceConfiguration?

```
- (instancetype)initWithRegion:(AWSRegionType)regionType
           credentialsProvider:(id<AWSCredentialsProvider>)credentialsProvider;

```

Thanks,
Rohan

**Comment by xikimay** [comment]
Hi,

The problem is resolved, I think I have passed a bad string to the endpoint argument.

Thanks for your help
