### ISSUE TITLE
Expected member name or ';' after declaration specifiers into AWSS3Model.h

### ISSUE THREAD

**Issue by jviebach** [aws/aws-sdk-ios#613]
I'm receiving several parse issues for syntax on AWSS3Model.h when building an objective-C iOS workspace that also contains C++ files (.mm extensions in XCode).  

This seems similar to #597 as the errors appear due to using reserved C++ keywords as names:
* AWSS3Model.h: Line 620: @property (nonatomic, strong) AWSS3AnalyticsAndOperator * _Nullable and;
* AWSS3Model.h: Line 3311: @property (nonatomic, strong) AWSS3LifecycleRuleAndOperator * _Nullable and;
* AWSS3Model.h: Line 4114: @property (nonatomic, strong) AWSS3MetricsAndOperator * _Nullable and;

Any workaround or fix?

**Comment by rohandubal** [comment]
This might be due to `and` being a reserved c++ keyword. We will look into this.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
resolved with 2.5.3
