### ISSUE TITLE
AWSIoT shadowDevice documents

### ISSUE THREAD

**Issue by SanjoDeundiak** [aws/aws-sdk-ios#616]
AWSIoT SDK doesn't subscribe to update/delta topic for shadow device, so messages that Shadow Service publishes there are not available using SDK.
Doc reference:
http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html#update-delta-pub-sub-topic

**Comment by fengsongAWS** [comment]
Hi @SanjoDeundiak ,
Thanks for your interest in AWS IoT SDK.
Is there any problems that you are not able to receive shadow messages from service? 
From here https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/AWSIoTDataManager.m#L807,
the data manager will subscribe 7 shadow topics and wait for messages from server. 
Also, we have samples that demonstrate shadow operation as well.  https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoTTemperatureControl-Sample/Swift

Please let us know if you have more questions. 
Thanks

**Comment by SanjoDeundiak** [comment]
@fengsongAWS Sorry, I've made a mistake. SDK doesn't subscribe to update/documents topic [http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html#update-documents-pub-sub-topic](url)
Other topics are totally OK.

**Comment by fengsongAWS** [comment]
Hi @SanjoDeundiak ,

Yes, you are right. This is a new API from shadow service that current SDK does not support. We will have this covered in the future release. 

Thanks

**Comment by SanjoDeundiak** [comment]
@fengsongAWS got it.
That would be great cause we've faced problems implementing behavior we need without subscribing to update/documents topic:
1. Thing1 updates desired value, so it doesn't match with reported: everyone gets update/delta notification
2. Thing2 applies this update and updates reported value, so it now matches with desired value: **noone gets notification about this??**
Would be happy to know when you're planning to update SDK with this functionality, if possible.
Please, close this issue/move to feature request or whatever you usually do with such issues.

**Comment by fengsongAWS** [comment]
Thanks for letting us know your use case.

In your case, you can use plain MQTT subscription on update/document topic to be notified as a work around. Or you could register callback on update/accepted whenever the changes got accepted. 

Definitely, it would be much better to have API to handle update/document and we will be working on this soon. 

Thanks
