### ISSUE TITLE
AWSSNS (Unauthenticated access is not supported for this identity pool.) 2.5.2

### ISSUE THREAD

**Issue by mdotadil** [aws/aws-sdk-ios#617]
### To help us solve your problem better, please answer the following list of questions.
Unauthenticated access is not supported for this identity pool.

* What service are you using?
AWSSNS

* In what version of SDK are you facing the problem?
2.5.2

* Is the issue limited to Simulators / Actual Devices?
Simulator and devices.

* Can your problem be resolved if you bump to a higher version of SDK?
It is working fine on 2.4.1

* Is this problem related to specific iOS version?
Nope.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

		AWSSNS *sns = [AWSSNS defaultSNS];
		AWSSNSPublishInput *smsInput = [AWSSNSPublishInput new];
		smsInput.message = message
		smsInput.phoneNumber = phoneNumber
		[sns publish:smsInput completionHandler:^(AWSSNSPublishResponse * _Nullable response, NSError * _Nullable error) {
			if (response) {
				NSLog(@"Response: %@", response);
			}
			else {
				NSLog(@"Error: %@", error);
			}
		}];

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by karthiksaligrama** [comment]
@mdotadil this means that you have not setup unauthenticated access on you cognito identity pool. 

If you do not want unauthenticated acccess to your identity pool then you should pass a credential provider that can federate using the identity provider that you have setup on amazon cognito identity.

**Comment by mdotadil** [comment]
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:CognitoRegionType
																			 credentialsProvider:[AmazonClientManager sharedInstance].credentialsProvider];
		
		AWSSNS *sns = [AWSSNS SNSForKey:@"USEast1SNS"];
		[AWSSNS registerSNSWithConfiguration:configuration forKey:@"USEast1SNS"];
		AWSSNSPublishInput *smsInput = [AWSSNSPublishInput new];
		smsInput.message = @"Test Message";
		smsInput.phoneNumber = self.contactNoTextField.text;
		[sns publish:smsInput completionHandler:^(AWSSNSPublishResponse * _Nullable response, NSError * _Nullable error) {
			if (response) {
				NSLog(@"Response: %@", response);
			}
			else {
				NSLog(@"Error: %@", error);
			}
		}];
