### ISSUE TITLE
Crash when uploading file that does not exists through AWSTransferUtility with AWSS3TransferUtilityUploadTask

### ISSUE THREAD

**Issue by nick3389** [aws/aws-sdk-ios#618]
To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSS3
* In what version of SDK are you facing the problem?
2.5.2
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
no
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Try to upload a file that does not exists (I did it with a fake path) through AWSS3TransferUtility func:
```
- (AWSTask<AWSS3TransferUtilityUploadTask *> *)uploadFile:(NSURL *)fileURL
                                                   bucket:(NSString *)bucket
                                                      key:(NSString *)key
                                              contentType:(NSString *)contentType
                                               expression:(AWSS3TransferUtilityUploadExpression *)expression
                                        completionHandler:(AWSS3TransferUtilityUploadCompletionHandlerBlock)completionHandler
```

Probably, you will see a crash. I inserted a try-catch block for:
`NSURLSessionUploadTask *uploadTask = [weakSelf.session uploadTaskWithRequest:request
                                                                                fromFile:fileURL];
            [uploadTask resume];`

and made it return: [AWSTask taskWithError:fileError] and it worked ok.

**Comment by minbi** [comment]
Thank you for reporting this issue. We will have a fix for this with the next release.

**Comment by nick3389** [comment]
Great! Thanx.

**Comment by karthiksaligrama** [comment]
resolved with 2.5.3

**Comment by wowrahul** [comment]
The fix misses an edge case where the File path has directory names that have spaces. Since the URL is encoded the NSFileManager returns NO when trying to locate the file using the encoded URL. You should ideally be using the path property of the URL rather than the absolute string.

**Comment by nick3389** [comment]
Same for me. I commented the new code because it always returned a AWSTask with error. However, my file names do not have a space between them. They are UUIDs in form of xxxxx-xxxxxx-xxxxx-xxxxx
