### ISSUE TITLE
[AWSCognitoIdentityUserPool strippedPoolId] keeps crashing after sign in

### ISSUE THREAD

**Issue by jaskooo** [aws/aws-sdk-ios#619]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?

1.  AWSCognitoIdentityProvider (2.5.2):
2.  AWSCore (= 2.5.2)
3.  AWSCore (2.5.2)

iOS 10.2

* Is the issue limited to Simulators / Actual Devices?
no

* Can your problem be resolved if you bump to a higher version of SDK?
i don't know

* Is this problem related to specific iOS version?
i don't knnow

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
When I am signing in using username and password after successful process app just keep crashing on `[AWSCognitoIdentityUserPool strippedPoolId]` method and console says: `fatal error: subscript: subrange start precedes String start`

**Comment by jaskooo** [comment]
My mistake sorry

**Comment by AndreasDpp** [comment]
What did you do to fix it?..

I have the same problem now

**Comment by cmd-johnson** [comment]
For future reference: I just had the same problem. Turns out I used the identity pool id instead of the user pool id. After fixing this, everything worked just fine.

**Comment by annamalairaj** [comment]
@jaskooo how did you fix this issue?
