### ISSUE TITLE
Is there a CloudWatch Logs library for iOS?

### ISSUE THREAD

**Issue by emresebat** [aws/aws-sdk-ios#623]
Hi

Is there any plans for a aws-logging-ios project which can work with CloudWatch Logs? [dotnet](https://github.com/aws/aws-logging-dotnet) version works great and I think we need an iOS project which has PutLogEvents integrated. 

There is a good [documentation](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.htm) but a logging library needs threading, error handling etc. 

I couldn't find any libraries which support this out of the box like LogKit or other.

**Comment by lehno** [comment]
You can use API-Gateway to invoke a lambda function. Lambda can create the LogGroup, LogStream and put logs for you there. In that way you can log anything using Cloudwatch using any device that can post data.

**Comment by karthiksaligrama** [comment]
added in 2.5.3

**Comment by emresebat** [comment]
Hi @karthiksaligrama 
I've checked the change logs and some functionality is added but I don't see any examples which can create a log event. 
We use Cloudwatch Logs for all our log needs from .NET C# (NLog + NLog Cloudwatch LogsTarget), and nodejs (winston + Cloudwatch Logs target). iOS is missing the core function to create log events.
Do you plan to support some iOS logging libraries like willow or cocoalumberjack so they can use AWS Cloudwatch Logs as a target?

**Comment by freynolds** [comment]
Hey guys, I'm also intrested on what @emresebat is asking. I would love to see my logs in cloudwatch directly from the app.

**Comment by ppamorim** [comment]
Any idea when this feature will be added?

**Comment by kvasukib** [comment]
@ppamorim @freynolds Have you checked out AWSLogs (https://github.com/aws/aws-sdk-ios/tree/master/AWSLogs)?
