### ISSUE TITLE
APIGateway generating SDK with "#import GHttps://apigateway.amazonaws....h" for model references

### ISSUE THREAD

**Issue by mhaverland** [aws/aws-sdk-ios#624]
Yesterday APIGateway's generated SDK started failing for me, and had been working well for the past few weeks.

aws-sdk-ios 2.5.2 (Podfile details below)

Summary:
One model definition references another, e.g. model ImageArray includes:
    "$ref" : "https://apigateway.amazonaws.com/restapis/........../models/Image"
per https://forums.aws.amazon.com/thread.jspa?messageID=697388 , not finding “$ref”: “#/definitions/Image” or other variations to work.

Generated sdk in GImageArray.h prior to yesterday was GImageArray.h:
    #import "GImage.h" // "G" is prefix specified during SDK generation
and  GImageArray.m:
    + (NSValueTransformer *)itemsJSONTransformer {
        return [NSValueTransformer awsmtl_JSONArrayTransformerWithModelClass:[GImage class]];

but is now:
    #import "GHttps://apigateway.amazonaws.com/restapis/........../models/Image.h"
and
    + (NSValueTransformer *)itemsJSONTransformer {
        return [NSValueTransformer awsmtl_JSONArrayTransformerWithModelClass [GHttps://apigateway.amazonaws.com/restapis/........../models/Image class]];

What is the proper way to reference other models in a Model definition, and generate proper SDK?

Thanks for any help!

Details:

Generating an objective-c SDK for use in a swift 3 project via bridging header.

Podfile.lock:
PODS:
   AWSAPIGateway (2.5.2):
    - AWSCore (= 2.5.2)
  - AWSCognito (2.5.2):
    - AWSCore (= 2.5.2)
  - AWSCore (2.5.2)
  - AWSDynamoDB (2.5.2):
    - AWSCore (= 2.5.2)
  - AWSS3 (2.5.2):
    - AWSCore (= 2.5.2)

e.g. model ImageArray shown here references model Image:
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "ImageArray",
    "description": "array of Images",
    "properties": {
        "Items": {
            "description": "array of Images",
            "type": "array",
            "items": {
                "$ref": "https://apigateway.amazonaws.com/restapis/........../models/Image"
            }
        }
    }
}

**Comment by rohandubal** [comment]
Hi,

Could you please mention what changes you made before the SDK generation started failing? Did the SDK generation work correctly prior to change? or did the SDK generation started failing without any change?

Thanks,
Rohan

**Comment by mhaverland** [comment]
Thanks for the followup @rohandubal.  Looking back through commits, notes, etc. I find only one possibly relevant change around this break: I had added a model, and an array model that $ref's it, but that's it.  I had been iteratively altering my API, updating models, and generating the sdk for several weeks prior, without issue. I had had models with $ref used like this for most of those preceding weeks (all through the web console, SDK Generation tab on the stage editor, etc.)

I've tried deleting those recent models and redeploy/regenerate, same issue.  Very strange.

**Comment by rohandubal** [comment]
Thanks for getting back @mhaverland , I will investigate into this and get back to you.

**Comment by ramki982** [comment]
This issue is occurring with Objective C, Swift and Android auto generated code

**Comment by rohandubal** [comment]
This issue is caused due to missing "type" attribute for the concerned model. The API definition model needs to have the type attribute for SDK generation to succeed.

Thanks,
Rohan
