### ISSUE TITLE
Sign in AWSTaskCompletionSource is nill 

### ISSUE THREAD

**Issue by ijknm** [aws/aws-sdk-ios#625]
New to AWS framework but it work like anything I am not faced any issue until today from last 1 week 
-Sign up Works fine get OTP (phone number verification)
-Confirm Sign Up Works Fine (Successfully confirm)
-Sign in getting an issue.
bellow code:

```
-(IBAction)didTapOnSignInButton:(id)sender{  self.passwordAuthenticationCompletion.result = [[AWSCognitoIdentityPasswordAuthenticationDetails alloc] initWithUsername:_usernameText password:self.ibPassword.text];
NSLog(@"%@",self.passwordAuthenticationCompletion);
}
-(id<AWSCognitoIdentityPasswordAuthentication>) startPasswordAuthentication {
    return self;
}
-(void) getPasswordAuthenticationDetails: (AWSCognitoIdentityPasswordAuthenticationInput *) authenticationInput  passwordAuthenticationCompletionSource: (AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> *) passwordAuthenticationCompletionSource {
    self.passwordAuthenticationCompletion = passwordAuthenticationCompletionSource;
    dispatch_async(dispatch_get_main_queue(), ^{
        if(!self.usernameText)
            self.usernameText = authenticationInput.lastKnownUsername;
    });   
}
-(void) didCompletePasswordAuthenticationStepWithError:(NSError*) error {
    dispatch_async(dispatch_get_main_queue(), ^{
        if(error){
              nslog(@"Error ");
        }else{
            self.usernameText = nil;
            [self dismissViewControllerAnimated:YES completion:nil];
        }
    });
}
```

self.passwordAuthenticationCompletion = nill 

Printing description of self->_passwordAuthenticationCompletion:
<nil>
and never called getPasswordAuthenticationDetails and didCompletePasswordAuthenticationStepWithError
what is wrong....... 

Following this document 
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample

**Comment by rohandubal** [comment]
Hello @ijknm,

Could you please open this issue under the samples repository? It would be easier to track this issue there.

Thanks,
Rohan

**Comment by ijknm** [comment]
ya..

**Comment by KosalaFMF** [comment]
where is the solution for this issue
