### ISSUE TITLE
Reassigning AWS3TransferUtility task from one instance to another

### ISSUE THREAD

**Issue by jamesbebbington** [aws/aws-sdk-ios#626]
Hi.

Our iOS app uploads large files, and so to avoid unexpected data usage charges to our users, by default we set `allowsCellularAccess = false` and ask them to upload using Wi-Fi. Some international markets however have fast, unmetered cellular services, with some users solely relying on them for their data connections. We'd therefore like to provide the option to allow uploads over the cellular network.

AIUI it's not possible to simply change the `allowsCellularAccess` value on the `AWSServiceConfiguration`  as this is fixed once initially set. I see that `AWS3TransferUtility` provides `.register(with:forkey:)` that we can use to create two different configurations, one that allows cellular and another that doesn't. However is it possible to transfer a running upload task from one configuration to another? 

AWSS3 v2.5.2, iOS, Swift 3.1, cocoapods.

Many thanks.

**Comment by rohandubal** [comment]
Hello @jamesbebbington ,

You are correct, you could use configuration to set different clients having with or without cellular use case. Also, it is not possible to change the behavior of the upload task by switching configuration.

To understand your question better, could you please tell me Why would you require to switch configuration mid-upload? Is it possible to determine the expected behavior before the start of upload and then use the appropriate client?

Thanks,
Rohan

**Comment by jamesbebbington** [comment]
Thanks for getting back to me @rohandubal, much appreciated.

> Why would you require to switch configuration mid-upload? Is it possible to determine the expected behavior before the start of upload and then use the appropriate client?

We certainly can (and would) ask the user whether they would like to allow the use of cellular data before starting their first upload, but we would also like to give the user the option to change this app-wide setting at will, via the application's Settings bundle.

We could abort and restart the user's uploads when they change this setting, but forcing users to re-upload data they've already transmitted seems a little inelegant. I was hoping that there was a way to avoid this.

Relatedly, I see that [Transfer Manager supports multipart uploads](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transfermanager.html#multipart-upload) but I don't see any mention of support in the [Transfer Utility docs](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html), which I thought might help with our particular use case. Is the plan for Transfer Utility to replace Transfer Manager in the long run? Will Transfer Utility support multipart uploads in the future?

Thanks.

**Comment by rohandubal** [comment]
Yes, you are correct. Transfer Manager does support multipart uploads and your use case would be better suited with Transfer Manager. But a downside is that Transfer Manager does not have background downloads / uploads which Transfer Utility does. We currently do not have immediate plans to add multipart uploads for Transfer Utility, but I will take it as a feature request to the team.

Thanks,
Rohan
