### ISSUE TITLE
Explicit way of setting new password for AdminCreateUser

### ISSUE THREAD

**Issue by jiaziw** [aws/aws-sdk-ios#627]
We want to use the AdminCreateUser feature in our app. Do we need to implement the AWSCognitoIdentityInteractiveAuthenticationDelegate and AWSCognitoIdentityNewPasswordRequired to set the new password for the user or is there any explicit way we can use? If not, will you provide the  explicit function in iOS sdk?
Thanks!

**Comment by vlekakis** [comment]
Currently, there is no explicit way to do this. You need to implement those delegates.
As far as I know, there is no immediate plan to implement an explicit function.
