### ISSUE TITLE
Updating to 2.5.3 breaks serviceConfiguration.endpoint again

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#628]
So after updating to 2.5.3 my projects breaks again.

I'm still getting compiler error 

Cannot assign property 'endpoint' is a get-only property.

This was previously resolved by adding a bridging header then a custom class as discussed else where. I was under the impression that 2.5.3 would be fully Swift compatible now. And even the old way of overwriting the class with a bridging header has now stopped working.

This is the lines not working

```
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: Constants.identityPoolId, identityProviderManager: IdentityProvider(provider: Constants.auth0Domain, token: token))
        let serviceConfiguration = AWSServiceConfiguration(region: .EUWest1, credentialsProvider: credentialsProvider)!
        
        serviceConfiguration.endpoint = AWSEndpoint(region: .EUWest1, service: .APIGateway, url: URL(string: Constants.host)!)
```

**Comment by helloniklas** [comment]
right, just realised there's a new intializer, so all works now.

```
        let endpoint = AWSEndpoint(region: .EUWest1, service: .APIGateway, url: URL(string: Constants.host)!)
        let serviceConfiguration = AWSServiceConfiguration(region: .EUWest1, endpoint: endpoint, credentialsProvider: credentialsProvider)!
```

**Comment by Sulemankandornawala** [comment]
I m integrating the AWS and facing up the same error 
I have tried multiple pods version for this 2.6.33 & the latest one but facing the same issue in both version any solution for this 


  self.configuration = configuration.copy() as! AWSServiceConfiguration
	    var URLString: String = "https://nw9jinchy0.execute-api.us-west-2.amazonaws.com/qal"
	    if URLString.hasSuffix("/") {
	        URLString = URLString.substring(to: URLString.index(before: URLString.endIndex))
	    }
        
//        self.configuration.endpoint = AWSEndpoint(region: configuration.regionType, service: .APIGateway, url: URL(string: URLString))
	   
        self.configuration.endpoint = AWSEndpoint(region: configuration.regionType, service: . APIGateway, url: URL(string: URLString))
