### ISSUE TITLE
Letting Carthage users pull and build only needed frameworks

### ISSUE THREAD

**Issue by SanjoDeundiak** [aws/aws-sdk-ios#629]
Currently, those, who use Carthage, are able only to pull and build all AWS SDKs. It would be better to let users pull only needed SDKs.
Unfortunately, that involves dividing source code into many repositories.

**Comment by karthiksaligrama** [comment]
You are right this would involve splitting up the repo, which is not something we are looking at in the immediate future. However a compromise could be to do something discussed #459. I'm closing this issue so we can have discussion at a single place.

**Comment by ikzjfr0** [comment]
Sad to hear that since it could take a long time to download whole SDK when using carthage update. To always have a clean build is quite common for CI/CD, so this quite sucks :(
