### ISSUE TITLE
Crash: - AWSPinpointSessionClient endCurrentSessionTimeoutWithTimer EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by bruun** [aws/aws-sdk-ios#630]
* What service are you using?
Pinpoint

* In what version of SDK are you facing the problem?
2.5.2 & 2.53

* Is the issue limited to Simulators / Actual Devices?
Can't reproduce locally in the simulator or on device, but reported by Crashlytics.

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No (iOS 9 & 10)

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
[crash_aws.txt](https://github.com/aws/aws-sdk-ios/files/896419/crash_aws.txt)

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I can't reproduce the problem, but the path to the crash requires that the user first backgrounds the application. Crashlytics reports that the app is never in focus when the crash occurs.

See crash log attached.

**Comment by jberkel** [comment]
May be related to #614. What does your crash log say in the `Exception Note:` field?

**Comment by bruun** [comment]
No exception note reported for this crash, only exception type and subtype:
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000018

**Comment by marksvend** [comment]
The problem might be that the block needs to be copied before being stored in the NSTimer userInfo dictionary here:
https://github.com/aws/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointSessionClient.m#L317

After reading the documentation, it's unclear to me if ARC does a copy for you in this situation. I'd still do a copy here just to be safe.

**Comment by bruun** [comment]
From what I can see the `block` parameter is never set. This is the only path I can find leading to the block you linked to: 
https://github.com/aws/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointSessionClient.m#L122

**Comment by marksvend** [comment]
It's fine if the block is nil since it is checked for nil before anything is done with it.
https://github.com/aws/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointSessionClient.m#L316

**Comment by bruun** [comment]
Exactly, so the block not being copied can't be in issue in this case.

**Comment by rohandubal** [comment]
Fixed with 2.6.2.
