### ISSUE TITLE
AWSAPIGateway's generated Swift SDK cannot be compiled

### ISSUE THREAD

**Issue by syn-jayesh-kacha** [aws/aws-sdk-ios#633]
AWSAPIGateway's generated Swift SDK cannot be compiled, as it is not in sync with AWSAPIGateway/AWSCore. Generated Swift code cannot be compiled as it looks it is not in sync with AWSAPIGateway/AWSCore, code is having compilation issues for some methods. 
Code tries to access some method which are not exposed in AWS framework. 

Tried to link AWSAPIGateway version 2.5.3 as per mentioned Pod file. Also tried to link 2.4.7 as README document. Looks like Swift SDK calling methods which are not exposed (or changed method signature by AWSAPIGateway framework).

* What service are you using?
Using AWSAPIGateway/AWSCore modules for iOS SDK using Cocoapods Swift project

* In what version of SDK are you facing the problem?
2.4.7 /  2.5.3 

* Is the issue limited to Simulators / Actual Devices?
Simulator/Device

* Can your problem be resolved if you bump to a higher version of SDK?
Unsure, but tried with 2 versions.

* Is this problem related to specific iOS version?
Observed in iOS Swift

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Tried both Cocoapods & manually 

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Generated SDK has MyDemoClient which is subclass of AWSAPIGatewayClient, MyDemoClient.swift doesn't have "invokeHTTPRequest" method (looks method signature changed). Also problem with other properties.

**Comment by rohandubal** [comment]
Hello,

Could you please confirm if you included the Bridging Header in your Swift app and added it as specified in the instructions? 

Thanks,
Rohan

**Comment by syn-jayesh-kacha** [comment]
Below property is readonly.

self.configuration = configuration.copy() as! AWSServiceConfiguration

**Comment by rohandubal** [comment]
Can you update to the latest version of SDK and try? You should be using SDK version 2.5.3.

Thanks,
Rohan

**Comment by syn-jayesh-kacha** [comment]
It is fixed, also automatically generated readme document needs to reflect to change to point -  version-2.5.3.
