### ISSUE TITLE
AWSS3TransferUtility has problem with URLs containing spaces as of version 2.5.3

### ISSUE THREAD

**Issue by jrichau** [aws/aws-sdk-ios#634]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSS3TransferUtility

* In what version of SDK are you facing the problem?
2.5.3

* Is the issue limited to Simulators / Actual Devices?
Tested on actual device

* Can your problem be resolved if you bump to a higher version of SDK?
No, but I do have a workaround.

* Is this problem related to specific iOS version?
Tested on 10.3 - may be related to Apple's new file system changes

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Recently upgraded to swift 3 and got the latest changes for use with the APIGateway. However this broke my use of the AWSTransferUtility. After some debugging it came down to this added check in version 2.5.3

```
NSString *filePath = [fileURL absoluteString];
    // [fileURL absoluteString] prefix is "file:///", length 8
    if ([filePath length] < 8 || ! [[NSFileManager defaultManager] fileExistsAtPath:[filePath substringFromIndex:7]]) {
        return [AWSTask taskWithError:[NSError errorWithDomain:AWSS3TransferUtilityErrorDomain
                                                          code:AWSS3TransferUtilityErrorLocalFileNotFound
                                                      userInfo:nil]];
    }
```
I was using swift's recommended way of getting a temp dir like this:
`try FileManager.default.url(for: .itemReplacementDirectory, in: [.userDomainMask], appropriateFor: sourceURL, create: true)`
which produces a directory of the form <path to app container>/AppData/tmp/(A Document Being Saved By <AppName> <number>)/

WORKAROUND: For now I am using NSTemporaryDirectory() instead of the above method in order to get a path to the tmp area and I am being careful that no spaces are in my path. 

FIX: However I believe the check that got added is a bit wonky and conversion to absoluteString seems a bit odd (and in my case was problematic) and should be something more like:
`if (! [[NSFileManager defaultManager] fileExistsAtPath:[fileURL path]]) {
        return <ErrorHandling>;
    }`

Overall I believe there should be a test added to check that the transfermanager works with paths with spaces.

In AWSS3Tests, there is a test:
testGoodFilePathUpload

there should also be:
testGoodFilePathUploadWithSpaces that tries something like:
`let filePath = NSTemporaryDirectory() + "Dir with spaces/testGoodFilePathUpload.tmp"`

**Comment by wowrahul** [comment]
Agreed. I updated the code to use filePath because directory name on our side has spaces. Hoping this gets resolved in next version.

**Comment by minbi** [comment]
AWS Mobile SDK for iOS v2.5.6 has been released
