### ISSUE TITLE
AWSCore/AWSNetworking.h not found error with use_frameworks!

### ISSUE THREAD

**Issue by Alexs1987** [aws/aws-sdk-ios#635]
When importing AWSKinesis - 
`#import <AWSKinesis/AWSKinesis.h>
`

from a file in an **inner static library**, I'm getting the following error - 

`In file included from ../Pods/AWSKinesis/AWSKinesis/AWSKinesis.h:25:
In file included from ../Pods/AWSKinesis/AWSKinesis/AWSKinesisService.h:18:
../Pods/AWSKinesis/AWSKinesis/AWSKinesisModel.h:17:9: fatal error: 'AWSCore/AWSNetworking.h' file not found
#import <AWSCore/AWSNetworking.h>`

My podfile looks like that -  

```
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target :MyTarget do
    pod 'AWSCore', '2.4.5'
    pod 'AWSKinesis', '2.4.5'
end
```

I'm using cocoapods version 1.2.0

Here is an example project to see the issue https://github.com/Alexs1987/AWSTest

**Comment by mlshon** [comment]
Hi,
I tried to reproduce your issue using the Podfile you provided, but I was unable to reproduce it.
Can you tell me steps to reproduce?

What I did:
1. Created a Podfile (identical to yours)
2. `pod install`
3. imported AWSKinesis
4. wrote a line of code to actually use the import
5. build.

**Comment by Alexs1987** [comment]
Hi @mlshon 

I've created an [example project ](https://github.com/Alexs1987/AWSTest) to demonstrate the issue. It seems that it happens if I import the AWSKinesis framework in my static library.
Note that I import other pods to my static library and it works perfectly. AWSKinesis is the only pod that is causing me issues.

**Comment by mlshon** [comment]
I believe this is something to do with your Podfile..

Try something along the lines of...

```
platform :ios, '9.0'
inhibit_all_warnings!

workspace 'AWSTest.xcworkspace'

project 'AWSTest'

target :AWSTest do
    pod 'AWSCore', '2.4.5'
    pod 'AWSKinesis', '2.4.5'
end

target :MyStaticLib do
    project 'MyStaticLib/MyStaticLib'
end
```

**Comment by Alexs1987** [comment]
@mlshon Unfortunately getting the same error.

**Comment by mlshon** [comment]
Hm, I just downloaded your sample project and copied the Podfile I pasted and then ran `pod install`
The build succeeds for me.

**Comment by Alexs1987** [comment]
@mlshon - Why aren't you using use_frameworks ? I need use_frameworks! to install pods with Swift.
If you add use_frameworks! you will get the error.

**Comment by mlshon** [comment]
By using `use_frameworks!` it is indicating that the dependencies have to be used as dynamic frameworks and not static libraries. For dynamic frameworks, the loading is done at **run time**, while for static libraries its done at **compile time**. If you set the dependency for AWS SDKs as frameworks, they will be loaded only at runtime and not compile time and hence you face the issue while you use them in your static library. So in your usecase, the SDK wont be able to be used. You could use our static library SDK (2.3.6 version) and achieve this but not when you use it as frameworks. If you are writing an objective c app, you could get rid of use_frameworks! and everything would work fine.

**Comment by andresinaka** [comment]
@Alexs1987 hey did you find a way of making it work? I'm having the same problem as you!

**Comment by Alexs1987** [comment]
@andresinaka I ended up updating the Podfile like that -

`target :AWSTest do
    pod 'AWSCore', '2.4.5'
    pod 'AWSKinesis', '2.4.5'
end

target : MyStaticLib do
    project 'MyStaticLib/MyStaticLib.xcodeproj'
    pod 'AWSCore', '2.4.5'
    pod 'AWSKinesis', '2.4.5'
end`
