### ISSUE TITLE
confirm user who listed unconfirm in user pool

### ISSUE THREAD

**Issue by aniliosdev** [aws/aws-sdk-ios#641]
In my iOS app I implemented mobile No. verification. But if user enter wrong mobile number then user created in user pool but he is still unconfirm. So I'm not able to signIn (user not confirm error) and reset password. And not able to sign up with this email (get email exist error). So how to confirm this unconfirm user using mobile verification with new mobile number. I'm not able to update mobile number in userpool.

SignUp process is - > SingUp In user pool -> Confirm user with code -> SignIn

I used following pod in app

pod 'AWSCognito'
pod 'AWSCognitoIdentityProvider'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSLambda'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSNS'

Thanks

**Comment by chetanme** [comment]
In situations like this where a user has locked himself out by entering an incorrect value for phone number or email, only admin actions can correct it for them.

A developer with correct admin privileges has following options:
- Call AdminConfirmSignUp API to confirm the user. The user will be able to login after this and can update the phone number to correct value. He can also request verification after this and verify the new phone number.
-  Call AdminUpdateUserAttributes API and update the phone number to the correct value. The user can request to resend the confirmation code and then confirm the account.
