### ISSUE TITLE
AWS IOT MQTTDecoder crash

### ISSUE THREAD

**Issue by ramki982** [aws/aws-sdk-ios#642]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IOT

* In what version of SDK are you facing the problem?
2.5.3

* Is the issue limited to Simulators / Actual Devices?
both

* Can your problem be resolved if you bump to a higher version of SDK?
this is latest

* Is this problem related to specific iOS version?
no

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Attached the capture of the xcode when it crashed. MQTTDecoder trying to assign NULL to databuffer and seems to crash
<img width="1182" alt="screen shot 2017-04-19 at 9 20 27 am" src="https://cloud.githubusercontent.com/assets/353611/25191688/09908ff2-254e-11e7-9378-6e18e7ebfa16.png">

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by ramki982** [comment]
This is still occurring in the latest version of SDK

Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x3737623331633238
Crashed Thread:  0

Thread 0 Crashed:
0   libobjc.A.dylib                      0x000000018f35d7ec objc_object::release() + 0
1   AWSIoT                               0x0000000100965a04 -[MQTTDecoder stream:handleEvent:] (MQTTDecoder.m:138)
2   CoreFoundation                       0x000000019082a01c _signalEventSync + 208
3   CoreFoundation                       0x0000000190834d84 _cfstream_solo_signalEventSync + 252
4   CoreFoundation                       0x000000019088d42c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 20
5   CoreFoundation                       0x000000019088cd04 __CFRunLoopDoSources0 + 384
6   CoreFoundation                       0x000000019088a9a8 __CFRunLoopRun + 740
7   CoreFoundation                       0x00000001907bada4 CFRunLoopRunSpecific + 420
8   GraphicsServices                     0x0000000192224074 GSEventRunModal + 96
9   UIKit                                0x0000000196a75058 UIApplicationMain + 204
10  Norton Core                          0x000000010014574c main (NHAppDelegate.swift:20)
11  libdyld.dylib                        0x000000018f7c959c start + 0

**Comment by ramki982** [comment]
This exact crash has happened in a different MQTT Client Framework - https://github.com/ckrey/MQTT-Client-Framework/issues/11 and they have solved it by using some sync wait on the MQTT client. 

Could you help fix the AWS IOT Data Manager also do something similar to avoid crashing on CFNetwork

**Comment by kvasukib** [comment]
Hi @ramki982,

Thanks for reporting to us.

1. Can you describe the scenario in which this occurs? Does it occur every time?
2. Do you perform necessary cleanup - closing the connection and freeing up the resources?
3. Can you attach the debug log if possible?

**Comment by ramki982** [comment]
Hi @kvasukib 

It occurs when there is a switch from LTE and WIFI and such network changes. So the reconnect happens internal to the SDK but not reproduced everytime. 

As pointed to in the last comment - this bug has been open for quite some time across different versions of AWS IOS SDK.

But the issue seems to be in the underlying MQTT Client code which is exactly what is found in https://github.com/ckrey/MQTT-Client-Framework/issues/11

And seems to have exact same stack trace. 

So wanted to check if the fixes suggested in the other mqtt client framework can be considered to fix this.

thanks
Ram

**Comment by bxpan** [comment]
@ramki982 This issue should have already been fixed in previous release. We'll close the this thread if you're not seeing the same issue any more.

Thanks.

**Comment by kvasukib** [comment]
Closing the issue. Please re-open or open a new one if the issue persists.
