### ISSUE TITLE
AWSDDFileLogger doesAppRunInBackground conflict

### ISSUE THREAD

**Issue by slv** [aws/aws-sdk-ios#643]
* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
2.5.4

Since in AWSDDFileLogger.m at line 46 there is a global function "doesAppRunInBackground" with the same name of the function of CocoaLumberjack's function, it fails to compile.
It should be renamed with a prefix like the rest of the file.

Thanks

**Comment by slv** [comment]
duplicate symbol _doesAppRunInBackground in:
    /Users/max/Library/Developer/Xcode/DerivedData/proj-acwuhcdiuzlymggddqqqayylekoj/Build/Products/Release-iphonesimulator/AWSCore/libAWSCore.a(AWSDDFileLogger.o)
    /Users/max/Library/Developer/Xcode/DerivedData/proj-acwuhcdiuzlymggddqqqayylekoj/Build/Products/Release-iphonesimulator/CocoaLumberjack/libCocoaLumberjack.a(DDFileLogger.o)
ld: 1 duplicate symbol for architecture x86_64

**Comment by mohamedadly** [comment]
I also have this issue, I had to downgrade the pod to 2.5.3 to solve the issue.
`pod 'AWSS3', '2.5.3'`

**Comment by rohandubal** [comment]
Hello,

Thank you for reporting this issue, we will update this thread once we have a fix out.

Thanks,
Rohan

**Comment by minbi** [comment]
Version 2.5.5 has been released
