### ISSUE TITLE
Documentation isn't updated on deprecation of AWSLogger and logLevel.

### ISSUE THREAD

**Issue by freak4pc** [aws/aws-sdk-ios#647]
The docs state using `logLevel` on AWSLogger even though the new AWSDDLogger was introduced. The documentation don't state how to set the same flag for the updated logger. 

https://github.com/aws/aws-sdk-ios/#logging

**Comment by minbi** [comment]
Thank you for reporting this.

**Comment by karthiksaligrama** [comment]
Updated. Closing

**Comment by jamesbebbington** [comment]
The updated example reads:

```swift
AWSDDLog.sharedInstance().logLevel = .verbose
```

But I think it should read:

```swift
AWSDDLog.sharedInstance.logLevel = .verbose
```
