### ISSUE TITLE
Transfer Utility (Default) not obeying allowsCellularAccess flag

### ISSUE THREAD

**Issue by andrewkouri** [aws/aws-sdk-ios#648]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS S3 Transfer Utility
* In what version of SDK are you facing the problem?
- all/latest
* Is the issue limited to Simulators / Actual Devices?
- Actual Device
* Can your problem be resolved if you bump to a higher version of SDK?
- No
* Is this problem related to specific iOS version?
- No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
- CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
```
In AppDelegate:
        let credentialProvider = AWSCognitoCredentialsProvider(regionType: .USWest2, identityPoolId: "us-west-x:xxx")
        let configuration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: credentialProvider)
        configuration?.allowsCellularAccess = false

        AWSServiceManager.default().defaultServiceConfiguration = configuration
```

Any following requests don't obey the allowsCellularAccess flag being set to false.

Here's how I am making the request:
```
In a view controller:
        let transferUtility = AWSS3TransferUtility.default()
        transferUtility.uploadFile(...)
```

After making the upload request, I test it by turning off Wi-Fi, and the upload continues over cellular.

**Comment by rohandubal** [comment]
Hi @andrewkouri ,

Thanks for reporting this. We will have a look at it.

Thanks,
Rohan

**Comment by andrewkouri** [comment]
Thanks Rohan -- eagerly awaiting the results of your investigation.

**Comment by rohandubal** [comment]
Hello @andrewkouri 

I did the following steps on my end using the transfer utility sample on github:

1. Use Transfer Utility to upload a file
2. Upload via wifi and wait for success (file uploads successfully)
3. Start upload again over wifi and turn wifi off when progress is 50%
4. Progress bar is stuck and does not move ahead
5. Turn wifi on again, upload starts again

Also this is the LOC where the setting is applied:
https://github.com/aws/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L220

Do you have any other ways in which we can reproduce ths?

Thanks,
Rohan

**Comment by andrewkouri** [comment]
Is the way I'm initializing the default service configuration correct? Looking at the code, it seems like the `+ (instancetype)defaultS3TransferUtility {` method (https://github.com/aws/aws-sdk-ios/blob/master/AWSS3/AWSS3TransferUtility.m#L109) does not take that service configuration into account whatsoever.

What happens if you start an upload on cellular? Not simply start on wifi and then turn off wifi?

Also, can you post the code you used to test on the sample repo?  The only example I see uses the `default` service configuration

**Comment by rohandubal** [comment]
This is the code I used to configure my Transfer Utility Client

```
let credentialsProvider = AWSCognitoCredentialsProvider(
            regionType: .USEast1,
            identityPoolId: "us-east-1:xdsfsdf-32d3-sdfsdf-sdfsdf-sdfsdf")
        
let configuration = AWSServiceConfiguration(
            region: .USEast1,
            credentialsProvider: credentialsProvider)
        
configuration?.allowsCellularAccess = false
        
AWSServiceManager.default().defaultServiceConfiguration = configuration
       
let transferUtility = AWSS3TransferUtility.default()
```

The default configuration does obey the cellular access flag. If you start the upload on cellular, there will be no progress until you connect to a wifi network.

Thanks,
Rohan
