### ISSUE TITLE
Error message should describe problem 

### ISSUE THREAD

**Issue by nevinjethmalani** [aws/aws-sdk-ios#649]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3
* In what version of SDK are you facing the problem?
current (2.5.5)
* Is the issue limited to Simulators / Actual Devices?
both
* Can your problem be resolved if you bump to a higher version of SDK?
no
* Is this problem related to specific iOS version?
no
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
cocoa pods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
We were passing emojis into the meta data by accident. The error read out as "The request signature we calculated does not match the signature your provided. Check your key and signing method." I don't think that is the right error message that should be put there. It is not a big deal but we did waste time looking at the key etc. when it was a simple error with passing characters that weren't allowed.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello @nevinjethmalani 

Thanks for reporting this. Marking this as an enhancement.

Thanks,
Rohan
