### ISSUE TITLE
AWSRekognition Landmark NS_ENUM incorrectly set

### ISSUE THREAD

**Issue by laud** [aws/aws-sdk-ios#650]
Face landmarks are incorrectly serialized and deserialized. The property transformer for AWSRekognitionLandmark type, `+(NSValueTransformer *)typesJSONTransformer`, is using incorrect semantics for the landmarks. The current SDK implementation assumes that word breaks are separated by underscores. However, the API uses camelCase semantics. Please remove underscores in comparison strings in forward and reverse blocks.

For example, in [AWSRekognitionModel.m](https://github.com/aws/aws-sdk-ios/blob/master/AWSRekognition/AWSRekognitionModel.m), change line 714 from
`        if ([value caseInsensitiveCompare:@"EYE_LEFT"] == NSOrderedSame) {
`
to
`        if ([value caseInsensitiveCompare:@"EYELEFT"] == NSOrderedSame) {
`

* What service are you using?
AWSRekognition

* In what version of SDK are you facing the problem?
v2.5.5

* Is the issue limited to Simulators / Actual Devices?
Simulator & Actual Device

* Can your problem be resolved if you bump to a higher version of SDK?
No, it's in current version.

* Is this problem related to specific iOS version?
No, it's an error in Mantle +(NSValueTransformer *)typesJSONTransformer. 

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods. But this is an error in all distributions.

**Comment by rohandubal** [comment]
Hello @laud 

Thank you for reporting this. We will investigate and revert.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
@laud can you tell me from where are you referring the api spec? It seems correct to me.

**Comment by laud** [comment]
It looks like API documentation is different from actual response. Here is the [documentation](http://docs.aws.amazon.com/rekognition/latest/dg/API_DetectFaces.html). In the API spec, underscores are the correct semantics. But from the sample response (and [actual responses](https://console.aws.amazon.com/rekognition/home?region=us-east-1#/face-detection) from the API), camelCase tags are returned. Either the documentation needs to be updated to camelCase (easier), or the API needs to change to underscores (harder for API clients).

**Comment by karthiksaligrama** [comment]
The console might have a different behavior when it tries to display the result. It might be doing a transformation itself. 

The api specs are whats right. Are you getting an error when you make a call to the service from the sdk?

**Comment by laud** [comment]
No errors. It's just that all the landmarks are set with type `AWSRekognitionLandmarkTypeUnknown` except for the nose landmark with type `AWSRekognitionLandmarkTypeNose`. This is because the nose landmark has no spaces (and underscores).

I'd suggest taking a look at the raw JSON response from the Rekognition DetectFace API. It's most definitely using camelCase...
`{
   "FaceDetails":[
      {
         "AgeRange":{
            "High":2,
            "Low":0
         },
         "Beard":{
            "Confidence":99.99393463134766,
            "Value":false
         },
         "BoundingBox":{
            "Height":0.5417323112487793,
            "Left":0.30000001192092896,
            "Top":0.12440945208072662,
            "Width":0.3822222352027893
         },
         "Confidence":99.66996002197266,
         "Emotions":[
            {
               "Confidence":99.31541442871094,
               "Type":"HAPPY"
            },
            {
               "Confidence":2.516043186187744,
               "Type":"SURPRISED"
            },
            {
               "Confidence":0.7923781871795654,
               "Type":"CALM"
            }
         ],
         "Eyeglasses":{
            "Confidence":99.98967742919922,
            "Value":false
         },
         "EyesOpen":{
            "Confidence":99.97037506103516,
            "Value":true
         },
         "Gender":{
            "Confidence":100.0,
            "Value":"Female"
         },
         "Landmarks":[
            {
               "Type":"eyeLeft",
               "X":0.41980627179145813,
               "Y":0.33144858479499817
            },
            {
               "Type":"eyeRight",
               "X":0.5556442141532898,
               "Y":0.346063494682312
            },
            {
               "Type":"nose",
               "X":0.472995787858963,
               "Y":0.40803447365760803
            },
            {
               "Type":"mouthLeft",
               "X":0.42871055006980896,
               "Y":0.49114567041397095
            },
            {
               "Type":"mouthRight",
               "X":0.5524633526802063,
               "Y":0.5028529167175293
            },
            {
               "Type":"leftPupil",
               "X":0.4157116115093231,
               "Y":0.32899850606918335
            },
            {
               "Type":"rightPupil",
               "X":0.5406509041786194,
               "Y":0.34020721912384033
            },
            {
               "Type":"leftEyeBrowLeft",
               "X":0.37689512968063354,
               "Y":0.27034860849380493
            },
            {
               "Type":"leftEyeBrowRight",
               "X":0.41298773884773254,
               "Y":0.25543245673179626
            },
            {
               "Type":"leftEyeBrowUp",
               "X":0.4516240656375885,
               "Y":0.27521705627441406
            },
            {
               "Type":"rightEyeBrowLeft",
               "X":0.5077894330024719,
               "Y":0.2749972939491272
            },
            {
               "Type":"rightEyeBrowRight",
               "X":0.5620320439338684,
               "Y":0.26962795853614807
            },
            {
               "Type":"rightEyeBrowUp",
               "X":0.6095941662788391,
               "Y":0.30604732036590576
            },
            {
               "Type":"leftEyeLeft",
               "X":0.39278510212898254,
               "Y":0.328066349029541
            },
            {
               "Type":"leftEyeRight",
               "X":0.4490252733230591,
               "Y":0.3441503942012787
            },
            {
               "Type":"leftEyeUp",
               "X":0.42001858353614807,
               "Y":0.3170458674430847
            },
            {
               "Type":"leftEyeDown",
               "X":0.4184949994087219,
               "Y":0.34119153022766113
            },
            {
               "Type":"rightEyeLeft",
               "X":0.5252671837806702,
               "Y":0.35197949409484863
            },
            {
               "Type":"rightEyeRight",
               "X":0.586054801940918,
               "Y":0.3514276146888733
            },
            {
               "Type":"rightEyeUp",
               "X":0.5545052289962769,
               "Y":0.3301205337047577
            },
            {
               "Type":"rightEyeDown",
               "X":0.5567663311958313,
               "Y":0.356366366147995
            },
            {
               "Type":"noseLeft",
               "X":0.455196738243103,
               "Y":0.44002780318260193
            },
            {
               "Type":"noseRight",
               "X":0.5080957412719727,
               "Y":0.4442262053489685
            },
            {
               "Type":"mouthUp",
               "X":0.48152387142181396,
               "Y":0.4789465665817261
            },
            {
               "Type":"mouthDown",
               "X":0.48087623715400696,
               "Y":0.549203097820282
            }
         ],
         "MouthOpen":{
            "Confidence":64.68264770507812,
            "Value":false
         },
         "Mustache":{
            "Confidence":97.53254699707031,
            "Value":false
         },
         "Pose":{
            "Pitch":8.570343017578125,
            "Roll":4.238544940948486,
            "Yaw":-9.421775817871094
         },
         "Quality":{
            "Brightness":56.19452667236328,
            "Sharpness":99.9305191040039
         },
         "Smile":{
            "Confidence":99.97782897949219,
            "Value":true
         },
         "Sunglasses":{
            "Confidence":99.9217300415039,
            "Value":false
         }
      }
   ]
}`

**Comment by minbi** [comment]
AWS Mobile SDK for iOS 2.6.8 has been released.

Please re-open if this issue is not resolved.
