### ISSUE TITLE
XCode 7 and v2.5.4+ compatibility issue

### ISSUE THREAD

**Issue by laud** [aws/aws-sdk-ios#651]
In v2.5.4, `CocoaLumberjack` was added for the new `AWSDDLog`. [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack) is only compatible with Xcode 8 as described in their README. All future version builds seem to now be incompatible with Xcode 7.

When building, Xcode 7 throws multiple `Unknown property attribute class` and `Unexepected parameter declarator errors`.

* What service are you using?
AWSCore

* In what version of SDK are you facing the problem?
2.5.4

* Is the issue limited to Simulators / Actual Devices?
Compilation error. Unable to run in either.

* Can your problem be resolved if you bump to a higher version of SDK?
No. Seems like a breaking change since 2.5.4.

* Is this problem related to specific iOS version?
The inclusion of CocoaLumberjack in 2.5.4 appears to break XCode 7 compatibility.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Create a new project. Add in AWSCore to Podfile and create xcworkspace. Open workspace and build. Build error occurs.

**Comment by rohandubal** [comment]
Hello,

Sorry that you are having issues using the SDK.

The SDK is compatible with Xcode 8+. We will update the documentation to reflect that.

Is there a specific reason you are still using Xcode 7?

Thanks,
Rohan

**Comment by laud** [comment]
No worries about backwards compatibility. We've actually moved to XCode8 (finally). We had a few 3rd party libraries that were not yet converted to Swift3. This is no longer the case.
