### ISSUE TITLE
S3 TransferUtility: Authentication delegate not set Error when trying to access a valid unauthenticated S3 resource.

### ISSUE THREAD

**Issue by keshavkaul** [aws/aws-sdk-ios#652]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Cognito, AWS S3

* In what version of SDK are you facing the problem?
2.5.5

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Prebuilt frameworks

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1. Allow unauthenticated user access to S3 via Cognito Identity Pool Unauthenticated User Role Policy.
1. Configure AWS Cognito Identity Provider with Cognito User Pool.
2. Configure AWS S3 with the previously configured Identity Provider.
3. Try downloading or uploading a file to S3 without authenticating with a user using S3 Transfer Utility.

Expected Outcome: 
1. File should download or upload

Actual Outcome:
1. I get an error saying Authentication Delegate not set.
2. I don't require the Authentication Delegate to be set. 

This doesn't happen on android. 

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello @keshavkaul 

Could you please provide us with the code snippet of how you are setting up the credential provider and using it for AWSS3 and AWSS3TransferUtility client?

Thanks,
Rohan

**Comment by keshavkaul** [comment]
This is my setup code:

```
self.credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:[self.region aws_regionTypeValue] identityPoolId:self.identityPoolId];
    
AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:[self.region aws_regionTypeValue] credentialsProvider:self.credentialsProvider];
    
[serviceConfiguration addUserAgentProductToken:ServiceName];
    
AWSCognitoIdentityUserPoolConfiguration *configuration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:self.clientId clientSecret:self.clientSecret poolId:self.userPoolId];
    
[AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration userPoolConfiguration:configuration forKey:@"UserPool"];
    
self.userPool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];
    
[self.credentialsProvider setIdentityProviderManagerOnce:self.userPool];
```
Also my S3 Transfer Utility setup code:

```
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:[[options objectForKey:@"region"] aws_regionTypeValue] credentialsProvider:credentialsService.credentialsProvider];

[AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:configuration forKey:@"react-native-transfer-utility"];

[configuration addUserAgentProductToken:@"AwsS3"];

transferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:@"react-native-transfer-utility"];
```

And I'm using TransferUtillity's upload API.

**Comment by rohandubal** [comment]
I see that you are setting the userPool as Identity Provider Manager which is not correct. You should be using the code in the following link to set up user pools as an identity provider. http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html 

This should fix the issue. 

Thanks,
Rohan

**Comment by keshavkaul** [comment]
@rohandubal I was initially using the documented way to integrate user pool with federated identities:
```
AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:nil];

AWSCognitoIdentityUserPoolConfiguration *userPoolConfiguration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:@"YOUR_CLIENT_ID"  clientSecret:@"YOUR_CLIENT_SECRET" poolId:@"YOUR_USER_POOL_ID"];

[AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration userPoolConfiguration:userPoolConfiguration forKey:@"UserPool"];

AWSCognitoIdentityUserPool *pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];

AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"YOUR_IDENTITY_POOL_ID" identityProviderManager:pool];
```
But this too was giving me the same error. hence i tried modifying the code to its current version.

But alas I gave up and am fixing this by using the following method ie not initially assigning user pool to federated identity. When user logs in using `getSession:username:password` i set the identity provider as userpool.

Initial Config
```
self.credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:[self.region aws_regionTypeValue] identityPoolId:self.identityPoolId];
    
AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:[self.region aws_regionTypeValue] credentialsProvider:self.credentialsProvider];
    
[serviceConfiguration addUserAgentProductToken:ServiceName];
    
AWSCognitoIdentityUserPoolConfiguration *configuration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:self.clientId clientSecret:self.clientSecret poolId:self.userPoolId];
    
[AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration userPoolConfiguration:configuration forKey:@"UserPool"];
    
self.userPool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];
```

After User Logs In:
```
[[[self credentialsService] credentialsProvider] setIdentityProviderManagerOnce:[[self userPoolService] userPool]];
```

My method is working for the time being for unauthenticated access. But I think, with this solution, i cannot convert unauthenticated users to authenticated users.

**Comment by keshavkaul** [comment]
@rohandubal Any comments ?
