### ISSUE TITLE
AWSLexVoiceButton without storyboard

### ISSUE THREAD

**Issue by mspraley** [aws/aws-sdk-ios#654]
I can initialize a AWSLexVoiceButton in Swift using

`        self.voiceButton = AWSLexVoiceButton();
`

and then add it to my view. However, the only initializer that setups the button (images, delegate, addTarget) is with a coder: aDecoder meaning I need it setup in a storyboard. Is there really no way I can setup the button without a storyboard? #

**Comment by rohandubal** [comment]
Hello @mspraley 

Currently story board is the only way to initialize the Lex button. I will take this as a feature request to the team.

Thanks,
Rohan
