### ISSUE TITLE
AWS CocoaLumberJack extension conflicting with Default CocoaLumberJack in XMPPFramework

### ISSUE THREAD

**Issue by vickydhas** [aws/aws-sdk-ios#655]
Hello We are using Robbiehanson XMPPframework which is using the CocoaLumberJAck library.

However after using AWS for our S3 usage SDK, the CocoaLumberJack #defines are conflicting and leading to error, warnings and no printing of our existing library logs.

We have tried replacing the logs at our side code but the XMPPFramework is Pod framework that automatically used CocoaLumberJack which cannot be modified.

This is leading to conflict and logging errors. Please resolve.

**Classic Example:** 
Tried your below solution also but doesnt work , constantly gives warnings and unable to use the THIS_FILE, THIS_METHOD functions given in DDLogs.

Its due to following statement is used in two places.

    #define LOG_LEVEL_DEF ddLogLevel

#warning CocoaLumberjack 1.9.x legacy macros enabled. \
Disable legacy macros by importing AWSCocoaLumberjack.h or AWSDDLogMacros.h instead of AWSDDLog.h or add `#define AWSDD_LEGACY_MACROS 0` before importing AWSDDLog.h.

**Comment by vickydhas** [comment]
One more user facing similar issue , so the fix have to be in the AWS SDK as Pods every time will overwrite out modifications.

https://github.com/magicalpanda/MagicalRecord/issues/1125

**Comment by rohandubal** [comment]
Hi, 

Thanks for reporting this issue. We will investigate and revert.

Thanks,
Rohan

**Comment by rohandubal** [comment]
I have the following configuration and not able to reproduce the issue:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target :'MyTarget' do
    pod 'AWSS3', '~> 2.5.5'
    pod 'XMPPFramework', '~> 3.7.0'
end
```

Are you consuming the frameworks via cocoapods? If not, how are you consuming them?

Could you provide steps to reproduce?

Thanks,
Rohan

**Comment by vikram17000** [comment]
Hi - I seem to be getting the same issue. I've integrated the AWS frameworks dynamically (not via CocoaPods / Carthage) - I get the exact same DDLog error...

**Comment by minbi** [comment]
AWS Mobile SDK for iOS v2.5.6 has been released

**Comment by vickydhas** [comment]
Okay will check if the warning goes else reopen the issue.

But one thing as my XMPP framework is using the cocoa lumberjack and aws is
using customized one.

I have to keep both due to this.

Will this conflict all classes.
-- 
Sent from my iPhone6+

**Comment by vikram17000** [comment]
Thanks but unfortunately, the errors still persist for the macros LOG_MAYBE, LOG_MACRO and THIS_FILE. Do we need to adopt the same fix for them and then create frameworks?

**Comment by vickydhas** [comment]
My suggestion would be if you have renamed all the cocoalumberjack classes
then rename the constants also so no project warnings will occur for
ambiguous.


Other option is to inherit AWS library than just renaming all files with
AWSCocoalumberjackfilenames.h/m
-- 
Sent from my iPhone6+

**Comment by ppoletti** [comment]
I am seeing a similar issue with conflicting LOG_MAYBE definitions. One is the definition defined in CocoaLumberJack in the DDLogMacros.h file that is used by many of our internal pods and the other is in AWSDDLogMacros.h which is in the AWSCore pod. It looks like this file is copied and pasted with a prefix on the front off many of the higher level macros but as you dig deeper you can see on line 75 of AWSDDLogMacros.h which does not have a AWS specific prefix or suffix.

#define LOG_MAYBE(async, lvl, flg, ctx, tag, fnct, frmt, ...) \
        do { LOG_MACRO(async, lvl, flg, ctx, tag, fnct, frmt, ##__VA_ARGS__); } while(0)

This conflicts with at least in my version the same named define of the following.

#define LOG_MAYBE(async, lvl, flg, ctx, tag, fnct, frmt, ...) \
        do { if(lvl & flg) LOG_MACRO(async, lvl, flg, ctx, tag, fnct, frmt, ##__VA_ARGS__); } while(0)

on line 82 of my version of CocoaLumberJack within the DDLogMacros.h file. We are not using Carthage and only pods in our configuration.

**Comment by vickydhas** [comment]
I would like to keep this issue open as the issue still exist in the latest cocoa pods.

Also I have installed the XMPP framework using pods and same goes for AWS.

Attached the screenshot to the issue referenced in this conversation

**Comment by vickydhas** [comment]
Issue exist for the THE_FILE, THE_METHOD MACROS

....Filename.m.m:333:    DDLogDebug(@"socketDidConnect %@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:340:    DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:395:    DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:456:    DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:461:    DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:473:    DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:482:    DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:521:    DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:1125:    DDLogVerbose(@"%@: %@ - %@", THIS_FILE, THIS_METHOD, [presence fromStr]);
....Filename.m.m:1170:    DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:1270:    DDLogDebug(@"%@: %@ : %@", THIS_FILE, THIS_METHOD,enabled);
....Filename.m.m:1277:        DDLogDebug(@"%@: %@ : %@", THIS_FILE, THIS_METHOD,stanzaIds);
....Filename.m.m:1299:    DDLogDebug(@"%@: %@ : %@", THIS_FILE, THIS_METHOD,failed);
....Filename.m.m:1307:    DDLogDebug(@"%@: %@ : %u", THIS_FILE, THIS_METHOD,connectionFlags);

<img width="918" alt="screen shot 2017-05-19 at 2 32 41 pm" src="https://cloud.githubusercontent.com/assets/834663/26235869/0b1e4580-3ca0-11e7-8b42-2aee4f5d20e4.png">

**Comment by joshuafeldman** [comment]
+1 getting warning for `#define THIS_FILE`
