### ISSUE TITLE
AWS Cognito crash related to JSON transformer (Mantle)

### ISSUE THREAD

**Issue by binho** [aws/aws-sdk-ios#660]
* What service are you using?
*AWS Cognito*

* In what version of SDK are you facing the problem?
*v2.5.3*

* Is the issue limited to Simulators / Actual Devices?
*Both simulator and device is affected*

* Can your problem be resolved if you bump to a higher version of SDK?
*No*

* Is this problem related to specific iOS version?
*Yes*

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
*CocoaPods*

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

*When I try to sign up or sign in using user pools I got the crash:*
```
2017-05-06 09:48:21.284 Trivia[97880:52269181] *** Assertion failure in +[NSValueTransformer awsmtl_JSONDictionaryTransformerWithModelClass:], /Users/binho/Documents/dev/MetaLab/nc2-sdk-ios/Pods/AWSCore/AWSCore/Mantle/NSValueTransformer+AWSMTLPredefinedTransformerAdditions.m:51
2017-05-06 09:48:21.291 Trivia[97880:52269181] *** Caught exception Invalid parameter not satisfying: [modelClass isSubclassOfClass:AWSMTLModel.class] parsing JSON key path "AuthenticationResult" from: {
    AuthenticationResult =     {
        AccessToken = "...";
        ExpiresIn = 3600;
        IdToken = "...";
        NewDeviceMetadata =         {
            DeviceGroupKey = "...";
            DeviceKey = "...";
        };
        RefreshToken = "...";
        TokenType = Bearer;
    };
    ChallengeParameters =     {
    };
}
```

I already tried updating for the last SDK version and got same error. Also tried to create new User Pool.

The crash happens in `NSParameterAssert([modelClass isSubclassOfClass:AWSMTLModel.class]);` inside `NSValueTransformer+AWSMTLPredefinedTransformerAdditions` class.

Other pods I'm using in the project:
```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Google/SignIn'
pod 'AFNetworking', '~> 3.0'
```

Thanks!

**Comment by vysotsky** [comment]
Is this still open?
I've faced with the same issue and trying to investigate what's going wrong.

**Comment by behrooziAWS** [comment]
1. What device tracking configuration do you have on your pool?
2. Seems like that error can only happen during sign in, not sign up.
3. Are you setting the pool.delegate to do interactive login or using the [getSession](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityUser.html#//api/name/getSession:password:validationData:) w/password method?
4. Have you tried updating your Podspec to point at 2.6.9?
