### ISSUE TITLE
Please fix include case in AWSMobileAnalyticsDefaultDeliveryClient.m

### ISSUE THREAD

**Issue by minimalistcode** [aws/aws-sdk-ios#662]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific iOS version?

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by minimalistcode** [comment]
In the file AWSMobileAnalyticsDefaultDeliveryClient.m there is an include statement:

`#import "AWSMObileAnalyticsDefaultSessionClient.h"`

It has a capital O instead of lower case on the word Mobile.  Can you please fix the O in Mobile so it's lower case so we don't get a compiler warning?  The correct import statement should be:

`#import "AWSMobileAnalyticsDefaultSessionClient.h"`

Thanks.

**Comment by rohandubal** [comment]
Fixed with 2.5.7.
