### ISSUE TITLE
AWS resources tagging

### ISSUE THREAD

**Issue by olbartek** [aws/aws-sdk-ios#663]
Hello,
Is there a way to upload a resource and tag it with only one request? Right now, using AWS SDK, I am able to upload a file and then tag it using `AWSS3PutObjectTaggingRequest`.

Thanks for help.

**Comment by rohandubal** [comment]
You could tag the resources while uploading them using the x-amz-tagging parameter as specified here: http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html. 

Could you specify how are you uploading your object?

Thanks,
Rohan

**Comment by olbartek** [comment]
Hi Rohan, 
Currently I am uploading an object using `AWSS3TransferManager` & `AWSS3TransferManagerUploadRequest` and then after a successful upload I am tagging the object using `AWSS3PutObjectTaggingRequest `. 
Now, I assume that I should use `AWSS3PutObjectRequest` and specify tagging variable within that request?

**Comment by rohandubal** [comment]
`AWSS3TransferManagerUploadRequest` inherits from `AWSS3PutObjectRequest`, so you should be able to set the tagging in the same upload request using the `tagging` property.
Links:
https://github.com/aws/aws-sdk-ios/blob/b79dbbc9b1547684092028792c0a17448265705a/AWSS3/AWSS3TransferManager.h#L241
https://github.com/aws/aws-sdk-ios/blob/4ec54488b0c8d226278e68f82530834c749aadf0/AWSS3/AWSS3Model.h#L5075

Thanks,
Rohan

**Comment by shirishpickup** [comment]
Late to the discussion. 
But can i add multiple tags with AWSS3TransferManagerUploadRequest ?
