### ISSUE TITLE
#667 re-open, AWSS3TansferUtility

### ISSUE THREAD

**Issue by beautynanacalico** [aws/aws-sdk-ios#668]
To help us solve your problem better, please answer the following list of questions.

What service are you using?
AWSS3TransferUtility

In what version of SDK are you facing the problem?
2.5.6

Is the issue limited to Simulators / Actual Devices?
Both

Can your problem be resolved if you bump to a higher version of SDK?
Current version is latest.

Is this problem related to specific iOS version?
10.X

How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

rohandubal, a kindly developer who answer for me,

```
AWSS3TransferUtility(forKey: "transfer-acceleration").uploadData(fileData, bucket: bucket, key: key,....
```

But I can't find initializer, (forKey:...)
[screenshot file link](https://s3.ap-northeast-2.amazonaws.com/karlstyner/screenshot.png)

How can I do that?

**Comment by beautynanacalico** [comment]
Oh no.................

The Fu...ing document!

annotation in ios sdk, 

```
*Swift*
    let S3TransferUtility = AWSS3TransferUtility(forKey: "USWest2S3TransferUtility")
```

But It's incorrect. 
I found something written just below:

```
*Objective-C*
    AWSS3TransferUtility *S3TransferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:@"USWest2S3TransferUtility"];
```

Correctly "Swift" way is:

```
AWSS3TransferUtility.s3TransferUtility(forKey: "USWest2S3TransferUtility")
```

In the next version (2.5.7), please correct the incorrect comment above.

**Comment by rohandubal** [comment]
@beautynanacalico Which is the Swift version you are using?

**Comment by beautynanacalico** [comment]
I'm using Swfit3

**Comment by rohandubal** [comment]
Thanks for reporting this. We will update the documentation.

Thanks,
Rohan
