### ISSUE TITLE
How can I add a interceptor for AWSAPIGatewayClient?

### ISSUE THREAD

**Issue by zhihuitang** [aws/aws-sdk-ios#669]
I am using **Google-login+Cognito** in Swift. As we known the google token will expire every 1 hour, in that case I get 404 error:

    {"__type":"NotAuthorizedException","message":"Access to Identity 'eu-west-1:06245164-17b8-4704-bc14-4bdff5610123' is forbidden."}

Here is my request from iPhone:

    POST / HTTP/1.1
    Host: cognito-identity.eu-west-1.amazonaws.com
    Content-Type: application/x-amz-json-1.1
    X-Amz-Target: AWSCognitoIdentityService.GetCredentialsForIdentity
    Accept-Encoding: gzip, deflate
    Connection: keep-alive
    Accept: */*
    User-Agent: aws-sdk-iOS/2.3.4 iOS/10.3.2 en
    Content-Length: 63
    Accept-Language: en-us
    X-Amz-Date: 20170511T152945Z

    {"IdentityId":"eu-west-1:06245164-17b8-4704-bc14-4bdff5610123"}

I was wondering, can I set a interceptor for my AWSAPIGatewayClient? so that once I get "NotAuthorizedException" I can retry my  request?

I googled a lot but couldn't find any clue.

thank you very much.

**Comment by rohandubal** [comment]
Hello @zhihuitang 

Are you setting an identity manager in your configuration? Can you refresh the token  once it is going to expire so that cognito will fetch new credentials before calling the retried service call?

Thanks,
Rohan

**Comment by zhihuitang** [comment]
Thank you @rohandubal ,
I am not what do you mean identity manager, here is my initializer function:
```
fileprivate init() {
        //AWS Init
        //let logins = [provider.rawValue : token]
        AWSLogger.default().logLevel = AWSLogLevel.verbose
        
        //keyChain = UICKeyChainStore(service: NSBundle.mainBundle().bundleIdentifier!)
        AWSLogger.default().logLevel = AWSLogLevel.error
        identityPoolId = conf.getCognitoIdentityPoolId()
        developerProviderName = conf.getCognitoDeveloperProvider()
        
        self.credentialsProvider = AWSCognitoCredentialsProvider(regionType: CognitoRegionType, identityPoolId: self.identityPoolId)
        let configuration = AWSServiceConfiguration(region: CognitoRegionType, credentialsProvider: self.credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
    }
```

What is the best practise to detect that token is going to expire? To check timestamp before every request?
Now I have a scheduledTimer to refresh Google Token and CognitoId. But I don't think it is the best practise to refresh token. 
```
timer = Timer.scheduledTimer(timeInterval: TOKEN_REFRESH_PERIOD,
                                 target: self,
                                 selector: #selector(self.refreshGoogleToken),
                                 userInfo: nil,
                                 repeats: true)

```

May be you have better solution?

**Comment by rohandubal** [comment]
Hi, what I meant was, how are you federating the Google token with Cognito?

**Comment by zhihuitang** [comment]
Here is my code, I am using AWSCognitoCredentialsProvider.refresh to get new cognitoId.
And it works. But I was wondering when to trigger the refresh process? Now I am using a 30-min-timer to refresh google-token and cognitoId, but I don't think it is a good practise.


    ```
 func connectWithGoogle(_ token: String) -> AWSTask<AnyObject>? {
        self.useDeveloperAuthenticatedIdentities = false
        let logins = [AWSCognitoLoginProviderKey.google.rawValue: token]
        
        credentialsProvider!.logins = logins

      // credentialsProvider: AWSCognitoCredentialsProvider
        return credentialsProvider!.refresh().continue({ (task: AWSTask!) -> AnyObject! in
            if let newCognitoId = task.result as? String {
                self.cognitoId = newCognitoId
            }
            return task
        })
```

**Comment by zhihuitang** [comment]
I saw the **responseInterceptors** in the class **AWSNetworkingConfiguration**

```
open class AWSNetworkingConfiguration : NSObject, NSCopying {

    
    open var url: URL! { get }

    open var baseURL: URL!

    open var urlString: String!

    open var httpMethod: AWSHTTPMethod

    open var headers: [AnyHashable : Any]!

    
    open var requestSerializer: AWSURLRequestSerializer!

    open var requestInterceptors: [Any]! // Array of AWSNetworkingRequestInterceptor.

    open var responseSerializer: AWSHTTPURLResponseSerializer!

    open var responseInterceptors: [Any]! // Array of AWSNetworkingResponseInterceptor.

    open var retryHandler: AWSURLRequestRetryHandlerProtocol!

```

but they say nothing about **responseInterceptors** the in there documentation.

**Comment by minbi** [comment]
The interceptor is just a protocol, so you can pass any object that implements the required method.

```
@protocol AWSNetworkingHTTPResponseInterceptor <NSObject>

@required
- (AWSTask *)interceptResponse:(NSHTTPURLResponse *)response
                         data:(id)data
              originalRequest:(NSURLRequest *)originalRequest
               currentRequest:(NSURLRequest *)currentRequest;

@end
```

**Comment by zhihuitang** [comment]
Thank you @minbi , I did like you said, I am able to intercept request, but cannot intercept response. It never goes to MyResponseInteceptor. Please help.

```
// init client
func initClient(){
    let requestInterceptor = MyrequestInteceptor()
    if client.configuration.requestInterceptors != nil {
        client.configuration.requestInterceptors.append(requestInterceptor)
    } else {
        client.configuration.requestInterceptors = [requestInterceptor]
    }

    let responseInterceptor = MyResponseInteceptor()
    if client.configuration.responseInterceptors != nil {
        client.configuration.responseInterceptors.append(responseInterceptor)
    } else {
        client.configuration.responseInterceptors = [responseInterceptor]
    }

}
```
here are my interceptor
```
class MyrequestInterceptor: AWSNetworkingRequestInterceptor {
    override func interceptRequest(_ request: NSMutableURLRequest!) -> AWSTask<AnyObject>! {
        // interceptRequest works, can see the following output
        print("intercepted request here: \(request.debugDescription)")
        return super.interceptRequest(request)
    }
}

class MyResponseInteceptor: NSObject, AWSNetworkingHTTPResponseInterceptor {
    func interceptResponse(_ response: HTTPURLResponse!, data: Any!, originalRequest: URLRequest!, currentRequest: URLRequest!) ->     AWSTask<AnyObject>! {
        // interceptResponse doesn't work, cannot see the following output
        print("intercepted response here: \(response.debugDescription)")
        return AWSTask(result: response)
    }    
}
```
