### ISSUE TITLE
Apparent problem with SNS error parsing during response serialization process

### ISSUE THREAD

**Issue by trojas** [aws/aws-sdk-ios#671]
* What service are you using?
SNS

* In what version of SDK are you facing the problem?
2.5.6

* Is the issue limited to Simulators / Actual Devices?
Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
N/A - at the latest version

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

My steps to reproduce are as follows:

1. Create a platform endpoint using AWSSNS createPlatformEndpoint
2. Log into the SNS console and delete the endpoint
3. Attempt to get the platform attributes using AWSSNS getEndpointAttributes

Expected result: I was expecting to receive an error with the code: AWSSNSErrorNotFound. 
Actual result: I received and error with code: 0, which in reading the SDK code appears to be from AWSCognitoIdentityErrorUnknown.

I've attached a couple of screen shots from my debugging which show that there is apparently a mismatch between the fields of the responseObject from AWSXMLResponseSerializer and the parsing done by the subclass, AWSSNSResponseSerializer.  If I change the SDK code to look for the correct fields, my client code works.  I'm more than happy to submit a pull request if you deem this is an actual issue.  If it's determined that I'm somehow doing something wrong, any help would be appreciated.  Also, please let me know if any more info is needed.

<img width="808" alt="screen shot 2017-05-12 at 11 59 03 am" src="https://cloud.githubusercontent.com/assets/5531120/26015544/506aa334-3716-11e7-8561-1c0f510b1703.png">

<img width="810" alt="screen shot 2017-05-12 at 12 01 04 pm" src="https://cloud.githubusercontent.com/assets/5531120/26015543/5069f1b4-3716-11e7-9c4e-2d2857527256.png">

**Comment by rohandubal** [comment]
Hi,

Thanks for reporting this, we have identified the issue and will be working on a fix for this.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Fixed with 2.5.8.
