### ISSUE TITLE
Can't display verbose Logging in AWS iOS SDK

### ISSUE THREAD

**Issue by luisschubert** [aws/aws-sdk-ios#672]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS S3 

* In what version of SDK are you facing the problem?
2.5.6
* Is the issue limited to Simulators / Actual Devices?
Xcode
* Can your problem be resolved if you bump to a higher version of SDK?
no
* Is this problem related to specific iOS version?
no
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
cocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

This code will be flagged as deprecated code, but it is the code you present in your docs.
http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSLogger.html#//api/name/logLevel
AWSLogger.default().logLevel = .verbose

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
We suggest to migrate to use the new logging mechanism as described here:
https://github.com/aws/aws-sdk-ios#logging

We will mark the AWSLogger as deprecated in documentation.

Thanks,
Rohan
