### ISSUE TITLE
AWSLambda and clock skew handling

### ISSUE THREAD

**Issue by premiumbosslimited** [aws/aws-sdk-ios#673]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWSLambda

* In what version of SDK are you facing the problem?

2.5.6

* Is the issue limited to Simulators / Actual Devices?

I tested on Actual Devices.

* Is this problem related to specific iOS version?

No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Prebuilt frameworks

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If the device clock is wrong when executing the request to the AWS API,  InvalidSignatureException response is returned.
As far as the code of AWSURLSessionManager is concerned, when the corresponding error occurs, it is trying to retry by calling [NSDate aws_setRuntimeClockSkew:].
https://github.com/aws/aws-sdk-ios/blob/91426a8faf782cbae1f1ee60f217adac5534047b/AWSCore/Networking/AWSURLSessionManager.m#L300

For example, AWSSNS executes this process and succeeds after the retry. However, AWSLambda seems to be an error because the above process is not executed.
Is this behaving as expected?

**Comment by rohandubal** [comment]
Fixed with 2.5.7.
