### ISSUE TITLE
AWSMobileAnalyticsDefaultDeliveryClient.m import warning

### ISSUE THREAD

**Issue by omaestra** [aws/aws-sdk-ios#674]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
aws-sdk-ios

* In what version of SDK are you facing the problem?
2.5.6

In AWSMobileAnalyticsDefaultDeliveryClient.m file, there is a warning caused by a uppercased letter in line 25 #import "AWSMobileAnalyticsDefaultSessionClient.h"

**Comment by mlshon** [comment]
Hi, thank you for letting us know! We will update this thread once this issue is fixed.

**Comment by mlshon** [comment]
Hi, we released the new SDK. This issue has been fixed.
