### ISSUE TITLE
How to access Gateway generated models

### ISSUE THREAD

**Issue by syn-jayesh-kacha** [aws/aws-sdk-ios#675]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Using AWSAPIGateway/AWSCore modules for iOS SDK using Cocoapods Swift project

* In what version of SDK are you facing the problem?
2.5.3

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

- We are generating Swift/Android SDK based on models defined at AWS Gateway, however Generated Swift SDK has created class in different way for array (list of objects for GET service)

Please look at JSON definition as below.  Generated Swift/Android class for reference, In Android we can access list in correct way as it is subclass of **ArrayList<PersonListItem>**, however we are unsure how to access the list from swift generated model **TESTPersonList**, as it subclass of **AWSModel** 

`
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "items": {
        "id": "/items",
        "properties": {
            "address": {
                "id": "/items/properties/address",
                "properties": {
                    "city": {
                        "id": "/items/properties/address/properties/city",
                        "type": "string"
                    },
                    "geo": {
                        "id": "/items/properties/address/properties/geo",
                        "properties": {
                            "lat": {
                                "id": "/items/properties/address/properties/geo/properties/lat",
                                "type": "string"
                            },
                            "lng": {
                                "id": "/items/properties/address/properties/geo/properties/lng",
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "street": {
                        "id": "/items/properties/address/properties/street",
                        "type": "string"
                    },
                    "suite": {
                        "id": "/items/properties/address/properties/suite",
                        "type": "string"
                    },
                    "zipcode": {
                        "id": "/items/properties/address/properties/zipcode",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "company": {
                "id": "/items/properties/company",
                "properties": {
                    "bs": {
                        "id": "/items/properties/company/properties/bs",
                        "type": "string"
                    },
                    "catchPhrase": {
                        "id": "/items/properties/company/properties/catchPhrase",
                        "type": "string"
                    },
                    "name": {
                        "id": "/items/properties/company/properties/name",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "email": {
                "id": "/items/properties/email",
                "type": "string"
            },
            "id": {
                "id": "/items/properties/id",
                "type": "integer"
            },
            "name": {
                "id": "/items/properties/name",
                "type": "string"
            },
            "phone": {
                "id": "/items/properties/phone",
                "type": "string"
            },
            "username": {
                "id": "/items/properties/username",
                "type": "string"
            },
            "website": {
                "id": "/items/properties/website",
                "type": "string"
            }
        },
        "type": "object"
    },
    "type": "array"
}
`

Using above definition Generated java model for PersonList object as below 
_file: PersonList.java_

```
package test.model;

import java.util.ArrayList;
import java.util.*;
import test.model.PersonListItem;
public class PersonList extends ArrayList<PersonListItem> {
}

```

_file: PersonListItem.java_
 
import test.model.PersonListItemAddress;
import test.model.PersonListItemCompany;

```
public class PersonListItem {
    @com.google.gson.annotations.SerializedName("address")
    private PersonListItemAddress address = null;
    @com.google.gson.annotations.SerializedName("company")
    private PersonListItemCompany company = null;
    @com.google.gson.annotations.SerializedName("email")
    private String email = null;
    @com.google.gson.annotations.SerializedName("id")
    private Integer id = null;
    @com.google.gson.annotations.SerializedName("name")
    private String name = null;
    @com.google.gson.annotations.SerializedName("phone")
    private String phone = null;
    @com.google.gson.annotations.SerializedName("username")
    private String username = null;
    @com.google.gson.annotations.SerializedName("website")
    private String website = null;
.......

```

Using above definition Generated Swift model for TESTPersonList object as below 
_file: TESTPersonList.swift_
```
import Foundation
import AWSCore
public class TESTPersonList : AWSModel 
{
}
```
Generated Swift TESTPersonList_item model

_file: TESTPersonList_item.swift_

```
import Foundation
import AWSCore

public class TESTPersonList_item : AWSModel {
    var address: TESTPersonList_item_address?
    var company: TESTPersonList_item_company?
    var email: String?
    var id: NSNumber?
    var name: String?
    var phone: String?
    var username: String?
    var website: String?
.....

```

**Comment by mlshon** [comment]
This is a limitation of how the iOS SDK is generated.
There is a [workaround](https://forums.aws.amazon.com/thread.jspa?threadID=219703) for this though.

**Comment by woph** [comment]
Hi Folks,

we're also facing this issue and unfortunately the workaround doesn't work for us.
Is there in the meantime a better solution available?
APIGateway is giving us a hard time.

Please find below the following APIGateway schema definition for our response body.

`responses:
                    "200":
                      description: Some fancy description
                      schema:
                        type: object
                        properties:
                          listItems:
                            type: array
                            items:
                              type: object
                              properties:
                                  name:
                                    type: string
                                    description: FOOFOO
                                  streamingUri:
                                    type: string
                                    description: FOOFOOFOO
                                  filesize:
                                    type: string
                                    description: FOOFOOFOOFOO`

We're currently using Swift 4 but same problem also occurs when switching back to Swift 3.2.
During debbuging we can see that we're getting a response from the service itself. Unfortunately the convertion process is somehow losing the content and the used (generated) AWS Models do not carry any infromation.

Kind regards
Philipp
