### ISSUE TITLE
The operation couldn’t be completed. (com.amazonaws.AWSSNSErrorDomain error 0.)

### ISSUE THREAD

**Issue by aniliosdev** [aws/aws-sdk-ios#676]
I used latest SDK in cocoa-pod, I got this error "The operation couldn’t be completed. (com.amazonaws.AWSSNSErrorDomain error 0.)" when create createPlatformEndpoint some time. what is the issue??

**Comment by mlshon** [comment]
Could you please provide more details for us?
Sample code, stacktrace, SNS region, SDK version?

**Comment by rohandubal** [comment]
Thanks for reporting this issue. We have identified the issue and will be working on a fix for this.

Thanks,
Rohan

**Comment by aniliosdev** [comment]
@mlshon I used latest sdk. and region is sydney.

let myArn  = SNS_BASE_ARN + APP_ARN
            let platformEndPointRequest = AWSSNSCreatePlatformEndpointInput()
            platformEndPointRequest?.customUserData = POUserPrefrences.sharedInstance().currentUser.username!
            
            platformEndPointRequest?.platformApplicationArn = myArn
            platformEndPointRequest?.token = deviceTokenForAWS
            
            snsManager.createPlatformEndpoint(platformEndPointRequest!).continueWith (block: { (task) -> AnyObject? in
                if let res = task.result
                {
                    let topicArn = SNS_BASE_ARN+randomID
                    POGlobalData.subscribeTopicArnToEndPointARN(topicArn: topicArn, endPointArn: res.endpointArn!, completionBlock: { (success) -> () in
                        completionBlock(success)
                    })

                }
                else
                {
                    print(task.error?.localizedDescription ?? "no error");
                    completionBlock(false)
                }
                return task
            })

**Comment by karthiksaligrama** [comment]
related to #671 , Closing in favor of tracking in single place
