### ISSUE TITLE
Crash in AWSS3TransferUtility

### ISSUE THREAD

**Issue by nick3389** [aws/aws-sdk-ios#677]
In aws-ios SDK 2.5.5 (from cocoapods) there is a random crash in AWSS3TransferUtility's NSURLSessionDelegate URLSession:task:didCpmpleteWithError. I received this crash from Crashlytics platform:

Fatal Exception: Invalid NSURLSession state
Expected response of type NSHTTPURLResponse

**Comment by karthiksaligrama** [comment]
related to https://github.com/aws/aws-sdk-ios/issues/490
