### ISSUE TITLE
Crash in AWSCognitoIdentityUserPool calculateSecretHash

### ISSUE THREAD

**Issue by zrzka** [aws/aws-sdk-ios#679]
# Description

Several new users started complaining that they're unable to sign in in our iOS application. Application simply crashes. But they are able to sign in via web interface, ... I was scratching my head for a few minutes and then I found that they have accented characters in usernames. Tried this case with new user and cause was identified.

# Steps to reproduce

* Create user with username containing accented characters (_Kaštanek_ for example)
* Try to sign in on iOS
* Crash

# Crash description

* It crashes on this line https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L254
* Because `cData` contains `null` -> `strlen(cData)` -> `strlen(null)` -> crash https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L250
* And that's because `cStringUsingEncoding:NSASCIIStringEncoding` returns `null` because it can't be losslessly converted to ASCII encoding.

Documentation quote:

> A C string representation of the receiver using the encoding specified by encoding. **Returns NULL if the receiver cannot be losslessly converted to encoding.**

Documentation [source](https://developer.apple.com/reference/foundation/nsstring/1408489-cstringusingencoding?language=objc).

**Comment by behrooziAWS** [comment]
That is definitely a bug, I'll fix for a later release.  Thanks for reporting.

**Comment by zrzka** [comment]
@behrooziAWS I assume `NSUTF8StringEncoding` is correct encoding? Have to fix it locally and send new version to App Store as soon as possible. But don not want to send it to the App Store until someone confirms it. Thanks.

**Comment by behrooziAWS** [comment]
This was fixed in 2.5.8.  Please reopen if you continue to have issues.
