### ISSUE TITLE
KMS Encrypt Swift 3.0

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [aws/aws-sdk-ios#681]
Did you have an example of how can we Encrypt a plain text with KMS in Swift 3
Version 10.3
Regards.

**Comment by minbi** [comment]
We don't have a Swift 3 sample, but the translation to Swift should be straight forward.
An example of encrypting plain text can be found in the tests.
https://github.com/aws/aws-sdk-ios/blob/b7c4d59954e15d9cbd041f8d1e8c6ef7742f68bb/AWSKMSTests/AWSKMSTests.m#L170

**Comment by ulisescarreonalvarez** [comment]
Yes, i already did, thanks!

```
let encrypt = AWSKMSEncryptRequest()
        let input = "Hello World"
        let data_ = input.data(using: .utf8)!
        encrypt?.plaintext = data_
        encrypt?.keyId = "ARN"
        client.encrypt(encrypt!).continueWith { (task: AWSTask<AWSKMSEncryptResponse>) -> Any? in
            print(task.result)
            return nil
        }
    }
```

**Comment by Mindbowser** [comment]
@rohandubal @ulisescarreonalvarez 
I want to send encryptedData in API on server to save in database, when I convert it to string using let encrytionString = String(data: encryptionData!, encoding: NSUTF8StringEncoding), it is giving nil, any idea why and how I can sort this out so that backend decryption which is in Java works? Any idea how it can be sorted out?

**Comment by ulisescarreonalvarez** [comment]
@Mindbowser Try this, it works for my app

```
let client = AWSKMS.default()
let encrypt = AWSKMSEncryptRequest()
let input = "INFO_TO_ENCRYPT"
let data_ = input.data(using: .utf8)!
encrypt?.plaintext = data_
                encrypt?.keyId = "ARN_KEY_AWS"
                client.encrypt(encrypt!).continueWith { (task: AWSTask<AWSKMSEncryptResponse>) -> Any? in
                    let response = task.result
                    print("Encrypted data")
                    print(response?.ciphertextBlob?.base64EncodedString())
                    return nil
                }

```

**Comment by Mindbowser** [comment]
Thanks @ulisescarreonalvarez . On backend what is the approach you are doing to decrypt it?

**Comment by ulisescarreonalvarez** [comment]
@Mindbowser You need to control it with IAM Policy, becase the arn of your Encrypt Data must be only for "Encrypt" on the backend you need set the credentials with a role that can only "Decrypt" the info. You should never use the same ARN:Role for encrypt and decrypt.

I have an example on PHP:

Credentials of user that can decrypt:
`$this->Master_client = new Credentials($this->public_key, $this->public_secret_key);
`
Client KMS
`$this->Client_Kms = new KmsClient(['version'=>'latest','region'=>'us-east-1','credentials'=>$this->Master_client]);`

Decrypt process:
     ```
   try{
            $this->Result_Client_Key = $this->Client_Kms->decrypt([
                'CiphertextBlob' => base64_decode($this->Key)
            ]);
            $this->Key_ =  $this->Result_Client_Key["Plaintext"];
        }catch(\Exception $error){
            return ["status"=> false, "message"=>$error->getMessage()];
        }
```

**Comment by delasign** [comment]
https://gist.github.com/delasign/37a0f763c0dad66d4ddc9e681ee5460c

Incase anyone needs a Swift 4.2 version ^
