### ISSUE TITLE
AWSBasicSessionCredentialsProvider

### ISSUE THREAD

**Issue by stanleyst** [aws/aws-sdk-ios#687]
Hello,

I have been using the function AWSBasicSessionCredentialsProvider to handle some credential transfers. Recently, after using Carthage to update to the latest version, 2.5.8, of the aws-sdk-ios, I lost all functionality and even definition of this function. 

Has anybody else noted any similar issues? I cannot even build the project because as far as it is concerned, the function doesn't exist.

I appreciate your help!

**Comment by rohandubal** [comment]
Hello,

Could you elaborate more on steps to reproduce this issue? 

Did your app work correctly with 2.5.7? Have you included the frameworks as embedded binaries?

Thanks,
Rohan

**Comment by stanleyst** [comment]
Hello,

Sure thing! 

To produce this issue, I took code that was running for the project that I was working on and ran a carthage update and a carthage bootstrap to get the latest versions of everything (I use Mapbox, SwiftyBeaver, and AWS in this particular project). When I did so, I lost my definition and thus my functionality of the AWSBasicSessionCredentialsProvider function from the aws-sdk-ios version I was using (attempting to newly target 2.5.8). Previously, I had been running on 2.5.3 I believe.

I just attempted to target version 2.5.7 to test it by entering the following into my Cartfile

**github "aws/aws-sdk-ios" == 2.5.7**

This failed, yielding this error 
**A shell task (/usr/bin/env git checkout --quiet --force 2.5.7) failed with exit code 1:**
**error: pathspec '2.5.7' did not match any file(s) known to git.**

Yes, I have embedded the frameworks.

Thanks!

**Comment by rohandubal** [comment]
Hi, I tried using `github "aws/aws-sdk-ios" == 2.5.7` and I was able to get the artifacts from 2.5.7. I believe this could be a local workspace issue. We are unable to reproduce this on our side.

Thanks,
Rohan

**Comment by stanleyst** [comment]
After further testing by removing every other dependency in my cartfile, I was also able to do so with the only line in my cartfile being `github "aws/aws-sdk-ios" == 2.5.7`. Upon this success, I also added a SwiftyBeaver line: `github "SwiftyBeaver/SwiftyBeaver`.

I then attempted to add additional dependency lines and ran into Shell Task Exit Code 128 for the aws-sdk-ios. 

Do you have any insight as to why this error might pop up whenever I start to add additional dependencies to my cartfile?

**Comment by kvasukib** [comment]
Can you print out the contents of the file "Cartfile.resolved", which is located in the same directory as Cartfile?

**Comment by kvasukib** [comment]
Look for the answer in https://stackoverflow.com/questions/44328724/aws-ios-sdk-crashing-with-carthage-update-for-version-2-5-8.

If any of the dependencies in Cartfile has a dependency on a different version of "aws-sdk-ios", namespace collision occurs and hence the carthage update error.
