### ISSUE TITLE
AWSLex & response cards

### ISSUE THREAD

**Issue by baqtiste** [aws/aws-sdk-ios#688]
Hello,

I'm using the iOS framework v2.5.8 to build a chatbot app and I've noticed today that i don't have the response cards in the response from Lex.
I'm using ```InteractionKit``` to communicate with Lex (i'm just following the sample app code downloaded via MobileHub)

```
- (void)interactionKit:(AWSLexInteractionKit *)interactionKit
       switchModeInput:(AWSLexSwitchModeInput *)switchModeInput
      completionSource:(AWSTaskCompletionSource<AWSLexSwitchModeResponse *> * _Nullable)completionSource;
```

Did i miss something ?

Thanks

**Comment by minbi** [comment]
Did you set the delegate?

```
// fetch and set the interaction kit client
self.interactionKit = [AWSLexInteractionKit interactionKitForKey:@"botName"];
// set the interaction kit delegate
self.interactionKit.interactionDelegate = self;
```

**Comment by baqtiste** [comment]
Yes :) I'm able to get the response from Lex but the response cards (or suggestions that you can define for a specific prompt in the Lex interface) is not in the response

Here is what I'd like to get from Lex:

<img width="1452" alt="screen shot 2017-06-08 at 11 46 45 am" src="https://user-images.githubusercontent.com/4132014/26908796-5131eb26-4c40-11e7-98b0-bc27882fd68f.png">

**Comment by Yallappa** [comment]
@baqtiste did you get any solution for this? I am also stuck in the same place. Any updates would be helpful.

Thank you.

**Comment by baqtiste** [comment]
@Yallappa It looks like `InteractionKit` is using the [PostContent API](http://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostContent.html) which allows us to use voice to interact with Lex but response cards are not included in the response.
However the [PostText API](http://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostText.html) returns the response cards but we can't use audio interaction :)

**Comment by SreekanthGudisi** [comment]
@baqtiste hello,
> 
> ```swift
> let serviceConfig = AWSServiceConfiguration(region: Region, credentialsProvider: AWSIdentityManager.default().credentialsProvider)
>   
> guard let request = AWSLexPostTextRequest() else { return }
> request.botName = ChatbotBotName
> request.botAlias = ChatbotBotAlias
> request.userId = UUID().uuidString
> request.sessionAttributes = sessionAttributes as? [String : String]
> request.inputText = "i need help"
>   
> let key = "testPostText"
> AWSLex.register(with: serviceConfig!, forKey: key)
> AWSLex(forKey: key).postText(request) { (response, error) in
>     print(response?.message)
> }
> ```
And What is here **key** means ?

But this is not pure json right .. I'm getting like this

```
Optional(<AWSLexPostTextResponse: 0x600000a72fc0> {
    dialogState = 8;
    intentName = Hi;
    message = "Hello";
    responseCard = "<AWSLexResponseCard: 0x6000006249a0> {\n    contentType = 1;\n    genericAttachments =     (\n        \"<AWSLexGenericAttachment: 0x600000457cd0> {\\n    buttons =     (\\n        \\\"<AWSLexButton: 0x600000636c60> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000635060> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x6000006340a0> {\\\\n    text = \\\\\\\"text\\\\\\\";\\\\n    value = \\\\\\\"value\\\\\\\";\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000636ba0> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000633e40> {\\\\n    text = \\\\\\\"text\\\\\\\";\\\\n    value = \\\\\\\"value\\\\\\\";\\\\n}\\\"\\n    );\\n    subTitle = \\\"subTitle1\\\";\\n    title = \\\"title1\\\";\\n}\",\n        \"<AWSLexGenericAttachment: 0x6000006454f0> {\\n    buttons =     (\\n        \\\"<AWSLexButton: 0x600000634b00> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000634ac0> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000634760> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\",\\n        \\\"<AWSLexButton: 0x600000634660> {\\\\n    text = text;\\\\n    value = value;\\\\n}\\\"\\n    );\\n    subTitle = \\\"subTitle1\\\";\\n    title = \\\"title2\\\";\\n}\"\n    );\n    version = 1;\n}";
    sessionAttributes =     {
    };
    slots =     {
    };
})
```
