### ISSUE TITLE
Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2

### ISSUE THREAD

**Issue by Jeff-KaayLabs** [aws/aws-sdk-ios#689]
I'm using sdk 2.5.7
using AWSCognitoCredentialsProvider to upload get credentials

everything is fine. But on uploading using TransferUtility method I'm getting 403 with this error

Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 \"(null)\" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Tue, 06 Jun 2017 11:23:01 GMT, x-amz-request-id=2359B618449D40AF, x-amz-id-2=KJaz6OxXo70laEusAXzucIaYkcfkxF6+DhJlzHPhFVUPhz8RYVvc+eY1dVNpZaV6tVwnLJ/v6XA=}

**Comment by mlshon** [comment]
Do you have a code snippet you can post?

**Comment by Jeff-KaayLabs** [comment]
// In Appdelegate 
 let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1,identityPoolId: " my pool id")     

 let configuration = AWSServiceConfiguration(region:.USEast1, credentialsProvider:credentialsProvider)
        
        AWSServiceManager.default().defaultServiceConfiguration = configuration

// upto this its authenticating and getting identity id from credential provider


let key = folder + Date().timeIntervalSince1970.description.trimmingCharacters(in: CharacterSet.whitespaces)
        
         let utility = AWSS3TransferUtility.default()
        
         utility.uploadData(data, bucket: bucketName, key: key, contentType: contentType, expression: nil, completionHandler: { result in
            
            print("Status Code : ",result.0.response?.statusCode ?? "") // getting 403
            
            guard result.1 == nil else {
                print("\n\nError in uploading .. "+result.1.debugDescription)
                completion("")
                return
            }
            
            completion(self.url+key)
            
        })

**Comment by mlshon** [comment]
What is the contentType?

**Comment by Jeff-KaayLabs** [comment]
image/png






*Regards,*

*Jayan P*
*iOS  Junior Developer,*
*Kaay Labs*

**Comment by rohandubal** [comment]
Have you correctly set IAM policy for your authenticated role since you are calling this after getting authenticated? Does the upload succeed for any case at all or always fails?

**Comment by philipengberg** [comment]
It happens randomly for me. It's like if it's decided to fail it'll keep failing and vice versa.
