### ISSUE TITLE
Amazon lex

### ISSUE THREAD

**Issue by muneerkk66** [aws/aws-sdk-ios#691]
Hi Team,

  I have tried to integrate the amazon lex chat bot on my app. My plan is send the request to lex and get the result, But in given sample we are using SDK and Congitopool , etc. I dont want to integrate this  framework also my user is not communicating with these modules. 

  Is there is any API we can call amazon lex without using cognito.

**Comment by minbi** [comment]
If you don't require users to authenticate, then you can use unauthenticated access. This is built into the iOS SDK Core, so it would not be a large integration.

You would need to setup a identity pool with permissions to access Lex. This is different from Cognito user pools.

Sample project with specific line to relevant code:
https://github.com/awslabs/aws-sdk-ios-samples/blob/master/Lex-Sample/swift-3/LexSwift/AppDelegate.swift#L29

**Comment by Sreekanth1234** [comment]
@minbi anyone have for **Cognito user pools**  with Lex Integration? .. If u have code please send me or Link..
Thanks in advance.
