### ISSUE TITLE
Bitcode Compilation Error for real iOS Device

### ISSUE THREAD

**Issue by vikram17000** [aws/aws-sdk-ios#692]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWS iOS SDK 2.5.8

* In what version of SDK are you facing the problem?

2.5.8

* Is the issue limited to Simulators / Actual Devices?

Actual devices.

* Can your problem be resolved if you bump to a higher version of SDK?

Already using the latest version.

* Is this problem related to specific iOS version?

Generic.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

CocoaPods.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hi - I'm integrating the AWS iOS SDK (latest version 2.5.8) in my project using the instructions given for CocoaPods. I'm able to build / run the project successfully on a simulator, but get linker error on a real device. This linker error is related to enabling bitcode. If I disable bitcode for my target and then run the it on a real device, it works fine. Can you advise please if there is something wrong here in my understanding of the frameworks' support for bitcode?

Thanks.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by minbi** [comment]
Which pods are you experiencing this problem with?

**Comment by vikram17000** [comment]
All pods when I integrate the SDK with my app. So essentially, after having integrated the iOS SDK, the app fails to compile on a real device unless bitcode is switched off.

**Comment by kredden** [comment]
Is this still a problem for you?  All the apps I've tried with bitcode on are working fine.

Thanks,
Kevin

**Comment by kredden** [comment]
Closing issue as it seems to be working fine, if you are still having the problem then please reopen this issue.

Thanks,
Kevin

**Comment by vikram17000** [comment]
Thanks! All good now!
