### ISSUE TITLE
SDK annotation makes warnings

### ISSUE THREAD

**Issue by beautynanacalico** [aws/aws-sdk-ios#694]
in AWSCore/Fabric.h
<img width="898" alt="s1" src="https://user-images.githubusercontent.com/23450264/27329504-c6a5533e-55f0-11e7-90f0-d726f6783e84.png">

in AWSCore/AWSCognitoIdentity+Fabric.m
<img width="889" alt="s2" src="https://user-images.githubusercontent.com/23450264/27329533-df897182-55f0-11e7-85a5-62f4a96a128f.png">

in AWSCore/AWSCognitoIdentity+Fabric.h
<img width="895" alt="s4" src="https://user-images.githubusercontent.com/23450264/27329579-149dd494-55f1-11e7-99af-9270cb668386.png">

in AWSCore/Fabric+FABKits.h
<img width="898" alt="s1" src="https://user-images.githubusercontent.com/23450264/27329551-f845f1be-55f0-11e7-81b2-e0b4c8ea2a01.png">

I am aware that AWS, Amazon is a very big company. Nevertheless, it is not quite clear why it causes these warnings.
Please, I want you to take care of this part.

**Comment by kvasukib** [comment]
Hi @beautynanacalico ,

Thanks for reporting to us. What is the iOS SDK version you are using?

**Comment by beautynanacalico** [comment]
@kvasukib 
Thanks, I always use recently version. and I'm using Swift3

XCode: 8.3.3
AWS SDK: 2.5.7

**Comment by kvasukib** [comment]
HI @beautynanacalico,

We have fixed the typo in the documentation. 

Can you check this: 
https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Fabric/Fabric.h#L43
https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Fabric/Fabric%2BFABKits.h#L31

Can you tell us how are you getting the iOS SDK? Cocoapods / Carthage / Embedded frameworks?

**Comment by beautynanacalico** [comment]
Cocoapods, Thank you

**Comment by beautynanacalico** [comment]
I have seen that this issue has been fixed in version 2.5.8. Thank you for your quick response.
