### ISSUE TITLE
Swift 3 AWSS3TransferManager Global Task

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [aws/aws-sdk-ios#697]
Hi,  we are working with the AWSS3TransferManager in Swift, actually all works great, whe we use the  DispatchQueue.global(qos: .background).async when the device is locked the AWS Transfer stop until we return to the app.
`                            transferManager.upload(uploadRequest!).continueWith { (task) -> AnyObject! in
}
`
Any idea that how when we are not in the app the upload still continue?

Regards

**Comment by kvasukib** [comment]
Hi @ulisescarreonalvarez,

Thanks for reporting to us.

For uploads to be progressing in the background, use AWSS3TransferUtility. http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html

Doc reference: http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html

Sample App: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample

**Comment by ulisescarreonalvarez** [comment]
@kvasukib You are right, we needed the AWSS3TransferUtility for the back/foreground, that resolve our problem, thanks a lot!
