### ISSUE TITLE
Crash with AWSCognitoCredentialsProvider if initWithRegionType:identityPoolId:identityProviderManager: is used

### ISSUE THREAD

**Issue by RoninSTi** [aws/aws-sdk-ios#700]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

Cognito, specifically `AWSCognitoCredentialsProvider`

* In what version of SDK are you facing the problem?
2.5.8

* Is the issue limited to Simulators / Actual Devices? 
Both

* Can your problem be resolved if you bump to a higher version of SDK?
Using highest

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If the following code is used to initialize an instance of AWSCognitoCredentialsProvider, the following crash occurs:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AWSCognitoCredentialsProvider initWithRegionType:identityPoolId:identityProviderManager:]: unrecognized selector sent to instance 0x1702e4e80'`

```swift
self.credentialsProvider = AWSCognitoCredentialsProvider(regionType: region, identityPoolId: poolId, identityProviderManager: FacebookProvider())
```
`FacebookProvider` adheres to the protocol

If use the following code, no crash

```swift
self.credentialsProvider = AWSCognitoCredentialsProvider(regionType: region, identityPoolId: poolId)
``` 

This also produces the same crash:

```swift
self.credentialsProvider = AWSCognitoCredentialsProvider(regionType: region, identityPoolId: poolId, identityProviderManager: nil)
```

**Comment by rohandubal** [comment]
Hello,

Thanks for reporting this. We will have a look at it.

Thanks,
Rohan

**Comment by Kamaldeep-Singh** [comment]
Hello, 

Is there a resolution on this one ?

Thanks

**Comment by muellerfr** [comment]
Hello @RoninSTi  and @Kamaldeep-Singh,

Sorry for the delayed response. Does the issue still reproduce in the latest version of the SDK?
