### ISSUE TITLE
Allow an Unconfirmed User to Update Their Attributes (i.e. to change Phone Number in case an incorrect Phone Number was inputted)

### ISSUE THREAD

**Issue by aksharbonu** [aws/aws-sdk-ios#701]
I'm unable to allow an unconfirmed user to update their phone number in case they typed it in correctly during sign up.

I'm unable to authenticate an unconfirmed user and consequently cannot call updateAttributes.

Is there any workaround for this?

Many thanks!

**Comment by mosn** [comment]
Bump!

**Comment by nuwan-swivel** [comment]
I'm facing the same issue. Any update on this?
