### ISSUE TITLE
While uploading this to testflight, getting "Com.amazonaws.sdk.ios.awsresources"  missing code signing entitlements in iOS.

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [aws/aws-sdk-ios#704]
I am using ur Framework, its working fine, but while uploading to test flight getting following errors.

ERROR ITMS-90166: “Missing code signing entitlements. No entitlements found in bundle ‘com.amazongaws.sdk.ios.AWSResources’ for executable ‘path’

ERROR ITMS-90171: “Invalid Bundle Structure - The binary file “AWSLex.framework/AWSResources.bundle/AWSResources’ is not permitted.

Can anyone guide me how to fix and upload to test flight.

**Comment by rohandubal** [comment]
Hello @AnilkumarRabhasa ,

Thanks for reporting this issue. We will work on a fix for this and update the thread once we have an update.

Thanks,
Rohan

**Comment by kvasukib** [comment]
This is fixed in 2.5.9

**Comment by AnilkumarRabhasa** [comment]
Thanks so much for fixing issue!!
