### ISSUE TITLE
Error while compiling using iOS 11 beta 3

### ISSUE THREAD

**Issue by animeshp** [aws/aws-sdk-ios#706]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSCore

* In what version of SDK are you facing the problem?
2.5.8
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
iOS 11 beta 3 / Xcode 9.0 beta 3 (9M174d)
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

In the file `AWSDDOSLogger.m` inside `AWSCore` SDK, following errors are shown when trying to compile:

<img width="1134" alt="screen shot 2017-07-11 at 12 33 24 pm" src="https://user-images.githubusercontent.com/4133494/28086862-4f56871c-6635-11e7-8591-10d8f3f556ff.png">

#705 tries to fix this.

**Comment by lexrus** [comment]
seealso https://github.com/CocoaLumberjack/CocoaLumberjack/issues/883

**Comment by rohandubal** [comment]
Fixed in 2.6.0
