### ISSUE TITLE
Can't access response headers with AWSAPIGateway SDK

### ISSUE THREAD

**Issue by fsproru** [aws/aws-sdk-ios#707]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSAPIGateway

* In what version of SDK are you facing the problem?
aws-sdk-ios version 2.5.7
aws-api-gateway version 2.5.8 according to its podspec

* Is the issue limited to Simulators / Actual Devices?
No, it appears on any simulator or device.

* Can your problem be resolved if you bump to a higher version of SDK?
Nope.

* Is this problem related to specific iOS version?
Nope

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

  * Export an SDK from AWSAPIGateway web interface.
  * Put it in the app. 
  * Send any request.
  * There is a way to access the response body as a model. However, there is no way to access *response headers*.

I couldn't find a way to access response headers neither from the documentation nor from reading the code itself. 

**How can I access the response headers?**

Thank you.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by minbi** [comment]
What is your use-case for accessing the headers?

**Comment by fsproru** [comment]
@minbi, headers are usually used for authentication which is a common industry practice. Is there an existing way to access headers with AWS API Gateway SDK?

**Comment by fsproru** [comment]
Hi @minbi, just wanted to follow up. Is there a way to access headers or it's currently in the works?

**Comment by rohandubal** [comment]
Hi @fsproru 

There is a field `rawResponse` which can be used to get the underlying response as-is. It is available in SDK version `2.6.0` and above.

Thanks,
Rohan

**Comment by fsproru** [comment]
Thanks @rohandubal
