### ISSUE TITLE
Voice recognition in LEX seems to be bit challenging

### ISSUE THREAD

**Issue by sujithdas** [aws/aws-sdk-ios#713]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
LEX.  it is not recognizing the intent in one go and sometime need to repeat many times
* In what version of SDK are you facing the problem?
iOS 10.3.3, Xcode 8.3.2
* Is the issue limited to Simulators / Actual Devices?
Both simulator and actual Devices
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
Tested in iOS 10.3 and 10.3.3
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Just try to chat with the bot in voice mode

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
This seems more of a service related issue. Could you please file a AWS Forum post in Lex forums so that we can help you better? Thanks!
