### ISSUE TITLE
Call back for published messages in aws iot?

### ISSUE THREAD

**Issue by SanyasiraoM** [aws/aws-sdk-ios#717]
I came to know that paho mqtt will give callback when message published to the server, Weather success or failure. But I'm not getting such call back when publishing messages using aws iot ios sdk

Example:
https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/PublishViewController.swift#L37

**Comment by kvasukib** [comment]
Hi @SanyasiraoM,

Thanks for reporting to us and sorry for the inconvenience caused. Currently, the publish APIs don't have a callback. 

What is the reason for using the callback for "publish" API? 

Thanks

**Comment by SanyasiraoM** [comment]
Hi @kvasukib,

Thanks for reply

Consider I'm using aws iot for one on one chat purpose. I need to change message status from waiting to sent when it reaches the server. For that, I need confirmation from the server.

Currently, I'm able to get in Android sdk. But could not find the same thing in ios SDK

**Comment by kvasukib** [comment]
Hi @SanyasiraoM,

Thanks for the quick response. We are taking it as a feature request.

Thanks

**Comment by SanyasiraoM** [comment]
Thank you @kvasukib :)

**Comment by pavithramh** [comment]
Hi,

is there any solution available for the above question "Call back for published messages in aws iot or delegate function for received messages??" just like in swiftMQTT library "https://github.com/aciidb0mb3r/SwiftMQTT"..

Please help.
Thank you.

**Comment by SanyasiraoM** [comment]
@kvasukib If the some issue is labeled as featured request and stale bot closes. What will you guys do?
