### ISSUE TITLE
iOS Share Extension, set sharedContainerIdentifier from Info.plist

### ISSUE THREAD

**Issue by VigneshPT** [aws/aws-sdk-ios#718]
@karthiksaligrama @minbi I'm using the TransferUtility in the Share Extension of my app, and the upload doesn't work unless I hard code the sharedContainerIdentifier property in the AWSS3TransferUtility file in the Pod project, which is obviously not a good idea. Can we set the `sharedContainerIdentifier` through the `Info.plist`, if so, what is the key name?

I see that a similar issue(https://github.com/aws/aws-sdk-ios/issues/283) was closed earlier stating that support for the `sharedContainerIdentifier` was added through the `ServiceConfiguration` but it wasn't clear on what the key name is, for setting it via `Info.plist`

**Comment by kvasukib** [comment]
Hi @VigneshPT,

Thanks for reporting to us.

You can see how the SharedContainerIdentitifer is passed in S3TransferUtility.

https://github.com/aws/aws-sdk-ios/blob/24324b8be26a3c29f413e0b043e007f4dc1a0951/AWSS3/AWSS3TransferUtility.m#L204,L232

Can you set it in AWSServiceConfiguration?

**Comment by rohandubal** [comment]
It is not possible currently to do it via `info.plist`, but you can do it via code using `AWSServiceConfiguration` object. I will take the info.plist part as a feature request to the team.

Thanks,
Rohan
