### ISSUE TITLE
AWSDDLogMessage not compiling with Xcode 9 beta 4+

### ISSUE THREAD

**Issue by petebarber** [aws/aws-sdk-ios#721]
I updated to the latest version of AWSCore, AWSCognito & AWSLambda via cocoapods. I've hit a compilation error when building AWSCore.

It's in the function (void)logMessage:(AWSDDLogMessage *)logMessage in AWSDDLogger.m:

Looking at the code, I think there may be another issue in that the msg that is logged is an em

Info below:

Showing All Errors Only

Build target AWSCore of project Pods with configuration Debug

CompileC /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/arm64/AWSDDOSLogger.o AWSCore/AWSCore/Logging/AWSDDOSLogger.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/Pete/Projects/todo/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/Pete/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/Pete/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=AWSCore -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fembed-bitcode-marker -index-store-path /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Index/DataStore -iquote /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/AWSCore-generated-files.hmap -I/Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/AWSCore-own-target-headers.hmap -I/Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/AWSCore-all-non-framework-target-headers.hmap -ivfsoverlay /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/all-product-headers.yaml -iquote /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/AWSCore-project-headers.hmap -I/Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Products/Debug-iphoneos/AWSCore/include -I/Users/Pete/Projects/todo/Pods/Headers/Private -I/Users/Pete/Projects/todo/Pods/Headers/Public -I/Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/DerivedSources/arm64 -I/Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/DerivedSources -F/Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Products/Debug-iphoneos/AWSCore -include /Users/Pete/Projects/todo/Pods/Target\ Support\ Files/AWSCore/AWSCore-prefix.pch -MMD -MT dependencies -MF /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/arm64/AWSDDOSLogger.d --serialize-diagnostics /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/arm64/AWSDDOSLogger.dia -c /Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m -o /Users/Pete/Library/Developer/Xcode/DerivedData/todofu-dfvtbwxtwskhjddtmrrhautvyxpi/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/arm64/AWSDDOSLogger.o

/Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m:58:17: error: static_assert failed "format argument must be a string constant"
                os_log_error(OS_LOG_DEFAULT, msg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'os' imported from /Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m:17:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/os/log.h:319:9: note: expanded from macro 'os_log_error'
        os_log_with_type(log, OS_LOG_TYPE_ERROR, format, ##__VA_ARGS__)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/os/log.h:475:5: note: expanded from macro 'os_log_with_type'
    _Static_assert(__builtin_constant_p(format), "format argument must be a string constant"); \
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m:62:17: error: static_assert failed "format argument must be a string constant"
                os_log_info(OS_LOG_DEFAULT, msg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'os' imported from /Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m:17:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/os/log.h:247:9: note: expanded from macro 'os_log_info'
        os_log_with_type(log, OS_LOG_TYPE_INFO, format, ##__VA_ARGS__)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/os/log.h:475:5: note: expanded from macro 'os_log_with_type'
    _Static_assert(__builtin_constant_p(format), "format argument must be a string constant"); \
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m:67:17: error: static_assert failed "format argument must be a string constant"
                os_log_debug(OS_LOG_DEFAULT, msg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'os' imported from /Users/Pete/Projects/todo/Pods/AWSCore/AWSCore/Logging/AWSDDOSLogger.m:17:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/os/log.h:277:9: note: expanded from macro 'os_log_debug'
        os_log_with_type(log, OS_LOG_TYPE_DEBUG, format, ##__VA_ARGS__)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/os/log.h:475:5: note: expanded from macro 'os_log_with_type'
    _Static_assert(__builtin_constant_p(format), "format argument must be a string constant"); \
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

**Comment by animeshp** [comment]
Please check #705 and #706. Hopefully this help until newer version of AWS SDK compiling with stable version of iOS 11 comes out.

**Comment by superandrew** [comment]
+1

**Comment by DmitriyBagrov92** [comment]
+1

**Comment by rohandubal** [comment]
Fixed in 2.6.0.

**Comment by HiteshBoricha-BTC** [comment]
+1

**Comment by kredden** [comment]
Versions of the SDK prior to 2.6.0 will have this problem, you will need to upgrade to the latest version to fix it.
