### ISSUE TITLE
Cognito MFA - Swift setUserSettings not enabling MFA for user

### ISSUE THREAD

**Issue by MeeperBots** [aws/aws-sdk-ios#722]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito (AWSCognitoIdentityProvider)

* In what version of SDK are you facing the problem?
2.5.9

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
I don't believe so
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

We have setup an AWS user pool and can create user accounts and login to those accounts through our iOS (Swift) app.  

Our user pool is set to MFA Optional.  Our app offers users the option of enabling MFA.  We are doing so like this:

self.user = self.pool?.currentUser()
        
        let mfaOptions = AWSCognitoIdentityUserMFAOption()
        
        mfaOptions.attributeName = "phone_number"
        mfaOptions.deliveryMedium = AWSCognitoIdentityProviderDeliveryMediumType.sms
        
        let settings = AWSCognitoIdentityUserSettings()
        settings.mfaOptions?.append(mfaOptions)
           
        self.user!.setUserSettings(settings).continueWith( executor: AWSExecutor.mainThread(), block: { (task: AWSTask!) -> Void in
        
            print(task.debugDescription)
            
            if let error = task.error as NSError? {
                print("error")
            } else {
                print("updated 2 factor")          
            }
            
            
        })

This function executes without error, however the user account is not updating the MFA Enabled status.

Please help :)
Thanks

**Comment by behrooziAWS** [comment]
Hi MeeperBots,

I think it's just the standard swift behavior with nil.  settings.mfaOptions is nil so appending to it is a noop.  Try setting it to an array instead of appending to a nil array:

settings.mfaOptions = [mfaOptions]

**Comment by MeeperBots** [comment]
That did it!  Thanks so much, would have never seen that.  Really appreciate it.

-J

**Comment by girijeshkumar2007** [comment]
I tried this code but it not getting 2MFA is not getting enaled 

        let mfaOptions = AWSCognitoIdentityUserMFAOption()
        mfaOptions.attributeName = "phone_number"
        mfaOptions.deliveryMedium = AWSCognitoIdentityProviderDeliveryMediumType.sms
        let settings = AWSCognitoIdentityUserSettings()
        settings.mfaOptions = [mfaOptions]
        let user = AWSCognitoIdentityUserPool.default().getUser()
        AWSCognitoIdentityUserPool.default().delegate = self
        user.setUserSettings(settings)

**Comment by girijeshkumar2007** [comment]
I did fix it by doing 
func twoMfaEnable() {
        let mfaOptions = AWSCognitoIdentityUserMFAOption()
        mfaOptions.attributeName = "phone_number"
        mfaOptions.deliveryMedium = AWSCognitoIdentityProviderDeliveryMediumType.sms
        
        let settings = AWSCognitoIdentityUserSettings()
        settings.mfaOptions = [mfaOptions]
        let preferences = AWSCognitoIdentityUserMfaPreferences()
//        let smsMFA = AWSCognitoIdentityUserMfaType(enabled: false, preferred: false)
        let smsMFA = AWSCognitoIdentityUserMfaType(enabled: true, preferred: true)

        preferences.smsMfa = smsMFA
        let userInfo = AWSCognitoIdentityUserPool.default().currentUser()
        userInfo?.setUserSettings(settings)
        userInfo?.setUserMfaPreference(preferences)
        userInfo?.getDetails().continueWith(block: { response in
            
//            print("response \(response.result?.userMFASettingList)")

            print("response \(response.result?.preferredMfaSetting)")
        })
    }
