### ISSUE TITLE
Unable to get session after User signup with confirmation code

### ISSUE THREAD

**Issue by Henawey** [aws/aws-sdk-ios#723]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSCognitoIdentityProvider
* In what version of SDK are you facing the problem?
2.5.9
* Is the issue limited to Simulators / Actual Devices?
Simulator
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
1- signup
2- confirm user email with code 
3- (user or  userPool.currentUser).getSession.continueWith will never called back

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by behrooziAWS** [comment]
Can you try configuring this sample with your pool and client and see if you can sign up and sign in?  https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample

If that works, please provide details on how you are calling getSession and whether you are configuring a AWSCognitoIdentityInteractiveAuthenticationDelegate

**Comment by Henawey** [comment]
I'll try it tomorrow and give you a feedback

**Comment by giovazjim** [comment]
Hello I'm dealing with the same issue. Currently I'm using the 2.4.16 SDK version, I tried with the latest version (2.5.2) but the problem remain.
This is happening with actual devices and I consuming the SDK throughout Carthage.
The steps to reproduce the error are the same as @Henawey

**Comment by rohandubal** [comment]
Hello @giovazjim 

Are you calling sign in after the sign up? I think the user is required to sign in again after the sign up.

Thanks,
Rohan

**Comment by giovazjim** [comment]
Hello @rohandubal 

Yes, first I'm calling sing up and getting the verification code. Then the code is verified and after that I'm call sign up but (userPool.currentUser).getSession.continueWith will never called back.

Thanks
Giovanni
