### ISSUE TITLE
[AWSPinpointEventRecorder submitEvents:error:eventIDs:stop:] Selector name found in current argument registers: release

### ISSUE THREAD

**Issue by nnbanuba** [aws/aws-sdk-ios#726]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Pinpoint

* In what version of SDK are you facing the problem?
2.5.9

* Is the issue limited to Simulators / Actual Devices?
We do not use simulator, I can't reproduce locally on device, but the crash is reported by HockeyApp very often.

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Crash log is attached:
[crash_log.txt](https://github.com/aws/aws-sdk-ios/files/1230803/crash_log.txt)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by bruun** [comment]
Seeing the same issue in version 2.6.1 of the SDK.

**Comment by balaji2591** [comment]
Hello @nnbanuba and @bruun 
I'm closing this issue because we have a duplicate issue raised for the latest version (v2.6.1). It includes information about other warnings as well.
You can track that issue in
https://github.com/aws/aws-sdk-ios/issues/737
