### ISSUE TITLE
AWSDynamoDBObjectMapper.default().save fails on 10% of users with AWSCognitoIdentityErrorDomain error 0

### ISSUE THREAD

**Issue by mwhitt** [aws/aws-sdk-ios#727]
* What service are you using?
DynamoDB

* In what version of SDK are you facing the problem?
Tried 2.5.9 & 2.5.10

* Is the issue limited to Simulators / Actual Devices?
Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

    This is only happening to 10% of the users in production. Everyone else works with no problems. 

    I am using an app level, unauthorized cognito identity with permissions to read & write to both DynamoDB & S3. The dynamo table and indexes are in the resource of the policy. 

    Everyone can read with no problems

    The same with S3, read & write no problems, works with everyone

    Only some users, when calling save on AWSDynamoDBObjectMapper, have it always fail with  the error `AWSCognitoIdentityErrorDomain error 0`

* iOS setup
    Cognito, S3 and Dynamo are configured in the Info.plist 

    TLS levels are set to the same values as in the Dynamo sample app

**Comment by mwhitt** [comment]
If it helps any here is the line I am calling:
`dynamoDBObjectMapper.save(dynamoMessage).continueWith(executor: AWSExecutor.mainThread(), block: { (task: AWSTask!) -> AnyObject! in })`

And stack trace has it failing in the framework here:
`AWSTask.m line 331`

**Comment by rohandubal** [comment]
Hi,

Can you please provide with the stack trace? It seems to me that the error is not getting correctly mapped and thats why you are seeing this generic error. 

Thanks,
Rohan

**Comment by mwhitt** [comment]
Hi,

Thanks for response, I was able to resolve this, the error was a dynamoDB column was empty string for some users when saving and was causing this generic error. Thanks, will be closing this.
