### ISSUE TITLE
AWS Mobile Hub Localization

### ISSUE THREAD

**Issue by yusufonderd** [aws/aws-sdk-ios#731]
I'm using AWS Mobile Hub service for user sign-in. I follow mobile hub developer guide. How to apply localization in AWSAuthUIViewController. For example I want to use "Yeni hesap oluştur"  instead of "Create new account" for Turkish localization. I have a localizable string for turkish and english languages in XCode 8.3.3.

**Comment by rohandubal** [comment]
Hello @yusufonderd ,

Currently localization is not supported, but I will take this as a feature request to the team. 

As a temporary workaround, you could modify the AWSUserPools.storyboard in the AWSUserPoolsSignIn package and SignIn.storyboard in AWSAuthUI package.

Thanks,
Rohan
