### ISSUE TITLE
get userSub on signup Cognito iOS SDK

### ISSUE THREAD

**Issue by milesHopkins** [aws/aws-sdk-ios#732]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito userpool signup iOS
* In what version of SDK are you facing the problem?
2.6.1
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hi, I am trying to retrieve the usersub property from the userpool when a user is signing up with an unauthenticated userpool. I can see it in the response header, but there is not a way to retrieve it from the sdk. 
![screen shot 2017-09-19 at 17 37 19](https://user-images.githubusercontent.com/32105414/30604027-5a36d476-9d61-11e7-9249-f9fb6418942d.png)
Header Returned
`{
  "CodeDeliveryDetails": {
    "AttributeName": "email",
    "DeliveryMedium": "EMAIL",
    "Destination": "e@e.ee"
  },
  "UserConfirmed": false,
  "UserSub": "c35a57af-845a-4408-86fd-c56c1485dcf9"
}`

[I have found that it has been changed in the JS SDK.](https://github.com/aws/amazon-cognito-identity-js/issues/335)  Would this be able too be fixed here?

Thanks

**Comment by kvasukib** [comment]
Hi @milesHopkins,

Thank you for using our SDK and reporting to us.
We are taking it as an enhancement and we will fix it.

Thanks

**Comment by milesHopkins** [comment]
Hi @kvasukib,
Thanks for getting back to me. Have you got any idea of how long this will take to be accepted/implemented?

Thanks

**Comment by rohandubal** [comment]
Fixed with 2.6.2.
