### ISSUE TITLE
Pinpoint HTTP errors + crashes with 2.6.1

### ISSUE THREAD

**Issue by CooperCodeComposer** [aws/aws-sdk-ios#737]
Hi,

We've noticed a massive spike in HTTP errors (in New Relic) relating to Pinpoint. Seems to only be happening on our latest release of the app, which uses 2.6.1 of Pinpoint. The previous version of the app uses 2.5.6 and isn't experiencing the errors. 

Also there have been 2 new crashes:
AWSPinpointEventRecorder.m line 713 in [AWSPinpointEventRecorder submitEvents:error:eventIDs:stop:]_block_invoke]
SIGSEGV

and
AWSPinpointEventRecorder.m line 738 in [AWSPinpointEventRecorder submitEvents:error:eventIDs:stop:]_block_invoke_2.438]
--

Wondering; do you have any info on this + do you know if there's a fix?

Thanks!
-A

QnA
* What service are you using? = AWSPinpoint 

* In what version of SDK are you facing the problem? = 2.6.1

* Is the issue limited to Simulators / Actual Devices? = Devices

* Can your problem be resolved if you bump to a higher version of SDK? = Think we're on the latest

* Is this problem related to specific iOS version? = I see 2 crashes on New Relic, they're both on iOS9. Not sure about the http errors.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? = CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

**Comment by rohandubal** [comment]
Hello @CooperCodeComposer Thanks for reporting this issue. We will investigate and reply back.

--
Rohan

**Comment by CooperCodeComposer** [comment]
Thanks Rohan, 

A colleague of mine suggested that the pinpoint crash can be fixed by muting line 713 of PinpointEventRecorder "*stop = YES;" and adding "else if" on L715. Any thoughts on this or the HTTP errors?

Also noticing some warnings relating to AWS classes accessing UIApplication from a background thread:

Main Thread Checker: UI API called on a background thread: -[UIApplication isRegisteredForRemoteNotifications]
PID: 3784, TID: 701340, Thread name: (none), Queue name: com.amazonaws.AWSPinpointEventRecorder, QoS: 0

In particular L86 + L88 of AWSPinpointEndpointProfile.

**Comment by YousefED** [comment]
We're seeing similar issues in Firebase Crash Reporting with the following stack traces. Resulting in app crashes for our users:

```Exception name: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
1
AWSPinpoint
__61-[AWSPinpointEventRecorder submitEvents:error:eventIDs:stop:]_block_invoke (AWSPinpointEventRecorder.m:713)
2
AWSPinpoint
__61-[AWSPinpointEventRecorder submitEvents:error:eventIDs:stop:]_block_invoke (AWSPinpointEventRecorder.m:712)
3
AWSCore
__56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke (AWSTask.m:331)
4
AWSCore
__30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:65)
5
AWSCore
-[AWSExecutor execute:] (AWSExecutor.m:131)
6
AWSCore
-[AWSTask runContinuations] (AWSTask.m:307)
7
AWSCore
-[AWSTask trySetError:] (AWSTask.m:266)
8
AWSCore
-[AWSTaskCompletionSource setError:] (AWSTaskCompletionSource.m:52)
9
AWSCore
__61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke (AWSURLSessionManager.m)
10
AWSCore
__63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke (AWSTask.m:398)
11
AWSCore
__56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke (AWSTask.m:331)
12
AWSCore
__30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:65)
13
AWSCore
-[AWSExecutor execute:] (AWSExecutor.m:131)
14
AWSCore
-[AWSTask continueWithExecutor:block:cancellationToken:] (AWSTask.m:368)
15
AWSCore
-[AWSTask continueWithExecutor:successBlock:cancellationToken:] (AWSTask.m:394)
16
AWSCore
-[AWSTask continueWithSuccessBlock:] (AWSTask.m:404)
17
AWSCore
-[AWSURLSessionManager URLSession:task:didCompleteWithError:] (AWSURLSessionManager.m:216)```

Any progress on investigating this?

**Comment by balaji2591** [comment]
Hi YousefED, 
The latest 5 versions of the ios sdk doesn't have this stop variable .The method definitions have been changed. Can you use the latest version ?

**Comment by YousefED** [comment]
Yes seems better in latest version.

**Comment by balaji2591** [comment]
Thanks , closing this issue now . Can be reopened if the issue continues
