### ISSUE TITLE
Inconsistent request timestamp used in chunked S3 uploads

### ISSUE THREAD

**Issue by tbuscher** [aws/aws-sdk-ios#739]
We're using AWSS3TransferManager's ```upload:``` method to stream files from the iOS device to S3, with the ```uploadRequest.body``` property set to ```[NSURL fileURLWithPath:path]```.

Intermittently, these uploads stall for one minute, with the following typical log sequence:

```
Sep 25 12:20:36 iPad MyApp[1723] <Notice>: AWS4 String to Sign:[AWS4-HMAC-SHA256
20170925T192035Z
20170925/us-west-2/s3/aws4_request
0d36ca54d5f24115b0b19cd79669d8567a57f97f08e83e164c780119b287bba2]
Sep 25 12:20:36 iPad MyApp <Notice>: Request headers:
{
    Authorization = "AWS4-HMAC-SHA256 Credential=..., SignedHeaders=content-encoding;content-type;host;transfer-encoding;user-agent;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-security-token;x-amz-server-side-encryption, Signature=25cfe8245129fe0885245f693105c3c5c13985f170128796c60592718939bcb2";
    "Content-Encoding" = "aws-chunked";
    "Content-Type" = "video/MP2T";
    Host = "s3-us-west-2.amazonaws.com";
    "Transfer-Encoding" = Chunked;
    "User-Agent" = "aws-sdk-iOS/2.6.1 iOS/10.3.3 en_US transfer-manager";
    "X-Amz-Date" = 20170925T192035Z;
    "X-Amz-Security-Token" = ...
Sep 25 12:20:36 iPad MyApp[1723] <Notice>: AWS4 String to Sign: [AWS4-HMAC-SHA256-PAYLOAD
20170925T192036Z
20170925/us-west-2/s3/aws4_request
25cfe8245129fe0885245f693105c3c5c13985f170128796c60592718939bcb2
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
b8ad71777b211de1baca42e0e1a4466869e8a136a7195b509b08594ac6867ceb]
Sep 25 12:20:36 iPad MyApp[1723] <Notice>: AWS4 Chunked Header: [007fa5;chunk-signature=66ddc1b90a2b702806e61cd09d5130b2119cbcf42a5781264f8375880bd02063]

[... other chunks omitted ...]

Sep 25 12:20:38 iPad MyApp(libsystem_network.dylib)[1723] <Notice>: nw_endpoint_flow_prepare_output_frames [16.1 54.231.177.60:443 ready socket-flow (satisfied)] Failing the write requests due to the connection being closed
Sep 25 12:20:38 iPad MyApp(libsystem_network.dylib)[1723] <Error>: nw_endpoint_flow_prepare_output_frames [16.1 54.231.177.60:443 ready socket-flow (satisfied)] Failed to use 1 frames, marking as failed
Sep 25 12:20:38 iPad MyApp(CFNetwork)[1723] <Error>: TIC Write Error [16:0x170199f30]: 1:32
Sep 25 12:20:38 iPad MyApp(CFNetwork)[1723] <Notice>: TIC TCP Conn Cancel [16:0x170199f30]
Sep 25 12:20:38 iPad MyApp(libsystem_network.dylib)[1723] <Error>: nw_endpoint_handler_add_write_request [16.1 54.231.177.60:443 failed socket-flow (satisfied)] cannot accept write requests
Sep 25 12:20:38 iPad MyApp(libsystem_network.dylib)[1723] <Error>: tcp_connection_write_eof_block_invoke Write close callback received error: [22] Invalid argument

[... one minute later...]

Sep 25 12:21:38 iPad MyApp(CFNetwork)[1723] <Error>: NSURLSessionTask finished with error - code: -1001
Sep 25 12:21:38 iPad MyApp[1723] <Notice>: Session task failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x170454a00 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://s3-us-west-2.amazonaws.com/bucket/key, NSErrorFailingURLKey=https://s3-us-west-2.amazonaws.com/bucket/key, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
Sep 25 12:21:38 iPad MyApp[1723] <Notice>: Response headers:
{
    Connection = close;
    "Content-Type" = "application/xml";
    Date = "Mon, 25 Sep 2017 19:20:36 GMT";
    Server = AmazonS3;
    "Transfer-Encoding" = Identity;
    "x-amz-id-2" = ...;
    "x-amz-request-id" = ...;
}
```
The S3 service logs indicate that S3 is returning *403 SignatureDoesNotMatch* for each of these failed requests.

This appears to be due to an error in the iOS client code that occasionally causes the timestamp used in calculating the AWS4 chunk signature to differ from the timestamp present in the *X-Amz-Date* HTTP request header. In the example above, note that the date in the request header is 20170925T19203<b>5</b>Z but the first chunk's signature calculation uses 20170925T19203<b>6</b>Z.

As an experiment, I replaced [the line that sets the date used in the chunk signature calculation](https://github.com/aws/aws-sdk-ios/blob/91426a8faf782cbae1f1ee60f217adac5534047b/AWSCore/Authentication/AWSSignature.m#L189) with:
```
NSDate *date = [NSDate aws_dateFromString:[urlRequest valueForHTTPHeaderField:@"X-Amz-Date"] format:AWSDateISO8601DateFormat2];
```
so that is uses the value already set for the request header, and this seems to have eliminated the intermittent stall in our application.
<hr>

* What service are you using? **S3**
* In what version of SDK are you facing the problem? **2.6.1**
* Is the issue limited to Simulators / Actual Devices? **Both**
* Can your problem be resolved if you bump to a higher version of SDK? **N/A**
* Is this problem related to specific iOS version? **No**
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? **CocoaPods**
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

See also #602

**Comment by kvasukib** [comment]
Hello @tbuscher,

Can you try `AWSS3TransferUtility` which has multi-part and background support for uploads in 2.6.13? You can have a look at the API Reference here: https://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html#//api/name/uploadDataUsingMultiPart:key:contentType:expression:completionHandler:NS_SWIFT_NAME:
