### ISSUE TITLE
Can't use on watchOS ?

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#742]

**Comment by kvasukib** [comment]
Hi, @helloniklas,

Thanks for reporting to us. Can you provide a description of what part of the SDK are you trying to use on watchOS?

**Comment by helloniklas** [comment]
Awsauthcore
Awscore
Awsdynamodb

**Comment by kvasukib** [comment]
Thank you for the reply. Currently, our SDK is only compatible with iOS. We are taking it as a feature request.

**Comment by helloniklas** [comment]
Your MobileHub is not very mobile then. Guess I can use auth0 instead with custom authoriser then skip Cognito and make normal https request to APIGateway. A lot of work though.

**Comment by sailinz** [comment]
> Thank you for the reply. Currently, our SDK is only compatible with iOS. We are taking it as a feature request.

Is there any reference for this feature's progress?

**Comment by jignesh123** [comment]
Is there any update on this ?. I want to add in my watch os app.
