### ISSUE TITLE
task.result is nil for my sdk generated by apigateway

### ISSUE THREAD

**Issue by randalb1991** [aws/aws-sdk-ios#744]
I have an issue with my SDK generated for IOS(Swift 4).I've implement the get method for the resource:
 https://utakevspc6.execute-api.eu-west-1.amazonaws.com/production/petstorewalkthrough/flattenall

Based on http://docs.aws.amazon.com/es_es/apigateway/latest/developerguide/getting-started-models.html#getting-started-models-lambda:

It works when i calling with postman, but when I generate the SDK for IOS the result of the task has ever the following values:
`Optional(<AWSTask: 0x600000278300; completed = YES; cancelled = NO; faulted = NO; result = (null)>) `

My code used for this call is:

` func testAWS(){
        let client = RDTalkClassClient.default()
        
        
        client.petstorewalkthroughFlattenallGet().continueWith{ (task: AWSTask?) -> AnyObject? in
            if let error = task?.error {
                print("Error occurred: \(error)")
                return nil
            }
            task?.waitUntilFinished()
            if let completed = task?.isCompleted{
                print("i have the result")
                print(task)
                print(task?.result)
                // Do something with result
            }
            print("nil")
            return nil
        }
        
    }`

You can found all my code on my github https://github.com/randalb1991/talkclassIOS

### INFO

* What service are you using?
My SDK for IOS generated by APIGATEWAY
* In what version of SDK are you facing the problem?
2.6.2
* Is this problem related to specific iOS version?
I don't know
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Framework

**Comment by randalb1991** [comment]
¿Does it a issue? or is a problem with my infrastructure

**Comment by rohandubal** [comment]
Does this issue happen when platform is set to Swift 3 or only for Swift 4? Currently the generated SDK is Swift 3 only.

**Comment by randalb1991** [comment]
For swift 4. Do you if the SDK will be generated for swift4?

**Comment by cbommas** [comment]
hello @randalb1991 

We have plans to move to Swift 4, but the timing for it is TBD at this point. Please look for a Forum announcement or an update to this thread once we have a timeline identified.
