### ISSUE TITLE
"You need to configure `awsconfiguration.json` or `Info.plist` before using this method"

### ISSUE THREAD

**Issue by jboo1212** [aws/aws-sdk-ios#745]
I have completed the "build a basic backend" and "user sign in" guide and I've downloaded the most recent "awsconfiguration.json."  In the step-by-step guide, it says that all I need to do is have my configuration.json file in the same folder as info.plist which I've done, yet still receive this error.  I'm not sure how I'm supposed to get AWS up and running when nothing seems to be touching the configuration.json file and reading from it...

Attached are the "info.plist," AppDelegate.Swift, Podfile files.

Below is the call stack:

2017-10-02 22:46:10.903415-0700 testingwithamazon[31699:963568] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `awsconfiguration.json` or `Info.plist` before using this method.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001115071cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e1e9f41 objc_exception_throw + 48
	2   AWSAuthCore                         0x000000010d7c53ed __44+[AWSIdentityManager defaultIdentityManager]_block_invoke + 205
	3   libdispatch.dylib                   0x000000011255243c _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00000001125539c7 dispatch_once_f + 297
	5   AWSAuthCore                         0x000000010d7c52f4 +[AWSIdentityManager defaultIdentityManager] + 84
	6   AWSAuthCore                         0x000000010d7c5c49 __34+[AWSSignInManager sharedInstance]_block_invoke + 153
	7   libdispatch.dylib                   0x000000011255243c _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00000001125539c7 dispatch_once_f + 297
	9   AWSAuthCore                         0x000000010d7c5b84 +[AWSSignInManager sharedInstance] + 84
	10  testingwithamazon                   0x000000010d4d5990 _T017testingwithamazon11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tF + 112
	11  testingwithamazon                   0x000000010d4d675a _T017testingwithamazon11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tFTo + 186
	12  UIKit                               0x000000010e7b035a -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 267
	13  UIKit                               0x000000010e7b1db7 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4105
	14  UIKit                               0x000000010e7b7245 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1720
	15  UIKit                               0x000000010eb72c6c __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 924
	16  UIKit                               0x000000010ef403ef +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	17  UIKit                               0x000000010eb72865 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 249
	18  UIKit                               0x000000010eb730c3 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 668
	19  UIKit                               0x000000010f4d0c11 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 262
	20  UIKit                               0x000000010f4d0aca -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 444
	21  UIKit                               0x000000010f1beb9c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 420
	22  UIKit                               0x000000010f3b9c3e _performActionsWithDelayForTransitionContext + 100
	23  UIKit                               0x000000010f1be998 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 231
	24  UIKit                               0x000000010ef3fa4c -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	25  UIKit                               0x000000010e7b5ac6 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 523
	26  UIKit                               0x000000010ed7e523 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 369
	27  FrontBoardServices                  0x0000000114102158 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 338
	28  FrontBoardServices                  0x000000011410ac4d __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 235
	29  libdispatch.dylib                   0x000000011255243c _dispatch_client_callout + 8
	30  libdispatch.dylib                   0x0000000112557af4 _dispatch_block_invoke_direct + 592
	31  FrontBoardServices                  0x0000000114136672 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	32  FrontBoardServices                  0x0000000114136328 -[FBSSerialQueue _performNext] + 464
	33  FrontBoardServices                  0x0000000114136897 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	34  CoreFoundation                      0x00000001114aa2b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	35  CoreFoundation                      0x0000000111549d31 __CFRunLoopDoSource0 + 81
	36  CoreFoundation                      0x000000011148ec19 __CFRunLoopDoSources0 + 185
	37  CoreFoundation                      0x000000011148e1ff __CFRunLoopRun + 1279
	38  CoreFoundation                      0x000000011148da89 CFRunLoopRunSpecific + 409
	39  GraphicsServices                    0x0000000114a299c6 GSEventRunModal + 62
	40  UIKit                               0x000000010e7b8d30 UIApplicationMain + 159
	41  testingwithamazon                   0x000000010d4d6a57 main + 55
	42  libdyld.dylib                       0x00000001125ced81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

----------------------------------------------------------------------------------------------
[githubissue.zip](https://github.com/aws/aws-sdk-ios/files/1351252/githubissue.zip)

* What service are you using? 
AWS iOS Mobile Hub SDK with Facebook Signin, DynamoDB

* In what version of SDK are you facing the problem?
2.6.2
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

**Comment by kvasukib** [comment]
Hi Jerome,

Thanks for using our SDK and reporting to us.

From the Podfile it looks like you are integrating FacebookSignIn and AuthUI. 

Have you followed the steps here?
http://docs.aws.amazon.com/mobile-hub/latest/developerguide/add-aws-mobile-user-sign-in-facebook.html

How did you add the awsconfiguration.json to your XCode Project? Can you check if the file exists on disk and in XCode as well?

Thanks

**Comment by jboo1212** [comment]
The link you sent here was for Android.  Yes, I did follow the steps.

I downloaded the awsconfiguration.json file into my Downloads folder on my Mac and then I dragged the file into Xcode and copied the groups, etc. like the instructions said to.

**Comment by jboo1212** [comment]
[Culinarian-aws-my-sample-app-ios-swift.zip](https://github.com/aws/aws-sdk-ios/files/1354196/Culinarian-aws-my-sample-app-ios-swift.zip)
Here is the screenshot of the awsconfiguration on my disk & the zip of the project itself.

![screen shot 2017-10-03 at 4 24 16 pm](https://user-images.githubusercontent.com/8954137/31153728-a3121c0e-a857-11e7-858a-1fe9a80a4280.png)

**Comment by jboo1212** [comment]
Found out what's wrong: the awsconfiguration.json file didnt have the target membership checked for the project, not sure why it doesnt do it automatically because it always does.

**Comment by FozziWig1998** [comment]
how do you change the target membership for the project?

**Comment by kredden** [comment]
![screen shot 2018-01-02 at 7 51 46 am](https://user-images.githubusercontent.com/13521046/34489744-4b0cc4fa-ef92-11e7-9234-ba7af6e11f9c.png)

**Comment by daviskoh** [comment]
Was wondering. Why is `Info.plist` or `awsconfiguration.json` required if necessary configuration is set in the code. Ex:

```
let credentialProvider = AWSCognitoCredentialsProvider(
      regionType: .USEast1,
      identityPoolId: "poolId"
)

let serviceConfiguration = AWSServiceConfiguration(
      region: .USEast1,
      credentialsProvider: credentialProvider
)

AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration
```

**Comment by kvasukib** [comment]
Thank you @daviskoh for reporting to us. Info.plist or awsconfiguration.json is necessary for the User SignIn feature as described in the https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html page. User SignIn however as an exception doesn't use AWSServiceConfiguration and relies on Info.plist or awsconfiguration.json. 

For other parts of the SDK AWSServiceConfiguration still holds good and can be a substitute for Info.plist or awsconfiguration.json.

**Comment by ETGgames** [comment]
My awsconfiguration.json file has like no data and looks like this: 

`{
  "UserAgent": "MobileHub/1.0",
  "Version": "1.0",
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "eu-west-1:3f7e0e1d-568e-48ad-a255-ae4480b809eb",
        "Region": "eu-west-1"
      }
    }
  },
  "IdentityManager": {
    "Default": {}
  },
  "PinpointAnalytics": {
    "Default": {
      "AppId": "d98bb78926ea49c3b7425204eabc7e48",
      "Region": "us-east-1"
    }
  },
  "PinpointTargeting": {
    "Default": {
      "Region": "us-east-1"
    }
  }
}
`

I want to use rekognition on ios (swift), but I cannot add the app id and secret, where do I do this???

**Comment by vijjuk** [comment]
I am also getting the same error. while using pinpoint - *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The Pinpoint AppId is `nil`. You need to configure it in `awsconfiguration.json` or `Info.plist` before using this method.'

I have awsconfiguration.json in the target and also has the "PinpointAnalytics": {
        "Default": {
            "AppId": "f6f5cc63467e4e2f83aba08f6a2dce44",
            "Region": "us-east-1"
        }
    },

this is SUPER frustrating..can somebody tell me what is wrong 

I created everything as per the documentation using amplify CLI

**Comment by 101airborne** [comment]
I had the same problem when I ran the Amazon Polly Sample: 

_2019-07-25 14:27:13.323716-0500 PollySample[2567:1701131] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `awsconfiguration.json`, `Info.plist` or set `defaultServiceConfiguration` before using this method.'_

My problem was fixed when I changed occurrences of "Region": "**US_WEST_2**" to "Region": "**us-west-2**" in awsconfiguration.json.  I had specified the Region incorrectly.

**Comment by Ankish** [comment]
How do we set up for different schemes within the target ?

**Comment by isaac-patterson-xero** [comment]
@abvijaykumar did you find a solution to this. Currently running into this problem. Both target and aws configuration is setup correctly as far as I can tell. Very frustrating for a core feature
