### ISSUE TITLE
Can I access my bucket using host-style request in S3 ?

### ISSUE THREAD

**Issue by EricCheungSCUT** [aws/aws-sdk-ios#754]
### To help us solve your problem better, please answer the following list of questions.

From the article  http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html  I found that using host-style request can accelerate rerouting a little bit. Unfortunately from the source code I found that request sent by S3 SDK are all path-style request. Are there any plans to support host-style request in S3 SDK?

* What service are you using?
S3    
* In what version of SDK are you facing the problem?
2.6.4    
* Is the issue limited to Simulators / Actual Devices?
NO    
* Can your problem be resolved if you bump to a higher version of SDK?
NO    
* Is this problem related to specific iOS version?
NO    
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods    
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Simpley uploading a small object can see that.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by minbi** [comment]
Hi @EricCheungSCUT ,

Thank you for the question. If you wish to increase transfer speed, you may enable transfer acceleration -- which does have another pricing model.

As for the hosted-syle URL increasing speed; which part of the documentation are you looking at?

Are you referring to this sentence?
```
When you create a bucket, in any region, Amazon S3 updates DNS to reroute the request to the correct location, which might take time.
```
