### ISSUE TITLE
AWSS3TransferUtlity not restoring completion handlers after returning to foreground

### ISSUE THREAD

**Issue by ItsProf** [aws/aws-sdk-ios#755]
* What service are you using?
AWSS3TransFerUtility

* In what version of SDK are you facing the problem?
2.6.4

* Is the issue limited to Simulators / Actual Devices?
Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
Using the latest one

* Is this problem related to specific iOS version?
Tested on iOS 10.x.x 11.0.x

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

We are supporting background upload in one of our apps. The completion handlers do not get restored correctly when following the developer guide where that logic is done in the view controller's `viewDidLoad` method.

We setup a notification for `applicationDidBecomeActive` inside our uploads tracking view controller. We also persist the task identifiers for the restoration. The completion handlers are restored inside the notification handler method using the following code:

```swift
// Notification setup
override func viewDidLoad() {
    super.viewDidLoad()
    NotificationCenter.default.addObserver(self, selector: #selector(SKUploadsViewController.applicationDidBecomeActive(_:)), name: NSNotification.Name.UIApplicationDidBecomeActive, object: nil)
}

// Notification handler
func applicationDidBecomeActive(_ notification: Notification) {
    connectHandlers()
}

// Restoration function
func connectHandlers() {
        transferUtility.enumerateToAssignBlocks(forUploadTask: { task, progress, completion in
            print("[INFO] Restoring blocks for task: \(task.taskIdentifier)")
            
            progress?.pointee = { task, progress in
                print("[INFO] Upload Progress: \(progress.fractionCompleted)")
                DispatchQueue.main.async {
                    self.tableView.reloadData()
                }
            }
            
            completion?.pointee = { task, error in
                let tasks = self.persistedTasks as! [SKUpload]
                guard let foundTask = tasks.first(where: { $0.taskId == task.taskIdentifier }) else { return }
                
                if let error = error {
                    print("[ERROR] Error uploading: \(error.localizedDescription)")
                    DispatchQueue.main.async {
                        SKNotifications.showLocalNotificationIfNotActive(title: "Error Occurred", message: error.localizedDescription)
                        self.showErrorAlert(title: "Error Occurred", message: "An error occured while uploading media. Please try again.", completionHandler: nil)
                        self.deletePersistedTask(task: foundTask)
                    }
                } else {
                    print("[INFO] Upload completed, delete magical record object and clean up")
                    DispatchQueue.main.async {
                        if let tabBarController = self.tabBarController as? SKTabBarController {
                            tabBarController.setTabBarBadgeValue()
                        }
                        
                        self.tableView.reloadData()
                    }
                    
                    self.deletePersistedTask(task: foundTask)
                    
                    let successTitle = "Upload Complete"
                    let successMessage = "Your media has been successfully uploaded."
                    
                    SKNotifications.showLocalNotificationIfNotActive(title: successTitle, message: successMessage)
                }
            }
        })
    }
```

Please advice, the guide example on how to do it doesn't work at all, and our solution frequently fails as well so we suspect there is an issue in the SDK itself. Thank you very much.

**Comment by kvasukib** [comment]
Hi @itsProf,

Thanks for reporting to us. Can you tell us exactly what happens when the application becomes active? Is there a problem in updating the progress of the transfer or the transfer progress gets lost completely? Are you getting any exception?

**Comment by nick3389** [comment]
@kvasukib  do you have any news about this issue?

**Comment by nick3389** [comment]
@kvasukib any news about this?

**Comment by kvasukib** [comment]
Hi @nick3389 Sorry for the delayed reply. We did make enhancements to the `AWSS3TransferUtility` by supporting multi-part for uploads in `2.6.13`. Investigating completion handlers is the next task in our queue. Can you share any code/logs from your application? That will help us expedite the root-cause.

**Comment by kvasukib** [comment]
Hi @nick3389 Sorry for the delayed reply. We did make enhancements to the AWSS3TransferUtility by supporting multi-part for uploads in 2.6.13. Investigating completion handlers is the next task in our queue. Can you share any code/logs from your application? That will help us expedite the root-cause.

**Comment by cbommas** [comment]
@nick3389 @ItsProf 

The latest version of the SDK (2.6.23) has additional support for resuming transfers after app restart. 3 convenience methods have been added to the TransferUtilityTask

- `status`: to get the current status of the transfer. Returns an enumeration of type `AWSS3TransferUtilityTransferStatusType`
- `setCompletionHandler`: to set a completion handler to the transfer
- `setProgressBlock`: to set a progress block to the transfer for tracking.

If the app transitions from background to foreground, you don't need to re-associate or setup connection handlers. The ones that you setup before the app went to the background will be in place and will work fine.

For app restarts, I'd recommend the following approach that I personally find simpler
 
     let uploadTasks = transferUtility.getUploadTasks().result
             for task in uploadTasks! {
                 task.setCompletionHandler(completionHandler!)
                 task.setProgressBlock(progressBlock!)
             }

You can repeat this for downloadTasks and MultipartUploadTasks.

Please try these out and let me know if you run into issues.

**Comment by cbommas** [comment]
Closing this thread as we are tracking TransferUtility pause/resume/completion handler restoration/status etc in #769
