### ISSUE TITLE
AWSS3TransferUtility.uploadData(...) does not report error on wrong bucket name

### ISSUE THREAD

**Issue by alex-vasenin** [aws/aws-sdk-ios#757]
I'm uploading an image to S3 with AWSS3 v.2.6.4 (using Cocoa Pods).
`AWSS3TransferUtility.default().uploadData(data, bucket: bucketName, key: path, contentType: "image/jpeg", expression: nil).continueWith { task in
    if let error = task.error { /* handle failure */ }
    else { /* handle success */ }
}`
Everything goes well if all parameters are correct. If I don't specify the bucket name taks.error contains an error, as expected. However, if I call the method with wrong bucket name, task.error is nil while the actual upload operation is failed. Please fix.

**Comment by rohandubal** [comment]
Hello @alex-vasenin This is the expected behavior. The first task which is returned is an accepted task while the invalid bucket error is a service validation behavior.

Thanks,
Rohan

**Comment by alex-vasenin** [comment]
I don't get it, how returning success from failed operation is an expected behavior?

**Comment by k4ety** [comment]
This pull request solves this very issue, and I have been trying to get someone to review it for 5 months:  https://github.com/aws/aws-sdk-ios/pull/666
