### ISSUE TITLE
Feature request: S3 URL construction

### ISSUE THREAD

**Issue by alex-vasenin** [aws/aws-sdk-ios#758]
Quite often after uploading a file to S3 with AWSS3 iOS framework you need the URL of just uploaded file (I mean something like https://s3-us-west-1.amazonaws.com/your.bucket/your.key). It would be nice if AWSS3 could help with that. Well, at least AWSRegionType could have baseURL property.

**Comment by kvasukib** [comment]
Hi @alex-vasenin,

Thanks for reporting to us. We will take it as a feature request.
