### ISSUE TITLE
Cognito: Memory Leak

### ISSUE THREAD

**Issue by plm75** [aws/aws-sdk-ios#762]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using? Cognito auth with user pool

* In what version of SDK are you facing the problem? v2.6.5

* Is the issue limited to Simulators / Actual Devices?  no

* Can your problem be resolved if you bump to a higher version of SDK? no

* Is this problem related to specific iOS version? no

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? cocoa pods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
see attached example app

Hello, I'm trying to resolve a memory leak issue I'm having with Cognito as demonstrated in the attached app.  I may have done something wrong, but it looks like a bug.

[Cognito Test.zip](https://github.com/aws/aws-sdk-ios/files/1471029/Cognito.Test.zip)

**Comment by ryancrunchi** [comment]
I have the same problem.
With interactive auth, the SDK is retaining the AWSCognitoIdentityXXXAuthentication delegate object (LoginVC in the example above) in the CompletionSource task that is waiting for authentication details.
If for some reason we cancel the interactive auth and deinit the AWSCognitoIdentityXXXAuthentication object, it leaks.
In the example we dismiss the LoginVC but it is retained by the CompletionSource task.
