### ISSUE TITLE
bad entry in file AWSS3TransferManager.m (line = 531): Argument is not a literal string

### ISSUE THREAD

**Issue by michi-trecker** [aws/aws-sdk-ios#767]
Exporting an app with version AWSS3 2.6.6 has an issue:
"The data couldn’t be read because it isn’t in the correct format."

Based on Apples description:

> During XLIFF export or import, NSLocalizedString macro issues or empty strings files may result in an error, “The data couldn’t be read because it isn’t in the correct format."
> Remove empty strings files from your project or use the following Terminal command to find NSLocalizedString macro issues in your project.
> 
> $find <project directory> -name "*.m" -exec xcrun extractLocStrings {} \;
> 
> (21101899)

[Xcode Release Notes](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html)

Please fix AWSS3TransferManager.m (line = 531): Argument is not a literal string

**Comment by kvasukib** [comment]
Thanks for reporting to us. We are looking into it.

**Comment by kvasukib** [comment]
Hi @michi-trecker, Can you upgrade to 2.6.8 and check?
