### ISSUE TITLE
Building version 2.6.7 with Carthage fails

### ISSUE THREAD

**Issue by FlorianMielke** [aws/aws-sdk-ios#770]
The recent SDK version 2.6.7 fails to build with Carthage with the following error:

```
The following build commands failed:
	Ld /Users/xxx/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/aws-sdk-ios/2.6.7/Build/Intermediates.noindex/ArchiveIntermediates/AWSCognitoIdentityProvider/IntermediateBuildFilesPath/AWSiOSSDKv2.build/Release-iphoneos/AWSCognitoIdentityProviderASF.build/Objects-normal/armv7/AWSCognitoIdentityProviderASF normal armv7
```

Any hints how to fix that?

**Comment by minbi** [comment]
Should be fixed now.

**Comment by seclorum** [comment]
Including this binary in the archive breaks cocoa pods, please see the report at:

https://github.com/aws/aws-sdk-ios/commit/89ba87a1d9df05f3e386e78d580c149ccf6971d2

**Comment by louisvigneau** [comment]
SDK version 2.6.7 - AWSCognitoIdentityProviderASF

```
/Pods/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF/Internal/libAWSCognitoIdentityProviderASF.a(AWSCognitoIdentityASF.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
SDK version 2.6.7 - AWSCognitoIdentityProvider
```
ld: '/Library/Developer/Xcode/DerivedData/11_Life-dgipkwdkcswzpjcfoimxvjnipjao/Build/Intermediates.noindex/ArchiveIntermediates/11 Life/BuildProductsPath/Release-iphoneos/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF.framework/AWSCognitoIdentityProviderASF' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Library/Developer/Xcode/DerivedData/11_Life-dgipkwdkcswzpjcfoimxvjnipjao/Build/Intermediates.noindex/ArchiveIntermediates/11 Life/BuildProductsPath/Release-iphoneos/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF.framework/AWSCognitoIdentityProviderASF' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```


AWSCognitoIdentityProvider seems to lack full bitcode support - I was able to build it without bitcode - but then I cannot use bitcode in my IPAs with testFlight...

Will bitcode support come back to AWSCognitoIdentityProvider ?
Thank You.

**Comment by behrooziAWS** [comment]
I'm going to reopen this as it seems like there may be some outstanding issues.  @louisvigneau did you pull the latest version of the .a? @seclorum which cocoapods version are you using?

**Comment by louisvigneau** [comment]
@behrooziAWS I 

When ? : 1 hour ago (5 dec @ 7:30 PM GMT +1)

- did removed completely AWSCognitoIdentityProvider from my pod file
- pod install to un-install it completely
- put back AWSCognitoIdentityProvider from my pod file
- pod install to install it again
- pod update to be sure that this was the latest version

Info : I haven't specified a particular version of the pod, it should be getting the latest right ?

**Comment by behrooziAWS** [comment]
@louisvigneau Thanks for the clarification, seems like you have the latest.  We will investigate since it should have included the bitcode.

**Comment by behrooziAWS** [comment]
Hi @louisvigneau  on further review of what you did, it seems like you are still using the locally cached version not the latest with bitcode, please run `pod cache clean --all` and then `pod install` to pull it down from the repo again.  @seclorum AWSCognitoIdentityProviderASF pod is also creating libAWSCognitoIdentityProviderASF.a which is clashing with the binary that is included of the same name, we are going to rename the binary and will let you know when the fix is pushed.

**Comment by louisvigneau** [comment]
@behrooziAWS I will try this today. And will give you feedback as soon as I have it.

**Comment by louisvigneau** [comment]
@behrooziAWS AWSCognitoIdentityProvider and AWSCognitoIdentityProviderASF now supports bitcode ✅.
Thank You.

**Comment by seclorum** [comment]
@behrooziAWS  Roger that, thanks for the info - can you maybe tell me why it is that a pre-built library is being included in the sdk?  I'm kind of suspicious of this fact .. but perhaps there is a good reason?

**Comment by seclorum** [comment]
Aprorpos pod version, full details are available here:

https://github.com/aws/aws-sdk-ios/commit/89ba87a1d9df05f3e386e78d580c149ccf6971d2

**Comment by minbi** [comment]
AWS Mobile SDK for iOS 2.6.8 has been released.

Please re-open if this issue is not resolved.
