### ISSUE TITLE
Is Text-in-image service available through the SDK?

### ISSUE THREAD

**Issue by Shoshin23** [aws/aws-sdk-ios#771]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Rekogntion

* In what version of SDK are you facing the problem?
2.6.7

* Is the issue limited to Simulators / Actual Devices?
Both

Hi, 

Is the Text in images feature that was introduced recently available through the ios sdk? I can't seem to find any relevant endpoints for this. 

Thanks!

**Comment by kredden** [comment]
Hi, it is not yet available in the Android or iOS SDK, we are working on it!

**Comment by Shoshin23** [comment]
Thanks! Any rough idea when it would be integrated with the sdk? Also, is there some documentation that details http calls out for me?

**Comment by Shoshin23** [comment]
*AWS rekognition text-in-image feature.

**Comment by minbi** [comment]
AWS Mobile SDK for iOS 2.6.8 has been released.

Please re-open if this issue is not resolved.

**Comment by kredden** [comment]
2.6.8 includes the Text in Images feature for Rekognition.

Regards,
Kevin
