### ISSUE TITLE
AWSCognitoIdentityProviderASF with bitcode

### ISSUE THREAD

**Issue by damoteTHC** [aws/aws-sdk-ios#772]
* What service are you using?
AWSCognitoIdentityProvider

* In what version of SDK are you facing the problem?
2.6.7

* Is the issue limited to Simulators / Actual Devices?
VM and exporting archive

* Can your problem be resolved if you bump to a higher version of SDK?
unknown

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods, dependency declared in private pod podspec

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Issue arises when attempting to validate an Archive from xCode 9.0 and 9.1. Witness when using generating Enterprise target on Bitrise.io. The advanced security feature "was built without full bitcode". Overall build settings for Enterprise target disable bitcode. Work-around solution was pinning to 2.6.6

Are there additional settings that we need to be configuring?

**Comment by minbi** [comment]
The repo was just updated with the library that has full bitcode. Can you try again?

**Comment by damoteTHC** [comment]
Yes! That resolved the issue. Thanks!

**Comment by swiftTalker** [comment]
@minbi is this fixed pushed to production? which cocoa pod version?

**Comment by behrooziAWS** [comment]
2.6.7, you should do a `pod cache clean --all` and `pod install` to make sure it isn't using the cached bad version.
