### ISSUE TITLE
AWSS3TransferUtilityTimeoutIntervalForResource

### ISSUE THREAD

**Issue by nick3389** [aws/aws-sdk-ios#773]
Will there be a future possibility to customize the AWSS3TransferUtilityTimeoutIntervalForResource static property of AWSS3TransferUtility class?

Thank you!

**Comment by kvasukib** [comment]
Hi @nick3389, Thanks for reporting to us. The limit of 50 minutes is imposed by Amazon Cognito Federated Identities. The Cognito credentials need to be refreshed after every 50 minutes and this is required for the S3 operations to succeed. Hence, AWSS3TransferUtilityTimeoutIntervalForResource is a constant.

**Comment by nick3389** [comment]
@kvasukib So, if I use only the AWSS3TransferUtility and not the Cognito service, am I restricted to this timeout?

**Comment by kvasukib** [comment]
The AWSS3TransferUtility creates PreSigned URLs that rely on the Cognito Identity to retrieve temporary credentials. http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html#limitations.
You can use AWSS3 class instead which is the low-level client and you will not be having this interval limit when you use it with STS (Security Token Service) or AWS Access / Secret Access Keys.

**Comment by nick3389** [comment]
@kvasukib Do you mean the AWSS3Service class?. Is there any documentation for using this?

**Comment by kvasukib** [comment]
It would be this one: http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html

**Comment by nick3389** [comment]
Does it support handleEventsForBackgroundURLSession?

**Comment by kvasukib** [comment]
The AWSS3 client (http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3.html) doesn't support background transfers. The AWSS3TransferUtility only supports background transfers.

**Comment by nick3389** [comment]
Ok. So, I guess I am stuck with AWSS3TransferUtility. Is there any plan to support background transfers with the AWSS3 client?

**Comment by cbommas** [comment]
Hello nick3389

Thank you for your continued feedback on this topic. The TransferUtility component currently has a hard limit of 50 minutes as already mentioned by kvasukib. I have added the following enhancements requests to the SDK backlog. 
- Make the timeout configurable
- Allow the client to pass in credentials to the TransferUtility
- Implement Multipart uploads in TransferUtility

Please check back on this thread ( or look for general forum announcements)  for updates on these items.

That said, if you are currently blocked and need a solution for longer lived background uploads, you can do a background transfer with S3 using pre-signed URLs and NSURLSession. (see  https://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3-pre-signed-urls.html for further details)

**Comment by chrisscholly** [comment]
Would be so nice if `AWSS3TransferUtility` could have a configurable timeout.
So, I am also stuck with AWSS3TransferUtility at the moment :(

**Comment by chrisscholly** [comment]
@nick3389 Have you found any solution for the moment?

**Comment by nick3389** [comment]
@chrisscholly no. I still use transfer utility, but every time I do a `pod update`, I change manually the timeoutInterval. Probably I will wait for the changes @cbommas mentioned. For now, I leave it as it is.

**Comment by chrisscholly** [comment]
@nick3389 Thank you for the update.
Changing manually the timeoutInterval is enough to overcome the 50 minutes limitation?
@cbommas @kvasukib could you also confirm?

**Comment by nick3389** [comment]
@chrisscholly Yes, it's working.

**Comment by chrisscholly** [comment]
@nick3389 Are you sure? Only by tweaking the timeoutInterval?
Seems like we should also pass in credentials to the TransferUtility instead of letting Cognito Identity retrieve temporary credentials.

**Comment by nick3389** [comment]
@chrisscholly Sorry, I forgot to mention that I don't use Cognito. I use accessKey and secretKey for S3 (static credentials). You should setup your own `defaultServiceConfiguration` and then register in `AWSS3TransferUtility` with:
`+ (void)registerS3TransferUtilityWithConfiguration:(AWSServiceConfiguration *)configuration forKey:(NSString *)key;`

**Comment by chrisscholly** [comment]
@nick3389 Okay, thank you, will have a try :)

**Comment by chrisscholly** [comment]
@nick3389 Seems like it works like a charm 👌
Thanks bro!

**Comment by chrisscholly** [comment]
@nick3389 Just noticed that `TransferUtility` does not support multi-parts 😔
So it will be very tricky to upload large files.
What is your strategy in terms of network loss, pause/resume, etc.?

**Comment by cbommas** [comment]
@chrisscholly We are working on adding multi-part functionality to the Transfer Utility and  adding enhanced error handling/retry to tackle network loss, pause/resume etc. Please check back on this thread (or look for general forum announcements) for updates on these items.

**Comment by kvasukib** [comment]
We have added support for Mulit-part in uploads in `AWSS3TransferUtility` in `2.6.13`. Please upgrade and let us know any feedback you have.

**Comment by kvasukib** [comment]
Hello @nick3389 @chrisscholly 

The latest version of the SDK, 2.6.20 released on 6/1/2018, contains this feature. 

        let serviceConfiguration = AWSServiceManager.default().defaultServiceConfiguration
        let transferUtilityConfiguration = AWSS3TransferUtilityConfiguration()
        //Set the timeoutIntervalForResource parameter (in seconds)
        transferUtilityConfigurationWithRetry.timeoutIntervalForResource = 15*60 //15 minutes
        
        AWSS3TransferUtility.register(
            with: serviceConfiguration!,
            transferUtilityConfiguration: transferUtilityConfiguration,
            forKey: "custom-timeout"
        )

        //Instantiate the transfer utility
        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "custom-timeout")
