### ISSUE TITLE
LEX iOS SDK  -Speech not recognized correctly in iPhone device 

### ISSUE THREAD

**Issue by eniyavans** [aws/aws-sdk-ios#774]
* What service are you using?
LEX speech recognition service

* In what version of SDK are you facing the problem?
 AWSLEX iOS SDK version    is '2.6.7'

* Is the issue limited to Simulators / Actual Devices?
Issue iss Happening in  iPhone devices where in iOS simulators this issue is not occurring.

* Can your problem be resolved if you bump to a higher version of SDK?
Not sure.

* Is this problem related to specific iOS version?
We are using iOS  11.x

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Speech not recognized correctly in iPhone device wheres, if we use the same phrase in simulator the speech is  recognized correctly.

LEX iOS SDK version- 2.6.7'
Input type - Speech 
iOS SDK version  -11.1
iOS version  -11.x

**Comment by kredden** [comment]
What kind of recognition issues are you seeing?  Is only part of it being recognized, none of it?  Can you give us some sample phrases?

Thanks,
Kevin

**Comment by Baalakrishnan** [comment]
Hi Kavin,
We tried with the Simulator iOS 11.2  it will respond 8/10 times but in the device, it will give 1/10 response for iOS 10.x and 11.x, for Latest iOS 11.2, it has some improvement 4/10 times, We tired with the name (First name and Last name) and country/location. most probably we got the answer as "sorry you can repeat that" in device and probability of text conversion also less with two letter words.
Thanks,
Bala

**Comment by kredden** [comment]
Bala,

I just tried using this example: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/Lex-Sample/swift-3 and am not having any issues.  Can you try this sample with your bot and let me know if you have the same problems?  Please update the podfile with the following before building:

platform :ios, '9.0'

pod 'AWSLex', '~>2.6.0'

Thanks,
Kevin

**Comment by kredden** [comment]
Any luck?

**Comment by Baalakrishnan** [comment]
Hi Kredden,
Thanks for help, right now its working for us due to audio shared instances and some other loading animation cause this issue, Now we sorted out the issue 

Thanks,
Balakrishnan J

**Comment by kredden** [comment]
Great to hear it is working for you!  Closing the issue.

Regards,
Kevin
