### ISSUE TITLE
AWSMobileClient target is not compatible with armv7

### ISSUE THREAD

**Issue by FlorianMielke** [aws/aws-sdk-ios#775]
Archiving the AWS SDK 2.6.8 with a deployment target < iOS 11.0 results a linker error:

```
Undefined symbols for architecture armv7:
"_OBJC_CLASS_$_AWSMobileClient", referenced from:
...
ld: symbol(s) not found for architecture armv7
```

This is because the AWSMobileClient target has set it's deployment target to iOS 11.0 which only supports arm64 architecture.

**Comment by rohandubal** [comment]
Hello, how are you consuming the AWSMobileClient? I can try and a do a patch release to fix the issue. Please let us know!

Thanks,
Rohan.

**Comment by FlorianMielke** [comment]
I'm consuming it via Carthage.

**Comment by minbi** [comment]
Version 2.6.9 of the iOS SDK has been released.

Please re-open if problem persists.

**Comment by FlorianMielke** [comment]
Thanks. It's fixed.
