### ISSUE TITLE
AWSTask `continueOnSuccessWith` immediately executes without waiting all tasks finished

### ISSUE THREAD

**Issue by wqfan** [aws/aws-sdk-ios#778]
* What service are you using?
AWS S3
* In what version of SDK are you facing the problem?
2.6.8
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hello, I'm following this [example](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html#executing-multiple-tasks) to do a parallel S3 uploading. However, I met a problem that the `continueOnSuccessWith` callback immediately returns without waiting all tasks finished. I have the code below.

```swift
static func uploadMultipleToS3(photos: [S3Photo], exp: AWSS3TransferUtilityUploadExpression? = nil) {
    var tasks = [AWSTask<AWSS3TransferUtilityUploadTask>]()
    for p in photos {
        tasks.append(transferUtility.uploadData(p.raw, bucket: "bucket_name", key: "\(p.id).\(p.ext)", contentType: "image/\(p.ext)", expression: exp, completionHandler: { (_, _) in print("Single") }))
    }
    
    AWSTask(forCompletionOfAllTasks: tasks as? [AWSTask<AnyObject>]).continueOnSuccessWith { (task: AWSTask<AnyObject>) -> Any? in
        print("All")
        return nil
    }.continueWith { (task: AWSTask<AnyObject>) -> Any? in
        if let error = task.error {
            print(error)
        }
        return nil
    }
}
```

The function prints `"All"` immediately and then prints multiple `"Single"`.

I was wondering if I use the SDK correctly and hope to get some pointers! Thanks!

**Comment by kvasukib** [comment]
The `continueOnSuccessWith` block gets executed when the S3 request successfully reaches the AWS S3 service. For completion handler, you can use `completionHandler` parameter in `uploadData` API to know when the upload task finished execution.
