### ISSUE TITLE
AWSKinesis diskBytesUsed didn't change instantaneously after adding a record

### ISSUE THREAD

**Issue by shadiabusamra** [aws/aws-sdk-ios#779]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
  Amazon Kinesis Firehose

* In what version of SDK are you facing the problem?
2.6.6

* Is the issue limited to Simulators / Actual Devices?
Both

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Prebuilt frameworks

* Steps to reproduce:
1-Add record (saveRecord:(NSData *)data
             streamName:(NSString *)streamName)
2-Check  diskBytesUsed (kinesisRecorder.diskBytesUsed)
Actual result: diskBytesUsed did not change 
Expected result: diskBytesUsed should increase by record size

**Comment by kredden** [comment]
The call to saveRecord is asynchronous so the diskBytesUsed value will not be set immediately.
