### ISSUE TITLE
SDK Error

### ISSUE THREAD

**Issue by sakthinath** [aws/aws-sdk-ios#780]
### To help us solve your problem better, please answer the following list of questions.
Thread 1: signal SIGABRT
* What service are you using?
AWS S3
* In what version of SDK are you facing the problem?
2.6.8
* Is the issue limited to Simulators / Actual Devices?
simulator and Divice
* Can your problem be resolved if you bump to a higher version of SDK?
NO
* Is this problem related to specific iOS version?

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapod
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kredden** [comment]
Are you using one of the samples, if so which one?  Did you follow the instructions in the ReadMe?  Can you post a stack trace?

Thanks,
Kevin

**Comment by kredden** [comment]
Closing due to no response, please reopen if you still have this issue.
