### ISSUE TITLE
How do I automatically sign in a user after sign up

### ISSUE THREAD

**Issue by hermanccw** [aws/aws-sdk-ios#782]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
2.6.6

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Once I signup a user with user name and password, confirmed code sent from SMS, how do I sign in a user without asking the user to input the password again?  Seems like there is no way.  A lot of people have also ask for this functionality it seems: https://github.com/aws/amazon-cognito-identity-js/issues/186

I tried calling `getSession:username:password:validationData` with the user name and password that I *just* entered and it gives me an user name and password invalid error.

```
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=20 "(null)" UserInfo={__type=NotAuthorizedException, message=Incorrect username or password.}
```

**Comment by kvasukib** [comment]
Hi @hermanccw, Thanks for reporting to us. We are taking it as a feature request.

**Comment by hermanccw** [comment]
@kvasukib hmmmm is there a way to hack around this atm?

**Comment by jukka-palomaki** [comment]
You can store the password internally and login with that after user creation.

**Comment by lreddy90** [comment]
> ### To help us solve your problem better, please answer the following list of questions.
> * What service are you using?
>   Cognito
> * In what version of SDK are you facing the problem?
>   2.6.6
> * Is the issue limited to Simulators / Actual Devices?
>   Both
> * Can your problem be resolved if you bump to a higher version of SDK?
>   No
> * Is this problem related to specific iOS version?
>   No
> * How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
>   Carthage
> * Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
> 
> Once I signup a user with user name and password, confirmed code sent from SMS, how do I sign in a user without asking the user to input the password again? Seems like there is no way. A lot of people have also ask for this functionality it seems: [amazon-archives/amazon-cognito-identity-js#186](https://github.com/amazon-archives/amazon-cognito-identity-js/issues/186)
> 
> I tried calling `getSession:username:password:validationData` with the user name and password that I _just_ entered and it gives me an user name and password invalid error.
> 
> ```
> Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=20 "(null)" UserInfo={__type=NotAuthorizedException, message=Incorrect username or password.}
> ```

Same error is throwing when i use getdetails() method. can any one suggestion me the solution?

**Comment by shaikhshoeb** [comment]
AWSCognitoIdentityProviderErrorDomain error 20
i am getting this error when i want to delete user from cognito user pool 

AWSCognitoIdentityUserPool.default().currentUser()?.delete().continueWith(block: { (task) -> Any? in
                             if let error = task.error {
                                 print("Error deleting user: \(error.localizedDescription)")
                             }
