### ISSUE TITLE
AWSCore can't find out in my project

### ISSUE THREAD

**Issue by DavidPhysics** [aws/aws-sdk-ios#783]
My Podfile
---------
target 'AWS_Application_Congfito' do
source 'https://github.com/CocoaPods/Specs.git'

  platform :ios, '9.0'
  use_frameworks!

  target :'AWS_Application_Congfito' do
    pod 'AWSAutoScaling'
    pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    pod 'AWSKinesis'
    pod 'AWSLambda'
    pod 'AWSLex'
    pod 'AWSMachineLearning'
    pod 'AWSMobileAnalytics'
    pod 'AWSPinpoint'
    pod 'AWSPolly'
    pod 'AWSRekognition'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'
  end

  target 'AWS_Application_CongfitoTests' do
    inherit! :search_paths
    
  end

  target 'AWS_Application_CongfitoUITests' do
    inherit! :search_paths
    
  end

end

My application delegate.m file.
--------
#import "AppDelegate.h"
_#import <AWSCore/AWSCore.h>_

@interface AppDelegate ()

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    return YES;
}
--------
Step1 "pod install" in cmd.
Step2 "pod update" in cmd.
Step3 "pod update" in cmd
Step4 Add "#import <AWSCore/AWSCore.h>" to application delegate.m file.

The delegate.m file of my project can't find out "AWSCore/AWSCore.h" when I set ATS. My cocoapods version is 1.3.1. I have read the AWS iOS developer guild, but it also has same as a problem.

Can tell me why my project can't find out the AWSCore?

**Comment by kredden** [comment]
Are you opening the project file or the workspace file in XCode (you should be opening the workspace file)?  What are you trying to do with AWSCore?  Are you getting an error when you try to compile?

If you look in your "Pods" section of your workspace and expand the Pods directory do you see the "AWSCore" directory in there?

Have you tried doing a clean build?

Kevin

**Comment by DavidPhysics** [comment]
When I edited the codes(AWSCore), Xcode showed the error message. The error message told  me AWSCore could not find out in workspace file.
Expand the Pods directory? When I opened my project workspace file, I saw my project has two project files. One file is my project. Another is Pods file.

**Comment by kvasukib** [comment]
When you open AWS_Application_Congfito.xcworkspace in XCode, on the left side under "Pods" -> "Pods" -> "AWSCore". Are you seeing this directory "AWSCore" under Pods/Pods in XCode?

**Comment by DavidPhysics** [comment]
My progress:
Step1 create the iOS project.
Step2 sudo gem install cocoapds
Step3 pod setup
Step4 pod init
Step5 Open Podfile and add AWS service.
Step6 pod install
Step7 pod update 
Step8 Open project workspace file.
Step9 Add "#import <AWSCore/AWSCore.h>" in applications delegate.m file. 

The step9 shows a error message which tells me AWSCore can not find out.

**Comment by DavidPhysics** [comment]
@kvasukib Yes! I see it.

**Comment by kvasukib** [comment]
Hi @DavidPhysics, What version of XCode are you using?

**Comment by DavidPhysics** [comment]
@kvasukib My Xcode version is 8.3.3 (8E3004b).

**Comment by DavidPhysics** [comment]
@kredden @kvasukib 
My Xcode screen:
<img width="1280" alt="screen shot 2017-12-14 at 10 41 03 pm" src="https://user-images.githubusercontent.com/25798404/33997603-ebd0a81a-e11f-11e7-9d78-8d54f0b51c4d.png">

**Comment by kredden** [comment]
Have you actually tried building your code (command-B)?  If you have not compiled you will see this error.

Kevin

**Comment by DavidPhysics** [comment]
@kredden Why? I remember the framework concept is a kind of hierarchy directory and can share resources. If I add any AWS service or any function codes to my project when I edit my code, will always see this error?

**Comment by kredden** [comment]
After you use Cocoapods to download the source from the SDK the code needs to be compiled/built in Xcode before will stop giving you that error.

**Comment by DavidPhysics** [comment]
When I build my code, the Xcode shows more the warning message about other AWS service. 
The AWSCore error message have disappeared, but other warning message shows on my Xcode.
Could tell me why my Xcode shows more other warning message? Is it a normal phenomenon?

<img width="1280" alt="screen shot 2017-12-16 at 1 37 02 pm" src="https://user-images.githubusercontent.com/25798404/34069481-40cf7b02-e28d-11e7-94cc-0cbc930a9ad9.png">

<img width="1280" alt="screen shot 2017-12-16 at 1 37 06 pm" src="https://user-images.githubusercontent.com/25798404/34069482-454eea3c-e28d-11e7-9a55-cf5266fbec83.png">

**Comment by kredden** [comment]
Yes, those are normal.  Does your app launch and run as expected?

**Comment by DavidPhysics** [comment]
Yes. I can't understand why I add new codes about AWS service which always shows warning message on my Xcode? Is it because my iOS app running environment sets iOS10? If my profiles sets iOS10, will the warning message always show on my Xcode?

**Comment by kredden** [comment]
It all depends on what target platform you are using and what version of Xcode.  As new versions of Xcode come out they typically add more checks that cause warnings in older code.

Not all developers update to the latest Xcode right away so the SDKs need to support more than the latest version of Xcode and not all the new warnings and deprecations that come out are backward compatible.

**Comment by DavidPhysics** [comment]
@kredden Thank you.
