### ISSUE TITLE
Transfer Acceleration Support for S3

### ISSUE THREAD

**Issue by farzaa** [aws/aws-sdk-ios#784]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3

* In what version of SDK are you facing the problem?
2.6.8

* Is the issue limited to Simulators / Actual Devices?
No.

* Can your problem be resolved if you bump to a higher version of SDK?
No.

* Is this problem related to specific iOS version?
No.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hey there all! 

On my S3 bucket I flicked the switch that allows the bucket to use transfer acceleration. But, to actually reflect this change in my code is proving to be a bit difficult. Based of my searches, here is how I have it set up.

In my AppDelegate I have:

`        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1, identityPoolId:  IDENT_POOL_ID)
        let configuration = AWSServiceConfiguration(region:.USEast1, credentialsProvider:credentialsProvider)
        
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        let t = AWSS3TransferUtilityConfiguration()
        t.isAccelerateModeEnabled = true
        
        AWSS3TransferUtility.register(with: configuration!, transferUtilityConfiguration: t, forKey: "transfer-acceleration")` 

Then, within my download method I have:

`        let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-acceleration").download(.........`

I'm pretty sure what I'm doing right now is incorrect because when I go to actually start my downloads they are just as slow as before the acceleration. But, I directly looked at the test example from here: https://github.com/aws/aws-sdk-ios/blob/master/AWSS3Tests/AWSS3TransferUtilityTests.swift and the way its done there is exactly how I do it.

Could that example be outdated? Any help on properly doing this would be greatly appreciated.

**Comment by kvasukib** [comment]
Hi @farzaa, What is the file type and size you are trying to upload? Have you setup Transfer Acceleration for the bucket on the S3 Console?

**Comment by farzaa** [comment]
Hey there! 

I am actually trying to download some small (500KB) JPEG files.

And yes, I have set up transfer acceleration. As far as I know I still have to somehow tell the SDK to to use transfer acceleration. Sort of like how I did in my code snippet. Any advice there?

**Comment by farzaa** [comment]
Just a note, when I download directly from the transfer accelerated url (XXXXX.s3-accelerate.amazonaws.com)  by simply initiating a download from the URL, the download is near instant.

But, when i go through the S3 SDK it returns to taking 3-5 seconds for a 500KB image.

**Comment by cbommas** [comment]
farzaa,

I took a look at your code and it looks correct. Please note that the increase in the speed of S3 Acceleration depends on your location (i.e., where you are running the app) and where the bucket is located. Please check http://s3-accelerate-speedtest.s3-accelerate.amazonaws.com/en/accelerate-speed-comparsion.html to get an indicator of the speed-up.

To verify that you are indeed using acceleration, please do the following experiment - turn off acceleration on the bucket using the S3 console and restart the app and try the upload/download. The app should fail with "error from cloudfront" in the error details; this indicates that the code is looking for the accelerated bucket. Turn the acceleration back on and the error should disappear.
