### ISSUE TITLE
S3 (iOS SDK) takes a very long time to complete very small downloads.

### ISSUE THREAD

**Issue by farzaa** [aws/aws-sdk-ios#785]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3
* In what version of SDK are you facing the problem?
2.6.8
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hi there.

I am using the S3 SDK to download some very small images (500KB in size). I created a very basic app that simply logs image download times and found that these downloads take a very long time, up to 5 seconds on WiFi. I have tried different internet connections, and using it in LTE but the images still take a rather long time to load.

Though, I noticed that when I download batches of images together (like around 5 at a time) the downloads are very quick. I'm performing everything on the main thread just for test purposes and am using TransferUtility's download to file functions.

Is there any explanation for this behavior and is S3 just supposed to be this slow when dealing with small files?

**Comment by kvasukib** [comment]
Hi @farzaa, Are you running on device or simulator? Any configuration information about the device/simulator?

**Comment by farzaa** [comment]
Hey there! I am running on my iPhone 6S with the latest iOS. I've noticed that on both WiFi and LTE these tiny files take a very long time to download. I've tried using different WiFi connections and even using different phones with other cellular service providers. 

Though, I found that when I queue several downloads at the same time I get very good performance when they are all in a row like this. The downloads become near instant. But, one at a time leads to huge drops. 

Honestly not sure whats going on there or if thats intended behavior. Any help would be amazing.

**Comment by kvasukib** [comment]
Thanks @farzaa for the reply. Can you post the code snippet that you are using to upload/download files? Are you using AWSS3TransferUtility/AWSTransferManager/AWSS3 class?

**Comment by farzaa** [comment]
Sure!

So I'm using the near exact snippet from this example here - https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/DownloadViewController.swift

I also used TransferManager and got very similar results.

**Comment by kvasukib** [comment]
Hello @farzaa,

We have added support for mulit-part uploads in TransferUtility. This will speed up the uploads in TransferUtility. Can you upgrade to 2.6.13 and give a try? See [APIDoc](https://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html#//api/name/uploadDataUsingMultiPart:key:contentType:expression:completionHandler:NS_SWIFT_NAME:) for more details.
