### ISSUE TITLE
How to use User Pools App Integration and Federation with native UI in iOS Swift

### ISSUE THREAD

**Issue by phhuan** [aws/aws-sdk-ios#787]
Hi,
     I see that we have solution to use User Pools App Integration and Federation with native UI on Android (https://github.com/aws/aws-sdk-android/issues/370). 
    Could you please help me to confirm that we have a similar solution for iOS Swift ? 
thanks,

**Comment by minbi** [comment]
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Swift
