### ISSUE TITLE
AWSS3 & AWSCognito cocoapods in Xcode 9.2 breaks with error:  Implicit declaration of function 'assert' is invalid in C99

### ISSUE THREAD

**Issue by Pranoy1c** [aws/aws-sdk-ios#788]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using? AWSCognito & AWSS3

* In what version of SDK are you facing the problem? Latest 2.6.2

* Is the issue limited to Simulators / Actual Devices? Both

* Can your problem be resolved if you bump to a higher version of SDK? NO, already using latest

* Is this problem related to specific iOS version? Not sure

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

-----------

To reproduce, I created a brand new blank project using the single view controller template. Added the podfile:

    target "AWSTest" do
        pod 'AWSCognito'
        pod 'AWSS3'
    end

Ran `pod install` and then opened the workspace. Successful install:

    Analyzing dependencies
    Downloading dependencies
    Installing AWSCognito (2.6.2)
    Installing AWSCore (2.6.2)
    Installing AWSS3 (2.6.2)
    Generating Pods project
    Integrating client project
    
    [!] Please close any current Xcode sessions and use `AWSTest.xcworkspace` for this project from now on.
    Sending stats
    Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.

Build the app and it complains:

    Implicit declaration of function 'assert' is invalid in C99

at the following line from the pod file `AWSFMDatabase.m`:

    - (instancetype)initWithPath:(NSString*)aPath {
        
        assert(sqlite3_threadsafe()); // whoa there big boy- gotta make sure sqlite it happy with what we're going to do.
        
        self = [super init];
        
        if (self) {
            _databasePath               = [aPath copy];
            _openResultSets             = [[NSMutableSet alloc] init];
            _db                         = nil;
            _logsErrors                 = YES;
            _crashOnErrors              = NO;
            _maxBusyRetryTimeInterval   = 2;
        }
        
        return self;
    }

Is there something I can do to fix this?

**Comment by minbi** [comment]
I tried this in version 9.1 of XCode version 2.6.9 of Cocoapods.

**Comment by kredden** [comment]
I tried this in 9.2 and it had no issues.  Are you building a Swift or ObjC app?  Did you do this recently?  The reason I ask is that your log above shows Cocoapods pulling down 2.6.2 but the latest version that should be being pulled down based on your podfile above should be 2.6.9.

**Comment by kredden** [comment]
Are you still having the problem?

**Comment by kredden** [comment]
If you are still having this problem then please reopen this issue.

Regards,
Kevin
