### ISSUE TITLE
Confirming subscription - ios swift 4 SNS

### ISSUE THREAD

**Issue by AddyMehra** [aws/aws-sdk-ios#789]
This is the swift 4 code I'm using :

    private func subscribe(_ token : String, _ completionHandler : ((Error?) -> ())? = nil)
    {
        let credentialsProvider : AWSStaticCredentialsProvider = AWSStaticCredentialsProvider(accessKey: Constants.AWSAccessKey, secretKey: Constants.AWSSecretKey)
        let defaultServiceConfiguration : AWSServiceConfiguration = AWSServiceConfiguration(region: Constants.AWSRegion, credentialsProvider: credentialsProvider)
        
        AWSServiceManager.default().defaultServiceConfiguration = defaultServiceConfiguration
        
        let sns = AWSSNS.default()
        let createPlatformEndpointInput = AWSSNSCreatePlatformEndpointInput()
        createPlatformEndpointInput?.token = token
        createPlatformEndpointInput?.platformApplicationArn = Constants.SNSPlatformApplicationArn
        
        sns.createPlatformEndpoint(createPlatformEndpointInput!).continueWith { (task) -> AnyObject! in
            
            if task.error != nil {
                print("Error creating platform endpoint: \(task.error)")
                completionHandler?(task.error)
                return nil
            }
            let result = task.result as! AWSSNSCreateEndpointResponse
            let subscribeInput = AWSSNSSubscribeInput()
            subscribeInput?.topicArn = Constants.SNSTopicARN
            subscribeInput?.endpoint = result.endpointArn
            print("Enfdpoint created")
            print("Endpoint arn: \(result.endpointArn!)")
            subscribeInput?.protocols = "application"
            sns.subscribe(subscribeInput!).continueWith { (task) -> AnyObject! in
                
                if task.error != nil {
                    completionHandler?(task.error)
                    print("Error subscribing: \(task.error)")
                    return nil
                }
                print("Subscribed succesfully")
                print("Subscription arn: \(task.result?.subscriptionArn!)")
                let subscriptionConfirmInput = AWSSNSConfirmSubscriptionInput()

                subscriptionConfirmInput?.token = ???

                subscriptionConfirmInput?.topicArn = Constants.SNSTopicARN
                sns.confirmSubscription(subscriptionConfirmInput!).continueWith { (task) -> AnyObject! in
                    
                    if task.error != nil {
                        completionHandler?(task.error) 
                    }
                   print("Confirmed subscription")
                    return nil
                }
                return nil
            }
            return nil
        }
    }
Code is working fine till subscribing...

But what to enter in the "token" for : subscriptionConfirmInput?.token = ???

### To help us solve your problem better, please answer the following list of questions.

* What service are you using? SNS

* In what version of SDK are you facing the problem? 2.6.9

* Is the issue limited to Simulators / Actual Devices? 

* Can your problem be resolved if you bump to a higher version of SDK? No

* Is this problem related to specific iOS version? No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? Prebuilt frameworks

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi @AddyMehra, Thanks for reporting to us. The token is the device token that you receive from APNS or GCM.
