### ISSUE TITLE
EC2: Changing region after describeInstances-Request returned fails

### ISSUE THREAD

**Issue by ssferrazza** [aws/aws-sdk-ios#796]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
** EC2

* In what version of SDK are you facing the problem?
** 2.6.10

* Is the issue limited to Simulators / Actual Devices?
** No, on both types

* Can your problem be resolved if you bump to a higher version of SDK?
** No

* Is this problem related to specific iOS version?
** No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
** Pods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I'm trying to make a request e.g. describeInstances using one region with static credentials. After the request completes I want to make a further request using another region, but this request fails with following error message:

> Error Domain=com.amazonaws.AWSServiceErrorDomain Code=5 "(null)" UserInfo={Code=AuthFailure, Message=AWS was not able to validate the provided access credentials}

I've registered each region like this 
```
var configuration = AWSServiceConfiguration(region: .APNortheast1, credentialsProvider: credentialsProvider)
AWSEC2.register(with: configuration!, forKey: "ap-northeast-1")
```
        
credentialsProvider is a AWSStaticCredentialsProvider. 
To retrieve a Service for a specific region I call
```
let ec2 = AWSEC2(forKey: "ap-northeast-1")
ec2.describeInstances(request!).continueWith(block: {(task) -> Void in
...
})
```

If I make only one call everything works as expected. Calling a further region as described causes the mentioned error.
Could anyone point me to the right direction?

Thanks
Sal

**Comment by kvasukib** [comment]
Hi @ssferrazza,

Thanks for reporting to us and sorry for the delayed reply. I tried the following:

```swift
        let ec2_credentialsProvider: AWSStaticCredentialsProvider = AWSStaticCredentialsProvider(accessKey: "XXX", secretKey: "YYYYYY")
        let ec2_configuration = AWSServiceConfiguration(region: .APNortheast1, credentialsProvider: ec2_credentialsProvider)
        
        // with region: ap-northeast-1
        AWSEC2.register(with: ec2_configuration!, forKey: "ap-northeast-1")
        let request: AWSEC2DescribeInstancesRequest = AWSEC2DescribeInstancesRequest()
        let ec2 = AWSEC2(forKey: "ap-northeast-1")
        
        ec2.describeInstances(request).continueWith(block: {(task: AWSTask) -> Void in
            print (task.error as Any)
            print (task.result as Any)
        })
        
        // with region: ap-northeast-2
        AWSEC2.register(with: ec2_configuration!, forKey: "ap-northeast-2")
        let request_1: AWSEC2DescribeInstancesRequest = AWSEC2DescribeInstancesRequest()
        let ec2_1 = AWSEC2(forKey: "ap-northeast-2")
        
        ec2_1.describeInstances(request_1).continueWith(block: {(task: AWSTask) -> Void in
            print (task.error as Any)
            print (task.result as Any)
        })
```

And I did not see any error. Can you confirm if this is what you meant?

**Comment by ssferrazza** [comment]
Hi @kvasukib ,

Thanks for providing a valuable feedback. I was able to get my example running using your example and I found the cause for the error. The problem is reusing the request parameter in further calls. So I've to define a new AWSEC2DescribeInstancesRequest for every call. Reusing the ec2 client works as expected.
Thanks again pointing me in the right direction
Sal
