### ISSUE TITLE
Check users IAM permissions programmatically

### ISSUE THREAD

**Issue by trondkr** [aws/aws-sdk-ios#797]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS SDK iOS

* In what version of SDK are you facing the problem?
2.6.5

This is not really an issue but rather a question about how I can obtain the permissions of an IAM user. For example, I want to enable Lambda and SNS for a user that is logged into my app using his/hers IAM credentials, but prior to trying to setup these services I want to make sure that he/se has the necessary permissions. Is there a generic way/method that I could use to do this? For example, I want to make sure the user has the permission "AWSLambdaFullAccess" and not just "AWSLambdaReadOnlyAccess".

Any clarification of this would be very helpful. Thanks. Cheers, Trond

**Comment by kvasukib** [comment]
Hi @trondkr, Question: Is there a reason for using IAM for authentication instead of Amazon Cognito (https://aws.amazon.com/cognito/)? Cognito simplifies the App User SignIn flows.

**Comment by trondkr** [comment]
Hi. I enabled the AWS SDK for macos and I am using IAM as login as that seemed the easiest to provide the user access to all of their resources. I understand that if the user logged in using Cognito it would be to a pool predefined with permissions. However, for my app the IAM login seems the best for a user to be able to access their AWS resources.

**Comment by behrooziAWS** [comment]
Although you can get the policies associated with an iam user: https://docs.aws.amazon.com/cli/latest/reference/iam/get-user-policy.html it's probably more effort than it's worth to parse these to determine if someone has access to something.  Your best bet, especially if the user is an AWS Developer is when you make the call and you get an AccessDeniedException to notify them to confirm they have AWSLambdaFullAccess associated with the user/role they have authenticated with.
