### ISSUE TITLE
Dynamodb: "Supplied AttributeValue is empty" error ,though all fields are filled in iOS swift #

### ISSUE THREAD

**Issue by Manan0510** [aws/aws-sdk-ios#798]
func createNews() {
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        
        // Create data object using data models you downloaded from Mobile Hub
        let newsItem: News = News()
        
        newsItem._userId = AWSIdentityManager.default().identityId
        
        newsItem._articleId = "YourArticleId"
        newsItem._title = "YourTitlestring"
        newsItem._author = "YourAuthor"
        newsItem._category = "YourAuthor"
        newsItem._creationDate = NSDate().timeIntervalSince1970 as NSNumber
        
        //Save a new item
        dynamoDbObjectMapper.save(newsItem, completionHandler: {
            (error: Error?) -> Void in
            
            if let error = error {
                print("Amazon DynamoDB Save Error: \(error)")
                return
            }
            print("An item was saved.")
        })
    }

**Comment by kvasukib** [comment]
Hi @Manan0510, 

Thanks for reporting to us. Can you print the _userId from newsItem object to see if its present and valid?

What version of SDK and iOS are you using?

**Comment by Manan0510** [comment]
I resolved today. Actually I made new project for this demo and it uses Swift 4. When I try same code with Swift 3.2 it's working. Please mention in description that Swift 4 is not supported because it's takes my 3 days due to this Swift version issue.

**Comment by kvasukib** [comment]
Thanks, @Manan0510 for pointing it out. Sorry for the inconvenience caused.

**Comment by sagar-turvo** [comment]
It's been 3 months since last comment. Have you guys (AWS Mobile iOS SDK) started supporting `Swift 4`?
