### ISSUE TITLE
AWSS3TransferManager uploadTask returning AWSServiceErrorDomain Error 11.

### ISSUE THREAD

**Issue by hemanth2k13** [aws/aws-sdk-ios#800]
I added AWSS3 2.6.2 using CocoaPods into my Swift project.

when i use AWSS3TransferManager.default().upload(....

i get error like 

**Returning ENOTCONN because protocol has not yet been set up

Error: Error Domain=com.amazonaws.AWSServiceErrorDomain Code=11 "(null)" UserInfo={HostId=qqsnZwwKIe+SwNvRXnTG26ubeGHY04c1EzizozdAMKZLwZjJbcfnSgsfAeEbroNrURu7JNaKjSI=, Message=Access Denied, Code=AccessDenied, RequestId=96AEE3753C6E9190}

The operation couldn’t be completed. (com.amazonaws.AWSServiceErrorDomain error 11.)**

The upload request is 

**}
    ACL = 2;
    body = "file:///var/mobile/Containers/Data/Application/E62A87F3-9626-4C73-A9A7-A0FC18334CFE/Documents/customerSelfee_1515501685676.jpeg";
    bucket = "xxx.xxxxxxxx.com";
    contentType = "image/jpeg";
    currentUploadingPartNumber = 0;
    key = "95248/doc/b2c/customerSelfee_1515501685676.jpeg";
    requestPayer = 0;
    serverSideEncryption = 0;
    state = 0;
    storageClass = 0;
    totalSuccessfullySentPartsDataLength = 0;
}**

**Comment by peteradel** [comment]
I am facing the same issue can you tell me how did you fix it?

**Comment by dharmendra-ios** [comment]
I am facing the same issue can you tell me how did you fix it?

**Comment by rahulvyas** [comment]
I am getting the same error.

**Comment by yiytan92** [comment]
why was this issue closed? I'm getting the same error

**Comment by froggomad** [comment]
The owner closed it, open a new one

**Comment by bdering** [comment]
Any updates on this issue?

**Comment by EddieLukeAtmey** [comment]
it's in the year 2020 and I'm proud to say that I'm facing the same issue.

**Comment by Shamsiddin** [comment]
It's 16.02.2020 and I'm having the same problem

**Comment by palpatim** [comment]
AWSS3TransferManager is deprecated since [2.8.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.8.0). Please use [AWSS3TransferUtility](https://aws-amplify.github.io/docs/sdk/ios/storage) instead.

Also, if you're working on a non-production project, or if your project is not time-sensitive, you can investigate the [Amplify Storage Preview](https://aws-amplify.github.io/docs/ios/storage) we announced in December.
