### ISSUE TITLE
Is it possible to login With Mobile number and OTP in AWS Userpool ?

### ISSUE THREAD

**Issue by Manan0510** [aws/aws-sdk-ios#802]
First user will signup with mobile number,name and email. User will get confirmation code on mobile and if he verify it will successfully register in app.

After Logout from APP.

Now if user wants to login in app he need to enter only mobile number and he receive OTP and by verifying OTP he will logged in.

But How to send OTP to Confirmed status user for Login ??

**Comment by kvasukib** [comment]
Hi @Manan0510, If I understand correctly, are you trying to avoid password and just use 'Phone Number' and 'OTP' as the login mechanism for a registered user? What version of SDK are you using?

**Comment by Manan0510** [comment]
aws version 2.6.0
