### ISSUE TITLE
AWSDynamoDBObjectMapper does not accept Data as a supported type

### ISSUE THREAD

**Issue by mehmetkemalbayer** [aws/aws-sdk-ios#803]
[models.zip](https://github.com/aws/aws-sdk-ios/files/1623108/models.zip)

Hello,
I'm using AWSDynamoDBObjectMapper for Swift. In my model there are attributes like
  ```
  var _relativeAltitudes: Data?
    var _rotations: Data?
```
When I use them with NSKeyedArchiver:
```
sensorData._relativeAltitudes = NSKeyedArchiver.archivedData(withRootObject: movement.altitudes) as Data
            sensorData._rotations = NSKeyedArchiver.archivedData(withRootObject: movement.rotations) as Data
```
I got 
**Amazon DynamoDB Save Error: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=0 "(null)" UserInfo={__type=com.amazon.coral.validate#ValidationException, message=Supplied AttributeValue is empty, must contain exactly one of the supported datatypes}**
error. You can find related classes attached.
Any suggestion? Is there another way to save list of custom objects to dynamo db?
Thank you.

**Comment by kvasukib** [comment]
Hi @mehmetkemalbayer, Are you using Swift 4? What version of SDK and iOS are you using?

**Comment by mehmetkemalbayer** [comment]
Hello @kvasukib 
I'm using Swift 4, iOS 11.1 and AWSDynamoDB 2.6.10.

**Comment by kvasukib** [comment]
Can you try the solution described in #750?

**Comment by mehmetkemalbayer** [comment]
Thank you @kvasukib.
I tried **@objcMembers** previously but not **@objc** for members.
It worked very well.
