### ISSUE TITLE
Is a Cognito Identity Pool Authentication Provider's ServerSideTokenCheck being honored? 

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-sdk-ios#805]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito with integrated User Pools

* In what version of SDK are you facing the problem?
2.6.6

* Is the issue limited to Simulators / Actual Devices?
Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
1) Setup a Cognito User Pool and create a client app. Now you'll have a user pool ID and an app client ID.
2) Create a Cognito Identity Pool. In 'Authentication Providers' --> 'Cognito' tab, enter the user pool ID and the client ID.
3) Turn on 'ServerSideTokenCheck' for that auth provider by using the AWS CLI:
`aws cognito-identity update-identity-pool --identity-pool-id <cognito_identity_pool_id> --identity-pool-name <pool_name> --no-allow-unauthenticated-identities --cognito-identity-providers ProviderName=<user_pool_id>,ClientId=<app_client_id>,ServerSideTokenCheck=true`
4) Verify that ServerSideTokenCheck is on using the AWS CLI command:
`aws cognito-identity describe-identity-pool --identity-pool-id <cognito_identity_pool_id>`
5) In the iOS client code, implement user sign in via the `AWSCognitoIdentityInteractiveAuthenticationDelegate`.
6) Run the app and sign in the user. Now the app has a valid token and refresh token for that user.
7) Sign the user out of the User Pool using the AWS CLI:
`aws cognito-idp admin-user-global-sign-out --user-pool-id <user_pool_id> --username <username>`

After waiting 5+ minutes, we expect the password authentication flow to kick off again via the `AWSCognitoIdentityInteractiveAuthenticationDelegate`, but `startPasswordAuthentication` is never called. Our assumption is based on the fact that the iOS SDK would verify with the user pool (server) that the user isn't signed out before using the refresh token. Is the iOS SDK not honoring the ServerSideTokenCheck attribute on the Cognito Identity Pool Authentication Provider (i.e. my user pool)?

This is important to us for 2 reasons:
1) In the case of an abusive user, we would need to sign them out everywhere (so that their refresh token wouldn't work) and also disable them in the User Pool so that they cannot sign in from scratch again.
2) We are trying to replicate refresh token expiry so that we can ensure that our code handles this situation (we have several beta users currently stuck in this bad state). If the SDK doesn't support ServerSideTokenCheck, how else can we hack the expiry of the refresh token to validate that our code handles this situation?

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kalpitad** [comment]
Here is the AWS JS SDK issue where this need was first brought up and implemented by the Cognito team: https://github.com/aws/amazon-cognito-identity-js/issues/21

**Comment by offero** [comment]
How do you specify multiple --cognito-identity-providers ?
