### ISSUE TITLE
Error Handling Best Practices

### ISSUE THREAD

**Issue by CareerFairPlus** [aws/aws-sdk-ios#807]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

S3

* In what version of SDK are you facing the problem?

2.4.10

* Is the issue limited to Simulators / Actual Devices?

Both.

* Can your problem be resolved if you bump to a higher version of SDK?

Unknown.

* Is this problem related to specific iOS version?

No.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I'm not having an issue, but more a documentation/best practices question. I'm trying to implement effective error handling on the response from an `[AWSS3 getObject:]` call and I haven't been able to find any guidance on best practices for error handling. So far the only way that I've found to capture the errors that I need is to look at the `Code` value in the `userInfo` dictionary passed back in the Task's error property, but that seems fragile.

Any guidance or documentation you could provide would be very helpful.

Thanks!

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
The easiest way would be to check for error domain  `AWSS3ErrorDomain` and check specific type of error which you want to handle. Like `NoSuchKeyError` would be for missing file/ invalid filename. If the error domain is Cognito, its related to credentials being expired.
