### ISSUE TITLE
[Feature Request] Gzip Body of Kinesis PutRecords

### ISSUE THREAD

**Issue by tlubz** [aws/aws-sdk-ios#808]
It would be nice to be able to gzip the entire body of Kinesis PutRecords calls when using KinesisRecorder to save network overhead and battery. This feature seems to be available on the Android sdk (https://aws.amazon.com/releasenotes/release-aws-sdk-for-android-2-2-2/).

To verify it is not gzipping, follow the ios aws sdk kinesis integration example in the documentation. Put a breakpoint in `AWSURLRequestSerialization.m` on line 120, after `request.HTTPBody` has been set.

Save a bunch of records to a kinesis recorder, and use `submitAllRecords` to submit them to the stream. You can verify whether the body is gzipped by inspecting the request body and the Content-Encoding header.

Actual behavior: Kinesis PutRecords request body is not encoded as gzip, and the Content-Encoding header is not set.
Desired behavior: Kinesis PutRecords request body should be encoded as gzip, and the Content-Encoding header should be set to gzip

* What service are you using?
Kinesis / KinesisRecorder

* In what version of SDK are you facing the problem?
2.6.9

* Is the issue limited to Simulators / Actual Devices?
both, afaik

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
Not sure

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

**Comment by kvasukib** [comment]
Hi @tlubz,

Thank you for reporting to us. We will take a look at it. We will notify here when this feature is released.
