### ISSUE TITLE
AWSSignature签名版本问题

### ISSUE THREAD

**Issue by ysmilel** [aws/aws-sdk-ios#813]
请问有S3的V3版本签名的SDK吗？急需！！！

**Comment by kredden** [comment]
Translated to English:
Is there a S3 version of the S3 signature SDK? urgent need

Can you be more specific about what you are trying to do?  I'm using Google Translate so not sure if the question is translated correctly. (你能更具体地说明你正在做什么？我正在使用Google翻译，因此不确定问题是否已正确翻译).

Regards,
Kevin

**Comment by ysmilel** [comment]
My tool does not support AWS S3 SignatureV4 and only supports V3 version signatures.

**Comment by minbi** [comment]
We do not support V3 signatures.
