### ISSUE TITLE
Dynamodb - save function doesn't work

### ISSUE THREAD

**Issue by DavidPhysics** [aws/aws-sdk-ios#817]
##Dynamodb - save function

I uses the AWS hub mobile service to connect the dynamodb database serivce, but I can't execute the save function of the dynamodb service in iOS app by objective C. I try to use the Cognito service to connect the dynamodb database service to run the save function of the dynamodb, but it doesn't work. Update, delete and load function also can't work. Could someone tell me where is wrong?

* What service are you using?
  AWS hub mobile service, AWS dynamodb service, AWS cognito service.
* In what version of SDK are you facing the problem?
  AWS SDK 2.6.10
  CocoaPods 1.4.0
  Xcode version 8.3.3 (8E3004b)
--------------------------
ViewController.m file

#import "ViewController.h"
#import "Books.h"
@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (IBAction)Increased:(id)sender {
    AWSDynamoDBObjectMapper *dynamoDBObjectMapper = [AWSDynamoDBObjectMapper defaultDynamoDBObjectMapper];
    
    Books *myBook =[Books new];

    myBook._ISBN=self.BookISBNBox.text;
    myBook._Title=self.BookNameBox.text;
    myBook._Author=self.BookAuthorBox.text;

    [[dynamoDBObjectMapper save:myBook] continueWithSuccessBlock:^id _Nullable(AWSTask * task) {
        if(task.error)
        {
            NSLog(@"The request failed. Error:[%@]",task.error);
        }
        else
        {
            NSLog(@"OK! Error:[%@]",task.error);
        }
        return nil;
    }];
}
@end

------------
Books.m files

#import "Books.h"

@implementation Books
+(NSString *)dynamoDBTableName {
 return @"Books";
}

+(NSString *)hashKeyAttribute {
    return @"_ISBN";
}

+(NSDictionary *)JSONKeyPathsByPropertyKey{
    return @{
             @"_ISBN":@"ISBN",
             @"_Title":@"Title",
             @"_Author":@"Author",
             };
}
@end

<img width="1280" alt="screen shot 2018-01-22 at 5 12 35 pm" src="https://user-images.githubusercontent.com/25798404/35213126-81f1c3e8-ff97-11e7-8cc2-fc07c760d258.png">

**Comment by minbi** [comment]
Hi @DavidPhysics ,

Can you add breakpoints on line 41 and 45 to see what the error being returned is?

**Comment by DavidPhysics** [comment]
@minbi When I execute my iOS app projects, the code doesn't run the line 45 and the line 41. It only runs the line 38, then it misses other codes. I have checked the program logic which is correct so I don't know where is wrongs. No any messages that tells me where is wrongs!

**Comment by DavidPhysics** [comment]
When I use the dynamodb service, do I must modify the Info.plist file of iOS project?

**Comment by rohandubal** [comment]
You are using the `continueWithSuccess` block. To catch the errors, you will have to use `continueWith` block. `continueWithSuccess` gets called only if the call successfully goes through. To debug, you will have to use `continueWith` block.

**Comment by DavidPhysics** [comment]
@rohandubal  
Thank you giving me answer. I have found out problem. :)

**Comment by kvasukib** [comment]
Thank you @DavidPhysics for confirming. Please feel free to re-open if you face any issue.
