### ISSUE TITLE
Does S3 aws-sdk-ios support client-side encryption？

### ISSUE THREAD

**Issue by EricCheungSCUT** [aws/aws-sdk-ios#819]
I found that this feature is available on other S3 SDKs, like SDK for Android. But I can't found any client-side encryption related information in aws-sdk-ios. Does aws-sdk-ios support client-side encryption？If the answer is no, is there any plans to support it?

**Comment by minbi** [comment]
There is no integrated support for client side encryption. You may use the KMS SDK to encrypt files before using the S3 SDK to upload.

This support is not currently in the roadmap. We will take this as a feature request.

**Comment by drummeric** [comment]
Could you please provide an example or any additional guidance on how to use the KMS SDK to encrypt the files?

We were looking to use the [AWS Encryption SDK](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html), but it doesn't seem like that's supported in Swift.
