### ISSUE TITLE
This is more of a question than an issue.

### ISSUE THREAD

**Issue by balajikondalrayal** [aws/aws-sdk-ios#820]
We are trying to consume a 'AWS API Gateway' API from iOS (using Swift) that needs signature V4 signing. What are the available approaches? 

Do we have to use the generated SDK for the API from the API Gateway console? Is this the only approach?

OR

Can we sign and access the API by using 'only' the AWSAPIGateway.framework? (i.e.) without the generated SDK.

**Comment by minbi** [comment]
@balajikondalrayal ,

You'll need to write your own marshallers and unmarshallers, but the signing is available through the AWSAPIGateway.framework.
