### ISSUE TITLE
Lambda uses unauth credentials after a user sign in

### ISSUE THREAD

**Issue by vysotsky** [aws/aws-sdk-ios#822]
## To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito, IAM, Lambda, S3

* In what version of SDK are you facing the problem?
2.6.10 

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hi! I've faced issue when Lambda cannot get credentials set in the AWSCognitoIdentityUserPool after a user sign in.

Here is my configuration

```swift
  let credentialsProvider = AWSCognitoCredentialsProvider(
      regionType: environment.region,
      identityPoolId: environment.identityPoolId,
      identityProviderManager: nil
    )
    let serviceConfiguration = AWSServiceConfiguration(
      region: environment.region,
      credentialsProvider: credentialsProvider
    )
    let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(
      clientId: environment.appId,
      clientSecret: nil,
      poolId: environment.userPoolId
    )
    AWSCognitoIdentityUserPool.register(
      with: serviceConfiguration,
      userPoolConfiguration: userPoolConfiguration,
      forKey: configurationKey
    )
    let userPool = AWSCognitoIdentityUserPool(forKey: configurationKey)
    userPool.delegate = self
    AWSLambdaInvoker.register(with: serviceConfiguration!, forKey: configurationKey)

    AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration
```

It sets unath role for Lambda.

Then I try to sign user in by using the following:

```swift
 let user = AWSCognitoIdentityUserPool(forKey: configurationKey).getUser()
    return Promise(resolvers: { resolve, reject in
      user.getSession(username, password: password, validationData: nil)
        .continueWith(block: { task -> Any? in
          if let error = task.error {
            let message = (error as NSError).userInfo["message"] as? String
            return reject(AWSError.SignIn.sessionError(message))
          }
          guard let idToken = task.result?.idToken?.tokenString else {
            return reject(AWSError.SignIn.noTokenProvided)
          }
          guard let identityId = user.username else {
            return reject(AWSError.SignIn.noIdentityIdProvided)
          }
          return resolve((idToken: idToken, identityId: identityId))
        })
    })
```

But Lambda still cannot perform any action which needs the user to be authorized. 
When I was using React Native and your JS SDK, it was enough to set idToken like the following

```javascript
    Config.credentials = new CognitoIdentityCredentials({
      IdentityPoolId: appConfig.identityPoolId,
      Logins: {
        [`cognito-idp.${appConfig.region}.amazonaws.com/${appConfig.userPoolId}`]: token
      }
    }, {
      region: appConfig.region
    });
```
where token - idToken which we got in the native code.

I also tried to implement custom AWSIdentityProviderManager where I set `logins` like in the JS code. But it didn't work.
Can you please have a look and tell me what I'm missing? Seems like there is no example provided to make it clear or I just didn't find it. Thanks!

**Comment by rohandubal** [comment]
Hello,

You will have to provide an identityManager here:

```
 let credentialsProvider = AWSCognitoCredentialsProvider(
      regionType: environment.region,
      identityPoolId: environment.identityPoolId,
      identityProviderManager: nil
    )
```

which manages the user pools token and federates it with Cognito Identity to use the auth role. 

You can also use Identity Manager which is a high level abstraction to achieve this. The documentation for same is specified here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html 

Thanks,
Rohan
