### ISSUE TITLE
AWSAPIGateway framework for Swift limitation - App Crashing while parsing JSON 64-bit integer

### ISSUE THREAD

**Issue by balajikondalrayal** [aws/aws-sdk-ios#824]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSAPIGateway 

* In what version of SDK are you facing the problem?
2.6.11

* Is the issue limited to Simulators / Actual Devices?
No, happens in both simulator and an actual device.

* Can your problem be resolved if you bump to a higher version of SDK?
Using the latest version already.

* Is this problem related to specific iOS version?
No.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1. Integrated the AWSAPIGateway through Cocoapods.
2. Later, imported the source files generated in API Gateway console, to consume specific APIs generated from the console.
3. After integrating the framework, App is crashing while parsing JSON response of another REST API (which was NOT developed from the API Gateway console). Crash happens at the step, where the app tries to convert a JSON integer into Int in Swift. 
4. If the AWSAPIGateway framework is uninstalled, the app works fine.

I understand from this (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html) document that, API Gateway does not support Int32 or Int64 types. But why does the SDK affect parsing a JSON response of another REST API which is not related to API Gateway at all?

**Comment by minbi** [comment]
Hi @balajikondalrayal ,

Are you saying that integrating the AWSAPIGateway framework is interfering with network calls that are not made through an API Gateway client?

> App is crashing while parsing JSON response of another REST API (which was NOT developed from the API Gateway console)

**Comment by balajikondalrayal** [comment]
Yes. That's the behaviour we are observing.

Once we undo the integration of the framework, the REST API call works normally.

Can you confirm if this is an issue with the latest version of the framework? Do you recommend integrating an earlier version of the framework?

**Comment by balajikondalrayal** [comment]
Hi Team, 

Any update on this yet? Are you able to reproduce? Do you want any more information?
