### ISSUE TITLE
Amazon SES : Request timing out with attachments

### ISSUE THREAD

**Issue by sleman** [aws/aws-sdk-ios#825]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Amazon SES

* In what version of SDK are you facing the problem?
2.6.11

* Is the issue limited to Simulators / Actual Devices?
Actual Device

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
Not sure

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Trying to send a raw e-mail with an attachment that is an mp4 file. The e-mail gets sent and received however I get a timeout error in `sendRawEmail` response. If I send without the attachment, response works fine. If I send with a JPG attachment, everything works fine as well.

Here's a sample raw e-mail I'm sending.

[sample-email2.txt](https://github.com/aws/aws-sdk-ios/files/1700261/sample-email2.txt)

**Comment by sleman** [comment]
Found out that issue was caused by not having a line break after `Content-Transfer-Encoding: base64` and before the base64 encoded attachment. This drove me nuts for a day and Amazon should really not return a timeout on their end for this.

**Comment by kvasukib** [comment]
Thank you @sleman for reporting to us. We will look into improving it.
