### ISSUE TITLE
Crash at line 303 in AWSService.m for iOS 11

### ISSUE THREAD

**Issue by shashiLBB** [aws/aws-sdk-ios#828]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
I am using **AWSCognitoCredentialsProvider** 

> - (instancetype)initWithRegionType:(AWSRegionType)regionType
                    identityPoolId:(NSString *)identityPoolId

* In what version of SDK are you facing the problem?
`Using AWSCognito (2.4.12)
Using AWSCognitoIdentityProvider (2.4.12)
Using AWSCore (2.4.12)
Using AWSKinesis (2.4.12)`
* Is the issue limited to Simulators / Actual Devices?
Actual Devices 

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific iOS version?
`iOS 11`
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you @shashiLBB for reporting to us. Sorry for the inconvenience caused. Can you post the code snippet and include the exception and stacktrace here? That would be helpful for us in debugging.

**Comment by shashiLBB** [comment]
> NSString *region = "ap-south-1";
AWSRegionType defaultRegionType = [region aws_regionTypeValue];
    NSLog(@"defaultRegionType %ld", (long)defaultRegionType);
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]
                                                          initWithRegionType: defaultRegionType
                                                          identityPoolId:poolID];
>


`Crash is : 
Fatal Exception: NSInternalInconsistencyException
Invalid region type.
`

**Comment by shashiLBB** [comment]
defaultRegionType = 11 
It's crashing only on iOS 11, pls check

**Comment by kvasukib** [comment]
Thank you @shashiLBB for posting the code snippet.

`Code:`

```
NSString *region = @"ap-south-1";
    AWSRegionType defaultRegionType = [region aws_regionTypeValue];
    NSLog(@"defaultRegionType %ld", (long)defaultRegionType);
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]
                                                          initWithRegionType: defaultRegionType
                                                          identityPoolId:@"ap-south-1:**********"];
    NSLog(credentialsProvider);
}
```

**Debugger output:**

```
(lldb) n
(lldb) n
(lldb) po defaultRegionType
AWSRegionAPSouth1

(lldb) n
2018-02-09 10:42:16.104421-0800 PodCheckSampleApp[11517:62850] defaultRegionType 12
(lldb) n
(lldb) n
(lldb) n
(lldb) po credentialsProvider
<AWSCognitoCredentialsProvider: 0x6040000abe80>

```

I ran it on iPhone 8 Plus running latest iOS version and I don't see a crash in versions 2.4.12 ad well as 2.6.12.

What version of XCode are you using? Are you running on simulators?
