### ISSUE TITLE
AWS SNS, error  subscribing to a topic

### ISSUE THREAD

**Issue by guna** [aws/aws-sdk-ios#830]
Hello,  my iOS client is trying to subscribe to a topic but I get this error:

Error subscribing: Optional(Error Domain=com.amazonaws.AWSSNSErrorDomain Code=1 "(null)" UserInfo={Type=Sender, Message=User: arn:aws:sts::612274203562:assumed-role/Cognito_TipsAppAuth_Role/CognitoIdentityCredentials is not authorized to perform: SNS:Subscribe on resource: arn:aws:sns:us-west-2:612274203562:XXXX, Code=AuthorizationError, __text=(
    "\n    ",
    "\n    ",
    "\n    ",
    "\n  "
)})

I have a policy to allow subscribe/unsubscribe to a topic and have attached the policy to the role. Any help is appreciated. Thanks.

**Comment by rohandubal** [comment]
Hello @guna 

Have you attached the permissions to both the Auth and Un-Auth roles? I see the error being raised for Auth role. 

Could you also mention the policy you have attached to Auth role?

Thanks,
Rohan

**Comment by guna** [comment]
Hi @rohandubal - We are only using Auth role and we did attach the right policy to Auth role.

**Comment by guna** [comment]
I removed the MultiFactorAuthPresent condition and also added permission for ConfirmSubscription and  I am able to successfully subscribe and receive notifications. But I still get this error message on my console?:

Subscribed succesfully
Error subscribing: Optional(Error Domain=com.amazonaws.AWSSNSErrorDomain Code=4 "(null)" UserInfo={Type=Sender, Message=Invalid token, Code=InvalidParameter, __text=(
    "\n    ",
    "\n    ",
    "\n    ",
    "\n  "
)})

**Comment by rohandubal** [comment]
@behrooziAWS  could you share some insight on policy for MFA requirement?

**Comment by guna** [comment]
Hello Rohan - I have a question using AWS Pinpoint. Currently I have
working AWS backend in N-California region, with UserPools in Oregon
Region. Now I would like to start using AWS Pinpoint that is available only
in N.Virginia region. When I create a project into Pinpoint, it
automatically uses UserPool in N.Virginia region. How can I do this with
two userPools, as my active userPool is in Oregon region.

Any help is appreciated.

Thanks
guna
