### ISSUE TITLE
Verify your bundle identifier - Prebuilt frameworks install

### ISSUE THREAD

**Issue by Vi-dot** [aws/aws-sdk-ios#831]
I'm following the **Prebuilt frameworks** install steps.
Then I downloaded package **aws-sdk-ios-2.zip**

Issue is happening when I want to send the application to App Store (with "Upload to App Store" or "Application Loader").

The frameworks are embedded and I added the Script Phase to strip frameworks.

But at the end I still have this error : **No suitable application records were found. Verify your bundle identifier 'com.amazonaws.sdk.ios.AWSCognitoIdentityProviderASF' is correct.**

I tried to add a Wildcard App Id "com.amazonaws.sdk.ios.*", but it doesn't work.

Anyone have any thoughts on this ?
Thanks

**Comment by joelkraut** [comment]
@Vi-dot this is not an AWS issue, it's Apple. What they're saying is that you haven't created an application in iTunes Connect called "com.amazonaws.sdk…". That's probably not what you want, either, unless you work at Amazon. Sign in to itunesconnect.apple.com, create a new application record, then set your project's bundle identifier to the match.
