### ISSUE TITLE
AWSSNS: Too many symbol files issue after iTunes Delivery process

### ISSUE THREAD

**Issue by Incorporalis** [aws/aws-sdk-ios#832]
Hello! We have a problem with using AWSSNS (+AWSCore) as prebuilt frameworks in our project.

It is the latest version of the SDK. 2.6.12 Mobile SDK

It occurs only if we upload a new build to iTunes Connect, it doesn't bring any problem with publishing, just a warning

It seems like dsym files for sliced binaries (with run script strip-frameworks.sh).

``` 
Dear developer,

We have discovered one or more issues with your recent delivery for "***". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Too many symbol files - These symbols have no corresponding slice in any binary [2039709E-6371-3902-A8A6-C05DFCD1DA96.symbols, F83335A0-626F-3E3C-AC42-FAB4248B9FE4.symbols]

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,
The App Store team

**Comment by rohandubal** [comment]
Hello,

Do you follow the process of stripping symbols as specified by Carthage?

Thanks,
Rohan

**Comment by Incorporalis** [comment]
Hello,

@rohandubal Yes, we use carthage with stripping symbols, but AWS is installed as prebuilt framework, so carthage doesn't do anything with our embed frameworks. If it makes any sense. 

Ivan

**Comment by rohandubal** [comment]
@Incorporalis 

Have you tried doing a force build on your client side? Does it have the same impact? As a minimum comparison, you could check the size of binaries.
