### ISSUE TITLE
API Gateway throws an error on Post request with body encoded with Codable

### ISSUE THREAD

**Issue by Stan-Ost** [aws/aws-sdk-ios#834]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS API Gateway

* In what version of SDK are you facing the problem?
2.6.12 and below

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No, it persists across all versions

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I have a POST request with the following class: 

class Event: Codable {
     
}

Body for request:
`let data = try? encoder.encode(event) as? Any`

Error details:

Class: AWSMTLJSONAdapter.h
Method: `- (id)initWithModel:(AWSMTLModel<AWSMTLJSONSerializing> *)model `
Line: 230  `_JSONKeyPathsByPropertyKey = [[model.class JSONKeyPathsByPropertyKey] copy];`

**Comment by rohandubal** [comment]
Hello,

Could you provide a code snippet of how you are using the SDK for invocation? Do you use the generated API Gateway SDK?

Thanks
Rohan

**Comment by Stan-Ost** [comment]
I call directly `client.invokeHTTPRequest:` method to return the request, and than use `.continieWithTask()`.


``` swift
    // MARK: Private methods
    
    /// Create a request for provided resource. This method can return Stubbed data if needed.
    ///
    /// - Parameter target: request target
    /// - Returns: AWSTask
    fileprivate func request(target: Target) -> AWSTask<AnyObject> {
        if testMode {
            return AWSTask(result: target.sampleData as AnyObject)
        } else {
            return  client.invokeHTTPRequest(target.httpMethod.rawValue,
                                             urlString: target.endpointURL,
                                             pathParameters: target.pathParameters,
                                             queryParameters: target.queryParameters,
                                             headerParameters: target.headerParameters,
                                             body: target.body,
                                             responseClass: nil)
        }
    }

```
Is there any specific way to form Body from Codable? `invokeHTTPRequest` uses `Any`, not `Data`.

**Comment by rohandubal** [comment]
No, there is no direct way to use Codable. Could you try integrating with the generated SDK and then passing the specified parameters?

**Comment by Stan-Ost** [comment]
I created an API based on how it's structured in the generated SDK. Here is the example from generated file:
```swift
return self.invokeHTTPRequest("POST", urlString: "/message", pathParameters: pathParameters, queryParameters: queryParameters, headerParameters: headerParameters, body: nil, responseClass: Empty.self) as! AWSTask<Empty>
```


Body is `nil` here, but I have a body to pass. So what format does it support? `Data`?  Or `[String:Any]`?

**Comment by rohandubal** [comment]
You should be able to use either a string body as used [here](https://github.com/aws/aws-sdk-ios/blob/a50e487cc71fc9345bdd55b8bdfe0eb08c7250ac/AWSAPIGatewayTests/AWSAPIGatewayInvokeTest.swift#L65).

You could also use a dictionary like shown [here](https://github.com/aws/aws-sdk-ios/blob/a50e487cc71fc9345bdd55b8bdfe0eb08c7250ac/AWSAPIGatewayTests/AWSAPIGatewayInvokeTest.swift#L154).

You can use a raw body as specified [here](https://github.com/aws/aws-sdk-ios/blob/a50e487cc71fc9345bdd55b8bdfe0eb08c7250ac/AWSAPIGatewayTests/AWSAPIGatewayInvokeTest.swift#L94).

Thanks,
Rohan
