### ISSUE TITLE
AWSAuthUIViewController sign-in is covered by keyboard

### ISSUE THREAD

**Issue by afbeaver** [aws/aws-sdk-ios#835]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSAuthUIViewController

* In what version of SDK are you facing the problem?
2.6.12

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
When using AWSAuthUIViewController, the iOS on-
screen keyboard covers the sign-in username/password textfields.  The screen does not adjust to the keyboard.  Also, on the iphone 5s smaller screen, the Facebook and google buttons are off the screen to the bottom and you cannot access them. 

<img width="379" alt="screen shot 2018-02-16 at 5 05 57 pm" src="https://user-images.githubusercontent.com/560462/36331411-bda7d1f4-133b-11e8-80cf-8eaa624dff6d.png">

**Comment by kvasukib** [comment]
Hi @afbeaver, Thank you for reporting to us. Sorry for the inconvenience caused. Are you using a custom AuthUIConfiguration? If so, can you post the code snippet here?

**Comment by afbeaver** [comment]
I have done some more testing.  The default screen without any config is ok.  When you use a custom image or remove the facebook or google sign-in, the textfield ends up below the keyboard.  Here is a custom config example:
`let config = AWSAuthUIConfiguration()`
`config.enableUserPoolsUI = true`
`config.backgroundColor = UIColor.blue`
`config.isBackgroundColorFullScreen = false`
`config.canCancel = true`
`config.logoImage = UIImage(named: "testImage")`
`config.addSignInButtonView(class: AWSFacebookSignInButton.self)`

Also, the same problem exists on the 'Sign Up' page even with the default config:
<img width="379" alt="screen shot 2018-02-17 at 11 22 57 am" src="https://user-images.githubusercontent.com/560462/36343084-a098a896-13d5-11e8-8855-ff6a7c533a58.png">

**Comment by kvasukib** [comment]
Hi @afbeaver This has been fixed with 2.6.14 (https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#2614). Please upgrade, check and let us know if it fixes the issue.

**Comment by njcme** [comment]
Your fix in #2614 pushes the input fields off the top of the screen - I am not sure this is an improvement. For example - the sign-in screen when typing the username:
![image](https://user-images.githubusercontent.com/25744035/38166637-00030cb4-34f5-11e8-898c-1698f4f090d1.png)

**Comment by rohandubal** [comment]
Hello,

Does this happen on real devices as well or just the simulator? Which simulator are you using?

Thanks,
Rohan

**Comment by njcme** [comment]
This happens on real devices - in my case an iPhone X running 11.3. When the keyboard appears on the sign-in screen the view is pushed up so far the fields are no longer visible. This is also with the default sign in screen not a custom one.
It does not happen on my simulator (iPhone 8) as the keyboard does not appear.

**Comment by mciccarello** [comment]
Same here, on my iPhone 7. The cure is worse than the disease. Please fix this!
![disease](https://user-images.githubusercontent.com/75937/38323802-31d8941a-37f3-11e8-8da4-202d4dc9f35f.png)

**Comment by rohandubal** [comment]
Hello,

This issue is fixed with the latest SDK release (2.6.17)

Thanks,
Rohan
