### ISSUE TITLE
AWSTranscribe Framework?

### ISSUE THREAD

**Issue by waynemock** [aws/aws-sdk-ios#837]
Hi aws-sdk-ios team!

I'm starting a new macOS project using the AWS Transcribe preview. This SDK is great, but missing a framework for Transcribe. Just wondering if one is in the works. I've started developing my own, and would love to contribute once it's ready if that make sense. I'm following the S3 framework as a model for how to structure it.

I've ported this SDK over to macOS, and it seems to be working well. I have a fork of the SDK here with the changes if anyone's interested in where I'm headed with it: [AWS macOS SDK](https://github.com/waynemock/aws-sdk-ios). I consider it a WIP at this point, as I've only have a couple of days work into it. My AWS Transcribe frame work will live here for now too.

Thx,
Wayne

**Comment by kvasukib** [comment]
#845 Linking the PR here.

**Comment by waynemock** [comment]
Going to mark as answered since I’m developing the addition to the SDK myself.
