### ISSUE TITLE
enhancement - Need example  for adminLinkProviderForUser for facebook / google

### ISSUE THREAD

**Issue by johndpope** [aws/aws-sdk-ios#838]
I want to be able to link a new facebook / google login to an existing user account.
It's not clear how to do this. yes - I've seen the docs and header
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminLinkProviderForUser-property

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
social identity pools

* In what version of SDK are you facing the problem?
latest
n/a
* Is the issue limited to Simulators / Actual Devices?
n/a
* Can your problem be resolved if you bump to a higher version of SDK?
n/a
* Is this problem related to specific iOS version?
no
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
n/a
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
n/a

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforios/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/). 

https://github.com/aws/amazon-cognito-identity-js/issues/560 #

**Comment by minbi** [comment]
Hi @johndpope ,

Based on the Javascript issue [linked](https://github.com/aws/amazon-cognito-identity-js/issues/560), the same API could be called from the iOS' client. I have not implemented this code, but the call would be something along these lines.

The Facebook token can be extracted after a login-in process separate from the Cognito UserPools SDK by using `[FBSDKAccessToken currentAccessToken]`. The token is parsed for the Facebook user id.

Then, using the Cognito UserPools token, the Cognito user id could be acquired.

The linking called could be made after the above two pieces of information are acquired.

The method call:
https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderService.h#L500

The method call's input:
https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/CognitoIdentityProvider/AWSCognitoIdentityProviderModel.h#L1084
