### ISSUE TITLE
enhancement - mobilehub login via amazon - email / password

### ISSUE THREAD

**Issue by johndpope** [aws/aws-sdk-ios#839]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
mobilehub

* In what version of SDK are you facing the problem?
latest

website should allow user to be able to select amazon login as a social login
![screen shot 2018-02-26 at 11 54 17 am](https://user-images.githubusercontent.com/289994/36683584-f3882ea6-1aeb-11e8-8975-31c4c3463d6a.png)

**Comment by johndpope** [comment]
if !AWSSignInManager.sharedInstance().isLoggedIn {
            let config = AWSAuthUIConfiguration()
            config.enableUserPoolsUI = true
            config.addSignInButtonView(class: AWSGoogleSignInButton.self)
            config.addSignInButtonView(class: AWSFacebookSignInButton.self)


I want to be able to plugin amazon

       config.addSignInButtonView(class: AWSAmazonSignInButton.self)

**Comment by johndpope** [comment]
these repos seems to be only swift code using amazon login.

![screen shot 2018-02-26 at 12 11 21 pm](https://user-images.githubusercontent.com/289994/36684394-2c84f64c-1aee-11e8-9b96-d94eef08dc76.png)


https://github.com/LuAndreCast/amazonAlexaLogin/blob/038a9dbd13b7e0e856ee53d9162300b8fb6da220/Library%20Version%202/Alexa%20and%20Amazon%20Login/SWIFT/AmazonLoginSwift/amazon%20login/AmazonAuthorizationRequest.swift


https://github.com/indraShan/rubber_duck_ios_swamphacks2018/blob/c4ab0f2c4f18f7c98a4bce0781688a94fc120614/RubberDuck/RubberDuck/ViewController.swift

following the rabbit hole down - the sdk for LoginWithAmazonSample seems completely outdated / only supporting objective-c.

<img width="1363" alt="screen shot 2018-02-26 at 12 16 36 pm" src="https://user-images.githubusercontent.com/289994/36684625-ed602260-1aee-11e8-9335-e197527e07d2.png">


also - not sure why ios app is not supported out of the box on amazon developer console ? only android / mac / web
https://developer.amazon.com/home.html

<img width="1309" alt="screen shot 2018-02-26 at 12 15 57 pm" src="https://user-images.githubusercontent.com/289994/36684599-d418c96a-1aee-11e8-8662-ddb374abb615.png">

**Comment by johndpope** [comment]
Adding Login with Amazon as an Identity Provider
Create an app in the Login With Amazon App Console at http://login.amazon.com/manageApps. Note the client ID and client secret (shown in the Web Settings section).

Sign in to the Amazon Cognito console. You may be prompted for your AWS credentials.

In the navigation pane, choose Manage your User Pools, and choose the user pool you want to edit.

Choose Identity providers from the Federation console page.

Choose Amazon.

For the Amazon app ID, enter the app ID that you received when you created your Amazon app.

For App secret, enter the app secret that you received when you created your Amazon app.

For Authorize scopes, enter the names of the Login with Amazon scopes that you want to map to user pool attributes, separated by spaces, for example, profile postal_code.

Choose Update Amazon.

Add your user pool domain URL https://your-user-pool-domain/oauth2/idpresponse to the Login with Amazon app's Allowed Return URLs. This ensures that Login with Amazon will accept the redirect URL supplied by Amazon Cognito when it authenticates users. For more information, see http://login.amazon.com/website.


https://sellercentral.amazon.com/gp/homepage.html

<img width="1379" alt="screen shot 2018-02-26 at 3 42 22 pm" src="https://user-images.githubusercontent.com/289994/36694217-ac2379e2-1b0b-11e8-8e18-1a7dee94d3e4.png">

**Comment by johndpope** [comment]
persevering with instructions from above -  I can add and see amazon social login - it has client secret only for web app though. This obviously is not integrated with mobilehub yet. 

![screen shot 2018-02-26 at 3 45 14 pm](https://user-images.githubusercontent.com/289994/36694413-5761d6a0-1b0c-11e8-9e18-aab7a774744b.png)
<img width="905" alt="screen shot 2018-02-26 at 3 47 50 pm" src="https://user-images.githubusercontent.com/289994/36694452-7740f7bc-1b0c-11e8-9549-708c44d0a39b.png">

**Comment by johndpope** [comment]
found this login via amazon which exposes ios api key / secret 

<img width="1308" alt="screen shot 2018-02-27 at 11 08 29 am" src="https://user-images.githubusercontent.com/289994/36739695-9347e838-1bae-11e8-9ba5-c7c055c4026b.png">

**Comment by johndpope** [comment]
so this test app - https://github.com/grimlockrocks/login-with-amazon-swift3-sample-app
successfully logs in with ios in swift. but there's no integration with cognito

import **LoginWithAmazon**

need clarification on how to integrate with awscognitoidentity provider.

**Comment by minbi** [comment]
Hi @johndpope ,

You should be able to set the token shown in this example:
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon.html#set-up-amazon-1.ios-swift

```swift
func requestDidSucceed(apiResult: APIResult!) {
    if apiResult.api == API.AuthorizeUser {
        AIMobileLib.getAccessTokenForScopes(["profile"], withOverrideParams: nil, delegate: self)
    } else if apiResult.api == API.GetAccessToken {
        credentialsProvider.logins = [AWSCognitoLoginProviderKey.LoginWithAmazon.rawValue: apiResult.result]
    }
}
```

**Comment by johndpope** [comment]
will try and post update here in due course and close ticket.
