### ISSUE TITLE
how to set pathstyle  and signature version in AWSServiceConfiguration

### ISSUE THREAD

**Issue by joke-lee** [aws/aws-sdk-ios#843]
i try to use ios sdk for ceph rgw, and how to set pathstyle  and signature version

we can set signature version and style in boto3

```
s3_client = session.client(
    's3',
    endpoint_url=url,
    use_ssl = False,
    config = boto3.session.Config(
         signature_version = 's3v4',
         addressing_style = 'path'
    )
)
```
so how to set pathstyle and signature version in ios sdk(swift and object-c)

**Comment by joke-lee** [comment]
hi @kredden, would you mind tell me how to set signature version and addressing style?

**Comment by minbi** [comment]
AWS iOS SDK does not expose this option and uses sigv4 for most of the services.

**Comment by joke-lee** [comment]
hi @minbi  do you know which one AWS iOS SDK use, path style or vitual host style? we have a domain only support pathstyle for ssl,(example: https://eos.cloud.com/bucketname)  ,so it mean i can not user iOS SDK?

**Comment by minbi** [comment]
@joke-lee The S3 code is using path style, please check to confirm for your specific method calls.

Example delete using path style: https://github.com/aws/aws-sdk-ios/blob/master/AWSS3/AWSS3Service.m#L211

**Comment by joke-lee** [comment]
hi @minbi @kredden

```
 AWSStaticCredentialsProvider *credentialsProvider = [[AWSStaticCredentialsProvider alloc] initWithAccessKey: @"accesskey" secretKey : @"secretkey"];
    AWSEndpoint *customEndpoint = [[AWSEndpoint alloc]initWithURLString:@"https://zgp1z1.ecloud.today"];
   
    AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc]initWithRegion:AWSRegionUSEast1 endpoint:customEndpoint credentialsProvider:credentialsProvider];
    
    AWSSignatureV2Signer *signer = [[AWSSignatureV2Signer alloc] initWithCredentialsProvider:credentialsProvider
                                                                              endpoint:customEndpoint];
    
    AWSNetworkingRequestInterceptor *baseInterceptor = [[AWSNetworkingRequestInterceptor alloc] init];
    
    
    serviceConfiguration.requestInterceptors = @[baseInterceptor, signer];
    

    
    [AWSS3 registerS3WithConfiguration:serviceConfiguration forKey:@"customendpoint"];
    
    AWSS3 *s3 = [AWSS3 S3ForKey:@"customendpoint"];
    
    AWSS3ListObjectsRequest *listObjectReq = [AWSS3ListObjectsRequest new];
``` 
but it still use v4 signatue， do you kown how to set use v2 signature ? thanks

**Comment by joke-lee** [comment]
hi @karthiksaligrama ,do you know how to set to use v2 signature ?

**Comment by cbommas** [comment]
Hello @joke-lee 

The AWS iOS SDK does not support SigV2 for the S3 Service. As you can see in line 162 of https://github.com/aws/aws-sdk-ios/blob/master/AWSS3/AWSS3Service.m, the AWSS3 client code overwrites any previous value in the requestInterceptors with a SigV4 interceptor.

Please note that we recommend that you use SigV4 as the best practice. SigV2 is only supported in a limited fashion for backward compatibility on a subset of services - see https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html for more details.
