### ISSUE TITLE
sent APNs with Pinpoint Campaigns not have ‘sound’ and ‘badge’

### ISSUE THREAD

**Issue by Hello-Bye** [aws/aws-sdk-ios#844]
"aps":{ 
"alert":{ 
"title":"s",
"body":"s"
},
"content-available":1
},

Hi

When i sent APNs with Pinpoint Campaigns to iOS, I received notification message is this way, "aps" need have "alert" "sound" and "badge", but it only has "alert" now. What did I miss？Do you have any ideas about this？

**Comment by minbi** [comment]
This is an example taken from [apple documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html):

```
    {
       "aps" : {
          "category" : "NEW_MESSAGE_CATEGORY"
          "alert" : {
             "body" : "Acme message received from Johnny Appleseed",
          },
          "badge" : 3,
          "sound" : “chime.aiff"
       },
       "acme-account" : "jane.appleseed@apple.com",
       "acme-message" : "message123456"
    }
```

You also need to ask for permission to show these items in your app code.

**Comment by Hello-Bye** [comment]
Hi 

I'm sure I've registered the notifications correctly. For example：

`
[[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge  completionHandler:^(BOOL granted, NSError * _Nullable error) {}];
        [[UIApplication sharedApplication] registerForRemoteNotifications];
`

I wonder if there is a API that can be configured with sound and badge,  I look up pinpoint API related documents, and I don't find any sound and badge settings.

If you have any information about this, please let me know. Thank you very much.

**Comment by minbi** [comment]
Have you included the sound and badge keys in your push payload?

**Comment by Hello-Bye** [comment]
Thanks for your help

The problem has been solved now.

But i has a new problem: 
I tried to set up a badge of ‘1’ or ‘+1’ with a payload. But it always shows ‘1’ on the phone app icon.

How should I set the value of the badge.
How should I manage Badge.

**Comment by minbi** [comment]
The payload should contain the total badges that the application should show.
For instance, if payload contains `"badge": 8` then the app will should 8

Other Apple APIs are available to manage the badge count on client side.
For instance, iOS 10 has these APIs https://developer.apple.com/documentation/usernotifications/unusernotificationcenter

**Comment by trithucbkpro** [comment]
Hi @Hello-Bye , now I face the same problem (on iOS receive notification with no sound)
Could you please share your solution ?
