### ISSUE TITLE
Any practice on building a timeline with AWS Mobile Hub? 

### ISSUE THREAD

**Issue by Vincent-St** [aws/aws-sdk-ios#847]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWS Mobile Hub

* In what version of SDK are you facing the problem?

The AWS Mobile SDK for iOS 2.6.12

* Is the issue limited to Simulators / Actual Devices?

Both Simulators and Actual Devices

* Can your problem be resolved if you bump to a higher version of SDK?

Nope

* Is this problem related to specific iOS version?

Nope

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I'm trying to build a sample app with AWS Mobile Hub, which looks like the following picture.

<img width="451" alt="screen shot 2018-03-07 at 15 27 30 copy" src="https://user-images.githubusercontent.com/12606544/37079050-33ec423e-221c-11e8-8573-57560a57a0db.png">

I saved the images to AWS S3 with AWSS3TransferManager, and other labels' text to AWS DynamoDB. I could load the images (which saved on AWS S3) perfectly (one by one, in a timeline), but I have no idea how to load the strings which saved on AWS DynamoDB one by one, in a timeline. PS: I could only access / load one string which saved on AWS DynamoDB successfully at one time. Any advices you can share with me? Thanks.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello,

You could use paginated queries which would let you query a fixed number of items and load additionally as required. As a starter you can look at the documentation here: [Link](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-nosql-database.html)

You can use the `.limit` property in the query expression for `DynamoDBObjectMapper` and set the number of items you want to retrieve.

Thanks,
Rohan
