### ISSUE TITLE
Data Encryption

### ISSUE THREAD

**Issue by SSDIAshokPathak** [aws/aws-sdk-ios#850]
Dear ,

Thank you for your support.

I just want to know that is this library using any Data Encryption processing (like "AES", "3DES", "RSA", "DH" etc), if yes could you please give some information about it, if possible.

Thanks in advance.

**Comment by rohandubal** [comment]
Hello @SSDIAshokPathak 

Could you please elaborate a little further on your use-case? With which service do you want to use Data Encryption?

Thanks,
Rohan

**Comment by SSDIAshokPathak** [comment]
Thanks Rohan.

Thank you for your reply.

I wan to use Amazon Simple Email Service (Amazon SES).

**Comment by minbi** [comment]
Hi @SSDIAshokPathak ,

Encryption is optional and is not on by default, please read more here: https://docs.aws.amazon.com/kms/latest/developerguide/services-ses.html

Please open another issue if there are further questions. Closed issues are not monitored.
