### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by joke-lee** [aws/aws-sdk-ios#853]
hi,
i fork and modify some code for adapt ceph radosgw  s3 service, and i find 

> 
3.3 Use Limitation. The Work and any derivative works thereof only may be used or intended for use with the web services, computing platforms or applications provided by Amazon.com, Inc. or its affiliates, including Amazon Web Services, Inc.

in LICENSE.AMAZON

here is my fork
https://github.com/joke-lee/aws-sdk-ios

is it ok to distribute https://github.com/joke-lee/aws-sdk-ios to my custom for commerce usage? my custom use as follow

```
target 'ios_s3_demo' do
  pod 'AWSS3', :git => 'https://github.com/joke-lee/aws-sdk-ios.git'
  pod 'AWSCore', :git => 'https://github.com/joke-lee/aws-sdk-ios.git'
end
```

**Comment by hyandell** [comment]
My apologies @joke-lee, we can't provide you with legal advice. 

As the license says, your fork may only be used with Amazon services/platforms/applications. There are other conditions to comply with if you distribute or modify+distribute. 

If you are concerned your activity may not be permitted under the license, please consult an attorney.
