### ISSUE TITLE
Configure Amazon Pinpoint Campaigns via Email address in iOS app.

### ISSUE THREAD

**Issue by shrawan2015** [aws/aws-sdk-ios#854]
Currently I am using AWSPinpoint for analytics and **Amazon Pinpoint Campaigns**--

So I want to use email based Campaign so, how we have to configure endpoint to set email address or phone number .

Is this proper way to configure the profile of endpoint.

            let profile: AWSPinpointEndpointProfile = currentEndPoint
            profile.user?.userId = withValue
            profile.address = "testemail@gmail.com"
            pinpoint?.targetingClient.update(profile);

After updating above method ,are we able to send campaign to respective email address.I am not able to get proper document for above scenario in app side.

**Comment by sauravexodus** [comment]
Sadly there is no documentation for adding endpoints.

I ended up using `AWSPinpointTargeting.default().updateEndpointsBatch(batchRequest)` and created instances of `AWSPinpointTargetingEndpointBatchItem()` which lets you assign `channelType` and `address`.

However, it is not very reliable so I have already created an issue #861

**Comment by balaji2591** [comment]
The sdk by default registers an endpoint as either APNS/ APNS Sandbox endpoint. Any changes to that will not be reflected.
