### ISSUE TITLE
Spelling error on Confirm email page

### ISSUE THREAD

**Issue by ekordin** [aws/aws-sdk-ios#855]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

Cognito SignUp feature

* In what version of SDK are you facing the problem?

2.6.12, 2.6.13

* Is the issue limited to Simulators / Actual Devices?

All devices

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific iOS version?

No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Just sign up with any user with Email confirmation option in your pool, the confimation page will be displayed, and in UI you will see the "Confiration Code" label instead of "Confirmation Code"

See your code: 
[[AWSFormTableCell alloc] initWithPlaceHolder:@"Confiration Code" type:InputTypeText];

![screen shot 2018-03-22 at 10 25 13 am](https://user-images.githubusercontent.com/18438446/37759298-dc4c29e4-2dbb-11e8-9126-69e2b07980ba.png)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by ekordin** [comment]
Hey, and why it will not be fixed?

**Comment by kvasukib** [comment]
Hi @ekordin, This has been fixed in our latest releases. https://github.com/aws/aws-sdk-ios/blame/2.6.15/AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolSignUpViewController.m#L215
