### ISSUE TITLE
IoT Websocket Connection retry doesn't work as expected if the first attempt fails due to no Internet connectivity

### ISSUE THREAD

**Issue by ArisSarris** [aws/aws-sdk-ios#856]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IOT
* In what version of SDK are you facing the problem?
2.6.13
* Is the issue limited to Simulators / Actual Devices?
all
* Can your problem be resolved if you bump to a higher version of SDK?
Tried with the latest version
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1. Enable Airplane mode
2. Fresh install (to make sure the keychain is empty)
3. Connect using websocket and `[AWSCognitoCredentialsProvider initWithRegionType:identityPoolId:]`
4. Disable Airplane mode
5. `[AWSIoTMQTTClient reconnectToSession ]` called as part of the retry process but the property  `configuration` will always be `nil` since it is only set if the credentials are successfully retrieved the first time.

I think in this case the connection should either completely fail (stop retrying and notify the caller) or set the configuration property earlier, so the retry process works.

**Comment by kvasukib** [comment]
Thank you @ArisSarris for reporting to us. We are looking into it.

**Comment by cbommas** [comment]
hello @ArisSarris 

We released version 2.6.19 earlier today with fixes in the re-connection logic. I was able to reproduce your scenario on a simulator and verify that the fix works. Can you please upgrade to the latest SDK and let us know how it goes?
