### ISSUE TITLE
AWSCognitoAuth signIn error

### ISSUE THREAD

**Issue by serddmit** [aws/aws-sdk-ios#857]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
  AWSCognitoAuth

* In what version of SDK are you facing the problem?
  SDK 11.2

* Is the issue limited to Simulators / Actual Devices?
  NO

* Can your problem be resolved if you bump to a higher version of SDK?
  NO

* Is this problem related to specific iOS version?
  NO

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
  Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

SignIn with Google provider. SignOut. Sign in with Google provide -> Error occurs.

When I had authorized previously and made sign out after, my next sign In will display "Loading page failed". This happens every second login-logout pair.

This happens only for Google provider.
The error is generated in `- (void)safariViewController:(SFSafariViewController *)controller didCompleteInitialLoad:(BOOL)didLoadSuccessfully` with `didLoadSuccessfully = NO`.

So this will generate error and not wait for NSURLSession callback.

Does anyone has such problem?Thanks

**Comment by kainoffke** [comment]
I can confirm this issue. I am currently facing the same problems. As a workaround I created an extension for `AWSCognitoAuth` like so:

```
extension AWSCognitoAuth : SFSafariViewControllerDelegate {
   public func safariViewController(_ controller: SFSafariViewController, didCompleteInitialLoad didLoadSuccessfully: Bool) {
        // I was just implemented do stop AWSCognitoAuth calling its own delegate implementation.
    }
}
```

The problem seems to be, that the redirects in the SafariViewController are happening too fast for it to actually load the page initially.

**Comment by serddmit** [comment]
I end up by removing this method at all:
`public func safariViewController(_ controller: SFSafariViewController, didCompleteInitialLoad didLoadSuccessfully: Bool) {
        // I was just implemented do stop AWSCognitoAuth calling its own delegate implementation.
    }`
This will not impact functionality, but leave user to make done/cancel by itself.

**Comment by dluquedavid** [comment]
problem only happen when yo set "identity_provider=google", the redirect fail.
We fixed it with @kainoffke solution.
