### ISSUE TITLE
AWSS3TransferUtility multipart upload does not work when adding custom metadata

### ISSUE THREAD

**Issue by captainuberawesome** [aws/aws-sdk-ios#858]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3

* In what version of SDK are you facing the problem?
2.6.13

* Is the issue limited to Simulators / Actual Devices?
All

* Can your problem be resolved if you bump to a higher version of SDK?
Already using the latest version

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
 CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I am using AWSS3TransferUtility to upload file using multipart upload. If I add custom metadata, the upload always fails with error 
```swift
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Fri, 23 Mar 2018 13:18:36 GMT, x-amz-request-id=C6FE6E1243FCAB45, x-amz-id-2=Yh09DBEVcH/flrTZtgauiqcWepvcGu34F9fuaS61PAkqB+qFlIViupaWGIuQp/NVp/5v/fK6epE=}
```
Without metadata, the upload will finish successfully. If I use AWSS3TransferUtility non-multipart upload method it will also finish successfully. The problem seems to be only with the combination of multipart upload and custom metadata.

I have reproduced this issue with the aws-sdk-ios-samples S3TransferUtility-Sample project (by replacing regular upload with multipart upload and adding custom metadata):

```swift
func uploadImage(with data: Data) {
        let expression = AWSS3TransferUtilityMultiPartUploadExpression()
        expression.progressBlock = progressBlock
      
        expression.setValue("public-read", forRequestParameter: "x-amz-acl")
        let parameters = ["x-amz-meta-author": "1",
                          "x-amz-meta-action": "challenge",
                          "x-amz-meta-category": "3"]
        for (key, metaValue) in parameters {
          expression.setValue(metaValue, forRequestParameter: key)
        }

        transferUtility.uploadUsingMultiPart(data:
            data,
            bucket: S3BucketName,
            key: S3UploadKeyName,
            contentType: "image/png",
            expression: expression,
            completionHandler: completionHandler).continueWith { (task) -> AnyObject! in
                if let error = task.error {
                    print("Error: \(error.localizedDescription)")
                    
                    DispatchQueue.main.async {
                        self.statusLabel.text = "Failed"
                    }
                }
                
                if let _ = task.result {
                    
                    DispatchQueue.main.async {
                        self.statusLabel.text = "Generating Upload File"
                        print("Upload Starting!")
                    }
                    
                    // Do something with uploadTask.
                }
                
                return nil;
        }
    }
```

**Comment by cbommas** [comment]
hello @captainuberawesome 

Thank you for reporting this error and apologies for any inconvenience caused. This is a bug and we will fix it in the next SDK release. I will update this thread once the release is completed.

**Comment by kvasukib** [comment]
Hi @captainuberawesome This has been fixed with 2.6.14 (https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#2614). Please upgrade, check and let us know if it fixes the issue.

**Comment by captainuberawesome** [comment]
Hello @kvasukib 
Unfortunately I'm still repeating this issue with version 2.6.14. Same conditions, same error.

**Comment by captainuberawesome** [comment]
Hi @kvasukib 
I've looked at the code and it seems the problem is in `AWSS3TransferUtility` method
```createUploadSubTask:subTask:startTransfer:```
specifically line 1025 
`[transferUtilityMultiPartUploadTask.expression assignRequestParameters:request];`

``` 
- (void)assignRequestParameters:(AWSS3GetPreSignedURLRequest *)getPreSignedURLRequest {
    for (NSString *key in self.internalRequestParameters) {
        [getPreSignedURLRequest setValue:self.internalRequestParameters[key]
                     forRequestParameter:key];
    }
} 
```

Since `createUploadSubTask:` is called for each part in multipart request and there's no check for "x-amz-meta" prefix when adding parameters in `assignRequestParameters:`, custom metadata parameters end up being attached to each part of the multipart request, which seems to be the cause of the error.

**Comment by captainuberawesome** [comment]
Hi @cbommas 

I was using `setValue:forRequestParameter:` method to add custom metadata to upload request as described [here](https://github.com/aws/aws-sdk-ios/issues/277). I was under impression that this was the correct method to use to add metadata, but since you're referencing method `assignRequestHeaders:`, apparently I was supposed to use `setValue:forRequestHeader:` instead. It's not very clear in the documentation.

Apologies for miscommunication, the upload works if I use `setValue:forRequestHeader:` to add custom metadata.
