### ISSUE TITLE
Crashes: AWS Pinpoint

### ISSUE THREAD

**Issue by patpawasantanon** [aws/aws-sdk-ios#860]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
pinpoint
* In what version of SDK are you facing the problem?
2.6.13
* Is the issue limited to Simulators / Actual Devices?
no
* Can your problem be resolved if you bump to a higher version of SDK?
no
* Is this problem related to specific iOS version?
no
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

we found many crash reports from fabric for AWS pinpoint. Links below
http://crashes.to/s/01c4bbbe72f
http://crashes.to/s/198696e7d6d
http://crashes.to/s/c16072fd945
http://crashes.to/s/4d7480d0e18
http://crashes.to/s/d9e8115017e
http://crashes.to/s/8c7d5630fd3
http://crashes.to/s/4e44d353009
http://crashes.to/s/cfdb5867459
http://crashes.to/s/bb20e08914f
http://crashes.to/s/ba44f87015c

**Comment by balaji2591** [comment]
Hi @patpawasantanon 
A newer version of aws ios sdk was released last thursday (2.6.14) that contains fixes for some of the issues listed out here. Can you verify and update the issue ?

**Comment by kubbing** [comment]
@patpawasantanon ?

**Comment by petrpavlik** [comment]
Hi @balaji2591 @kvasukib, I'm responding on behalf of @patpawasantanon. 

We have finally released a new version of our app using version 2.6.16 of your SDK in production and this is what we're seeing so far:

http://crashes.to/s/01c4bbbe72f seems fixed
http://crashes.to/s/198696e7d6d is not fixed
http://crashes.to/s/c16072fd945 is not fixed
http://crashes.to/s/4d7480d0e18 is not fixed
http://crashes.to/s/d9e8115017e cannot replicate so far
http://crashes.to/s/8c7d5630fd3 is not fixed -> http://crashes.to/s/28c8c8ea339
http://crashes.to/s/4e44d353009 cannot replicate so fa
http://crashes.to/s/cfdb5867459 cannot replicate so far
http://crashes.to/s/bb20e08914f seems to be the same crash as http://crashes.to/s/4d7480d0e18
http://crashes.to/s/ba44f87015c is not fixed -> http://crashes.to/s/8e720433c44
