### ISSUE TITLE
Undefined symbols for architecture x86_64 when running Unit Tests

### ISSUE THREAD

**Issue by runmad** [aws/aws-sdk-ios#862]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
**AWSS3**

* In what version of SDK are you facing the problem?
**2.6.13**

* Is the issue limited to Simulators / Actual Devices?
Both when running tests **Tests**

* Can your problem be resolved if you bump to a higher version of SDK?
**N/A**

* Is this problem related to specific iOS version?
**Xcode 9.3 + iOS 11.3**

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
**Prebuilt**

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I'm running into the following issue:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AWSS3TransferManagerUploadRequest", referenced from:
      objc-class-ref in AWSManagerTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This only happens when I run my unit test target. The integration did not change, I've upgraded to Xcode 9.3 and attempting to run this on iOS 11.3.

**Comment by rohandubal** [comment]
Which mode are you running the tests in? Debug/ Release? Can you run it in Release mode?

**Comment by runmad** [comment]
`Debug`.

I've switched to compiling the project and linking it that way to solve it.
