### ISSUE TITLE
Deprecated use of Objective-C code needs removal

### ISSUE THREAD

**Issue by kteman** [aws/aws-sdk-ios#863]
Hi guys, are you planning to fix the deprecated use of Objective-C methods? These are now warnings, and next they will be crippling!

<img width="1159" alt="screen shot 2018-04-01 at 12 16 21 pm" src="https://user-images.githubusercontent.com/1731595/38176138-c0042e42-35a6-11e8-965c-00dd0068a50e.png">

**Comment by kvasukib** [comment]
Thank you @kteman for reporting to us. Sorry for the inconvenience caused. We are looking into it.

**Comment by rohandubal** [comment]
Fixed with 2.6.15 release.
