### ISSUE TITLE
Very large number of warnings about using 'self' in AWS SDK with Xcode 9.3

### ISSUE THREAD

**Issue by doctorcolinsmith** [aws/aws-sdk-ios#864]
I just updated to AWS SDK version 2.6.14 and to Xcode 9.3.   I have the AWS SDK installed in my app's workspace with Cocoapods.

There are now a very large number of occurrences of the warning "Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior" coming out of AWSCore.  There are a few instances of the same warning in other AWS pods.  I believe this is a new warning to Xcode 9.3.

Would be great to get these cleaned up to reduce the noise when building my app.

**Comment by kvasukib** [comment]
Thank you @doctorcolinsmith for reporting to us. We are looking into it.

**Comment by minbi** [comment]
Merged pull request https://github.com/aws/aws-sdk-ios/pull/868
Release with next version
