### ISSUE TITLE
How does iOS specify which alias of a Lambda function to use?

### ISSUE THREAD

**Issue by gomigbg** [aws/aws-sdk-ios#865]
I used the Streamlined Steps to set up AWS Lambda in my project:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-cloud-logic.html

How do I specify an alias for a Lambda function?

**Comment by rohandubal** [comment]
You will have to configure the alias from the API Gateway console. You can invoke a stage from the SDK for a particular API though. The Cloud Logic feature invocation is done via API Gateway.

Thanks,
Rohan
