### ISSUE TITLE
"x-amz-meta-" metadata prefix duplicating on multipart upload (also wrong content-type and access permission)

### ISSUE THREAD

**Issue by captainuberawesome** [aws/aws-sdk-ios#869]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3

* In what version of SDK are you facing the problem?
2.6.14

* Is the issue limited to Simulators / Actual Devices?
All of the above

* Can your problem be resolved if you bump to a higher version of SDK?
Already using the latest version

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I am using `AWSS3TransferUtility` to upload file using multipart upload (`uploadFileUsingMultiPart:bucket:key:contentType:expression:completionHandler:`). I add custom metadata to the upload request using `AWSS3TransferUtilityExpression` method `setValue:forRequestHeader:`
The request is sent with custom metadata in its headers:

```
    "Content-Type" = "video/quicktime";
    "x-amz-meta-action" = challenge;
    "x-amz-meta-author" = 58;
    "x-amz-meta-category" = 3;
```

But when the file is uploaded successfully, the file's metadata look like this in S3 bucket:
<img width="395" alt="screenshot" src="https://user-images.githubusercontent.com/15043216/38298723-5c8ff976-3822-11e8-87c9-9d4a034b1053.png">
All metadata has duplicated "x-amz-meta-" prefix. Also content-type is listed as "binary/octet-stream" instead of  "video/quicktime". I've looked at the code in AWSS3TransferUtility and looks like the problem might be on the server side.

Edit: I'm also setting file access parameter `expression.setValue("public-read", forRequestParameter: "x-amz-acl")` but the resulting file is not available for public read, so there's a problem with that too.
I have tried setting the permission parameter as a request header `expression.setValue("public-read", forRequestHeader: "x-amz-acl")` but it results in the upload error:
```
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Wed, 04 Apr 2018 12:48:14 GMT, x-amz-request-id=3ABD9528CAB869C5, x-amz-id-2=NKWwQcAP9y/FqQSGEOb0YFvbTzUwMVbMFQ9VwhW6LYSD/todZqLn/UM4PRMYl1MN415Pwy0dA9M=}
```

None of the above problems appear with regular (non-multipart) `AWSS3TransferUtility` file upload

**Comment by cbommas** [comment]
Hello @captainuberawesome 

Thanks for reporting this issue and sorry for any convenience. I will investigate this issue and get back to you.

**Comment by cbommas** [comment]
Hello @captainuberawesome 

The problems with the custom metadata and x-amz-acl are due to bugs in the code. They will be fixed and included in the next release of the SDK.

The content-type for the uploaded file can be specified directly in the `contentType` parameter in the upload function call. If you specify this in the expression as a request header, it will be overridden by the value passed into the `contentType` parameter.

**Comment by captainuberawesome** [comment]
Hi @cbommas 

> The content-type for the uploaded file can be specified directly in the contentType parameter in the upload function call. If you specify this in the expression as a request header, it will be overridden by the value passed into the contentType parameter.

I am specifying content type directly in the function call, but it still gets overwritten

```
transferUtility.uploadUsingMultiPart(fileURL: URL(fileURLWithPath: fileURL),
                                     bucket: Constants.bucket,
                                     key: fileName,
                                     contentType: "video/quicktime",
                                     expression: expression,
                                     completionHandler: completion)
```

**Comment by cbommas** [comment]
hi @captainuberawesome 

Ah, I see the problem. The content type that is being passed in via the method is not being properly propagated to the `AWSS3CreateMultipartUploadRequest` object that is used to initiate the multi part transfer. The server sees a blank value, because of the propagation issue, and is setting up a default contentType.

The fix for this issue will also be included in the next version of the SDK.

**Comment by captainuberawesome** [comment]
Hi @cbommas 

Thanks for the update, the bug is fixed now.
