### ISSUE TITLE
API Gateway: Cognito & Unauthenticated

### ISSUE THREAD

**Issue by SkyFred27** [aws/aws-sdk-ios#871]
Hi, 

I'm quite new with aws services.
I've setup API Gateway to end up to a lambda function. everything is working fine.
Just added cognito, to authorize only log in user. (iOS)
How can I now authorize also unauthenticated user to access API Gateway ? 

I know that I can get an identityId and also accessKey, SecretKey and SessionKey but what should I do with that. I was not able to find any documentation about this.

Thanks a lot 
Fred

**Comment by minbi** [comment]
Hi Fred,

Unauthenticated users have an IAM policy attached and can be viewed in the Cognito Federated Identities console. Access to the API Gateway APIs that should be accessed will need to be added to the IAM policy.

Please post in AWS Forums for specific assistance to services.

**Comment by SkyFred27** [comment]
This doesn't really help, anyway thank you for your answer.
I know the forum, but there's no one there, at least here I got an answer
