### ISSUE TITLE
submitAllEvents startup freeze @synchronized(self.lock)

### ISSUE THREAD

**Issue by kubbing** [aws/aws-sdk-ios#872]
This is an PinPoint iOS SDK startup freeze issue. Pinpoint gets stuck on its own lock on main thread. We managed to get the call stack by manually pausing the app in debugger. In production iOS Watchdog kills the app on launch. Very critical issue.

0. receive a push notification, warm launch (background -> foreground)
1. We call `pinpointAnalytics.record(event)` (in our code) with a remote notification payload
2. `AWSPinpointAnalyticsClient.submitAllEvents`
3. `AWSPinPointaEventRecoded.submitAllEvents`
4. its gets stuck at `@synchronized(self.lock)`, `AWSPintPointEventRecorder.m#486`

Its a rare race condition. Hard to replicate in debugger. In production it gets stuck and iOS Watchdog kills the app. Pls see the screenshot of the stack trace - app is stuck on that lock during. I had to pause the app manually.

# To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Pinpoint

* In what version of SDK are you facing the problem?
AWSPinpoint 2.6.14

* Is the issue limited to Simulators / Actual Devices?
Device

* Can your problem be resolved if you bump to a higher version of SDK?
Not available

* Is this problem related to specific iOS version?
Not really, its a startup freeze

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Well not really.

![image 6](https://user-images.githubusercontent.com/324165/38317404-4c5e4d18-382d-11e8-823d-e5996df75317.png)

**Comment by balaji2591** [comment]
Hi Kubbing, 
Can you upload a screen shot that is using the 2.6.14 version ? (so that we can confirm that issue exists in 2.6.14 as well. Looks like the screen shot is not from the 2.6.14 version)
because Line number 486 is different in 2.6.14
https://github.com/aws/aws-sdk-ios/blob/master/AWSPinpoint/AWSPinpointEventRecorder.m#L486

**Comment by kubbing** [comment]
@balaji2591 Can't confirm, hard to replicate atm. We are running another beta testing to see if the issue  is still present.

**Comment by petrpavlik** [comment]
We have received reports of our app "freezing" even after we've updated the SDK to 2.6.14.

**Comment by kubbing** [comment]
@balaji2591 we are no longer getting report of this freeze
