### ISSUE TITLE
AmazonDaxClient for iOS ?

### ISSUE THREAD

**Issue by dproton** [aws/aws-sdk-ios#875]
Are there any ways to use DAX (Amazon DynamoDB Accelerator) for iOS ? Currently, java supports DAX for clients (at here https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-dax/src/main/java/com/amazonaws/services/dax)

**Comment by minbi** [comment]
Hi @dproton ,

We currently do not have DAX support. We will take this as a feature request.
