### ISSUE TITLE
AWS Auth UI Present Login Keyboard Bug

### ISSUE THREAD

**Issue by RushanB** [aws/aws-sdk-ios#877]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWS iOS SDK - AWS Auth UI
* In what version of SDK are you facing the problem?

Latest version: 2.6.14 - Carthage
* Is the issue limited to Simulators / Actual Devices?

Occurs on both actual and simulator
* Can your problem be resolved if you bump to a higher version of SDK?

On version 2.6.13 It did not occur
* Is this problem related to specific iOS version?

I'm not sure.
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Carthage
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I am using Xcode 9.3, Swift 4.1, incorporate the Auth UI storyboard manually and call the AWSAuthUIViewController.presentViewController method and you will see the keyboard push the textfield upward out of view. 

You can view the image of the bug at https://imgur.com/a/DFxHG - iPhone 8 Plus simulator.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you for reporting to us. We fixed this issue in 2.6.17 https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#2617. Can you upgrade and provide us any feedback on the issue?

**Comment by dhrebeniuk** [comment]
@kvasukib Thanks you, issue was fixed
