### ISSUE TITLE
AWSAuthUI textfields disappear with keyboard

### ISSUE THREAD

**Issue by King-Kira** [aws/aws-sdk-ios#878]
I'm developing an app that requires user sign-in. Unfortunately, the sign-in UI provided by Amazon shifts upwards and the textfields disappear when the keyboard appears, leaving an unsightly black space. It happens in both the simulator and on my physically phone. However, it doesn't happen for a simulator of iPhone X. I notice that for iPhone X, the view shifts upward such that the textfields are still visible and accessible without the unsightly black space.

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSAuthUI

* In what version of SDK are you facing the problem?
2.6.14

* Is the issue limited to Simulators / Actual Devices?
No, but it's occurred with multiple iPhone versions except iPhone X

* Can your problem be resolved if you bump to a higher version of SDK?
No, it appeared when I updated.

* Is this problem related to specific iOS version?
No.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I don't do anything strange to implement the sign-in UI. I simply follow the instructions found here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by RushanB** [comment]
I was curious so I looked into the SDK. They are using hard-coded values instead of dynamic which is why I think its behaving the way it is.

 This is how they are doing it:
- (void)keyboardDidShow:(NSNotification *)notification {
    CGSize size = ((NSValue *)[[notification userInfo]
                               valueForKey:UIKeyboardFrameBeginUserInfoKey]).CGRectValue.size;
    
    [self.view setFrame:CGRectMake(0, -NAVIGATION_BAR_HEIGHT - size.height, self.view.frame.size.width, self.view.frame.size.height)];
}

- (void)keyboardDidHide:(NSNotification *)notification {
    [self.view setFrame:CGRectMake(0, NAVIGATION_BAR_HEIGHT ,self.view.frame.size.width,self.view.frame.size.height)];
}

**Comment by vccabral** [comment]
I just encountered this issue. I want to get this resolved for my app.

**Comment by RushanB** [comment]
The only way to resolve this at the moment is to downgrade to the previous version of the SDK. @vccabral

**Comment by vccabral** [comment]
@RushanB 

I am using this repo/branch with the following Podfile

```
    # Pods for OpenMovement
    pod 'AWSMobileClient', '~> 2.6.16'
    pod 'AWSUserPoolsSignIn', '~> 2.6.16'
    pod 'AWSAuthUI', :git => 'https://github.com/dhrebeniuk/aws-sdk-ios.git', :branch => 'bugfix/textfield-disappear-with-keyboard'
    pod 'AWSDynamoDB', '~> 2.6.16'
```

I look forward to a merge, so I can remove an explicit reference to a random fork.

**Comment by dhrebeniuk** [comment]
Hello @RushanB ,
1. Which version from AWSAuthUI bug free?
2. When, you will be able my branch into main release?

P.S. I also need fix of this issue for my project.

**Comment by vccabral** [comment]
@dhrebeniuk I tested your branch on my iPhone 6. It worked well. Not sure what the optimal is or how the automated tests work here. I can take a look at that later but the keyboard no longer covered UI.

**Comment by kvasukib** [comment]
Thank you for reporting to us. We fixed this issue in 2.6.17 https://github.com/aws/aws-sdk-ios/blob/master/CHANGELOG.md#2617. Can you upgrade and provide us any feedback on the issue?

**Comment by dhrebeniuk** [comment]
@kvasukib , Thank you, issue was fixed

**Comment by 24601** [comment]
I am not sure this is "fixed" or it's "fix" created a new problem/regression. Regardless, I've opened a separate issue as #984, maybe it's related, maybe it isn't.
