### ISSUE TITLE
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “mybucketname” which could put your confidential information at risk."

### ISSUE THREAD

**Issue by FahdSaif** [aws/aws-sdk-ios#879]
func uploadData(with data: Data) {
        
        //var data: Data = Data() // Data to be uploaded
        //let mykey="\(resource).\(type)" //filename.jpeg
        //data=UIImagePNGRepresentation(UIImage(named: mykey)!)!
        
        //let image=myimageview.image
        
        print("data length")
        print (data.count)
        
        
        let expression = AWSS3TransferUtilityUploadExpression()
        expression.progressBlock = {(task, progress) in
            DispatchQueue.main.async(execute: {
                // Do something e.g. Update a progress bar.
            })
        }
        
        var completionHandler: AWSS3TransferUtilityUploadCompletionHandlerBlock?
        completionHandler = { (task, error) -> Void in
            print("Error: \(error?.localizedDescription)")
            DispatchQueue.main.async(execute: {
                // Do something e.g. Alert a user for transfer completion.
                // On failed uploads, `error` contains the error object.
                print("something error")
            })
        }
        
        let transferUtility = AWSS3TransferUtility.default()
        
        transferUtility.uploadData(data,
                                   bucket: bucketname,
                                   key: "myTransferUtilityUpload.png",
                                   contentType: "image/png",
                                   expression: expression,
                                   completionHandler: completionHandler).continueWith {
                                    (task) -> AnyObject! in
                                    if let error = task.error {
                                        print("Error: \(error.localizedDescription)")
                                        
                                        DispatchQueue.main.async {
                                            print("failede")
                                        }
                                        
                                    }
                                    
                                    if let _ = task.result {
                                        // Do something with uploadTask.
                                        DispatchQueue.main.async {
                                            print("Completed")
                                        }
                                    }
                                    return nil;
        }
    }

### To help us solve your problem better, please answer the following list of questions.

I would also like to add that the same bucket, when I use the TransferManager utility code it works fine on IOS, but when I use the transferUtility to upload it gives me the error in the title.
Here is my info.plist file:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>amazonaws.com</key>
			<dict>
				<key>NSThirdPartyExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>amazonaws.com.cn</key>
			<dict>
				<key>NSThirdPartyExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>

* What service are you using?
I am uploading images to S3, using transfer utility

* In what version of SDK are you facing the problem?
IOS 11.0

* Is the issue limited to Simulators / Actual Devices?
I have not tested it on the actual device yet. Its comming on the Xcode 9.2's simulator.

* Can your problem be resolved if you bump to a higher version of SDK?
My deployment target is 11.2 I have also changed the deployment target to 9.0 same error

* Is this problem related to specific iOS version?
Im not sure about this

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello @FahdSaif 

This might be because of you trying to use the folder name as a part of bucket name for your uploads/ downloads. The S3 host naming varies a little and the recommended way is to use bucket name separately from the folder. The key should have the folder name. 

This seems related to #https://github.com/awslabs/aws-sdk-ios-samples/issues/263 

Could you please answer those questions to clarify?

Thanks
Rohan

**Comment by rohandubal** [comment]
Closing it in accordance with #awslabs/aws-sdk-ios-samples#263
