### ISSUE TITLE
Add Certificate Pinning

### ISSUE THREAD

**Issue by eman8519** [aws/aws-sdk-ios#880]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Core

* In what version of SDK are you facing the problem?
All

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
Yes
* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
N/A

Hey guys, I don't mind forking and working on this myself, but was wondering if there were any plans/reasons that there isn't an option for Cert pinning at the Core Level of the SDK?  I think it would be a great addition, but not sure if/why this was left out intentionally.

**Comment by rohandubal** [comment]
Hello @eman8519 

Thanks for submitting this issue. I am taking this as a feature request to the team and will keep posted if we work on this. 

Also if you can work on a PR, that would be awesome!

Thanks,
Rohan

**Comment by om-ha** [comment]
Any update on this? @rohandubal

**Comment by gadget-man** [comment]
Would really appreciate an update on this - the SDK is very prone to MITM attacks making the full policy available via the SDK to an unscrupulous attacker.
