### ISSUE TITLE
S3 multipart uploading with aws-sdk-ios. resume on error.

### ISSUE THREAD

**Issue by danilke** [aws/aws-sdk-ios#891]
I'm trying to handle errors (no internet connection) on multipart uploading to s3. It is possible somehow to resume uploading from the same percentage when the internet connection is back? Thank you!

```let credentialsProvider = AWSStaticCredentialsProvider(accessKey: access_id, secretKey: secret_key)
let configuration = AWSServiceConfiguration.init(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)
AWSServiceManager.default().defaultServiceConfiguration = configuration
let uploadRequest = AWSS3TransferManagerUploadRequest()!

transferManager.upload(uploadRequest).continueWith { [weak self] (task) -> Any? in

    if let error = task.error {
        // DO SOME ENDLESS CICLE WHILE
        // INTERNET CONNECTION IS BACK
        // AND THAN RESUME FROM THE SAME %
    }

    if task.result != nil {
        // IT'S OK
    }
}

**Comment by kvasukib** [comment]
Thank you @danilke for reporting to us. We have introduced multi-part support with ability to pause/resume transfers in `AWSS3TransferUtility`. We recommend using the `AWSS3TransferUtility`, where we will accept feature requests and bug reports.

Currently `AWSS3TransferUtility` does not listen to network connectivity changes. However you can use `Reachability.swift` library to listen for network changes and pause the transfer when network drops and resume the transfer when network comes back.

**Comment by danilke** [comment]
Thank you, I will try it.

**Comment by danilke** [comment]
Hi, @kvasukib,  where I can listen to the network connectivity changes on uploading? 

I was trying put listener to `transferManager.upload(uploadRequest).continueWith... ` block,  but connection error was faster then than listener. It is same with ` uploadRequest.uploadProgress = { (bytesSent, totalBytesSent, totalBytesExpectedToSend) -> Void in`

Thank you.
