### ISSUE TITLE
AWSCognitoAuth Facebook SignOut Issue

### ISSUE THREAD

**Issue by damisv** [aws/aws-sdk-ios#894]
Hello, 
I'm using the AWSCognitoAuth fw into my iOS app, to achieve login with Facebook. All works pretty well, except the signout. Although it clears the keychain, I can't login with other facebook user. It shows the previously user logged in and waiting for my approval to continue.
I've already tried clearing cache & cookies but no luck.

**Comment by gwander** [comment]
Currently, Cognito doesn't support signout flow on Facebook, but this is a feature request on our roadmap.

**Comment by ekordin** [comment]
Have the same thouble. Would be great to have it fixed soon.

**Comment by VishnuNCS** [comment]
Any Update on this issue

**Comment by Tymofiev** [comment]
Is there any other way to completely logout from Facebook and clear all sessions except of doing `Auth.signOut()` along with manually terminating the session from Facebook app? Thanks!
