### ISSUE TITLE
Unable to add new attribute to DynamoDB

### ISSUE THREAD

**Issue by sanjivsoni17** [aws/aws-sdk-ios#898]
I am using Mobile Hub for iOS with DynamoDB only. I am trying to add a new attribute to the table, but unable to send data from iOS App. I have added the attribute '_experiementId' through aws mobile hub console and verified it. I am unable to save data to DynamoDB.

Here is my DynamoDB Mapper Class
`class Shots: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _shotId: String?
    var _userId: String?
    var _creationDate: NSNumber?
    var _deviceId: String?
    var _experiementId: String?
    var _metaData: String?
    var _payload: String?
    var _transferTime: NSNumber?
    var _updateDate: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "strbatdatatagger-mobilehub-64050291-Shots"
    }
    
    class func hashKeyAttribute() -> String {

        return "_shotId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_shotId" : "shotId",
               "_userId" : "userId",
               "_creationDate" : "creationDate",
               "_deviceId" : "deviceId",
               "_experiementId" : "experiementId",
               "_metaData" : "metaData",
               "_payload" : "payload",
               "_transferTime" : "transferTime",
               "_updateDate" : "updateDate",
        ]
    }
}
`

I've verified that my code has the correct table and attribute names

Here is how I am adding values to the mapper object 
`func insertShotDDB(shotPayload: String, shotMeta: String, transferTime: Int64) -> String {
    let dynamoDBObjectMapper = AWSDynamoDBObjectMapper.default()
    
    print(shotMeta)
    // Create a new shot
    let shotItem: Shots = Shots()
    
    shotItem._shotId = NSUUID().uuidString
    shotItem._userId = "Tester-A"
    shotItem._creationDate = NSDate().timeIntervalSince1970 as NSNumber
    shotItem._deviceId = "SensorTile-ST"
    shotItem._metaData = shotMeta
    shotItem._payload = shotPayload
    shotItem._transferTime = transferTime as NSNumber
    shotItem._updateDate = NSDate().timeIntervalSince1970 as NSNumber
    shotItem._experiementId = "Test"
    
    //Save a new item
    dynamoDBObjectMapper.save(shotItem, completionHandler: {
      (error: Error?) -> Void in
      
      if let error = error {
        print("Amazon DynamoDB Save Error on new shot: \(error)")
        return
      }
      print("New shot was saved to DDB.")
      transferState = .GetData
      flag = 1
    })
    
    return "true"
  }`

Heres the error I get when the code executes
`Amazon DynamoDB Save Error on new shot: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=0 "(null)" UserInfo={__type=com.amazon.coral.validate#ValidationException, message=Supplied AttributeValue is empty, must contain exactly one of the supported datatypes}`

SDK is installed via CocoaPods

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific iOS version?

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Are you using Swift 4? If yes, you will have to specify `@objcMembers` directive for your class as specified here: https://github.com/aws/aws-sdk-ios/issues/750#issuecomment-337046816 

Thanks,
Rohan

**Comment by zaxonus** [comment]
I am having similar issues, and I have tried to specify @objcMembers to the class or @objc to each member. But to no avail: the error message didn't change a bit.

**Comment by rohandubal** [comment]
the _userId attribute should be a valid cognitoIdentityId and not a random string. `shotItem._userId = "Tester-A"` will get rejected due to policy set by MobileHub.
