### ISSUE TITLE
Multipart upload doesn't work when using custom AWSS3TransferUtility instance with custom configuration

### ISSUE THREAD

**Issue by captainuberawesome** [aws/aws-sdk-ios#900]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3

* In what version of SDK are you facing the problem?
2.6.16

* Is the issue limited to Simulators / Actual Devices?
All

* Can your problem be resolved if you bump to a higher version of SDK?
Already using the latest version

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I am using AWSS3TransferUtility to upload file using multipart upload. When using default transfer utility, everything works fine
`transferUtility = AWSS3TransferUtility.default`

But if I create custom transferUtility with custom configuration, the upload hangs on the start and the progress never moves from zero. 
```
func uploadImage(with data: Data) {
      let expression = AWSS3TransferUtilityMultiPartUploadExpression()
      expression.progressBlock = progressBlock
    
      let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1,
                                                              identityPoolId: IdentityPoolId)
      if let configuration = AWSServiceConfiguration(region: .EUWest3, credentialsProvider: credentialsProvider) {
        AWSS3TransferUtility.register(with: configuration, forKey: "transferUtilityConfigurationKey")
      }
      transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transferUtilityConfigurationKey")
      
      transferUtility?.uploadUsingMultiPart(data: data,
                                  bucket: S3BucketName,
                                  key: S3UploadKeyName,
                                  contentType: "image/png",
                                  expression: expression,
                                  completionHandler: completionHandler).continueWith { (task) -> AnyObject! in
                if let error = task.error {
                    print("Error: \(error.localizedDescription)")
                    
                    DispatchQueue.main.async {
                        self.statusLabel.text = "Failed"
                    }
                }
                
                if let _ = task.result {
                    
                    DispatchQueue.main.async {
                        self.statusLabel.text = "Generating Upload File"
                        print("Upload Starting!")
                    }
                    
                    // Do something with uploadTask.
                }
                
                return nil;
        }
    }
```

I am using the same region types and poolId that I've provided in the Info.plist file for the default configuration.

Note that the above problem does not occur with the non-multipart upload. It works fine with both custom and default transfer utility (same code as above with upload method changed to regular upload from multipart upload).

**Comment by cbommas** [comment]
Hello @captainuberawesome 

This issue has been fixed in version 2.6.17. I am closing this issue - please feel free to reopen if issue hasn't been fixed.
