### ISSUE TITLE
AWSIoTDataManager statusCallback is never called after reconnecting

### ISSUE THREAD

**Issue by haiiro-shimeji** [aws/aws-sdk-ios#901]
statusCallback is never called after reconnecting MQTT over websocket connection because of the code linked below:

https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/Internal/AWSIoTMQTTClient.m#L881

Once MQTT over websocket connection is closed, then nil is set to statusCallback. So the application never knows the connection is restored or not.

I expect that AWSIoTDataManager will automatically reconnect to server and will behave the same before disconnecting. So AWSIotDataManager.connectUsingWebSocketWithClientId must be called again because the state of AWSIoTDataManager is different (statusCallback is nil or not) after reconnecting.

Is this correct?

**Comment by haiiro-shimeji** [comment]
Hi,

Does anyone have the similar problem about AWSIoTMQTTClient`s reconnecting behavior ??

My problem is the following.

1. Connect to AWSIoT server with AWSIoTDataManager.connectUsingWebSoketWithClientID() method.
2. Down the network.
3. The callback is called with AWSIoTMQTTStatusDisconnected.
4. Restore network and wait until reconnected to AWSIoT server.
5. The callback is not called (I expect it is called with AWSIoTMQTTStatusConnected)

Is this intended?

**Comment by cbommas** [comment]
hello @haiiro-shimeji 

We made a bunch of changes to the IoT SDK in version 2.6.19. Can you please upgrade and let us know how it goes?

The behavior is that AWSIoTDataManager will automatically reconnect to the server in case of connection failures and will behave the same as before disconnecting. For each reconnect, it will call the callback with AWSIoTMQTTStatusConnecting to indicate that it is reconnecting, and then with  AWSIoTMQTTStatusConnected  if the connection is successful.

Can you provide some more context on your scenarios and what you are looking to to do? That context will be very helpful in assisting you further.

**Comment by haiiro-shimeji** [comment]
@cbommas 
Sorry for my late reply.

In 2.6.21, everything works perfectly as I had expected!
Thanks a lot!!
