### ISSUE TITLE
Issue with AWSNetworkingUploadProgressBlock

### ISSUE THREAD

**Issue by dms90** [aws/aws-sdk-ios#91]
Hi, I've recently asked a question on StackOverflow associated with an issue with <code>AWSNetworkingUploadProgressBlock</code>

http://stackoverflow.com/questions/26593316/upload-images-using-aws-s3-sdk-v2-for-ios-track-progress

Maybe is not an issue and is a mistake in my code, I was trying different ways and I can't track the progress of all photos. It seems like the block declared on <code>AWSNetworkingUploadProgressBlock</code> is only called for the earliest tasks.

```objective-c
- (void)uploadPhotos:(NSArray *)photos
{   
    NSMutableArray *tasks = [@[] mutableCopy];
    AWSS3TransferManagerUploadRequest *uploadRequest;
    
    for (Photo *photo in photos) {
        
        NSString *key = photo.file_name;
        
        uploadRequest = [AWSS3TransferManagerUploadRequest new];
        
        uploadRequest.bucket = self.bucketRootName;
        uploadRequest.key = key;        
        uploadRequest.body = photo.url_edited;
        
        uploadRequest.uploadProgress = ^(int64_t bytesSent, int64_t totalBytesSent, int64_t totalBytesExpectedToSend) {
            
            int progress = (int)(totalBytesSent * 100.0 / totalBytesExpectedToSend);
           
            DDLogInfo(@"%@: %d", photo.file_name, progress);
            
        };
        
        BFTask *task = [self.s3transferManager upload:uploadRequest];
        [tasks addObject:task];
    }
    
    [[BFTask taskForCompletionOfAllTasks:tasks] continueWithExecutor:[BFExecutor mainThreadExecutor] withBlock:^id(BFTask *task) {
        
        if (task.error != nil) {            
            DDLogError(@"Error: [%@]", task.error);
        } else {
            DDLogInfo(@"All photos uploaded!");
        }
        
        return nil;
        
    }];
}
```
The log reports progress for the first 4 photos, the rest of them are just uploading without tracking progress. With SDK v1 I could track progress without problems using the delegate.

Thanks,
Diego

**Comment by yosuke-matsuda** [comment]
I've confirmed that when there are many current connections, the transfer feedback gets dropped eventually. Our progress feedback is directly derived from the `- URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:` delegate method, and I am trying to see if there is anything we can do to circumvent this. Thank you for your patience.

**Comment by dms90** [comment]
Ok, I'm glad you can reproduce it. Hope you can fix it soon.

Thanks!

Regards,
Diego

**Comment by yosuke-matsuda** [comment]
I talked to an engineer from Apple and confirmed this is a bug in the iOS. A bug report has already been filed (19474276). He suggested monitoring the state of the input streams as a proxy for upload progress. It may work reasonably well for `AWSS3TrasnferManager`, but for a shared component of the SDK, it may not be the ideal solution.

We will consider adding configuration options for concurrency limit and `HTTPMaximumConnectionsPerHost`. Thank you for your patience.

**Comment by dms90** [comment]
Thanks for the answer. Hope it will be fixed soon.

Please keep in touch.

Thanks!

Regards,
Diego

**Comment by dms90** [comment]
Do you have some update from Apple?

Thanks!

Regards,
Diego

**Comment by yosuke-matsuda** [comment]
The bug report is still open on Apple Bug Reporter. Usually, it takes a while for a report to get resolved.

**Comment by pablogeek** [comment]
@dms90 Anyway You have to write this inside of uploadprogress block:

`
dispatch_async(dispatch_get_main_queue(), ^{
`
For me this is working because I think the progress upload block is not in the ui thread

**Comment by dms90** [comment]
Thanks @pablogeek but I'm still having the error.

@yosuke-matsuda do you have any update from Apple?

Thanks.

Regards,
Diego

**Comment by yosuke-matsuda** [comment]
The case is still open on [Bug Reporter](https://bugreport.apple.com).

**Comment by Colbize** [comment]
Is there an update on this or at least a work around?  I'd like to use taskForCompletionOfAllTasks but I'm having the annoying issue above.

**Comment by dms90** [comment]
Hi Colby,

I decided to implement a custom way to handle it because the bug is still
open :(

Hope someday Apple fixes it.

2015-08-06 19:19 GMT-03:00 Colby Reineke <notifications@github.com>:

**Comment by yosuke-matsuda** [comment]
Apple closed the bug report. iOS 9 fixes the issue. Thanks.

**Comment by shankera** [comment]
Since it's a known bug for Apple, will there be any support from AWS to help support older versions of iOS?

**Comment by yosuke-matsuda** [comment]
You need to update the iOS to address the root cause. You can circumvent the issue by limiting the maximum number of concurrent transfers. The [original poster's solution](http://stackoverflow.com/a/26922681/1721492) is a valid one.
