### ISSUE TITLE
[AWSTask exception]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by nadein** [aws/aws-sdk-ios#911]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
_AWS iOS SDK (AWSCore, AWSDynamoDB)._

* In what version of SDK are you facing the problem?
_2.6.14 (through Cocoapods)._

* Is the issue limited to Simulators / Actual Devices?
_Reproduced both on Simulator and iOS devices._

* Can your problem be resolved if you bump to a higher version of SDK?
_Not sure. It's the latest version on CocoaPods._

* Is this problem related to specific iOS version?
_No._

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
_CocoaPods._

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
_Issue is reproduced while saving or fetching objects to/from DynamoDB._

### Issue info:
I got a message in Xcode console:
`-[AWSTask exception]: unrecognized selector sent to instance 0x17587ac00`
And then application is crashed.

I've tried to prevent it by creating custom extension:
```
extension AWSTask {
    public func exception() {
        print("AWSTask exception method called")
    }
}
```

Then I've got next message and app crash:
`*** Terminating app due to uncaught exception of class 'AWSTask'`

Exception breakpoint stops in method `- (AWSTask *)continueWithExecutor:(AWSExecutor *)executor block:(AWSContinuationBlock)block cancellationToken:(nullable AWSCancellationToken *)cancellationToken`
On line `id result = block(self);`

Stacktrace:
```
#0	0x00000001883a5014 in __pthread_kill ()
#1	0x000000018846f264 in pthread_kill ()
#2	0x00000001883199c4 in abort ()
#3	0x0000000187de51b0 in abort_message ()
#4	0x0000000187dfec04 in default_terminate_handler() ()
#5	0x0000000187e0c820 in _objc_terminate() ()
#6	0x0000000187dfb5d4 in std::__terminate(void (*)()) ()
#7	0x0000000187dfaef8 in __cxa_throw ()
#8	0x0000000187e0c66c in objc_exception_throw ()
#9	0x00000001893b1ef4 in -[NSObject(NSObject) doesNotRecognizeSelector:] ()
#10	0x00000001893aef54 in ___forwarding___ ()
#11	0x00000001892aad4c in _CF_forwarding_prep_0 ()
#12	0x0000000100457708 in __55-[AWSS3ContentProvider GETURLForKey:completionHandler:]_block_invoke ()
#13	0x00000001010381f8 in __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke at /Pods/AWSCore/AWSCore/Bolts/AWSTask.m:331
#14	0x0000000100fddfb8 in __30+[AWSExecutor defaultExecutor]_block_invoke_2 at /Pods/AWSCore/AWSCore/Bolts/AWSExecutor.m:65
#15	0x0000000100fde9e8 in -[AWSExecutor execute:] at /Pods/AWSCore/AWSCore/Bolts/AWSExecutor.m:131
#16	0x00000001010380e0 in -[AWSTask continueWithExecutor:block:cancellationToken:] at /Pods/AWSCore/AWSCore/Bolts/AWSTask.m:368
#17	0x0000000101038900 in -[AWSTask continueWithBlock:] at /Pods/AWSCore/AWSCore/Bolts/AWSTask.m:375
#18	0x0000000100457630 in -[AWSS3ContentProvider GETURLForKey:completionHandler:] ()
#19	0x0000000100455194 in -[AWSContent downloadWithDownloadType:pinOnCompletion:progressBlock:completionHandler:] ()
```

### Update:
I also have AWSMobileHubHelper.framework integrated as static library. It seems it is the source of crash. But how can I update it to the latest version? (It's not presented in CocoaPods specs).

How can I fix this issue?

**Comment by nadein** [comment]
I found `AWSMobilehubHelper` source at [this repo](https://github.com/aws/aws-mobilehub-helper-ios).
But unfortunately can't manage to build a static library (because of building script issue).
So I added it's source to project with the bridging header.
And it's seems to fix my issue.

**Comment by kvasukib** [comment]
Thank you @nadein for reporting to us. Sorry for the inconvenience caused. The Auth component of the AWSMobileHubHelper is moved to the SDK under AWSAuthSDK. What part of the AWSMobileHubHelper are you using? We recommend using AWSAuthSDK for the Auth component.
