### ISSUE TITLE
[Documentation] Is there a schema of all potential configuration for AWS dictionary for Info.plist

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ios#912]
I have been using services independent of MobileHub for a long time and i've been recently seeing a lot of documentation drift over configuration. I can't use mobile hub because i can't figure how to import my existing cognito.  Anyways, i currently have an AWS dictionary in my `Info.plist` with settings for each service, probably through some old guide I used, no idea about how or why. 

Now i'm simply trying to turn on `isAccelerateModeEnabled`, is there a key i can use in the Info.plist like in this example file?

https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/Info.plist#L73

Otherwise i'd have to register it with below per the example from https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-more-transfer-examples

```swift
//Setup credentials
let credentialProvider = AWSCognitoCredentialsProvider(regionType: YOUR-IDENTITY-POOL-REGION, identityPoolId: "YOUR-IDENTITY-POOL-ID")

//Setup the service configuration
let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)

//Setup the transfer utility configuration
let tuConf = AWSS3TransferUtilityConfiguration()
tuConf.isAccelerateModeEnabled = true


//Register a transfer utility object
AWSS3TransferUtility.register(
    with: configuration!,
    transferUtilityConfiguration: tuConf,
    forKey: "transfer-utility-with-advanced-options"
)


//Look up the transfer utility object from the registry to use for your transfers.
let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-utility-with-advanced-options")
```

But now i'm manually setting up a credential provider, should i completely remove my `AWS` dictionary in my plist?  I need to either do everything through code, or through plist, but as of now it's a confusing mess.  Also, what is `awsconfiguration.json`?

**Comment by rromanchuk** [comment]
Ok looks like i answered my question by hunting it down https://github.com/aws/aws-sdk-ios/blob/199553710fac562a4ce10e747d9b4ff25d89ba11/AWSS3/AWSS3TransferUtility.m#L209

I've tried googling, but is there anyway to get these values for each service besides looking at the source?

**Comment by kvasukib** [comment]
Thank you @rromanchuk for reporting to us. Sorry for the inconvenience caused. Currently our documentation lacks the details for the list of keys that are supported through the Info.plist file. We will work on to improve the documentation. 

`awsconfiguration.json` has the configuration information for the backend resources that you have configured and the SDK understands this file much like Info.plist. However, awsconfiguration.json is only limited to the resources configured through the AWS Mobile Hub.

We will update our docs and add more details about Info.plist, awsconfiguration.json, AWSServiceConfiguration and notify this thread. Thank you for the feedback.
