### ISSUE TITLE
AWS IOT sdk for iOS : No way to find if subscription to a topic was failed

### ISSUE THREAD

**Issue by giovazjim** [aws/aws-sdk-ios#919]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IoT

* In what version of SDK are you facing the problem?
2.6.1

* Is the issue limited to Simulators / Actual Devices?
all

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

===================

We have implemented AWS IoT in our iOS app for delivering message payloads over MQTT. We would like to know if when we subscribe to a topic is successful or failed. 
Nowadays the IoT service has a method that allow us to subscribe to a topic which return a boolean to know if the the subscription was successful or failed, but it seems that is not working properly. We deny the privilege to the policy that allows us to subscribe to an specific topic to see if this can cause the failure but when we test it we still get true (Success) as a response of the method but we aren't able to get the callback about the topic, which is correct because we are not subscribe to a valid topic.

Is that behaviour correct??
If that is true, how can we know when a subscription to a topic fail?

Our aim is tho retry on MQTT subscription failures, but we haven't found the way to know when that happen.

By the way our code implementation is similar as in the example provide for you about IoT sample

https://github.com/awslabs/aws-sdk-ios-samples

===================

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by cbommas** [comment]
Hello @giovazjim 

We implemented callbacks for publish and subscribe in the latest rev of the SDK (2.6.18).  See code snippet below

       iotDataManager.subscribe(toTopic: testTopic, qoS: .messageDeliveryAttemptedAtLeastOnce, messageCallback: { (payload) ->Void in
        //callback that is invoked on receipt of a message.
        .....
        ......
        }, ackCallback: {
        //callback that is invoked on confirmation from the server that the subscription has successfully gone through.
        .....
        ......
        })

Please try this and let us know if you run into issues. I am closing this thread, please feel free to reopen if required.

**Comment by giovazjim** [comment]
@cbommas Thanks so much for your help, I've already implemented  :)
