### ISSUE TITLE
How can download a file on S3 multiple times concurrent?

### ISSUE THREAD

**Issue by dproton** [aws/aws-sdk-ios#921]
If I use `content.download( with: policy, pinOnCompletion: pinOnCompletion, progressBlock, completionHandler:)` to download a file on S3 multiple times concurrent, SDK will invoke `completionHandler` with error `AWSContentManagerErrorTypeTransferAlreadyInProgress: Initiated a transfer on a content that is already running.`
How can download a file on S3 multiple times concurrent?
Thanks for your support !

**Comment by minbi** [comment]
Hi @dproton ,

Can you explain your use-case? Why do you need to download the same file multiple times?
Are you trying to propagate copies of the file to multiple places?

**Comment by dproton** [comment]
Example use case: 
User goes to view A. In this view, the app needs to download file a.json. But user exit view A when the downloading still in progress. And after that user re-enters view A. App should download file a.json again. Because we don't have API to cancel the download, so the 2nd downloading process will failed  with error `AWSContentManagerErrorTypeTransferAlreadyInProgress `.

**Comment by kvasukib** [comment]
Are you referring to the [Mobile Hub Helper library] (https://github.com/aws/aws-mobilehub-helper-ios/blob/4a1573af7115788ecf83b27221fe32407c3afe0d/AWSMobileHubHelper/ContentDelivery/AWSContentManager.h#L30)? AWSContentManager is part of the Mobile Hub Helper library. 

We have moved portions of the Mobile Hub Helper library into the AWS iOS SDK. AWSS3TransferUtility in iOS can replace AWSContentManager where we provide the functionality to suspend/resume/cancel the transfers. See [documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html) for further details.
