### ISSUE TITLE
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" 

### ISSUE THREAD

**Issue by David-Madpixel** [aws/aws-sdk-ios#922]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWS iOS SDK (AWSS3TransferUtility)

* In what version of SDK are you facing the problem?

2.6.16 and 2.6.17

* Is the issue limited to Simulators / Actual Devices?

both

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific iOS version?

Not sure, I'm testing on iOS 11.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Prebuilt

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "(null)" 

I tested with several files, and only get this error when I try upload files over 5 GB with AWSS3TransferUtility.  With AWSS3TransferManagerUploadRequest I can upload those files.

```
    AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityUploadTask *task, NSError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            uploadCompletionHandler(error);
        });
    };
    
    AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
    
    [[transferUtility uploadFile:file
                                        bucket:bucket
                                          key:[NSString stringWithFormat:@"%@/%@",directory,[file lastPathComponent]]
                                  contentType:@"application/zip"
                                   expression:expression
                            completionHandler:completionHandler]
     continueWithExecutor:[AWSExecutor mainThreadExecutor]
     withBlock:^id(AWSTask *task)
     {
         if (task.error != nil)
             uploadCompletionHandler(task.error);
         
         return nil;
     }];
```

**Comment by cbommas** [comment]
Hello @David-Madpixel 

Sorry to hear that you are running into issues. I will look into this and get back to you.

**Comment by cbommas** [comment]
Hello @David-Madpixel 

A value of 2 for AWSS3TransferUtilityErrorDomain  indicates that a 4XX error was returned from the server for the request. The latest version of the SDK, 2.6.18, contains logic to propagate additional diagnostic information (thanks to PR https://github.com/aws/aws-sdk-ios/pull/666 submitted by @k4ety ). Can you upgrade to the latest and send me the details of the error? 

See below for a code snippet on how to get the error information

        let errorInfo = err.userInfo["Error"] as? [String: Any]
        if errorInfo != nil {
            print("Found error in response. Details are:")
            for element in errorInfo! {
                print(">> \(element.key): \(element.value)")
            }
       }

**Comment by David-Madpixel** [comment]
Hello. Looks like its a size problem:

    MaxSizeAllowed = 5368709120;
    Message = "Your proposed upload exceeds the maximum allowed size";
    ProposedSize = 7703575944;

With multipart is working.

Thanks.

**Comment by cbommas** [comment]
Thank you for confirming @David-Madpixel
