### ISSUE TITLE
AWS Pinpoint with existing UserPools(in USWest-Oregon)

### ISSUE THREAD

**Issue by guna** [aws/aws-sdk-ios#923]
I have a question using AWS Pinpoint. Currently I have
working AWS backend(DB in N-California region and UserPools in Oregon
Region). Now I would like to start using AWS Pinpoint that is available only
in N.Virginia region. When I create a project into Pinpoint, it
automatically generates a configuration json file that has UserPool in N.Virginia region. 
This creates a conflict in my  awsconfiguration.json file, as my active userPool is in Oregon region.
Do I have to move my userPool to N.Virginia? 

Any help is appreciated.

Thanks

**Comment by minbi** [comment]
Hi @guna ,

Are you using AWS Mobile Hub to configure Pinpoint?

The SDKs do not require that the Cognito User Pool and Pinpoint be in the same region.
