### ISSUE TITLE
SSL failure IOS

### ISSUE THREAD

**Issue by serddmit** [aws/aws-sdk-ios#925]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
2.6.18

* Is the issue limited to Simulators / Actual Devices?
simulators/devices

* Can your problem be resolved if you bump to a higher version of SDK?
no

* Is this problem related to specific iOS version?
no

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
cocoa pods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I have set my device to future date - 2019 year. After that, I tried to log in using UserPool.
I had an error:

Printing description of error:
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1c010c690>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSErrorFailingURLStringKey=https://gwma.auth.eu-west-1.amazoncognito.com/oauth2/authorize

How can I resolve it?
Thanks

**Comment by cbommas** [comment]
Hello @serddmit 

Sorry to hear that you are running into issues. Can you provide a code snippet that we can use to debug this issue further?

**Comment by parthsoni42** [comment]
I am facing same issue while signIn using amplify cognito. please check my debug error.

2020-06-16 16:43:10.381877+0530 Amplify DataStore[11770:225980] Task <C71CE986-EDA0-4C63-A7F6-6C539B489997>.<1> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://cognito-idp.us-east-1.amazonaws.com/, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C71CE986-EDA0-4C63-A7F6-6C539B489997>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C71CE986-EDA0-4C63-A7F6-6C539B489997>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://cognito-idp.us-east-1.amazonaws.com/, NSUnderlyingError=0x60000339a400 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}

Thanks in advance.
