### ISSUE TITLE
AWSPinpointEndpointProfile.setOptOut overrides calls to setting optOut property with a String

### ISSUE THREAD

**Issue by liugrego** [aws/aws-sdk-ios#928]
https://github.com/aws/aws-sdk-ios/blob/7898e71963e77bcddb14168425a33795abfcf70c/AWSPinpoint/AWSPinpointEndpointProfile.h#L57

https://github.com/aws/aws-sdk-ios/blob/7898e71963e77bcddb14168425a33795abfcf70c/AWSPinpoint/AWSPinpointEndpointProfile.m#L117-L124

Attempting to set `AWSPinpointEndpointProfile.optOut` property to a String value from Swift results in a call to `setOptOut` (above) rather than setting the readwrite property as expected. If this is expected behavior, it is artificially limiting and prevents parity with the REST and Java API's. That is, from Java it is easy e.g.

```
EndpointRequest endpointRequest = new EndpointRequest().withOptOut("NONE");
UpdateEndpointRequest request = new UpdateEndpointRequest().withApplicationId(APPLICATION_ID).withEndpointId(endpointId).withEndpointRequest(endpointRequest);
amazonPinpoint.updateEndpoint(request);
```

Would it be possible to enable setting the `optOut` property of `AWSPinpointEndpointProfile` to enable updating endpoint profile's `optOut` status?

Thanks,
Greg

**Comment by kvasukib** [comment]
We have fixed this issue in 2.6.22. Please upgrade and let us know any feedback you have.
