### ISSUE TITLE
Though Re-installing App again, " pool.currentUser()?.isSignedIn " always return "true"

### ISSUE THREAD

**Issue by tushar666** [aws/aws-sdk-ios#933]
Though Re-installing App again, " pool.currentUser()?.isSignedIn " always returning "true", i want user to go for login screen, if user is reinstalling the app again, i know i can detect using custom flag in my app, but just the same thing is possible using AWS

- And also what is the difference between, getUser("+91**********") and getUser(), When to use one appropriately.

**Comment by behrooziAWS** [comment]
isSignedIn is based on whether the user has a refresh token or not which persists app installs in the keychain, it doesn't make any service calls to verify the refresh token is still valid.  There isn't any built-in support to detect whether the app launch is for a reinstall or not.

The difference is that you may not know the username up front.  With interactive authentication, you may need to display a login screen to the user to get their username.  The way you do that is `pool.getUser().getSession()`  you could also do `pool.currentUser().getSession()` if you don't know if the user is authenticated or not yet and have it prompt the user if they aren't.

**Comment by tushar666** [comment]
Thank you for your valuable reply, it was helpful.
