### ISSUE TITLE
Play video files (.m3u8) using AVPlayer directly from S3

### ISSUE THREAD

**Issue by opteamix-ppalanisamy** [aws/aws-sdk-ios#938]
I'm using AWS iOS SDK 2.6. I'm using cocoapods to integrate AWS.
I would like to upload my video files in S3 buckets and manually convert those files as .m3u8 files and store it another S3 bucket. I'm not planning to use AWS cloud front due to my financial restrictions. I've done till this point.

Now i'm trying to play these .m3u8 files from AVPlayer. If i change my access permission to public i can play and if i keep those files as private, i'm not able to play it. 
I do not want to have any user logins in my application. And also i do not want to access my video files from outside of my iOS application. I know i need to configure my bucket in aws.config json and use AWS sdk to access my files.

Problem is i'm trying to load .m3u8 files directly using Avplayer and its not playing due to access denied error.

Could anyone help me how do it?

1. Playing video files from s3 directly without using AWS cloud front
2. Can i extract AWS access key and secret key from AWS credentials (not using AWS authentication. I can see some access key, token are created and printed in xcode console)
3. Can i create a custom request to gain access and directly play it AVPlayer from S3 buckets.
 

Thanks in advance.

**Comment by opteamix-ppalanisamy** [comment]
It might help somone. I can get the AWSCredentials like access key, secret key,etc using below code. 

        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "POOL_ID")
        let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        
        credentialsProvider.credentials().continueOnSuccessWith { (task) -> Any? in
            if (task.error != nil) {
                print("Error: " + task.error!.localizedDescription)
            }
            else {
                let credentials = task.result!
                print("access key = ",credentials.accessKey)
                print("secret key = ",credentials.secretKey)
            }
            return task
        }

Still looking answers for other questions that i have.

**Comment by cbommas** [comment]
hello @opteamix-ppalanisamy 

For your scenario, you could use presigned urls to create short-lived urls that you can pass to the video player. This way, your bucket doesn't have to be public. See https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-ios-s3-presigned-urls.html for more information on how to generate a presigned URL.

**Comment by opteamix-ppalanisamy** [comment]
Thank you cbommas for reply. I have tried to create presigned url using the above example. Still i'm not able to download the s3 file.  I'm using below code

        let getPreSignedURLRequest = AWSS3GetPreSignedURLRequest()
        getPreSignedURLRequest.bucket = "bucketname/protected"
        getPreSignedURLRequest.key = "h264_master.m3u8"
        getPreSignedURLRequest.httpMethod = .GET
        getPreSignedURLRequest.expires = Date(timeIntervalSinceNow: 3600)
        
        AWSS3PreSignedURLBuilder.default().getPreSignedURL(getPreSignedURLRequest).continueWith { (task:AWSTask<NSURL>) -> Any? in
            if let error = task.error as? Error {
                print("Error: \(error)")
                return nil
            }
            
            let presignedURL = task.result
            print("Download presignedURL is: \(String(describing: presignedURL))")
            
// Below code will be replaced by loading the video playlist file in AVPlayer. For testing i have kept below download code.
            let request = URLRequest(url: presignedURL as! URL)
            let downloadTask: URLSessionDownloadTask = URLSession.shared.downloadTask(with: request)
            downloadTask.resume()

return nil;
}

can you please help me where i'm making mistake.

**Comment by cbommas** [comment]
@opteamix-ppalanisamy 

I tried the exact same code on my side and it worked fine. The way I tested it was that I took the link that was printed out in the continueWith block and loaded it from a browser and it downloaded the file successfully.

Can you paste the exact error that you are seeing?

 Also, I see that you are using "Unauth" access of the Identity Pool. Can you share how you have setup the IAM policy on the unauth role?  

In case you need some documentation, look at https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-integrate-an-existing-bucket.html for details on how to setup access to the bucket.

**Comment by cbommas** [comment]
@opteamix-ppalanisamy 

Looks like you may be all set on this issue. I will go ahead and close this - please feel free to reopen if you are still running into problems.

**Comment by hiteshinfostride** [comment]
I am still facing this issue, i'm not sure if it is something related to my AVPlayer. When i hit the preSignedUrl in browser the m3u8 file gets downloaded.
But when i pass the url to my player it does not play anything.

`let videoAsset = AVURLAsset(url: videoURL)
  let playerItem = AVPlayerItem(asset: videoAsset)
  self.player = AVPlayer(playerItem: playerItem)`

Here 'videoURL' is the preSignedUrl. 
Furthermore, When i hit the same url in safari in my iPhone. 
The video remains paused at first frame and never plays even if i click on Play button. 
My AVPlayerItem.Status is 'readyToPlay' but nothing happens if i call player.play()

**Comment by pathakota9966** [comment]
I am also facing the same issue like with preSignedUrl AVPlayer is not playing the videos.
Can anyone help in this regard.
Thanks in advance.
