### ISSUE TITLE
Modify Volume in EC2 missing?

### ISSUE THREAD

**Issue by ssferrazza** [aws/aws-sdk-ios#940]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS EC2

* In what version of SDK are you facing the problem?
2.6.18

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
It seems that the call to modify a volume (see https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVolume.html) is missing in the current version. Is there any workaround available or is this feature on the product roadmap and if so, when will it be available?

Thanks in advance
Sal

**Comment by rohandubal** [comment]
This issue should be fixed with 2.6.20.
