### ISSUE TITLE
Not work sign out function in AWSCognitoAuth.default()

### ISSUE THREAD

**Issue by Bhadresh4488** [aws/aws-sdk-ios#947]
auth.signOut { (error:Error?) in
              if(error != nil){
                   alertWithTitle("Error", message: (error! as NSError).userInfo["error"] as? String)
              }else {
                
                session = nil
                alertWithTitle("Info", message: "Session completed successfully")
            }
            self.refresh()
        }

- I am use this method but can't successfully sign out?
Click sing in button then open safari page & can't ask user name & password why?

**Comment by minbi** [comment]
SFSafariViewController will keep cookies of the user's session and not prompt the user for login. You may use logout URLs to simulate a logout in the view controller.

**Comment by minbi** [comment]
Closing to track in #894

**Comment by Bhadresh4488** [comment]
Give me logout URLs

**Comment by Bhadresh4488** [comment]
also i am clear cookies:
let cookieJar = HTTPCookieStorage.shared
        
        for cookie in cookieJar.cookies! {
            // print(cookie.name+"="+cookie.value)
            
            cookieJar.deleteCookie(cookie)
        }
