### ISSUE TITLE
How to easily convert to iPhone X 

### ISSUE THREAD

**Issue by Prasad018** [aws/aws-sdk-ios#948]
We have developed our iOS application (portrait mode), but it is not compatible with iPhone X, so how can we easily convert to IPhone X, (now the screens are   little bit stretched in width  in iPhone X see the images ...)
So any one can suggest some good methods to solve the issue of converting to iPhone X
(Curretly app is working in all other versions above 5 well, except  iPhone X)

![simulator screen shot - iphone x - 2018-05-31 at 17 37 27](https://user-images.githubusercontent.com/39764890/40781437-87849e94-64f9-11e8-875d-5f69835c1b4a.png)
![simulator screen shot - iphone x - 2018-05-31 at 17 37 44](https://user-images.githubusercontent.com/39764890/40781439-891e0fec-64f9-11e8-9211-09d2f31f043d.png)

**Comment by joshwoods** [comment]
@Prasad018 this has nothing relating to the iOS AWS SDK. This should probably be closed.

**Comment by Prasad018** [comment]
give the correct link to post this

**Comment by joshwoods** [comment]
This is a repository for AWS. Your question is about iOS. Use google to find what you’re looking for.

**Comment by cbommas** [comment]
Closing this issue. 
@Prasad018  Please feel free to post if you have any questions or issues using the AWS SDK.
