### ISSUE TITLE
IoT iOS 9 crash.

### ISSUE THREAD

**Issue by steelzeh** [aws/aws-sdk-ios#949]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IoT

* In what version of SDK are you facing the problem?
2.6.19

* Is the issue limited to Simulators / Actual Devices?
Actual device.

* Can your problem be resolved if you bump to a higher version of SDK?
No higher version of SDK

* Is this problem related to specific iOS version?
Yes i believe it's only iOS 9

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Run the AWS IoT on iOS 9, and try to connect.

self.iotDataManager!.connect(withClientId: uuid, cleanSession: true, certificateId: cert, statusCallback: self.mqttEventCallback)

If run on iOS 9 the following will make it crash: 
+[NSTimer scheduledTimerWithTimeInterval:repeats:block:]: unrecognized selector sent to class 0x39c9ded4

<img width="320" alt="screen shot 2018-06-01 at 08 56 21" src="https://user-images.githubusercontent.com/7465835/40826038-b2804ca8-6579-11e8-855b-3bf043cede03.png">

This API call is only iOS 10+
https://developer.apple.com/documentation/foundation/nstimer/2091889-scheduledtimerwithtimeinterval?preferredLanguage=occ

**Comment by cbommas** [comment]
hello @steelzeh 

Thank you for reporting this issue. I will investigate and get back to you.

**Comment by cbommas** [comment]
@steelzeh 

The fix for this issue will be included in the next rev of the SDK. I will loop back on this thread once the release is completed.

**Comment by aat2703** [comment]
When is the fix scheduled to be released?

**Comment by cbommas** [comment]
@aat2703 

We are looking to get this released next week.

**Comment by aat2703** [comment]
@cbommas okay - We cannot release a new version and fix this issue: https://github.com/aws/aws-sdk-ios/issues/752 because of this. So its really important to get this fixed...

**Comment by cbommas** [comment]
@aat2703 

I understand. I will loop back on this thread once the release is completed.

**Comment by cbommas** [comment]
@aat2703 

We released ver 2.6.21 today (6/5) with the fix. Please try this out and let us know how it goes.

**Comment by steelzeh** [comment]
Seems to be working again, thanks @cbommas

**Comment by cbommas** [comment]
Thank you @steelzeh  for confirming. Please feel free to reopen this thread if you run into further issues.
