### ISSUE TITLE
getAttributeVerificationCode requires authentication

### ISSUE THREAD

**Issue by daviskoh** [aws/aws-sdk-ios#950]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

Cognito

* In what version of SDK are you facing the problem?

latest

* Is the issue limited to Simulators / Actual Devices?

Both

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific iOS version?

No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1) User signs up.
2) `autoConfirmUser` was set to `true` during Signup.
3) User logs out of account w/o verifying their email.
4) User is now unauthenticated and `email_verified` is `false`.
5) User has forgotten their password
7) Allow user to reset or change their password somehow

Ideally, I would just call`forgotPassword()`, but it seems to require a verified email which is understandable. So, i am calling `getAttributeVerificationCode("email")`, to have the User verify their email before attempting `forgotPassword()`, but this triggers `startPasswordAuthentication()` in my `AWSCognitoIdentityInteractiveAuthenticationDelegate`.

Is this by design? Why would authentication be required to verify an email? If the User knew their password, they wouldnt need to do `forgotPassword()` in the first place. There is no error returned from `getAttributeVerificationCode("email")` either before it triggers the Auth flow.

Questions:

1) Is the user completely locked out of their account in this case?

2) Is there some sort of workaround possible? This is a very common use-case as almost all apps I know of allow an unauthenticated user to reset their password via email even if it is unverified. 

3) If email verification is so crucial that unverified accounts will break functionality, why isnt a verification code being send on signup?

4) At the very least, is there a way to let the user know they are locked out? Simply having the `startPasswordAuthentication()` flow triggered, there is no current way to know that this is happening.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by daviskoh** [comment]
...

**Comment by daviskoh** [comment]
unbelievable...

**Comment by minbi** [comment]
Hi @daviskoh ,

Sorry for the delayed response. The guidance for this use-case is that when a user forgets their password and the developer wants to allow the user to self-serve through forgot password flow, they should already have a verified email address. This means that email should be required during sign-up or shortly after the sign-in to allow the user to use forgot password flow. Otherwise, the developer would have to manually reset the user's password.

**Comment by ankitnaugariya** [comment]
As of now, Cognito allows sending codes for forgot password only to verified email / phone. If these are not verified, the codes are not sent. This seemed to have been done for security reasons.
As @minbi mentioned, developers can ask users to confirm their email / phone after signup.
Another way to implement forgot password flow for the users is to call AdminUpdateUserAttribute to mark phone / email as verified, then allow user to reset the password. Later, after reset is done, the attribute can be marked unverified again using the same API call.
