### ISSUE TITLE
S3 crash on iPhone 4S using multi part upload

### ISSUE THREAD

**Issue by ppamorim** [aws/aws-sdk-ios#954]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using? S3

* In what version of SDK are you facing the problem? 2.6.17

* Is the issue limited to Simulators / Actual Devices? Only iPhone 4S

* Can your problem be resolved if you bump to a higher version of SDK? Not tested

* Is this problem related to specific iOS version? No idea, but crashed on iOS 9.3.5.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

```
Crashed: NSOperationQueue 0x147d8bb0 :: NSOperation 0x158e0be0 (QOS: LEGACY)
0  My_App                         0x18920c UploadManagerImpluploadPart empty-list Realmrealm first-element-marker IntuserIdIntidAtServerStringfileNameOnDeviceNSData?dataAWSS3s3IntpartNumberIntfileSizeIntbytesOffsetStringbucketStringkeyStringuploadId empty-list String (UploadPart.swift:98)
1  My_App                         0x18a868 UploadManagerImpluploadPart empty-list Realmrealm first-element-marker IntuserIdIntidAtServerStringfileNameOnDeviceNSData?dataAWSS3s3IntpartNumberIntfileSizeIntbytesOffsetStringbucketStringkeyStringuploadId empty-list String (UploadPart.swift)
2  My_App                         0x18a868 UploadManagerImpluploadPart empty-list Realmrealm first-element-marker IntuserIdIntidAtServerStringfileNameOnDeviceNSData?dataAWSS3s3IntpartNumberIntfileSizeIntbytesOffsetStringbucketStringkeyStringuploadId empty-list String (UploadPart.swift)
3  My_App                         0x195d14 Int64 (SingleUpload.swift)
4  AWSCore                        0x81cdc1 -[AWSURLSessionManager URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:] (AWSURLSessionManager.m:401)
5  CFNetwork                      0x2164124d __86-[NSURLSession delegate_task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:]_block_invoke + 64
6  Foundation                     0x21869679 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
7  Foundation                     0x217ca5f3 -[NSBlockOperation main] + 146
8  Foundation                     0x217bcbc9 -[__NSOperationInternal _start:] + 768
9  Foundation                     0x2186b931 __NSOQSchedule_f + 192
10 libdispatch.dylib              0x20bd2423 _dispatch_queue_drain$VARIANT$mp + 1758
11 libdispatch.dylib              0x20bd1a61 _dispatch_queue_invoke$VARIANT$mp + 284
12 libdispatch.dylib              0x20bd415d _dispatch_root_queue_drain + 396
13 libdispatch.dylib              0x20bd3fcd _dispatch_worker_thread3 + 96
14 libsystem_pthread.dylib        0x20d89b29 _pthread_wqthread + 1024
15 libsystem_pthread.dylib        0x20d89718 start_wqthread + 8
```

Code sample:

```swift
let uploadPartRequest = AWSS3UploadPartRequest()

//More config of uploadPartRequest...

uploadPartRequest.uploadProgress = { bytesSent, tBytesSent, _ in

    internalPartBytesSent += Int(bytesSent)
    let progress = Int((internalPartBytesSent * 100) / fileSize)
    if oldUploadProgressPercentage < progress && possibleRange ~= progress {
        oldUploadProgressPercentage = progress
        //Continue...
    }

}

s3.uploadPart(uploadPartRequest)
    .continueWith(block: { task in
    //Continue...
    }
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by ppamorim** [comment]
@cbommas Probably related to #913 ?

**Comment by cbommas** [comment]
@ppamorim 

It is possible - Are you seeing the "Fatal Exception: Task created in a session that has been invalidated" message in your logs.  I would recommend updating to the latest revision of the SDK and seeing if that resolves the issue.

**Comment by ppamorim** [comment]
@cbommas I will check. Thanks.

**Comment by cbommas** [comment]
thanks @ppamorim. Please let me know what you find.

**Comment by ppamorim** [comment]
I need to send the app to production first to check if the problem has been solved. I was not able to replicate on two iPhone 4s I have here unfortunately.

**Comment by cbommas** [comment]
@ppamorim 
Any updates?

**Comment by ppamorim** [comment]
Not yet, still waiting Apple review.

**Comment by ppamorim** [comment]
@cbommas Seems to be solved. I will close it.

**Comment by cbommas** [comment]
@ppamorim Thank you very much for confirming!
