### ISSUE TITLE
API Gateway SDK Generation is broken

### ISSUE THREAD

**Issue by JohnyBeG** [aws/aws-sdk-ios#956]
Hi,

When the SDK generation will be available ? Currently the link is broken.
Will it be available for Swift 4 ?

Regards

**Comment by rohandubal** [comment]
which link are you mentioning? 

Currently there is a workaround which you can use as mentioned here: #916

**Comment by JohnyBeG** [comment]
Sorry. I didn't know.
The link is from the aws api gateway console.

What service are you using?
API Gateway.

In what version of SDK are you facing the problem?
Not from the SDK but from the aws api gateway console

Is the issue limited to Simulators / Actual Devices?
None

Can your problem be resolved if you bump to a higher version of SDK?
No actually.

Is this problem related to specific iOS version?
Doesn't seem to be.

How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods.

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
It's the same issue as this one. The developer who filed that issue closed it because of the workaround discussed in the comments but the generated SDK remains broken (see comment).

The problem is when I try to generate the api gateway SDK from a deployed api. I try to generate it in swift but it always said that the link is broken (404 error).

**Comment by rohandubal** [comment]
Let me investigate what is going on with the generation in console and get back to you.

**Comment by JohnyBeG** [comment]
Ok. I understant where the problem is : it's from Safari navigator (i don't know why).
It works fine from Google Chrome.

Sorry for the disturbing and thank you for your help

**Comment by cbommas** [comment]
Closing the issue. @JohnyBeG, please feel free to reopen if you run into further issues.
