### ISSUE TITLE
Feature Request: Cognito "InitiaateAuth" request allowed custom "scopes" in AccessToken

### ISSUE THREAD

**Issue by tomjanne** [aws/aws-sdk-ios#958]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Cognito

Hello, 

we are currently using a Cognito User Pool for authenticating our Application Users. These are accessing an Amazon API Gateway secured by a Cognito Authorizer with OAuth (custom) scopes. 

At first we tried using the Android sdk from your Documentation 
https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html

But then we were facing the issue, that we have no possibility to define a "scope" parameter to retrieve also other custom scopes in the "AccessToken" returned by the CognitoUserSession. In the returned access token is always set the "aws.cognito.signin.user.admin" as scope paramater only.

After some further looking into the SDK, we found out, that the API call is done with the InitateAuth action and the AuthFlow USER_SRP_AUTH.
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html

Would it be possible to request also a custom "scope" to be set in the AccessToken which is enabled for the given ClientId.
For example something like this for the InitiateAuth action: 

{
   "AnalyticsMetadata": { 
      "AnalyticsEndpointId": "string"
   },
   "AuthFlow": "string",
   "AuthParameters": { 
      "string" : "string" 
   },
   "Scope": "string",
   "ClientId": "string",
   "ClientMetadata": { 
      "string" : "string" 
   },
   "UserContextData": { 
      "EncodedData": "string"
   }
}

I know we could do it using the Cognito Auth SDK (aws-android-sdk-cognitoauth) following the OAuth 2 Flow with browser redirection. But we wanted to do it in-app without popping to the browser.

With kind regards
Tom Janne

**Comment by fcouceiro** [comment]
I am also experiencing this. 
I do not understand why "aws.cognito.signin.user.admin" is the only scope included in the token even though I did not enable it on app client settings. This makes it rather difficult to interact with an API Gateway resource (read impossible), for our use case, where API Gateway resources require certain custom scopes to be present.

**Comment by hanslai** [comment]
The problem of not getting the OAuth2 scopes are still here.  new issue #3732

**Comment by rupertlssmith** [comment]
Seems to have been fixed on Cognito User Pools: https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cognito-user-pools-customize-access-tokens/
