### ISSUE TITLE
Making queries using Swift

### ISSUE THREAD

**Issue by obmayes** [aws/aws-sdk-ios#96]
I'm trying to implement this SDK into iOS using Swift. I've managed to set my project up and am able to query a table, however I am stuck at how to get an element from the query response. Are there any guides or sample projects on performing queries using Swift?

**Comment by yosuke-matsuda** [comment]
We've released the Swift version of the [Amazon DynamoDB Object Mapper sample app](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/DynamoDBObjectMapper-Sample/Swift) in our sample app repo. Hope it helps.
