### ISSUE TITLE
S3TransferUtility Upload failed. SSL Error

### ISSUE THREAD

**Issue by mpirogov** [aws/aws-sdk-ios#963]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSS3/Transferutility(including MultipartUpload)

* In what version of SDK are you facing the problem?
2.6.18 ~ 2.6.21
* Is the issue limited to Simulators / Actual Devices?
Actual Devices
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

small size files are almost working.
big size files are not working.

error screenshot:
![error_screenshot](https://user-images.githubusercontent.com/19306638/41449295-d89d1072-7025-11e8-9f0d-cded7bdfa8c2.png)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by cbommas** [comment]
@mpirogov 

Sorry to hear that you are running into issues. Can you provide some more details about your scenario and share a code snippet if possible. Also if you could share details about where your bucket is located and any specific settings ( such as serverside encryption, bucket acceleration), that would help in debugging this further. 

The 1200 means that ATS is rejecting the SSL handshake. See https://medium.com/@YogevSitton/how-to-fix-ios-9-ats-ssl-error-when-your-server-supports-tls-version-1-2-fd93b219853e for more details around this issue in general. One experiment that we can try to validate that this is the case is by including the following in your info.pllist and see if the error goes away.

    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
          <key>amazonaws.com</key>
          <dict>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
          </dict>
          <key>amazonaws.com.cn</key>
          <dict>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
          </dict>
      </dict>
  </dict>

Please try this and let me know. I will be able to work with you on a path forward on how to correctly address this error.

**Comment by mpirogov** [comment]
I already have done it.

**Comment by mpirogov** [comment]
I have attached my info.plist.
What do you need more from me?

**Comment by cbommas** [comment]
Thanks, that should rule out any ATS related issues. How are you getting the credentials? Are you using Cognito/using static credentials? Also, where is your bucket located?

**Comment by mpirogov** [comment]
bucket located in USEAST1.
static credentials

**Comment by mpirogov** [comment]
ohh sorry.

**Comment by mpirogov** [comment]
I have attached one screenshot.
![info_plist 2](https://user-images.githubusercontent.com/19306638/41482166-664152b4-70dd-11e8-90b4-fda0779ac8d6.png)

**Comment by cbommas** [comment]
Excellent, everything looks good. I was basically looking to see what the credentials expiry was; since you are using Cognito identity pool, expiry is not an issue as the credentials will be refreshed as needed.

Can you setup retries for the TransferUtility to see if the issue is being caused by transient errors. By default, it is set to 0, but you change it to a different value. See sample code below

    //Setup credentials
     let credentialProvider = AWSCognitoCredentialsProvider(regionType: YOUR-IDENTITY-POOL-REGION, identityPoolId: "YOUR-IDENTITY-POOL-ID")

    //Setup the service configuration
    let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialProvider)

    //Setup the transfer utility configuration
    let tuConf = AWSS3TransferUtilityConfiguration()
    tuConf.retryLimit = 5

    //Register a transfer utility object
    AWSS3TransferUtility.register(
        with: configuration!,
        transferUtilityConfiguration: tuConf,
        forKey: "transfer-utility-with-advanced-options"
    )


    //Look up the transfer utility object from the registry to use for your transfers.
    let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "transfer-utility-with-advanced-options")

Let me know how it goes.

**Comment by mpirogov** [comment]
thank you. 
I also coded it.
![appdelegate_m](https://user-images.githubusercontent.com/19306638/41482817-78220c42-70df-11e8-960f-628892167024.png)

**Comment by mpirogov** [comment]
from ago 2years, I worked with aws sdk.
whenever new release, I always upgrade as new.
recently I am getting these missing upload issues from our customers.

**Comment by mpirogov** [comment]
sorry, I am not sure what is certain.
maybe after multipart upload version.
from ago about 40 days

**Comment by cbommas** [comment]
I ran a bunch of tests locally and saw instability whenever I increased the `timeoutIntervalForResource` on the transferUtilityConfiguration beyond 50 minutes. 

The credentials generated by Cognito are valid for 50 minutes and setting the `timeoutIntervalForResource`greater than that may be causing the issue. I will do some more testing on my side to dive further into this. Can you try this on your side as well and let me know how it goes?

**Comment by mpirogov** [comment]
Thank you. I will try on my side.

**Comment by mpirogov** [comment]
when you have anything, can you let me know?
Thank you.

**Comment by cbommas** [comment]
Will do. The internal test I'm running uploads a 3.3G file using a simulator and so far, 5+ attempts, every run with a value greater than 50 minutes for `timeoutIntervalForResource` is failing and every run with a value less than or equal to 50 minutes is passing.

**Comment by mpirogov** [comment]
I am testing with my app.
when I upload a image/video, it is working well.
when I upload multiple images/videos with multi thread, it is not working well.
max file size is not exceed than 3Gbytes.

**Comment by mpirogov** [comment]
hello 
any suggestion or solution?

**Comment by cbommas** [comment]
@mpirogov 

Were you able to try with the `timeoutIntervalForResource` set to a lower value? Did that make things better.

With regards to the multi-threaded scenarios, I've tried to reproduce them on my side, but haven't been able to see any SSL handshake issues. Can you provide some more details about your scenario - specifically around how you creating the transfer utility client (are you using one instance or many instances), does the SSL error only happen on certain types of transfer ( upload only or multipart only) etc.

**Comment by mpirogov** [comment]
- (void) startDataUpload:(NSData *)data contentType:(NSString *)contentType
{
    if(self.status == UPLOAD_SUCCESS) {
        NSLog(@"ignoring upload, has successed for %@\n", _fileName);
        return;
    }
    
    if(self.status == UPLOAD_CANCELLED) {
        NSLog(@"ignoring upload, was cancelled for %@\n", _fileName);
        return;
    }

    AppDelegate *appDel = (AppDelegate*)[[UIApplication sharedApplication] delegate];
    [appDel updateProgress];

            
            //[[[AWSS3TransferUtility defaultS3TransferUtility] getUploadTasks] continueWithBlock:^id(AWSTask<NSArray<AWSS3TransferUtilityUploadTask*> *> *tasks) {
            [[[AWSS3TransferUtility S3TransferUtilityForKey:S3TransferUtility] getUploadTasks] continueWithBlock:^id(AWSTask<NSArray<AWSS3TransferUtilityUploadTask*> *> *tasks) {
                
                for(AWSS3TransferUtilityUploadTask * task in tasks.result)
                {
                    if ( task.sessionTask.error ) {
                        
                        NSLog(@"Found task %ld Error.", (long)task.taskIdentifier);
                        
                    } else {
                        if(task.taskIdentifier == _savedUploadIdentifier) {
                            NSLog(@"Found task %ld for %@, no need to  start again NsData.", (long)_savedUploadIdentifier, self.fileName);
                            
                            dispatch_async(dispatch_get_main_queue(), ^{
                                
                                self.uploadTask = task;

                            });
                            return nil;
                        }
                        
                    }
                }
                
                NSLog(@"Fresh task %ld for data %@.", (long)self.uploadTask.taskIdentifier, self.fileName);
                
                //AWSS3TransferUtility *transfterUtility = [AWSS3TransferUtility defaultS3TransferUtility];
                AWSS3TransferUtility *transfterUtility = [AWSS3TransferUtility S3TransferUtilityForKey:S3TransferUtility];
                
                [[transfterUtility uploadData:data bucket:S3BucketName key:self.fileName contentType:contentType expression:[self uploadExpression]  completionHandler:self.completionHandler] continueWithBlock:^id(AWSTask *task) {
                    
                    if ( task.error ){
                        NSLog(@"Error: %@", task.error);
                        dispatch_async(dispatch_get_main_queue(), ^{
                            
                            [self retryUpload];

                        });
                        
                        
                    } else {
                        
                        NSLog(@"Uploading Data task %ld for data %@.", (long)self.uploadTask.taskIdentifier, self.fileName);
                        
                        dispatch_async(dispatch_get_main_queue(), ^{
                            
                            _uploadTask = task.result;
                            
                            [appDel saveSelectedArray];
                        });
                    }
                    
                    return nil;

                }];
                
                return nil;
            }];
            
            NSLog(@"upload complete\n");


    
}


- (void) startFileUpload:(NSURL *)url contentType:(NSString *)contentType
{
    // update progress now we know asset size.
    AppDelegate *appDel = (AppDelegate*)[[UIApplication sharedApplication] delegate];
    
    [appDel updateProgress];

        //[[[AWSS3TransferUtility defaultS3TransferUtility] getUploadTasks] continueWithBlock:^id(AWSTask<NSArray<AWSS3TransferUtilityUploadTask*> *> *tasks) {
        [[[AWSS3TransferUtility S3TransferUtilityForKey:S3TransferUtility] getUploadTasks] continueWithBlock:^id(AWSTask<NSArray<AWSS3TransferUtilityUploadTask*> *> *tasks) {
            
            for(AWSS3TransferUtilityUploadTask * task in tasks.result)
            {
                
                if ( task.sessionTask.error ) {
                    
                    NSLog(@"Found task %ld Error.", (long)task.taskIdentifier);
                    
                } else {
                    if(task.taskIdentifier == _savedUploadIdentifier) {
                        NSLog(@"Found task %ld for %@, no need to  start again NsData.", (long)_savedUploadIdentifier, self.fileName);
                        
                        dispatch_async(dispatch_get_main_queue(), ^{
                            
                            self.uploadTask = task;
                            
                        });
                        return nil;
                    }
                    
                }
                
            }
            
            NSLog(@"Fresh task %ld for file %@.", (long)self.uploadTask.taskIdentifier, self.fileName);
            
            
            //AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
            AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:S3TransferUtility];
            
            [[transferUtility uploadFile:url bucket:S3BucketName key:self.fileName contentType:contentType expression:[self uploadExpression] completionHandler:self.completionHandler] continueWithBlock:^id(AWSTask * task){
                
                if ( task.error ){
                    NSLog(@"Error: %@", task.error);
                    
                    dispatch_async(dispatch_get_main_queue(), ^{
                        
                        [self retryUpload];

                    });
                } else {
                    
                    NSLog(@"Uploading File task %ld for data %@.", (long)self.uploadTask.taskIdentifier, self.fileName);
                    
                    dispatch_async(dispatch_get_main_queue(), ^{
                        
                        _uploadTask = task.result;
                        
                        [appDel saveSelectedArray];
                        
                    });
                    
                }
                return nil;
                
            }];
            return nil;
        }];
        
        NSLog(@"upload complete\n");
}
above my code snippet.
I have not yet tried with multipart.

**Comment by mpirogov** [comment]
do you need more details?
can you let me know what is the best value for timeoutIntervalForResource?
mine is now 7200.

**Comment by cbommas** [comment]
Change the `timeoutIntervalForResource` to 3000. Cognito sets the credentials it provides with a 50 minute expiry, so staying within/at that limit is good.

**Comment by mpirogov** [comment]
Thank you @cbommas 
I will try it, let you know.

**Comment by mpirogov** [comment]
@cbommas 

Thank you for your advise.
I have configured it to 3000.
it is good for upload only.
but multipart is bad, getting same issue.
multipart is still in improvement? I thought it is a good solution for upload big files.

and one thing.
sometimes I am getting an another issue "storage full" when upload files.
can you give me any advise for storage full issue?

Thank you for your help.

**Comment by cbommas** [comment]
@mpirogov 

The best way to know if a transfer succeeded or failed is by using the completion handler mechanism. Checking the underlying NSURLSessionTask for the status of completion is not the recommended way as it may not work in all cases. I am working on improving the statusing mechanism for a future rev of the SDK, but for now it would be good to use the completion handler.

I am curious about how you are doing this for multipart transfers as it uses multiple NSURLSessionTasks under the covers. Can you provide a code snippet?

Also, for the storage full error, can you provide a stack trace?

**Comment by baileycolbert** [comment]
@cbommas 
sorry to late.
I will provide a stack trace and details soon.
thank you.

**Comment by mpirogov** [comment]
@cbommas 
Sorry to late.
I will soon provide a stack trace and details for storage full error.
I am getting same issue on android.(Android sdk version 2.6.19)
now I have downgraded to 2.4.3 (android) and watching it now.
Thank you.

**Comment by rohandubal** [comment]
Hello @mpirogov 

Could you open a separate issue for Android? Also for the storage error, might be best to open a separate issue since it might help other users in discovery.

**Comment by cbommas** [comment]
@mpirogov 

As suggested by @rohandubal, please create separate issues for the Android and the Storage Error. 
As mentioned previously, we have added support for getting status information more easily from a transfer utility task. The latest version of the SDK (2.2.23) has a convenience method to get the status of an ongoing transfer 

- `status`: to get the current status of the transfer. Returns an enumeration of type `AWSS3TransferUtilityTransferStatusType`

Please try this out and let us know how it goes.

**Comment by mpirogov** [comment]
@cbommas 
Great.

**Comment by cbommas** [comment]
@mpirogov 

Checking back to see if this worked for you.

**Comment by mpirogov** [comment]
@cbommas 
sorry to late.
I am still investigating with real users.
it will takes much delay.
will let you know as possible as soon.
thank you.

**Comment by cbommas** [comment]
@mpirogov 
Take a look at the testUploadAndDownloadData in AWSS3TransferUtilityTests.swift. This line https://github.com/aws/aws-sdk-ios/blob/34cb80c57f6b8b57bbbe92530c2aab999f9eba6f/AWSS3Tests/AWSS3TransferUtilityTests.swift#L119 shows an example of how to get and use the status.

**Comment by mpirogov** [comment]
Thank you @cbommas 
I implemented already.
I am still in investigating with users.
I will let you know soon.
Thanks again.

**Comment by cbommas** [comment]
@mpirogov Thanks!

**Comment by mpirogov** [comment]
Hi @cbommas 
I have investigated with users.
can not get this issue.
it is working now.
you can close my issue.
Thank you for your help.

**Comment by cbommas** [comment]
@mpirogov 

Great to hear! Please feel free to comment back here if the issue crops up again.
