### ISSUE TITLE
CPU too high when connection lost

### ISSUE THREAD

**Issue by sangios** [aws/aws-sdk-ios#971]
Dear all,

The case that after connects MQTT successfully, you will see CPU usage too high when turns off wifi, or in airplane mode, or no internet connection.

while (self.runLoopShouldContinue in - (void)openStreams:(id)sender of AWSIoTMQTTClient.m never exits. Also "[runLoopForStreamsThread runMode:NSDefaultRunLoopMode beforeDate:[NSDate distantFuture]];" without input source will make cpu too high.

PODS:

Alamofire (4.7.2)
AWSCore (2.6.22)
AWSIoT (2.6.22):
AWSCore (= 2.6.22)

**Comment by rohandubal** [comment]
Hello @sangios 

Thanks for reporting this. I will investigate this further and reply back to you. Are you noticing this behavior for specific devices / OS versions?

Thanks,
Rohan

**Comment by sangios** [comment]
I think all of iOS version

**Comment by sangios** [comment]
@rohandubal There is one more case that will cause the CPU usage too high as step belows:
- connect to mqtt successful
- app enters background
- wait for about 60 seconds
- open app again
- cpu is too high after that

**Comment by cbommas** [comment]
Closing this issue as we are tracking it in #968
