### ISSUE TITLE
Disconnect error: DUPLICATE_CLIENT_ID

### ISSUE THREAD

**Issue by aat2703** [aws/aws-sdk-ios#972]
Some of our customers is experiencing disconnects which is causing some sockets to not reach our application. 

All errors is logged to CloudWatch all with the same error: DUPLICATE_CLIENT_ID even though every time we instantiate connect() method a new uuid is generated? 

Do you guys have any clue what the issue can be?

<img width="652" alt="duplicate" src="https://user-images.githubusercontent.com/10488234/41970065-bb77cba2-7a09-11e8-8f71-fedc78ffa877.png">

<img width="855" alt="code" src="https://user-images.githubusercontent.com/10488234/41970167-276d1e70-7a0a-11e8-9252-00e982b8d346.png">

* What service are you using?

AWS IoT

* In what version of SDK are you facing the problem?
2.6.21

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
Really bad at version 9.3.x but also happening on higher versions

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

**Comment by aat2703** [comment]
@cbommas

**Comment by steelzeh** [comment]
@cbommas any news on this?

**Comment by cbommas** [comment]
@steelzeh @aat2703 

Version 2.6.23 was released yesterday ( july 5) and contains the fixes for this issue.
Please upgrade to this version and let me know how it goes.

**Comment by cbommas** [comment]
@aat2703 @steelzeh 

Closing this issue as we are tracking it in #965
