### ISSUE TITLE
AWSSignInManager.resumeSession completionHandler not called with google sign in error

### ISSUE THREAD

**Issue by wfan9** [aws/aws-sdk-ios#974]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Mobile SDK
* In what version of SDK are you facing the problem?
2.6.22
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Using AWSSignInManager.resumeSession() (programming in SWIFT), with AWSGoogleSignInProvider. When there is no error, the completion handler passed to resumeSession() gets called as expected. In the case of an error from the google sign in, the error is output to the log, but the completion handler is never called with the error.

From debugging, it looks like the following code (AWSGoogleSignInProvider.m:190-210) is where there is a difference in treatment of successful sign in, and errors in sign in.

```swift
- (void)signIn:(GIDSignIn *)signIn didSignInForUser:(GIDGoogleUser *)user withError:(NSError *)error {
    // `self.taskCompletionSource` is used to return `user.authentication.idToken` or `error` to the `- token` method.
    // See the `AWSIdentityProvider` section of this file.
    if (error) {
        AWSDDLogError(@"Error: %@", error);
        if (self.taskCompletionSource) {
            self.taskCompletionSource.error = error;
            self.taskCompletionSource = nil;
        }
        if (self.completionHandler) {
            self.completionHandler(nil, error);
        }
    } else {
        if (self.taskCompletionSource) {
            self.taskCompletionSource.result = user.authentication.idToken;
            self.taskCompletionSource = nil;
        }
        [self completeLoginWithToken];
    }
    dispatch_semaphore_signal(self.semaphore);
}
```
The code path for resumeSession() doesn't set self.taskCompletionSource or self.completionHandler, so in the case of an error, it is only output to the log. When there is no error, completeLoginWithToken() is called, which calls AWSSignInManager.completeLoginWithToken(), which calls the completion handler passed to resumeSession().

The error here needs to make its way back to the completion handler that was passed to resumeSession().

**Comment by rohandubal** [comment]
Hello @wfan9 

Thanks for reporting this. You are right, it needs to be surfaced. I am marking this as a bug in the SDK and discuss with the team when to prioritize it.

Thanks,
Rohan

**Comment by doctorcolinsmith** [comment]
Is there any way to get this re-opened?  This bug is still a problem for our app.
