### ISSUE TITLE
Host is not updated when changing S3 configurations 

### ISSUE THREAD

**Issue by orenyaar** [aws/aws-sdk-ios#976]
Hi,

* What service are you using?
AWS iOS SDK

* In what version of SDK are you facing the problem?
v2.4.12

* Is the issue limited to Simulators / Actual Devices?
Actual devices.

* Can your problem be resolved if you bump to a higher version of SDK?
No, I tried 2.6.22 and it reproduces there as well.

* Is this problem related to specific iOS version?
No.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1. Login with a user A (my app context) and try to retrieve a file in S3.
2. Configure SBAWSConfigurationsModel with us-east-1 region.
3. Use AWSS3GetObjectRequest with bucket, key, customer key and AES256 customer algorithm.
4. Use AWSS3.default with getObject:completionHandler method.
5. Download the file - got it successfully.
6. Logout from A and login with user B (**don't kill the app**).
7. Try to download other file from other region: eu-central-1.
8. Request fails with this error:
"Message=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., Code=PermanentRedirect, Endpoint=###########.s3.amazonaws.com}" (# hide my real bucket).
9. Notice that kill the process and try again with the same last configurations - file was downloaded successfully.

The different between user A and B:
1. Bucket name.
2. Region (one in eu-central-1 and one in us-east-1).

I noticed, in verbose mode, that the host is not updated when changing S3 configurations and the points to the previous user's region.

Please help me with this issue..
Thanks!

**Comment by rohandubal** [comment]
Hi, 

The recommended way to handle this would not be to share the same client, but rather use the `register:withKey` method and then register different client for different regions. You can have different clients for different regions and that should resolve the issue.

Thanks,
Rohan

**Comment by orenyaar** [comment]
Thanks @rohandubal !! 👍
