### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

### ISSUE THREAD

**Issue by tzzen93** [aws/aws-sdk-ios#977]
How to calculate aws signature in swift 3? 

My calculation is below. Could you please kindly check it? I got "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details." message for authorization. 

func getAuthorization(request: URLRequest, secretSigningKey: String, accessKeyId: String) -> String? {
        var signedRequest = request
        let date = iso8601()
        guard let bodyData = signedRequest.httpBody, let body = String(data: bodyData, encoding: .utf8), let url = signedRequest.url, let host = url.host
            else { return .none }
        
        signedRequest.addValue(host, forHTTPHeaderField: "Host")
        signedRequest.addValue(date.full, forHTTPHeaderField: "X-Amz-Date")
        
        guard let headers = signedRequest.allHTTPHeaderFields, let method = signedRequest.httpMethod
            else { return .none }
        let signedHeaders = headers.map{ $0.key.lowercased() }.sorted().joined(separator: ";")
        
        let canonicalRequestHash = [
            method,
            url.path,
            url.query ?? "",
            headers.map{ $0.key.lowercased() + ":" + $0.value }.sorted().joined(separator: "\n"),
            "",
            signedHeaders,
            body.sha256()
            ].joined(separator: "\n").sha256()
        
        let credential = [date.short, awsRegion, serviceType, aws4Request].joined(separator: "/")
        
        let stringToSign = [
            hmacShaTypeString,
            date.full,
            credential,
            canonicalRequestHash
            ].joined(separator: "\n")
        
        guard let signature = hmacStringToSign(stringToSign: stringToSign, secretSigningKey: secretSigningKey, shortDateString: date.short)
            else { return .none }
        
        let authorization = hmacShaTypeString + " Credential=" + accessKeyId + "/" + credential + ", SignedHeaders=" + signedHeaders + ", Signature=" + signature
        print("Authorization \(authorization)")
        return authorization
    }

**Comment by rohandubal** [comment]
Hi @tzzen93 

Are you implementing your own signing solution? What is the use-case which prompts you to not use our iOS SDK? 

You can take a dependency on `AWSCore` and use the Signature utility from this class: https://github.com/aws/aws-sdk-ios/blob/91426a8faf782cbae1f1ee60f217adac5534047b/AWSCore/Authentication/AWSSignature.h#L36 

I am closing this issue as the issue about your signature is not part of the project. I suggest you post it on AWS Forums. 

Thanks,
Rohan

**Comment by tzzen93** [comment]
Hi Thanks for your replying
