### ISSUE TITLE
AWSS3TransferUtility Acceleration not working when deleting and installing the app.

### ISSUE THREAD

**Issue by shashank-rps** [aws/aws-sdk-ios#980]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSCore | AWSCognito | AWSS3

* In what version of SDK are you facing the problem?
2.6.22

* Is the issue limited to Simulators / Actual Devices?
NO

* Can your problem be resolved if you bump to a higher version of SDK?
NO

* Is this problem related to specific iOS version?
NO

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

The issue is with Amazon `AWSS3TransferUtility` acceleration. If I enable acceleration in the existing app everything works fine. Now if I uninstall the app and install again then the video upload to the bucket does not work. If I relaunch the app again with same configurations everything works fine.

On debugging the issue I found out that the first time after reinstalling the app, the secretKey and accessKey is new (which does not work and fails the upload) and when I launch again the secretKey and accessKey are different from the previous one and it remains same for the rest of the sessions (with this new secretKey and accessKey combination, upload is fine).

 I guess the issue is with the **secretKey** and **accessKey** which gets stored in AWSKeyChain.  

The code I am using in `didFinsihLaunchingWithOptions:`  
``` AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:AMAZON_POOL_ID];
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionAPSoutheast1 credentialsProvider:credentialsProvider];
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;  
    AWSS3TransferUtilityConfiguration *transferConfig = [[AWSS3TransferUtilityConfiguration alloc] init];
    transferConfig.accelerateModeEnabled = YES;
    transferConfig.bucket = AMAZON_UPLOAD_BUCKETNAME;
    [AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:configuration transferUtilityConfiguration:transferConfig forKey:kUSEast1S3TransferUtility];
```

This issue is reproducible every time. (Currently using - iPhone X, iOS- 11.3.1)

**Comment by rohandubal** [comment]
Are you using `CognitoIdentity` for your auth mechanism? Could you call `clearCredentials()` on cognito identity client when your app launches to see if this error goes away?

Thanks,
Rohan

**Comment by shashank-rps** [comment]
No, I am not using any auth mechanism, It's being used internally when I try to upload any media to my bucket.

**Comment by cbommas** [comment]
@shashank-rps 

Can you share the code snippet for where you are creating the credentialsProvider object that you are passing into the AWSServiceConfiguration

_AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionAPSoutheast1 credentialsProvider:**credentialsProvider**];_

**Comment by shashank-rps** [comment]
**Here is the full configuration code.**

```
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:AMAZON_POOL_ID];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionAPSoutheast1 credentialsProvider:credentialsProvider];
AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;  
AWSS3TransferUtilityConfiguration *transferConfig = [[AWSS3TransferUtilityConfiguration alloc] init];
transferConfig.accelerateModeEnabled = YES;
transferConfig.bucket = AMAZON_UPLOAD_BUCKETNAME;
[AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:configuration transferUtilityConfiguration:transferConfig forKey:kUSEast1S3TransferUtility];
```

**Comment by cbommas** [comment]
@shashank-rps 

Thank you. Everything looks good in the code snippet. Can you post logs that contain the error you are seeing?

Also, are you setting up acceleration on the bucket programmatically or are you using the AWS console to do it? Setting accelerateModeEnabled = YES in the transfer utility config just tells the TransferUtility that the bucket has acceleration turned on; it doesn't change the actual bucket configuration on S3.

**Comment by shashank-rps** [comment]
I am not seeing any error logs in the console, it's just that neither I am getting any progress updates, nor the code hits failure or success blocks.

I have enabled acceleration on the actual bucket as well from the console at our backend.

You can easily reproduce the issue by following the steps I mentioned above.

**Comment by cbommas** [comment]
@shashank-rps 

I have tried to reproduce the error you are seeing, but haven't been able to. It is difficult to debug this without log information. Can you post the code where you are doing the transfer to see if that can shed some light on this issue?

**Comment by cbommas** [comment]
@shashank-rps 

Closing this out as I haven't heard back. Hopefully this means that you have been able to resolve your problem. Please feel free to reopen this thread if you are still facing issues.
