### ISSUE TITLE
AuthUI user pool sign up UI configurable attribute input fields

### ISSUE THREAD

**Issue by EthanLozano** [aws/aws-sdk-ios#982]
* What service are you using?
AuthUI
* In what version of SDK are you facing the problem?
2.6.23
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

The user pool sign up UI has [four hard-coded fields ("User Name", "Password", "Email", and "Phone Number")](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSUserPoolsSignIn/UserPoolsUI/AWSUserPoolSignUpViewController.m#L70-L73).

My user pool only requires a User Name and Password, so the "email" and "phone number" fields are optional fields. I would like the sign up process to be as easy as possible so that that I don't scare away users. At the very least, it would be nice if I could hide optional fields by setting configuration in [AWSAuthUIConfiguration](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIConfiguration.m). Ideally, the ui queries the required attributes from my user pool and dynamically generates inputs for all required attributes.

**Comment by minbi** [comment]
Hi @EthanLozano ,

Thank you for reporting these issues. We will reply back here.
