### ISSUE TITLE
AuthUI user pool sign in UI configurable attribute field labels

### ISSUE THREAD

**Issue by EthanLozano** [aws/aws-sdk-ios#983]
* What service are you using?
AuthUI
* In what version of SDK are you facing the problem?
2.6.23
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

The Sign In View controller [hardcodes "User Name"](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSAuthUI/AWSSignInViewController.m#L194) for the username label. However, my user pool uses email addresses rather than user names, so I would prefer if this label said "email" instead to avoid confusing my users. At least, it would be nice if you could change the label as a configuration in [AWSAuthUIConfiguration](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIConfiguration.m). Ideally, the UI would dynamically set the label by querying the User Pool attributes and determining which type of username is appropriate.

**Comment by minbi** [comment]
Hi @EthanLozano ,

Thank you for reporting these issues. We will reply back here.
