### ISSUE TITLE
Enable inventory on bucket using API (SDK for iOS)

### ISSUE THREAD

**Issue by trondkr** [aws/aws-sdk-ios#985]
I am trying to enable inventory configuration programmatically on a bucket using AWS SDK iOS 2.6.21. I am setting up my credentials (secret key and access id) for the correct region the bucket is in (I have tested that this works as I am able to get bucket versioning etc.). But when I try to enable inventory configuration on the bucket I get a problem with error message:

`Finished put bucket inventory (null) - error Error Domain=com.amazonaws.AWSServiceErrorDomain Code=3 "(null)" UserInfo={Message=The request signature we calculated does not match the signature you provided. Check your key and signing method.,`

My guess is that I am missing a required parameter in the configuration request, but I am unable to figure out which one. I also don´t find any examples as for how to do this so I am hoping someone could look at my Objective-C code and direct me to what I am missing. Thanks. Cheers, Trond

`-(AWSTask*) putBucketInventory:(SDS3Bucket*)bucketObject region:(NSString*) region{

    AWSS3PutBucketInventoryConfigurationRequest *putBucketInventoryRequest = [AWSS3PutBucketInventoryConfigurationRequest new];
    putBucketInventoryRequest.bucket = bucketObject.name;
    putBucketInventoryRequest.identifier=@"TestInventory";
    putBucketInventoryRequest.inventoryConfiguration=[AWSS3InventoryConfiguration new];
    putBucketInventoryRequest.inventoryConfiguration.isEnabled=@(YES);
    putBucketInventoryRequest.inventoryConfiguration.identifier=@"TestInventory";
    
    AWSS3InventoryFilter *filter=[AWSS3InventoryFilter new];
    filter.prefix=@"";
    putBucketInventoryRequest.inventoryConfiguration.filter=filter;
    
    AWSS3InventoryS3BucketDestination *s3dest=[AWSS3InventoryS3BucketDestination new];
    AWSS3InventoryEncryption *enc = [AWSS3InventoryEncryption new];
    
    AWSS3SSES3 *sses3=[AWSS3SSES3 new];
    enc.SSES3=sses3;
    s3dest.encryption=enc;
    
    s3dest.accountId=bucketObject.owner.identifier;
    s3dest.bucket=[NSString stringWithFormat:@"arn:aws:s3:::%@",bucketObject.name];
    s3dest.format=AWSS3InventoryFormatCsv;
    s3dest.prefix=@"inventory";
    
    AWSS3InventoryDestination *destination=[AWSS3InventoryDestination new];
    destination.s3BucketDestination=s3dest;

    putBucketInventoryRequest.inventoryConfiguration.destination=destination;
    AWSS3InventorySchedule *schedule=[AWSS3InventorySchedule new];
    schedule.frequency=AWSS3InventoryFrequencyDaily;
    putBucketInventoryRequest.inventoryConfiguration.schedule=schedule;
      putBucketInventoryRequest.inventoryConfiguration.includedObjectVersions=AWSS3InventoryIncludedObjectVersionsCurrent;
    putBucketInventoryRequest.inventoryConfiguration.optionalFields=@[@"Size",
                                                                      @"LastModifiedDate",
                                                                      @"StorageClass",
                                                                      @"ETag",
                                                                      @"IsMultipartUploaded",
                                                                      @"ReplicationStatus",
                                                                      @"EncryptionStatus"];
    NSLog(@"Putting inventory");
    
    return [[[AWSS3 S3ForKey:region] putBucketInventoryConfiguration:putBucketInventoryRequest] continueWithSuccessBlock:^id(AWSTask *task) {
        if(task.error != nil){
            NSLog(@"The request failed. error: [%@]", task.error);
        }
        
        NSLog(@"INVENTORY PUT %@",task.result);
        
        return task;
    }];
}`

* What service are you using?
S3
* In what version of SDK are you facing the problem?
AWS SDK iOS v2.6.21
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

**Comment by cbommas** [comment]
@trondkr 

version 2.6.25 ( released on 7/18) has the bug fix. Can you upgrade to the latest and let us know how it goes?

**Comment by cbommas** [comment]
@trondkr 

I will go ahead and close this out as you may be all set. Please feel free to reopen if you are still facing issues.

**Comment by trondkr** [comment]
@cbommas This works perfectly now. I see that if the XML contains blank fields e.g. `AWSS3InventoryFilter *filter=[AWSS3InventoryFilter new];
    filter.prefix=@"";
   putBucketInventoryRequest.inventoryConfiguration.filter=filter;` it will still fail, but perhaps this is intended? Still, avoiding the empty fields it works well. Thanks
