### ISSUE TITLE
TransferUtility Random Error AWSS3TransferUtilityErrorDomain Code=2 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by dawn360** [aws/aws-sdk-ios#989]
I am getting a random error behavior when uploading images or videos. Occasionally I get this error for no reason. Then it will work and fail after a couple more tries. I tried between using the `info.plst` config and config
via code to make sure the region was set right but the issue still persists.

    Failed with error: Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "
    (null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Wed, 11 Jul 
    2018 21:50:21 GMT, x-amz-request-id=997046661220FE40,
    ....&X-Amz-SignedHeaders=content-type%3Bhost%3Bx-amz-acl%3Bx-
    amz-meta-description%3Bx-amz-meta-id%3Bx-amz-meta-
    push_notfication%3Bx-amz-meta-title%3Bx-amz-meta-total_items%3Bx-amz-meta-type%3Bx-amz-meta-upload_id%3Bx-amz-meta-
    user_token\ncontent-type:image/jpeg\nhost:uploadBucketName.s3.amazonaws.com\.....
    Code = SignatureDoesNotMatch;
    HostId = "+V2PadRBqGEiSjRIF+s/LkenwPeKMoxRVj0NOwK5tR7hjZ8k9ZBJvZlsmuAzSViMuj7TO1n5xek=";
    Message = "The request signature we calculated does not match the signature you provided. Check your key and signing method.";
    RequestId = 997046661220FE40;
    SignatureProvided = 65a3b5cbb3fb67b0538c09587c6cd4f2f1ab86bc158b9d2293952c29f7f387a0;
    StringToSign = "AWS4-HMAC-SHA256\n20180711T214914Z\n20180711/us-east-1/s3/aws4_request\nc387de0c4a47af018370380c5dab89abea7995098dfad0cb06a90f9492c32786";
    
Notice the host does not contain the region. i wonder if am missing something.

Here's the code in my Appdelegate
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1,
                                                                identityPoolId:"us-east-1:xxxxx")

        let configuration = AWSServiceConfiguration(
            region: .USEast1,
            credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        let tuConf = AWSS3TransferUtilityConfiguration()
        tuConf.bucket = "xxxxxx"
        tuConf.retryLimit = 3
        AWSS3TransferUtility.register(with: configuration!,transferUtilityConfiguration: tuConf, forKey: "Default")

An example upload in my code

		let transferUtility = AWSS3TransferUtility.s3TransferUtility(forKey: "Default")
           transferUtility.uploadData (
            mediaData,
            key: S3UploadKeyName,
            contentType: mediaType,
            expression: expression,
            completionHandler: completionHandler).continueWith { (task) -> AnyObject? in
                if let error = task.error {
                    print("UPLOAD Error: \(error.localizedDescription)")
          
i also tried the `info.plst` config, but issue still persist
here is my config 

		<key>AWS</key>
	<dict>
		<key>CredentialsProvider</key>
		<dict>
			<key>CognitoIdentity</key>
			<dict>
				<key>Default</key>
				<dict>
					<key>PoolId</key>
					<string>us-east-1:xxxxx</string>
					<key>Region</key>
					<string>us-east-1</string>
				</dict>
			</dict>
		</dict>
		<key>S3TransferUtility</key>
		<dict>
			<key>Default</key>
			<dict>
				<key>Bucket</key>
				<string>someBucketName</string>
				<key>Region</key>
				<string>us-east-1</string>
			</dict>
		</dict>
	</dict>

* What service are you using?
AWSS3TransferUtility
* In what version of SDK are you facing the problem?
2.6.23
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

**Comment by cbommas** [comment]
@dawn360 

sorry to hear that you are running into issues. A few questions that will help narrow this down 
- have you been able to identify any patterns in the bucket names and key names where the errors are occurring?
- have you seen it fail intermittently for the same bucket and key combination? If so, could you share two logs 1) when the error occurs 2) when the transfer happens successfully
- are you pausing and resuming the transfer?

**Comment by dawn360** [comment]
Thanks for the reply, I have been comparing the verbose log for both successes and failed requests, but I can seem to spot anything out of the ordinary.  But, I suspect this has something to do with the 
custom headers I am passing.

    content-type:video/mp4
	host:someBucket.s3.amazonaws.com
	x-amz-acl:public-read
	x-amz-meta-category_id:0
	x-amz-meta-description:Stringofmaxlen50
	x-amz-meta-facebook_post:0
	x-amz-meta-id:Stringofmaxlen10
	x-amz-meta-push_notfication:0
	x-amz-meta-title:sometitle
	x-amz-meta-total_items:1
	x-amz-meta-twitter_post:0
	x-amz-meta-type:video
	x-amz-meta-upload_id:363uk2Tu
	x-amz-meta-user_token:JWTToken

Could any of these header keys cause an issue?

**Comment by cbommas** [comment]
@dawn360 

This could be related to how the content-type is being passed in. In my testing, I was able to reproduce the signing error consistently when I set the contentType as a header key in addition to specifying it as a parameter in the uploadData call. 

     uploadExpression.setValue("video/mp4", forRequestHeader:"content-type")

I did not have any issues with the other header keys. If you are setting the contentType as a header key, can you exclude it and see if that resolves the issue for you?

Please let me know one way or the other.

**Comment by cbommas** [comment]
@dawn360 
I will go ahead and close this as I haven't heard back from. Please feel free to reopen if the problem still persists.
