### ISSUE TITLE
Cannot Archive: AWS framework was built without full bitcode

### ISSUE THREAD

**Issue by ntewinkel** [aws/aws-sdk-ios#991]
Xcode 9.4.1, using Swift.
AWS-IOS-SDK-2.6.19

I rebuilt your Amazon IoT Sample using the Frameworks steps as described here:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-ios-sdk-setup.html

The Swift IoT Sample is from here:
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift/

My main app is built without pods, so I chose to build using direct frameworks import (as per the steps I mentioned above).
I can provide the rebuilt IoT Sample I'm testing with.

When I try to "Archive", I get error:
`ld: bitcode bundle could not be generated because '/Users/nicotewinkel/Desktop/MQTT_AWS_test/frameworks/AWSMobileClient.framework/AWSMobileClient' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/nicotewinkel/Desktop/MQTT_AWS_test/frameworks/AWSMobileClient.framework/AWSMobileClient' for architecture arm64
`

The same kind of error happens for the other frameworks if I narrow down to what is required.

This seems to be a regression of issue #301 
"Cannot archive project with AWSCore when Bitcode is ENABLED"

Is there anything I can do to work around this issue? (or is the issue due to my project settings?)

edit: same result with aws-ios-sdk-2.6.23

**Comment by kvasukib** [comment]
Thank you @ntewinkel for reporting to us. Sorry for the inconvenience caused. Currently, AWSMobileClient and AWS Auth SDK frameworks lack full bitcode support. We are looking into it.

**Comment by ntewinkel** [comment]
Hi @kvasukib, it looks like this has been fixed in 2.6.26 - Thank you!
(I'll let you close, in case there's more details you need to track)

**Comment by kvasukib** [comment]
Closing this for now. Please feel free to re-open the issue if it persists.

**Comment by ntewinkel** [comment]
Hi @kvasukib, can we re-open this case?

It looks like the frameworks are now built with bitcode, which is a step in the right direction, and allows archiving, but they were built with bitcode that does not apply to iPhones and iPads, which means I cannot submit the binary to Apple for TestFlight or release.
A simple test for this is to archive the project as I described in the original post, and then from the Organizer use the "Validate..." option.

The bitcode appears to be set to X86 devices, but iOS devices have Arm chips. (Simulator runs on Mac with X86, but doesn't need the bitcode).

May I please request a rebuild with the proper settings for iOS?
My settings are "arm64 armv7 armv7s", which I believe to be the most up-to-date, and is what newly created apps default to, but you may want to verify that with Apple.

Thanks!
-Nico
