### ISSUE TITLE
How to setup an app with Cognito UserPools and calls to an authenticated API Gateway ?

### ISSUE THREAD

**Issue by nashfive** [aws/aws-sdk-ios#997]
Hi,
I have trouble to figure out how to setup an iOS app that would use a Cognito User Pool to sign-up users and then make calls to an authenticated API Gateway ?
I tried to follow the AWS Mobile (via Mobile Hub) tutorials but it doesn't provide sample code to call an API Gateway. In the same manner, the Cognito documentation doesn't use AWSMobileClient nor provide a way to setup for calling API Gateway, and, again, the APIGateway documentation doesn't use AWSMobileClient nor provide a way to setup authentication via Cognito user pools...

Can someone provide some knowledge on how to bootstrap an iOS app with AWSMobileClient, a Cognito userpool-based authentication and accessing APIGateway endpoints in an authenticated manner?

Here is my current code in my app delegate that I try to setup without using the AWSMobileClient : 
```swift
let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: CLIENT_ID, clientSecret: CLIENT_SECRET, poolId: POOL_ID)
let userPoolServiceConf = AWSServiceConfiguration(region: REGION, credentialsProvider: nil)
AWSCognitoIdentityUserPool.register(with: userPoolServiceConf, userPoolConfiguration: userPoolConfiguration, forKey: USER_POOL_KEY)
let pool = AWSCognitoIdentityUserPool(forKey: USER_POOL_KEY)
pool.delegate = self

let credentialsProvider = AWSCognitoCredentialsProvider(regionType: REGION, identityPoolId: IDENTITY_POOL_ID, identityProviderManager: pool)
let defaultServiceConfiguration = AWSServiceConfiguration(region: REGION, credentialsProvider: credentialsProvider)
AWSServiceManager.default().defaultServiceConfiguration = defaultServiceConfiguration
```
Then how to do a call to my API Gateway ?

**Comment by behrooziAWS** [comment]
Just confirming you want to use the user pool id/access token to call your api gateway methods and not sigv4 correct?

**Comment by nashfive** [comment]
@behrooziAWS I think I need to use sigv4 because my API is configured to be private. 
It has an Authorizer that uses a Cognito User Pool.

**Comment by nashfive** [comment]
@behrooziAWS I can do a signup & a signin, but I can't find a way to setup a API Gateway client that uses the access token I received. 
I am not using the AWSMobileClient generated by the MobileHub. I tried but ran into problems too so I decided to kind of build my own stack in order to understand what it does under the hood.

**Comment by behrooziAWS** [comment]
It sounds like you don't want sigv4, because that would require another step to exchange the user pools token for aws credentials.  Follow the steps here: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-use-sdk-ios-objc.html except instead of configuring the credentials provider: 

```
AWSCognitoCredentialsProvider *creds = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:your_cognito_pool_id];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:creds];
AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

Modify the generated client to set the "Authorization" header to the result of your user's sessions idToken for each api call.

**Comment by nashfive** [comment]
@behrooziAWS thanks for your help. I will try it.
In the meantime, how come the generated mobile hub client signs my API request calls with sigv4 ? Is it coming from the way my user pool/identity pool is configured or is it coming out of the box from the generated client ?

**Comment by nashfive** [comment]
I managed to sign-in on an user pool without federated identities and by only using the AWSCognitoIdentityProvider SDK. 
Thanks for your help!
