### ISSUE TITLE
AWSCognitoAuth sign-out followed by sign-in broken - SFSafariViewController remains

### ISSUE THREAD

**Issue by EthanLozano** [aws/aws-sdk-ios#998]
* What service are you using?
AWSCognitoAuth
* In what version of SDK are you facing the problem?
2.6.24
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

        self.auth.signOut { error in
            if error == nil {
                self.auth.getSession { (session, error) in
                    if error == nil {
                        print("Success!")
                    } else {
                        print("Sign-In failure: " + ((error! as NSError).userInfo["error"] as! String))
                    }
                }
            } else {
                print("Sign-Out failure: " + ((error! as NSError).userInfo["error"] as! String))
            }
        }

Suggestion: Reimplement the [signOutTapped method](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoAuth-Sample/Swift/CognitoAuthSample/ViewController.swift#L117) with the above snippet for a quick repro.

Prompting the user to sign-in immediately after sign-out is a [common pattern](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-user-sign-in-sign-out.html). However, the code above fails with `Sign-In failure: Loading page failed`. Subsequently, the user is able to sign-in, but the sign-in modal does not dismiss itself as it should.

Suggestion: Place breakpoints on the following lines:
1. launchSignInVC - [`self.svc = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:url] entersReaderIfAvailable:NO];`](https://github.com/aws/aws-sdk-ios/blob/2.6.24/AWSCognitoAuth/AWSCognitoAuth.m#L226)
2. completeSignOut - [`self.signOutBlock(error);`](https://github.com/aws/aws-sdk-ios/blob/2.6.24/AWSCognitoAuth/AWSCognitoAuth.m#L336)
3. signOutInternal - [`self.svc = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:url] entersReaderIfAvailable:NO];`](https://github.com/aws/aws-sdk-ios/blob/2.6.24/AWSCognitoAuth/AWSCognitoAuth.m#L367)
4. dismissSafariVC - [`if(self.svc){`](https://github.com/aws/aws-sdk-ios/blob/2.6.24/AWSCognitoAuth/AWSCognitoAuth.m#L588)
5. dismissSafariVC - [`self.svc = nil;`](https://github.com/aws/aws-sdk-ios/blob/2.6.24/AWSCognitoAuth/AWSCognitoAuth.m#L591)

Running the above code with the given breakpoints results in the following order:
1. signOutInternal (set svc)
2. completeSignOut (call user's signOutBlock)
3. dismissSafariVC (check svc)
4. launchSignInVC (set svc)
5. print "Sign-In failure"
6. dismissSafariVC (check svc)
7. dismissSafariVC (unset svc)

As you can see, the svc variable gets corrupted at step 4. Also, the modal isn't dismissed completely until step 7, well after the user's code is executed in step 2. So, here is the order that would prevent corruption and would avoid the annoying presence of a modal/SFSafariViewController when the user's completeSignOut code is executed:
1. signOutInternal (set svc)
2. dismissSafariVC (check svc) [previously step 3]
3. dismissSafariVC (unset svc) [previously step 7]
4. completeSignOut (call user's signOutBlock) [previously step 2]
5. launchSignInVC (set svc) [previously step 4]
6. dismissSafariVC (check svc) [new]
7. dismissSafariVC (unset svc) [new]
8. completeGetSession (call user's getSessionBlock) [new]
9. print "Success" [new]

Also, the implementation seems a little more complicated than necessary: I believe `dismissSafariVC` is only ever called from the main thread, so its asynchronous main thread call (i.e. `dispatch_async(dispatch_get_main_queue()`) might be unnecessary.

**Comment by kvasukib** [comment]
Thank you @EthanLozano for the analysis. We are looking at the pull request submitted.

**Comment by EthanLozano** [comment]
Are there any updates here? My app periodically crashes after signing out, and I'm pretty sure the crashes are related to this issue since the user's sign-out block is called when the safari VC is still presented modally:
```
2018-08-03 16:28:02.580272-0500 [redacted][41473:988722] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <[redacted]ViewController: 0x7faa3283f200>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010906a1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000104830031 objc_exception_throw + 48
	2   UIKit                               0x0000000105bb0a20 -[UIViewController _presentViewController:withAnimationController:completion:] + 5142
	3   UIKit                               0x0000000105bb33e3 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke_2 + 70
	4   UIKit                               0x0000000105ab9b6a +[UIView(Animation) performWithoutAnimation:] + 90
	5   UIKit                               0x0000000105bb3337 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 212
	6   UIKit                               0x0000000106756a29 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 294
	7   UIKit                               0x00000001067526d5 -[_UIViewControllerTransitionContext _runAlongsideCompletions] + 132
	8   UIKit                               0x00000001067523c4 -[_UIViewControllerTransitionContext completeTransition:] + 118
	9   UIKit                               0x0000000105a044b3 _runAfterCACommitDeferredBlocks + 318
	10  UIKit                               0x00000001059f371e _cleanUpAfterCAFlushAndRunDeferredBlocks + 388
	11  UIKit                               0x0000000105a21ea5 _afterCACommitHandler + 137
	12  CoreFoundation                      0x000000010900c607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	13  CoreFoundation                      0x000000010900c55e __CFRunLoopDoObservers + 430
	14  CoreFoundation                      0x0000000108ff0b81 __CFRunLoopRun + 1537
	15  CoreFoundation                      0x0000000108ff030b CFRunLoopRunSpecific + 635
	16  GraphicsServices                    0x000000010c41ca73 GSEventRunModal + 62
	17  UIKit                               0x00000001059f9057 UIApplicationMain + 159
	18  [redacted]                          0x0000000103aa2577 main + 55
	19  libdyld.dylib                       0x000000010ac40955 start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
```

**Comment by EthanLozano** [comment]
ping
