### ISSUE TITLE
AWSCognitoIdentityUserPool isn't initialized

### ISSUE THREAD

**Issue by nilotic** [aws/aws-sdk-ios#999]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
 AWSCognitoIdentityUserPool

* In what version of SDK are you facing the problem?
AWSCognito (2.6.25)
AWSCognitoAuth (2.6.25)
AWSCognitoIdentityProvider (2.6.25)
AWSCognitoIdentityProviderASF (1.0.1)
AWSCore (2.6.25)

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific iOS version?
no

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

` 
// MARK: Pirvate
    private let userPool                      = AWSCognitoIdentityUserPool(forKey: Cognito.userPoolKey)
    private let cognitoPasswordAuthentication = CognitoPasswordAuthentication()
    private let cognitoRememberDevice         = CognitoRememberDevice()
`

When I initialize the AWSCognitoIdentityUserPool, 
Always, the instance is nil. (AWSCongnitoIdentityUserPool) 0x00000000000000

I tested by the below.
`
 DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
            self.userPool.delegate = self
        }
`

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you @nilotic for reporting to us. Sorry for the inconvenience caused. 

Can you post the complete stacktrace? 

Also, can you post the code snippet of how do you create the UserPool object? There are two ways to create this:

1) [Method-1](https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.h#L62)

2) [Method-2](https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.h#L65)

**Comment by nilotic** [comment]
Hi @kvasukib. 
I uploaded full project in https://github.com/nilotic/CognitoTest

You can check the problem 
UserDataManager.swift > line 127( userPool.delegate = self )  > check the userPool memory address

<img width="2624" alt="screen shot 2018-07-20 at 9 44 13 am" src="https://user-images.githubusercontent.com/4756783/42977526-9fef89d2-8c02-11e8-86be-e14fb0fc1976.png">

Thank you  in advance for your support.

**Comment by nilotic** [comment]
Also, you can create a simple project and check the problem
1. Create new project
2. Install Pod
`platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def pods
pod 'Fabric'
pod 'Crashlytics'
pod 'AWSCognito'
pod 'AWSCognitoAuth'
pod 'AWSCognitoIdentityProvider'
end


target 'CocoaTest' do
pods
end
`
3. Initialize the AWSCognitoIdentityUserPool

<img width="2253" alt="screen shot 2018-07-20 at 10 13 45 am" src="https://user-images.githubusercontent.com/4756783/42978045-aebbfe8e-8c05-11e8-8e11-814d171ec85d.png">

**Comment by nilotic** [comment]
I found the reason why the AWSCognitoIdentityUserPool isn't initialized

I think, before initializing the AWSCognitoIdentityUserPool
Configurations Must be registered (AWSServiceConfiguration, AWSCognitoIdentityUserPoolConfiguration)


Like this 
` private lazy var userPool: AWSCognitoIdentityUserPool = {
        let serviceConfiguration = AWSServiceConfiguration(region: Cognito.userPoolRegion, credentialsProvider: nil)
        let poolConfiguration    = AWSCognitoIdentityUserPoolConfiguration(clientId: Cognito.userPoolAppClientID, clientSecret: nil, poolId: Cognito.userPoolID)
        AWSCognitoIdentityUserPool.register(with: serviceConfiguration, userPoolConfiguration: poolConfiguration, forKey: Cognito.userPoolKey)
        
        let userPool = AWSCognitoIdentityUserPool(forKey: Cognito.userPoolKey)
        userPool.delegate = self
        return userPool
    }()`

**Comment by kvasukib** [comment]
Thank you @nilotic  for confirming. You can take a look at the tests here for reference: https://github.com/aws/aws-sdk-ios/blob/a78f49b076e306f2400478ded6002a4056db7f32/AWSCognitoIdentityProviderTests/AWSCognitoIdentityProviderTests.m#L166
